packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.sass
fix #10821
fix #10821 
fix #10821 
Visually using [reproduction](https://codepen.io/Leespiker/pen/BaNrpZW)
=> fix(VNavigationDrawer): change closed navigation drawer visibility

packages/docs/src/snippets/bash/yarn_startup_vuetify.txt
Added the localhost port to the docs page for contributing so that users know where to go.
I personally did not know the port number when I had properly built the dev docs, and so I wanted to make it easier for future people who build dev environment. 
Looks correct as of my dev docs.
=> docs: add localhost port for dev environment setup

packages/vuetify/src/components/VSelect/VSelect.ts, packages/vuetify/src/components/VSelect/__tests__/VSelect4.spec.ts
Emit click event in v-select and add a test for it.
fixes #10839
Bugfix.
fixes #10839
unit
<details>
```vue
<template>
<v-container>
<v-select @change="doSomething('change')" @click="doSomething('click')" :items=items></v-select>
</v-container>
</template>
<script>
data: () => ({
items: ['one', 'two']
}),
methods: {
doSomething(eventType) {
console.log(eventType)
}
}
}
</script>
```
</details>
=> fix(VSelect): emit click event

packages/vuetify/src/components/VSelect/VSelect.sass
fix #10538
fixes #10538 
visually
<details>
```vue
<template>
v-model="contacts"
label="Номера телефона"
placeholder="Укажите контактные номера телефонов для объекта Укажите контактные номера телефонов для объекта"
:items="options"
:item-value="'user_id'"
:item-text="'phone'"
multiple
return-object
prefix="+7"
/>
</v-container>
</template>
<script>
data: () => ({
contacts: '',
options: [],
}),
}
</script>
```
</details>
=> fix(VAutocomplete): prefix overlap with placeholder

packages/vuetify/src/components/VSlider/VSlider.sass
eventual inputs in append/prepend slots should not be affected
closes #10684
manually in playground
<details>
```vue
<template>
<v-slider v-model="slider" class="align-center" :max="max" :min="min" hide-details readonly>
<template v-slot:append>
<v-text-field v-model="slider" label="Max" single-line hide-details type="number" class="max-storage" />
</template>
</v-slider>
</template>
<script>
data () {
return {
min: 0,
max: 100,
slider: 20,
range: [0, 100],
}
},
}
</script>
```
</details>
=> fix(VSlider): readonly should apply only to slider control

packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts
https://github.com/vuetifyjs/vuetify/issues/10758
playground
<details>
```vue
<template>
<div>
hide-overlay
temporary
value="true">
Always active
<div style="min-height:2000px"></div>
</div>
</template>
```
</details>
=> fix(VNavigationDrawer): scrolling in temporary hide-overlay

packages/docs/src/components/getting-started/Team.vue
<details>
```vue
```
</details>
=> docs: added core member

packages/docs/src/views/home/components/Tidelift.vue
Updates the Tidelift URL on the homepage.
The homepage URL was pointing to an old Tidelift URL and was being redirected to the new one. It also wasn't being tracked correctly in the Tidelift system.
N/A
N/A
=> docs: Update Tidelift URL on homepage

packages/vuetify/src/components/VData/VData.ts, packages/vuetify/src/components/VData/__tests__/VData.spec.ts, packages/vuetify/src/components/VData/__tests__/__snapshots__/VData.spec.ts.snap, packages/vuetify/src/components/VDataTable/VDataTable.ts, packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts, packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap, packages/vuetify/src/util/helpers.ts, packages/vuetify/types/index.d.ts
closes #10627
manually in playground, unit test
<details>
```vue
<template>
<div>
<v-data-table
show-group-by
:group-desc="sortDescending"
>
<template v-slot:top>
<v-switch v-model="sortDescending" :label="`group-desc: ${sortDescending.toString()}`" class="pa-3"></v-switch>
</template>
</div>
</template>
<script>
data () {
return {
sortDescending: false,
headers: [
{
align: 'left',
value: 'name',
},
],
desserts: [
{
calories: 159,
fat: 6.0, …
```
=> fix(VDataTable): groups should be sorted according to groupDesc

packages/vuetify/src/components/VProgressLinear/VProgressLinear.sass
fix #10852
Repeat striped image horizontally and vertically instead of just horizontally
visually
<details>
```vue
<template>
<div id="app">
<v-app>
<v-container>
striped
height="60"
value="50"
></v-progress-linear>
</v-container>
</v-app>
</div>
</template>
<script>
export default {}
</script>
```
</details>
=> fix(VProgressLinear): use both horizontal and vertical repeat

packages/vuetify/src/components/VImg/VImg.ts, packages/vuetify/src/directives/intersect/index.ts
fixes #10848
<details>
```vue
<template>
<v-app>
<v-container>
<v-row>
<v-col>
<p v-for="i in 10" :key="i">
Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic, vitae fugit corrupti impedit quod sit sapiente
placeat dolore voluptates, officia possimus a minima, eveniet quam illum magni nisi numquam quae.
Et placeat doloremque praesentium corporis voluptate architecto dolorem quo natus repudiandae maiores
sapiente, minima iure laborum ea adipisci cum rem sed! Debitis quis impedit id! Quisquam aliquid repellendus
vitae earum!
Officiis laudantium est maiores nostrum neque molestiae atque quia dicta incidunt, magnam omnis a quo
accusantium nobis minus excepturi voluptatum assumenda totam animi corporis repellat? Minima nulla quos
provident pariatur?
</p>
<v-img …
```
=> fix(VImg): correctly pass options to intersect directive

packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts, packages/vuetify/src/components/VNavigationDrawer/__tests__/VNavigationDrawer.spec.ts
fixes #10862
Before the application width used to depend on `isMouseover` due to which the application's width was not calculated properly when `isMouseover` is active.
<details>
```vue
<template>
<div id="app">
<v-navigation-drawer app :mini-variant="miniVariant" v-model="drawer" :color="color" :expand-on-hover="expandOnHover" :right="right" :src="bg" absolute dark>
<v-list dense nav class="py-0">
<v-list-item two-line>
<v-list-item-avatar>
</v-list-item-avatar>
<v-list-item-title>Application</v-list-item-title>
<v-list-item-subtitle>Subtext</v-list-item-subtitle>
</v-list-item>
<v-list-item v-for="item in items" :key="item.title" link>
<v-icon>{{ item.icon …
```
=> 10862 fix application width in VNavigationDrawer

package.json, packages/docs/babel.config.js, packages/docs/package.json, packages/vuetify/babel.config.js, packages/vuetify/package.json, yarn.lock
Ability to use new ts features
```bash
yarn test directives
yarn test effects
yarn test framework
yarn test locale
yarn test services
yarn test util
```
```vue
import { h, defineComponent } from 'vue'
setup (props) {
const foo = { bar: 1 }
return () => h('div', [
foo?.bar?.baz,
foo.noMethod?.(),
foo.fizz ?? 'ok',
])
},
})
</script>
```
=> feat: typescript 3.8, nullish coalescing, optional chaining

packages/docs/src/lang/fr-FR/mixins/Colorable.json
fixed 404 link
<details>
```vue
```
</details>
=> Update Colorable.json, fixes 404 colors link

packages/docs/src/data/pages/components/Combobox.pug, packages/docs/src/lang/en/components/Combobox.json, packages/docs/src/lang/en/components/Selects.json
Added a notice for users to know about combobox's return value 
A notice inside the combobox plus a short notice in item-value prop which explains why combobox always returns the full value provided to it. ie Why item-value has no effect
See #5479
<details>
```vue
```
</details>
=> docs(Combobox): update object alert

packages/vuetify/src/components/VIcon/VIcon.ts, packages/vuetify/src/components/VIcon/__tests__/__snapshots__/VIcon.spec.ts.snap
fixes #10938
Visually
<details>
```vue
<template>
<v-container>
{{ myIcon }}
<v-icon :size="50">mdi-close</v-icon>
<v-icon :size="50">$my-icon</v-icon>
</v-container>
</template>
<script>
}
</script>
```
**Index.js:**
```vue
import Vue from 'vue'
import App from './App'
import Vuetify from 'vuetify'
import * as locales from '../src/locale'
import router from './router'
Vue.config.performance = true
Vue.use(Vuetify)
Vue.component('MyComponent', {
template: `<svg style="fill: currentColor" preserveAspectRatio="xMinYMin meet" viewBox="0 0 1.1 1.1" > <g transform="translate(0.05, 0.05)"> <g> <path d="M0.9999999999988001,0.499999A0.4166666666666667,0.4166666666666667,0,1,0,0.9999999999988001,0.5000009999999999" stroke="#0f0f0f" …
```
=> fix(VIcon): add missing width attribute when rendering svg icons

packages/docs/src/examples/bottom-navigation/simple/shift.vue
The MDI icon was not displaying due to inappropriate naming(music_note).
I have replaced it 'mdi-music-note' to fix it and display icon.
<details>
```vue
```
</details>
=> Changed inappropriate naming of MDI icon to fix icon display issue 

packages/vuetify/src/components/VBtn/VBtn.sass
This PR makes the button hover pseudo-element inherit the border-radius.
#10671
visually
<details>
```vue
<template>
<v-container>
<v-btn outlined style="border-radius: 2em;">text</v-btn>
</v-container>
</template>
<script>
data: () => ({
//
})
}
</script>
<style>
</style>
```
</details>
=> fix(VBtn): make the hover inherit border-radius

packages/vuetify/src/mixins/overlayable/__tests__/overlayable.spec.ts, packages/vuetify/src/mixins/overlayable/index.ts
fix for #9588
playground
https://codepen.io/aleksandrrakov/pen/qBdgYdq
=> fix(overlayable): overlay must be removed if quickly deactivated

packages/docs/src/snippets/js/vuetify_anchor_color.txt
Missing Export of object.
<details>
```vue
```
</details>
=> docs(snippet): add export object

packages/vuetify/src/components/VAppBar/__tests__/__snapshots__/VAppBar.spec.ts.snap, packages/vuetify/src/components/VImg/VImg.sass, packages/vuetify/src/components/VImg/VImg.ts, packages/vuetify/src/components/VImg/__tests__/__snapshots__/VImg.spec.ts.snap
Add Themeable support to `v-img`
It is commonly asked for and quite useful. Currently in order to change text color or propagate theme is difficult for no reason. This makes supporting `dark/light` images convoluted.
```html
<v-img class="text--white">...</v-img>
<v-theme-provider dark>
<v-img>...</v-img>
</v-theme-provider>
```
jest
<details>
```vue
<template>
<div class="ma-12 pa-12">
<v-img
class="black"
dark
>
Hello
</v-img>
</div>
</template>
<script>
}
</script>
```
</details>
=> feat(VImg): add themeable support

packages/vuetify/src/components/VCalendar/mixins/__tests__/calendar-with-events.spec.ts
Systems with 24-hour clock format used to fail the test as the system returns different time value
#10941
Fixes #10941
https://github.com/vuetifyjs/vuetify/issues/10941
<details>
```vue
```
</details>
=> fix(calendar-with-events.spec.ts): fixes test issue with 24-hour systems

package.json, packages/api-generator/package.json, packages/vuetify/dev/index.js, yarn.lock
updated vue to 3.0.0-beta.2
```
// bash
yarn test directives
yarn test effects
yarn test framework
yarn test locale
yarn test services
yarn test util
```
```vue
<template>
<div>foo</div>
<div>bar</div>
</template>
```
=> chore: vue@3.0.0-beta 2

packages/docs/src/data/pages/styles/Text.pug, packages/docs/src/examples/text/decoration.vue, packages/docs/src/lang/en/styles/Text.json, packages/vuetify/src/styles/settings/_utilities.scss
Create new helper classes for **text-decoration**:
```css
.text-decoration-none- *no decoration*
.text-decoration-underline
.text-decoration-overline
.text-decoration-line-through
```
Requested feature. It's quick and easy. Possible that I can avoid the duplicated values, @KaelWD will have to chime in. As far as using *.text-normal* as opposed to *.text-none* is because that value is used currently by the **text-transform** helper classes.
visually
<details>
```vue
<template>
<div class="ma-12 pa-12">
<a
v-for="val in ['normal', 'underline', 'overline', 'line-through']"
:key="val"
href="#"
class="d-block my-4"
:class="`text-${val}`"
v-text="val"
></a>
</div>
</template>
```
</details>
=> feat(framework): create new decoration helper classes

packages/vuetify/src/components/VTextField/VTextField.ts
fixes #5748
<details>
```vue
```
</details>
=> fix(VTextField): Skip value property update if IME composing string

packages/docs/src/data/pages/styles/CssReset.pug, packages/docs/src/lang/en/styles/CssReset.json
=> docs(CssReset): add warning about using native html elements

packages/vuetify/src/components/VCalendar/util/__tests__/events.spec.ts, packages/vuetify/src/components/VCalendar/util/events.ts, packages/vuetify/src/components/VCalendar/util/timestamp.ts
fixes #11159
If a timed event in a day view ended at midnight, it showed up on the next day as an event.
resolves #11159 
visually, unit
<details>
Before the fix Weekly Meeting 1 & 3 would display on the next day.
```vue
<template>
<v-container>
<v-calendar
ref="calendar"
:now="today"
:value="today"
type="week"
></v-calendar>
</v-container>
</template>
<script>
data: () => ({
today: '2019-01-08',
events: [
{
name: 'Weekly Meeting 1',
start: '2019-01-06 23:00',
end: '2019-01-07 00:00',
},
{
name: 'Weekly Meeting 2',
start: '2019-01-06 23:00',
end: '2019-01-07 00:15',
},
{
name: 'Weekly Meeting 3',
start: '2019-01-05 23:00',
end: '2019-01-06 00:00',
},
{
name: 'Weekly Meeting 4',
start: '2019-01-05 23:00',
end: '2019-01-06 00:15',
},
{
name: …
```
=> fix(VCalendar): event ends midnight (#11159)

packages/vuetify/src/components/VTextField/VTextField.ts
See #5748
fixes #11190
<details>
```vue
```
</details>
=> fix(VTextField): Update value on compositionend

package.json, packages/api-generator/package.json, packages/docs/package.json, packages/vuetify/src/components/VCalendar/VCalendarDaily.ts, packages/vuetify/src/components/VCalendar/VCalendarWeekly.ts, packages/vuetify/src/components/VDataTable/VDataTableHeaderMobile.ts, packages/vuetify/src/components/VDatePicker/VDatePickerHeader.ts, packages/vuetify/src/components/VList/VListItem.ts, yarn.lock
=> fix: don't use nativeOn on native elements

packages/vuetify/src/components/VSelect/VSelect.ts, packages/vuetify/src/components/VSelect/__tests__/VSelect4.spec.ts
This PR blocks any keydown action when readonly prop is set to true.
#11164
visually
<details>
```vue
<template>
<v-container>
<v-select
:items="items"
readonly
label="Read-only"
></v-select>
</v-container>
</template>
<script>
data: () => ({
items: ['Foo', 'Bar', 'Fizz', 'Buzz'],
})
}
</script>
```
</details>
=> fix(VSelect): disable arrows on readonly select

packages/vuetify/src/components/VAppBar/VAppBar.ts, packages/vuetify/src/components/VAppBar/__tests__/VAppBar.spec.ts
In Safari on iOS, `VAppBar` sometimes disappears when scrolling to the
top and in negative territory.
Fixes #9993
The app bar disappears when scrolling bounces at the top in Safari on iOS.
The app bar persists and survives the scroll bounce.
- Manual
- Unit test
<details>
```vue
<template>
<div>
<v-app-bar
scroll-threshold="100"
color="indigo darken-2"
hide-on-scroll
app
dark
>
<v-app-bar-nav-icon></v-app-bar-nav-icon>
<v-toolbar-title>Title</v-toolbar-title>
<v-btn icon>
<v-icon>mdi-magnify</v-icon>
</v-btn>
<v-btn icon>
<v-icon>mdi-heart</v-icon>
</v-btn>
<v-btn icon>
<v-icon>mdi-dots-vertical</v-icon>
</v-btn>
</v-app-bar>
<div style="height: 3000px">Fizz</div>
</div>
</template>
<script>
data: () => ({
//
}),
}
</script>
```
</details>
=> fix(VAppBar): ensure bar visibility when hide-on-scroll (#9993)

packages/vuetify/src/components/VTabs/VTabs.sass
Make buttons's color inside a tab follow tab state and color.
fixes #11171
visually
<details>
```vue
<template>
<v-container>
<v-tabs>
<v-tab>Tab One<v-btn icon><v-icon>mdi-close</v-icon></v-btn></v-tab>
<v-tab>Tab Two<v-btn text>test</v-btn></v-tab>
<v-tab>Tab Three<v-btn icon><v-icon>mdi-close</v-icon></v-btn></v-tab>
</v-tabs>
<v-tabs dark>
<v-tab>Tab One<v-btn icon><v-icon>mdi-close</v-icon></v-btn></v-tab>
<v-tab>Tab Two<v-btn text>test</v-btn></v-tab>
<v-tab>Tab Three<v-btn icon><v-icon>mdi-close</v-icon></v-btn></v-tab>
</v-tabs>
</v-container>
</template>
<script>
data: () => ({
//
}),
}
</script>
```
</details>
=> fix(VTabs): make buttons inside tab inherit current color of the tab

packages/docs/src/examples/data-tables/complex/crud.vue
<details>
```vue
```
</details>
=> example: Using nextTick instead of setTimeout

packages/docs/src/lang/en/customization/Accessibility.json
Typo: `applicatable`->`applicable`
There was a typo in the heading text for Accessibility.json: `applicatable`->`applicable`
To my understanding, `applicatable` isn't a word.
<details>
```vue
```
</details>
=> docs: Typo: `applicatable`->`applicable`

packages/vuetify/src/components/VSlider/VSlider.ts
thumb got recreated when slider was disabled, instead of reused.
closes #11303
playground
<details>
```vue
<template>
<div>
<v-switch label="vertical" v-model="vertical"></v-switch>
<v-switch label="rtl" v-model="$vuetify.rtl"></v-switch>
<v-switch label="disabled ticks" v-model="enabledTicks"></v-switch>
<v-slider max="10" min="0" ticks :disabled="!enabledTicks" v-model="slide" :vertical="vertical"></v-slider>
<v-switch label="disabled no ticks" v-model="enabledNoTicks"></v-switch>
<v-slider max="10" min="0" :disabled="!enabledNoTicks" v-model="slide2"></v-slider>
</div>
</template>
<script>
data: () => ({
enabledNoTicks: true,
enabledTicks: true,
slide: 5,
slide2: 5,
vertical: false,
}),
}
</script>
```
</details>
=> fix(VSlider): fix thumb shifting position when toggling disabled state

packages/docs/src/data/pages/components/ProgressLinear.pug, packages/docs/src/examples/progress-linear/simple/reverse.vue, packages/docs/src/lang/en/components/ProgressLinear.json, packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap, packages/vuetify/src/components/VProgressLinear/VProgressLinear.sass, packages/vuetify/src/components/VProgressLinear/VProgressLinear.ts, packages/vuetify/src/components/VProgressLinear/__tests__/VProgressLinear.spec.ts, packages/vuetify/src/components/VProgressLinear/__tests__/__snapshots__/VProgressLinear.spec.ts.snap
Adds `reverse` prop, fixes `stream` in RTL mode
fixes #11245
unit, playground, docs
<details>
```vue
<template>
<v-container>
<v-checkbox
v-model="reverse"
label="reverse"
/>
<v-checkbox
v-model="$vuetify.rtl"
label="rtl"
/>
class="my-4"
:reverse="reverse"
:value="15"
/>
class="my-4"
:reverse="reverse"
:value="15"
:buffer-value="30"
/>
class="my-4"
:reverse="reverse"
:value="15"
:buffer-value="30"
stream
/>
class="my-4"
:reverse="reverse"
indeterminate
/>
class="my-4"
:reverse="reverse"
indeterminate
query
/>
</v-container>
</template>
<script>
data: () => ({
reverse: false,
})
}
</script>
```
</details>
=> feat(VProgressLinear): `reverse` prop

packages/docs/src/lang/en/components/AppBars.json
A link was pointing to a non-existent url.
<details>
```vue
```
</details>
=> Fixed wrong link to navigation drawers doc

packages/api-generator/src/maps/v-date-picker.js, packages/docs/src/data/pages/components/DatePickers.pug, packages/docs/src/examples/date-pickers/simple/date-button-events.vue, packages/docs/src/lang/en/components/DatePickers.json, packages/vuetify/src/components/VDatePicker/VDatePicker.ts, packages/vuetify/src/components/VDatePicker/VDatePickerYears.ts, packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.date.spec.ts, packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.month.spec.ts, packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.ts, packages/vuetify/src/components/VDatePicker/util/eventHelpers.ts, packages/vuetify/src/components/VDatePicker/util/index.ts
fixes #5598
fixes #4884
<details>
```vue
<template>
<v-date-picker
@contextmenu:month="(value, event) => e('contextmenu (with prevent default)', value, event)"
@mouseenter:year="e('mouseenter', $event)"
@dblclick:date="e('dblclick', $event)"
/>
</template>
<script>
methods: {
e (name, value, event) {
event && event.preventDefault() // for context menu example
console.log(name, value)
}
}
}
</script>
```
</details>
=> feat(VDatePicker): native events on day/month/year

packages/vuetify/src/components/VDataTable/VSimpleTable.sass, packages/vuetify/src/components/VPicker/VPicker.sass, packages/vuetify/src/components/VPicker/_variables.scss
Adds a lot of  `>`
fixes #7384
visually
<details>
```vue
<template>
<v-row>
<v-col>
Standalone
</v-col>
<v-col>
In row and exapanded row
<v-data-table
:expanded="[1]"
:headers="[{ value: 'id' }]"
hide-default-header
:items="[{ id: 1 }]"
>
<template #item.id="foo">
</template>
<template #expanded-item="foo">
<td><v-date-picker /></td>
</template>
</v-col>
<v-col>
In no-data slot
<v-data-table
:headers="[{ value: 'id'}]"
:items="[]"
hide-default-header
>
<template #no-data><v-date-picker /></template>
</v-col>
</v-row>
</template>
```
</details>
=> fix(VDatePicker, VDataTable): incorrect date picker styling when in data table

packages/api-generator/src/maps/v-data-table.js
progress is slot is not scoped
closes #10280
<details>
```vue
<template>
<v-container>
<v-data-table
:server-items-length="totalDesserts"
>
<template #progress>hello</template>
</v-container>
</template>
<script>
data () {
return {
desserts: [],
loading: true,
options: {},
headers: [
{
align: 'left',
value: 'name',
},
],
}
},
}
</script>
```
</details>
=> docs(VDataTable): progress slot is not scoped

packages/vuetify/src/components/VTreeview/VTreeview.ts, packages/vuetify/src/components/VTreeview/VTreeviewNode.ts, packages/vuetify/src/components/VTreeview/__tests__/VTreeview.spec.ts
selecting parent item did not respect disabled children
closes #8244
<details>
```vue
<template>
<v-content>
<v-treeview
:items="items"
selectable
/>
{{ selected }}
</v-container>
</v-content>
</template>
<script>
data: () => ({
selected: [4],
items: [
{
id: 1,
name: 'Parent',
children: [
{id: 2, name: 'Child 1'},
{id: 3, name: 'Child 2'},
{id: 4, name: 'Child 3', disabled: true },
{id: 5, name: 'Child 4', disabled: true},
]
}
],
}),
}
</script>
```
</details>
=> fix(VTreeview): disabled items should be ignored when selecting parent

packages/vuetify/src/components/VDataTable/VDataTableHeaderMobile.ts
close multi-sort select when clicking on mobile
closes #10735
<details>
```vue
<template>
<v-container>
<v-data-table
multi-sort
</v-container>
</template>
<script>
data () {
return {
headers: [
{
value: 'name',
},
],
desserts: [
{
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1%',
},
{
calories: 237,
fat: 9.0,
carbs: 37,
protein: 4.3,
iron: '1%',
},
{
name: …
```
=> fix(VDataTable): close multi-sort select when clicking on mobile

packages/vuetify/src/components/VData/VData.ts, packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts, packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
only `must-sort` prop directly on data table was working. settings `must-sort` in options prop had no effect.
closes #10244
<details>
```vue
<template>
<v-container>
<v-data-table
:options="options"
must-sort
</v-container>
</template>
<script>
data () {
return {
options: {
// mustSort: true /// does not work, but must-true prop works
},
headers: [
{
text: "Dessert (100g serving)",
align: "left",
value: "name"
},
{ text: "Calories", value: "calories" },
{ text: "Fat (g)", value: "fat" },
{ text: "Carbs (g)", value: "carbs" },
{ text: "Protein (g)", value: "protein" },
{ text: "Iron (%)", value: "iron" }
],
desserts: [
{
name: "Frozen Yogurt",
calories: 159,
fat: …
```
=> fix(VDataTable): respect mustSort property in options prop

packages/vuetify/src/components/VCheckbox/VSimpleCheckbox.ts, packages/vuetify/src/components/VCheckbox/__tests__/VSimpleCheckbox.spec.ts
fixes #11345
jest, playground
<details>
```vue
<template>
<v-tooltip bottom>
<v-simple-checkbox
v-model="v"
v-on="on"
@click="log"
@mouseenter="log"
/>
</template>
Tooltip
</v-tooltip>
</template>
<script>
data: () => ({ v: false }),
methods: { log: e => console.log(e) },
}
</script>
```
</details>
=> fix(VSimpleCheckbox): pass listeners to component

packages/docs/src/examples/lists/intermediate/action-title-and-subtitle.vue
Replace v-model which was triggering vue/valid-v-model eslint validation error with :input-value
fix #11407
fixes #11407
When using the example snippet you would get a eslint error. This fixes remote
Visually, I went to the documentation page in question and i've checked all functionality were still working. The settings object still works. I have not created new tests (I don't know how).
<details>
```vue
```
</details>
=> docs(action-title-and-subtitle.vue): replace v-model by :input-value

packages/docs/src/data/drawerItems.json, packages/docs/src/data/pages/customization/GlobalConfig.pug, packages/docs/src/lang/en/customization/GlobalConfig.json, packages/docs/src/lang/en/meta.json, packages/docs/src/lang/en/vuetify/AppDrawer.json, packages/docs/src/snippets/js/global_config_silent.txt, packages/vuetify/src/framework.ts, packages/vuetify/src/util/console.ts, packages/vuetify/types/index.d.ts, packages/vuetify/types/test/global.ts
=> feat: allow all console messages to be disabled

packages/vuetify/src/components/VFileInput/VFileInput.ts, packages/vuetify/src/components/VFileInput/__tests__/VFileInput.spec.ts, packages/vuetify/src/components/VFileInput/__tests__/__snapshots__/VFileInput.spec.ts.snap, packages/vuetify/src/components/VTextField/VTextField.ts
fix #10886
Hide the input but still need it at the DOM
<details>
```vue
<template>
<div>
<v-file-input
multiple
label="File input"
<v-file-input
multiple
label="File input"
hide-input
></v-file-input>aaaaa
</div>
</template>
```
</details>
=> feat(VFileInput): add prop 'hide-input'

packages/vuetify/src/components/VTextField/VTextField.sass
Due to Issue #11338, 
I made next changes: if element is not reachable(disabled) it have not to get interactions by hover effect
<details>
There is a codepen example in related issue, which i used for playground
</details>
=> fix(VTextField): remove hover effect when disabled

packages/docs/src/data/pages/components/DataTables.pug, packages/docs/src/lang/en/components/DataTables.json, packages/vuetify/src/components/VDataTable/VDataTableHeader.ts
add v-data-table-header api docs
closes #9402
<details>
```vue
```
</details>
=> docs(VDataTable): add v-data-table-header api docs

packages/docs/src/lang/en/components/Menus.json
fix #11247
<details>
```vue
```
</details>
=> docs(VMenu): enhance docs for closeDelay & openDelay

packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.sass
disable inherit value of background property to v-select-list under v-navigation-drawer
fix #11153
The v-select options is becomes transparent when attach prop is used.
Fixed that to work in that situation.
fixes #11153 
visually
<details>
```vue
<template>
<div id="app">
<v-app id="hoge">
<v-app-bar app color="primary" dark>
<div class="d-flex align-center">
<v-img
alt="Vuetify Logo"
class="shrink mr-2"
contain
src="https://cdn.vuetifyjs.com/images/logos/vuetify-logo-dark.png"
transition="scale-transition"
width="40"
/>
<v-img
alt="Vuetify Name"
class="shrink mt-1 hidden-sm-and-down"
contain
min-width="100"
src="https://cdn.vuetifyjs.com/images/logos/vuetify-name-dark.png"
width="100"
/>
</div>
</v-app-bar>
<v-sheet height="400" class="overflow-hidden" …
```
=> fix(v-navigation-drawer): disable inherit value of background property

packages/vuetify/src/components/VSelect/VSelect.ts
fix https://github.com/vuetifyjs/vuetify/issues/11430
<details>
```vue
```
</details>
=> fix(VSelect): allow tab key down on read-only

packages/docs/src/lang/en/professional-support/Enterprise.json
It was a misspelling as I caught. Thought to bring it up.
<details>
```vue
```
</details>
- [x ] The PR title is no longer than 64 characters.
- [x ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x ] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
=> misspellings

packages/vuetify/src/components/VAvatar/VAvatar.sass, packages/vuetify/src/components/VAvatar/VAvatar.ts, packages/vuetify/src/components/VAvatar/__tests__/VAvatar.spec.ts
Integrate roundable mixin inside VAvatar
Asked by john
=> feat(VAvatar): integrate roundable mixin

packages/api-generator/src/maps/v-data-table.js, packages/docs/src/examples/data-tables/simple/group.vue, packages/docs/src/lang/en/components/DataTables.json, packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts, packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts, packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap, packages/vuetify/types/index.d.ts
setting it to false will remove group button on header
closes #10889
<details>
```vue
<template>
<v-data-table
sort-by="name"
group-by="category"
show-group-by
</template>
<script>
data () {
return {
headers: [
{
value: 'name',
groupable: false,
},
{ text: 'Category', value: 'category', align: 'right' },
{ text: 'Dairy', value: 'dairy', align: 'right' },
],
desserts: [
{
category: 'Ice cream',
dairy: 'Yes',
},
{
category: 'Ice cream',
dairy: 'Yes',
},
{
category: 'Cookie',
dairy: 'Yes',
},
{
category: 'Pastry',
dairy: 'Yes',
},
{ …
```
=> feat(VDataTable): add groupable property to header items

packages/api-generator/src/index.js, packages/api-generator/src/maps/v-click-outside.js, packages/api-generator/src/maps/v-intersect.js, packages/docs/src/data/drawerItems.json, packages/docs/src/data/pages/directives/ClickOutside.pug, packages/docs/src/examples/click-outside/close-conditional.vue, packages/docs/src/examples/click-outside/usage.vue, packages/docs/src/lang/en/directives/ClickOutside.json, packages/docs/src/lang/en/meta.json, packages/docs/src/lang/en/vuetify/AppDrawer.json, packages/docs/src/snippets/ts/directive_click_outside_value.txt, packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap, packages/vuetify/src/components/VDialog/VDialog.ts, packages/vuetify/src/components/VMenu/VMenu.ts, packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts, packages/vuetify/src/components/VSelect/VSelect.ts, packages/vuetify/src/directives/click-outside/__tests__/click-outside.spec.ts, packages/vuetify/src/directives/click-outside/index.ts, packages/vuetify/src/directives/mutate/index.ts, packages/vuetify/src/directives/scroll/__tests__/scroll.spec.ts, packages/vuetify/src/directives/scroll/index.ts, packages/vuetify/src/mixins/intersectable/index.ts
fixes #4654
Might be considered a breaking change if someone is using these with render functions, some things like `args` either don't exist or are excessively complicated to use with templates. 
<details>
```vue
<template>
<v-container>
<v-list>
<v-list-item v-click-outside="() => clickOutside1 = false" @click="clickOutside1 = true">
<v-list-item-title>Click outside - handler only</v-list-item-title>
<v-list-item-action>
<v-icon :color="clickOutside1 ? 'green' : 'red'">mdi-record</v-icon>
</v-list-item-action>
</v-list-item>
<v-list-item v-click-outside="{ handler: () => clickOutside2 = false, closeConditional }" @click="clickOutside2 = true">
<v-list-item-title>Click outside - with closeConditional</v-list-item-title>
<v-list-item-action>
<v-icon :color="clickOutside2 ? 'green' : …
```
=> feat(directives): expose all options to templates

packages/docs/src/data/drawerItems.json, packages/docs/src/data/pages/components/Menus.pug, packages/docs/src/examples/menus/simple/rounded.vue, packages/docs/src/lang/en/components/Menus.json, packages/vuetify/src/components/VMenu/VMenu.sass, packages/vuetify/src/components/VMenu/VMenu.ts, packages/vuetify/src/components/VMenu/_variables.scss
Adds new functionality to `VMenu` through the addition of the `Roundable` mixin
resolves #10397
visually
<details>
```vue
<template>
<div class="text-center fill-height d-flex justify-space-around align-center">
<v-menu top rounded="0">
<v-btn
class="rounded-0"
dark
v-on="on"
>
rounded="0"
</v-btn>
</template>
<v-list>
<v-list-item
:key="index"
@click=""
>
</v-list-item>
</v-list>
</v-menu>
<v-menu top :rounded="true">
<v-btn
dark
v-on="on"
>
:rounded="true"
</v-btn>
</template>
<v-list>
<v-list-item
:key="index"
@click=""
>
<v-list-item-title>{{ item.title …
```
=> feat(VMenu): roundable menu

packages/vuetify/src/components/VTextField/VTextField.ts, packages/vuetify/src/components/VTextField/__tests__/VTextField.spec.ts
Applied the proposed solution in #9368 to return '-0' as a string.
fixes #9368
playground
<details>
```vue
<template>
<v-container>
<v-text-field
v-model.number="input"
type="number"
step="any"
label="Try typing '-0.1'"
>
</v-text-field>
{{ input }}
<v-text-field
v-model.number="inputText"
label="Try typing '-0.1'"
>
</v-text-field>
{{ inputText }}
</v-container>
</template>
<script>
data: () => ({
input: null,
inputText: null,
}),
}
</script>
```
</details>
=> fix(VTextField): allow numeric input starting with -0 

packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.ts, packages/vuetify/src/util/helpers.ts
Fixes #5546
Fixes #5546 by adding a 250ms throttle to the function reacting to scroll wheel events
Fixes blurring that happens when VDatePicker is scrolled via a touchpad.  Reference #5546
Tested visually on a MacBook Pro on safari, chrome and firefox.  Passes all existing tests.
<details>
```vue
<v-date-picker scrollable></v-date-picker>
```
</details>
=> fix(VDatePicker): throttle scroll with using scrollable prop

packages/docs/src/data/pages/components/FileInputs.pug, packages/docs/src/lang/en/components/FileInputs.json
Forgot to add to docs at https://github.com/vuetifyjs/vuetify/pull/11031
Currently at dev not master
<details>
```vue
```
</details>
=> docs(vfileinput): add the hide-input prop to docs

packages/vuetify/src/components/VDataIterator/VDataIterator.ts, packages/vuetify/src/components/VDataTable/VDataTable.ts, packages/vuetify/types/index.d.ts
Expose return type of `createItemProps()`
I want to use this type for [click:row](https://vuetifyjs.com/en/components/data-tables/) event's second argument in my developing application. (should be like `DataItemProps & { headers: DataTableHeader<any>[]; }`)
build command succeed
=> feat(types): add DataItemProps interface

packages/docs/src/snippets/js/global_config_silent.txt
Minor fix of silent config example.
Make the documentation examples correct.
Visually.
=> docs: fix silent config example

packages/vuetify/src/components/VVirtualScroll/VVirtualScroll.ts, packages/vuetify/src/components/VVirtualScroll/__tests__/VVirtualScroll.spec.ts
fix #11622
Provide the right index to tthe VVirtualScroll slots
resolves #11622 
https://github.com/vuetifyjs/vuetify/issues/11622
visually + playground
<details>
```vue
<template>
<v-container>
<v-card
max-width="400"
>
<v-card-title class="white--text orange darken-4">
User Directory
<v-btn
color="white"
class="text--primary"
fab
small
>
<v-icon>mdi-plus</v-icon>
</v-btn>
<v-card-text class="pt-4">
Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi nobis a at voluptates culpa optio amet! Inventore deserunt voluptatem maxime a veniam placeat, eos impedit nulla quos? Officiis, aperiam ducimus.
</v-card-text>
<v-virtual-scroll
:items="items"
:item-height="50"
height="300"
> …
```
=> fix(VVirtualScroll): provide correct item index to default slot

packages/docs/src/examples/text-and-typography/typography.vue
Modifies overline elements to match code changed in ([8c650e4](https://github.com/vuetifyjs/vuetify/commit/8c650e48a53ac32ba44bd16d3f853a8b07810ff3)).
fixes #11674.
A revert commit made to a change commit has caused the docs to have a minor error related to the overline type.
https://github.com/vuetifyjs/vuetify/issues/11674
none
<details>
```vue
```
</details>
=> docs(Typography): update overline elements

packages/docs/src/examples/menus/intermediate/absolute-without-activator.vue
The description of the menu component [Absolute position without activator](http://localhost:8095/en/components/menus/#absolute-position-without-activator) example says "Try right-clicking anywhere..." but the menu only opens on a normal left-click. Fixed it so the menu opens on a right-click via the `contextmenu` event.
The description of the example doesn't match up with the actual example.
=> docs(VMenu): no activator example menu opens on right click

packages/vuetify/src/components/VChip/VChip.sass
=> fix(VChip): outlined hover state

packages/vuetify/src/components/VContent/VContent.ts
Add the `v-content` and `v-content__wrap` class names to the elements created using the deprecated `v-content`.
The change from v-main to v-content caused a backwards compatibility issue for any app relying on the `v-content` and `v-content__wrap` class names.
none
<details>
```vue
<template>
<v-content></v-content>
</template>
```
</details>
=> fix(VMain): add existing v-content classes for backwards compatibility

packages/docs/src/lang/en/styles/TextAndTypography.json
<details>
```vue
```
</details>
=> Fix class name convention on helping text

packages/docs/src/lang/en/getting-started/QuickStart.json
Fix a typo that made the sentence grammatically incorrect
=> Fix a typo

packages/api-generator/src/helpers/variables.js, packages/docs/src/lang/en/components/Selects.json
Add items prop object the disabled option in the description in english and in the example also,
mention the item-disabled prop in the description as its relevant
=> docs(v-select): add items prop object the disabled option

packages/docs/src/layouts/layouts/demos/baseline-flipped.vue, packages/docs/src/layouts/layouts/demos/baseline.vue, packages/docs/src/layouts/layouts/demos/complex.vue, packages/docs/src/layouts/layouts/demos/dark.vue
Updated dates in pre-made layouts.
<details>
The sandbox example contains the following code:
```vue
<span class="px-4">&copy; {{ new Date().getFullYear() }}</span>
```
but the remaining examples contain:
```vue
<span class="white--text">&copy; 2019</span>
```
```vue
<span>&copy; 2020</span>
```
</details>
=> docs(layouts/demos): dynamic dates in demo layouts.

packages/vuetify/src/components/VMenu/VMenu.ts, packages/vuetify/src/components/VSelect/VSelect.ts
Ensure that `VSelect` adds scroll listener to `VMenu`'s `content`.
Arbitrary one-time delay of `this.getContent().addEventListener('scroll', this.onScroll, false)` does not guarantee that target element will exist the next time that we try to add the listener.
Proposed solution does guarantee that listener is eventually added.
In the playground.
```vue
<template>
<v-container>
<v-alert>Loaded {{ this.options.length }} options</v-alert>
<v-combobox ref="combobox" :items="options" @click="firstLoad && loadOptions()">
<template #append-item>
<div v-intersect="onNextPageIntersection"/>
<v-progress-linear :active="loading" indeterminate class="fixed-bottom"></v-progress-linear>
</template>
</v-combobox>
<div class>1. See that no options are loaded. Open the menu.
<br>2. You notice that some …
```
=> fix(VSelect): ensure VMenu's content has scroll listener added

packages/vuetify/src/components/VFooter/VFooter.ts
VFooter has tag prop, but always render `<footer>`.
So I change to render component with `tag` prop.
And I set the default value to `<footer>` like before.
fixes #11580
unit, visually
<details>
```vue
<template>
<div id="app">
<v-app>
<div>
<v-footer
absolute
class="font-weight-medium"
tag="section"
>
<v-col
class="text-center"
cols="12"
>
{{ new Date().getFullYear() }} — <strong>Vuetify</strong>
</v-col>
</v-footer>
</div>
</v-app>
</div>
</template>
```
</details>
=> fix(VFooter): add missing tag prop

packages/vuetify/src/styles/settings/_dark.scss, packages/vuetify/src/styles/settings/_light.scss
fix #10740
resolves #10740
Safari treats `transparent` as "transparent black". To fix this problem, we change `transparent` to use a value of `rgba(255, 255, 255, 0)`.
#10740
Playground, docs on Safari
<details>
```vue
<template>
<v-container>
<v-app>
<v-skeleton-loader type="article"></v-skeleton-loader>
</v-app>
</v-container>
</template>
<script>
data: () => ({
}),
}
</script>
```
</details>
=> fix(VSkeletonLoader): use rgba transparency for animation on Safari

packages/vuetify/src/components/VNavigationDrawer/__tests__/VNavigationDrawer.spec.ts, packages/vuetify/src/framework.ts, packages/vuetify/src/install.ts, packages/vuetify/src/services/breakpoint/__tests__/breakpoint.spec.ts, packages/vuetify/src/services/breakpoint/index.ts, packages/vuetify/src/services/theme/__tests__/__snapshots__/theme.spec.ts.snap, packages/vuetify/src/services/theme/__tests__/theme.spec.ts, packages/vuetify/src/services/theme/index.ts
fixes #3436
fixes #7410
Also threw in a refactor of theme reactivity just for fun. 
tested in nuxt
=> fix(ssr): use xs breakpoint on inital render when hydrating

packages/vuetify/src/components/VProgressCircular/VProgressCircular.sass
fixes #11867
https://github.com/vuetifyjs/vuetify/issues/11867
visually
<details>
```vue
```
</details>
=> fix(VProgressCircular): don't apply rotate animation to svg icon

packages/vuetify/src/components/VBtnToggle/VBtnToggle.sass
Make sure that when using VBtnToggle in RTL mode with rounded corners, the correct corners are rounded for the first and last item, and borders are displayed correctly (no missing or doubled borders).
Fixes #11793
Fixes #11793
visually
<details>
```vue
<template>
<v-btn-toggle rounded>
<v-btn>
<v-icon>mdi-format-align-left</v-icon>
</v-btn>
<v-btn>
<v-icon>mdi-format-align-center</v-icon>
</v-btn>
<v-btn>
<v-icon>mdi-format-align-right</v-icon>
</v-btn>
<v-btn>
<v-icon>mdi-format-align-justify</v-icon>
</v-btn>
</template>
<script>
data: () => ({}),
mounted() {
this.$vuetify.rtl = true;
},
};
</script>
```
</details>
=> fix(VBtnToggle): add missing RTL support in button groups

packages/docs/src/data/pages/getting-started/QuickStart.pug, packages/docs/src/lang/en/getting-started/QuickStart.json, packages/docs/src/snippets/js/vue_add_vuepress.txt
Translations status for this update
1 incomplete out of 9, 1/9
UY :x:
EN :white_check_mark:
DE :white_check_mark:
FR :white_check_mark:
JP :white_check_mark:
KR :white_check_mark:
RU :white_check_mark:
CN :white_check_mark:
EN :white_check_mark:
Add vuetify "usgae with vuepress" documentation with 8 translations
fixes #10738
#10738
visually
<details>
```vue
```
</details>
=> docs(GettingStarted): add usage with vuepress (#10738)

packages/vuetify/src/locale/nl.ts
=> Fixed typo (NL)

packages/docs/src/examples/list-item-groups/intermediate/selection-controls.vue, packages/docs/src/examples/lists/intermediate/subheadings-and-dividers.vue
- https://vuetifyjs.com/en/components/list-item-groups/\#selection-controls
- https://vuetifyjs.com/en/components/lists/\#subheadings-and-dividers
resolves #11986
Update docs to latest usage
none
=> docs(VListItemAction): update checkbox handling to latest usage (#11986)

packages/docs/src/lang/en/styles/BorderRadius.json
…desText1
Correctly name border-radius classes for rounding a side `.rounded-b-xl` and `.rounded-t`." in paragraph text
Correctly name border-radius classes for rounding a side `.rounded-b-xl` and `.rounded-t`." in paragraph text
Fixes Documentation typo
<details>
```vue
```
</details>
=> docs(Border-Radius): Fix Docs Typo on Rounding Sides Separately

packages/docs/src/lang/en/styles/Elevation.json
Fixed an Indefinite article from `a` to `an`.
<details>
```vue
```
</details>
=> docs(elevation): fix indefinite article

packages/docs/src/examples/v-data-table/misc-crud.vue
`docs/import-next`
[review - 12217](https://github.com/vuetifyjs/vuetify/pull/12217#pullrequestreview-487269237)
The toolbar background in "CRUD Actions" section in "en\components\data-tables" is hard coded with
"white", which is not respecting dark theme. Removed it.
See here: https://vuetifyjs.com/en/components/data-tables/#crud-actions (with dark theme enabled)
visually
=> docs: removed hard coded color

packages/docs/src/examples/v-avatar/misc-advanced.vue, packages/docs/src/examples/v-btn-fab/misc-lateral-screens.vue, packages/docs/src/examples/v-btn-fab/misc-small.vue, packages/docs/src/examples/v-card/misc-twitter-card.vue, packages/docs/src/examples/v-chip/misc-in-selects.vue, packages/docs/src/examples/v-data-table/misc-crud.vue, packages/docs/src/examples/v-expansion-panels/misc-advanced.vue, packages/docs/src/examples/v-input/event-slot-clicks.vue, packages/docs/src/examples/v-input/usage.vue, packages/docs/src/examples/v-select/prop-icons.vue, packages/docs/src/examples/v-slider/prop-icons.vue, packages/docs/src/examples/v-subheader/misc-menu.vue, packages/docs/src/examples/v-subheader/misc-social-media.vue, packages/docs/src/examples/v-subheader/prop-inset.vue, packages/docs/src/examples/v-tabs/misc-dynamic-height.vue, packages/docs/src/examples/v-textarea/prop-clearable.vue, packages/docs/src/examples/v-toolbar/prop-floating-with-search.vue
There are many broken icons in the doc and icon names are only visible.
Visually
=> Fixed broken icons with `mdi-*` prefix

packages/docs/src/examples/v-hover/prop-open-and-close-delay.vue, packages/docs/src/examples/v-hover/usage.vue
Targeting changes to docs/import-next
https://github.com/vuetifyjs/vuetify/pull/12215#pullrequestreview-487179857
Adjusted the style to show the change in appearance of Usage and Open/Close Delay examples when hovering in dark mode.
fixes #11906 
Usage and Open/Close Delay examples look bad in the dark mode.
<details>
```vue
```
</details>
=> docs(vhover): improve visibility in dark mode

packages/docs/src/i18n/messages/en.json
This is a tiny change. Fix typo in [breakpoints table in English doc](https://vuetifyjs.com/en/features/breakpoints/).
=> docs(en/breakpoints-table): fix typo

packages/docs/src/data/team.json
=> fix(docs): update team page link

.gitignore, packages/docs/src/pages/en/components/date-pickers.md
Add .yarn to .gitignore.  This is so users new to yarn, who follow the recommendation at [https://yarnpkg.com/getting-started/install](url) to use yarn on a per project basis aren't greeted by thousands of additions after first running `yarn`.
Ever so slightly lowers contribution barrier for those on a slightly different environment setup.
visually
<details>
```vue
```
</details>
=> Add .yarn to .gitignore for local yarn 2 envs

packages/docs/src/pages/en/getting-started/browser-support.md
Updates explanation about IE11/safari polyfill with some more modern examples and also splits it up into 2 seperate sections for Vue CLI / Webpack.
Both `babel-polyfill` and `@babel/polyfill` are deprecated
resolves #8025
<details>
```vue
```
</details>
=> docs: update IE11 polyfill explanation

packages/docs/src/pages/en/features/sass-variables.md
Add nuxt install content for sass-variables.md
No one wrote, I did
Vision
Vision
=> docs(sass-variables): add nuxt install content

packages/docs/src/pages/en/components/button-groups.md
Just add one missing word to documentation
Documentation update
=> Missed word in button-groups.md

packages/vuetify/src/components/VCard/VCard.sass
fixes #11672
visually 
```vue
<template>
<div>
<v-card
class="pa-12 my-2 mx-auto"
max-width="344"
hover
shaped
>Shaped</v-card>
<v-card
class="pa-12 my-2 mx-auto"
max-width="344"
hover
>Normal</v-card>
<v-card
class="pa-12 my-2 mx-auto"
max-width="344"
hover
outlined
>Outlined</v-card>
</div>
</template>
```
=> fix(VCard): hover works only for outlined cards

packages/vuetify/src/components/VTextField/VTextField.ts
Removes erroneous whitespace in VTextField legend 
Chrome auto-translate replaces whitespace with non-whitespace characters ie. when translated to French (France) this character becomes "La"
Visually 
<details>
```vue
```
</details>
=> fix(VTextField): remove erroneous white space #11747

packages/vuetify/src/components/VTextField/VTextField.ts
Use Resize directive to recalculate elements width after window resize.
Cause elements width can be changed after window resize. Inspired by #9341
visually
https://codepen.io/djaler/pen/eYJrOKp (resize your browser window to make it smaller than 1000px in width)
=> fix(VTextField): use resize directive to recalculate elements width

packages/vuetify/src/components/VColorPicker/VColorPicker.sass
fix #12169
fixes #12169 
Visually
<details>
```vue
<template>
<v-container>
<v-color-picker class="ma-2"/>
<v-color-picker
class="ma-2"
dark
/>
</v-container>
</template>
<script>
data: () => ({
//
}),
}
</script>
```
</details>
=> fix(VColorPicker): use theme color for color-picker inputs

packages/vuetify/src/components/VTimePicker/VTimePickerClock.sass
This will add the `flex-basis` property on the time picker (VTimePicker) component to render ok on browsers like Firefox 52.
| Before | After |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/93357469-02b5ee80-f849-11ea-816e-eafb5663e559.png) | ![image](https://user-images.githubusercontent.com/120486/93357497-09dcfc80-f849-11ea-93f0-d9b00c9d1300.png) |
See [relevant MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis):
> The `flex-basis` CSS property sets the initial main size of a flex item.
The time picker component was not rendering ok on browsers like Firefox 52.
Tried this on Firefox 52 and latest Firefox, Chrome.
<details>
```vue
```
</details>
=> fix(VTimePicker): add flex-basis property to container for safari 52 support

packages/docs/src/data/team.json
Add to teams documentation page.
=> docs(team) update team.json

packages/docs/src/examples/v-data-table/misc-crud.vue
Update in the delete function to suit the layout.
Update in the delete function to suit the layout.
Contribute to the community
<details>
```vue
```
</details>
=> Improvement Delete function

packages/docs/src/pages/en/components/calendars.md
Section : #### Day body
minor change on a sentence from "we add" to "we added"
<details>
```vue
```
</details>
=> minor change on a sentence

packages/docs/src/examples/v-data-iterator/misc-filter.vue
Change icon name in the example from `md` to `mdi` based.
Old icon in use.
Visually.
<details>
N/A
```vue
```
</details>
=> docs(misc-filter): change icon name from 'md' to 'mdi' based

packages/docs/src/pages/en/features/sass-variables.md
This resolves the issue  #12346 
I tested the proposed changes by manually editing the link in the devtools - where it works.
=> Fix broken link to sass api

packages/vuetify/src/locale/th.ts
- dataTable.ariaLabel.activateNone
- dataTable.ariaLabel.activateDescending
- dataTable.ariaLabel.activateAscending
- carousel.ariaLabel.delimiter
- dataIterator.loadingText 
- dataTable.ariaLabel.sortDescending
- dataTable.ariaLabel.sortAscending
- dataTable.ariaLabel.sortNone
- dataTable.sortBy
- datePicker.nextMonthAriaLabel
- datePicker.nextYearAriaLabel
- datePicker.prevMonthAriaLabel
- datePicker.prevYearAriaLabel
- carousel.next
- calendar.moreEvents
- pagination.ariaLabel.wrapper
- pagination.ariaLabel.currentPage
- There are new strings that should be translated.
- Some current translations should be improved or updated in sync with the `en` locale.
=> fix(locales): th-Thai i18n translation

packages/vuetify/src/components/VSelect/VSelect.ts, packages/vuetify/src/components/VSelect/__tests__/VSelect.spec.ts, packages/vuetify/src/components/VSelect/__tests__/VSelect2.spec.ts, packages/vuetify/src/components/VSelect/__tests__/VSelect3.spec.ts, packages/vuetify/src/components/VSelect/__tests__/VSelect4.spec.ts, packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect3.spec.ts.snap
clicking on a selection item (for example the close icon of a v-chip) would cause menu to open if component was using filled/outlined/solo
~~closes #11824~~
closes #10774
<details>
```vue
<template>
<v-card>
<v-select
filled
:items="asd"
></v-select>
v-model="friends"
:disabled="isUpdating"
:items="asd"
solo
chips
color="blue-grey lighten-2"
label="Select"
multiple
v-model="friends"
:disabled="isUpdating"
solo
chips
color="blue-grey lighten-2"
label="Select"
item-text="name"
multiple
>
<template v-slot:selection="data">
<v-chip
v-bind="data.attrs"
:input-value="data.selected"
close
@click="data.select"
@click:close="remove(data.item)"
>
<v-avatar left>
<v-img :src="data.item.avatar"></v-img>
</v-avatar> …
```
=> fix(VSelect): do not open menu if clicking on selection item

packages/docs/src/examples/transitions/misc-todo.vue
icon for completed task was "check" instead of "mdi-check" which caused text to appear instead of the icon
Minor fix to documentation example. Fixed icon text from "check" to "mdi-check"
Documentation examples should work perfectly to allow users to have sound reference material.
Checked locally and on the MDI website to ensure the icon exists and mdi-check is the correct reference. 
<details>
```vue
```
</details>
=> Fixed 'check' Icon in transitions Todo example

packages/api-generator/src/maps/v-data-table.js
closes #11784
#11784
just looked at the local docs
=> docs: change TableHeader in to DataTableHeader

packages/docs/src/examples/v-card/misc-horizontal-cards.vue
typo "v-card-action" has been fixed with "v-card-actions"
<details>
```vue
```
</details>
=> Fixed typo

packages/docs/src/examples/flex/flex-align.vue, packages/docs/src/examples/flex/flex-justify.vue
I've tried to do something for #11340 but i'm not sure this is the way vuetify wan't to go, so i only did it for 2 examples.
#11340
just opened the docs locally and checked if they have the same result as online
=> Docs: Plain markup docs

packages/docs/src/pages/en/getting-started/installation.md
Added a warning to alert users that the command can make significant file changes and that they should commit their changes before proceeding
ref: https://discordapp.com/channels/340160225338195969/340160225338195969/763412014323728394
<details>
```vue
```
</details>
=> Added a warning to `vue add vuetify` command

packages/docs/src/pages/en/getting-started/contributing.md
[Rendered](https://github.com/vuetifyjs/vuetify/blob/docs/contributing-guide/packages/docs/src/pages/en/getting-started/contributing.md)
=> docs: update contributing guide

packages/docs/src/examples/v-virtual-scroll/prop-bench.vue
The ID itself wasn't rendering so I just added it to the example doc
The ID itself wasn't rendering
Not really needed although I tested it visually on my machine
create a new project, copy & paste the code
<details>
<template>
<div>
<v-responsive
max-width="400"
class="mx-auto mb-4"
>
<v-text-field
v-model="benched"
type="number"
label="Total Preload"
min="0"
max="100"
</v-responsive>
<v-card
elevation="16"
max-width="400"
>
<v-virtual-scroll
:bench="benched"
:items="items"
height="300"
item-height="64"
>
<template v-slot="{ item }">
<v-list-item :key="item">
<v-list-item-action>
<v-btn
fab
small
depressed
>
{{ item }}
</v-btn>
</v-list-item-action>
User Database Record <strong>{{ item }}</strong> …
=> docs(VVirtualScroll): show item ID in bench example

packages/api-generator/src/maps/v-calendar.js
#12176
#12176
visually
and i've checked if the paramaters in the event:click are indeed the parameters i've used
=> docs: add event events to calendar

packages/api-generator/src/maps/v-radio.js
closes #12046
Because v-radio uses v-input the doc-generator automatically creates the append and prepend slot documentation.
So either the is should stop using v-input or it should get those prepend and append slots
For now i'll make a PR that "deletes" those slots on the documentation generator of the v-radio but i'm guessing there should be an issue for adding this functionality
#12046
visually tested VRadio and VCheckbox docs
=> docs: remove append and prepend slot from VRadio

packages/docs/src/components/vuetify/Comparison.vue
Added styling to the table of why Vuetify section
=> refactor: Added styling to the table of why vuetify section

packages/docs/src/components/ad/Bsa.vue, packages/docs/src/components/ad/Discovery.vue, packages/docs/src/components/ad/Entry.vue, packages/docs/src/components/ad/Exit.vue, packages/docs/src/components/ad/Promoted.vue, packages/docs/src/components/ad/Random.vue, packages/docs/src/components/doc/PremiumThemes.vue, packages/docs/src/components/doc/links/StoreLink.vue, packages/docs/src/mixins/ad.js
Add UTM source and medium on Vuetify ads
Better Vuetify ads efficiency tracking
Visually | GA
<details>
```vue
```
</details>
=> docs: add utm metadata to ads

packages/docs/src/pages/en/getting-started/unit-testing.md
Remove duplicated `const localVue` on [Spec Tests](https://vuetifyjs.com/en/getting-started/unit-testing/#spec-tests) sample code
If there are duplicated same const variable, the sample code cannot work.
visually 
N/A
<details>
```vue
```
</details>
=> docs(unit-testing): fix error on Spec Tests sample code

README.md
<details>
```vue
```
</details>
=> Spliting plugins and presets in readme.md

packages/docs/src/examples/v-radio-group/prop-mandatory.vue, packages/docs/src/pages/en/components/radio-buttons.md
fix #12435
Fix the default value of radio-buttons mandatory props : from true to false.
fix #12435 : have a documentation correct.
Build the docs and have a look on the result.
<details>
```vue
```
</details>
=> docs: fix radio button mandatory props default

packages/vuetify/src/locale/ja.ts
Update translation of ja.
Improve existing and add new translation.
none
<details>
```vue
```
</details>
=> fix(locale): improve japanese translations

packages/vuetify/src/components/VTabs/VTabs.ts
fixes #12524
VTabs now watches for changes to the icons-and-text prop and redraws the slider
Done to fix issue #12524 
Tested visually
<details>
```vue
```
</details>
=> fix(VTabs): resize slider when icons-and-text prop changes

packages/docs/src/examples/v-card/misc-card-reveal.vue, packages/docs/src/pages/en/components/cards.md
resolves #1240 
visually
<details>
```vue
```
</details>
=> docs(VCard): Card reveal example

packages/vuetify/src/components/VToolbar/VToolbar.sass, packages/vuetify/src/components/VToolbar/_variables.scss
fixes https://github.com/vuetifyjs/vuetify/issues/12222
fix typo
none
<details>
```vue
```
</details>
=> fix(VToolbar): v-toolbar sass variables typo

packages/vuetify/src/components/VInput/VInput.sass, packages/vuetify/src/components/VInput/_variables.scss
fixes https://github.com/vuetifyjs/vuetify/issues/12250
- Fixed sass variable to specify letter-spacing for input label.
- Fixed the default letter-spacing value is too large.
visually
<details>
```vue
<template>
<v-container>
<v-row class="ma-4">
<v-select label="My Select"></v-select>
</v-row>
</v-container>
</template>
<script>
data: () => ({
//
}),
}
</script>
```
</details>
=> fix(VInput): use label letter-spacing variable

packages/vuetify/src/components/VRadioGroup/VRadioGroup.sass
Few issues with radio group main label
Before:
After:
sense of aesthetics
playground visually
<details>
```vue
<template>
<div>
<v-container style="width: 200px">
<v-radio-group label="This label is very long. This label is very long. This label is very long. This label is very long. This label is very long. This label is very long. ">
<v-radio label="foo" />
<v-radio label="foo" />
<v-radio-group
row
label="This label is very long. This label is very long. This label is very long. This label is very long. This label is very long. This label is very long. "
>
<v-radio label="foo" />
<v-radio label="foo" />
</v-container>
<v-container style="width: 800px">
<v-radio-group label="This label is not very long">
<v-radio label="foo" />
<v-radio label="foo" /> …
```
=> fix(VRadioGroup): label styles

packages/vuetify/src/components/VDataIterator/VDataFooter.ts, packages/vuetify/src/components/VDataIterator/__tests__/__snapshots__/VDataFooter.spec.ts.snap, packages/vuetify/src/components/VDataIterator/__tests__/__snapshots__/VDataIterator.spec.ts.snap, packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
fix #12012
fixes #12012 
<details>
```vue
<template>
<div id="app">
<v-data-table
:single-select="singleSelect"
show-select
>
<template v-slot:top>
<v-switch
v-model="singleSelect"
label="Single select"
class="pa-3"
></v-switch>
</template>
</v-app>
</div>
</template>
<script>
name: 'App',
data () {
return {
singleSelect: false,
selected: [],
headers: [
{
value: 'name',
},
],
desserts: [
{ …
```
=> fix(vdatafooter): transate itemsPerPageText

packages/vuetify/src/components/VRadioGroup/VRadio.sass, packages/vuetify/src/components/VRadioGroup/VRadioGroup.sass, packages/vuetify/src/styles/components/_selection-controls.sass
fix #12023
<details>
```vue
<template>
<div id="app">
<v-app>
<div style="width: 200px;">
<v-radio-group>
<v-radio
label="Label A"
value="a"
disabled
/>
<v-radio
label="Label B"
value="b"
/>
<v-checkbox label="Checkbox"></v-checkbox>
<v-checkbox
label="Checkbox"
disabled
></v-checkbox>
<v-switch
v-model="switchValue"
label="John"
value="John"
@click="onClick"
></v-switch>
<v-switch
v-model="switchValue"
label="Jacob"
value="Jacob"
disabled
@click="onClick"
></v-switch>
</div>
</v-app>
</div>
</template>
<script>
data: () => ({
checkbox: ['John'],
switchValue: null,
radio: null,
}),
methods: {
onClick () {
console.log('click')
},
},
}
</script>
<style>
.v-input__slot {
padding: 15px;
border: 1px green solid;
}
.v-input--selection-controls__input {
padding: …
```
=> fix(VRadio): do not use cursor pointer if disabled

packages/vuetify/src/components/VDataTable/VDataTable.sass, packages/vuetify/src/components/VDataTable/VSimpleTable.sass, packages/vuetify/src/components/VDataTable/VSimpleTable.ts, packages/vuetify/src/components/VDataTable/__tests__/VSimpleTable.spec.ts, packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap, packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VSimpleTable.spec.ts.snap
fixes https://github.com/vuetifyjs/vuetify/issues/12550
fixes https://github.com/vuetifyjs/vuetify/issues/12550
unit and visually
<details>
```vue
<template>
<v-container>
<v-simple-table class="mt-4">
<template
v-slot:default
>
<thead>
<tr>
<th class="text-left">Name</th>
<th class="text-left">Calories</th>
</tr>
</thead>
<tbody>
<tr
v-for="item in dessertsForSimpleTable"
:key="item.name"
>
<td>{{ item.name }}</td>
<td>{{ item.calories }}</td>
</tr>
</tbody>
</template>
</v-simple-table>
<v-data-table
class="mt-4"
<v-data-table
hide-default-header
class="mt-4"
</v-container>
</template>
<script>
data: () …
```
=> fix(VSimpleTable): add border radius to first and last row 

packages/vuetify/src/components/VTextField/VTextField.sass
Added background color to the line under input on the focused state in order to remove white line.
I have the following input:
```
<v-text-field
label="Search..."
single-line
flat
hide-details
clearable
filled
clear-icon="mdi-close"
class="rounded-0"
```
and I'm viewing it on Windows 10 with 150% scale on the system level. I can see the white line that crosses underlining of active input. Please, see the screenshot of this issue bellow:
Tested visually
Here's the issue: https://codepen.io/maxim_mazurok/pen/JjKBWwp
Here's the fix: https://codepen.io/maxim_mazurok/pen/QWEBpYj
- [] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
=> fix(VTextField): add background for line

packages/vuetify/src/components/VFileInput/VFileInput.sass, packages/vuetify/src/components/VFileInput/_variables.scss
fixes https://github.com/vuetifyjs/vuetify/issues/11300
fixes https://github.com/vuetifyjs/vuetify/issues/11300
visually
<details>
```vue
<template>
<v-container>
<v-row>
<p>normal</p>
</v-row>
<v-row>
<v-col
cols="12"
sm="6"
md="3"
>
<v-text-field
label="Regular"
dense
</v-col>
<v-col
cols="12"
sm="6"
md="3"
>
<v-text-field
label="Regular"
prepend-icon="mdi-map-marker"
dense
</v-col>
<v-col
cols="12"
sm="6"
md="3"
>
<v-file-input
label="File"
dense
</v-col>
</v-row>
<v-row>
<p>solo</p>
</v-row>
<v-row>
<v-col
cols="12"
sm="6"
md="3"
>
<v-text-field
label="Solo"
dense
solo
</v-col>
<v-col
cols="12"
sm="6"
md="3"
>
<v-text-field
label="Solo"
prepend-icon="mdi-map-marker"
dense
solo
</v-col>
<v-col …
```
=> fix(VFileInput): file-input-slot dense min-height

packages/api-generator/src/maps/v-click-outside.js, packages/docs/src/examples/v-click-outside/option-include.vue, packages/docs/src/pages/en/directives/click-outside.md
resolves #12493 
[Issue](https://github.com/vuetifyjs/vuetify/issues/12493)
Visually
<details>
```vue
```
</details>
=> docs(VClickOutside): Add include example

README.md
Update the main README's cli preset links and cli utils link.
Visually
<details>
```vue
```
</details>
=> docs(readme): update ecosystem links

packages/api-generator/src/locale/en/v-carousel.json, packages/api-generator/src/locale/en/v-window.json, packages/api-generator/src/maps/v-carousel.js, packages/api-generator/src/maps/v-window.js, packages/docs/src/examples/v-carousel/slots-next-prev.vue, packages/docs/src/examples/v-window/slots-next-prev.vue, packages/docs/src/pages/en/components/carousels.md, packages/docs/src/pages/en/components/windows.md, packages/vuetify/src/components/VWindow/VWindow.ts
Adds slots for prev/next arrow
fixes partially #3235
playground
<details>
```vue
<template>
<v-container>
<v-window
reverse
show-arrows
>
<template #prev="{ on, attrs }">
<v-btn
color="success"
v-bind="attrs"
v-on="on"
>Prev</v-btn>
</template>
<template #next="{ on, attrs }">
<v-btn
color="info"
v-bind="attrs"
v-on="on"
>Next</v-btn>
</template>
<v-window-item
v-for="n in 3"
:key="`card-${n}`"
class="pa-12"
>Lorem ipsum</v-window-item>
</v-window>
<v-carousel>
<template #prev="{ on, attrs }">
<v-btn
color="success"
v-bind="attrs"
v-on="on"
>Prev</v-btn>
</template>
<template #next="{ on, attrs }">
<v-btn
color="info"
v-bind="attrs"
v-on="on"
>Next</v-btn>
</template>
v-for="i in 6"
:key="i"
>
<div class="black--text">
Slide {{ i + 1 }}
</div> …
```
=> feat(VWindow,VCarousel): **prev** and **next** slots

packages/api-generator/src/locale/en/v-date-picker.json, packages/docs/src/examples/v-date-picker/prop-show-adjacent-months.vue, packages/docs/src/examples/v-date-picker/prop-show-sibling-months.vue, packages/docs/src/pages/en/components/date-pickers.md, packages/vuetify/src/components/VDatePicker/VDatePicker.ts, packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts, packages/vuetify/src/components/VDatePicker/__tests__/__snapshots__/VDatePicker.date.spec.ts.snap, packages/vuetify/src/components/VDatePicker/__tests__/__snapshots__/VDatePickerDateTable.spec.ts.snap, packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.ts
Adds possibility to display days from prev/next monhts
fixes #12237
playground
<details>
```vue
<template>
<v-container>
<v-date-picker
v-model="dates"
:picker-date.sync="pickerDate"
multiple
show-current="2021-01-02"
/>
<v-date-picker
v-model="dates"
:picker-date.sync="pickerDate"
multiple
show-current="2021-01-02"
/>
</v-container>
</template>
<script>
data: () => ({ dates: ['2020-11-29', '2021-01-01'], pickerDate: '2020-12' }),
}
</script>
```
</details>
=> feat(VDatePicker): `show-adjacent-months` prop

packages/docs/src/examples/border-radius/usage.vue
fixes #12632 a type in the usage example for border radius.
visually
<details>
```vue
```
</details>
=> docs(border-radius): fix usage example

packages/vuetify/src/components/VColorPicker/__tests__/__snapshots__/VColorPicker.spec.ts.snap, packages/vuetify/src/components/VRangeSlider/__tests__/__snapshots__/VRangeSlider.spec.ts.snap, packages/vuetify/src/components/VSlider/VSlider.ts, packages/vuetify/src/components/VSlider/__tests__/__snapshots__/VSlider.spec.ts.snap
fixes #12620
Input tag value from `VSlider` shall be mutated ONLY based on `this.internalValue` from
`VSlider`. Therefore, always disabling input tag in `VSlider` level will make sure its value is not
changed by other events (e.g. label click)
fixes #12620
unit testing & visually
<details>
```vue
```
</details>
=> fix(VSlider): disable input tag

packages/vuetify/src/components/VPagination/VPagination.ts
This resolves this #7510 feature request.
All it does is check if `total-visible` is set to `0` then it will display no items.
Solves the issue where one doesn't want to show any items like described in #7510.
Only tested visually.
<details>
```vue
<template>
<v-container>
<div>
<v-pagination
v-model="page"
:length="5"
:total-visible="0"
>
</v-pagination>
</div>
</v-container>
</template>
<script>
data: () => ({
page: 1,
}),
}
</script>
```
</details>
=> fix(VPagination): Add support for 0 totalVisible items

packages/vuetify/src/components/VCalendar/__tests__/VCalendarCategory.spec.ts, packages/vuetify/src/components/VCalendar/util/parser.ts
Update parser to return full category object
The parser is currently returning {categoryName}. It needed to return full category
During interval styling we want to read the whole category instead of just the name
Wrote a unit test for interval styling to make sure full category is being passed.
<details>
```vue
<template>
<v-container>
<v-calendar
type="category"
:categories="['Jeff', 'Nate']"
category-show-all
:interval-style="intervalStyle"
/>
</v-container>
</template>
<script>
data: () => ({
events: [
{
name: "Nate",
category: "Nate",
start: new Date(),
end: new Date()
}
]
}),
methods: {
intervalStyle(obj){
console.log(obj.category)
}
}
};
</script>
```
</details>
=> feat(VCalendar): update parser to return full category

packages/vuetify/src/components/VTabs/VTabs.sass, packages/vuetify/src/components/VWindow/VWindow.sass
Fixes #11971
#11971
visually
Applied on https://codepen.io/heiybb/pen/abdeVYZ
=> fix(VTabsItems): keep rounded corners during animations

packages/vuetify/src/components/VTooltip/VTooltip.ts
fixes #12360
#12360
visualy
<details>
```vue
<template>
<v-container>
<v-tooltip bottom>
<div v-on="on" v-bind="attrs">Hover me</div>
</template>
Tooltip
</v-tooltip>
</v-container>
</template>
<script>
}
</script>
```
</details>
=> fix(VTooltip): don't add role:button to activator

MIGRATION.md
Add the `v-chip` in the `outline` section of migration docs
When migration one of my projects, I noticed that the v-chip has this prop `outline` and the API changed in docs to `outlined`, just like other components, but it's not mentioned in the docs
I checked the docs of both Vuetify 1.5.x and 2.x:
- https://vuetifyjs.com/en/api/v-chip/#outlined
- https://v15.vuetifyjs.com/en/components/chips#api
=> docs(migration): outline changed to outlined in v-chip

packages/vuetify/src/components/VWindow/VWindow.ts
Stop click event propagation for prev/next buttons of VCarousel
Fixes #12676 
Done to fix issue #12676 
visually
<details>
```vue
<template>
<v-container>
<v-card @click="cardClick">
<v-carousel>
<v-carousel-item src="https://cdn.vuetifyjs.com/images/carousel/squirrel.jpg"></v-carousel-item>
<v-carousel-item src="https://cdn.vuetifyjs.com/images/carousel/sky.jpg"></v-carousel-item>
</v-carousel>
</v-card>
</v-container>
</template>
<script>
data: () => ({
//
}),
methods: {
cardClick: function () {
console.log('cardClick')
}
}
}
</script>
```
</details>
=> fix(VCarousel): stop event propagation for prev/next buttons

packages/vuetify/src/components/VCalendar/VCalendar.ts
fixes #12666
fixes #12666
close  #12666
visually
<details>
```vue
<template>
<v-container>
<v-row>
<v-calendar ref="calendar" type="4day" :start="start" :end="end" :events="events" @change="onChange" />
</v-col>
</v-row>
</v-container>
</template>
<script>
data () {
return {
start: "2020-11-23",
end: "2020-12-29",
events: []
}
},
methods: {
onChange({ start, end }) {
console.log("onChange:start", start)
console.log("onChange:end", end)
this.start = start.date
this.end = end.date
},
onPrevClick() {
this.$refs.calendar.prev()
},
onNextClick() {
this.$refs.calendar.next()
}
}
}
</script>
```
</details>
=> fix(VCalendar): resolve wrong relative day span for 4day

packages/vuetify/src/components/VRangeSlider/VRangeSlider.ts, packages/vuetify/src/components/VRangeSlider/__tests__/VRangeSlider.spec.ts
Display the Track color mentioned in the v-range-silder prop track-fill-color
fixes #12733 
Done to fix #12733
Previously wrong method was used to access the fill color
UT have been added and Visually 
<details>
```vue
<template>
<v-container>
<v-range-slider
v-model="range"
min="0"
max="360"
track-fill-color="red"
track-color="grey"
/>
<v-range-slider
v-model="range"
min="0"
max="360"
track-fill-color="rgba(255, 255, 0, 0.5)"
track-color="grey"
/>
<v-slider
v-model="single"
min="0"
max="100"
track-fill-color="green"
track-color="grey"
/>
</v-container>
</template>
<script>
data: () => {
//
return {
range: [10, 20],
single: [10],
}
},
}
</script>
```
</details>
=> fix(VRangeSlider): Displaying trackFillColor passed via prop

packages/docs/build/markdown-it.js
Fixes #12779
Anchors for headers starting with a non-latin character or number won't work.
Visually
=> fix(docs): fix anchors in non-latin translations

packages/vuetify/src/components/VImg/VImg.ts
fix #12784 cause new bug:
visually
<details>
```vue
<template>
<div id="app">
<v-app>
<v-container>
<v-row>
svg with height/width
<v-img src="https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/AJ_Digital_Camera.svg"></v-img>
</v-row>
<v-row>
svg no given height/width
<v-img src="https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/410.svg"></v-img>
</v-row>
<v-row>
data-url:
<v-img src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3Ccircle r='50' cx='50' cy='50' fill='tomato'/%3E%3Ccircle r='41' cx='47' cy='50' fill='orange'/%3E%3Ccircle r='33' cx='48' cy='53' fill='gold'/%3E%3Ccircle r='25' cx='49' cy='51' fill='yellowgreen'/%3E%3Ccircle r='17' cx='52' cy='50' fill='lightseagreen'/%3E%3Ccircle r='9' cx='55' cy='48' fill='teal'/%3E%3C/svg%3E" />
</v-row> …
```
=> fix(VImg): SVG size wrong after uncached load

packages/api-generator/src/helpers/variables.js, packages/docs/src/examples/v-text-field/prop-counter.vue, packages/docs/src/pages/en/components/text-fields.md, packages/vuetify/src/components/VTextField/VTextField.ts
=> feat(VTextField): add `counter` scoped slot

packages/docs/src/examples/v-dialog/prop-transitions.vue, packages/docs/src/pages/en/components/dialogs.md, packages/vuetify/src/components/transitions/index.ts, packages/vuetify/src/styles/generic/_transitions.scss, packages/vuetify/types/lib.d.ts
playground, docs
<details>
```vue
<template>
<div>
<v-dialog
transition="dialog-bottom-transition"
>
<v-btn
v-bind="attrs"
v-on="on"
>Open dialog from the bottom</v-btn>
</template>
<template #default="dialog">
<v-card>
<v-toolbar
dark
>Opening from the bottom</v-toolbar>
<v-card-text>
<div class="text-h2 pa-12">Hello world!</div>
</v-card-text>
<v-card-actions class="justify-end">
<v-btn
text
@click="dialog.value = false"
>Close</v-btn>
</v-card>
</template>
</v-dialog>
<v-dialog
transition="dialog-top-transition"
>
<v-btn
v-bind="attrs"
v-on="on"
>Open dialog from the top</v-btn>
</template>
<template …
```
=> feat(transitions): add dialog-top-transition

packages/docs/src/data/team.json
<details>
```vue
```
</details>
=> Add Judd Franklin as contributor

packages/vuetify/src/components/VCombobox/__tests__/VCombobox-multiple.spec.ts, packages/vuetify/src/components/VSelect/VSelect.ts
Fixed wrong Behaviour of combobox when using with keyboard
Done to fix issue #12781 
visually
<details>
```vue
<template>
<div id="app">
<v-row>
<v-combobox
:items="items"
multiple
outlined
dense
></v-combobox>
</v-col>
</v-row>
</v-container>
</v-app>
</div>
</template>
<script>
data () {
return {
select: ['Vuetify', 'Vue'],
items: [
'Programming',
'Design',
'Vue',
'Vuetify',
],
}
},
}
</script>
```
</details>
=> fix(VCombobox): fixed incorrect combobox behaviour

packages/docs/src/pages/en/getting-started/installation.md
<details>
```vue
```
</details>
=> fix: remove duplicated related section

packages/vuetify/src/composables/__tests__/tag.spec.ts, packages/vuetify/src/composables/index.ts, packages/vuetify/src/composables/tag.ts
PR for #12888
<details>
```vue
```
</details>
=> feat(tag): create new composable

packages/docs/src/examples/v-btn-fab/usage.vue, packages/docs/src/examples/v-btn/usage.vue, packages/vuetify/src/components/VAlert/__tests__/__snapshots__/VAlert.spec.ts.snap, packages/vuetify/src/components/VAppBar/__tests__/__snapshots__/VAppBarNavIcon.spec.ts.snap, packages/vuetify/src/components/VBottomNavigation/__tests__/__snapshots__/VBottomNavigation.spec.ts.snap, packages/vuetify/src/components/VBtn/VBtn.sass, packages/vuetify/src/components/VBtn/VBtn.ts, packages/vuetify/src/components/VBtn/__tests__/VBtn.spec.ts, packages/vuetify/src/components/VBtn/__tests__/__snapshots__/VBtn.spec.ts.snap, packages/vuetify/src/components/VCalendar/__tests__/__snapshots__/VCalendar.spec.ts.snap, packages/vuetify/src/components/VCalendar/__tests__/__snapshots__/VCalendarDaily.spec.ts.snap, packages/vuetify/src/components/VColorPicker/__tests__/__snapshots__/VColorPicker.spec.ts.snap, packages/vuetify/src/components/VColorPicker/__tests__/__snapshots__/VColorPickerEdit.spec.ts.snap, packages/vuetify/src/components/VDataIterator/__tests__/__snapshots__/VDataFooter.spec.ts.snap, packages/vuetify/src/components/VDataIterator/__tests__/__snapshots__/VDataIterator.spec.ts.snap, packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap, packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VEditDialog.spec.ts.snap, packages/vuetify/src/components/VDatePicker/__tests__/__snapshots__/VDatePicker.date.spec.ts.snap, packages/vuetify/src/components/VDatePicker/__tests__/__snapshots__/VDatePicker.month.spec.ts.snap, packages/vuetify/src/components/VDatePicker/__tests__/__snapshots__/VDatePickerHeader.spec.ts.snap
fixes #12903
related: #12892, #12845, #12814
<details>
v2.3: https://codepen.io/kaelwd/pen/oNzybwv  
v2.4: https://codepen.io/kaelwd/pen/abmKdWM
```vue
<template>
<v-container>
baseline: <br>
<v-btn>normal</v-btn>
<v-btn text>text</v-btn>
<v-btn plain>plain</v-btn>
<v-btn depressed>depressed</v-btn>
<v-btn outlined>outlined</v-btn>
<hr class="my-2">
coloured: <br>
<v-btn color="primary">normal</v-btn>
<v-btn
text
>
text
</v-btn>
<v-btn
plain
>
plain
</v-btn>
<v-btn
depressed
>
depressed
</v-btn>
<v-btn
outlined
>
outlined
</v-btn>
<hr class="my-2">
elevation: <br>
<v-btn elevation="5">
normal
</v-btn>
<v-btn
elevation="5"
text
>
text
</v-btn>
<v-btn
elevation="5"
plain
>
plain
</v-btn>
<v-btn
depressed
elevation="5"
> …
```
=> fix(VBtn): show background on non-elevated buttons, fix color states

packages/vuetify/src/composables/__tests__/border-radius.spec.ts, packages/vuetify/src/composables/border-radius.ts
Making compromises between Draft PR #12801 from which I was throwing ideas, and current PR #12886
* Instead of writing possible values of a type, write once, and create a type based on it
* Missing test cases
Yes, and is adding more.
=> feat(border-radius): missing test cases from another PR

packages/vuetify/src/composables/__tests__/border-radius.spec.ts, packages/vuetify/src/composables/border-radius.ts, packages/vuetify/src/composables/index.ts
PR for #12789
<details>
```vue
```
</details>
=> feat(border-radius): add new composable

packages/vuetify/src/composables/__tests__/dimensions.spec.ts, packages/vuetify/src/composables/dimensions.ts, packages/vuetify/src/composables/index.ts
Updated naming convention and process for composable and its unit tests to bring it more in line with current standards.
Working on #12692 and ran into consistency issues with how we handle classes and styles.
jest
=> refactor(dimensions): update code to unify process

packages/docs/src/pages/en/components/hover.md
The examples all show the new syntax `v-slot="{ hover }"`. Update the text to match the examples
The old syntax was deprecated with Vue 2.6.
=> docs(hover): updated deprecated syntax

packages/docs/src/data/team.json
New contributor on board!
<details>
```vue
```
</details>
=> docs(team): add ohadsh535

packages/api-generator/src/locale/en/v-autocomplete.json
Fix a wrong link in the description of [the prop](https://vuetifyjs.com/ja/api/v-autocomplete/#props).
There is no issue about it.
<details>
```vue
```
</details>
=> docs: fix a wrong link for filter example.

packages/docs/src/layouts/default/settings/Theme.vue
Fixed the OS-based dark mode as entering the documentation
Also, I changed the `addEventListener('change')` to `onchange` to comply with Safari on macOS < 11, as it actually gave me an error when I did it on my site
Having the automatic dark mode working properly is important for a good user experience
Visually only
<details>
```vue
```
</details>
=> docs(theme): fix OS-based dark mode

packages/docs/src/pages/en/components/cards.md, packages/docs/src/pages/en/components/images.md, packages/docs/src/pages/en/components/lists.md, packages/docs/src/pages/en/components/tabs.md, packages/docs/src/pages/en/features/accessibility.md
<details>
```vue
```
</details>
=> docs(components): add Vuetify store ads

packages/docs/src/pages/en/styles/text-and-typography.md
Currently the page [Styles and animations > Text & Typography > RTL Alignment](http://localhost:8081/en/styles/text-and-typography/#wrapping-and-overflow) has a link to [RTL](https://vuetifyjs.com/en/features/rtl/) which does **not exist**. 
I changed that link to point to [bidirectionality (LTR/RTL)](https://vuetifyjs.com/en/features/bidirectionality/) 
N/A
=> docs: fix broken link to RTL page

packages/vuetify/src/components/VPagination/VPagination.ts, packages/vuetify/src/components/VPagination/__tests__/__snapshots__/VPagination.spec.ts.snap
fixes #12953
#12953
updated existing test from ```src/components/VPagination/__tests__/VPagination.spec.ts``` 
<details>
```vue
<template>
<v-container>
<v-pagination
v-model="page"
:length="6"
/>
</v-container>
</template>
<script>
data () {
return {
page: 1,
}
},
}
</script>
```
</details>
=> fix(VPagination): add disabled attr to buttons (#12953)

packages/vuetify/src/components/VDataTable/VDataTableHeader.sass
fixes #12823
fixes #12823
**Cause**: when table header column has a sorting arrow icon, icon eventual height is bigger than its column header text `span` and will have impact on parent `th` `box-shadow` 
**Solution**: in `VDataTableHeader` level, set icon's `line-height: 0.9` to make sure its eventual shape does not exceeds header column bottom line.
close #12823
visually
<details>
```vue
<template>
<v-container>
<v-dialog :value="true">
<v-card>
<v-data-table
dark
dense
show-select
single-select
fixed-header
height="calc(100vh - 200px)"
:items-per-page="15"
:items="items"
>
</v-card>
</v-dialog>
</v-container>
</template>
<script>
data () {
return {
headers: [
{ text: "Name", value: "name" },
{ text: "Manufacture", value: "manufacture" …
```
=> fix(VDataTableHeader): decrease sort icon line height

packages/vuetify/src/components/VRating/VRating.ts
Set tabindex to 0 so we can tab to the button and press enter.
resolves #10820 
This makes the buttons generated by v-rating accessible.
fixes #10820 
Tested visually. Ran with NVDA, can tab to the buttons and aria-labels are read.
<details>
```vue
```
</details>
=> fix(VRating): make icons tab-accessible

packages/docs/src/pages/en/features/treeshaking.md
Fixes some typos and formatting issues in the `treeshaking.md` file
=> docs(treeshaking): fix grammar and formatting

packages/vuetify/src/components/VSelect/VSelect.ts, packages/vuetify/src/components/VSelect/__tests__/VSelect2.spec.ts, packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect2.spec.ts.snap
resolves #11584
#11584
I'm the original author of the `counter-value` feature :wave: 
locally
<details>
```vue
<template>
<v-container>
:items="items"
counter
:counter-value="v => (v || '').replace(v, 'test123')"
v-model="values"
:items="items"
counter
:counter-value="v => v.join(', ') + 'test123'"
multiple
<v-text-field
v-model="title"
counter
:counter-value="v => (v || '').replace(v, 'test123')"
</v-container>
</template>
<script>
data: () => ({
title: "",
items: ["foo", "bar", "fizz", "buzz"],
values: ["foo", "bar"],
value: null
})
};
</script>
```
</details>
=> fix(VSelect) add missing counter-value function support

packages/vuetify/src/locale/sk.ts
Fix `rating.ariaLabel.icon` translation key in sk.
Because it was wrong.
Carefully.
<details>
```vue
```
</details>
=> fix(locales): update `sk` translation

packages/docs/src/pages/en/getting-started/installation.md
Add alpha support for v3 in Vue CLI alert.
Added instructions to use nightly in webpack instructions.
Visually
- [ x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ x] My code follows the code style of this project.
- [ x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
=> docs: v3 install notes

packages/docs/src/pages/en/getting-started/installation.md
Added the installation process for Vuetify v3 Alpha on the `next` branch.
=> docs(installation.md) added v3 Alpha installation

packages/vuetify/src/components/VIcon/VIcon.tsx
update v-icon to use the tag composable
Consistency with other components
unit | visually 
<details>
```vue
<template>
<v-app>
<v-icon icon="mdi-home" />
<v-icon tag="button" icon="mdi-home" />
</v-app>
</template>
```
</details>
=> refactor(VIcon): update with tag composable

packages/docs/src/examples/v-alert/usage.vue
I fixed a typo.
Typos are not good.
Does not need a test.
=> Fix typo (`Im` to `I'm`)

packages/vuetify/src/components/VLayout/VLayoutItem.tsx, packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.sass, packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.tsx, packages/vuetify/src/components/VNavigationDrawer/_variables.scss, packages/vuetify/src/composables/layout.ts
- fixed layout integration with v-model and temporary props
- removed size prop from useLayoutItem, added width prop to nav drawer
- removed dense prop, can be done with just rail-width
- removed scss widths
<details>
```vue
<template>
<v-app class="v-application--is-ltr">
<v-theme-provider :theme="theme">
fixed
expand-on-hover
:aligned="aligned"
:bottom="bottom"
:mobile="mobile"
:right="right"
:temporary="temporary"
:floating="floating"
:rail="rail"
:src="src"
:rail-width="railWidth"
:class="src && 'white--text'"
>
<template #prepend v-if="prepend">
<div class="pa-2 py-5 text-truncate">
Prepend
</div>
</template>
<div class="pa-2" style="height: 100vh;">Fixed Left Default</div>
<template #append v-if="append"> …
```
=> feat: update nav-drawer layout functionality, removed stuff

packages/docs/src/pages/en/features/global-config.md
<details>
```vue
```
</details>
=> docs: add global defaults information

packages/docs/src/pages/en/getting-started/installation.md
<details>
```vue
```
</details>
=> docs: add usage section to installation page

packages/vuetify/src/components/VColorPicker/VColorPicker.ts, packages/vuetify/src/components/VColorPicker/VColorPickerSwatches.ts
fixes #13160
fixes #13160
close #13160
visually
<details>
```vue
<template>
<v-container>
<v-row>
<v-col>
<h3>Enabled</h3>
<v-color-picker show-swatches></v-color-picker>
</v-col>
<v-col>
<h3>Disabled</h3>
<v-color-picker show-swatches disabled></v-color-picker>
</v-col>
<v-col>
<h3>The problem</h3>
<p>
While canvas, inputs and sliders are all "disabled" and cannot be
interacted with, the swatches can still be used.
</p>
</v-col>
</v-row>
</v-container>
</template>
```
</details>
=> fix(VColorPicker): Allow swatches to be disabled

packages/vuetify/src/components/VBtn/VBtn.sass
Fix vicon increased specificity to overwrite commit overwriting vbtn left icon font-size
fixes #11294
<details>
```vue
```
</details>
=> fix(VBtn): override icon font-size with left/right props

packages/docs/src/pages/en/components/date-pickers.md
<details>
```vue
```
</details>
=> docs(date-pickers): update width description

packages/docs/src/pages/en/features/theme.md
<details>
```vue
```
</details>
=> docs(theme): update page for v3

packages/docs/src/examples/v-btn/prop-block.vue, packages/docs/src/examples/v-btn/prop-flat.vue, packages/docs/src/examples/v-btn/prop-icon.vue, packages/docs/src/examples/v-btn/prop-outlined.vue, packages/docs/src/examples/v-btn/prop-plain.vue, packages/docs/src/examples/v-btn/prop-rounded.vue, packages/docs/src/examples/v-btn/prop-sizing.vue, packages/docs/src/examples/v-btn/prop-text.vue, packages/docs/src/pages/en/components/buttons.md
<details>
```vue
```
</details>
=> docs: update btn examples

packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts, packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.date.spec.ts, packages/vuetify/src/components/VDatePicker/__tests__/__snapshots__/VDatePickerDateTable.spec.ts.snap
fixes #13058
fixes #13058
add unit test case
<details>
```vue
<template>
<v-container>
<v-date-picker
v-model="picker"
first-day-of-week="1"
show-week
</v-container>
</template>
<script>
data: () => ({
picker: '2021-02-01',
}),
};
</script>
```
</details>
=> fix(VDatePicker): correctly show weeks and dates

packages/docs/src/pages/en/styles/float.md, packages/vuetify/src/styles/settings/_utilities.scss, packages/vuetify/src/styles/tools/_utilities.sass, packages/vuetify/src/styles/utilities/_index.sass
fixes #11874
playground
<details>
```vue
<template>
<v-container floating>
<v-btn
block
@click="$vuetify.rtl = !$vuetify.rtl"
>{{ $vuetify.rtl ? 'RTL' : 'LTR' }}</v-btn>
<v-card
v-for="float in ['left', 'right', 'start', 'end']"
:key="float"
class="ma-6"
>
<v-card-text>
<div
:class="`float-${float} me-4 ms-4 yellow text-h4`"
style="background: yellow"
>{{ float }}</div>
<div>{{ 'foo '.repeat(300) }} </div>
</v-card-text>
</v-card>
</v-container>
</template>
```
</details>
=> feat: `float-<bp>-start` and `float-<bp>-end` utility classes

packages/docs/src/components/doc/ColorPalette.vue, packages/docs/src/examples/color/classes.vue, packages/docs/src/examples/color/text-classes.vue, packages/docs/src/pages/en/styles/colors.md, packages/vuetify/src/styles/generic/_colors.scss
```
// v2
.indigo
.indigo--text
.indigo.lighten-2
.indigo--text.text--darken-1
// v3
.bg-indigo
.text-indigo
.bg-indigo-lighten-2
.text-indigo-darken-1
```
This aligns generic color classes with those generated from the theme system, which means that the generic ones can be used in `color` prop without any additional work.
This is a breaking change.
<details>
```vue
```
</details>
=> feat: change generic color class names

packages/api-generator/src/helpers/parsing.js, packages/api-generator/src/index.js, packages/vuetify/src/components/VAvatar/VAvatar.tsx, packages/vuetify/src/composables/border-radius.ts, packages/vuetify/src/util/makeProps.ts
<details>
```vue
```
</details>
=> fix(api-gen): generate correct prop default values

packages/docs/src/components/api/ApiTable.vue
resolves #13202
resolves #13202 
But I'm not sure, maybe it would be better to move the anchor formation into a method?
https://github.com/vuetifyjs/vuetify/issues/13202
<details>
```vue
```
</details>
=> docs: specify props anchors

packages/docs/src/pages/en/features/internationalization.md
To make the term "Traditional Chinese"(正體中文) more clear for zh_tw (zh_hant)
<details>
```vue
```
</details>
=> docs(internationalization): update Traditional Chinese text

packages/docs/src/pages/en/components/buttons.md
`**white--text**` is rendered as "white–text" on the website, attempting to fix that
none
=> docs(buttons): update class name from bold to code

packages/vuetify/src/components/VRangeSlider/VRangeSlider.ts, packages/vuetify/src/components/VSlider/VSlider.ts, packages/vuetify/src/components/VSlider/__tests__/VSlider.spec.ts
fixes #13259 
fixes #13259 
add unit test case
<details>
```vue
<template>
<v-container>
<v-slider
v-model="curVal"
@change="onChange"
/>
</v-container>
</template>
<script>
data: () => ({
curVal: 4
}),
methods: {
onChange(val) {
console.log(val)
}
}
};
</script>
```
</details>
=> fix(VSlider): support touch and drag

README.md
Fixed readme link url.
<details>
```vue
```
</details>
=> docs(readme): fix @vuetify/preset link url

packages/vuetify/src/components/VSelect/VSelect.sass, packages/vuetify/src/components/VSelect/_variables.scss
fixes #13007
I fixed it so that VSelect baseline dose not changes when empty string is selected
Without this fix, VSelect baseline would change when empty string is selected.
visually
---
**before behavior**  
**after behavior**  
<details>
```vue
<template>
<v-container>
<v-row align="baseline">
<v-col>
Some label
</v-col>
<v-col cols="10">
<v-select
value="Item 2"
:items="items"
hide-details
/>
</v-col>
</v-row>
</v-container>
</template>
<script>
data: () => {
return { items: ['', 'Item 2', 'Item 3'] }
},
}
</script>
```
</details>
=> fix(VSelect): specify min-height 10px

packages/docs/src/pages/en/components/navigation-drawers.md
Fix a typo
<details>
```vue
```
</details>
=> docs(VNavigationDrawer): correct a typo

packages/docs/src/pages/en/getting-started/upgrade-guide.md
Added a note to the `v-toolbar` section in the upgrade guide about the `v-toolbar-side-icon`
The upgrade mentions a migration from `<v-toolbar>` to `<v-app-bar>`, but would have been helpful to also mention the change from `<v-toolbar-side-icon>` to `<v-app-bar-nav-icon>`.
N/A
N/A
=> docs(upgrade-guide): add note about `v-app-bar-nav-icon`

.eslintrc.js, packages/vuetify/src/components/VGrid/VCol.ts, packages/vuetify/src/components/VImg/VImg.tsx, packages/vuetify/src/components/VLayout/VLayout.tsx, packages/vuetify/src/components/VLayout/VLayoutItem.tsx, packages/vuetify/src/components/VResponsive/VResponsive.tsx, packages/vuetify/src/components/transitions/createTransition.ts, packages/vuetify/src/composables/color.ts, packages/vuetify/src/composables/delay.ts, packages/vuetify/src/composables/group.ts, packages/vuetify/src/composables/icons.tsx, packages/vuetify/src/composables/layout.ts, packages/vuetify/src/composables/proxiedModel.ts, packages/vuetify/src/composables/scroll.ts, packages/vuetify/src/composables/theme.ts, packages/vuetify/src/directives/scroll/__tests__/scroll.spec.ts, packages/vuetify/src/framework.ts, packages/vuetify/src/globals.d.ts, packages/vuetify/src/iconsets/fa.ts, packages/vuetify/src/iconsets/fa4.ts, packages/vuetify/src/iconsets/md.ts, packages/vuetify/src/iconsets/mdi-svg.ts, packages/vuetify/src/iconsets/mdi.ts, packages/vuetify/src/util/__tests__/console.spec.ts, packages/vuetify/src/util/__tests__/helpers.spec.ts, packages/vuetify/src/util/color/transformCIELAB.ts, packages/vuetify/src/util/createSimpleFunctional.ts, packages/vuetify/src/util/helpers.ts, packages/vuetify/src/util/useDirective.ts
@johnleider can stop complaining in PR reviews now
=> style: sort imported members

packages/vuetify/src/components/VSlideGroup/VSlideGroup.sass, packages/vuetify/src/components/VSlideGroup/VSlideGroup.ts
fixes #12293
partically fixes #10673
As per suggestions in #10673, `VSlideGroup` should determine swipe intent (horizontal or vertical) first, then using swipe intent to only allow one of horizontal/vertical swipe gestures between each `onTouchStart` and `onTouchEnd` session
fixes #12293
partically fixes #10673
fixes #12293
partically fixes #10673
visually
<details>
```vue
<template>
<v-container>
<v-slide-group>
<v-slide-item v-for="i in 10" :key="i" class="ma-5">
<v-card color="#eeeeee" elevation="10" max-width="300px">
<v-img
src="https://cdn.vuetifyjs.com/images/cards/sunshine.jpg"
height="200px"
></v-img>
<v-card-text>
SWITCH TO MOBILE
Try swiping up/down while still keeping finger on these slides
</v-card-text> …
```
=> fix(VSlideGroup): detect horizontal/vertical swipe intent

packages/docs/src/examples/v-card/misc-horizontal-cards.vue
Updated a VCard example from the old `.headline` class to the new `.text-h5` class.
The VCard example uses the old `.headline` class.
N/A
=> docs: updated example from .headline to .text-h5

packages/docs/src/pages/en/components/floating-action-buttons.md
This fixes a small typo found while using the documentation.
=> fix: small typo in the floating action button page

packages/docs/src/examples/v-banner/event-icon-click.vue
This fixes a typo found while using the documentation.
=> Change `Connecting Settings` to `Connection Settings`

packages/docs/src/examples/v-hover/misc-hover-list.vue
fixes https://github.com/vuetifyjs/vuetify/issues/13406
lorempixel is now unavailable.
visually
<details>
```vue
```
</details>
=> docs(v-hover): fix broken image links

packages/api-generator/src/locale/en/generic.json, packages/api-generator/src/locale/en/v-dialog.json, packages/docs/src/pages/en/components/dialogs.md
Updates documentation for generic, v-dialog api and component page solving #13424
https://github.com/vuetifyjs/vuetify/issues/13424
Visually
=> docs: updated persistent description for v-dialog #13424 

packages/docs/src/examples/v-sparkline/prop-fill.vue
In [this part of the v-sparkline doc](https://vuetifyjs.com/en/components/sparklines/#fill), you should be able to choose the color / gradient of the sparkline, but you cannot, because the `:gradient` prop refers to the `gradient` variable, which doesn't exist (it was renamed `selectedGradient` in [this commit](https://github.com/vuetifyjs/vuetify/commit/34a37a06fd49e4c70f47b17e46eaa56716250283#diff-d90da49a53047d3816d1eea16b8e696a62dacb07a00c8aac09d6d523d1a7e64a))
If fixes the bug described above
Codepen from your documentation: https://codepen.io/bokub/pen/zYNRyXV
Codepen after my modification: https://codepen.io/bokub/pen/ExZQGMq
=> docs(v-sparkline): fix gradient selection in v-sparkline example

packages/vuetify/src/components/VCalendar/VCalendarCategory.sass, packages/vuetify/src/components/VCalendar/VCalendarDaily.sass, packages/vuetify/src/components/VSelect/VSelect.sass, packages/vuetify/src/components/VWindow/VWindow.sass
This will fix a Bug which makes it impossible to use VSelect in projects
Currently using VSelect causes the following error:
```
SassError: Expected identifier.
╷
68 │       position: relative
│                         ^
╵
[...]\VSelect\VSelect.sass 68:25  root stylesheet
```
This PR will fix this issue by removing unnecessary whitespace in the related file.
This has been tested visually. Removing the whitespace got rid of the error
<details>
```vue
```
</details>
=> fix(VSelect): resolve "Expected identifier." error

packages/docs/src/pages/en/components/selects.md
This documentation says that its example shouldn't exist, which I assume is a typo.
<details>
```vue
```
</details>
=> docs(selects): update readonly example description

packages/vuetify/src/locale/ja.ts
translated fully ja.ts.
fixed for rating ariaLabel.
Thare are missing part in japanese translation.
none
<details>
```vue
```
</details>
=> fix(locale): update japanese translation

packages/vuetify/src/components/VBreadcrumbs/_variables.scss
$breadcrumbs-padding was defined twice:
```scss
$breadcrumbs-padding: 18px 12px !default;
$breadcrumbs-padding: 0 14px !default;
```
I left only the first definition.
To reduce confusion
Using common sense
N/A
=> fix(VBreadcrumbs): remove duplicate scss var

packages/vuetify/src/components/VCheckbox/VCheckbox.sass, packages/vuetify/src/components/VCheckbox/_variables.scss
fixes https://github.com/vuetifyjs/vuetify/issues/11998
visually
<details>
```vue
<template>
<v-container class="grey lighten-5">
<v-row dense>
<v-col cols="2">
<v-text-field label="This is"></v-text-field>
</v-col>
<v-col cols="2">
<v-checkbox label="good"></v-checkbox>
</v-col>
</v-row>
<v-row dense>
<v-col cols="2">
<v-text-field label="This is" dense></v-text-field>
</v-col>
<v-col cols="2">
<v-checkbox label="bad" dense></v-checkbox>
</v-col>
</v-row>
<v-row dense>
<v-col cols="2">
<v-text-field label="This is" dense></v-text-field>
</v-col>
<v-col cols="2">
<v-checkbox label="bad" dense></v-checkbox>
</v-col>
</v-row>
</v-container>
</v-app>
</template>
<script>
data: () => ({
}),
}
</script>
```
</details>
=> fix(VCheckbox): add variable checkbox-dense-padding-top

packages/docs/src/pages/en/getting-started/installation.md
"if you are you looking" wrong
"if you are looking" right :)
<details>
```vue
```
</details>
=> docs(installation): fix typo

packages/docs/src/pages/en/about/sponsors-and-backers.md
Markdown links like [foo](bar) link relative to the current page.  You must explicitly add `mailto:` for browsers to interpret it as email.
=> docs(sponsors-and-backers.md): update sponsors link markdown

packages/api-generator/src/locale/en/v-data-footer.json, packages/api-generator/src/maps/v-data-footer.js
The "pageText" slot specified in the documentation does not work. [https://codepen.io/irinablagun/pen/mdRKRbM](https://codepen.io/irinablagun/pen/mdRKRbM)
visually
<details>
```vue
```
</details>
=> docs(v-data-footer): change slot name

packages/vuetify/types/lib.d.ts
fixes https://github.com/vuetifyjs/vuetify/issues/13385
none
<details>
```vue
```
</details>
=> fix(VAppBarTitle): export VAppBarTitle types

packages/docs/src/pages/en/components/banners.md, packages/docs/src/pages/en/components/dividers.md
Added changes to divider and banner for v3
<details>
```vue
```
</details>
=> docs: added changes to divider and banner for v3

packages/vuetify/src/components/VIcon/VIcon.sass, packages/vuetify/src/components/VIcon/_variables.scss, packages/vuetify/src/composables/__tests__/__snapshots__/theme.spec.ts.snap, packages/vuetify/src/composables/theme.ts
The default implementation of `v-icon` did not match specification. In addition, I:
* Updated default and disabled color
* Updated naming for left/right to use start/end for variable names for better consistency
* Added new css and sass variables for icon and disabled opacities
* Added ltr/rtl support
* Cleaned up styles
Match MD specification <https://material.io/design/iconography/system-icons.html#color>
visually, snapshots
<details>
```vue
<template>
<v-app class="v-application--is-ltr">
<v-container>
<v-icon icon="mdi-vuetify" class="mr-4" />
<v-icon icon="mdi-vuetify" disabled />
<v-theme-provider theme="dark">
<v-icon icon="mdi-vuetify" class="mr-4" />
<v-icon icon="mdi-vuetify" disabled />
</v-theme-provider>
<h1>Density</h1>
<h2>Default</h2>
<div>
<v-btn class="mr-4" icon="mdi …
```
=> refactor(VIcon): update default color, abstract variables

packages/docs/src/pages/en/features/icon-fonts.md, packages/docs/src/pages/en/features/presets.md, packages/docs/src/pages/en/getting-started/frequently-asked-questions.md, packages/docs/src/pages/en/getting-started/unit-testing.md, packages/docs/src/pages/en/getting-started/upgrade-guide.md
Visually
<details>
```vue
```
</details>
=> docs(ads): add vuetify ads.

packages/vuetify/src/components/VBtn/VBtn.sass, packages/vuetify/src/components/VIcon/VIcon.sass, packages/vuetify/src/components/VIcon/VIcon.tsx, packages/vuetify/src/components/VIcon/__tests__/VIcon.spec.ts, packages/vuetify/src/components/VIcon/_variables.scss, packages/vuetify/src/composables/__tests__/__snapshots__/theme.spec.ts.snap, packages/vuetify/src/composables/theme.ts
reverts icon color changes from https://github.com/vuetifyjs/vuetify/pull/13561
with the changes from #13561 it becomes increasingly complex to make icon respect parent color decisions when used inside other components. we'd have to add `color: inherit/currentColor` classes for every possible situation when an icon could appear inside another component. additionally, the changes made it so that icon did not respect color class when doing something like 
```
<div class="bg-primary">
<v-icon icon="$close" />
</div>
```
playground, tests
<details>
```vue
<template>
<v-app class="fill-height">
<input type="checkbox" :checked="current === 'dark'" @change="current = current === 'dark' ? 'light' : 'dark'">theme
<v-icon icon="$close" />
<v-icon icon="$close" color="primary" />
<v-icon …
```
=> feat(VIcon): revert color changes

packages/vuetify/src/components/VBtn/VBtn.tsx
<details>
```vue
<template>
<v-app class="fill-height">
<input type="checkbox" :checked="current === 'dark'" @change="current = current === 'dark' ? 'light' : 'dark'">
<div class="pa-10">
<div class="d-flex flex-column">
icon prop
<div class="d-flex">
<v-btn icon="$close" />
<v-btn icon="$close" disabled />
</div>
icon prop with text
<div class="d-flex">
<v-btn icon="$close" text />
<v-btn icon="$close" text disabled />
</div>
icon prop with plain
<div class="d-flex">
<v-btn icon="$close" plain />
<v-btn icon="$close" plain disabled />
</div>
icon prop with outlined
<div class="d-flex">
<v-btn icon="$close" outlined />
<v-btn icon="$close" outlined disabled />
</div>
</div>
</div>
</v-app>
</template>
<script>
import { useTheme } from '../src/composables/theme' …
```
=> feat(VBtn): set default icon style to filled color

packages/api-generator/src/locale/en/v-btn.json, packages/vuetify/src/components/VAppBar/__tests__/__snapshots__/VAppBarNavIcon.spec.tsx.snap, packages/vuetify/src/components/VBtn/VBtn.sass, packages/vuetify/src/components/VBtn/VBtn.tsx, packages/vuetify/src/components/VBtn/_mixins.scss, packages/vuetify/src/components/VBtn/_variables.scss, packages/vuetify/src/components/VIcon/VIcon.sass
<details>
```vue
<template>
<v-app>
<v-container>
<v-btn prepend-icon="mdi-vuetify">
Prepend
</v-btn>
<div class="my-6" />
<v-btn prepend-icon="mdi-vuetify" size="x-large">
Prepend
</v-btn>
<div class="my-6" />
<v-btn prepend-icon="mdi-vuetify" stacked>
Prepend
</v-btn>
<div class="my-6" />
<v-btn prepend-icon="mdi-vuetify" stacked density="comfortable">
Prepend
</v-btn>
<div class="my-6" />
<v-btn prepend-icon="mdi-vuetify" stacked density="compact">
Prepend
</v-btn>
<div class="my-6" />
<v-btn stacked>
<v-icon icon="mdi-vuetify" />
</v-btn>
</v-container>
</v-app>
</template>
```
</details>
=> feat(VBtn): add stacked and prepend/append icon props

.eslintrc.js, packages/vuetify/src/composables/icons.tsx
<details>
```vue
```
</details>
=> chore(eslint: add jsx-quotes rule

packages/vuetify/src/components/VBadge/VBadge.sass
Fixes #13425 setting height and width to icon.
It fixes the issue mentioned above.
Visually with the playground and the reproduction link in the issue.
<details>
```vue
<template>
<v-container>
<v-badge
bordered
color="error"
icon="mdi-account"
overlap
>
<v-btn
class="white--text"
color="error"
depressed
>
Test
</v-btn>
</v-badge>
</v-container>
</template>
<script>
data: () => ({
}),
}
</script>
```
</details>
=> fix(VBadge): fix icon size when using svg

packages/vuetify/src/components/VAppBar/VAppBar.sass, packages/vuetify/src/components/VAppBar/VAppBar.tsx, packages/vuetify/src/components/VAppBar/_variables.scss, packages/vuetify/src/components/VBottomNavigation/VBottomNavigation.sass, packages/vuetify/src/components/VBottomNavigation/VBottomNavigation.tsx, packages/vuetify/src/components/VLayout/VLayout.sass, packages/vuetify/src/components/VLayout/VLayoutItem.sass, packages/vuetify/src/components/VLayout/VLayoutItem.tsx, packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.sass, packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.tsx, packages/vuetify/src/components/VNavigationDrawer/__tests__/VNavigationDrawer.spec.tsx, packages/vuetify/src/components/VNavigationDrawer/__tests__/__snapshots__/VNavigationDrawer.spec.tsx.snap, packages/vuetify/src/components/VNavigationDrawer/_variables.scss, packages/vuetify/src/composables/layout.ts, packages/vuetify/src/composables/proxiedModel.ts
adds support in layout composable for active/inactive items that retain their own size while impacting layout (or not)
- removed position composable from both nav-drawer and app-bar. it make _no_ sense together with layout composable. we are re-using a composable for a completely different use-case. @johnleider ping me if you want to discuss this (I will die on this hill).
- added `position` prop to app-bar and nav-drawer
<details>
```vue
<template>
<v-app>
<v-theme-provider
:key="String(dark)"
:theme="dark ? 'dark' : 'light'"
>
:expand-on-hover="hover"
:mobile="mobile"
:position="bottom ? 'bottom' : right ? 'right' : 'left'"
:temporary="temporary"
:rail="rail"
:src="src"
:class="src && 'white--text'"
:permanent="permanent"
>
<template v-if="prepend" …
```
=> feat: add support for active/inactive layout items

packages/docs/src/pages/en/components/cards.md
<details>
```vue
```
</details>
=> docs(v-card): Change outdated v-flex to v-col

packages/vuetify/src/components/VWindow/VWindow.sass
Fixes #13360
Visually
<details>
```vue
<v-window show-arrows>
<template v-slot:prev="{ on, attrs }">
<v-btn
color="success"
v-bind="attrs"
v-on="on"
>Previous slide</v-btn>
</template>
<template v-slot:next="{ on, attrs }">
<v-btn
color="info"
v-bind="attrs"
v-on="on"
>Next slide</v-btn>
</template>
<v-window-item
v-for="n in 5"
:key="`card-${n}`"
>
<v-card
color="grey"
height="200"
>
<v-row
class="fill-height"
align="center"
justify="center"
>
<h1
style="font-size: 5rem;"
class="white--text"
>
Slide {{ n }}
</h1>
</v-row>
</v-card>
</v-window-item>
</v-window>
```
</details>
=> fix(VWindow): transition snap with different content height

packages/vuetify/src/components/VDataIterator/VDataIterator.ts
fixes #13677
https://github.com/vuetifyjs/vuetify/issues/13677
There was no test for this feature (or I missed them), so I don't add unit tests. I test with my real example and it fixes the problem.
<details>
```vue
<template>
<v-app>
<v-container>
<v-data-table
:headers="table_headers"
:items="table_data"
item-key="id"
show-select
</v-container>
</v-app>
</template>
<script>
module.exports = {
data: function() {
return {
table_data: [
{
"id": 1,
"column1": "Toto",
"column2": "Tutu"
},
{
"id": 2,
"column1": "Toto",
"column2": "Tutu"
},
{
"id": 3,
"column1": "Toto",
"column2": "Tutu"
},
{
"id": 4,
"column1": "Toto",
"column2": "Tutu"
}
],
table_headers: [
{align: "left", text: "Column 1", value: "column1"},
{align: "left", text: …
```
=> fix(VDataIterator): use itemKey instead of name for select

BACKERS.md, packages/docs/src/components/team/TeamMember.vue, packages/docs/src/examples/v-autocomplete/misc-api-search.vue, packages/docs/src/pages/en/features/sass-variables.md, packages/docs/src/pages/en/getting-started/frequently-asked-questions.md, packages/docs/src/pages/en/getting-started/release-notes.md, packages/docs/src/pages/en/getting-started/unit-testing.md
Github -> GitHub
<details>
```vue
```
</details>
=> docs: fix GitHub format

packages/docs/src/components/app/Code.vue
=> docs: fix selection color in prism for dark theme

packages/docs/src/pages/en/getting-started/upgrade-guide.md
Added a note to the `v-text-field` section in the upgrade guide about the the removal of icon callback props.
Props like `prepend-inner-icon-cb` no longer work after upgrading, and I noticed they are not mentioned in the new API.
N/A
N/A
=> docs(upgrade-guide.md): add prepend/append-icon-cb removal

packages/vuetify/src/mixins/activatable/index.ts
Fixes #13755
<details>
```vue
```
</details>
=> fix(VMenu): activator should not return non Element nodes

packages/vuetify/src/components/VApp/VApp.sass
fixes #13821 
All the calculations assume the v-app was relatively positioned, except it wasn't, only the v-application--wrap was relatively positioned leading to the demonstrated bug 
Visually
<details>
```vue
```
</details>
=> fix(VMenu): apply position:relative to v-app

packages/api-generator/src/maps/$vuetify.js, packages/api-generator/src/maps/vuetify.js, packages/docs/src/components/api/ApiTable.vue, packages/vuetify/src/services/goto/index.ts, packages/vuetify/types/index.d.ts, packages/vuetify/types/services/goto.d.ts
=> fix(types): add missing `goTo` types

packages/docs/src/examples/flex/flex-wrap-reverse.vue, packages/docs/src/examples/flex/flex-wrap.vue
Added a serial number to each item in the examples of `flex-wrap` and `flex-wrap-reverse`
Right now, example for 'flex-wrap-reverse' and 'flex-wrap' visually look the same. Adding a serial number to each item will clarify how the items are arranged
Not tested
<details>
```vue
```
</details>
=> docs(flex): add iteration num to example template

packages/docs/src/examples/v-combobox/misc-advanced.vue
Right now, the "close" icon (x) for the [Misc - Advanced custom options](https://vuetifyjs.com/en/components/combobox/#advanced-custom-options) inside the combobox documentation is missing the `mdi` prefix, so it's displaying the word `close` instead.
Looks a bit odd, and I'm guessing someone just forgot to add the `mdi` prefix, since the `close` word it's inside a `v-icon` component.
Tested on my local environment only. It's just a small documentation fix.
<details>
```vue
<template>
<v-combobox
:filter="filter"
:hide-no-data="!search"
:items="items"
hide-selected
label="Search for an option"
multiple
small-chips
solo
>
<template v-slot:no-data>
<v-list-item>
<span class="subheading">Create</span>
<v-chip …
```
=> docs(v-combobox): fix close icon - misc advanced custom options

packages/docs/.eslintrc.js, packages/docs/src/crowdin.template.html, packages/docs/src/registerServiceWorker.js, packages/vuetify/.eslintrc.js, packages/vuetify/src/components/VTimePicker/__tests__/VTimePicker.spec.ts, packages/vuetify/src/util/helpers.ts
<details>
```vue
```
</details>
=> refactor: replace 'var' with 'let' and 'const'

packages/vuetify/types/lib.d.ts
=> fix(types): declare vuetify/lib/services/goto module

packages/vuetify/src/components/VAppBar/__tests__/__snapshots__/VAppBarNavIcon.spec.tsx.snap, packages/vuetify/src/components/VBtn/VBtn.tsx, packages/vuetify/src/components/VBtn/_variables.scss, packages/vuetify/src/components/VCard/VCard.sass, packages/vuetify/src/components/VCard/VCard.tsx, packages/vuetify/src/components/VCard/__tests__/__snapshots__/VCard.spec.ts.snap, packages/vuetify/src/components/VCard/_variables.scss, packages/vuetify/src/components/VList/VList.sass, packages/vuetify/src/components/VList/VListItem.tsx, packages/vuetify/src/components/VList/__tests__/__snapshots__/VListItem.spec.ts.snap, packages/vuetify/src/components/VList/_variables.scss, packages/vuetify/src/composables/variant.tsx, packages/vuetify/src/styles/tools/_variant.sass
Alternative to #13689 but only for components with variants.
Also fixes default text color for link buttons.
<details>
```vue
<template>
<v-app>
<v-container>
<div class="text-h5 ma-2">v-btn</div>
<template v-for="variant in ['contained', 'outlined', 'text', 'plain', 'contained-text']" :key="variant">
<div class="mb-12">
<v-btn class="mr-6" :variant="variant" link to="/page1">
{{ variant }} variant
</v-btn>
<v-btn color="primary" :variant="variant" link>
{{ variant }} variant
</v-btn>
</div>
</template>
<div class="text-h5 ma-2">v-list</div>
<template v-for="variant in ['contained', 'outlined', 'text', 'plain', 'contained-text']" :key="variant">
<v-list :subheader="variant + ' variant'">
<v-list-item title="Default" to="/page2" :variant="variant" />
<v-list-item title="Colored" link …
```
=> feat: add contained-text variant

packages/vuetify/src/components/VBanner/VBanner.sass, packages/vuetify/src/components/VBanner/VBanner.tsx, packages/vuetify/src/components/VBanner/VBannerActions.ts, packages/vuetify/src/components/VBanner/VBannerAvatar.tsx, packages/vuetify/src/components/VBanner/VBannerContent.ts, packages/vuetify/src/components/VBanner/VBannerText.ts, packages/vuetify/src/components/VBanner/_variables.scss, packages/vuetify/src/components/VBanner/index.ts, packages/vuetify/src/components/VBtn/VBtn.sass, packages/vuetify/src/components/VBtn/_variables.scss
* removed default color
* fixed multi-line support with clamping
* changed two-line/three-line props to lines="two/three"
* created new helper components
Refactored `v-banner` using updated coding styling established in `v-card` and `v-list`. Removed default color and improved line clamp functionality.
* add line-clamping
* add text prop and slot
* bring in line with newer components
* remove ltr/rtl usage
* remove default color
<details>
```vue
<template>
<v-app class="v-application--is-ltr">
<div
class="ma-12 pa-12 grey lighten-5"
style="min-height: 600vh;"
>
<div style="max-width: 360px;">
<v-banner mobile>
<v-banner-text>
One line text string with one action
</v-banner-text>
<template #actions>
<v-btn>Action</v-btn>
</template>
</v-banner>
<div class="my-12"></div>
<v-banner mobile …
```
=> refactor(VBanner): update code with current standards

packages/api-generator/src/export.js, packages/api-generator/src/index.js, packages/vuetify/package.json
just re-enabled old generation of vetur and web-types definitions
<details>
```vue
```
</details>
=> chore(api): re-enable generation of vetur and web-types

packages/docs/src/examples/v-btn-fab/misc-speed-dial.vue
Removed unused computed property in the speed dial demo of FAB.
While I read the docs, I realise there is an unused computed property in the speed dial demo of FAB.
I just search in the code for "activeFab" and no usage found.
<details>
```vue
```
</details>
=> docs(fab): remove unused computed property

packages/vuetify/src/components/VAlert/VAlert.sass, packages/vuetify/src/components/VAlert/_variables.scss, packages/vuetify/src/components/VBadge/VBadge.sass, packages/vuetify/src/components/VBtn/VBtn.sass, packages/vuetify/src/components/VBtn/_variables.scss, packages/vuetify/src/components/VIcon/VIcon.sass, packages/vuetify/src/components/VIcon/_variables.scss
<details>
<summary>Playground</summary>
```html
<template>
<v-app class="v-application--is-ltr">
<v-container>
<h1>Density</h1>
<h2>Default</h2>
<div>
<v-btn class="mr-4">
button
</v-btn>
<v-btn class="mr-4" flat>
button
</v-btn>
<v-btn class="mr-4" outlined>
button
</v-btn>
<v-btn class="mr-4" text>
button
</v-btn>
<v-btn class="mr-4" plain>
button
</v-btn>
<v-btn class="mr-4" icon="mdi mdi-vuetify" plain />
<v-btn class="mr-4" icon="mdi mdi-vuetify" />
</div>
<h2 class="mt-6">Comfortable</h2>
<div>
<v-btn class="mr-4" density="comfortable">
button
</v-btn>
<v-btn class="mr-4" flat density="comfortable">
button
</v-btn>
<v-btn class="mr-4" outlined density="comfortable">
button
</v-btn>
<v-btn class="mr-4" text density="comfortable">
button
</v-btn>
<v-btn class="mr-4" plain …
```
=> fix(VIcon): size with ems instead of px

packages/vuetify/src/composables/__tests__/group.spec.ts, packages/vuetify/src/composables/group.ts, packages/vuetify/src/util/helpers.ts
<details>
```vue
```
</details>
=> feat(group): remove need for index prop

packages/vuetify/src/components/VDataIterator/VDataIterator.ts, packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts
closes #14006
<details>
```vue
<template>
<v-app>
<v-data-table
item-key="id"
show-select
:footer-props='{ itemsPerPageOptions: [5]}'
/>
</v-app>
</template>
<script>
data () {
return {
selected: [],
headers: [
{ text: 'ID', value: 'id' },
{ text: 'Text', value: 'text' },
],
desserts: [],
}
},
mounted () {
for (let i = 1; i <= 8; i++) {
this.desserts.push({ id: i, text: 'Text ' + i })
}
},
}
</script>
```
</details>
=> fix(VDataTable): selection bug when using numbers as item-key

packages/docs/build/generate-routes.js, packages/docs/build/prerender.js, packages/docs/build/sitemap.js
sitemap did not include api paths because reasons
built locally
<details>
```vue
```
</details>
=> docs: make sure sitemap includes all paths

packages/docs/src/pages/en/components/forms.md
Fix dead link for Vee-Validate
Fix dead link for Vee-Validate in Forms component docs
Replace a dead link with the current link to documentation.
No tests necessary.
<details>
```vue
```
</details>
=> docs(forms): update Vee-Validate link

packages/vuetify/src/components/VSlider/VSlider.ts
Fixes #14114
Fixes #14114
Visually with playground
<details>
```vue
<template>
<v-container>
<p>Select param:</p>
<v-btn @click="selectedSliderParam = 0">Param 1</v-btn>
<v-btn @click="selectedSliderParam = 1">Param 2</v-btn>
<v-btn @click="selectedSliderParam = 2">Param 3</v-btn>
<p class="pt-4">Slider value: {{ value }}</p>
<p>Param value: {{ currentSliderParam }}</p>
<v-slider
:min="currentSliderParam.min"
:max="currentSliderParam.max"
>
<template #prepend>{{ currentSliderParam.min }}</template>
<template #append>{{ currentSliderParam.max }}</template>
</v-slider>
</v-container>
</template>
<script>
const sliderParams = [
{
min: 0,
max: 10,
},
{
min: 0,
max: 100,
},
{
min: 10,
max: 10,
},
]
data: () => ({
value: 0,
sliderParams,
selectedSliderParam: 0, …
```
=> fix(VSlider): prevent NaN for inputWidth when same min & max

packages/vuetify/src/locale/es.ts
<details>
```vue
```
</details>
=> fix(locale): update es translation

packages/docs/src/examples/v-window/misc-onboarding.vue
I have added text-center property to align it to center
=> docs(VWindow): update onboarding example

packages/vuetify/src/components/VResponsive/VResponsive.sass
Set `max-height` to `100%` to match `max-width` in `v-responsive` CSS class.
See https://codepen.io/glen-84/pen/ExXmBVP.
`v-responsive` and its children should be 46x46 (48px - 2px border), instead, they are 46x48, because there's a `max-width` but not a `max-height`.
Codepen/dev-tools.
<details>
```vue
```
</details>
=> fix(VResponsive): set max-height to 100% to match max-width

packages/vuetify/src/components/VFileInput/VFileInput.ts
Fixes #13969 
Visually
<details>
```vue
<template>
<v-file-input
label="FileInput"
persistent-placeholder
/>
</v-app>
</template>
```
</details>
=> fix(VFileInput): support persistent-placeholder

packages/vuetify/src/components/VSlider/VSlider.ts
fixes #14010
resolves #14010
resolves #14010
visually 
<details>
```vue
<template>
<v-container>
<h4>VSlider inherit is wrong</h4>
<p>[data-test="slider"] count: {{sliderCount}}</p>
<v-slider data-test="slider" />
<h4>VSwitch inherit is correct</h4>
<p>[data-test="switch"] count: {{switchCount}}</p>
<v-switch data-test="switch" />
</v-container>
</template>
<script>
data: () => ({
sliderCount: 0,
switchCount: 0
}),
mounted () {
this.sliderCount = document.querySelectorAll('[data-test="slider"]').length
this.switchCount = document.querySelectorAll('[data-test="switch"]').length
}
};
</script>
```
</details>
=> fix(VSlider): remove attributes inherit from thumb container

packages/vuetify/src/components/VField/VField.tsx, packages/vuetify/src/composables/__tests__/loader.spec.ts, packages/vuetify/src/composables/loader.tsx
converted loadable mixin to v3
resolves #13529
jest
<details>
```vue
<template>
<v-app>
<div class="ma-12 pa-12">
<v-btn @click="loading = !loading">Loader</v-btn>
<v-text-field label="Foobar" :loading="loading" />
</div>
</v-app>
</template>
<script>
data: () => ({
loading: false,
}),
}
</script>
```
</details>
=> feat(loader): port to v3

packages/docs/src/pages/en/introduction/roadmap.md
Corrected the year on the v3 beta release timeframe.
The beta date should be prior to release date.
=> docs: v3 beta release date year correction

packages/docs/src/examples/v-select/prop-icons.vue
Remove the item array, because it is not used in example, and therefore makes the code in the example less readable
Example in codepen: [https://codepen.io/Vincere1st/pen/jOwdYYv](https://codepen.io/Vincere1st/pen/jOwdYYv)
=> docs: Items Array never use

packages/docs/src/examples/v-app-bar/usage.vue
- add  `outlined`, `rounded`, `shaped` to tabs
- add `elevation` to sliders.
<details>
```vue
```
</details>
=> docs: update app-bar usage component 

packages/docs/src/examples/v-toolbar/usage.vue, packages/docs/src/pages/en/components/toolbars.md
- add  `outlined`, `rounded`, `shaped` to tabs
- add `elevation` to sliders.
<details>
```vue
```
</details>
=> docs: update toolbar usage component

tsconfig.json
Anything wrong with using ESNext?
=> chore: use esnext in tsconfig

packages/docs/src/pages/en/introduction/roadmap.md
`**Notes:**:` => `**Notes:**`
extra colon is not needed
none
=> docs(roadmap.md): remove extra colons from notes

packages/vuetify/src/styles/settings/_variables.scss
fixes #12341
- add  `$spacers-steps-number` variable with value: `16 !default;`
- make the loop `@for $i from 0 through $spacers-steps-number` for `$spacers` `$negative-spacers`
<details>
```vue
```
</details>
=> feat(styles): add $spacers-steps sass variable

packages/api-generator/src/locale/en/v-treeview.json, packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
resolves https://github.com/vuetifyjs/vuetify/issues/14282
visually
<details>
```vue
<template>
<v-container>
<v-treeview
item-disabled="locked"
disable-per-node
:items="items"
></v-treeview>
</v-container>
</template>
<script>
data: () => ({
items: [
{
id: 1,
name: "locked: true",
locked: true,
children: [
{
id: 2,
name: "locked: false",
locked: false,
children: [
{ id: 22, name: "locked: false", locked: false },
{ id: 33, name: "locked: true", locked: true },
{ id: 44, name: "locked: false", locked: false }
]
},
{ id: 3, name: "locked: true", locked: true },
{ id: 4, name: "locked: false", locked: false }
]
}
]
}),
}
</script>
```
</details>
=> feat(VTreeview): add disablePerNode prop

packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.sass, packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.ts
fixes #14243
fixes #14243
This issue is caused by Firefox has very wired mouse event behaviour on div with `overflow: hidden` applied, this issue has been confirmed by bugzilla ([detail](https://bugzilla.mozilla.org/show_bug.cgi?id=1736188))
solution is remove `overflow: hidden`  on dragging div and apply `text-overflow: ellipsis` to summary text in order to restrict its content within the event container
fixes #14243
visually
<details>
```vue
<template>
<v-row class="fill-height">
<v-col>
<v-sheet height="600">
<v-calendar
ref="calendar"
type="4day"
:event-color="getEventColor"
:event-ripple="false"
@change="getEvents"
@mousedown:event="startDrag"
@mousedown:time="startTime" …
```
=> fix(VCalendar): resolve drag drop issue on firefox

packages/vuetify/src/directives/ripple/VRipple.sass, packages/vuetify/src/directives/ripple/_variables.scss, packages/vuetify/src/directives/ripple/index.ts, packages/vuetify/src/styles/settings/_variables.scss
fixes #11505 
- removed variables from `packages/vuetify/src/directives/ripple/_variables.scss` as they are already defined in `packages\vuetify\src\styles\settings\_variables.scss`
- removed opactiy functionality from `Vripple index.ts` as it overrides the opactiy in sass file 
- added `opacity` variable, functionality into sass file
<details>
```vue
<template>
<div v-ripple class="text-center elevation-2 pa-12 text-h5">
HTML element with v-ripple
</div>
</v-app>
</template>
<script>
export default {};
</script>
```
</details>
=> fix(VRipple): use $ripple-animation-visible-opacity variable

packages/vuetify/src/locale/it.ts
I just corrected the translations in it
The translations were not good
There is no need to testing
<details>
```vue
```
</details>
- [ x] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)
- [x ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
=> fix(locale): update `it` translations

packages/docs/src/examples/border-radius/misc-removing-border-radius.vue
options added to example:
- **rounded-t-0**
- **rounded-r-0**
- **rounded-b-0**
- **rounded-l-0**
- **rounded-tl-0**
- **rounded-tr-0**
- **rounded-br-0**
- **rounded-bl-0**
<details>
```vue
```
</details>
=> docs: improve 'remove-border-radius' example

packages/docs/src/examples/v-tooltip/prop-color.vue, packages/docs/src/pages/en/components/tooltips.md
<details>
```vue
```
</details>
=> docs(VTooltip): add example for color prop

packages/vuetify/src/services/application/index.ts
The use-case that this was changed for was very convoluted and niche and ultimately has caused
a regression. This PR reverts the change made in b1058f3
fixes #13665
jest/visually
=> fix(application): allow use of multiple drawers

packages/docs/src/pages/en/getting-started/installation.md
in Vuetify 3 [installation page (Vite section)](https://next.vuetifyjs.com/en/getting-started/installation/#vite)
`vue-cli[#vue-cli]` seems to be a link, but it is broken
<details>
```vue
```
</details>
=> fix(docs): fix broken vue-cli link in install page

packages/docs/src/examples/v-badge/misc-dynamic.vue
While reading the documentation of v-badge to check about the usage of the component, I recognized that there is an unsed variable show in script part. That's a little bit misleading because I was looking for the variable in the template part.
I suggest to remove it.
Improving documentation
-
-
<details>
```vue
```
</details>
=> docs(v-badge): remove unused show

packages/docs/src/examples/v-list/slot-expansion-lists.vue
Change two of the category icons in the v-list expansion lists example.
The icons were changed to better represent the categories of each expansion list.
Visually
=> docs(VList): change icons in expansion lists example

packages/vuetify/src/components/VList/VList.tsx, packages/vuetify/src/components/VList/VListChildren.tsx
<details>
```vue
```
</details>
=> fix(VList): internal header slot would propagate to child groups

packages/vuetify/types/lib.d.ts
fixes #14496
added missing VOtpInput export in lib.d.ts
missing VOtpInput export in lib.d.ts
=> fix(types): add missing VOtpInput export in lib.d.ts

packages/vuetify/dev/index.js, packages/vuetify/src/composables/theme.ts, packages/vuetify/src/framework.ts
=> feat(theme): support ssr with @vueuse/head

packages/vuetify/src/components/VOtpInput/VOtpInput.ts
Update the otp input when `value` changes.
fixes #14437 
This pull request solves the update problem present on the new VOtpInput component. Indeed, it is impossible to change or to empty the field, even during the reset of a form (see the reproduction in #14437 )
<details>
```vue
<template>
<v-container>
<v-form ref="form">
<v-otp-input
v-model="otp"
></v-otp-input>
</v-form>
<v-btn @click="$refs.form.reset()">Reset Button</v-btn>
<v-btn @click="otp = '123'">change otp value to : 123</v-btn>
{{otp}}
</v-container>
</template>
<script>
data: () => ({
otp: '0'
}),
}
</script>
```
</details>
=> fix(VOtpInput): update the `otp` when `value` changes

packages/vuetify/src/components/VCombobox/VCombobox.ts, packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.ts
fixes #14507 
visually | unit
<details>
```vue
<template>
<v-app>
input1 @input events={{input1}}
<v-combobox :items="items" @input="input1++"/>
input2 @input events={{input2}}
<v-combobox :items="items" multiple @input="input2++"/>
</v-app>
</template>
<script>
data: () => ({
input1: 0,
input2: 0,
items: [ "item1", "item2", "item3", "item4"]
}),
}
</script>
```
</details>
=> fix(VCombobox): don't reset search when cleared

packages/docs/src/examples/v-snackbar/prop-variants.vue
- change snackbar content name
- add new snackbar with `tile` prop.
<details>
```vue
```
</details>
=> docs(VSnackbar): improve variants example

packages/docs/src/pages/en/components/toolbars.md
v-app -> v-app-bar
https://vuetifyjs.com/en/components/toolbars/#variations
<details>
```vue
```
</details>
=> docs(toolbar): fix typo

packages/docs/src/pages/en/components/bottom-navigation.md
Fix grammatical error in line 36
<details>
```vue
```
</details>
=> docs(bottom-navigation): fix grammatical error

packages/vuetify/src/components/VTabs/VTab.ts
If vTab is disabled I set the `tabindex` to `-1`, means that the element is not reachable via sequential keyboard navigation.
fixes #14601 
This PR solves the problem present on the vTab component which can be focused by the keyboard even if is disabled.
(see the reproduction in #14601)
<details>
```vue
<template>
<v-container>
<v-switch v-model="disableTab" label="Enable/Disable tab #3"></v-switch>
<v-tabs>
<v-tab>Item One</v-tab>
<v-tab>Item Two</v-tab>
<v-tab :disabled="disableTab">Item Three</v-tab>
<v-tab>Item Four</v-tab>
<v-tab-item>1</v-tab-item>
<v-tab-item>2</v-tab-item>
<v-tab-item >3</v-tab-item>
<v-tab-item >4</v-tab-item>
</v-tabs>
</v-container>
</template>
<script>
data: () => ({
disableTab: true
})
}
</script>
```
</details>
=> fix(VTab): disabled tab can be reached by keyboard

packages/docs/src/examples/transitions/misc-todo.vue
Icon added as `add_circle` so it appears as text on the docs. Updates the icon with `mdi-plus-circle` which is probably what was intended in the first place.
<details>
```vue
```
</details>
=> docs(transitions): fix icon name

packages/docs/src/pages/en/introduction/roadmap.md
<details>
```vue
```
</details>
=> docs(roadmap): update v3 release dates.

packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.tsx, packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbsItem.tsx, packages/vuetify/src/components/VBreadcrumbs/__tests__/VBreadcrumbs.spec.ts
- renamed `item` slot to `text`, since it no longer allows one to define the whole `v-breadcrumbs-item` element but instead just the content inside of it.
<details>
```vue
<template>
<v-app>
<v-breadcrumbs :items="items">
<template v-slot:text="{ item }">
{{ item.text.toUpperCase() }}
</template>
</v-breadcrumbs>
</v-app>
</template>
<script>
data: () => ({
items: [
{
text: 'Dashboard',
disabled: false,
href: 'breadcrumbs_dashboard',
},
{
text: 'Link 1',
disabled: false,
href: 'breadcrumbs_link_1',
},
{
text: 'Link 2',
disabled: true,
href: 'breadcrumbs_link_2',
},
],
}),
}
</script>
```
</details>
=> feat(VBreadcrumbs): rename item slot to text, update passed variables

packages/vuetify/src/components/VBadge/VBadge.tsx, packages/vuetify/src/components/VBadge/__tests__/VBadge.spec.tsx, packages/vuetify/src/components/VBadge/__tests__/__snapshots__/VBadge.spec.tsx.snap
feat(VBadge): update test
It's common to use a number as content of vbadge. This the case in nearly all doc examples.
#14809
<details>
```vue
```
</details>
=> feat(VBadge): add number type to content props (#14809)

packages/vuetify/src/components/VOverlay/__tests__/VOverlay.spec.cy.tsx, packages/vuetify/src/components/VPagination/__tests__/VPagination.spec.cy.tsx, packages/vuetify/src/composables/group.ts, packages/vuetify/src/util/helpers.ts
If value is not set on group items, use the index of item instead of the internal id
This allows one to use coupled components like v-tabs + v-window without explicitly setting value on items.
```html
// Before
<v-tabs v-model="active">
<v-tab value="foo"/>
<v-tab value="bar"/>
</v-tabs>
<v-window v-model="active">
<v-window-item value="foo"/>
<v-window-item value="bar"/>
</v-window>
```
```html
// After
<v-tabs v-model="active">
<v-tab/>
<v-tab/>
</v-tabs>
<v-window v-model="active">
<v-window-item/>
<v-window-item/>
</v-window>
```
<details>
```vue
<template>
<v-app>
<v-card>
<v-tabs v-model="tab" slider-color="secondary">
<div>
<v-tab>Main Settings</v-tab>
</div>
<v-tab>Intro Text</v-tab>
</v-tabs>
{{ tab }}
<v-window v-model="tab">
<v-window-item>
foo
</v-window-item>
<v-window-item> …
```
=> feat(group): use index as implicit value instead of id

packages/vuetify/src/components/VItemGroup/__tests__/VItemGroup.spec.cy.tsx, packages/vuetify/src/composables/group.ts
closes #14754
<details>
```vue
```
</details>
=> fix(group): apply both group and item selected-class

packages/docs/src/examples/v-system-bar/prop-color.vue, packages/docs/src/examples/v-system-bar/prop-window.vue, packages/docs/src/examples/v-system-bar/usage.vue, packages/vuetify/src/components/VSystemBar/VSystemBar.sass, packages/vuetify/src/components/VSystemBar/VSystemBar.tsx, packages/vuetify/src/components/VSystemBar/_variables.scss
add layout support for system bar
<details>
```vue
<template>
<v-app>
<v-system-bar window>
<v-icon>mdi-message</v-icon>
<span>10 unread messages</span>
<v-btn icon="mdi-minus" class="mr-2"></v-btn>
<v-btn icon="mdi-checkbox-blank-outline" class="mr-2"></v-btn>
<v-btn icon="mdi-close"></v-btn>
</v-system-bar>
<v-main>
hello
</v-main>
</v-app>
</template>
<script>
data: () => ({
})
}
</script>
```
</details>
=> feat(VSystemBar): add layout support

packages/vuetify/src/components/VSelect/VSelect.tsx
<details>
```vue
```
</details>
=> fix(VSelect): selection should show title, not value

packages/vuetify/src/components/VTextField/__tests__/VTextField.spec.cy.tsx, packages/vuetify/src/composables/validation.ts
closes #14733
<details>
```vue
```
</details>
=> fix(validation): validate when model changes

packages/docs/src/pages/en/getting-started/unit-testing.md
<details>
```vue
```
</details>
=> docs: remove unused imports on unit tests

packages/vuetify/dev/router.js, packages/vuetify/src/components/VBtn/VBtn.tsx, packages/vuetify/src/components/VList/VListItem.tsx, packages/vuetify/src/components/VSlideGroup/VSlideGroup.tsx, packages/vuetify/src/components/VTabs/VTab.tsx, packages/vuetify/src/composables/group.ts, packages/vuetify/src/composables/nested/nested.ts, packages/vuetify/src/composables/router.tsx, packages/vuetify/src/composables/selectLink.ts
maybe something like this?
fixes #14914
<details>
```vue
<template>
<v-app>
<v-navigation-drawer :model-value="true" permanent>
<v-list :items="items" v-model:selected="bar"></v-list>
<pre>{{ bar }}</pre>
<v-main>
<v-tabs v-model="foo">
<v-tab v-for="item in items" :key="item.name" :to="item.to" color="primary">
{{ item.title }}
</v-tab>
</v-tabs>
<pre>{{ foo }}</pre>
<v-btn to="/">asd</v-btn>
<v-tabs
v-model="tab"
background-color="primary"
>
<v-tab value="one">Item One</v-tab>
<v-tab value="two">Item Two</v-tab>
<v-tab value="three">Item Three</v-tab>
</v-tabs>
Component loads below:
<router-view></router-view>
</v-main>
</v-app>
</template>
<script>
name: 'App',
data: () => ({
foo: null,
bar: null,
tab: null,
items: [
{
title: 'Home',
to: { name: …
```
=> fix: update router compatible components when route changes

packages/vuetify/src/components/VForm/VForm.tsx, packages/vuetify/src/components/VForm/__tests__/VForm.spec.cy.tsx, packages/vuetify/src/composables/form.ts, packages/vuetify/src/composables/validation.ts
closes #14901
<details>
```vue
<template>
<v-app>
<v-form v-model="valid" ref="form">
<v-container>
<v-row>
<v-col cols="12" md="4">
<v-text-field
v-model="firstname"
:counter="10"
label="First name"
required
</v-col>
<v-col cols="12" md="4">
<v-text-field
v-model="lastname"
:counter="10"
label="Last name"
required
</v-col>
<v-col cols="12" md="4">
<v-text-field
:rules="emailRules"
label="E-mail"
required
</v-col>
</v-row>
<v-btn @click="validate">validate</v-btn>
<v-btn @click="reset">reset</v-btn>
<v-btn @click="resetValidation">reset validation</v-btn>
<pre>{{ JSON.stringify(valid, null, 2) }}</pre>
<pre>{{ JSON.stringify(response, null, 2) }}</pre>
</v-container>
</v-form>
</v-app> …
```
=> fix(VForm): should update valid state reactively

packages/vuetify/src/composables/validation.ts
fixes #14942
fixes #14942
<details>
```vue
<template>
<v-app>
<v-container>
Note how when num=0 the number gets hidden on lose focus but when num>0 it works fine
<v-text-field label="works" type="number" />
</v-container> 
</v-app> 
</template>
```
</details>
=> fix(validation): respect number 0 when calculating isDirty

packages/vuetify/src/styles/generic/_colors.scss
Removes border-color declaration in **background-color** style generation
Normalize with theme.ts color class generation
visually
<details>
```vue
<template>
<v-app>
<v-main>
<v-card color="white" border elevation="0">Hello</v-card>
</div>
</v-main>
</v-app>
</template>
<script setup>
// import { computed, ref } from 'vue'
</script>
```
</details>
=> refactor(colors): remove border-color declaration

packages/vuetify/src/locale/fi.ts
Added missing Finnish translations.
No need to test with units...
Not sure about which branch to target, but went with `master` for now. Should not matter tough as this is only really minor update.
=> fix(locale): add missing Finnish translations

packages/api-generator/src/locale/en/v-rating.json
I fixed the grammar.
I noticed that the grammar is not correct when I read [v-rating API](https://vuetifyjs.com/en/api/v-rating/).
=> docs(VRating): fix grammar

packages/vuetify/src/components/VToolbar/VToolbar.sass, packages/vuetify/src/components/VToolbar/_variables.scss
Add missing border functionality to `v-toolbar` (propagates to `v-app-bar`)
fixes #14985
none
<details>
```vue
<template>
<v-app>
<v-main>
<v-toolbar border>Hello</v-toolbar>
</div>
</v-main>
</v-app>
</template>
<script setup>
// import { computed, ref } from 'vue'
</script>
```
</details>
=> fix(VToolbar): add missing border functionality

packages/vuetify/src/components/VFooter/VFooter.tsx, packages/vuetify/src/composables/layout.ts
Adds conditional layout support through the **app** prop.
fixes #14983
none
<details>
```vue
<template>
<v-app>
<v-navigation-drawer permanent />
<v-main>
<h1>Vuetify Footer</h1>
</v-main>
<v-footer color="black" app>
<v-col class="py-4 text-center">
{{ new Date().getFullYear() }} — <strong>Company</strong>
</v-col>
</v-row>
</v-footer>
</v-app>
</template>
<script setup>
// import { computed, ref } from 'vue'
const data = '123124123'
</script>
```
</details>
=> fix(VFooter): add application layout support

packages/vuetify/src/components/VField/VField.tsx, packages/vuetify/src/components/VIcon/VIcon.sass, packages/vuetify/src/components/VIcon/VIcon.tsx, packages/vuetify/src/components/VInput/VInput.tsx, packages/vuetify/src/components/VTextField/VTextField.tsx
fixes #14896
Adds click detection to `v-icon` for automatic cursor change.
We use standard icons as individual clickable items throughout the framework and typically have to manually apply this styling.
visually
<details>
```vue
```
</details>
=> fix(VIcon): use pointer cursor on clickable icons

packages/docs/src/service-worker.js
resolves #15089
vercel preview
<details>
```vue
```
</details>
=> docs(pwa): serve SPA index, don't cache static pages

packages/vuetify/src/composables/validation.ts
closes https://github.com/vuetifyjs/vuetify/issues/15143
<details>
```vue
<template>
<v-app>
<v-container>
<v-form v-model="valid">
<v-text-field
label="foo"
v-model="fooInput"
:rules="[v => !!v]"
/>
<v-checkbox
label="Bar"
v-model="barChecked"
/>
<v-btn 
:disabled="!valid"
>Submit</v-btn>
</v-form>
</v-container>
</v-app>
</template>
import { defineComponent } from 'vue'
data: () => ({
valid: false,
fooInput: '',
barChecked: false,
}),
})
</script>
```
</details>
=> fix(validation): input without rules is always valid

packages/docs/src/components/app/list/List.vue, packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VList/VList.tsx, packages/vuetify/src/components/VList/VListChildren.tsx, packages/vuetify/src/components/VList/VListSubheader.tsx, packages/vuetify/src/components/VList/__tests__/VList.spec.cy.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx, packages/vuetify/src/composables/__tests__/filter.spec.ts, packages/vuetify/src/composables/__tests__/items.spec.ts, packages/vuetify/src/composables/filter.ts, packages/vuetify/src/composables/items.ts
items composable by itself is not enough to support v-list use case, which can have different **types** of items.
<details>
```vue
<template>
<v-card
max-width="450"
>
<v-toolbar
color="cyan"
dark
>
<v-app-bar-nav-icon variant="text"></v-app-bar-nav-icon>
<v-toolbar-title>Inbox</v-toolbar-title>
<v-btn variant="text" icon="mdi-magnify"></v-btn>
</v-toolbar>
<v-list
lines="three"
:items="items"
item-title="subject"
:item-props="itemProps"
>
<template v-slot:subtitle="{ item }">
<div>
<span class="text-primary">{{ item.from }}</span>
<span> &mdash; {{ item.content }}</span>
</div>
</template>
</v-list>
<v-select
:items="sitems"
item-title="state"
item-value="abbr"
label="Select"
single-line
></v-select>
</v-card> …
```
=> refactor(items): make it work with v-list

packages/docs/src/components/app/list/List.vue, packages/docs/src/examples/v-list/prop-three-line.vue, packages/vuetify/src/components/VList/VList.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx, packages/vuetify/src/composables/items.ts, packages/vuetify/src/util/helpers.ts
With #15108 the only way to pass additional props to select items was with an itemProps function. This PR adds 
- `item-props="props"` - a configurable key on the items which is spread onto list items (uses getPropertyFromItem)
- `:item-props="true"`/`item-props` - same behaviour as before #15108, items are interpreted as props objects
Fixes #15159
<details>
```vue
<template>
<v-card
max-width="450"
>
<pre>{{ { select, search } }}</pre>
v-model:search="search"
:items="selectItems"
item-title="state"
item-value="abbr"
label="Select"
single-line
/>
<v-card
max-width="450"
>
<v-toolbar
color="cyan"
dark
>
<v-app-bar-nav-icon variant="text" />
<v-toolbar-title>Inbox</v-toolbar-title>
<v-spacer />
<v-btn …
```
=> feat(items): add item-props="props" and :item-props="true"

packages/vuetify/src/composables/icons.tsx, packages/vuetify/src/composables/locale.ts, packages/vuetify/src/framework.ts
=> refactor(framework): tuning pass

package.json, packages/docs/src/components/app/Markdown.vue, packages/docs/src/components/doc/Releases.vue, packages/docs/src/plugins/global-components.ts, packages/docs/src/plugins/octokit.js, packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx, yarn.lock
This was initially supposed to just be fixing the `Uncaught ReferenceError: global is not defined` issue in the docs, but as things were getting fixed, other things were getting broken
- Fixes the `Releases.vue` component, refactored to use composition api
- Add `menuProps` prop to `VCombobox`, `VSelect`, and `VAutocomplete`
- Removed `octokit` and replaced by fetching release data from the rest api
-  Fixes `Uncaught ReferenceError: global is not defined`
Visually
<details>
```vue
```
</details>
=> docs(releases): convert component to composition api

packages/docs/src/data/nav-alpha.json, packages/docs/src/pages/en/components/no-ssr.md, packages/vuetify/src/components/VNoSsr/VNoSsr.tsx
<details>
```vue
//
```
</details>
=> refactor(VNoSsr): tuning pass

packages/vuetify/src/components/VRadio/__tests__/VRadio.spec.cy.tsx
<details>
```vue
//
```
</details>
=> refactor(VRadio): tuning pass

packages/vuetify/src/components/VParallax/VParallax.tsx, packages/vuetify/src/components/VParallax/__tests__/VParallax.spec.cy.tsx
<details>
```vue
```
</details>
=> refactor(VParallax): tuning pass

packages/vuetify/src/components/VSelectionControl/VSelectionControl.sass, packages/vuetify/src/components/VSelectionControl/VSelectionControl.tsx, packages/vuetify/src/components/VSelectionControl/_variables.scss
<details>
```vue
//
```
</details>
=> refactor(VSelectionControl): tuning pass

packages/vuetify/src/components/VInput/VInput.sass, packages/vuetify/src/components/VInput/VInput.tsx
<details>
```vue
//
```
</details>
=> refactor(VInput): tuning pass

packages/vuetify/src/components/VProgressLinear/VProgressLinear.sass, packages/vuetify/src/components/VProgressLinear/VProgressLinear.tsx, packages/vuetify/src/components/VProgressLinear/_variables.scss
<details>
```vue
//
```
</details>
=> refactor(VProgressLinear): tuning pass

packages/vuetify/src/components/VRating/VRating.sass, packages/vuetify/src/components/VRating/VRating.tsx
<details>
```vue
//
```
</details>
=> refactor(VRating): tuning pass

packages/vuetify/src/components/VOverlay/VOverlay.tsx, packages/vuetify/src/components/VOverlay/useActivator.tsx
<details>
```vue
//
```
</details>
=> refactor(VOverlay): tuning pass

packages/docs/src/pages/en/components/dialogs.md, packages/vuetify/src/components/VDialog/VDialog.sass, packages/vuetify/src/components/VDialog/VDialog.tsx, packages/vuetify/src/components/VDialog/__tests__/VDialog.spec.cy.tsx, packages/vuetify/src/components/VDialog/_variables.scss
<details>
```vue
//
```
</details>
=> refactor(VDialog): tuning pass

packages/vuetify/src/components/VForm/VForm.tsx
<details>
```vue
//
```
</details>
=> refactor(VForm): tuning pass

packages/vuetify/src/components/VColorPicker/VColorPicker.tsx, packages/vuetify/src/components/VColorPicker/VColorPickerCanvas.tsx, packages/vuetify/src/components/VColorPicker/VColorPickerEdit.tsx, packages/vuetify/src/components/VColorPicker/VColorPickerPreview.tsx, packages/vuetify/src/components/VColorPicker/VColorPickerSwatches.tsx, packages/vuetify/src/components/VColorPicker/_variables.scss
<details>
```vue
//
```
</details>
=> refactor(VColorPicker): tuning pass

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx
<details>
```vue
//
```
</details>
=> refactor(VAutocomplete): tuning pass

packages/vuetify/src/components/VGrid/VCol.ts, packages/vuetify/src/components/VGrid/VContainer.tsx, packages/vuetify/src/components/VGrid/VRow.ts
<details>
```vue
//
```
</details>
=> refactor(VGrid): tuning pass

packages/vuetify/src/composables/__tests__/validation.spec.ts, packages/vuetify/src/composables/validation.ts
closes #15209
<details>
```vue
<template>
<v-app>
<VForm>
<VTextField
label="E-mail"
:error-messages="emailError"
:error="!!emailError"
/>
</VForm>
</v-app>
</template>
<script>
import { defineComponent } from 'vue'
data: () => ({
email: '',
emailError: 'Foo',
}),
})
</script>
```
</details>
=> fix(validation): set input to invalid using error/errorMessages

packages/docs/src/examples/v-chip/misc-in-selects.vue
`this.chips = [...this.chips]` doesn't serve any purpose here, does it? Might be related to mutating or not mutating, but we already mutated chips when we did splice, so... I don't see any value in this extra line
extra line that does nothing
manually in my project
=> docs(VChip): remove useless code from example

packages/vuetify/src/components/transitions/index.ts, packages/vuetify/src/styles/generic/_transitions.scss
closes #14440
add default transition to custom component transitions
add transition animations
visually
<details>
```vue
<template>
<v-app>
<v-main>
<v-col cols="auto">
<v-dialog
transition="dialog-bottom-transition"
>
<v-btn
v-bind="props"
>From the bottom</v-btn>
</template>
<template #default="dialog">
<v-card>
<v-toolbar
dark
>Opening from the bottom</v-toolbar>
<v-card-text>
<div class="text-h2 pa-12">Hello world!</div>
</v-card-text>
<v-card-actions class="justify-end">
<v-btn
text
@click="dialog.value = false"
>Close</v-btn>
</v-card>
</template>
</v-dialog>
</v-col>
<v-col cols="auto">
<v-dialog
transition="dialog-top-transition"
> …
```
=> fix(transitions): apply default transition to component transitions

packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.sass, packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.tsx, packages/vuetify/src/components/VBreadcrumbs/__tests__/VBreadcrumbs.spec.cy.tsx, packages/vuetify/src/components/VBreadcrumbs/_variables.scss
closes #15430
<details>
```vue
<template>
<v-app>
<v-breadcrumbs :items="items" icon="mdi-home" />
</v-app>
</template>
<script>
data: () => ({
items: [{ title: "First" }, { title: "Second" }, { title: "Third" }],
}),
}
</script>
```
</details>
=> fix(VBreadcrumbs): only render one icon

packages/vuetify/src/components/VPagination/VPagination.tsx, packages/vuetify/src/components/VPagination/__tests__/VPagination.spec.cy.tsx
closes #15424
- used `_as` to set VBtn in VPagination to VPaginationBtn instead.
- added `active-color` prop
<details>
```vue
<template>
<v-app>
<v-pagination
v-model="page"
:length="6"
active-color="success"
></v-pagination>
</v-app>
</template>
<script>
data: () => ({
page: 1,
})
}
</script>
```
</details>
=> fix(VPagination): remove VBtn defaults, add activeColor prop

packages/vuetify/src/components/VTable/VTable.sass
Apply z-index to thead tr children to position above tbody content
fixes #15297
visually
<details>
```vue
<template>
<v-container>
<v-table
fixed-header
fixed-footer
height="300px"
>
<thead>
<tr>
<th class="text-left">
Name
</th>
<th class="text-left">
Calories
</th>
</tr>
</thead>
<tbody>
<tr
v-for="item in desserts"
:key="item.name"
>
<td><v-icon icon="mdi-delete" /></td>
<td>{{ item.calories }}</td>
</tr>
</tbody>
<tfoot>
<tr>
<th class="text-left">
Name
</th>
<th class="text-left">
Calories
</th>
</tr>
</tfoot>
</v-table>
</v-container>
</div>
</template>
<script>
data () {
return {
desserts: [
{
calories: 159,
},
{
calories: 237,
},
{
calories: 262,
},
{ …
```
=> fix(VTable): position fixed header above tbody content

packages/vuetify/src/components/VField/VField.sass
fixes #15483
I'm not sure why I added this. It moves the input text lower about 1px in `v-text-area` but doesn't seem to effect any of the `v-combobox` or `v-autocomplete` examples, which is where it stemmed from originally.
<details>
```vue
<template>
<v-container>
<v-row>
<v-col cols="12" md="6">
<v-text-field
v-model="name"
:disabled="isUpdating"
filled
color="blue-grey-lighten-2"
label="Name"
/>
</v-col>
<v-col cols="12" md="6">
<v-text-field
v-model="title"
:disabled="isUpdating"
filled
color="blue-grey-lighten-2"
label="Title"
/>
</v-col>
v-model="friends"
:disabled="isUpdating"
filled
chips
closable-chips
color="blue-grey-lighten-2"
label="Select"
item-title="name"
multiple
>
<template …
```
=> fix(VField): remove explicit v-field__input align-self

packages/vuetify/src/components/VFileInput/VFileInput.sass
Sometimes drag'n'drop is preferred way to add files to the form
visually
<details>
```vue
```
</details>
=> fix(VFileInput): allow native drag and drop

packages/docs/src/pages/en/components/data-tables.md
Fixed  typo `takes` to `take` on  Slots
<details>
```vue
```
</details>
=> fix(docs): typo on v-data-table slot description

packages/vuetify/src/components/VField/VField.sass
It will fix the dark color of placeholder for input & textarea compared to current version where ther's no color for placeholder. Moreover, we added placeholder color in [v2](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VInput/VInput.sass#L11-L13)
Without this changes - placeholder are darker than label
As above
<details>
```vue
const vuetifyTheme = useTheme()
const toggleTheme = () => {
vuetifyTheme.global.name.value = vuetifyTheme.global.name.value === 'dark' ? 'light' : 'dark'
}
</script>
<template>
<v-container>
<v-btn color="primary" class="mb-4" @click="toggleTheme">Toggle Dark mode</v-btn>
<div class="d-flex flex-column">
<p>Some body text</p>
<v-text-field …
```
=> fix(VField): use disabled as placeholder color

packages/docs/src/examples/v-snackbar/prop-variants.vue, packages/vuetify/src/components/VSnackbar/VSnackbar.tsx, packages/vuetify/src/components/VSnackbar/_variables.scss
closes #15473
<details>
```vue
<template>
<v-app>
<v-btn
color="indigo"
@click="snackbar = true"
>
Open Snackbar
</v-btn>
<v-theme-provider theme="dark">
<v-snackbar
v-model="snackbar"
vertical
:timeout="-1"
>
<div class="text-subtitle-1 pb-2">This is a snackbar message</div>
<p>This is a longer paragraph explaining something</p>
<template v-slot:actions>
<v-btn
color="indigo"
variant="text"
@click="snackbar = false"
>
Close
</v-btn>
</template>
</v-snackbar>
</v-theme-provider>
<v-snackbar
content-class="foo"
v-model="snackbar"
vertical
:timeout="-1"
>
<div class="text-subtitle-1 pb-2">This is a snackbar message</div>
<p>This is a longer paragraph explaining something</p>
<template v-slot:actions>
<v-btn
color="indigo"
variant="text"
@click="snackbar = false"
>
Close
</v-btn>
</template> …
```
=> fix(VSnackbar): use theme surface variant as background

packages/api-generator/src/maps/v-data-table.js
Typo fix of header type.
I'm using web-types to generate global component types for Volar intellisense and type check, but this issue prevents me from generating correct type file.
No need to test.
<details>
```vue
```
</details>
=> docs(VDataTable): fix type of headers in slot

packages/api-generator/src/maps/v-slide-item.js
Add missing slot props in docs of `VSlideItem`
I used web-types of vuetify 2 to generate global component types for Volar intellisense and type check. Then I found there is no slot props in docs of `VSlideItem`, resulting into type error.
<details>
```vue
```
</details>
=> docs(VSlideItem): add missing slot props

packages/vuetify/src/components/VRadio/VRadio.tsx
Alternative to #15384, using the same pattern as VCheckboxBtn
fixes #15037
=> fix(VRadio): use makeSelectionControlProps()

packages/docs/src/pages/en/features/internationalization.md, packages/vuetify/src/composables/rtl.ts
closes #15534
Removed defaultRtl option, since it only had effect if custom locale (that had not specified rtl) was used. If user needs to force RTL for non-RTL locale, they can use v-locale-provider
<details>
```vue
```
</details>
=> fix(rtl): remove defaultRtl option, update docs

packages/docs/src/pages/en/components/timelines.md, packages/vuetify/src/components/VTimeline/VTimeline.sass, packages/vuetify/src/components/VTimeline/VTimeline.tsx, packages/vuetify/src/components/VTimeline/VTimelineDivider.tsx, packages/vuetify/src/components/VTimeline/VTimelineItem.tsx
closes #15571
<details>
```vue
<template>
<v-app>
<v-locale-provider :rtl="rtl">
<div class="ma-10">
<v-timeline
truncate-line="both"
:line-inset="20"
>
<v-timeline-item>
<v-sheet height="200" width="300" color="primary"></v-sheet>
<template #opposite>opposite</template>
<v-timeline-item>
<v-sheet height="100" width="100" color="primary"></v-sheet>
<template #opposite>opposite</template>
<v-timeline-item>
<v-sheet height="300" width="200" color="primary"></v-sheet>
<template #opposite>opposite</template>
<v-timeline-item>
<v-sheet height="200" width="100" color="primary"></v-sheet>
<template #opposite>opposite</template>
</v-timeline>
</div>
<v-btn @click="rtl = !rtl">rtl</v-btn> …
```
=> fix(VTimeline): line-inset issues

packages/vuetify/src/components/VAutocomplete/VAutocomplete.sass, packages/vuetify/src/components/VAutocomplete/_variables.scss, packages/vuetify/src/components/VCombobox/VCombobox.sass, packages/vuetify/src/components/VCombobox/_variables.scss, packages/vuetify/src/components/VSelect/VSelect.sass, packages/vuetify/src/components/VSelect/_variables.scss
fixes #15482
<details>
```vue
<template>
<v-row>
<v-combobox
:items="items"
label="I use a scoped slot"
multiple
chips
variant="solo"
>
<template #chip="{ props }">
<v-chip
v-bind="props"
/>
</template>
</v-combobox>
</v-col>
</v-row>
</v-container>
</div>
</template>
<script>
data () {
return {
select: ['Vuetify', 'Programming'],
items: [
'Programming',
'Design',
'Vue',
'Vuetify',
],
}
},
}
</script>
```
</details>
=> fix(VSelect/VCombobox/VAutocomplete): add top margin for chip containers

packages/vuetify/src/components/VBtn/VBtn.sass, packages/vuetify/src/components/VBtn/_variables.scss
discussed in #15147, could do with an easy way to remove it
=> feat(VBtn): add global config for colored disabled buttons

packages/vuetify/dev/App.vue, packages/vuetify/src/components/VLayout/VLayout.sass, packages/vuetify/src/components/VLayout/__tests__/VLayout.spec.cy.tsx, packages/vuetify/src/components/VMain/VMain.sass, packages/vuetify/src/components/VMain/VMain.tsx, packages/vuetify/src/components/VNavigationDrawer/_variables.scss, packages/vuetify/src/components/VToolbar/VToolbar.sass, packages/vuetify/src/composables/layout.ts
closes #15433
closes #2132
<details>
```vue
<template>
<v-app-bar height="22" color="grey-darken-3" elevation="0"></v-app-bar>
<v-navigation-drawer width="72" color="grey-darken-2" v-model="drawer" temporary></v-navigation-drawer>
<v-navigation-drawer width="150" color="grey-darken-1"></v-navigation-drawer>
<v-app-bar height="48" color="grey" elevation="0"></v-app-bar>
<v-navigation-drawer location="right" width="150" color="grey-lighten-1" permanent></v-navigation-drawer>
<v-app-bar location="bottom" height="48" color="grey-lighten-2" elevation="0"></v-app-bar>
<v-main>
<div>
<v-btn @click="drawer = !drawer">drawer</v-btn>
<p v-for="i in 10" :key="i">{{ i }}</p>
<nav>
Sticky Navbar
</nav>
<p v-for="i in 100" :key="i">{{ i }}</p>
<v-layout class="ma-10" style="height: 600px">
<v-app-bar …
```
=> feat(VLayout): add scrollable main, support sticky elements

packages/docs/src/pages/en/components/navigation-drawers.md, packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.sass, packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.tsx, packages/vuetify/src/components/VNavigationDrawer/__tests__/VNavigationDrawer.spec.cy.tsx, packages/vuetify/src/util/anchor.ts
closes #15364
<details>
```vue
```
</details>
=> fix(VNavigationDrawer): add RTL support

packages/docs/src/examples/v-navigation-drawer/misc-combined.vue, packages/docs/src/examples/v-navigation-drawer/prop-expand-on-hover.vue, packages/docs/src/examples/v-navigation-drawer/prop-images.vue, packages/docs/src/examples/v-navigation-drawer/prop-mini-variant.vue, packages/vuetify/src/components/VAvatar/VAvatar.sass, packages/vuetify/src/components/VList/VList.sass, packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.sass, packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.tsx, packages/vuetify/src/components/VNavigationDrawer/__tests__/VNavigationDrawer.spec.cy.tsx
fixes #15454 
<details>
```vue
<template>
<v-container>
<v-card>
<v-layout>
:rail="rail"
permanent
@click="rail = false"
>
<v-list-item
prepend-avatar="https://randomuser.me/api/portraits/men/85.jpg"
class="pl-2"
title="John Leider"
nav
>
<v-btn
variant="text"
icon="mdi-chevron-left"
@click.stop="rail = !rail"
/>
</template>
</v-list-item>
<v-divider />
<v-list density="compact" nav>
<v-list-item prepend-icon="mdi-home-city" title="Home" value="home" />
<v-list-item prepend-icon="mdi-account" title="My Account" value="account" />
<v-list-item prepend-icon="mdi-account-group-outline" title="Users" value="users" />
</v-list>
<v-main style="height: 250px" />
</v-layout>
</v-card> …
```
=> fix(VNavigationDrawer): rail variant and examples

packages/vuetify/src/components/VGrid/VCol.ts, packages/vuetify/src/components/VGrid/VRow.ts, packages/vuetify/src/styles/settings/_utilities.scss
closes #15581
<details>
```vue
<template>
<v-app>
<v-row justify="space-evenly" align-content="space-evenly"></v-row>
</v-app>
</template>
```
</details>
=> feat(VRow): add space-evenly

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx
fix #15496
fix #15496
visually 
<details>
```vue
<template>
<v-app>
<v-container>
:items="items"
dense
filled
clearable
@click:clear="alertListener"
label="Filled"
</v-container>
</v-app>
</template>
<script>
setup () {
return {
//
}
},
methods: {
alertListener() {
alert('Hello')
}
},
data: () => ({
value: null,
}),
}
</script>
```
</details>
=> fix(VAutocomplete): remove emit click:clear event

packages/docs/src/components/app/Toc.vue, packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.sass, packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.tsx, packages/vuetify/src/components/VNavigationDrawer/sticky.ts, packages/vuetify/src/composables/layout.ts
Only tested in docs, probably incorrect if there's a bottom footer or if the app-bar height changes.
=> feat(VNavigationDrawer): add sticky prop

packages/vuetify/src/components/VOverlay/_variables.scss
Added `!default` to overlay opacity variable to make it configurable.
IDK much about tests but I had to generate new snapshot to commit my changes and possibly all test ran successfully.
<details>
```vue
$overlay-opacity: 32%; => $overlay-opacity: 32% !default;
```
</details>
=> fix(VOverlay): add missing !default to $overlay-opacity 

packages/vuetify/src/util/colorUtils.ts, packages/vuetify/src/util/colors.ts
color picker in 2.x had a special case for swatch with "transparent" value. use hexa value instead and make sure colorToInt accepts it as a valid color
<details>
```vue
<v-color-picker show-swatches />
```
</details>
=> fix(VColorPicker): use hexa value for transparent color

packages/vuetify/src/components/VSelect/VSelect.sass, packages/vuetify/src/components/VSelect/VSelect.tsx
Missing feature in V3.0, `VSelect` component property: `placeholder`.
behaves as same as in v.2x.
Missing feature
visually tested with `next` branch
<details>
```vue
<template>
<v-app>
<v-container>
<v-select
:items="items"
placeholder="please select"
/>
</v-container>
</v-app>
</template>
<script>
setup () {
const selected = ref('')
{ title: 'item1', value: 1 },
{ title: 'item2', value: 2 },
])
return {
selected,
items,
}
},
}
</script>
```
</details>
=> fix(VSelect): display placeholder text

packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.sass, packages/vuetify/src/components/VNavigationDrawer/_variables.scss
opacity variable added to make opacity configurable
I have added a navigation drawer opacity variable to make opacity configurable.
IDK much about tests but I had to generate new snapshot to commit my changes and possibly all test ran successfully.
<details>
```vue
$navigation-drawer-overlay-opacity: .2 !default;
opacity: $navigation-drawer-overlay-opacity
```
</details>
=> feat(VNavigationDrawer): add scrim opacity variable

packages/vuetify/src/components/VCard/_variables.scss, packages/vuetify/src/styles/tools/_variant.sass
I have removed the `background` property from the `$card-transition-property:` variable to the background transition issue. SEE GIF
IDK much about tests but I had to generate new snapshot to commit my changes and possibly all test ran successfully.
<details>
```vue
$card-transition-property: box-shadow, opacity, background !default; => $card-transition-property: box-shadow, opacity !default;
```
</details>
=> fix(VCard): remove opacity transition from underlay

packages/vuetify/src/components/VToolbar/_variables.scss
Fix VToolbar height with prop `fullscreen`
It doesn't show height properly
visually and yarn test
<details>
```vue
<template>
<v-app>
<v-container>
<v-btn @click="dialog = true">show dialog</v-btn>
<v-dialog
@click:outside="cancel"
@keydown.esc="cancel"
>
<v-card width="500">
<v-toolbar
dark
>
<v-btn
icon
dark
@click="cancel"
>
<v-icon>mdi-close</v-icon>
</v-btn>
<v-toolbar-title>Settings</v-toolbar-title>
<v-spacer />
<v-btn
dark
text
@click="cancel"
>
Save
</v-btn>
</v-toolbar>
<v-card-title v-if="customTitle" class="mt-2">
<v-icon left color="primary"> mdi-delete-outline</v-icon>
title
<p class="d-flex justify-start mb-0 ml-7 text--secondary pr-6">
Delete …
```
=> fix(VToolbar): don't allow toolbar to grow in flex column

packages/vuetify/src/components/VTimeline/VTimeline.sass, packages/vuetify/src/components/VTimeline/VTimeline.tsx, packages/vuetify/src/components/VTimeline/_variables.scss
closes #15681
<details>
```vue
<template>
<v-locale-provider>
<v-card>
<v-timeline align="center">
<v-timeline-item>
<template v-slot:opposite>
Opposite content
</template>
<div>
<div class="text-h6">Content title 1</div>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</p>
</div>
<v-timeline-item>
<template v-slot:opposite>
Opposite content
</template>
<div>
<div class="text-h6">Content title 2</div>
<p>
Lorem ipsum dolor sit amet,
</p>
</div>
<v-timeline-item>
<template v-slot:opposite>
Opposite content
</template>
<div>
<div class="text-h6">Content title 3</div>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et …
```
=> feat(VTimeline): add justify prop

packages/docs/src/examples/v-autocomplete/misc-cryptocurrency-selector.vue
`item-value` usually should be unique so that we can uniquely identify selected search result.
But `symbol` is not unique, there are 5 cryptos with a symbol "zoo", for example.
So instead - use `id` which is unique.
One of developers in our team got confused into thinking that `item-value` controls rendered results.
visually (https://codepen.io/maxim_mazurok/pen/Jjvdbdp?editors=1011)
<details>
```html
<div id="app">
<v-toolbar color="orange accent-1">
<v-app-bar-nav-icon class="hidden-sm-and-down"></v-app-bar-nav-icon>
<v-toolbar-title class="text-h6 mr-6 hidden-sm-and-down">
Cryptocurrency
</v-toolbar-title>
:items="items"
:loading="isLoading"
chips
clearable
hide-details
hide-selected
item-text="name" …
```
=> docs: use "id" in item-value of autocomplete example

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VRangeSlider/VRangeSlider.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx, packages/vuetify/src/composables/proxiedModel.ts, packages/vuetify/src/composables/validation.ts
=> fix(VSelect): don't pass internal model to validation rules

packages/docs/package.json, packages/docs/src/components/menus/NotificationsMenu.vue, packages/docs/src/layouts/default/SystemBar.vue, packages/docs/src/store/modules/ads.js, packages/docs/src/store/modules/app.js, packages/docs/src/store/modules/banners.js, packages/docs/src/store/modules/index.js, packages/docs/src/store/modules/shopify.js, packages/docs/src/store/modules/sponsors.js, yarn.lock
integrate cosmic api for banner images
=> docs(SystemBar): integrate cosmic

packages/api-generator/src/maps/v-data-iterator.js
fix #15786
I'm using web-types of Vuetify 2 to generate component TS types. Wrong web-types will result into wrong type check of Volar.
<details>
```vue
```
</details>
=> docs(VDataIterator): remove duplicate default slot

packages/docs/src/pages/en/components/sliders.md, packages/vuetify/src/components/VInput/VInput.tsx, packages/vuetify/src/components/VLabel/VLabel.sass, packages/vuetify/src/components/VLabel/VLabel.tsx, packages/vuetify/src/components/VRadioGroup/VRadioGroup.tsx, packages/vuetify/src/components/VRangeSlider/VRangeSlider.tsx, packages/vuetify/src/components/VSelectionControl/VSelectionControl.tsx, packages/vuetify/src/components/VSlider/VSlider.sass, packages/vuetify/src/components/VSlider/VSlider.tsx, packages/vuetify/src/components/VSlider/_variables.scss
closes #15732
<details>
```vue
<template>
<div class="pa-4">
<v-slider label="Foo" />
<v-slider label="Foo" prepend-icon="mdi-home" />
<v-slider label="Foo">
<template #label>
LABEL
</template>
</v-slider>
<v-slider label="Foo">
<template #prepend>
PREPEND
</template>
</v-slider>
<v-range-slider label="Foo" />
<v-range-slider label="Foo" prepend-icon="mdi-home" />
</div>
</template>
```
</details>
=> fix(VSlider): add label

packages/docs/src/pages/en/getting-started/installation.md, packages/vuetify/dev/vuetify.js, packages/vuetify/package.json, packages/vuetify/src/composables/__tests__/theme.spec.ts, packages/vuetify/src/composables/display.ts, packages/vuetify/src/composables/locale.ts, packages/vuetify/src/composables/theme.ts, packages/vuetify/src/framework.ts, packages/vuetify/vite.config.mjs
Also fixes some SSR problems by requiring an explicit `options.ssr = true`
=> feat: allow vuetify services to be accessed outside of app

packages/vuetify/src/components/VSlider/VSliderTrack.sass, packages/vuetify/src/components/VSlider/VSliderTrack.tsx
closes #15814
<details>
```vue
<template>
<v-app>
<v-slider
min="-5"
max="5"
:ticks='{ "-1":"-1%", "1":"1%", "-5": "-5%"}'
show-ticks="always"
/>
<v-slider
min="-1"
max="1"
:ticks='{ "0":"0%", "0.5":"0.5%", "1":"1%"}'
show-ticks="always"
/>
</v-app>
</template>
```
</details>
=> fix(VSlider): fix incorrect tick positions

packages/docs/src/examples/v-toolbar/prop-dense.vue
<details>
```vue
```
</details>
=> docs: fix example dense to density

package.json, packages/api-generator/src/index.ts, packages/api-generator/src/types.ts, packages/vuetify/src/components/VOverlay/locationStrategies.ts, packages/vuetify/src/components/VOverlay/scrollStrategies.ts, packages/vuetify/src/util/helpers.ts, yarn.lock
=> docs(api): specify types to reference by link

packages/docs/src/pages/en/getting-started/upgrade-guide.md, packages/docs/src/pages/en/styles/colors.md
documentation changes for colors
The changes to lighten and darken variants were a bit difficult to find from the documentation.
na
na
=> docs: color variants

packages/vuetify/src/locale/pl.ts
translated remaining english texts in polish translations
playground
=> fix(locale): polish translation fixes

packages/vuetify/src/components/VImg/VImg.tsx
=> fix(VImg): missing emit typings

packages/vuetify/src/components/VDialog/__tests__/VDialog.spec.ts
<details>
```vue
```
</details>
=> chore(VDialog): correct "disabled" spelling error in test name

packages/docs/src/examples/blueprints/md1.vue, packages/docs/src/examples/blueprints/md2.vue, packages/docs/src/examples/blueprints/md3.vue, packages/docs/src/pages/en/features/blueprints.md
Improve blueprints documentation
=> docs(blueprints): update page content

packages/vuetify/src/components/VTabs/VTabs.tsx
expose mandatory prop, remove optional
- remove `optional` prop, instead use `:mandatory="false"`
<details>
```vue
```
</details>
=> feat(VTabs): expose mandatory prop, remove optional

packages/vuetify/src/components/VTextField/VTextField.tsx
fixes vuetifyjs#15901
v-text-field change to using onInput for IME users.
v-textarea already uses onInput.
Is there a reason why v-text-filed not used it?
issue reproduction link [CodePen](https://codepen.io/xignp/pen/NWMJQZN)
Playground.vue
<details>
```vue
<template>
<v-app>
<v-container>
<v-text-field v-model="field"></v-text-field>
<p>{{ field }}</p>
<v-textarea v-model="area"></v-textarea>
<p>{{ area }}</p>
</v-container>
</v-app>
</template>
<script>
setup() {
const field = ref("");
const area = ref("");
return {
field,
area,
};
},
};
</script>
```
</details>
=> fix(VTextField): update value using IME

packages/api-generator/src/locale/en/v-btn-toggle.json, packages/api-generator/src/locale/en/v-carousel.json, packages/api-generator/src/locale/en/v-chip-group.json, packages/api-generator/src/locale/en/v-tabs.json, packages/docs/src/examples/v-badge/misc-tabs.vue, packages/docs/src/examples/v-tabs/misc-tab-items.vue, packages/docs/src/examples/v-tabs/prop-fixed-tabs.vue
Updated some docs->
I've tested the stuff that i updated or added using the playground. I've also discovered a bug this way and created a report.
</details>
=> docs: update multiple api documentations and examples

packages/vuetify/src/components/VChip/VChip.sass, packages/vuetify/src/components/VChip/VChip.tsx
fixes vuetifyjs#15853
v-chip's backgroundcolor will be hightlight when mouse hover
Playground.vue
<details>
```vue
<template>
<v-app>
<v-container>
<v-chip>non-clickable</v-chip>
<v-chip @click="chipClick">clickable</v-chip>
</v-container>
</v-app>
</template>
<script>
setup() {
const chipClick = () => {
console.log("clicked")
}
return {
chipClick
};
},
};
</script>
```
</details>
=> fix(VChip): highlight overlay on hover

packages/api-generator/src/locale/en/v-text-field.json, packages/docs/src/examples/v-text-field/event-icons.vue, packages/docs/src/examples/v-text-field/prop-icon.vue, packages/docs/src/examples/v-textarea/prop-icons.vue
fixes #15955
`append-outer-icon` => `append-icon`
=> docs: fixes prop name

packages/docs/src/pages/en/features/application-layout.md, packages/vuetify/src/composables/layout.ts
expose raw values of v-main boundary
can be useful for users
<details>
```vue
```
</details>
=> feat(layout): expose raw values

packages/docs/src/pages/en/features/sass-variables.md
<details>
```vue
```
</details>
=> docs(sass-variables): remove redundant wording

packages/docs/src/components/menus/ReleasesMenu.vue
This PR updates releases switcher and removes `beta` label from 3.0.0 version
As 3.0.0 was considered stable, we don't need `beta` label anymore
visually
<details>
```vue
```
</details>
=> docs: remove beta label in releases menu

packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.sass
fixes #16019
visually 
<details>
```vue
<template>
<v-app>
<v-main style="padding:50px;background-color:darkgrey;">
<v-expansion-panels rounded="xl">
<v-expansion-panel>
<v-expansion-panel-title>test</v-expansion-panel-title>
<v-expansion-panel-text>test</v-expansion-panel-text>
<br>
<v-expansion-panels rounded="xl">
<v-expansion-panel>
<v-expansion-panel-title>test</v-expansion-panel-title>
<v-expansion-panel-text>test</v-expansion-panel-text>
<v-expansion-panel>
<v-expansion-panel-title>test</v-expansion-panel-title>
<v-expansion-panel-text>test</v-expansion-panel-text>
<br>
<v-expansion-panels rounded="xl">
<v-expansion-panel> …
```
=> fix(VExpansionPanel): single panel has missing border radius

packages/vuetify/src/components/VTable/VTable.sass
fixed some styles leaking to the inner tables
visually
<details>
```vue
<template>
<v-app>
<v-main>
<v-table fixed-header height="300px">
<thead>
<tr>
<th>Fixed header</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<v-table>
<thead>
<tr>
<th>Normal header</th>
</tr>
</thead>
<tbody>
<tr>
<td style="height: 1000px; background: #eee">blabla</td>
</tr>
</tbody>
</v-table>
</td>
</tr>
</tbody>
</v-table>
</v-main>
</v-app>
</template>
```
</details>
=> fix(VTable): prevent styles being inherited by inner tables

packages/vuetify/src/components/VList/VListItem.tsx, packages/vuetify/src/composables/router.tsx, packages/vuetify/src/util/helpers.ts
fixes #16014 
<details>
```vue
<template>
<v-container>
<v-menu>
<template #activator="{props}">
<v-btn v-bind="props">
Dropdown Menu
</v-btn>
</template>
<v-list>
<v-list-item title="cursor = pointer" link="foo" />
<v-list-item title="cursor != pointer" @click="foo" />
</v-list>
</v-menu>
</v-container>
</template>
<script>
methods: {
foo() {
console.log("foo");
}
}
};
</script>
```
</details>
=> fix(VListItem): infer link if click event is bound

packages/docs/src/pages/en/getting-started/unit-testing.md
<details>
```vue
```
</details>
=> docs(Unit Testing): remove unused import

LICENSE.md
Updated the license year from 2020 to 2022
In order to keep license updated
visually
=> docs: Updated license year from 2020 to 2022

packages/docs/src/pages/en/getting-started/unit-testing.md
Fixes a typo on the unit tests under spec tests
<details>
```vue
```
</details>
=> docs(Spec Tests): fix typo on unit spec tests

packages/docs/src/examples/v-banner/usage.vue
fixes #15236
This PR fixes #15236
=> docs(v-banner): fixes VBanner's usage, which was not updated correctly

packages/docs/src/pages/en/components/grids.md
Added a full stop in line 39
<details>
```vue
```
</details>
=> docs(grids.md): update punctuation

packages/docs/src/pages/en/getting-started/contributing.md, packages/docs/src/pages/en/styles/display.md
This PR improves the documentation for Contributing. Both in the way that it improves the information, but it also improves the style / format of the page at some places of the page.
This is a needed pull request because it will increase the amount of contributors and make it easier for new contributors to make their first contribution.
Since this is just documentation, it has been tested locally on my computer, both with a dev server and after building.
N/A
=> docs(contribution): improve info & format

packages/vuetify/src/components/VCard/VCard.sass
VCard.sass had some properties, which were hardcoded and were overwriting the properties that were using variables. I removed them and now VCard styles is using only variables (where needed)
fix #16095
<details>
```vue
```
</details>
=> fix(VCard): removed duplicated style properties

packages/docs/package.json, packages/docs/src/components/app/Toc.vue, packages/docs/src/components/app/bar/NotificationsMenu.vue, packages/docs/src/components/home/Sponsors.vue, packages/docs/src/components/sponsor/Card.vue, packages/docs/src/components/sponsor/Sponsors.vue, packages/docs/src/composables/cosmic.ts, packages/docs/src/shims.d.ts, packages/docs/src/store/ads.ts, packages/docs/src/store/app.ts, packages/docs/src/store/sponsors.ts, yarn.lock
Update cosmicjs to the latest version
<details>
```vue
```
</details>
=> docs(package.json): update cosmicjs version

packages/vuetify/src/components/VRating/VRating.tsx
Changed `modelValue` prop type from `number` to `string|number`
_Alternatively examples in docs could be changed from `model-value="3"` to `:model-value="3"`_
playground
<details>
```vue
<template>
<div>
<v-rating model-value="3" />
</div>
<div>
num: {{ num }} {{ JSON.stringify(num) }}
</div>
<div>
<v-rating v-model="num" half-increments />
</div>
<div>
str: {{ str }} {{ JSON.stringify(str) }}
</div>
<div>
<v-rating v-model="str" half-increments />
</div>
</template>
<script setup>
const num = ref(3)
const str = ref('3.5')
</script>
```
</details>
=> fix(VRating): allow string model-value

packages/vuetify/src/components/VSlideGroup/VSlideGroup.sass
Tabs cant scroll because slideGroup width overflow in flex layout (#16116)
<details>
```vue
<template>
<v-app>
<v-container>
<v-app-bar>
These tabs don't scroll:
<template #extension>
<v-tabs v-model="tab">
<v-tab v-for="n in length" :key="n" :value="n">
A very long tab {{ n }}
</v-tab>
</v-tabs>
</template>
</v-app-bar>
<v-main>
But these tabs do:
<v-tabs v-model="tab2">
<v-tab v-for="n in length" :key="n" :value="n">
A very long tab {{ n }}
</v-tab>
</v-tabs>
</v-main>
</v-container>
</v-app>
</template>
<script>
data: () => ({
length: 15,
tab: null,
tab2: null,
}),
setup() {
return {};
},
};
</script>
```
</details>
=> fix(VSlideGroup): container width overflow (#16116)

packages/docs/src/pages/en/features/aliasing.md
This fixes the example in docs at [virtual-component-defaults ](https://github.com/vuetifyjs/vuetify/blob/next/packages/docs/src/pages/en/features/aliasing.md#virtual-component-defaults) and [nested-defaults](https://github.com/vuetifyjs/vuetify/blob/next/packages/docs/src/pages/en/features/aliasing.md#nested-defaults).
The example shows an object around `defaults` which is invalid.
none
=> docs(aliasing): remove object around defaults in example

packages/vuetify/src/components/VProgressLinear/VProgressLinear.sass, packages/vuetify/src/components/VProgressLinear/_variables.scss
fixes #16170
<details>
```vue
```
</details>
=> fix(VProgressLinear): indeterminate spelling (#16170)

packages/docs/src/pages/en/features/sass-variables.md
Updated docs for sass variables
none
=> docs: clarified using vuetify sass variables in templates

packages/vuetify/src/components/VGrid/VGrid.sass
fixes #16211
playground
<details>
```vue
<v-app>
<v-container class="bg-grey">
<v-row>
<v-col>
<v-sheet class="pa-2"> 1 </v-sheet>
</v-col>
</v-row>
<v-row>
<v-col>
<v-sheet class="pa-2"> 2 </v-sheet>
</v-col>
</v-row>
<v-row>
<v-sheet class="pa-2"> 3 </v-sheet>
</v-col>
<v-sheet class="pa-2"> 4 </v-sheet>
</v-col>
</v-row>
</v-container>
</v-app>
```
</details>
=> fix(VRow): correct gutter between rows

packages/vuetify/src/components/VColorPicker/VColorPicker.tsx, packages/vuetify/src/components/VColorPicker/VColorPickerCanvas.tsx, packages/vuetify/src/components/VColorPicker/VColorPickerEdit.tsx, packages/vuetify/src/components/VColorPicker/VColorPickerPreview.tsx, packages/vuetify/src/components/VColorPicker/VColorPickerSwatches.tsx, packages/vuetify/src/components/VColorPicker/util/index.ts, packages/vuetify/src/composables/theme.ts, packages/vuetify/src/util/__tests__/colorUtils.spec.ts, packages/vuetify/src/util/color/APCA.ts, packages/vuetify/src/util/color/transformSRGB.ts, packages/vuetify/src/util/colorUtils.ts
=> fix: parse all colors to rgba objects instead of numbers

packages/vuetify/src/components/VChip/VChip.tsx
Instead of `isClickable.value` only `isClickable` is used as value to check if `v-chip` component should add link class to component.
I did found it using latest version of library, it looks strange if there is no real action after click.
visually
<details>
```vue
```
</details>
=> fix(VChip): component always shows cursor pointer

packages/docs/src/examples/v-bottom-sheet/prop-model.vue
The `tiles` property is unused.
The `tiles` property is unused and thereby only unnecessary and confusing.
visually 
<details>
```vue
<template>
<v-btn
color="blue"
dark
@click="sheet = !sheet"
>
Open v-model
</v-btn>
<v-bottom-sheet v-model="sheet">
<v-sheet
class="text-center"
height="200px"
>
<v-btn
class="mt-6"
text
color="red"
@click="sheet = !sheet"
>
close
</v-btn>
<div class="py-3">
This is a bottom sheet using the controlled by v-model instead of activator
</div>
</v-sheet>
</v-bottom-sheet>
</div>
</template>
<script>
data: () => ({
sheet: false,
}),
}
</script>
```
</details>
=> docs(VBottomSheet): remove unused property from example

packages/vuetify/src/components/VBottomNavigation/VBottomNavigation.tsx
fixes #16041
fixes #16041
visually
<details>
```vue
<script setup>
const model = ref(null)
</script>
<template>
<v-app>
<v-container>
<v-text-field type="number" v-model.number="model" />
<v-bottom-navigation v-model="model">
<v-btn :value="0">One</v-btn>
<v-btn :value="1">Two</v-btn>
<v-btn :value="2">Three</v-btn>
</v-bottom-navigation>
</v-container>
</v-app>
</template>
```
</details>
=> fix(VBottomNavigation): use active prop for visibility

packages/vuetify/src/components/VRadioGroup/VRadioGroup.sass, packages/vuetify/src/components/VRadioGroup/_variables.scss
fixes #16207
The related styling, VRadioGroup.sass, actually defines some margins to add space between control group and label. However, the SASS code does not consider the v-input__control element correctly.
playground
<details>
```vue
<template>
<v-app>
<v-main>
<v-radio-group label="Radio box title">
<v-radio label="First radio button"></v-radio>
<v-radio label="Second radio button"></v-radio>
</v-main>
</v-app>
</template>
```
</details>
=> fix(VRadioGroup): correct margin definitions

packages/vuetify/src/locale/ar.ts
I clarified, fixed, and completed translating all texts in `ar.ts`.
Fixes #16185 
The Arabic locale file is not complete. Some texts are not translated, others have unclear translations.
Fixes #16185 opened by myself.
Visually.
None.
<details>
```vue
```
</details>
=> fix(locale): update arabic translations

packages/docs/src/pages/en/introduction/why-vuetify.md
<details>
```vue
```
</details>
=> (docs) fix typo

packages/api-generator/src/index.ts, packages/docs/src/data/nav-alpha.json, packages/docs/src/i18n/messages/en.json, packages/docs/src/pages/en/labs/introduction.md, packages/docs/src/plugins/vuetify.ts, packages/vuetify/_settings.scss, packages/vuetify/build/rollup.config.js, packages/vuetify/build/rollup.types.config.js, packages/vuetify/package.json, packages/vuetify/src/labs/components.ts, packages/vuetify/src/labs/index.ts
=> feat(labs): add labs export

packages/docs/src/pages/en/introduction/why-vuetify.md
<details>
```vue
```
</details>
=> docs(why-vuetify): fix Feature Guides links

packages/vuetify/src/components/VAppBar/VAppBarTitle.tsx
fixes #16375
`VToolbarTitle` allows to specify text via `text` property.
For consistency reasons, this `VAppBarTitle` should do that as well.
playground
<details>
```vue
<template>
<v-app>
<v-app-bar color="blue">
<v-app-bar-title>v-app-bar-title default slot</v-app-bar-title>
</v-app-bar>
<v-app-bar color="yellow">
<v-app-bar-title text="v-app-bar-title text prop" />
</v-app-bar>
<v-main style="margin: 16px">
<v-toolbar color="blue">
<v-toolbar-title>v-toolbar-title default slot</v-toolbar-title>
</v-toolbar>
<v-toolbar color="yellow">
<v-toolbar-title text="v-toolbar-title text-prop" />
</v-toolbar>
</v-main>
</v-app>
</template>
```
</details>
=> fix(VAppBarTitle): pass props to VToolbarTitle

packages/docs/src/pages/en/features/internationalization.md
fix #16339.
I didn't test with composable, maybe it needs a fix too.
<details>
```vue
```
</details>
=> docs(internationalization): correct locale for options api use

packages/vuetify/src/components/VAppBar/__tests__/VAppBar.spec.cy.tsx
This ports the tests from #16108 so they can be used for #16267
PR #16267 needed e2e tests, so I implemented them.
e2e
<details>
```vue
```
</details>
=> test(VAppBar): tests for hide scrolling behavior

packages/api-generator/src/locale/en/v-overlay-location-strategies.json
Edit `location` line description to specify different locations
<details>
```vue
```
</details>
=> docs(VSnackbar): update api description for location

packages/vuetify/src/composables/teleport.ts
using the global cache caused HMR issues, as seen in vuetify-playground
<details>
```vue
<template>
<v-btn
>
Open Dialog
<v-dialog
activator="parent"
>
<v-card>
<v-card-text>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</v-card-text>
<v-btn color="primary" block @click="dialog = false">Close Dialog</v-btn>
</v-card>
</v-dialog>
</v-btn>
</div>
</template>
<script>
data () {
return {
dialog: false,
}
},
}
</script>
```
</details>
=> fix(teleport): use querySelector instead of cache

packages/docs/src/pages/en/styles/border-radius.md
<details>
```vue
```
</details>
=> docs(border-radius): Fix typo infix class

packages/docs/src/pages/en/styles/display.md
<details>
```vue
```
</details>
=> docs(display): Fix d-xs-{value} typo

packages/docs/src/examples/elevation/usage.vue
<details>
```vue
```
</details>
=> docs(elevation): Example - index n in 0...24 range

packages/vuetify/src/components/VCard/VCard.tsx, packages/vuetify/src/components/VList/VListItem.tsx, packages/vuetify/src/components/VSlider/VSliderThumb.tsx
Exposes the ripple prop in all components that were missing it
Allows additional configuration & disabling of the ripple feature at a global level
visually
<details>
```vue
<template>
<v-app>
<v-container>
<v-list>
<v-list-item active-color="primary" to="/" exact title="foo" :ripple="false" />
<v-list-item active-color="primary" to="/page1" title="bar" :ripple="false" />
<v-list-item active-color="primary" to="/nested/page1" title="baz" :ripple="false" />
<v-list-item active-color="primary" to="/nested/page2" title="bro" :ripple="false"/>
</v-list>
</v-container>
</v-app>
</template>
</script>
```
</details>
=> fix: expose missing ripple prop in components

packages/docs/src/pages/en/features/blueprints.md
<details>
```vue
```
</details>
=> docs(blueprints): Update MD links and availability

packages/docs/src/examples/text-and-typography/typography-breakpoints.vue
<details>
```vue
```
</details>
=> docs(text-and-typography): Fix typo text-h6

packages/docs/src/data/nav-alpha.json, packages/docs/src/examples/v-data-table/slot-group-header.vue, packages/docs/src/examples/v-data-table/slot-item-key.vue, packages/docs/src/pages/en/components/data-tables/basics.md, packages/docs/src/pages/en/components/data-tables/slots.md, packages/vuetify/src/labs/VDataTable/VDataTableGroupHeaderRow.tsx, packages/vuetify/src/labs/VDataTable/VDataTableRows.tsx, packages/vuetify/src/labs/VDataTable/composables/group.ts
added item and group-header slots
playground
<details>
```vue
see doc examples
```
</details>
=> feat(VDataTable): add item and group-header slots

packages/docs/src/pages/en/features/accessibility.md
<details>
```vue
```
</details>
=> docs(a11y): Fix v-select example typos

packages/api-generator/src/locale/en/v-text-field.json
<details>
```vue
```
</details>
=> docs(v-text-field): api information for update modelValue

packages/vuetify/src/components/VFileInput/VFileInput.sass
<details>
https://play.vuetifyjs.com/#eNqFkLtyAiEUhl+FobFxIRfTbNaMeYG0KcQCBZXIbYA1Gsd3z4HdYuNOko7/XL7z8y8v+NV7cmwlrnGTpPGaJ/nCLELNseLel2cRhivbq6K3SstKWd8mpPla6jnDbw6JwHeIWwEP5xlG9J+Vd5X2o6WN5jFCU1gBO6cBpqEDI1l0Fhs6sA4yprPOT9ITUDm6TGcv55PsYrJCl4z4AjtCnmp0/8zsNYO6VTzFyngXElzz5CM6C/mUDdY3IsN1x8g1CDBrhvcp+VhT2lp/2JGNM3QBPRpam5SRlXBm8UgeyOyJChXTsE5kNNU6uM8oA1xkeDqAJ7U9/3agbwP3jsw6bF/KyBGKAv8oQxUk/DzI8Kfvm9kf3m96I//5JkR6hSy1sod4E+MmlgiXqzxyneIODcPlH3j1DbIh3HA=
</details>
=> fix(VFileInput): drag and drop

packages/api-generator/src/locale/en/v-label.json
Added description of the text property
<details>
```vue
```
</details>
=> chore(api-generator): update v-label.json text property

packages/docs/src/pages/en/components/cards.md
Small update of documentation :
- Update v-expend-transition outdated link
- Better format Markdown tables
=> docs(VCard): update outdated link

packages/docs/src/pages/en/components/application.md
=> docs(application): Fix typos

packages/docs/src/pages/en/components/alerts.md, packages/docs/src/pages/en/components/application.md, packages/docs/src/pages/en/components/badges.md, packages/docs/src/pages/en/components/defaults-providers.md, packages/docs/src/pages/en/components/locale-providers.md, packages/docs/src/pages/en/components/progress-linear.md, packages/docs/src/pages/en/components/theme-providers.md, packages/docs/src/pages/en/introduction/enterprise-support.md, packages/docs/src/pages/en/introduction/long-term-support.md
=> docs: fix API links and typos

packages/docs/src/pages/en/components/app-bars.md
=> docs(app-bars): density prop

packages/vuetify/src/locale/sv.ts
Went through the newly released code and spotted some small stuff in the swedish translation that I figured was worth fixing. Did not find proper translations for two untranslated text so I left them untouched.
=> fix(locale): update swedish locale messages

packages/vuetify/src/composables/nested/nested.ts
fixes https://github.com/vuetifyjs/vuetify/issues/16558
=> fix: getUid must be called from inside a setup function

packages/docs/src/examples/v-btn/prop-variant.vue
=> docs(VBtn): fix typo

packages/docs/src/pages/en/features/global-configuration.md
=> docs(VDefaultsProvider): fix broken link to the api

packages/api-generator/src/locale/en/v-field.json
=> docs(VField): add id api description

packages/docs/src/examples/v-card/misc-card-reveal.vue, packages/vuetify/src/components/transitions/createTransition.ts, packages/vuetify/src/styles/generic/_transitions.scss
fixes #16137
fixes #14440
```vue
<template>
<v-card
max-width="344"
>
<v-card-text>
<div>Word of the Day</div>
<p class="text-h4 text--primary">
el·ee·mos·y·nar·y
</p>
<p>adjective</p>
<div class="text--primary">
relating to or dependent on charity; charitable.<br>
"an eleemosynary educational institution."
</div>
</v-card-text>
<v-btn
variant="text"
color="teal-accent-4"
@click="reveal = true"
>
Learn More
</v-btn>
<v-expand-transition>
<v-card
v-if="reveal"
class="v-card--reveal"
style="height: 100%;"
>
<v-card-text class="pb-0">
<p class="text-h4 text--primary">
Origin
</p>
<p>late 16th century (as a noun denoting a place where alms were distributed): from medieval Latin eleemosynarius, from late Latin eleemosyna ‘alms’, from Greek …
```
=> fix(transitions): add !important, explicit transition-property

packages/vuetify/cypress/support/mount.ts, packages/vuetify/src/components/VAppBar/__tests__/VAppBar.spec.cy.tsx, packages/vuetify/src/components/VBottomNavigation/__tests__/VBottomNavigation.spec.cy.tsx, packages/vuetify/src/components/VChip/__tests__/VChip.spec.cy.tsx, packages/vuetify/src/components/VColorPicker/__tests__/VColorPicker.spec.cy.tsx, packages/vuetify/src/components/VForm/__tests__/VForm.spec.cy.tsx, packages/vuetify/src/components/VList/__tests__/VListItem.spec.cy.tsx, packages/vuetify/src/components/VNavigationDrawer/__tests__/VNavigationDrawer.spec.cy.tsx, packages/vuetify/src/components/VRating/__tests__/VRating.spec.cy.tsx, packages/vuetify/src/components/VSlider/__tests__/VSlider.spec.cy.tsx, packages/vuetify/src/components/VSystemBar/__tests__/VSystemBar.spec.cy.tsx, packages/vuetify/src/components/VTabs/__tests__/VTabs.spec.cy.tsx, packages/vuetify/src/components/VWindow/__tests__/VWindow.spec.cy.tsx, packages/vuetify/src/labs/VDataTable/__tests__/VDataTable.spec.cy.tsx, packages/vuetify/src/labs/VDataTable/__tests__/VDataTableServer.spec.cy.tsx, packages/vuetify/src/labs/VVirtualScroll/__tests__/VVirtualScroll.spec.cy.tsx, packages/vuetify/types/cypress.d.ts
`emitted` is now typed
```vue
```
=> chore: clean up e2e tests and improve types

packages/vuetify/src/components/VTabs/VTabs.sass, packages/vuetify/src/components/VTabs/_variables.scss
<details>
```vue
```
</details>
=> feat(VTabs): add tab-text-transform SASS variable

packages/api-generator/src/locale/en/v-table.json
The descriptions are from document 2.6.14 .
=> docs(VTable): Add description to props ( fixedHeader / height )

packages/docs/src/data/team.json
```json
"santiagoaloi": {
"discord": "lannister#9474",
"focus": [
"[vuetifyjs/docs](https://github.com/vuetifyjs/vuetify/tree/master/packages/docs)"
],
"languages": [
"Swedish",
"English",
"Spanish"
],
"linkedin": "santiagoaloi",
"location": "Stockholm, Sweden",
"name": "Santiago Aloi",
"team": "core"
}
```
=> docs(team.json): add lannister

packages/docs/src/components/about/TeamMember.vue, packages/docs/src/data/team.json
added:
- Yoones Khoshghadam
- Elvina Garcia
- Yuchao Wu
=> docs(team): add core team members

packages/docs/src/examples/v-rating/misc-card-overview.vue, packages/docs/src/examples/v-rating/misc-card.vue, packages/docs/src/pages/en/components/ratings.md
Crated a new example card for rating docs component page.
=> docs(rating): add example card

packages/api-generator/src/locale/en/v-selection-control-group.json
Added `id`,` error`, `readonly`, `multiple`, `trueIcon`, and `falseIcon` descriptions to the documentation.
```vue
```
=> docs(VSelectControlGroup): add api descriptions

packages/docs/src/pages/en/features/theme.md
=> docs(theme): fix composable link

packages/vuetify/src/components/VSlider/slider.ts
Keep fix for #16634
Port the same changes in PR #16667 to dev
```vue
<template>
<v-app>
<v-main class="mt-10">
<v-slider
:model-value="1.001"
:step="1.001"
:min="1.0001"
:max="10"
thumb-label
/>
</v-main>
</v-app>
</template>
<script setup>
</script>
```
=> chore: port fix for #16634 to dev

packages/docs/src/pages/en/components/slide-groups.md
Fixed wrong link for slide group item.
=> fix: update slide-groups.md

packages/docs/src/pages/en/getting-started/installation.md
When using laravel-mix we needed to copy the fonts to the dist folder.
=> docs(installation.md): Add Laravel Mix Support

packages/api-generator/src/locale/en/v-overlay-activator.json
=> docs(v-overlay-activator.json): Add description for close-on-content-click prop

packages/docs/src/pages/en/getting-started/installation.md
Fixes `puposes` to `purposes` in the Nightly Builds section on the Installation page.
=> docs(installation): correct spelling mistake

packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.tsx
fixes #15514
```vue
<template>
<v-app>
<v-container>
<v-expansion-panels>
<v-expansion-panel
v-for="i in 3"
:key="i"
title="Item"
text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
/>
</v-container>
</v-app>
</template>
```
=> fix(VExpansionPanel): remove duplicate aria-expanded

packages/docs/src/examples/border-radius/usage.vue, packages/docs/src/pages/en/styles/border-radius.md, packages/vuetify/src/styles/settings/_variables.scss
add option: `2xl` to border radius
th step between lg, xl was too big, So I've added new value between
old code:
- `'lg': $border-radius-root * 2`
- `'xl': $border-radius-root * 6`
new code:
- `'lg': $border-radius-root * 2`
- `'xl': $border-radius-root * 4` 
- `'2xl': $border-radius-root * 6` 
<details>
```vue
```
</details>
=> feat(styles): add xxl border-radius option

packages/vuetify/src/labs/VDataTable/VDataTableVirtual.tsx
Recent changes messed up v-data-table-virtual when using the item slot.
This moves the item slot inside the VirtualScrollItem so that height is calculated properly within the slot.
[Playground Reproduction in Latest](https://play.vuetifyjs.com/#eNrVlllv2zgQgP8KobawDViHzyRCEqRI9+h2HxbYp0UcoLTE2NxIpEBSznoN//cOZVKUZaVOH4sAsT0H55tD1DzsvI9FEWxK4sXetSJ5kWFFbhcMoeuUbm5fqFojmXF1HeqflXzjp1hhX+FlRvwNFarEmVYgFK8JTomQNwvPfFt4RkPhbC039p+IlESoWp9kWGo1ycgGK8qZP7KqNaGrtQLdNIqsTJ/mb3BWEpAznJODouIDQpsHeqcNwWRXeQxRIXghh0jx1Sojf0OwRKH9wjN+7dwEf7EKhDb+krIUzqrOsCBVbs9kC3IdIQAT8l9TeZdkNHkGdTNmX9sOnJmLH7YBbErhcW+O7UxRQXXUOF6qn6h3r+Z0lDv8lImgBWRGVFlUWdG84EKhHUp4XpSKpGiPngTPUQ/muncoSsKZVMBTZYZu0MMBZmcrr6jKSIx6JjnUH0XRCmKIDWWrQW9o7XBGVwzspMJCObEEAI0doyecSVLLYTTAWGdpbffmc1eHvMcZF5TI3rA+nbAUfh2cE6vucP0VA6nG6/R8wqrL6R6 …
=> fix(VDataTableVirtual): move slot inside VVirtualScrollItem

packages/api-generator/src/locale/en/VMenu.json
=> docs: Add '0' max-width option to VMenu from #17634 response

packages/vuetify/src/composables/__tests__/validation.spec.ts, packages/vuetify/src/composables/validation.ts
fixes #17548
Allow validation to return false
```vue
<template>
<v-app>
<v-container>
valid = {{ valid }}
<v-form v-model="valid">
<v-text-field v-model="msg" :rules="msgRules" />
</v-form>
</v-container>
</v-app>
</template>
<script setup>
const valid = ref(true)
const msgRules = [value => value !== 'bad']
</script>
```
=> fix(validation): allow validation to return false

packages/vuetify/src/components/VField/VField.sass, packages/vuetify/src/components/VField/_variables.scss, packages/vuetify/src/components/VTextField/VTextField.sass, packages/vuetify/src/components/VTextField/VTextField.tsx, packages/vuetify/src/components/VTextField/_variables.scss
fixes #17719
```vue
<template>
<v-app>
<v-container style="width: 1250px">
<h3>Outlined (compact)</h3>
<v-row>
<v-col>
<v-text-field
:model-value="'California'"
placeholder="Hello"
prefix="prefix"
suffix="suffix"
/>
</v-col>
<v-col>
:model-value="'California'"
placeholder="Hello"
prefix="prefix"
suffix="suffix"
/>
</v-col>
<v-col>
<v-combobox
:model-value="'California'"
placeholder="Hello"
prefix="prefix"
suffix="suffix"
/>
</v-col>
<v-col>
<v-select
:items="['California', 'Colorado', 'Florida', 'Georgia', …
```
=> fix(VTextField): align prefix/suffix with input and chips

packages/vuetify/src/components/VCarousel/VCarousel.tsx
fixes #17586 
```vue
<template>
<v-app>
<v-container>
<v-carousel direction="vertical">
src="https://cdn.vuetifyjs.com/images/cards/docks.jpg"
cover
/>
src="https://cdn.vuetifyjs.com/images/cards/hotel.jpg"
cover
/>
src="https://cdn.vuetifyjs.com/images/cards/sunshine.jpg"
cover
/>
</v-carousel>
<v-carousel>
src="https://cdn.vuetifyjs.com/images/cards/docks.jpg"
cover
/>
src="https://cdn.vuetifyjs.com/images/cards/hotel.jpg"
cover
/>
src="https://cdn.vuetifyjs.com/images/cards/sunshine.jpg"
cover
/>
</v-carousel>
</v-container>
</v-app>
</template>
```
=> fix(VCarousel): fix carousel direction props

packages/api-generator/src/locale/en/VFileInput.json
=> docs(events): add description for click:clear event

packages/docs/src/pages/en/introduction/why-vuetify.md
Fix word typo and sentence phrase.
=> docs: fix typo and sentence phrase

packages/api-generator/src/locale/en/VOverlay.json
resolves #16086
*Also fixed the "edit in github" links within the same file.*
=> docs: Clarified the `contained` prop of v-overlay

packages/docs/src/examples/v-combobox/usage.vue
Added multiple checkbox value into return statement.
=> docs(VCombobox): fix multiple in return statement

packages/vuetify/src/labs/date/adapters/__tests__/vuetify.spec.ts
Due to #17961 `date > adapter > vuetify.spec.ts` test was failing.
Updated test to accommodate changes from the PR
=> test(date): validate narrow format

packages/vuetify/src/components/VTimeline/VTimeline.sass
#17923 did not fully resolved the horizontal timeline issue. There is still gap visible in divider.
This PR resolves the gap issue in horizontal timeline.
```vue
<template>
<v-container>
<v-timeline side="end" direction="horizontal">
<v-timeline-item
:key="item.id"
:dot-color="item.color"
size="small"
>
<v-alert
:value="true"
:color="item.color"
:icon="item.icon"
>
Lorem ipsum dolor sit amet, no nam oblique veritus. Commune scaevola imperdiet nec ut, sed euismod convenire principes at. Est et nobis iisque percipit, an vim zril disputando voluptatibus, vix an salutandi sententiae.
</v-alert>
</v-timeline>
</v-container>
<v-container>
<v-timeline direction="horizontal">
<v-timeline-item
:key="item.id"
:dot-color="item.color" …
```
=> fix(VTimeline): Move padding from grid to _body & _opposite for horizontal timeline.

packages/api-generator/src/locale/en/Select.json, packages/api-generator/src/locale/en/VAutocomplete.json, packages/api-generator/src/locale/en/VSelect.json
=> docs(Selects): update menu-props api description

packages/api-generator/src/locale/en/VDefaultsProvider.json, packages/api-generator/src/locale/en/VField.json, packages/api-generator/src/locale/en/group.json
Fix some minor typos in the documentation
=> docs: fix various typos

packages/docs/src/pages/en/styles/text-and-typography.md
Add robot font reference in text and typography.
=> docs(text-and-typography): add reference to default font

packages/vuetify/src/composables/resizeObserver.ts
Fix build error on dev branch, it's caused by helper function change in #18013
The error stops #18025 from publishing a nightly release
=> chore: fix build error on dev branch

packages/docs/src/pages/en/components/data-tables/basics.md, packages/docs/src/pages/en/components/data-tables/server-side-tables.md
=> docs(VDataTable): fix broken import link

packages/vuetify/dev/vuetify.js, packages/vuetify/src/components/VSelectionControl/VSelectionControl.tsx, packages/vuetify/src/components/VSwitch/VSwitch.sass, packages/vuetify/src/components/VSwitch/VSwitch.tsx, packages/vuetify/src/components/VSwitch/_variables.scss, packages/vuetify/src/composables/__tests__/__snapshots__/theme.spec.ts.snap, packages/vuetify/src/composables/theme.ts
fixes #18089
```vue
<template>
<p>{{ people }}</p>
<v-switch
v-model="people"
label="John"
value="John"
hide-details
true-icon="mdi-check"
false-icon="mdi-close"
/>
<v-switch
v-model="people"
label="John"
value="John"
hide-details
true-icon="mdi-check"
false-icon="mdi-close"
inset
/>
<v-switch
v-model="people"
label="Jacob"
value="Jacob"
hide-details
/>
<v-switch
v-model="people"
label="Jacob"
value="Jacob"
hide-details
inset
/>
<v-card theme="dark">
<v-card-text>
<v-switch
v-model="people"
label="John"
value="John"
hide-details
true-icon="mdi-check"
false-icon="mdi-close"
/>
<v-switch
v-model="people"
label="John"
value="John"
hide-details
true-icon="mdi-check"
false-icon="mdi-close"
inset …
```
=> fix(VSwitch): improve dark theme visibility

packages/vuetify/src/locale/bg.ts
Updated Bulgarian localization
=> refactor(locale): translate to bulgarian

packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.sass, packages/vuetify/src/components/VExpansionPanel/VExpansionPanelTitle.tsx, packages/vuetify/src/components/VExpansionPanel/VExpansionPanels.tsx
<details>
```vue
<template>
<v-app>
<div>
<div class="text-subtitle-2 mb-2">Default</div>
<v-expansion-panels static>
<v-expansion-panel
v-for="i in 3"
:key="i"
title="Item"
text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
/>
<div class="text-subtitle-2 mt-4 mb-2">Accordion</div>
<v-expansion-panels variant="accordion" static>
<v-expansion-panel
v-for="i in 3"
:key="i"
title="Item"
text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud …
```
=> feat(VExpansionPanels): add static prop

packages/vuetify/src/locale/fr.ts
- translate new `loading` text
- use ellipsis character instead of `...`
=> fix(locale): Update French translations

packages/api-generator/src/locale/en/VNavigationDrawer.json
Updated scrim definition - missing.
```vue
```
=> docs: update v-navigation-drawer scrim definition

packages/api-generator/src/locale/en/generic.json
Old description was a little bit unclear or misleading 😕
=> docs: update valueComparator description

packages/docs/src/pages/en/features/sass-variables.md, packages/docs/src/pages/en/getting-started/installation.md, packages/docs/src/pages/en/getting-started/unit-testing.md
Add docs for `bun` package manager.
Sister PR updating `create-vuetify`: https://github.com/vuetifyjs/create-vuetify/pull/28
=> docs: add bun

packages/docs/src/pages/en/getting-started/unit-testing.md
Closes https://github.com/vuetifyjs/vuetify/issues/18258 by renaming tab to `bun`
```vue
```
=> docs: rename bun's tab

packages/vuetify/src/components/VApp/VApp.sass, packages/vuetify/src/components/VApp/VApp.tsx, packages/vuetify/src/composables/layout.ts
Issue - https://github.com/vuetifyjs/vuetify/issues/18064
```vue
<template>
<v-app>
<v-container>
<v-text-field v-model="msg" />
</v-container>
</v-app>
</template>
<script setup>
</script>
```
=> fix(VApp): remove layout styles

packages/docs/src/pages/en/getting-started/upgrade-guide.md, packages/vuetify/src/components/VBanner/VBanner.tsx
This PR adds a `bg-color` prop to `VBanner` to allow the user to change the color of the background seperately from the color of the icon and action text. It also updates the upgrade guide to indicate this, since this behavior is different from v2.
resolves #17124
```vue
<template>
<v-app>
<v-container>
<v-banner text="default" color="blue">
<template #actions>
<v-btn>Close</v-btn>
</template>
</v-banner>
<v-banner text="success" bg-color="success">
<template #actions>
<v-btn>Close</v-btn>
</template>
</v-banner>
<v-banner text="warning" bg-color="warning" />
<v-banner text="warning compact" bg-color="warning" density="compact" />
<v-banner text="warning" bg-color="warning">
<template #actions>
<v-btn>Close</v-btn>
</template>
</v-banner>
<v-banner text="warning compact" …
```
=> feat(VBanner): add `bg-color` prop

packages/docs/src/examples/v-card/prop-color.vue, packages/docs/src/examples/v-card/prop-elevated.vue, packages/docs/src/examples/v-card/prop-variant.vue, packages/docs/src/pages/en/components/cards.md
=> docs(VCard): add examples

packages/docs/src/examples/v-window/misc-onboarding.vue
=> docs(VWindow): fix broken windows example

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx
Fix the issue by checking disabled prop when removing item using backspace.
fixes #18298 
```vue
<template>
<v-card>
<v-row>
v-model="vAutocompleteValues"
:items="vAutocompleteItems"
label="VAutocomplete"
multiple
chips
closable-chips
return-object
</v-col>
</v-row>
<v-row>
<v-combobox
v-model="vComboboxValues"
:items="vComboboxItems"
label="VCombobox"
multiple
chips
closable-chips
return-object
></v-combobox>
</v-col>
</v-row>
</v-container>
</v-card>
</template>
<script>
data: () => ({
vAutocompleteItems: [
{ title: 'Item 1', value: 'item1', props: { disabled: true } },
{ title: 'Item 2', value: 'item 2' },
{ title: 'Item 3', value: 'item 3' },
],
vAutocompleteValues: [
{ title: …
```
=> fix(VCombobox): prevent removing disabled items with backspace

packages/docs/src/pages/en/getting-started/installation.md
Added instructions to the installation page to get Vuetify working in Nuxt 3
```vue
```
=> docs: Add Nuxt3 install instructions

packages/vuetify/src/labs/VDataTable/VDataTable.sass
resolves #17714
``` background: rgb(var(--v-theme-surface)) ``` - overwrites the selected background color
```vue
<template>
<v-app style="background-color: #c8e6c9">
<v-container>
<h1 class="text-center my-3">v-data-table</h1>
<p class="my-3 text-green">
css background-color property provided with css-class
</p>
<v-data-table
multi-sort
class="bg-orange"
<p class="my-3 text-green">
css background-color: transparent property provided with css-class
</p>
<v-data-table
class="bg-transparent"
multi-sort
<p class="my-3 text-green">
without css background-color property provided
</p>
<v-data-table …
```
=> fix(VDataTable): bg color change via class

packages/vuetify/src/components/VList/__tests__/VList.spec.cy.tsx
@johnleider, as per your request, a cy test that verifies `return-object` in VList is made
=> chore: add cy test to check return-object in VList

packages/vuetify/src/locale/nl.ts
Adds the missing Dutch translations.
```vue
```
=> fix(locale): update Dutch translations

packages/docs/src/examples/v-progress-circular/prop-slot-default.vue, packages/docs/src/pages/en/components/progress-circular.md
Really simple example (just adding '%' in the text)
=> docs(VProgressCircular): add example for default slot

packages/docs/src/pages/en/components/steppers.md
Added the actions API to the stepper doc, as it's accessible from the urls
```vue
```
=> docs(VStepper): add v-stepper-actions to api

packages/api-generator/src/locale/en/VTextarea.json
=> docs(VTextarea): update missing counterValue description

packages/vuetify/src/composables/filter.ts, packages/vuetify/src/labs/VDataTable/VDataTable.tsx, packages/vuetify/src/labs/VDataTable/VDataTableVirtual.tsx, packages/vuetify/src/labs/VDataTable/composables/headers.ts, packages/vuetify/src/labs/VDataTable/composables/sort.ts, packages/vuetify/src/labs/VDataTable/types.ts
closes #17588
```vue
<template>
<v-app>
<v-container>
<v-text-field v-model="search" />
<v-data-table :items="items" :headers="headers" :search="search" filter-mode="some" />
</v-container>
</v-app>
</template>
<script setup>
const search = ref()
{ key: 'name', title: 'Name' },
{
key: 'calories',
title: 'Calories',
sort: (a, b) => b - a,
},
{ key: 'fat', title: 'Fat' },
{ key: 'carbs', title: 'Carbs' },
{
key: 'protein',
title: 'Protein',
filter: (value, query, item) => {
return String(value).replace('.', '').includes(query)
},
},
{ key: 'iron', title: 'Iron' },
]
{
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1',
},
{
calories: 237,
fat: 9.0,
carbs: 37,
protein: 4.3, …
```
=> feat(VDataTable): add sort and filter functions to headers

packages/docs/src/pages/en/introduction/roadmap.md
=> docs(roadmap): correct release notes link

packages/docs/src/examples/v-infinite-scroll/usage.vue
=> docs(VInfiniteScroll): Fix Usage Example

packages/docs/src/pages/en/components/date-pickers.md
The range of dates is not supported in V3 yet.
=> docs: fix date pickers example description

packages/vuetify/src/locale/ru.ts
=> fix(translation): ru translation

packages/vuetify/src/components/VField/VField.sass
fixes #18469 
```vue
<template>
<v-app>
<v-container>
<v-autocomplete v-model="msg" clearable style="width: 320px" />
</v-container>
</v-app>
</template>
<script setup>
const msg = ref('Hello World! This title will be cut off at some point.')
</script>
```
=> fix(VField): display clearable icon with touch device

packages/vuetify/src/components/VFileInput/VFileInput.sass
fixes #18791
```vue
<template>
<v-form>
<v-container>
<v-row>
<v-col cols="12" sm="6">
<v-text-field
label="Your product or service"
model-value="Grocery delivery"
hint="For example, flowers or used cars"
variant="underlined"
</v-col>
<v-col cols="12" sm="6">
<v-text-field
label="Your landing page"
hint="www.example.com/page"
variant="underlined"
</v-col>
<v-col cols="12" sm="6">
<v-text-field
label="Your landing page"
hint="www.example.com/page"
</v-col>
<v-col cols="12" sm="6">
<v-file-input
label="Your landing page"
hint="www.example.com/page"
variant="underlined"
</v-col>
<v-col cols="12" sm="6">
<v-file-input
label="Your landing page" …
```
=> fix(VFileInput): fix hint not aligned with underlined variant

packages/docs/src/pages/en/features/internationalization.md, packages/vuetify/src/locale/index.ts, packages/vuetify/src/locale/km.ts
This PR adds locales in Khmer language.
Vuetify had Thailand and Vietnam locales but did not have Khmer locales.
It's been unit tested.
=> feat(locale): add khmer translations

packages/docs/src/components/api/ApiTable.vue
=> docs: transform query to camelCase before search for api

packages/api-generator/src/locale/en/VTextarea.json
I added the description of "max-rows" prop for v-textarea component.
=> docs: max-rows description

packages/vuetify/src/components/VOverlay/VOverlay.tsx
fixes #18880
<details>
```vue
<template>
<v-app>
<v-main>
<v-btn id="my-button" ref="button" variant="text">
<v-tooltip
v-if="showTooltip"
activator="my-button"
:model-value="true"
location="bottom"
>
My VOverlay Will Think I am Still Active
</v-tooltip>
Button text
</v-btn>
<v-switch v-model="showTooltip" label="Toggle Tooltip" />
<br>
<br>
<v-btn text="Click me" @click="onClick" />
</v-main>
</v-app>
</template>
<script setup>
import { nextTick, ref } from 'vue'
const showTooltip = ref(false)
async function onClick () {
let i = 0
const interval = setInterval(async () => {
if (i++ > 200) {
clearInterval(interval)
return
}
showTooltip.value = !showTooltip.value
await nextTick()
showTooltip.value = !showTooltip.value
}, 50)
}
</script>
```
</details>
=> fix(VOverlay): memory leak involving bound listeners

packages/vuetify/src/locale/cs.ts
This pull request adds missing translations for Czech. 
```vue
<template>
<v-app>
<v-container>
<v-date-picker elevation="24"></v-date-picker>
<v-input
:messages="['Messages']"
clear-icon="clear-icon"
>
Default Slot
</v-input>
</v-container>
</v-app>
</template>
<script setup>
</script>
```
=> fix: Translations for czech language

packages/vuetify/src/locale/nl.ts
=> fix(locale): update Dutch locale

packages/vuetify/src/composables/calendar.ts, packages/vuetify/src/composables/date/date.ts, packages/vuetify/src/labs/VCalendar/VCalendar.tsx, packages/vuetify/src/labs/VCalendar/VCalendarDay.sass
=> fix(VCalendar): weekdays prop to affect week view mode

packages/vuetify/src/components/VList/VList.tsx
fixes #18223 
```vue
<template>
<div>
<v-container>
<v-row no-gutters>
<v-col v-for="col in 3" :key="col" cols="4">
<v-card>
<v-list :lines="false">
<v-list-item v-for="row in 16" :key="row">
<span> {{ `row: ${row}, col: ${col}` }} </span><br>
<span> {{ `row: ${row}, col: ${col}` }} </span><br>
<span> {{ `row: ${row}, col: ${col}` }} </span><br>
<span> {{ `row: ${row}, col: ${col}` }} </span><br>
<span> {{ `row: ${row}, col: ${col}` }} </span><br>
<v-checkbox-btn color="success" label="collected" />
<v-divider />
</v-list-item>
</v-list>
</v-card>
</v-col>
</v-row>
</v-container>
</div>
</template>
```
=> fix(VList): unexpected page scrolling when focusing

packages/vuetify/src/composables/goto.ts
=> improve typing

packages/docs/src/pages/en/components/radio-buttons.md
=> docs(radio-buttons.md): String instead of sting

packages/docs/src/examples/v-card/misc-grids.vue
=> docs: remove unnecesary commented markup

packages/docs/src/pages/en/components/data-tables/basics.md
=> docs(data-tables): fix broken link

packages/vuetify/src/locale/nl.ts
=> fix(locale): dutch local for badge should be capitalized

packages/vuetify/src/components/VCheckbox/VCheckbox.tsx
fixes #19127 
```vue
<template>
<v-sheet width="300" class="mx-auto">
<v-form ref="form">
<v-text-field
v-model="name"
:counter="10"
label="Name"
required
<v-select
:items="items"
:rules="[v => !!v || 'Item is required']"
label="Item"
required
></v-select>
<v-checkbox
v-model="checkbox"
:rules="[v => !!v || 'You must agree to continue!']"
label="Do you agree?"
required
></v-checkbox>
<div class="d-flex flex-column">
<v-btn
color="success"
class="mt-4"
block
@click="validate"
>
Validate
</v-btn>
<v-btn
color="error"
class="mt-4"
block
@click="reset"
>
Reset Form
</v-btn>
<v-btn
color="warning"
class="mt-4"
block
@click="resetValidation"
>
Reset Validation
</v-btn>
</div>
</v-form>
</v-sheet>
</template>
<script setup>
import { ref } from …
```
=> fix(VCheckbox): fix show correct color in error state

packages/docs/src/examples/v-select/slot-append-and-prepend-item.vue
=> docs(VSelect): fix append, prepend item example

packages/docs/src/pages/en/components/progress-linear.md
docs: fix 'background color' attribute name in VProgressLinear component
=> docs(VProgressLinear): fix bgColor prop reference

packages/vuetify/src/components/transitions/createTransition.ts
Adds support for VExpandTransition and VExpandXTransition to produce a TransitionGroup.
resolves #19210
```vue
<template>
<v-app>
<v-container>
<v-btn class="mb-2" color="primary" @click="randomize">Randomize</v-btn>
<v-row>
<v-col>
<h2>v-expand-transition</h2>
<v-expand-transition group>
<v-card v-for="item in items" :key="item" :title="item" />
</v-expand-transition>
</v-col>
<v-col>
<h2>v-expand-x-transition</h2>
<v-expand-x-transition group>
<v-card v-for="item in items" :key="'x-' + item" :title="item" class="d-inline-block" />
</v-expand-x-transition>
</v-col>
</v-row>
</v-container>
</v-app>
</template>
<script>
setup () {
const items = ref([])
function randomize () {
const newItems = []
const count = 3 + …
```
=> feat(VExpandTransition): add `group` prop

packages/vuetify/src/components/VOtpInput/VOtpInput.tsx
fixes #18931 
```vue
<template>
<v-app>
<v-container>
<v-text-field v-model="msg" />
</v-container>
<v-otp-input />
</v-app>
</template>
<script setup>
</script>
```
=> fix(VOtpInput): fix paste string to input number

packages/docs/src/components/examples/UsageExample.vue, packages/docs/src/examples/v-data-iterator/usage.vue, packages/docs/src/examples/v-data-table/usage.vue, packages/docs/src/examples/v-infinite-scroll/usage.vue
=> docs: fix UsageExample with extra script

packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.sass
fixes #19379 
```vue
<template>
<v-container>
<div class="text-subtitle-2 mt-4 mb-2">Accordion with multiple items</div>
<v-expansion-panels variant="accordion">
<v-expansion-panel
rounded="xl"
v-for="i in 3"
:key="i"
text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
title="Item"
></v-expansion-panel>
<div class="text-subtitle-2 mt-4 mb-2">Accordion with 1 item</div>
<v-expansion-panels variant="accordion">
<v-expansion-panel
rounded="xl"
v-for="i in 1"
:key="i"
text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna …
```
=> fix(VExpansionPanel): fix accordion variant border radius

packages/vuetify/src/components/VAvatar/VAvatar.sass, packages/vuetify/src/components/VAvatar/_variables.scss
fixes #19349 
```vue
<template>
<div>
<div>
<v-avatar color="blue-darken-2" start>
<v-icon icon="mdi-alarm" />
</v-avatar>
Username
<v-avatar color="blue-darken-2" end>
<v-icon icon="mdi-alarm" />
</v-avatar>
</div>
<div>
<v-avatar color="blue-darken-2">
<v-icon icon="mdi-alarm" />
</v-avatar>
Username
<v-avatar color="blue-darken-2">
<v-icon icon="mdi-alarm" />
</v-avatar>
</div>
<div>
<v-avatar color="blue-darken-2" end start>
<v-icon icon="mdi-alarm" />
</v-avatar>
Username
<v-avatar color="blue-darken-2" end start>
<v-icon icon="mdi-alarm" />
</v-avatar>
</div>
</div>
</template>
```
=> fix(VAvatar): add style for start, end props same as VIcon

packages/docs/src/components/app/search/SearchResults.vue
=> docs: fix incorrect search result url

packages/docs/src/pages/en/getting-started/frequently-asked-questions.md
Fixes typo in reference to [@vue/compat](https://www.npmjs.com/package/@vue/compat)
=> docs(frequently-asked-questions): fix typo

packages/api-generator/src/locale/en/VNavigationDrawer.json
Location prop description missing
=> docs(VNavigationDrawer): update location description

packages/vuetify/src/components/VDataTable/VDataTableFooter.tsx
I couldn't create reproduction link in playground.
Use this vuetify configuration on local machine
```
import 'vuetify/src/styles/main.sass'
import { createVuetify } from 'vuetify/src/framework'
import * as directives from 'vuetify/src/directives'
// import { createVueI18nAdapter } from 'vuetify/locale/adapters/vue-i18n'
import { createVueI18nAdapter } from 'vuetify/src/locale/adapters/vue-i18n'
import { createI18n, useI18n } from 'vue-i18n'
import { en, sv } from 'vuetify/src/locale'
import date from './vuetify/date'
import defaults from './vuetify/defaults'
import icons from './vuetify/icons'
// import locale from './vuetify/locale'
const messages = {
en: {
$vuetify: {
...en,
dataIterator: {
rowsPerPageText: "Items per page:",
// pageText: …
```
=> fix(VDataTableFooter):  dont apply i18n to numbers

packages/vuetify/src/locale/lt.ts
This pull request adds missing translations for Lithuanian language.
=> fix(locale): add missing Lithuanian translations

packages/vuetify/src/styles/generic/_transitions.scss, packages/vuetify/src/styles/settings/_variables.scss
closes #6470
<details>
```vue
<template>
<v-app>
<v-list :items="items" />
</div>
</v-app>
</template>
<script setup>
{ title: 'Item 1', children: [{ title: 'Item 1.1' }] },
{ title: 'Item 2' },
{ title: 'Item 3' },
]
</script>
```
</details>
=> feat(transitions): add root variable

packages/vuetify/src/components/VBottomNavigation/VBottomNavigation.tsx, packages/vuetify/src/components/VBtn/VBtn.tsx, packages/vuetify/src/components/VBtnGroup/VBtnGroup.tsx
fixes #17042
Copy "baseColor" logic from VListItem
```vue
<template>
<v-card class="mx-auto" max-width="300">
<v-list :items="items" color="green" base-color="red"></v-list>
</v-card>
<br>
<br>
<br>
<v-card class="mx-auto" max-width="300">
<v-btn-toggle color="green" :base-color="baseColor" v-model="toggle_exclusive">
<v-btn>
<v-icon>mdi-format-align-left</v-icon>
</v-btn>
<v-btn>
<v-icon>mdi-format-align-center</v-icon>
</v-btn>
<v-btn>
<v-icon>mdi-format-align-right</v-icon>
</v-btn>
<v-btn>
<v-icon>mdi-format-align-justify</v-icon>
</v-btn>
</v-card>
<v-btn
@click="() => baseColor = 'yellow'"
>
change basecolor to yellow
</v-btn>
</template>
<script>
data: () => ({
toggle_exclusive: 2,
baseColor: 'red',
items: [
{
title: 'Item #1',
value: 1,
},
{
title: …
```
=> feat(VBtnGroup/VBottomNavigation): Add baseColor prop

packages/vuetify/src/locale/sl.ts
There are some missing Slovene translations, this PR adds them. It also improves a few existing messages.
=> fix(locale): update Slovene locale

packages/docs/src/data/team.json
=> docs(team): add core team member

packages/vuetify/src/components/VCarousel/VCarouselItem.tsx
fixes #19630 
```vue
<template>
<v-app>
<v-container>
<v-carousel>
class="docks"
src="https://cdn.vuetifyjs.com/images/cards/docks.jpg"
cover
></v-carousel-item>
class="hotel"
src="https://cdn.vuetifyjs.com/images/cards/hotel.jpg"
cover
></v-carousel-item>
class="sunshine"
src="https://cdn.vuetifyjs.com/images/cards/sunshine.jpg"
cover
></v-carousel-item>
</v-carousel>
</v-container>
</v-app>
</template>
```
=> fix(VCarouselItem): fix class props

packages/vuetify/src/composables/__tests__/group.spec.ts, packages/vuetify/src/composables/group.ts
fixes #19655 
fixes #19213
```vue
<script setup>
const createItem = (title, hasValue = false) => ({
id: Math.floor(Math.random() * 1000),
title,
content: '',
value: hasValue ? Math.random().toString(16).slice(2) : undefined,
})
const items = ref([createItem('A'), createItem('B'), createItem('C')])
const onAddItem = () => {
items.value.push(createItem('D'))
}
const onDelete = (event, itemToBeDeleted) => {
event.stopPropagation()
const index = items.value.findIndex(item => item.id === itemToBeDeleted.id)
items.value.splice(index, 1)
}
</script>
<template>
<v-app>
<v-container>
<v-expansion-panels class="accordion">
<v-expansion-panel v-for="item in items" :key="item.id" :value="item.value">
<v-expansion-panel-title>
<template #actions="{ expanded }">
<span …
```
=> fix(group): update the value when delete an item

packages/vuetify/src/components/VDatePicker/VDatePicker.tsx
fixes #19421 
```vue
<template>
<v-container>
<v-btn @click="d = new Date(2010, 3, 3)">set new date</v-btn>
<v-date-picker v-model="d" elevation="1"></v-date-picker>
</v-row>
</v-container>
</template>
<script>
data() {
return {
d: new Date(2000, 1, 1),
}
},
}
</script>
```
=> fix(VDatePicker): change calendar when date is changed

packages/docs/src/pages/en/components/infinite-scroller.md
Change some wording on doc
```vue
```
=> docs: better wording infinite-scroller.md

packages/vuetify/src/components/VInput/VInput.tsx, packages/vuetify/src/components/VTextField/VTextField.tsx
fixes #19598 
```vue
<template>
<v-app>
<v-container>
<v-text-field
v-model="msg"
:error-messages="['Error text']"
theme="dark"
/>
</v-container>
</v-app>
</template>
<script setup>
</script>
```
=> fix(VInput): add theme class

packages/vuetify/src/labs/VCalendar/VCalendar.sass
fixes #18988 
```vue
<template>
<v-container>
<v-calendar v-model="msg" :events="events" view-mode="week"></v-calendar>
</v-container>
</v-app>
</template>
<script setup>
const events = [
{
title: 'First',
start: new Date('2024-01-22T02:00:00Z'),
end: new Date('2024-01-22T04:30:00Z'),
color: 'blue',
},
{
title: 'Second',
start: new Date('2024-01-23T05:30:00Z'),
end: new Date('2024-01-23T08:30:00Z'),
color: 'red',
},
{
title: 'Third',
start: new Date('2024-01-23T08:30:00Z'),
end: new Date('2024-01-23T09:30:00Z'),
color: 'green',
},
{
title: 'Fourth',
start: new Date('2024-01-24T02:01:00Z'),
end: new Date('2024-01-24T04:01:00Z'),
color: 'green',
},
]
const msg = ref([new Date('2024-01-23T14:30:00Z')])
</script>
```
=> fix(VCalendar): remove background for week view mode

packages/api-generator/src/locale/en/VDatePickerMonth.json, packages/api-generator/src/locale/en/VPicker.json, packages/api-generator/src/locale/en/calendar.json, packages/docs/src/data/nav.json, packages/docs/src/data/page-to-api.json, packages/docs/src/examples/v-date-input/misc-passenger.vue, packages/docs/src/examples/v-date-input/prop-model.vue, packages/docs/src/examples/v-date-input/prop-multiple-range.vue, packages/docs/src/examples/v-date-input/prop-multiple.vue, packages/docs/src/examples/v-date-input/prop-prepend-icon.vue, packages/docs/src/examples/v-date-input/usage.vue, packages/docs/src/pages/en/components/date-inputs.md, packages/docs/src/pages/en/labs/introduction.md, packages/vuetify/src/labs/VDateInput/VDateInput.tsx, packages/vuetify/src/labs/VDateInput/index.ts, packages/vuetify/src/labs/components.ts
<details>
```vue
<template>
<v-app>
<v-date-input label="Enter date" clearable />
<v-date-input clearable multiple />
<v-date-input multiple="range" clearable />
<v-text-field type="date" clearable />
<pre>{{ JSON.stringify(model, null, 2) }}</pre>
</div>
</v-app>
</template>
<script setup>
const model = ref(null)
</script>
```
</details>
=> feat(VDateInput): create new component

packages/vuetify/src/locale/ko.ts
fix ko translation change to a natural word
=> fix(locale): fix ko translation

packages/docs/src/data/team.json
@MatthewAry has joined the Vuetify team. Adding his information to the team page.
Matthew's profile image is not resolving right now since the profile images are pulled from the Vuetify github organization and @MatthewAry is not part of the org yet.
=> docs(team.json): add new team member

packages/vuetify/src/labs/VNumberInput/VNumberInput.tsx
- Prevent focusing input when increment/decrement controls are clicked
- Only display decimal keyboard on mobile
fixes #19788
```vue
<template>
<v-app>
<v-select
v-model="fieldVariant"
label="Variants"
:items="['underlined', 'outlined', 'filled', 'solo', 'solo-inverted', 'solo-filled', 'plain']"
/>
<h1>{{ numberInputValue }}</h1>
v-model="numberInputValue"
:variant="fieldVariant"
/>
v-model="numberInputValue"
:variant="fieldVariant"
/>
v-model="numberInputValue"
control-variant="stacked"
:variant="fieldVariant"
/>
v-model="numberInputValue"
control-variant="split"
:variant="fieldVariant"
/>
</div>
<h1>Reverse</h1>
v-model="numberInputValue"
reverse …
```
=> fix(VNumberInput): mobile friendly support

packages/docs/src/pages/en/components/tables.md
Data table have since been moved from labs so the text is no longer relevant
```vue
```
=> docs: update tables reference to labs

packages/vuetify/src/locale/fa.ts
The untranslated sections were translated into the best Persian equivalents and were substituted.
changed words:
* dismiss
* ok
* itemsSelected
* today
* clear 
* top 
* title
* item
```vue
```
=> fix(locale): update missing persian translations

packages/docs/src/plugins/icons.ts
=> docs(VColorPicker): fix display eye dropper icon

packages/vuetify/src/components/VMenu/VMenu.tsx
fixes #19920 prevent Enter default only for inputs in forms
```vue
<template>
<v-app>
<v-container>
<v-btn id="rootButton"> Open Menu 1 </v-btn>
<v-menu
v-model="menu1"
:close-on-content-click="false"
activator="#rootButton"
height="300px"
location="top"
width="260px"
persistent
>
<v-form @submit="submit">
<v-card>
<v-card-title> Menu 1 </v-card-title>
<v-card-item>
<v-row>
<v-text-field v-model="menu1Text" label="Some text" />
</v-col>
</v-row>
</v-card-item>
<v-spacer />
<v-btn variant="text"> Cancel </v-btn>
<v-btn color="primary" variant="text" type="submit"> Save </v-btn>
</v-card>
</v-form>
</v-menu>
</v-container>
</v-app>
</template>
import { Ref, ref } from 'vue'
const menu1: Ref<boolean> = ref(false) …
```
=> fix(VMenu): allow enter keypress to work in input element

packages/api-generator/src/locale/en/VImg.json, packages/docs/src/pages/en/components/images.md
=> docs(VImg): example for gradient props

packages/vuetify/src/components/VDataTable/VDataTableFooter.tsx
=> fix(VDataTableFooter): Wrong icon types

packages/vuetify/src/components/VDatePicker/VDatePickerControls.tsx
=> fix(VDatePickerControls): Wrong icon types

packages/docs/src/examples/v-data-table/slot-simple-checkbox.vue
replace v-checkbox with v-checkbox-btn in the example
=> docs(v-checkbox-btn): fix example simple checkbox

packages/docs/src/pages/en/getting-started/installation.md
Change `Vuefity` to `Vuetify` in Nuxt installation guide.
=> docs(installation): Fix minor spelling mistake

packages/docs/src/pages/en/getting-started/installation.md
Added Vitepress configuration steps for Vuetify
Added those steps in the `installation.md`, below the `Using CDN` part
```md
You can use Vuetify's components in your Vitepress static site.
First, add vuetify to your dependencies
::: tabs
```bash [yarn]
yarn create vuetify
```
```bash [npm]
npm create vuetify@latest
```
```bash [pnpm]
pnpm create vuetify
```
```bash [bun]
bun create vuetify
```
:::
Then, in your `.vitepress/theme/index.ts`
```ts
import DefaultTheme from "vitepress/theme";
import "vuetify/styles";
import * as components from "vuetify/components";
import * as directives from "vuetify/directives";
import { createVuetify } from "vuetify";
const vuetify = createVuetify({ components, directives });
...DefaultTheme,
enhanceApp({ app }) {
app.use(vuetify);
},
}; …
=> docs(installation.md): Add Vitepress configuration

packages/vuetify/src/components/VBtn/VBtn.sass
=> fix(VBtn): stacked button couldn't be of type block

packages/vuetify/src/labs/VDateInput/VDateInput.tsx
fixes #19985 
```vue
<template>
<v-app>
<v-container>
<v-date-input class="custom-date-input-class" variant="outlined" />
<v-date-input :style="{ background: 'pink' }" variant="outlined" />
</v-container>
</v-app>
</template>
<style scoped>
.custom-date-input-class {
background: green;
}
</style>
```
=> fix(VDateInput): inherit class

packages/api-generator/src/locale/en/VList.json
This PR adds descriptions to the expanded-icon and collapse-icon APIs.
=> docs(VList): add description for expanded-icon and collapse-icon APIs

packages/docs/src/pages/en/styles/elevation.md
Updated the elevation utility class table to use bold formatting for class names.
Updated the elevation utility class table to use bold formatting for class names. This change improves the readability of the documentation by making the class names stand out.
=> docs(elevation): use bold formatting for class names in elevation utility table

packages/vuetify/src/labs/VTreeview/VTreeview.tsx
https://github.com/userquin/vuetify-nuxt-module/issues/243
```vue
```
=> fix(VTreeview): don't expose open

packages/docs/src/pages/en/features/display-and-platform.md, packages/docs/src/pages/en/getting-started/upgrade-guide.md
=> docs(useDisplay): replace deprecated properties

packages/docs/src/pages/en/getting-started/installation.md
Corrected the steps for installing Vuetify with Vitepress
```
After initializing your Vitepress project, add Vuetify to your dependencies
::: tabs
```bash [pnpm]
pnpm i vuetify
```
```bash [yarn]
yarn add vuetify
```
```bash [npm]
npm i vuetify
```
```bash [bun]
bun add vuetify
```
```
=> docs(installation): Correct Vitepress installation steps

packages/docs/src/pages/en/getting-started/installation.md
This PR adds `vuetify-nuxt-module` to nuxt install section:
NA
=> docs: add vuetify-nuxt-module to nuxt install section

packages/vuetify/src/components/VDialog/VDialog.sass
resolves #20416 
```vue
<template>
<v-app>
<v-container>
<div class="pa-4 text-center">
<v-dialog v-model="dialog" fullscreen scrollable>
<template v-slot:activator="{ props: activatorProps }">
<v-btn
class="text-none font-weight-regular"
text="Edit Profile"
variant="tonal"
v-bind="activatorProps"
></v-btn>
</template>
<form>
<v-card title="User Profile">
<v-card-text>
<v-row dense>
<v-col cols="12" md="4" sm="6">
<v-text-field label="First name*" required></v-text-field>
</v-col>
<v-col cols="12" md="4" sm="6">
<v-text-field
hint="example of helper text only on focus"
label="Middle name"
</v-col>
<v-col cols="12" md="4" sm="6">
<v-text-field
hint="example of persistent helper text"
label="Last name*"
required
</v-col>
<v-col cols="12" …
```
=> fix(VDialog): add height to form in fullscreen dialog

packages/docs/src/components/home/Entry.vue
Fixes the Inconsistent Clipboard Behavior on Homepage reported at [https://github.com/vuetifyjs/vuetify/issues/20618](https://github.com/vuetifyjs/vuetify/issues/20618)
=> docs: ensure clipboard copies the correct command from snippet

packages/docs/src/data/team.json
=> docs(team.json): Added shinji's profile

packages/docs/src/examples/v-form/usage.vue
=> docs(VForm): correct typo in validation message in example

packages/docs/src/pages/en/getting-started/installation.md
From this comment: https://github.com/vuetifyjs/vuetify/pull/20326#discussion_r1718055046
NA
=> docs: update nuxt 3 manual setup

packages/docs/src/data/team.json
=> docs(team.json): Fixed github name

packages/docs/src/examples/v-list/misc-actions.vue
Followup to #20373
- add missing script for options API
- fix missing import in composition API script
=> docs(VList): fix opening last example in playground

packages/docs/src/examples/v-data-iterator/slot-header-and-footer.vue
Fixes mismatch between images and mice specs to avoid distracting users (was reported on Discord).
=> docs(VDataIterator): fix example content mismatch

packages/vuetify/src/composables/calendar.ts, packages/vuetify/src/labs/VCalendar/VCalendar.tsx, packages/vuetify/src/labs/VCalendar/VCalendarDay.sass, packages/vuetify/src/labs/VCalendar/VCalendarDay.tsx, packages/vuetify/src/labs/VCalendar/VCalendarEvent.tsx, packages/vuetify/src/labs/VCalendar/VCalendarInterval.tsx, packages/vuetify/src/labs/VCalendar/VCalendarMonthDay.tsx
Help implement #19568
```vue
<template>
<v-app>
<v-container>
<v-row>
<v-col>
<v-select
v-model="type"
:items="types"
class="ma-2"
label="View Mode"
dense
hide-details
></v-select>
</v-col>
<v-col>
<v-select
class="ma-2"
dense
hide-details
></v-select>
</v-col>
</v-row>
<v-row>
<v-col>
<div style="height: 600px">
<v-calendar
@click:event="clickedEvent"
ref="calendar"
:view-mode="type"
:weekdays="weekday"
@next="clickedNext"
@prev="clickedPrev"
@today="clickedToday"
>
</v-calendar>
</div>
</v-col>
</v-row>
</v-container>
</v-app>
</template>
<script>
import { useDate } from 'vuetify'
data: () => ({
type: "month",
types: ["month", "week", "day"], …
```
=> Fix(VCalendar): fix @prev, @next, @today event data, add @click:event, add @contextmenu:date

packages/vuetify/src/labs/VTreeview/VTreeviewItem.tsx, packages/vuetify/src/labs/VTreeview/__tests__/VTreeview.spec.browser.tsx
fixes #20665
```vue
<template>
<v-treeview
:items="items"
color="warning"
activatable
open-all
@update:activated="id => console.log('update:activated is called with '+id)"
></v-treeview>
</template>
<script>
data: () => ({
items: [
{
id: 1,
children: [
{ id: 2, title: 'Calendar : app' },
],
},
{
id: 5,
title: 'Documents :',
children: [
{
id: 6,
title: 'vuetify :',
children: [
{
id: 7,
title: 'src :',
children: [
{ id: 8, title: 'index : ts' },
{ id: 9, title: 'bootstrap : ts' },
],
},
],
},
{
id: 10,
title: 'material2 :',
children: [
{
id: 11,
title: 'src :',
children: [
{ id: 12, title: 'v-btn : ts' },
{ id: 13, title: 'v-card : ts' },
{ id: 14, title: 'v-window …
```
=> fix(VTreeview): activated emits twice on leafs

packages/vuetify/src/labs/VCalendar/VCalendar.tsx, packages/vuetify/src/labs/VCalendar/VCalendarDay.tsx, packages/vuetify/src/labs/VCalendar/VCalendarEvent.tsx, packages/vuetify/src/labs/VCalendar/VCalendarInterval.tsx, packages/vuetify/src/labs/VCalendar/VCalendarIntervalEvent.tsx, packages/vuetify/src/labs/VCalendar/VCalendarMonthDay.tsx
Fixes the `event:click` handler in interval and day view
```vue
<template>
<v-app>
<v-container>
<v-row>
<v-col>
<v-select
v-model="type"
:items="types"
class="ma-2"
label="View Mode"
dense
hide-details
></v-select>
</v-col>
<v-col>
<v-select
class="ma-2"
dense
hide-details
></v-select>
</v-col>
</v-row>
<v-row>
<v-col>
<div style="height: 600px">
<v-calendar
@click:date="clickedDate"
@click:day="clickedDay"
@click:interval="clickedInterval"
@click:interval-date="clickedIntervalDate"
@click:event="clickedEvent"
@contextmenu:date="contextMenu"
@contextmenu:event="contextMenu"
ref="calendar"
:view-mode="type"
:weekdays="weekday"
@next="clickedNext"
@prev="clickedPrev" …
```
=> Fix event:click and linter errors

packages/api-generator/src/locale/en/Select.json, packages/docs/src/pages/en/components/banners.md
fix https://github.com/vuetifyjs/vuetify/issues/20815
```vue
```
=> docs: fix typo "to to"

packages/api-generator/src/locale/en/VBadge.json
Set specific documentation for the VBadge component's API. Specifically the modelValue prop.
=> docs(VBadge): set badge specific description for the modelValue

packages/docs/src/examples/v-time-picker/prop-allowed-times.vue
Some functions were missing in the script for composition API
=> docs(VTimePicker): fix example with selection restrictions

packages/docs/src/components/examples/UsageExample.vue, packages/docs/src/pages/en/features/display-and-platform.md
=> docs(useDisplay): update overrides example

packages/vuetify/src/labs/VTimePicker/VTimePicker.tsx
```vue
<template>
<v-time-picker v-model="myTime" format="24hr" label="Pick A Time" />
{{ myTime }}
</template>
const myTime = ref(null)
</script>
```
=> fix(VTimePicker): emit when changing hour

packages/docs/src/pages/en/features/dates.md
=> docs(dates): fix usage example

packages/vuetify/src/components/VDataTable/VDataTable.sass
This PR aims to fix rtl alignment for data-table mobile view.
repro: https://play.vuetifyjs.com/#eNpdTzFuwzAM/AqhJUtc74YTIEO3/iDOwMgsKoCWCIk2CgT5e2WpbpMsong83h3PN5OibU8ib8tMpjO90iSMSsfBA/RLgyLlWxobvKLzFH+hAnKwyNRIDIsbKUJU/hsXwoiKjeKVCTqX9dNhMKUOBqZwdUzHvn2k/atn+EV+C5Mnz2lWpIbt24cjcptsdKKQSOd6S15MCiUCHOBcFW+bqceJOtidPqOz6OGdSb7Q626/EZKQdZQy5yN8h3FNAVjZuLHupV7WMNU+G5v73s/M5bn8APSZe0g=
This issue is reproducible by rendering a data-table mobile view in rtl.
```vue
<template>
<v-app>
<v-container>
<v-locale-provider rtl>
<v-data-table :items="items" mobile />
</v-locale-provider>
</v-container>
</v-app>
</template>
{
name: 'African Elephant',
species: 'Loxodonta africana',
},
]
</script>
```
=> fix(VDataTable): rtl mobile alignment

packages/docs/src/examples/v-fab/misc-speed-dial.vue, packages/docs/src/pages/en/components/floating-action-buttons.md, packages/vuetify/src/components/VFab/VFab.sass, packages/vuetify/src/components/VFab/VFab.tsx
Original goal was to restore VFab + VSpeedDial example ([original in v2 docs](https://v2.vuetifyjs.com/en/components/floating-action-buttons/#speed-dial)) after hearing colleague on Discord saying he does not know the path to migrate `v-speed-dial` with `fixed`. Upgrade guide states that `fixed` and `absolute` are combined in `position`, but this is not the case here.
There is also a minor problem that traditional usage when `v-speed-dial` wraps element with `<template #activator>`  makes the menu attach to `.v-fab` wrapper element which extends far beyond the visible button. So the only viable usage is to wrap `v-speed-dial` inside `v-fab`. We should consider explaining it in the Upgrade guide.
Notes:
- switching from `absolute` to `app` causes `Error: [Vuetify] Could not find injected …
=> fix(VFab): improve positioning & examples

packages/vuetify/src/locale/de.ts
I have translated the texts for the fileupload, because actual they are only copied from the english version
=> fix(locale): add missing german translations

packages/vuetify/src/locale/da.ts, packages/vuetify/src/locale/fi.ts
fixes #20913
fixes #20913 
```vue
```
=> fix(locale): add missing danish and finnish translations

packages/vuetify/src/labs/VTreeview/VTreeviewChildren.tsx
```vue
<template>
<v-treeview
v-model:opened="open"
:items="items"
item-value="title"
activatable
open-on-click
>
<template v-slot:prepend="{ item, isOpen }">
<v-icon
v-if="!item.file"
:icon="isOpen ? 'mdi-folder-open' : 'mdi-folder'"
></v-icon>
<v-icon v-else :icon="files[item.file]"></v-icon>
</template>
</v-treeview>
</template>
<script setup>
import { shallowRef } from 'vue'
const open = shallowRef(['public'])
const files = shallowRef({
html: 'mdi-language-html5',
js: 'mdi-nodejs',
json: 'mdi-code-json',
md: 'mdi-language-markdown',
pdf: 'mdi-file-pdf-box',
png: 'mdi-file-image',
txt: 'mdi-file-document-outline',
xls: 'mdi-file-excel',
})
{
title: '.git',
},
{
title: 'node_modules',
},
{
title: 'public',
children: [
{
title: 'static',
children: [
{ …
```
=> fix(VTreeview): root item indentation issue

packages/docs/src/pages/en/blog/building-a-basic-nuxt-application-with-vuetify.md, packages/docs/src/pages/en/blog/index.md
=> docs(building-a-basic-nuxt-application-with-vuetify): add new blog post

packages/vuetify/src/components/VList/VListItem.tsx
fixes https://github.com/vuetifyjs/vuetify/issues/21030
I just added the same conditions as VList etc.
https://github.com/vuetifyjs/vuetify/blob/83aed7b17d717142373e862cd10600530ef974ee/packages/vuetify/src/components/VList/VList.tsx#L221
```vue
<template>
<v-treeview :items="items" item-value="id">
<template v-slot:title="{ item }">
<v-text-field label="Name"></v-text-field>
</template>
</v-treeview>
</template>
<script>
data: () => ({
items: [
{
id: 1,
children: [
{ id: 2, title: 'Calendar : app' },
],
},
{
id: 5,
title: 'Documents :',
children: [
{
id: 6,
title: 'vuetify :',
children: [
{
id: 7,
title: 'src :',
children: [
{ id: 8, title: 'index : ts' },
{ id: 9, title: …
```
=> fix(VListItem): allow space key in input tag

packages/vuetify/src/labs/VFileUpload/VFileUpload.tsx
fixes #21029 
```vue
<template>
<v-app>
<v-container>
<v-file-upload v-model="file" clearable />
</v-container>
</v-app>
</template>
<script setup>
const file = ref()
</script>
```
=> fix(VFileUpload): remove value from input file correctly

packages/vuetify/src/components/VDatePicker/VDatePickerMonth.tsx
fixes https://github.com/vuetifyjs/vuetify/issues/21090
model.value was a Date[] so I converted it
https://play.vuetifyjs.com/#eNqNU9Fu2yAU/RXESxwthjhdNSlKp0zaJ0x7KX1wzU1DBRgB9lZF+fddMMqcrpMiWchwzrmHc4HHEw2+4+MAUR3e2GugW6qM630kJ9J5aCP8nDByJgffG7Io3IWwhdjK1kXwBd5L1NSq57J9ew3IEhZ+Z17X2xBJkZOH6/LVSVhC4hEMbEn+J0TCoR10/DEtLrR6OcbFKmHnPCanC7ns4gKfl8LSVU73zTmGthhtFzqvXCQB4uCIbu3Lg6AxCPo1yS7BhwDfsfYHkf+SPBwKLCjigqakpIRMO8OEpU6FW5kjASGUV48lJi6xNFSVoJv15nO9bvATdLnMaT5kbOaMJzTY8SkbJsFJBOM0CnKu3VhPh2LdEInBliqngYy16SVo7EDelKCEI33HZ1ps4JS3Nq3D29FbbGJuuCgAyi5HUBqxxZ9jjC5sOe+kRRm6qNEzC5FbZ/geadwPNioDtezN/o7ds+aOSxXifJ1BMPWz738F8FhF0NKO7JMO5AavwkSLL6y5nyzKWq3b55A8/qnN0XAEX3uwEjz4WzO9k13leof9P9v1A7rF+kqAphu25p+w/qzorbWmEg1r8MONpxkzKhHTBceXhQ8Lr8V5ZQet8/D0B5GncG0=
```vue
```
=> fix(VDatePickerMonth):feat: use adapter date in onMultipleClick

packages/api-generator/src/locale/en/VBanner.json
Add documentation for the VBanner component's API. Specifically the prepend slot.
=> docs(api): set VBanner specific description for the prepend slot

packages/api-generator/src/locale/en/VDateInput.json
I added a missing description where it was labeled as 'MISSING DESCRIPTION'.
https://vuetifyjs.com/ja/api/v-date-input/#props-hide-actions
```vue
```
=> docs(VDateInput): add hideActions description

packages/docs/src/data/team.json
=> docs(team.json): update core team

packages/api-generator/src/locale/en/border.json
Set correct border prop description
=> docs(api): set correct description for border prop

packages/vuetify/src/labs/VFileUpload/VFileUpload.tsx
fixes #21146 
```vue
<template>
<v-app>
<v-container>
<v-file-upload
class="myClass"
style="color: green !important"
/>
</v-container>
</v-app>
</template>
<style>
.myClass {
border: 2px solid red !important;
}
</style>
```
=> fix(VFileUpload): support class & style props

README.md, packages/docs/src/pages/en/blog/index.md, packages/docs/src/pages/en/blog/vuetify-herodevs-partnership.md, packages/docs/src/pages/en/getting-started/frequently-asked-questions.md, packages/docs/src/pages/en/introduction/enterprise-support.md
=> docs(vuetify-herodevs-partnership): add new blog post

packages/docs/src/examples/v-calendar/prop-type-day.vue, packages/docs/src/examples/v-calendar/prop-type-week.vue
On the Calendar docs, on both examples:
https://vuetifyjs.com/en/components/calendars/#type-week
https://vuetifyjs.com/en/components/calendars/#type-day
Are showing the "month" type, if you press the "Edit in Vuetify Playground" you can see the wrong prop, it shoud be
```diff
- type="week"
+ view-mode="week"
```
It solves #19427 (is marked closed, but the issue persist)
Day example:
```vue
<template>
<v-row>
<v-col>
<v-sheet>
<v-calendar
view-mode="day"
></v-calendar>
</v-sheet>
</v-col>
</v-row>
</template>
```
Week example
```vue
<template>
<v-row>
<v-sheet>
<v-select
class="ma-2"
hide-details
></v-select>
</v-sheet>
</v-col>
<v-sheet>
<v-calendar …
```
=> docs(VCalendar): correct viewMode in examples

packages/api-generator/src/locale/en/VConfirmEdit.json, packages/api-generator/src/locale/en/VTextField.json, packages/api-generator/src/locale/en/VTimePicker.json, packages/docs/src/examples/v-autocomplete/misc-new-tab.vue, packages/docs/src/examples/v-avatar/misc-advanced.vue, packages/docs/src/examples/v-sheet/misc-congratulations.vue, packages/docs/src/pages/en/components/infinite-scroller.md, packages/docs/src/pages/en/features/rules.md, packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.date.spec.ts, packages/vuetify/test/setup/browser-setup.ts
=> docs: fix typos

packages/docs/src/pages/en/styles/text-and-typography.md
Add documentation for text-pre-wrap class introduced with https://github.com/vuetifyjs/vuetify/pull/11772
=> docs: add text-pre-wrap class

packages/docs/src/pages/en/components/data-tables/data-and-display.md, packages/docs/src/pages/en/components/data-tables/server-side-tables.md, packages/docs/src/pages/en/components/data-tables/virtual-tables.md
- adds feature links on VDataTable sub-pages
=> docs: missing links to GitHub

packages/api-generator/src/locale/en/VOverlay-location-strategies.json
=> docs: more precise description of the offset for location strategy

packages/docs/src/components/app/search/SearchResults.vue
Fixes duplicate key warning when searching
=> docs: fix duplicate key warning

packages/vuetify/src/components/VDatePicker/VDatePickerYears.tsx
fixes #21513
```
<template>
<v-app>
<v-main>
<v-container class="h-screen">
<div class="h-50" />
<v-row>
<v-date-picker v-model="date" format="24hr" scrollable />
</v-row>
<div class="h-50" />
</v-container>
</v-main>
</v-app>
</template>
<script setup>
</script>
```
=> fix(VDatePicker): Fix autoscroll

packages/vuetify/src/components/VDatePicker/VDatePicker.tsx
- propagate external changes to `month` and `year` while the picker is open
fixes #21562
Known workaround
- `:key='...'` to trash and reinstantiate the component
```vue
<template>
<v-container>
<v-number-input v-model="month" label="month" />
<v-number-input v-model="year" label="year" />
<v-date-picker
v-model:month="month"
v-model:year="year"
elevation="4"
hide-header
/>
</v-container>
</template>
<script setup>
const month = ref(9)
const year = ref(2025)
</script>
```
=> fix(VDatePicker): reactive month and year

packages/vuetify/src/composables/__tests__/hotkey.spec.ts, packages/vuetify/src/composables/hotkey.ts
- just stuff I would recommend during code review if I would not be ~~lazy~~ busy with other stuff 😛
=> chore(hotkey): drop unnecessary refs

packages/vuetify/src/components/VDataTable/VDataTable.sass
- On tab focus missing sort icon, it should also show and indicate that the column is sortable
- Related to PR: https://github.com/vuetifyjs/vuetify/pull/20939/files
```vue
<template>
<v-data-table :headers="headers" :items="items" />
</template>
<script>
data: () => ({
headers: [
{ title: 'Dessert (100g serving)', align: 'start', key: 'name' },
{ title: 'Calories', key: 'calories', align: 'end', sortable: false },
{ title: 'Fat (g)', key: 'fat', align: 'end' },
{ title: 'Carbs (g)', key: 'carbs', align: 'end' },
{ title: 'Protein (g)', key: 'protein', align: 'end' },
{ title: 'Iron (%)', key: 'iron', align: 'end' },
],
items: [
{
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1',
},
{
calories: 375,
fat: 0.0,
carbs: …
```
=> fix(VDataTableColumn): on tab focus also show sortable icon

packages/docs/src/components/PageFeatures.vue, packages/docs/src/composables/markdown.ts, packages/vuetify/vitest.workspace.ts
remove the slash at the end of the router.path 
```vue
```
=> docs(copy-page-as-markdown): Fix copy function

packages/docs/src/pages/en/resources/search-engine.md
=> docs(Search Engines): instructions for Firefox

packages/api-generator/src/locale/en/VTextarea.json, packages/vuetify/src/components/VTextarea/VTextarea.tsx, packages/vuetify/src/components/VTextarea/__tests__/VTextarea.spec.browser.tsx
Closes https://github.com/vuetifyjs/vuetify/issues/21133
```vue
<template>
<v-textarea auto-grow @update:rows="console.log(`rows: ${$event}`)" />
</template>
```
=> feat(VTextarea): add update:rows event

packages/vuetify/src/labs/VIconBtn/VIconBtn.tsx
Added type to button to prevent form submission
fixes #21634 
```
<template>
<v-form>
<v-icon-btn icon="mdi-account" @click="onClick" />
<v-btn icon="mdi-account" @click="onClick" />
</v-form>
</template>
<script setup>
function onClick () {
console.log('Clicked')
}
</script>
```
=> fix(VIconBtn): Add Button Type 

packages/vuetify/src/labs/VStepperVertical/VStepperVertical.tsx
fixed #21358 
```vue
<template>
<v-app>
<v-container>
<v-row no-gutters>
<v-stepper-vertical
:items="['A', 'B', 'C']"
next-text="Custom Next"
prev-text="Custom Prev"
/>
</v-col>
</v-row>
<v-divider class="my-8" :thickness="8" />
<v-row no-gutters>
<v-stepper
:items="['A', 'B', 'C']"
next-text="Custom Next"
prev-text="Custom Prev"
/>
</v-col>
</v-row>
</v-container>
</v-app>
</template>
<script setup>
</script>
```
=> fix(VStepperVertical): fix next/prev-text props

packages/vuetify/src/labs/VColorInput/VColorInput.tsx
fixes #21655 
```vue
<template>
<v-container>
<v-color-input />
</v-container>
</template>
```
=> fix(VColorInput): ensure cancel action closes menu

packages/docs/src/examples/v-mask-input/credit-card-form.vue, packages/docs/src/examples/v-mask-input/ip-address.vue
=> docs(VMaskInput): update examples after changes to validation

packages/docs/src/examples/v-data-table/virtual.vue
```diff
- { ..., value: item => formatPrice(item.price) },
+ { ..., value: item => this.formatPrice(item.price) },
```
=> docs(VDataTableVirtual): fix method call

packages/api-generator/src/locale/en/nested.json
Document some more options of the `active-strategy` prop.
Removes documentation of the `classic` strategy, which does not exist for the `active-strategy`.
Mention which strategy will be used by default.
=> docs: Improve documentation of activeStrategy prop

packages/docs/src/examples/v-form/prop-disabled.vue
=> docs(VForm): improved example for `disabled`

packages/docs/src/examples/v-combobox/misc-advanced.vue
=> docs(VCombobox): pick and preserve color from options

packages/vuetify/src/labs/VStepperVertical/VStepperVerticalItem.sass
fixes #21792
<details>
<summary>Playground (use narrow viewport)</summary>
```vue
<template>
<v-stepper-vertical>
<template #default="{ step }">
<v-stepper-vertical-item
:complete="step > 1"
subtitle="Personal details"
title="Step one"
value="1"
>
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi,
ratione debitis quis est labore voluptatibus! Eaque cupiditate minima,
at placeat totam, magni doloremque veniam neque porro libero rerum unde
voluptatem!
<template #next="{ next }">
<v-btn color="primary" @click="next" />
</template>
<template #prev />
</v-stepper-vertical-item>
<v-stepper-vertical-item
:complete="step > 2"
subtitle="Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi,
ratione debitis quis est labore voluptatibus! Eaque cupiditate minima,
at placeat …
```
=> fix(VStepperVertical): correct avatar alignment

packages/docs/src/examples/v-carousel/prop-custom-transition.vue, packages/docs/src/pages/en/components/carousels.md
- includes temporary disclaimer (we will figure out a new custom transition when 3.10.0 lands `crossfade` prop)
- [preview](https://play.vuetifyjs.com/#eNq1Vm2P4jYQ/itTpApWwgl76PqSwlb9Af1SnfplWZ1M4hDvOnFqOwGK+O8d2wl5gb29693xAcfjeWbG43nGfjxNtIrDumKGp8fgWU+iCc9LqQycIFaMGva3X4MzpErmMG10p5tiU7CDU41loQ00C7AeAmenTQFgMpazCNw3QMJSWgnzwQunCVUv07lfCkM7nnF2vtsUk7mL74+yDNA8BrcyLC8FWn+waqua0LJ0n26iM8YwHEG1Xm8m5YH8BOWRvIOtVAlTZLuZYKxCKlzUlUppzDaTBo34hNcXbEJSwQ6wO5Al2C+yV7TsKd9Wp4LvChKzwjAFO0qWAwRidEmLCyhXTuFPmbBoFdqloXJN4oyXZKdkVUJNctQTFobjyO5FGQw7GNThOd0xjdutqahYX5ByYYMTdMvEwyr0sE8bs0PPVDN921Ar9Dvopy7E3H2PVH5QtNDccFl8SULjSin004Ffy+5QiEXt85PShMFsW2FCCC/uNpOxXps5q0hMz81Y0ed0LHUpHgrfOLlXAo2V1NpHG1fayPwTsV50v3mUn1kW/ZmFOG53VMeeYygvmOoAKKRoUvfDiNoKOcH0sqWL3jSCq8OH9Xrd053CuZ+BjCMcy4bnHHOg24X+LrowCOrk/a3XJHXN …
=> docs(VCarousel): example for custom transitions

packages/api-generator/src/locale/en/VWindow.json, packages/docs/src/data/new-in.json, packages/docs/src/examples/v-carousel/prop-custom-transition.vue, packages/docs/src/pages/en/components/carousels.md, packages/vuetify/src/components/VWindow/VWindow.sass, packages/vuetify/src/components/VWindow/VWindow.tsx, packages/vuetify/src/components/VWindow/_variables.scss
- new `crossfade` prop
- new `transition-duration` prop
```vue
<template>
<v-container max-width="800">
<v-sheet class="px-6 py-2 border-b" color="surface">
<div class="d-flex gx-3 flex-wrap">
<div class="d-flex align-center ga-3">
<v-chip-group v-model="mode">
<v-chip text="images" value="images" filter label />
<v-chip text="text" value="text" filter label />
</div>
</div>
</v-sheet>
<div class="mb-1 mt-6"><v-code class="bg-purple-darken-2">transition-duration="900" crossfade</v-code></div>
<v-carousel height="300" :key="`a-${mode}`" transition-duration="900" crossfade>
<v-carousel-item v-for="({ src, text }, i) in items" :key="i" :src="src" cover>
<template #default>
<div class="d-flex align-center justify-center h-100">
<div
class="text-h1 …
```
=> feat(VWindow, VCarousel): add crossfade transition

packages/docs/components.d.ts, packages/docs/src/components/promoted/BitterBrains.vue, packages/docs/src/components/promoted/Entry.vue, packages/docs/src/components/promoted/Script.vue
Adds BitterBrains  custom banner script to docs.
=> docs: add bitterbrains ads

packages/vuetify/src/components/VList/VListItem.sass
This addresses the request for High Contrast Support https://github.com/vuetifyjs/vuetify/issues/21515 for the VList component by applying the expected system colors for the active item within the VList component when forced-color mode (For example, High Contrast Mode in Windows) is enabled.
_VList Component when not in forced-colors mode (High Contrast Mode in Windows):_
_VList Component when in forced-colors mode (High Contrast Mode in Windows) **before the changes in this pull request**:_
_VList Component when in forced-colors mode (High Contrast Mode in Windows) **after the changes in this pull request**:_
_Focus state is also improved as part of this pull request:_
```vue
<template>
<v-app>
<v-container>
<v-row dense> …
```
=> feat(VList): High Contrast Support (Forced-colors-mode)

packages/vuetify/src/composables/rounded.ts
Improve predictability and correctness of rounded classes when using blueprints.md3.
Resolves #21844
=> fix(rounded): reorder conditional checks for rounded classes

packages/docs/src/pages/en/getting-started/installation.md
Add installation instructions for Roboto font using in Vuetify
Resolves #19140
=> docs: add installation instructions for Roboto font

packages/docs/src/pages/en/getting-started/unit-testing.md
Add guidelines for testing Vuetify components and recommended test runners
Resolves #21548
=> docs: update testing documentation

packages/vuetify/src/directives/touch/index.ts
fix https://github.com/vuetifyjs/vuetify/issues/21768
The uid of the root component is 0, so the !uid check was incorrect.
https://play.vuetifyjs.com/#eNqNkc1ugzAQhF9l4wuNxE/aqKpKSKSq9556a3ogsIAVY1vG0FRR3r22gVCljZQLeNfj2dV8H0fSqCx6kTLsWiQxSTTWkqUaN1sOkHRBKqU7uiITXKeUoxpapjkLApjNZvAmNHwJtae8hC7Qos0q1w+CSZvTbjwDNPqb4XpLdmm2L5VoeW7smVAxlAqRr6BCWlY6hofFQh62ZHo52Ju3R2BYGMndHNYbMNs1gmHIRHnn2QtQQmhv7oPqnf6RuZtBB6dpSjRtnYlanuskukzBdvqQkuhXeKZsMkWldiJaS6E0vFqrQokavDCyhU3dW1k1AB6cJscibZmGYz/QThccuW7isQXOx++Lk/2ZTxKdxxHfQR39/1K1zN4r2pxBmePIrg9koDYRu05rx1q8Aut2UFlFWX4LqUE4otokkVnxMnty8skyfAzvn0wUy/A5XBC/SFmDF8H0zc8fNXTyqA==
=> fix(v-touch): Fixed to work with root components

packages/vuetify/src/components/VList/VList.tsx
=> fix(VTreeview): match type of update:opened with VList

packages/docs/src/examples/v-data-table/virtual-custom.vue, packages/docs/src/pages/en/components/data-tables/virtual-tables.md
Add example using itemRef slot with itemRef slot prop in virtual data table.
=> docs(VDataTableVirtual): add example with itemRef slot prop

packages/docs/src/examples/transitions/misc-expand-x-padding.vue, packages/docs/src/pages/en/styles/transitions.md
Add guidance on using padding with expand transitions
=> docs(transitions): add guidance on using padding with expand transitions

packages/vuetify/src/components/VBadge/VBadge.sass
This addresses the request for High Contrast Support https://github.com/vuetifyjs/vuetify/issues/21515 for the VBadge component when in forced-colors mode (e.g. Windows Accessibility > Contrast themes)
**Before:**
**After:**
```vue
<template>
<div class="d-flex ga-12 justify-center mb-8">
<v-badge color="warning" location="top right" dot>
<v-icon icon="mdi-bell" />
</v-badge>
<v-badge content="1" location="top right">
<v-icon icon="mdi-cog" />
</v-badge>
<v-badge color="success" content="25" location="top right">
<v-icon icon="mdi-calendar" />
</v-badge>
<v-badge color="primary" content="99+" location="top right">
<v-icon icon="mdi-cart" />
</v-badge>
</div>
<div class="d-flex ga-12 justify-center mb-8">
<v-badge color="warning" location="top right" bordered dot>
<v-icon icon="mdi-bell" …
```
=> fix(VBadge): render background highlight in forced-colors mode

packages/api-generator/src/locale/en/DataTable-sort.json, packages/api-generator/src/locale/en/VDataIterator.json, packages/docs/src/data/new-in.json, packages/vuetify/src/components/VDataIterator/VDataIterator.tsx, packages/vuetify/src/components/VDataTable/VDataTable.tsx, packages/vuetify/src/components/VDataTable/VDataTableServer.tsx, packages/vuetify/src/components/VDataTable/VDataTableVirtual.tsx, packages/vuetify/src/components/VDataTable/composables/sort.ts
resolves #11117
closes #20615
```vue
<template>
<v-data-table
:sort-by="[{ key: 'calories', order: 'asc' }, { key: 'fat', order: 'desc' }]"
initial-sort-order="desc"
multi-sort
/>
</template>
<script setup>
{ title: 'Dessert (100g serving)', align: 'start', sortable: false, key: 'name' },
{ title: 'Iron (%)', key: 'iron' },
]
const desserts = [
{ name: 'Frozen Yogurt', calories: 200, fat: 6.0, carbs: 24, protein: 4.0, iron: 1 },
{ name: 'Ice cream sandwich', calories: 200, fat: 9.0, carbs: 37, protein: 4.3, iron: 1 },
{ name: 'Eclair', calories: 300, fat: 16.0, carbs: 23, protein: …
```
=> feat(VDataTable): add `initial-sort-order` prop

packages/vuetify/src/composables/icons.tsx, packages/vuetify/src/framework.ts, packages/vuetify/src/icons.ts
=> fix(build): avoid circular dependency in icons setup
