vuetifyjs/vuetify

packages/vuetify/src/components/VTreeview/VTreeview.ts
When using VTreeView and the [item-children](https://vuetifyjs.com/en/api/v-treeview/#props-item-children) is null or undefined, then a `children.map` in `VTreeview.ts` will cause an error. 
Adding a simple null/undefined check and then setting it to `[]` fixes this problem. 
[[Bug Report] VTreeNode: Null or Undefined children causing trouble with event bubbling #9376 (comment)](https://github.com/vuetifyjs/vuetify/issues/9376#issuecomment-572765655) 
Tested in my current project by adding the same code and this fixes the problem. Children which are undefined are not expandable. 
<details>
```vue
<template>
<v-treeview :items="items" />
</template>
<script>
data: () => ({
items: [
{
id: 'a',
name: 'This one is  active with no exception',
},
{
id: 'b',
name: 'So it this …
```
=> fix(VTreeView): Null check when building tree from children

package.json, packages/vuetify/package.json, packages/vuetify/src/components/VBtn/VBtn.sass, packages/vuetify/src/styles/tools/_states.sass, yarn.lock
Resolves #3923
Resolves #8572
Resolves #9808
Only works in browsers that support [`:focus-visible`](https://caniuse.com/css-focus-visible), webkit just shows the normal focus overlay (including on click :angry:). It is possible to polyfill this but idk how that behaves with [`@supports`](https://caniuse.com/mdn-css_at-rules_supports_selector)
- https://www.npmjs.com/package/focus-visible
- https://www.npmjs.com/package/postcss-focus-visible
<details>
```vue
<template>
<v-app>
<v-container>
<v-btn variant="text" color="primary">Button</v-btn>
<v-btn variant="contained-text" color="primary">Button</v-btn>
<div class="my-5" />
<v-btn color="primary">Button</v-btn>
</v-container>
</v-app>
</template>
```
</details>
https://user-images.githubusercontent.com/16421948/129481461-b1d82ba7-ac8d-4ec8 …
=> fix(VBtn): only show focus if activated by keyboard

packages/docs/build/generate-routes.js, packages/docs/build/prerender.js
resolves #12854
#12854
visually
<details>
```vue
```
</details>
=> docs(prerender): do not prerender wireframes

packages/vuetify/src/composables/__tests__/icons.spec.ts, packages/vuetify/src/composables/icons.tsx
Implements the [suggestion](https://github.com/vuetifyjs/vuetify/issues/13975#issuecomment-893723888) by @nekosaur in #13975 – match the start of an icon string with the registered icon sets, instead of assuming that any string containing a colon includes an icon set name.
Fixes #13975. (_hopefully_ – not yet tested [see below])
See #13975. It allows icons to be URLs.
There is no test file for the icon composable. I tried to add one, but I got a bit stuck:
```ts
// Composables
import { useIcon } from '../icons'
describe('icons.ts', () => {
it.each([
// Default icon set.
["success", {component: ???, icon: "success"}],
["https://example.com/icon.svg", {component: ???, icon: "https://example.com/icon.svg"}],
// MDI icon set.
["mdi:success", {component: ???, icon: "success"}],
// Custom icon …
```
=> fix(VIcon): allow colons to be used in icon names

packages/docs/src/pages/en/features/display-and-platform.md, packages/docs/src/pages/en/features/icon-fonts.md, packages/docs/src/pages/en/features/internationalization.md, packages/docs/src/pages/en/getting-started/installation.md, packages/vuetify/build/rollup.config.js, packages/vuetify/build/rollup.types.config.js, packages/vuetify/package.json, packages/vuetify/src/composables/index.ts, packages/vuetify/src/entry-bundler.ts, packages/vuetify/src/entry.ts
```js
import 'vuetify/styles'
import { createApp } from 'vue'
import { createVuetify } from 'vuetify' // no more components in here
// import { createVuetify } from 'vuetify/framework' - also works
import { VApp } from 'vuetify/components'
import { Ripple } from 'vuetify/directives'
import { useDisplay } from 'vuetify/composables'
import { aliases, mdi } from 'vuetify/iconsets/mdi'
import { en } from 'vuetify/locale'
```
=> feat: define package exports

packages/vuetify/src/components/VIcon/VIcon.sass
The CSS generated to alter the `dense` property should look like this:
```css
.v-icon--dense .v-icon__svg { ... }
```
It currently looks like this:
```css
.v-icon--dense .v-icon--dense__svg { ... }
```
which fails to properly target the SVG (`svg.v-icon__svg`)
Currenly, the `dense` property of `v-icon` has no effect on the height of the element
visually
<details>
```vue
```
</details>
=> fix(VIcon): properly apply dense height to svg

packages/vuetify/src/components/VBtn/VBtn.sass
Using `width: 100%` to grow the buttons in a bottom navigation makes them too wide:
Since the surrounding container is a `flex` container, `flex: 1` should be used:
=> fix(VBtn): use flex: 1 instead of 100% width in bottom nav

packages/docs/src/pages/en/components/lists.md
`List` documentation page is calling `v-list-group` as `v-item-group` (which does not exist).
=> docs: fix component's name

packages/vuetify/src/components/VNoSsr/VNoSsr.tsx, packages/vuetify/src/composables/hydration.ts
Hydration composable checks if app/component is being generated/rendered on the server and waits to execute until on the client, else it executes right away.
This composable supports the VNoSsr component and other components that need to only execute functions on the client.
Playground and dev:ssr
<details>
```vue
<template>
<div>Server-side; This should display</div>
<v-no-ssr> This is only supposed to be on the client</v-no-ssr>
</template>
```
</details>
=> feat(hydration): create new composable

packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts, packages/vuetify/src/components/VCombobox/VCombobox.ts, packages/vuetify/src/components/VCombobox/__tests__/VCombobox-multiple.spec.ts, packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.ts, packages/vuetify/src/components/VSelect/VSelect.ts
fixes #14194 #6607
This pull request fixes #14194 as well as keeps fixing #6607
Test cases are added to cover both #14194 & #6607
resolves #14194
visually | unit 
<details>
```vue
<template>
<v-container>
<v-combobox
clearable
dense
filled
hide-selected
multiple
small-chips
:items="['a', 'aa', 'aaa', 'bar']"
@update:list-index="console.log($event)"
></v-combobox>
<v-combobox :items="todos" :auto-select-first="true"></v-combobox>
</v-container>
</template>
<script>
data: () => ({
console,
todos: [
{ text: "Learn JavaScript", done: false },
{ text: "Learn Vue", done: false },
{ text: "Play around in JSFiddle", done: true },
{ text: "Build something awesome", done: true }
]
}),
mounted () {
}
};
</script>
```
</details>
=> fix(VCombobox): keep highlighted item on filteredItems change

packages/vuetify/src/components/VList/VListItem.sass, packages/vuetify/src/components/VList/VListItem.ts, packages/vuetify/src/components/VList/__tests__/VListItem.spec.ts, packages/vuetify/src/mixins/routable/__tests__/routable.spec.ts, packages/vuetify/src/mixins/routable/index.ts
Restores #13719
Fixes #14186
Fixes #9285
The isActive variable was not changing when using a router element, with this PR this makes sure that it reflects the current state of the router link, taking into account if it's exact
With the playground, the doc and new test units
<details>
```vue<template>
<template>
<v-container>
<v-list-group group="/page2">
<template #activator>
<v-list-item-title>Pages</v-list-item-title>
</template>
<v-list>
<v-list-item
v-for="i in 2"
:key="i"
:to="{path: '/page' + i}"
>
<v-list-item-title>Page {{ i }}</v-list-item-title>
</v-list-item>
</v-list>
</v-list-group>
<v-list-group group="/page1">
<template #activator>
<v-list-item-title>Pages</v-list-item-title>
</template>
<v-list>
<v-list-item …
```
=> fix(VListItem): allow default color to change when inactive

packages/vuetify/src/components/VCalendar/VCalendarDaily.ts, packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.sass, packages/vuetify/src/components/VCalendar/mixins/mouse.ts
According to [MDN doc (TouchEvent)](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/TouchEvent)
`TouchEvent` constructor is not available on Safari and might not be available in Firefox.
Therefore, `if (e instanceof TouchEvent) {...}` does not work on Safari & Firefox
1. ✅fixes #14276 
2. ✅keeps the fix for #12366
3. ⚠️revert fix for #13174 and make a separate proper dedicated pull request to tackle it in future because previous changes of fixing it breaks #14243
4. ⚠️chagnes in point 3 restores [drag & drop example](https://vuetifyjs.com/en/components/calendars/#drag-and-drop) back to its previous version . #14243 is caused by a Firefix behaviour regarding `overflow: hidden` which has been officially  confirmed by Firefox as an issue …
=> fix(VCalendar): implicitly narrow TouchEvent

packages/vuetify/src/styles/settings/_variables.scss
As discussed on Discord:
> There's an issue with:
>
> ```scss
> $container-max-widths: map-deep-merge(
>   (
>     'md': map.get($grid-breakpoints, 'md') * 0.9375,
>     'lg': map.get($grid-breakpoints, 'lg') * 0.9375,
>     'xl': map.get($grid-breakpoints, 'xl') * 0.9375,
>     'xxl': map.get($grid-breakpoints, 'xxl') * 0.9375,
>   ),
>   $container-max-widths
> );
> ```
>
> ... if you want to add, for example, an `sm` breakpoint. Deep merge will append new items, so `sm` ends up at the end of the map, and the media queries are then out of order.
This is Kael's suggested solution.
It allows developers to set container max widths for `xs` and `sm` breakpoints, and have them applied in the correct order.
visually
<details>
```vue
```
</details>
=> fix(sass): ordering of container-max-widths media queries

packages/vuetify/src/components/VTabs/VTab.ts
Fixes problem with active item in VTabs component could not be set to inactive when [optional](https://vuetifyjs.com/en/api/v-tabs/#props-optional) property was set.
resolves #14397 
This PR solves a problem with [optional](https://vuetifyjs.com/en/api/v-tabs/#props-optional) property not working as declared in docs.
I visualy tested on local project by building package locally.
<details>
```vue
<template>
<div id="app">
<v-app dark>
<v-tabs v-model="selectedTab" optional>
<v-tab v-for="tabData in allTabData" :key="tabData.id">
{{ tabData.name }}
</v-tab>
</v-tabs>
<v-tabs-items v-model="selectedTab">
<v-tab-item v-for="tabData in allTabData" :key="tabData.id">
{{ tabData.text }}
</v-tab-item>
Selected tab is {{ selectedTab }}
</v-app>
</div>
</template>
<script>
new Vue({ …
```
=> fix(VTabs): allow set VTab inactive if optional property is set

packages/api-generator/src/locale/en/v-checkbox.json, packages/api-generator/src/locale/en/v-radio.json, packages/api-generator/src/locale/en/v-simple-checkbox.json, packages/vuetify/src/components/VCheckbox/VCheckbox.tsx, packages/vuetify/src/components/VFileInput/VFileInput.tsx, packages/vuetify/src/components/VInput/VInput.tsx, packages/vuetify/src/components/VRadio/VRadio.tsx, packages/vuetify/src/components/VRadioGroup/VRadioGroup.tsx, packages/vuetify/src/components/VSelectionControl/VSelectionControl.tsx, packages/vuetify/src/components/VSelectionControl/__tests__/VSelectionControl.spec.tsx, packages/vuetify/src/components/VSelectionControlGroup/VSelectionControlGroup.tsx, packages/vuetify/src/components/VSwitch/VSwitch.tsx, packages/vuetify/src/components/VTextField/VTextField.tsx, packages/vuetify/src/components/VTextarea/VTextarea.tsx, packages/vuetify/src/composables/validation.ts, packages/vuetify/src/util/helpers.ts
BREAKING CHANGE: renamed `onIcon`/`offIcon` to `trueIcon`/`falseIcon`
Vue 3 interprets props starting with `/on[A-Z]/` as events, so mergeProps
will combine them into an array instead of overwriting with the latest
value.
Related: 776881372767d10aeacf6408ac10362fa9a79e35
=> fix: filter both VInput and VSelectionControl props

packages/vuetify/src/components/VItemGroup/VItemGroup.ts, packages/vuetify/src/components/VItemGroup/__tests__/VItemGroup.spec.ts, packages/vuetify/src/components/VTabs/VTab.ts
fixes #9073
I couldn't find any justification for this in #5009. There is a chance this change could break anything relying on that behaviour but it seems pretty obtuse. 
<details>
```vue
<template>
<v-app>
<v-container>
<v-radio-group v-model="selected">
<v-radio
label="Yes"
:value="true"
></v-radio>
<v-radio
label="No"
:value="false"
></v-radio>
<v-radio
label="N/A"
:value="null"
></v-radio>
<v-tabs>
<v-tab>Tab</v-tab>
<v-tab>Tab</v-tab>
<v-tab>Tab</v-tab>
</v-tabs>
<pre>{{ String(selected) }}</pre>
</v-container>
</v-app>
</template>
<script>
data: () => ({
selected: undefined,
}),
}
</script>
```
</details>
=> fix(VItemGroup): allow null values

packages/vuetify/src/components/VItemGroup/VItemGroup.ts, packages/vuetify/src/components/VItemGroup/__tests__/VItemGroup.spec.ts, packages/vuetify/src/components/VRadioGroup/VRadioGroup.ts
Fixes #10571
Radio groups with object as values where not properly marked as active because the objects (having different reference) are compared with `===` instead of deep equality
unit test and playground
<details>
```vue
<template>
<v-container>
<v-radio-group v-model="radio">
<v-radio
label="test 1"
:value="{test: 1}"
></v-radio>
<v-radio
label="test 2"
:value="{test: 2}"
></v-radio>
<v-radio
label="test 3"
:value="3"
></v-radio>
</v-container>
</template>
<script>
data: () => ({
radio: null,
}),
}
</script>
```
</details>
=> fix(VItemGroup): allow object values and custom comparator

packages/vuetify/src/components/VStepper/VStepper.sass
fixes #12584
**changes on `v-stepper__label`**
- added `flex-grow: 1`, `display: block` to make it full the whole width
- removed flex as there is no need for it
**changes on `v-stepper__label small`**
- added `display: block` to `small` to make it appear in separate line
- changed `align-self: center` into `text-align: center` when `--alt-labels` is defined
I've checked all examples in VStepper document page. all of them works as expected
<details>
```vue
<template>
<v-app>
<v-container>
<v-card width="600">
<v-stepper
v-model="e6"
vertical
>
<v-stepper-step
step="1"
>
<v-textarea                   
single-line
rows="1"
no-resize
hide-details
dense
outlined
label="why isn't this as wide as the stepper step?"
></v-textarea> 
<v-stepper-content step="1"> …
```
=> fix(VStepper): expand stepper label to full width

packages/vuetify/src/components/VStepper/VStepperStep.ts, packages/vuetify/src/components/VStepper/__tests__/__snapshots__/VStepperStep.spec.ts.snap
Added tab navigation for editable stepper steps.
Fixes #14022 
Visually 
<details>
```vue
<template>
<v-stepper>
<v-stepper-step
editable
step="1"
>
Select campaign settings
<v-stepper-step
editable
step="2"
>
Create an ad group
<v-stepper-step
step="3"
editable
>
Create an ad
</v-stepper-header>
</v-stepper>
</template>
```
</details>
=> fix(VStepperStep): editable step tab navigation

packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.sass, packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.tsx, packages/vuetify/src/components/VNavigationDrawer/__tests__/VNavigationDrawer.spec.tsx, packages/vuetify/src/components/VNavigationDrawer/touch.ts, packages/vuetify/src/composables/layout.ts, packages/vuetify/src/composables/touch.ts, packages/vuetify/src/util/helpers.ts
closes #3262
<details>
```vue
<template>
<v-app>
<v-container>
<v-navigation-drawer app>
Drawer
<v-main>
Content
</v-main>
</v-container>
</v-app>
</template>
```
</details>
=> feat(VNavigationDrawer): add smooth touch dragging

packages/vuetify/src/components/VField/VField.tsx
Handling the case when label is missing or it has falsy value
I am not aware of any open issue that this PR resolves. It resolves an issue that we discussed on the discord chat. 
The layout is broken when using outlined variant. The notch is present and the border is interrupted with white space.
```vue
<template>
<v-app>
<v-container>
<v-text-field
v-model="something"
label="Something"
/>
<v-text-field
v-model="something"
label=""
/>
</v-container>
</v-app>
</template>
<script>
setup() {
return {
something: "",
};
},
};
</script>
```
</details>
=> fix(VField): don't show gap when missing label

packages/vuetify/src/components/VSelect/VSelect.ts
The [https://github.com/vuetifyjs/vuetify/commit/4a855cd8d940c35fc01c5a8521ff539c7491eda1](commit) made some of our autocompletes crash on null references. This change removes any null items from the array before the check introduced by the above commit. Keeping the nulls seemed like a bad idea. 
Without the fix we are not able to upgrade from vuetify 2.3.15
This resolves #14421 
visually
<details>
```vue
<template>
<v-container>
<div id="app">
<v-card
class="overflow-hidden"
color="purple lighten-1"
dark
>
<v-toolbar
flat
color="purple"
>
<v-icon>mdi-account</v-icon>
<v-toolbar-title class="font-weight-light">
User Profile
</v-toolbar-title>
<v-btn
color="purple darken-3"
fab
small
@click="isEditing = !isEditing"
>
<v-icon v-if="isEditing"> …
```
=> fix(VSelect): Do not keep null items when filtering duplicates

packages/vuetify/src/components/VDefaultsProvider/VDefaultsProvider.tsx, packages/vuetify/src/composables/defaults.ts
Default providers can now scope their settings to avoid inheriting from their parents or globally.
* the **scoped** prop only provides its specifically defined props. Nothing from parents or root is inherited.
* some components modify the styling of slotted components. this avoids potentially unintended chained defaults; e.g. `v-bottom-navigation` targets `v-btn` with specific defaults but does not want to use parent / global properties
* the **reset** prop traverses its parents based upon the provided number
* for use with components like `v-menu` that may not be interested in passing scoped defaults from a parent such as `v-bottom-navigation`
* the **root** property does not merge specifically defined or parent defaults, only global defaults
Many components within Material have specific …
=> feat(defaults): add support to scope defaults

packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts
Updated `v-navigation-drawer` to use its real width for application layout calculations. As a consequence to this change, a bug with **expand-on-hover** and listeners was resolved.
fixes #13309
visually
<details>
```vue
<template>
<div>
:mini-variant="mini"
:expand-on-hover="mini"
app
>
<v-list-item class="px-2">
<v-list-item-avatar>
<v-img src="https://randomuser.me/api/portraits/men/85.jpg"></v-img>
</v-list-item-avatar>
<v-list-item-title>John Leider</v-list-item-title>
<v-btn
icon
@click="mini = !mini"
>
<v-icon v-show="mini">mdi-plus</v-icon>
<v-icon v-show="!mini">mdi-minus</v-icon>
</v-btn>
</v-list-item>
<v-main app>
<div class="pa-8">
<p>Content</p>
<v-switch
v-model="mini"
label="Is Mini"
/>
</div>
</v-main>
</div> …
```
=> fix(VNavigationDrawer): always bind mouseover events

packages/vuetify/src/components/VBtnGroup/VBtnGroup.tsx, packages/vuetify/src/components/VDefaultsProvider/VDefaultsProvider.tsx, packages/vuetify/src/composables/defaults.ts
Reduces markup needed to provide defaults and removes the need to use the **reactive**, **computed**, and **toRef** helpers.
```ts
// Before
provideDefaults(reactive({
defaults: {
VBtn: {
color: toRef(props, 'color'),
flat: true,
},
},
scoped: true,
}))
// After
provideDefaults({
VBtn: {
color: toRef(props, 'color'),
flat: true,
},
}, { scoped: true })
```
Improve the interface and make it easier to provide defaults from within a component.
<details>
```vue
<template>
<v-app>
<v-switch
v-model="color"
label="color"
true-value="primary"
false-value=""
/>
<v-switch
v-model="variant"
label="text"
true-value="text"
false-value="contained-text"
/>
<v-btn-group
:color="color"
:variant="variant"
class="flex-wrap"
>
<v-btn
v-for="n in 200"
:key="n"
height="32"
>Button {{ n …
```
=> refactor(defaults): simplify provideDefaults interface

packages/vuetify/src/mixins/routable/index.ts
The v-tabs component didn't move the slider if the v-tab had the property "exact"
After investigating, it came from the mixin routable,
The value of "exactActiveClass" was not checked before assigning to the path, resulting in
`'_vnode.data.class.undefined` 
I change the code to fall back on `proxyClass ` if  `exactActiveClass` is undefined
As a precaution I did the same for `activeClass` even if it's not needed for resolving this issue
the bug was introduced by PR https://github.com/vuetifyjs/vuetify/pull/14207
Resolves #14431 
Resolves #14459 
didn't add unit tests
Playground.vue
```vue
<template>
<v-container>
<v-tabs>
<v-tab
to="/page1"
>page1</v-tab>
<v-tab
to="/page2"
>page2</v-tab>
</v-tabs>
<v-btn to="/page2">Go to page 2</v-btn>
</v-container>
</template>
<script>
export default …
```
=> fix(VTabs): correctly set active state with exact prop

packages/docs/src/examples/v-btn-toggle/misc-wysiwyg.vue
Padding in v-btn-toggle example in vuetify doc
I have changed the padding of an example which is in vuetify documentation
Just to make documentation more readable
I added padding only nothing more
<details>
```vue
```
</details>
=> docs(misc-wysiwyg): update example padding

packages/vuetify/src/mixins/menuable/index.ts
fixes #12195 
<details>
```vue
<template>
<v-toolbar>
<v-toolbar-items style="width: 100%">
<v-menu offset-y>
<v-btn class="ms-5" v-on="on">
<span>Menu #2</span>
<v-icon>mdi-menu-down</v-icon>
</v-btn>
</template>
<v-list>
<v-list-item>
<v-list-item-title> item with basic content </v-list-item-title>
</v-list-item>
<v-list-item>
item with some of tooo looooong content that wont fit
</v-list-item>
<v-list-item>
<v-list-item-title> item with basic content </v-list-item-title>
</v-list-item>
</v-list>
</v-menu>
</v-toolbar>
</v-app>
</template>
<script>
mounted () {
this.$vuetify.rtl = true;
},
}
</script>
``` …
=> fix(VMenu): wrong alignment in RTL mode

packages/vuetify/src/components/VCalendar/VCalendarCategory.sass
fixes #14433
background color was set to `white` without getting sass varaibles og theme:calender
<details>
```vue
<template>
<v-calendar type="category"  />
</v-app>
</template>
<script>
mounted () {
this.$vuetify.theme.dark = true;
},
}
</script>
```
</details>
=> fix(VCalendar): use theme background color for categories

packages/vuetify/src/components/VDialog/VDialog.ts, packages/vuetify/src/components/VDialog/__tests__/__snapshots__/VDialog.spec.ts.snap
fixes #14231
change the role from "document" to "dialog"
fixes #14231
The "role" attribute applied to the dialog should be role="dialog". But in fact, the role applied to the dialog is role="document".
This is a screenshot of using VoiceOver.
This is the same code as the following link: https://vuetifyjs.com/ja/components/dialogs/#section-4f7f304465b9
<details>
```vue
<template>
<v-dialog
width="500"
>
<v-btn
color="red lighten-2"
dark
v-bind="attrs"
v-on="on"
>
Click Me
</v-btn>
</template>
<v-card>
<v-card-title class="text-h5 grey lighten-2">
Privacy Policy
<v-card-text>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna …
```
=> fix(VDialog): change the role from "document" to "dialog"

packages/vuetify/src/components/VField/VField.sass, packages/vuetify/src/components/VField/_variables.scss, packages/vuetify/src/components/VInput/VInput.sass, packages/vuetify/src/components/VTextField/VTextField.sass, packages/vuetify/src/components/VTextField/VTextField.tsx, packages/vuetify/src/components/VTextarea/VTextarea.sass
Change how VField and VInput handle control sizing.
The original implementation assumed a fixed height and used center alignment. Components like VTextarea and VSelect have a variable control height and require this change.
visually
<details>
https://www.toptal.com/developers/hastebin/xurekiqopa.kotlin
</details>
=> fix(VInput/VField): input and label location with density

packages/vuetify/src/components/VField/VField.tsx, packages/vuetify/src/components/VInput/VInput.tsx
resolves #14685
(#14685 )
testing the playground just check the console:
Forked vuetify repo, checkout next branch and create a new one: I fix `VField` and `VInput` components, then `yarn build` from root.
<details>
<summary><strong>Playground</strong></summary>
```vue
<template>
<v-container>
<v-text-field
label="What's your name?"
append-icon="mdi:account"
prepend-icon="mdi:account"
prepend-inner-icon="mdi:account"
append-inner-icon="mdi:account"
@click:append="handleClick('append')"
@click:prepend="handleClick('prepend')"
@click:append-inner="handleClick('append-inner')"
@click:prepend-inner="handleClick('prepend-inner')"
/>
</v-container>
</template>
<script>
methods: {
handleClick (from) {
// eslint-disable-next-line no-console
console.log(`click ${from}`)
},
},
} …
```
=> fix(VField/VInput): append/prepend click not being emitted

packages/docs/src/components/menus/ReleasesMenu.vue
Changed the title of the link to the vuetify next, from Alpha to Beta
The vuetify next is currently in version Beta, not version Alpha
=> docs: update title on link to vuetify next

packages/vuetify/src/components/VTreeview/VTreeview.ts
fixes https://github.com/vuetifyjs/vuetify/issues/14955
visually
<details>
```vue
<template>
<v-main>
<v-btn
color="info"
@click="setSelected"
>select last added</v-btn>
<v-treeview
v-model="selectedItems"
dense
selectable
:items="items"
:load-children="loadChildren"
></v-treeview> </v-main></v-app>
</template>
<script>
data: () => ({
selectedItems: [],
ctr: 0,
items: [
{
id: 1,
name: '1',
children: [
{ id: 2, name: '2', children: [] },
{ id: 3, name: '3', children: [] },
{ id: 4, name: '4', children: [] },
],
},
],
}),
methods: {
setSelected () {
this.selectedItems.push('new_' + (this.ctr - 1))
},
loadChildren (node) {
const id = 'new_' + this.ctr++
node.children.push({ id, name: id, children: [] })
},
},
}
</script>
```
</details>
=> fix(VTreeview): independent selection inheriting parent state

packages/api-generator/src/maps/components/v-form.js, packages/vuetify/src/components/VForm/VForm.tsx, packages/vuetify/src/components/VForm/__tests__/VForm.spec.cy.tsx, packages/vuetify/src/composables/form.ts, packages/vuetify/src/composables/index.ts
Related: #14945
If `preventDefault` is not called on the submit event then the form will be submitted normally when validation succeeds. Otherwise, consumers can await the submit event to take their own action after validation. 
<details>
```vue
<template>
<v-app>
<v-container>
<v-form ref="form" @submit.prevent="onSubmit">
<v-btn type="submit">submit</v-btn>
</v-form>
<v-btn type="submit" @click="submit">external submit</v-btn>
</v-container>
</v-app>
</template>
import { computed, ref, watch } from 'vue'
import type { SubmitEventPromise } from 'vuetify'
import type { VForm } from 'vuetify/components'
const form = ref<VForm>()
function onSubmit (e: SubmitEventPromise) {
// or const { valid } = await e
e.then(({ valid }) => {
console.log(valid)
}) …
```
=> feat(VForm): emit custom SubmitEventPromise event on submit

packages/docs/src/examples/v-tabs/prop-end.vue, packages/docs/src/pages/en/components/tabs.md, packages/vuetify/src/components/VTabs/VTabs.sass, packages/vuetify/src/components/VTabs/VTabs.tsx
According to @KaelWD Vuetify 3 renamed all `left` or `right` props to `start` and `end`. I also added this in `vtabs` component.
Align with existing props
I don't know how to write test
None
=> feat(VTabs): right prop renamed to end

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx
VAutocomplete only filters complete waits for words to be completed on Android. The input of the inner VTextField of VAutocomplete is binded with a v-model. When using an android phone with autocomplete keyboard (GBoard) the value is first emitted when a word is completed. For instance if you write "House" v-model will first be updated when the word is completed and not on "H" -> "Ho" -> "Hou"... This means that VAutoComplete only filters on completed words. 
Here is a [codepen](https://codepen.io/tibnor/pen/MWQWxwg)
This pull request changes the databinding of VTextField in VAutoComplete from v-model into `@input` and `:modelValue`. `@input` is emitted on every key, while v-model waits for a word to be completed when using autocomplete on android keyboards. 
The code has been tested …
=> fix(VAutocomplete): update search value for mobile

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx, packages/vuetify/src/composables/group.ts, packages/vuetify/src/composables/proxiedModel.ts
closes #15008
<details>
```vue
<template>
<div>
<p>
This sandbox demonstrates a bug in Vuetify v3 VSelect component where the
"update:modelValue" event fails to trigger when items are selected in
multiple mode, even though the bound model is kept in sync.
</p>
<v-select
v-model="selectedUsers"
@update:modelValue="onUpdate"
:items="items"
multiple
/>
{{ selectedUsers }}
</div>
</template>
<script>
import { defineComponent, ref } from "vue";
name: "playground",
setup() {
function onUpdate(value) {
console.log("update:modelValue", value);
}
return {
selectedUsers: ref([1, 2]),
items: [
{
value: 1,
title: "John Doe",
},
{
value: 2,
title: "Jane Doe",
},
{
value: 3,
title: "Jack Doe",
},
{
value: 4,
title: "Josh Doe",
},
],
onUpdate,
};
},
});
</script>
``` …
=> fix(VSelect): set model value to trigger emit

packages/api-generator/src/locale/en/v-overflow-btn.json, packages/vuetify/src/components/VOverflowBtn/VOverflowBtn.ts, packages/vuetify/src/components/VOverflowBtn/__tests__/VOverflowBtn.spec.ts, packages/vuetify/src/components/VOverflowBtn/__tests__/__snapshots__/VOverflowBtn.spec.ts.snap
Fixes #15052
v-overflow-btn fixed so that with 'persistent-placeholder' property set to 'true' v-overflow-btn label will be visible in both focused and blurred states
Fixes #15052
Prior to Vuetify version 2.4.0 v-overflow-btn label was visible when being focused
Since version 2.4.0 v-overflow-btn label disappears when being focused, v-overflow-btn is empty
v-overflow-btn "persistent-placeholder" property does not address this issue - with "persistent-placeholder" property set to "true" v-overflow-btn label is absent both in focused and blurred states
This fix aims to make v-overflow-btn label visible with "persistent-placeholder" set to "true" for both focused and blurred states
unit, visually
<details>
<template>
<v-container>
<div></div>
<v-overflow-btn
:items="items"
label="Label One" …
=> fix(VOverflowBtn): make persistentPlaceholder label visible

packages/docs/src/pages/en/components/sheets.md
* Made verb tense the same between "increases" and "decreases"
* Added spacing around hyphens
* Adjusted emphasis markdown to include only relevant words
To make language clear and consistent.
=> docs(VSheets): normalize grammar and clarify markup

packages/vuetify/src/components/VSlider/VSlider.sass, packages/vuetify/src/components/VSlider/VSliderTrack.sass, packages/vuetify/src/components/VSlider/VSliderTrack.tsx, packages/vuetify/src/components/VSlider/_variables.scss
Also fixed some weird positioning of tick labels
<details>
```vue
<template>
<v-app>
<v-container>
<v-slider show-ticks="always" :ticks="[0, 1, 2, 3]" max="3" step="1" direction="horizontal" />
<v-slider show-ticks="always" :ticks="[0, 1, 2, 3]" max="3" step="1" direction="vertical" />
</v-container>
</v-app>
</template>
```
</details>
=> feat(VSlider): add $slider-track-active-size-offset variable

packages/docs/src/App.vue, packages/docs/src/components/app/Markup.vue, packages/docs/src/components/app/Toc.vue, packages/docs/src/components/app/settings/Group.vue, packages/docs/src/components/examples/Example.vue, packages/docs/src/components/promoted/Base.vue, packages/docs/src/components/sponsor/Card.vue, packages/docs/src/pages/en/features/theme.md, packages/vuetify/src/composables/__tests__/theme.spec.ts, packages/vuetify/src/composables/theme.ts
Closes #15169
Also threw in a big ol' refactor because why not. 
Before
```ts
interface ThemeInstance {
/** Name of the current theme */
current: Ref<string>
/** Processed theme objects */
themes: Ref<{ [name: string]: ThemeDefinition }>
/** Processed theme object */
getTheme: (key: string) => ThemeDefinition
setTheme:(key: string, theme: ThemeDefinition) => void
}
```
After
```ts
interface ThemeInstance {
/** Name of the current theme */
name: Ref<string>
/** Raw theme objects */
themes: Ref<{ [name: string]: ThemeDefinition }>
/** Processed theme object, includes automatically generated colors */
readonly current: ThemeDefinition
readonly computedThemes: { [name: string]: ThemeDefinition }
}
```
=> feat(theme): redesign public interface

packages/vuetify/src/components/VForm/__tests__/VForm.spec.cy.tsx, packages/vuetify/src/composables/form.ts
A user on discord got confused because the old api looked like this:
```js
(await form.value.validate()).errorMessages[0].errorMessages
```
instead of
```js
(await form.value.validate()).errors[0].errorMessages
```
=> feat(VForm): rename errorMessages to errors

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx, packages/vuetify/src/composables/validation.ts
fixes #15142
```html
<template>
<v-app>
<v-container>
<v-form ref="form" @submit.prevent>
<v-text-field v-model="text" label="text field" :rules="rules" />
<v-select v-model="select" label="select" :items="items" multiple :rules="rules" />
<v-autocomplete v-model="autocomplete" label="autocomplete" :items="items" multiple :rules="rules" />
<v-combobox v-model="combobox" label="combobox" :items="items" multiple :rules="rules" />
<v-btn type="submit">Validate</v-btn>
<v-btn type="reset">Reset</v-btn>
<v-btn @click="resetValidation">Reset validation</v-btn>
</v-form>
<pre>{{ {
text,
select,
autocomplete,
combobox,
} }}</pre>
</v-container>
</v-app>
</template>
<script setup>
import { computed, ref, watch } from 'vue'
const form = ref()
const items = Array.from({ length: 5 }, (_, i) => `Item …
```
=> fix: validate selected items instead of search

packages/vuetify/src/components/VList/VListItem.ts, packages/vuetify/src/components/VList/__tests__/VListItem.spec.ts
Add check for disabled prop to keydown handler
Fixes #15322
unit and visually
<details>
```vue
<template>
<v-container>
<p class="pa-6 text-center">The second item should not emit the click event when focussed using keyboard and pressing enter:</p>
<v-card class="mx-auto" max-width="400" tile>
<v-list-item tabindex="0" @click="ClickMe()">
<v-list-item-title>Single-line item</v-list-item-title>
</v-list-item>
<v-list-item disabled tabindex="0" two-line @click="ClickMe()">
<v-list-item-title>Two-line item</v-list-item-title>
<v-list-item-subtitle>Secondary text</v-list-item-subtitle>
</v-list-item>
<v-list-item tabindex="0" three-line>
<v-list-item-title>Three-line …
```
=> fix(VListItem): dont trigger kb events for disabled item

packages/vuetify/src/components/VDialog/VDialog.sass, packages/vuetify/src/components/VDialog/VDialog.ts, packages/vuetify/src/components/VDialog/__tests__/VDialog.spec.ts, packages/vuetify/src/components/VDialog/__tests__/__snapshots__/VDialog.spec.ts.snap, packages/vuetify/src/mixins/dependent/index.ts, packages/vuetify/src/mixins/detachable/index.ts
Focus was moved when showing from content to inner content
fixes #14581
After showing a dialog with a scrollbar, pressing the PgDn and PgUp keys did not work
visually
<details>
```vue
<template>
<v-container>
<v-dialog
hide-overlay
transition="dialog-bottom-transition"
>
<v-btn
dark
v-bind="attrs"
v-on="on"
>
Open Dialog
</v-btn>
</template>
<v-card>
<v-toolbar
dark
>
<v-btn
icon
dark
@click="dialog = false"
>
<v-icon>mdi-close</v-icon>
</v-btn>
<v-toolbar-title>Settings</v-toolbar-title>
<v-btn
dark
text
@click="dialog = false"
>
Save
</v-btn>
</v-toolbar>
<v-list
three-line
subheader
>
<v-subheader>User …
```
=> fix(VDialog): focus on internal content when shown

packages/vuetify/src/components/VToolbar/VToolbar.sass, packages/vuetify/src/components/VToolbar/VToolbar.tsx, packages/vuetify/src/components/VToolbar/_variables.scss
Adjust v-btn location depending upon it's location in v-toolbar.
Visual consistency
visually
<details>
```vue
<template>
<v-app>
<v-main>
<div>
<v-container>
<v-toolbar>
<template #prepend>
</template>
<v-toolbar-title class="text-h6">
Messages
</v-toolbar-title>
<v-btn icon="mdi-dots-vertical" />
</template>
</v-toolbar>
<br>
<br>
<v-toolbar density="compact">
<v-toolbar-title class="text-h6">
Messages
</v-toolbar-title>
<v-btn icon="mdi-dots-vertical" />
</template>
</v-toolbar>
</v-container>
</div>
</v-main>
</v-app>
</template>
<script>
data: () => ({
messages: [
{
from: 'You',
message: `Sure, I'll see you later.`,
time: '10:42am',
color: 'deep-purple lighten-1',
},
{
from: 'John …
```
=> fix(VToolbar): v-btn location in and outside of prepend/append elements

packages/vuetify/src/components/VSlideGroup/VSlideGroup.tsx, packages/vuetify/src/components/VTabs/__tests__/VTabs.spec.cy.tsx
closes #15237
<details>
```vue
<template>
<v-app>
<v-container>
<div>
<v-tabs v-model="model.tab" color="primary" v-if="model.show">
<v-tab value="A">Tab A</v-tab>
<v-tab value="B">Tab B</v-tab>
<v-tab value="C">Tab C</v-tab>
</v-tabs>
</div>
<pre>{{ model.tab }}</pre>
<v-btn color="primary" @click="model.show = !model.show" class="my-4">
Toggle
</v-btn>
</v-container>
</v-app>
</template>
<script>
import { defineComponent } from 'vue'
data: () => ({
model: {
tab: 'A',
show: true,
},
}),
})
</script>
```
</details>
=> fix(VSlideGroup): add key to prevent unnecessary unmount

packages/docs/src/pages/en/features/theme.md, packages/vuetify/src/composables/__tests__/theme.spec.ts, packages/vuetify/src/composables/theme.ts
Allows to set a CSP Nonce via options on Vuetify v3
resolves #15358
A content-security-policy is an effective mechanism to improve the security of a web application. Vuetify's theming is added as an inline script, which is not allowed by most CSPs.  
In order to make it pass the policy, it is necessary to add a nonce to the script and style sources.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_inline_script
The feature is covered by two new unit tests.
```ts
createVuetify({
theme: {
cspNonce: 'my-csp-nonce',
},
})
```
<details>
```vue
```
</details>
=> fix(theme): allow a csp nonce to be specified

packages/vuetify/src/components/VBtn/_variables.scss, packages/vuetify/src/components/VPagination/__tests__/VPagination.spec.cy.tsx
Before: 
After:
Partially reverts #15213
<details>
```vue
<template>
<v-app>
<v-container>
<v-btn density="default" prepend-icon="mdi-vuetify">vuetify</v-btn>
<v-btn density="comfortable" prepend-icon="mdi-vuetify">vuetify</v-btn>
<v-btn density="compact" prepend-icon="mdi-vuetify">vuetify</v-btn>
<br>
<br>
<v-btn icon="mdi-vuetify" density="default" />
<v-btn icon="mdi-vuetify" density="comfortable" />
<v-btn icon="mdi-vuetify" density="compact" />
<br>
<br>
<v-btn density="default" prepend-icon="mdi-vuetify">vuetify</v-btn>
<v-btn icon="mdi-vuetify" density="default" />
<br>
<v-btn density="comfortable" prepend-icon="mdi-vuetify">vuetify</v-btn>
<v-btn icon="mdi-vuetify" density="comfortable" />
<br>
<v-btn density="compact" prepend-icon="mdi-vuetify">vuetify</v-btn>
<v-btn …
```
=> fix(VBtn): restore original density values

packages/docs/src/examples/v-radio-group/prop-colors.vue
Fix dark variants color props in VRadioButton docs
Check the [V3 docs on radio buttons](https://next.vuetifyjs.com/en/components/radio-buttons/#colors) color prop examples. The dark variant examples display as the base color because they are written as `"red darken-2"` instead of `"red-darken-2"`
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] The PR title is no longer than 64 characters.
- [ x ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ x ] My code follows the code style of this project.
=> docs(VRadio): fix color prop example casing

packages/vuetify/src/components/VImg/VImg.tsx
This PR fixes the VImg component for screen readers by adding an empty `alt` attribute to the generated `img` element.
Since this is a fix on Vuetify 3, I'm submitting the PR to the `next` branch.
When generating a decorative image, the generated `img` was not having an `alt` attribute, making the `img` processed as a non-decorative image by screen readers. 
My proposed change is to always generate an empty `alt` attribute since the image textual alternative is managed on an higher level (`VResponsive`) when necessary.
None since it is just an empty attribute addition.
N/A
=> fix(VImg): add an empty alt to VImg generated img element

packages/api-generator/src/maps/v-data-table.js
Add missing  `index` scoped prop of item column in `VDataTable`
Users can add a column of index by the following code:
```vue
<v-data-table :headers="[{ text: '#', value: 'index' }]"
<template #item.index="{ index }">
{{ index + 1 }}
</template>
```
But `index` slot prop of item column does not exist in docs.
I used web-types of vuetify 2 to generate global component types for Volar intellisense and type check. Then I found `index` scoped prop of `#item.<name>` is missing in docs of `VDataTable`, resulting into type error.
<details>
```vue
```
</details>
=> docs(VDataTable): add missing item column props

packages/vuetify/src/components/VCarousel/VCarousel.ts
The missing key would create issues with SSR, the controls would in some rare random cases get duplicated
The vue doc does say it's required on templated v-for custom components, I don't know how much of that applies to render components but from some reading through vue's code and some debugging, I'm confident the same applies
https://vuejs.org/style-guide/rules-essential.html#use-keyed-v-for
=> fix(VCarousel): add keys to delimiter buttons

packages/vuetify/src/components/VBtn/VBtn.sass
fixes #15566
replaces #15573
Before:
After:
=> fix(VBtn): use correct base opacity for disabled buttons

packages/vuetify/src/composables/defaults.ts, packages/vuetify/src/util/defineComponent.tsx, packages/vuetify/src/util/injectSelf.ts
fixes #15595
<details>
```vue
<template>
<v-app>
<v-container>
<v-card
max-width="300"
>
<v-list :items="items" />
</v-card>
</v-container>
</v-app>
</template>
<script setup>
{ type: 'subheader', title: 'Group #1' },
{
title: 'Item #1',
value: 1,
},
{
title: 'Item #2',
value: 2,
},
{
title: 'Item #3',
value: 3,
},
{ type: 'divider' },
{ type: 'subheader', title: 'Group #2' },
{
title: 'Item #4',
value: 4,
},
{
title: 'Item #5',
value: 5,
},
{
title: 'Item #6',
value: 6,
},
]
</script>
```
</details>
=> fix(defaults): merge scoped defaults with global config

packages/vuetify/src/components/VCalendar/mixins/__tests__/mouse.spec.ts, packages/vuetify/src/components/VCalendar/mixins/mouse.ts, tsconfig.json
<details>
```vue
<template>
<div>
<v-sheet height="300">
<v-chip
draggable
color="blue"
>drag me over the calendar</v-chip> mouseUp and mouseEnter functions no longer work with the dragged element
<v-calendar
ref="calendar"
type="month"
start="2021-01-17"
:weekdays="[1, 2, 3, 4, 5, 6, 0]"
@dragover:day="dragoverDay"
@mouseenter:day="mouseenterDay"
@mouseup:day="mouseupDay"
></v-calendar>
</v-sheet>
</div>
</template>
<script>
data: () => ({
}),
methods: {
dragoverDay (event) {
console.log('dragover', event.day)
},
mouseenterDay (event) {
console.log('enter', event.day)
},
mouseupDay (event) {
console.log('up', event.day)
},
},
}
</script>
```
</details>
=> fix(VCalendar): forward all bound events to internal elements

packages/vuetify/src/components/VSelectionControl/VSelectionControl.tsx
use internal input checked for determining model
fixes #15601
<details>
```vue
<template>
<v-container
class="px-0"
fluid
>
<v-radio-group v-model="radioGroup">
<v-radio
v-for="item in list"
:key="item.value"
:label="`Radio ${item.text}`"
:value="item.value"
/>
{{ typeof radioGroup }}
{{ radioGroup }}
<v-checkbox v-model="radioGroup2" />
</v-container>
</div>
</template>
<script>
data () {
return {
radioGroup: null,
radioGroup2: null,
list: [
{ text: 'Number 0', value: 0 },
{ text: 'Empty string', value: '' },
{ text: 'Number 1', value: 1 },
{ text: 'Number 2', value: 2 },
{ text: 'Boolean false', value: false },
{ text: 'Boolean true', value: true },
],
}
},
}
</script>
```
</details>
=> fix(VSelectionControl): set internal model from input.checked

packages/vuetify/src/components/VSelect/VSelect.tsx
fixes #15522
<details>
```vue
<template>
<v-select label="Test" :items="[0, 1, 2, 3]" />
<v-autocomplete label="Test" :items="[0, 1, 2, 3]" />
<v-combobox label="Test" :items="[0, 1, 2, 3]" />
</div>
</template>
```
</details>
=> fix(VSelect): toggle menu when clicking control

packages/vuetify/src/components/VCard/VCard.tsx, packages/vuetify/src/components/VList/VListItem.tsx
resolves #11149
fixes #15042
This **only** removes the active styling from links or selected items. In v2 it would also suppress `to`/`href`/`@click` and just render a plain div, which seems pretty pointless aside from `@click` as you could just remove `to`/`href` for the same behaviour. 
Should we bring that back, leave it like this, or make `:active` and `:link` undefined by default and able to accept false like #15042 assumed?
<details>
```vue
<template>
<v-app>
<v-container>
<v-list nav>
<v-list-item title="Active" to="/" />
<v-list-item title="Inactive" inactive to="/" />
<v-list-item title="Click" @click="" />
</v-list>
</v-container>
</v-app>
</template>
```
</details>
=> feat: make active and link props default value undefined

packages/vuetify/src/components/VAlert/VAlert.tsx
fixes #15557
<details>
```vue
<template>
<v-alert type="success" title="Alert title" prominent>
{{ lorem }}
</v-alert>
<br>
<v-alert density="comfortable" type="success" title="Alert title" prominent>
{{ lorem }}
</v-alert>
<br>
<v-alert density="compact" type="success" title="Alert title" prominent>
{{ lorem }}
</v-alert>
<br>
<v-alert type="success" title="Alert title">
{{ lorem }}
</v-alert>
<br>
<v-alert density="comfortable" type="success" title="Alert title">
{{ lorem }}
</v-alert>
<br>
<v-alert density="compact" type="success" title="Alert title">
{{ lorem }}
</v-alert>
</div>
</template>
<script>
data: () => ({
lorem: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ratione debitis quis est labore voluptatibus! Eaque …
```
=> fix(VAlert): adjust default prepended icon size

packages/vuetify/src/components/VAlert/VAlert.sass, packages/vuetify/src/components/VAlert/VAlert.tsx
fixes #15589
<details>
```vue
<template>
<v-alert closable>
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ratione debitis quis est labore voluptatibus! Eaque cupiditate minima, at placeat totam, magni doloremque veniam neque porro libero rerum unde voluptatem!
<template #close="props">
<v-btn size="large" v-bind="props" />
</template>
</v-alert>
</div>
</template>
<script>
}
</script>
```
</details>
=> fix(VAlert): use v-btn for closable functionality

packages/vuetify/package.json
Allow user to import blueprints without having to use `lib`.
```javascript
// before
import { md1 } from 'vuetify/lib/blueprints'
import { md2 } from 'vuetify/lib/blueprints/md2'
// after
import { md1 } from 'vuetify/blueprints'
import { md2 } from 'vuetify/blueprints/md2'
```
=> feat: add blueprints to package exports

packages/vuetify/src/components/VSlideGroup/VSlideGroup.tsx, packages/vuetify/src/components/VSlideGroup/__tests__/VSlideGroup.spec.cy.tsx, packages/vuetify/src/components/VSlideGroup/helpers.ts, packages/vuetify/src/components/VTabs/VTab.sass, packages/vuetify/src/components/VTabs/VTabs.sass
closes #15400
fixes reported bug, and cleans up additional issues surrounding rtl + direction variants
<details>
```vue
<template>
<v-locale-provider :rtl="rtl">
<v-card>
<v-tabs
background-color="deep-purple-darken-4"
centerActive
>
<v-tab>One</v-tab>
<v-tab>Two</v-tab>
<v-tab>Three</v-tab>
<v-tab>Four</v-tab>
<v-tab>Five</v-tab>
<v-tab>Six</v-tab>
<v-tab>Seven</v-tab>
<v-tab>Eight</v-tab>
<v-tab>Nine</v-tab>
<v-tab>Ten</v-tab>
<v-tab>Eleven</v-tab>
<v-tab>Twelve</v-tab>
<v-tab>Thirteen</v-tab>
<v-tab>Fourteen</v-tab>
<v-tab>Fifteen</v-tab>
<v-tab>Sixteen</v-tab>
<v-tab>Seventeen</v-tab>
<v-tab>Eighteen</v-tab>
<v-tab>Nineteen</v-tab>
<v-tab>Twenty</v-tab>
</v-tabs>
</v-card>
<v-btn @click="rtl = !rtl">rtl</v-btn>
</v-locale-provider>
</template>
<script>
data: () => ({ …
```
=> fix(VTabs): rtl buttons and scroll behaviour

packages/vuetify/src/components/VField/VField.sass, packages/vuetify/src/components/VTextField/__tests__/VTextField.spec.cy.tsx
Previously I filed this [PR](https://github.com/vuetifyjs/vuetify/pull/15570) but somehow markup got changed and the input isn't getting the correct placeholder color again.
<details>
```vue
const vuetifyTheme = useTheme()
const toggleTheme = () => {
vuetifyTheme.global.name.value = vuetifyTheme.global.name.value === 'dark' ? 'light' : 'dark'
}
</script>
<template>
<v-container>
<v-btn color="primary" class="mb-4" @click="toggleTheme">Toggle Dark mode</v-btn>
<div class="d-flex flex-column">
<p>Some body text</p>
<v-text-field placeholder="Placeholder" variant="outlined" />
<v-text-field label="Label" variant="outlined" />
<v-textarea placeholder="Placeholder" variant="outlined" />
<v-textarea …
```
=> fix(VField): input placeholder opacity

packages/vuetify/src/mixins/menuable/index.ts
- https://github.com/vuetifyjs/vuetify/issues/14922
▼`packages/vuetify/dev/Playground.vue`
```vue
<template>
<div id="app">
<div
:style="{
display: 'flex',
flexDirection: 'column',
alignItems: 'center'
}"
>
<v-btn @click="attachInPlace = !attachInPlace">
Toggle Attach
</v-btn>
<div :style="{ position: 'fixed', top: '50px' }">
<v-menu :attach="attachInPlace ? $refs.container : false" offset-y>
<v-btn v-on="on">
Menu
</v-btn>
</template>
<v-list>
<v-list-item v-for="item in items" :key="item">
{{ item }}
</v-list-item>
</v-list>
</v-menu>
<div ref="container"></div>
</div>
</div>
</v-app>
</div>
</template>
<script>
data: () => ({
attachInPlace: true,
items: ["First", "Second"]
}) …
```
=> fix(VMenu): disabled activatorFixed when attach is enabled

packages/api-generator/src/export.js
Add support for VDataTable `header.<name>` and `item.<name>` slots in `web-types` metadata for better Vuetify support in JetBrains IDEs..
This fix properly describes item and header slots according to the newest supported web-types format. 
It fixes issue https://youtrack.jetbrains.com/issue/WEB-55216/False-positive-Unrecognised-slot-name-warning-for-slots-with-dot-notation-in-Vuetify-components
Tested manually in the latest WebStorm version.
<details>
```vue
```
</details>
=> fix(web-types): add support for VDataTable pattern slots

packages/vuetify/src/components/VField/VField.sass, packages/vuetify/src/components/VField/VField.tsx, packages/vuetify/src/components/VTextField/VTextField.sass, packages/vuetify/src/components/VTextarea/VTextarea.sass
fixes #15610
<details>
```vue
<template>
<v-app>
<v-container>
<input v-model="density" type="radio" name="density" value="default">
<input v-model="density" type="radio" name="density" value="comfortable">
<input v-model="density" type="radio" name="density" value="compact">
<template v-for="variant in variants">
<v-defaults-provider :defaults="{ global: { density, variant, singleLine: false, rows: 1, maxRows: 2, autoGrow: true }}">
<div class="my-6" />
<v-row>
<v-col>
<v-text-field
label="Basic"
/>
</v-col>
<v-col>
<v-text-field
/>
</v-col>
<v-col>
<v-textarea
v-model="areaModel"
label="Basic"
/>
</v-col>
<v-col>
<v-textarea
v-model="areaModel"
/>
</v-col>
</v-row>
<v-row>
<v-col>
<v-text-field
label="Prefix/suffix"
prefix="prefix" …
```
=> fix(VField): center input when singleLine or no label

packages/vuetify/src/components/VAvatar/VAvatar.sass, packages/vuetify/src/components/VAvatar/VAvatar.tsx, packages/vuetify/src/components/VAvatar/_variables.scss
add variant support to `v-avatar`
closes #15593
<details>
```vue
<template>
<v-avatar variant="outlined" color="primary" icon="mdi-vuetify" />
<br>
<br>
<v-avatar variant="flat" color="primary" icon="mdi-vuetify" />
<br>
<br>
<v-avatar variant="elevated" color="primary" icon="mdi-vuetify" />
<br>
<br>
<v-avatar variant="tonal" color="primary" icon="mdi-vuetify" />
<br>
<br>
<v-avatar variant="plain" color="primary" icon="mdi-vuetify" />
<br>
<br>
</div>
</template>
```
</details>
=> feat(VAvatar): add variant support

packages/vuetify/src/composables/__tests__/theme.spec.ts, packages/vuetify/src/composables/theme.ts
closes #15850
<details>
```js
// dev/vuetify.js
import { createVuetify } from 'vuetify/src/entry-bundler'
import { aliases, mdi } from 'vuetify/src/iconsets/mdi'
import { fa } from 'vuetify/src/iconsets/fa-svg'
import { ar, en, ja, sv } from 'vuetify/src/locale'
const theme = {
dark: false,
colors: {
background: '#FFFFFF',
surface: '#FFFFFF',
color2: '#024452',
gradient: '#EFF5F7',
error: '#FF5252',
info: '#2196F3',
success: '#4CAF50',
warning: '#FFC107',
},
}
export default createVuetify({
ssr: !!process.env.VITE_SSR,
locale: {
messages: {
en,
ar,
sv,
ja,
},
},
icons: {
defaultSet: 'mdi',
aliases,
sets: {
mdi,
fa,
},
},
theme: {
defaultTheme: 'myColors',
themes: { myColors: theme },
variations: {
colors: ['color2'],
lighten: 4,
darken: 0,
}, …
```
=> fix(theme): custom color key variants and default merge

packages/vuetify/src/components/VField/VField.sass
closes #15481
<details>
```vue
<template>
<v-card>
<v-card-text>
<div class="d-flex pa-4">
<v-checkbox-btn
v-model="includeFiles"
class="pr-2"
/>
<v-text-field
label="Include files"
hide-details
/>
</div>
<div class="d-flex pa-4">
<v-checkbox-btn
v-model="enabled"
class="pr-2"
/>
<v-text-field
:disabled="!enabled"
hide-details
label="I only work if you check the box"
/>
</div>
</v-card-text>
</v-card>
</div>
</template>
<script>
data: () => ({
includeFiles: true,
enabled: false,
}),
}
</script>
```
</details>
=> fix(VField): label opacity flicker

packages/vuetify/src/components/VAutocomplete/VAutocomplete.sass, packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx
fixes #15756
fixes #15756
visually
<details>
```vue
<template>
<v-app>
<v-container>
<v-autocomplete :items="countries" item-title="name" item-value="code" >
<template #selection="{ item }">
{{ item.raw.code }} {{ item.raw.name }}
</template>
<template #item="{ props, item }">
<v-list-item v-bind="props" title="">
{{ item.raw.code }} {{ item.raw.name }}
</v-list-item>
</template>
:items="items"
dense
small-chips
label="Solo"
solo
<h1>Select</h1>      
<v-select :items="countries" item-title="name" item-value="code">
<template #selection="{ item }">
{{ item.raw.code }} {{ item.raw.name }}
</template>
<template #item="{ props, item }">
<v-list-item v-bind="props" title="">
{{ item.raw.code }} {{ …
```
=> fix(VAutocomplete): show selections slot and the input side-by-side like v2 does

packages/vuetify/src/components/VRadioGroup/VRadioGroup.tsx, packages/vuetify/src/util/__tests__/propsFactory.spec.ts, packages/vuetify/src/util/propsFactory.ts
Removes `multiple` prop
There are some other props that are passed as attr to VSelectionControlGroup (`density`, `error`, `ripple`, [`valuecomparator`](https://github.com/vuetifyjs/vuetify/issues/15896)), not sure if they should just be removed from props or somehow handled
fixes #15559
`yarn test` + apigen
```vue
<template>
<v-main>
<v-radio-group multiple>
<v-radio value="1" label="1" />
<v-radio value="2" label="2" />
</v-main>
</template>
```
=> fix(VRadioGroup): remove `multiple` prop

packages/vuetify/src/components/VFileInput/VFileInput.ts
alternative solution would be to stop click event propagation on textfield label altogether. not sure if that's better or not
closes #15888
playground
<details>
```vue
<template>
<v-file-input
accept="image/*"
label="Click me when I'm actived"
</template>
```
</details>
=> fix(VFileInput): label click opens dialog twice

packages/vuetify/src/components/VSelectionControlGroup/VSelectionControlGroup.sass
Inline radio buttons are not wrapped
https://codepen.io/jkarczm/pen/BaxbJvN?editors=1010
Vuetify 2: https://codepen.io/jkarczm/pen/MWGxrzm?editors=1010
visually
<details>
```vue
<template>
<v-radio-group inline>
<v-radio
v-for="i in 20"
:key="i"
label="foo bar baz"
:value="i"
/>
</template>
```
</details>
=> fix(VRadioGroup): wrap inline radio group

packages/docs/src/pages/en/features/global-configuration.md
The order of global-configuration was wrong. When i read it, it seemed odd to me since you'd think that the component specific would overwrite the global section. After testing it i saw that it indeed had a logical order and that's why the update to the docs is needed.
=> docs: change global configuration order wording

packages/docs/src/pages/en/features/sass-variables.md, packages/docs/src/pages/en/getting-started/installation.md
After following the installation guide sass is missing as an dependency. When installed globally this doesn't seem to be an issue. But for some coworkers of mine it was. Also in ci/cdlike githubactions this was an issue as wel.
```
vite v3.1.3 building for production...
transforming...
✓ 204 modules transformed.
[vite:css] Preprocessor dependency "sass" not found. Did you install it?
file: /home/runner/work/mobyyou-clubportal/mobyyou-clubportal/src/App.vue?vue&type=style&index=0&scoped=a9d3ab21&lang.scss
error during build:
Error: Preprocessor dependency "sass" not found. Did you install it?
```
not
=> docs: add sass installation information

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VList/VList.tsx, packages/vuetify/src/components/VList/VListGroup.tsx, packages/vuetify/src/components/VList/VListItem.sass, packages/vuetify/src/components/VList/VListItem.tsx, packages/vuetify/src/components/VList/__tests__/__snapshots__/VList.spec.ts.snap, packages/vuetify/src/components/VSelect/VSelect.tsx, packages/vuetify/src/components/VSlideGroup/VSlideGroup.tsx, packages/vuetify/src/composables/nested/nested.ts
Closes #15428
https://w3c.github.io/aria-practices/examples/listbox/listbox-grouped.html
https://w3c.github.io/aria/#listbox
https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/#x6-6-keyboard-navigation-inside-components
https://www.w3.org/WAI/ARIA/apg/example-index/menu-button/menu-button-actions.html
<details>
```vue
<template>
<v-app>
<v-container>
<v-tabs>
<v-tab>Tab 1</v-tab>
<v-tab>Tab 2</v-tab>
<v-tab>Tab 3</v-tab>
</v-tabs>
<br>
<v-list :items="listItems" />
<br>
<v-select :items="selectItems" />
</v-container>
</v-app>
</template>
<script setup>
const listItems = [
{ title: 'Item 1' },
{ title: 'Item 2' },
{
title: 'Item 3',
// value: 'item-3',
children: [
{ title: 'Item 3.1' },
{ title: 'Item 3.2', value: 'item-3.2' },
{ title: 'Item 3.3' },
],
},
{ title: 'Item 4' },
{ …
```
=> feat(VList): add keyboard navigation

packages/vuetify/src/util/defineComponent.tsx
fix support for nested aliased components 
<details>
```js
// vuetify.js
import { createVuetify } from 'vuetify/src/entry-bundler'
import { aliases, mdi } from 'vuetify/src/iconsets/mdi'
import { fa } from 'vuetify/src/iconsets/fa-svg'
import { ar, en, ja, sv } from 'vuetify/src/locale'
import { VBtn, VCard } from '../src/components'
export default createVuetify({
aliases: {
ZBtn: VBtn,
ZCard: VCard,
},
defaults: {
ZCard: {
variant: 'outlined',
ZBtn: {
color: 'primary',
},
},
},
ssr: !!process.env.VITE_SSR,
locale: {
messages: {
en,
ar,
sv,
ja,
},
},
icons: {
defaultSet: 'mdi',
aliases,
sets: {
mdi,
fa,
},
},
})
```
</details>
=> fix(defaults): assume capital first is nested component

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VList/VList.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx
fixes #16034
playground
<details>
```vue
<template>
<div style="height: 2000px">
<v-select
:items="['foo', 'bar', 'baz', 'fizz', 'buzz']"
label="Select"
/>
<v-combobox
:items="['foo', 'bar', 'baz', 'fizz', 'buzz']"
label="Select"
/>
:items="['foo', 'bar', 'baz', 'fizz', 'buzz']"
label="Select"
/>
</div>
</template>
<script setup>
const select = null
</script>
```
</details>
=> fix(VList): prevent scroll on keyboard navigation

packages/docs/src/pages/en/styles/display.md, packages/docs/src/pages/en/styles/flex.md
I have added information about the usage of !important in the display classes. Such as how this could be an issue and what would happen with an example noted.
#14773
This is a needed addition to the documentation because some people might overlook that `!important` is added in the display classes.
#14773
Since this is just documentation, it has been tested locally on my computer, both with a dev server and after building.
N/A
=> docs(display.md + flex.md): add caveats section

packages/docs/src/examples/flex/flex-align-self.vue
The box with the class align-self-center had the textual content align-self-start.
Updated the text to match the class.
=> docs: fix typo in flex-align-self.vue example

packages/vuetify/src/components/VCard/VCard.tsx, packages/vuetify/src/components/VProgressLinear/VProgressLinear.tsx
This PR proposal is to conditionaly hide the linear progress from the accessibility: it is hidden when the `active` prop value is `falsy` through a new `aria-hidden` attribute binding.
The loader is currently rendered in the page with a tricky method (height of 0). This create an accessibility problem: the progress is not visible, but is still read by screen reader (as it is still in the accessibility tree).
This has been tested through the Playground with direct use of `VProgressLinear` (with or without `active` and `aria-hidden`).
<details>
<summary>My `Playground.vue` code</summary>
```vue
<template>
<v-app>
<v-container>
<div class="my-5">
<v-progress-linear :active="loading" indeterminate />
</div>
<div class="my-5">
<v-progress-linear :active="true" aria-hidden="true" indeterminate …
```
=> fix(VProgressLinear): hide from accessibility tree if not active

packages/docs/src/pages/en/getting-started/frequently-asked-questions.md, packages/docs/src/pages/en/styles/display.md
The link for vue-router, router-link documentation has been changed and therefore the current link is no longer valid, this PR changes the link to the current and updated vue-router link.
#15084
It is quite obvious why this is required, the link is outdated which makes that part of the documentation worthless without updating it.
#15084
Since this is just documentation, it has been tested locally on my computer, both with a dev server and after building.
N/A
=> docs(frequently-asked): fix broken link

packages/vuetify/build/rollup.config.js
Building Vuetify on windows was producing incorrect paths in importMap ~~(+ few eslint fixes because autofix on save)~~
Also fixed generating .css files in wrong folder when building Vuetify
- build vuetify
- build api
- check api-generator/src/attributes.json (should not be empty)
=> chore: fix importMap paths on windows

packages/api-generator/src/locale/en/v-app-bar.json, packages/api-generator/src/locale/en/v-toolbar.json, packages/vuetify/src/components/VAppBar/VAppBar.tsx, packages/vuetify/src/components/VToolbar/VToolbar.tsx
fixes #16141
playground/docs
<details>
```vue
<template>
<v-main>
<v-app-bar>
<template #title>Title slot (VAppBar)</template>
<template #prepend>Prepend slot (VAppBar)</template>
<template #append>Append slot (VAppBar)</template>
</v-app-bar>
<v-app-bar title="Title prop (VAppBar)" />
<v-toolbar>
<template #title>Title slot (VToolbar)</template>
<template #prepend>Prepend slot (VToolbar)</template>
<template #append>Append slot (VToolbar)</template>
</v-toolbar>
<v-toolbar title="Title prop (VToolbar)" />
</v-main>
</template>
```
</details>
=> docs: add missing VAppBar/VToolbar slots

packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.tsx
When having rail as a prop and v-model i noticed that while resizing the drawer scrim stayed on top and application became unusable because isActive value stayed benig true. Thats why I added nextTick on the update of isActive so when all resizing is done and DOM is updated, we update isActive.
Not 100% sure why this was happening only when you had rail as a prop, but like I said I noticed `isActive` state being `true` when you resize.
fix #15807
I tested visially but I can also maybe create tests checking if scrim is on top when resizing the window
<details>
```vue
```
</details>
=> fix(VNavigationDrawer): wait for nextTick in isTemporary watch

packages/vuetify/src/components/VOverlay/locationStrategies.ts
Menus and tooltips with :model-value='true' were not in the correct position because the refs for attached element were still undefined when the watchEffect in useLocationStrategies finished running. This fix will cause the watchEffect to run a second time after render, but only when the overlay is attached to an element.
fix #16042
Added an if statement so the async function doesn't call nextTick() if the location strategy is "connected" (the mode for tooltips and menus). Resolves #16042  
Bug described in #16042 also applied to VMenu. This change fixes both components.
Tested visually in multiple browsers.
<details>
```vue
<template>
<v-app>
<v-container>
<v-tooltip text="Tooltip" location="right" :model-value="true">
<template v-slot:activator="{ props }">
<v-btn …
```
=> fix(VOverlay): positioning when activated by default

packages/vuetify/.env.local, packages/vuetify/src/components/VCheckbox/VCheckbox.sass, packages/vuetify/src/components/VSelectionControl/VSelectionControl.sass, packages/vuetify/src/components/VSwitch/VSwitch.sass
fixes #15708 
<details>
```vue
<template>
<div class="ma-16 pa-16">
<v-selection-control label="Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ratione debitis quis est labore voluptatibus! Eaque cupiditate minima, at placeat totam, magni doloremque veniam neque porro libero rerum unde voluptatem!" />
<v-checkbox label="Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ratione debitis quis est labore voluptatibus! Eaque cupiditate minima, at placeat totam, magni doloremque veniam neque porro libero rerum unde voluptatem!" />
<v-switch label="Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ratione debitis quis est labore voluptatibus! Eaque cupiditate minima, at placeat totam, magni doloremque veniam neque porro libero rerum unde …
```
=> fix(VSelectionControl/VCheckbox/VSwitch): long label wrapping

packages/vuetify/src/shims.d.ts
Typing for `this.$vuetify` doesn't unwrap refs
Discussion on discord: https://discord.com/channels/340160225338195969/660898563139567625/1047548064866521110
wasn't (due to some unrelated technical problems)
```ts
interface Vuetify {
defaults: DefaultsInstance
display: DisplayInstance
theme: ThemeInstance
icons: IconOptions
locale: LocaleInstance & RtlInstance
}
export interface ComponentCustomProperties {
$vuetify: UnwrapNestedRefs<Vuetify>
}
```
=> fix(types): unwrap refs in `this.$vuetify`

packages/vuetify/src/components/VRadioGroup/VRadioGroup.tsx
VRadioGroup label should not be clickable (it isn't in Vuetify 2)
playground
<details>
```vue
<template>
<div class="ma-16 pa-16">
<v-radio-group label="Lorem ipsum">
<v-radio label="Lorem ipsum" value="0" />
<v-radio label="Lorem ipsum" value="1" />
</div>
</template>
```
</details>
=> fix(VRadioGroup): remove clickable from label

packages/vuetify/src/services/goto/util.ts, packages/vuetify/src/util/__tests__/console.spec.ts, packages/vuetify/src/util/console.ts
In Vue3 `_isVue` has been renamed to `__isVue`.
References:
https://github.com/vuejs/vue-next/search?q=__isVue
https://github.com/vuejs/vue/search?q=_isVue
I had warnings from Vue3's compatibility mode saying :
`Property "_isVue" was accessed during render but is not defined on instance.`
All relevant unit tests have been amended in this PR.
<details>
```vue
```
</details>
=> fix: change _isVue references to vue3's __isVue

packages/vuetify/src/composables/__tests__/validation.spec.ts, packages/vuetify/src/composables/validation.ts
Also allows 0 max messages
fixes #16242
<details>
```vue
<template>
<div class="ma-16 pa-16">
<v-text-field error-messages="Foo" />
<v-text-field error-messages="Foo" max-errors="0" />
<v-text-field error-messages="Foo" max-errors="1" />
</div>
</template>
```
</details>
=> fix(validation): don't truncate error message passed as string

packages/docs/src/pages/en/features/icon-fonts.md
Improves the accuracy of the mdi-svg usage, explaining why it's the recommended method for production environments and mention the ability to use different icons components.
As discussed in Discord (conversation starts [here](https://discord.com/channels/340160225338195969/660898563139567625/1045480458340810754)), I wanted to make sure I only used the minimum icon set for Vuetify to work, as I want to use unplugin-icons for the rest of the app. [Kael](https://discord.com/channels/340160225338195969/660898563139567625/1045930473446195230) confirmed that running the code snippet in this part of the documentation works as I intended.
Later on, #16168 was opened, so components can be passed as slots to ``v-icon``, further improving this usage.
This is the first part of the documentation …
=> docs(icon-fonts): improve accuracy of mdi-svg usage

packages/api-generator/src/locale/en/v-data-table.json, packages/api-generator/src/maps/v-data-table.js, packages/vuetify/src/components/VDataTable/VDataTable.ts
You are not able to do something with the event argument when using the row click. One thing that could be possible after this PR is creating a ctrl+click for a new tab.
There is an `@TODO`  for implementing this in v3 as first argument but for making the migration easier it could be possible after this PR
```vue
<template>
<v-container>
<v-data-table
@click:row="showDetails"
</v-container>
</v-app>
</template>
<script>
data () {
return {
headers: [
{
value: 'name',
},
{ text: …
```
=> fix(VDataTable): native event as argument to click:row

packages/vuetify/src/directives/ripple/index.ts
Check parent before calling removeChild in v-ripple ( #13457 )
fixes #13457
User actions with ripple effect in iOS devices throw quite a few those errors.
Only 1 line non-breaking change, so no additional test created. 
<details>
```vue
```
</details>
=> fix(ripple): check parent before calling removeChild

packages/docs/src/examples/v-autocomplete/misc-asynchronous-items.vue
The "Asynchronous example" in the "Autocompletes" section is broken here: https://next.vuetifyjs.com/en/components/autocompletes/
I was creating this component locally, and it wasn't working after I copied the example. After the change, it works as it should.
The API here is correct: https://next.vuetifyjs.com/en/api/v-autocomplete/#props-search
=> docs(autocomplete): fix asynchronous example

packages/docs/src/examples/v-navigation-drawer/prop-bottom-drawer.vue
updated drawer height because currently it's just so small that no one can tell what's the example is being showed.
<details>
```vue
```
</details>
=> docs(VNavigationDrawer): increase height of bottom example

packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.tsx, packages/vuetify/src/components/VNavigationDrawer/__tests__/VNavigationDrawer.spec.cy.tsx
Add support for rail v-model. Allows the user to choose to have main content shift with or without the rail expand-on-hover.
resolves #16022
e2e
<details>
```vue
<template>
id="drawer"
v-model:rail="miniVariant"
expand-on-hover
app
color="#8dca9d"
>
<v-list nav>
<v-list-item>
{{ myWidth }}
</v-list-item>
</v-list>
<v-main>
<div>
Mini: {{ miniVariant }}
</div>
</v-main>
</div>
</template>
<script>
data: () => ({
miniVariant: true,
myWidth: 0,
sidebar: null,
observer: null,
}),
mounted () {
this.sidebar = document.querySelector('#drawer')
this.observer = new ResizeObserver(this.onResize)
this.observer.observe(this.sidebar)
},
beforeUnmount () {
if (this.observer) {
this.observer.unobserve(this.sidebar)
}
}, …
```
=> feat(VNavigationDrawer): add rail prop v-model support

packages/vuetify/src/components/VCheckbox/VCheckbox.tsx, packages/vuetify/src/components/VField/VField.tsx, packages/vuetify/src/components/VFileInput/VFileInput.tsx, packages/vuetify/src/components/VInput/VInput.tsx, packages/vuetify/src/components/VMessages/VMessages.tsx, packages/vuetify/src/components/VRadioGroup/VRadioGroup.tsx, packages/vuetify/src/components/VRangeSlider/VRangeSlider.tsx, packages/vuetify/src/components/VSlider/VSlider.tsx, packages/vuetify/src/components/VSwitch/VSwitch.tsx
This PR proposes improvements on inputs' messages by adding a unique ID and ARIA attributes to the messages wrapper div (`role="alert"` and `aria-live="polite"`) and referencing those messages on input using `aria-describedby`.
Currently, the messages are not "connected" to the input for screen readers. Messages are not even read by SR when alerting on an error inside input.
This have been tested using the Vuetify playground when developping on various framework's inputs. See the test markup bellow.
<details>
```vue
<template>
<v-app>
<v-container>
<h1>Input messages accessibility</h1>
<template
v-for="id in testIds"
:key="`${id}`"
>
<h2>With ID: {{ id ?? 'undefined' }}</h2>
<template
v-for="(component, index) in testComponents"
:key="`${id}-${index}`"
>
<component
:is="component"
:id="id …
```
=> fix: improve accessibility of inputs' messages

packages/vuetify/src/components/VGrid/VGrid.sass
apply to a v-container, fill-height property have to set display flex and default align-items center to vertical align container (backport from v2.x)
=> fix(VContainer): fill-height prop

packages/vuetify/vite.config.mjs
The dev server can now properly listen on another IP address if one is specified in the HOST environment variable in the .env file.
When running `yarn dev`, I want to be able to access the dev server from another machine than localhost (specifically, I'm developing in a VM and accessing the project from my computer).
It used to be possible, in the main branch, to use the webpack dev server with a HOST environment variable for that purpose, but it seems to have disappeared in the new vite build system.
- Set `HOST=0.0.0.0` in the /packages/vuetify/.env file
- Run `yarn dev`
- See that `Network: use --host to expose` have disappeared, replaced by the actual IP addresses of your machines
<details>
```vue
```
</details>
=> chore(dev): allow to listen on the network

packages/vuetify/src/components/VBtn/VBtn.tsx
fixes #15833 & #15982
Cause: `v-bottom-navigation` adds `group?.isSelected`, which returns `isActive` as true even if VBtn's `link.isActive` becomes false
Solution: 
- `props.active` takes highest priority when it is explicitly set as `true` or `false`
- `link.active` takes second priority when it is a link
- `group.active` performs as the lowest priority when previous two are not valid
fixes #15833 & #15982
visually 
Firstly, config routes in `packages/vuetify/dev/index.js`
```js
// import { routes } from './router'
const Home = { template: '<div>Home</div>' }
const About = { template: '<div>About</div>' }
const Help = { template: '<div>Help</div>' }
const Login = { template: '<div>Login</div>' }
const routes = [
{ path: '/', component: Home },
{ path: '/about', component: About },
{ …
```
=> fix(VBtn): isActive calc priorities

packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.cy.tsx, packages/vuetify/src/composables/__tests__/filter.spec.ts, packages/vuetify/src/composables/filter.ts, packages/vuetify/src/labs/VDataTable/VDataTable.tsx, packages/vuetify/src/labs/VDataTable/VDataTableVirtual.tsx
fixes #16403
closes #16411
Kinda a temporary fix, I think tables need a separate InternalItem interface because some of the list stuff doesn't make sense for tables.
I also prefer this approach over #16411 as it doesn't run itemTitle multiple times, and still works with itemTitle as a function.
```vue
<template>
<v-container>
<v-combobox v-model:search="search" :items="items" item-title="name" />
<v-data-table :search="search" :items="items" :headers="headers" />
</v-container>
</template>
<script setup>
const search = ref('')
{
key: 'name',
},
{ title: 'Calories', align: 'end', key: 'calories' },
{ title: 'Fat (g)', align: 'end', key: 'fat' },
{ title: 'Carbs (g)', …
```
=> fix(VCombobox): filter transformed items

packages/vuetify/src/components/VBtn/VBtn.tsx, packages/vuetify/src/components/VBtn/__tests__/VBtn.spec.cy.tsx
- Implements the logic to allow consumers to provide a `value` prop that will be attached as Node attribute to the underlying DOM element.
fix #16188
Added Cypress Component testing
=> fix(VBtn): accept value prop for underlying DOM element 

packages/vuetify/src/components/VDivider/VDivider.tsx
Replaced useTextColor instead of useBackgroundColor.
resolves #16517
To change divider color, we need to set the color property instead of the background-color property. That's why I replaced useBackgroundColor composable with useTextColor.
```vue
<template>
<v-container>
<v-card color="" dark class="mx-auto" width="400px" hight="100vh" :loading="isUpdating">
<v-divider color="#fff" thickness="1"></v-divider>
<span>Some text</span>
<v-divider color="rgb(0,0,0)" thickness="2"></v-divider>
<span>Some text</span>
<v-divider color="rgb(0,0,0)" thickness="3"></v-divider>
<span>Some text</span>
<v-divider color="#92fd93" thickness="4"></v-divider>
<span>Some text</span>
<v-divider color="rgb(0,0,0)" thickness="5"></v-divider>
<span>Some text</span>
<v-divider class="rgb(0,0,0)" …
```
=> fix(VDivider): fix color attribute

packages/docs/src/examples/v-data-table/misc-server-side-paginate-and-sort.vue, packages/vuetify/src/labs/VDataTable/VDataTable.tsx, packages/vuetify/src/labs/VDataTable/VDataTableRows.tsx, packages/vuetify/src/labs/VDataTable/VDataTableServer.tsx, packages/vuetify/src/labs/VDataTable/VDataTableVirtual.tsx, packages/vuetify/src/labs/VDataTable/__tests__/VDataTableServer.spec.cy.tsx, packages/vuetify/src/labs/VDataTable/composables/options.ts
needed to fix regression caused by VDataTableRows injecting group to pass to slot
closes #16468
<details>
```vue
<template>
<div>
:items-length="totalDesserts"
:items-per-page="2"
show-select
show-expand
@update:options="options = $event"
>
<template v-slot:expanded-row>
This is an expanded row
</template>
</v-data-table-server>
</div>
</template>
<script>
data () {
return {
desserts: [],
loading: true,
options: {},
headers: [
{
key: 'name',
},
{ title: 'Protein …
```
=> fix(VDataTableServer): add groupBy functionality

packages/vuetify/src/components/VFileInput/VFileInput.tsx, packages/vuetify/src/components/VFileInput/__tests__/VFileInput.spec.cy.tsx
fix #16167
Currently, when the input is reset programmatically outside the VFileInput, the underlying `HTMLInputElement` is not reset, which prevents the same file from being reselected.
- implementing a Component testing to verify behaviour
Currently, in Cypress Component testing the Input doesn't update correctly. I might not be too familiar with the `cy` API and would require some help
```vue
<template>
<v-app>
<v-main>
<v-file-input v-model="files" />
<v-btn @click="onClick">remove input files</v-btn>
<ol class="pl-4">
<li>add a file</li>
<li>click remove button</li>
<li>add the same file</li>
</ol>
</v-main>
</v-app>
</template>
<script setup>
const files = ref([])
const onClick = () => {
files.value = []
}
</script>
```
* []  I've added relevant changes to …
=> fix(VFileInput): reset internal input when model is cleared

packages/docs/src/examples/flex/flex-justify.vue
=> docs(flex): add .justify-space-evenly to example

packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VSelect/__tests__/VSelect.spec.cy.tsx, packages/vuetify/src/composables/items.ts
closes #16512
```vue
<template>
<v-app>
<v-main>
<v-select v-model="selected" :items="values" multiple return-object />
<v-select v-model="selectedPlain" :items="valuesPlain" multiple return-object />
<v-combobox
v-model="foo"
v-model:search="search"
:items="items"
/>
<pre>{{ foo }}</pre>
<pre>{{ search }}</pre>
</v-main>
</v-app>
</template>
<script setup>
const selected = ref([{title: 'test', value: 'red'}])
const selectedPlain = ref([{title:'test', value: 'red'}])
const values = ref([{title: 'test', value:'red'}])
const valuesPlain = [{title: 'test', value:'red'}]
{ title: 'Item 1', value: 'item1' },
{ title: 'Item 2', value: 'item2' },
{ title: 'Item 3', value: 'item3' },
{ title: 'Item 4', value: 'item4' },
]
const foo = ref()
const search = …
```
=> fix(VSelect): return-object with plain items

packages/vuetify/src/composables/proxiedModel.ts
fixes #16512
alternative to #16546
```vue
<template>
<v-app>
<v-main>
<v-select v-model="selected" :items="values" multiple return-object />
<v-select v-model="selectedPlain" :items="valuesPlain" multiple return-object />
<v-combobox
v-model="foo"
v-model:search="search"
:items="items"
/>
<pre>{{ foo }}</pre>
<pre>{{ search }}</pre>
</v-main>
</v-app>
</template>
<script setup>
const selected = ref([{ title: 'test', value: 'red' }])
const selectedPlain = ref([{ title: 'test', value: 'red' }])
const values = ref([{ title: 'test', value: 'red' }])
const valuesPlain = [{ title: 'test', value: 'red' }]
{ title: 'Item 1', value: 'item1' },
{ title: 'Item 2', value: 'item2' },
{ title: 'Item 3', value: 'item3' },
{ title: 'Item 4', value: 'item4' },
] …
```
=> fix(proxiedModel): don't pass reactive objects to transformIn()

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VField/VField.tsx, packages/vuetify/src/components/VFileInput/VFileInput.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx, packages/vuetify/src/components/VTextField/VTextField.tsx, packages/vuetify/src/components/VTextarea/VTextarea.tsx
Fixes select label transition hitching with lots of items
Fixes inconsistent behaviour when clicking fields outside of the `<input>` element
```vue
<template>
<v-container>
<v-autocomplete :items="items" label="Label" />
<v-textarea />
<v-file-input />
</v-container>
</template>
<script setup>
const items = Array.from({ length: 1000 }, (_, i) => `Item ${i}`)
</script>
```
=> fix(inputs): focus on mousedown instead of click

packages/docs/src/pages/en/getting-started/upgrade-guide.md
Add missing obsolete or renamed components.
I have a discussion about it on Vuetify Discord #documentation 
> Hello, I will have to migrate a large application from vue 2 to vue 3 (using vuetify). I am making an inventory of the components used, and if they are still present and how to migrate them. There are some components, that I didn't find in vuetify 3: v-simple-table, v-subheader, v-tab-item. What are the status about them ? Should we add information about this in the migration guide ?
> johnleider — Today à 16:00
> v-simple-table -> v-table
> v-subheader -> v-list-subheader
> v-tab-item -> v-window-item
=> docs(upgrade-guide): add some renamed components

packages/docs/src/data/page-to-api.json
The links to the v-toolbar-items, v-toolbar-title are missing in the v3 documentation
v2 docs : https://vuetifyjs.com/en/components/toolbars/#api 
v3 docs : https://next.vuetifyjs.com/en/components/toolbars/#api 
I added the missing information to display the links
=> docs: add missing links to v-toolbar-items, -title

packages/vuetify/src/components/VAppBar/VAppBar.tsx, packages/vuetify/src/components/VBottomNavigation/VBottomNavigation.tsx, packages/vuetify/src/components/VSystemBar/VSystemBar.tsx
When moving between layouts the application app-bar has an entry animation.
=> fix(VAppBar/VSystemBar/VBottomNavigation): add ssr boot styling

packages/docs/src/components/app/bar/EcosystemMenu.vue
Changed playground url because the old one is not working.
The playground url in the Appbar points to https://playground.vuetifyjs.com which does not work.
Changed to https://play.vuetifyjs.com
=> docs: fix vuetify playground url

packages/docs/src/pages/en/getting-started/upgrade-guide.md
Just a small documentation fix.
Changed `createVue()` to `createApp()` in the code example because this is the correct usage.
This change will ensure people looking to migrate will not be confused. Especially for those unfamiliar with Vue3.
[Reference from Vue docs](https://vuejs.org/guide/essentials/application.html#the-application-instance)
=> docs: Fix code example for upgrade guide docs

packages/vuetify/src/components/VColorPicker/VColorPickerCanvas.tsx, packages/vuetify/src/components/VColorPicker/VColorPickerEdit.tsx, packages/vuetify/src/components/VColorPicker/VColorPickerPreview.tsx, packages/vuetify/src/components/VColorPicker/__tests__/VColorPicker.spec.cy.tsx, packages/vuetify/src/components/VColorPicker/util/__tests__/index.spec.ts, packages/vuetify/src/components/VColorPicker/util/index.ts, packages/vuetify/src/util/colorUtils.ts
Fixes #16672
- hex now parses with or without leading `#`
- alpha value is removed instead of resetting to FF
```vue
<template>
<v-app>
<v-main>
<v-container>
<v-color-picker
v-model="pickedColor"
elevation="15"
mode="rgba"
:modes="['hex', 'hexa', 'rgb', 'rgba']"
/>
<div class="mt-3">
Selected color: {{ pickedColor }}
</div>
</v-container>
</v-main>
</v-app>
</template>
<script setup>
const pickedColor = ref('#00FF00')
</script>
```
=> fix(VColorPicker): consistent output values

package.json, packages/docs/package.json, packages/vuetify/package.json, packages/vuetify/src/composables/theme.ts, yarn.lock
```vue
<template>
<v-app>
<v-container>
<v-btn color="primary" @click="toggle">Toggle theme</v-btn>
</v-container>
</v-app>
</template>
<script setup>
const theme = useTheme()
function toggle () {
theme.themes.value.light.colors.primary = theme.themes.value.light.colors.primary === '#1976d2' ? '#ff0000' : '#1976d2'
}
</script>
```
=> fix(theme): support vueuse/head v1.0

packages/docs/src/components/app/V2Banner.vue, packages/vuetify/src/components/VSystemBar/VSystemBar.sass, packages/vuetify/src/components/VSystemBar/_variables.scss
=> fix(VSystemBar): reserve space for hidden scrollbar from VOverlay

packages/vuetify/src/labs/VDataTable/VDataTableServer.tsx
Fixes #16704
```vue
<template>
:items-length="totalDesserts"
:items-per-page="2"
show-select
show-expand
@update:options="options = $event"
>
<template v-slot:column.name="{ column }">
{{ column.title.toUpperCase() }}
</template>
</v-data-table-server>
</template>
<script>
data () {
return {
desserts: [],
loading: true,
options: {},
headers: [
{
key: 'name',
},
{ title: 'Iron (%)', key: 'iron' },
],
}
},
watch: {
options: { …
```
=> fix(VDataTableServer): Support column slots

packages/vuetify/src/labs/VVirtualScroll/VVirtualScroll.tsx
Fixes #16725
Replaces #16726
```vue
<template>
<VApp>
<VMain>
<VSheet class="mx-5">
<VVirtualScroll :items="items" height="300">
<template #default="{ item, index }">
<p>
{{ index + 1 }} - {{ item }}
</p>
</template>
</VVirtualScroll>
<p class="mt-3">Total: {{ items.length }}</p>
</VSheet>
</VMain>
</VApp>
</template>
<script setup>
import { onMounted, onUnmounted, ref } from 'vue'
'sentence The rough teacher sadly dodged because some teacher humbly rolled below a rough hamster which, became a dumb, lovely old lady.',
'The soft hamster elegantly kicked because some old lady proudly died above a vibrating boy which, became a lazy, beautiful clock.',
'The soft plastic calmly died because some old lady proudly died above a lovely old lady which, became a vibrating, soft …
```
=> fix(VVirtualScroll): reset cached sizes on items length change

packages/docs/src/pages/en/getting-started/upgrade-guide.md
Add additional upgrade notes related to several components, theming and sass variables. 
I added them because I would have been grateful to have them when upgrading from v2.
=> docs(upgrade-guide): add additional upgrade notes

packages/vuetify/src/components/VTooltip/VTooltip.tsx
For performance reasons this should have **eager** support. Tested with 250 tooltips. Reduced render time by almost 50%.
| Eager | Avg Render Time |
| - | - |
|  true |  280ms |
| false | 143ms |
<details>
```vue
<template>
<v-app>
<template v-for="n in 100" :key="n">
<v-tooltip :eager="false">
<button v-bind="props">Tooltip</button>
</template>
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, ratione debitis quis est labore voluptatibus! Eaque cupiditate minima, at placeat totam, magni doloremque veniam neque porro libero rerum unde voluptatem!
</v-tooltip>
</template>
</div>
</v-app>
</template>
<script setup>
</script>
```
</details>
=> feat(VTooltip): add eager prop support

packages/vuetify/src/components/VSnackbar/VSnackbar.sass, packages/vuetify/src/components/VSnackbar/VSnackbar.tsx
Allows for `content-class="elevation-xx"`
```vue
<template>
<div class="text-center ma-2">
<v-btn
@click="snackbar = true"
>
Open Snackbar
</v-btn>
<v-snackbar
v-model="snackbar"
timeout="-1"
>
{{ text }}
<template #actions>
<v-btn
color="pink"
variant="text"
@click="snackbar = false"
>
Close
</v-btn>
</template>
</v-snackbar>
</div>
</template>
<script>
data: () => ({
snackbar: false,
text: `Hello, I'm a snackbar`,
}),
}
</script>
```
=> refactor(VSnackbar): remove redundant wrapper element

packages/vuetify/src/components/VAlert/_variables.scss
reduce inline margin end
**BEFORE:**
**AFTER:**
<details>
```vue
<template>
<v-app>
<v-defaults-provider
:defaults="defaults"
>
<div class="ma-4 pa-4 d-flex">
<div class="me-8">
<v-alert
type="info"
color="#0d66d0"
theme="dark"
text="Check the downloads section of your browser for the installer, or find it where you save downloads on your machine."
closable
max-width="385"
/>
<br>
<br>
<v-alert
type="success"
theme="dark"
text="Check the downloads section of your browser for the installer, or find it where you save downloads on your machine."
closable
max-width="385"
/>
<br>
<br>
<v-alert
type="warning"
theme="dark"
text="Check the downloads section of your browser for the installer, or find it where you save downloads on your machine."
closable
max-width="385"
/>
<br>
<br>
<v-alert …
```
=> fix(VAlert): reduce default close button margin

packages/vuetify/src/composables/display.ts
fixes #16825
Not sure the best way to test this but from @KaelWD's [comment](https://github.com/vuetifyjs/vuetify/issues/16825#issuecomment-1453810253), I assume this is the fix
=> fix(display): add hydrate checks for getPlatform

packages/vuetify/src/labs/VDataTable/VDataTable.sass
```vue
<template>
<v-app>
<v-container>
<v-data-table :headers="headers" :items="items" />
</v-container>
</v-app>
</template>
<script>
setup () {
const headers = ref([
{ title: 'One', key: 'one', sortable: true, align: 'start' },
{ title: 'Two', key: 'two', sortable: true, align: 'center' },
{ title: 'Three', key: 'three', sortable: true, align: 'end' },
])
{ one: 'One', two: 'Two', three: 'Three' },
])
return { headers, items }
},
}
</script>
```
=> fix(VDataTable): add css to align headers center

packages/vuetify/src/labs/VDataTable/VDataTable.sass, packages/vuetify/src/labs/VDataTable/VDataTableRow.tsx, packages/vuetify/src/labs/VDataTable/VDataTableRows.tsx
```vue
<template>
<v-app>
<v-container>
<v-data-table :headers="headers" :items="items">
<template #item.one="{ index }">
{{ index }}
</template>
</v-container>
</v-app>
</template>
<script>
setup () {
const headers = ref([
{ title: 'One', key: 'one', sortable: true, align: 'start' },
{ title: 'Two', key: 'two', sortable: true, align: 'center' },
{ title: 'Three', key: 'three', sortable: true, align: 'end' },
])
{ one: 'One', two: 'Two', three: 'Three' },
])
return { headers, items }
},
}
</script>
```
=> fix(VDataTable): missing index item[col] slots

packages/vuetify/src/composables/form.ts
```typescript
// src/composables/form.ts
interface FormField {
}
interface FormValidationResult {
valid: boolean
errors: FieldValidationResult[]
}
export function createForm (props: FormProps) {
const items = ref<FormField[]>([])
const errors = ref<FieldValidationResult[]>([])
}
```
There is an anti-pattern in `src/composables/form.ts`, where a `.d.ts` file is generated. The internal ref field is typed with an interface but not exported. However, the external field is exported using typeof and includes the interface. This is problematic and would result in a TypeScript error, even if not using vue.js.
For example, if you create a new TypeScript project with `"declaration": true` in tsconfig, and have two files: one file exports a function that uses an interface not exported in that file, …
=> refactor(form): export interfaces used in createForm()

packages/docs/src/pages/en/components/data-tables/basics.md
fixes typo in `v-data-tables` documentation.
```vue
```
=> docs(VDataTable): fix typo

packages/api-generator/src/locale/en/v-overlay.json
Added `scrim`, `persistent`, and `noClickAnimation` prop descriptions. 
Referenced: 
https://github.com/vuetifyjs/vuetify/issues/16580
https://v2.vuetifyjs.com/en/api/v-dialog/#props
n/a
=> docs(VOverlay): add missing api descriptions

packages/vuetify/src/components/VDialog/VDialog.tsx
This PR resolves the issue with VDialog accessibility. Instead of using the `role` attribute, `aria-role` was used.
=> fix(VDialog): replace `aria-role` with `role`

packages/docs/src/pages/en/features/aliasing.md
A minor tweak in the importing of components in `dev`resulting in slight performance benefit.
This only affects `dev` mode as in `prod` threeshaking will automatically optimize these kind of imports.
from:
```js
import { VBtn } from 'vuetify/components'
```
to:
```js
import { VBtn } from 'vuetify/components/VBtn'
```
=> docs(aliasing): update import code

packages/api-generator/src/locale/en/v-tab.json, packages/vuetify/src/components/VTabs/VTab.ts, packages/vuetify/src/components/VTabs/__tests__/VTabs.spec.ts
Potential solution..
Unfortunately we can't use `value` as prop name because it collides with an existing computed prop in the component that is tied to several levels of mixins, that in turn are used in multiple other components.
closes #10540
<details>
```vue
<template>
<v-card>
<v-tabs
v-model="tab"
@change="onChange"
background-color="primary"
dark
>
<v-tab
:key="item.tab"
:tab-value="item.tab"
>
{{ item.tab }}
</v-tab>
</v-tabs>
<v-tabs-items v-model="tab">
<v-tab-item
:key="item.tab"
:value="item.tab"
>
{{ item.tab }}
<v-card flat>
<v-card-text>{{ item.content }}</v-card-text>
</v-card>
</v-tab-item>
<pre>{{ tab }}</pre>
</v-card>
</template>
<script>
data () {
return {
tab: null, …
```
=> feat(VTab): add tabValue prop

packages/vuetify/src/util/globals.ts
`CSS.support` checkup now fails with some environments. I suggest adding an extra check on its existence similar to the way it's done in many other projects.
Specifically, I was checking it with `nuxt-vitest` (it uses `happy-dom`). 
The issue it produces is similar to that one https://github.com/wojtekmaj/react-fit/issues/2
This fix made earlier seems to be not enough
https://github.com/vuetifyjs/vuetify/commit/59370b0ebd7ad9029c9ec14ad0c580435af6b967
```vue
```
=> fix: check if CSS.supports exists

packages/docs/src/examples/v-img/complex-grid.vue, packages/docs/src/pages/en/components/images.md
Adding another use case for images in the docs (complex layout grid using responsve grid and flex-box)
=> docs(images): add complex-grid example

packages/api-generator/src/locale/en/v-tab.json
added prop descriptions for `fixed`, `sliderColor`, `hideSlider` and `direction`
resolves #16986
related to #13573
=> docs(v-tab): fix missing descriptions

packages/api-generator/src/locale/en/v-img.json, packages/docs/src/pages/en/components/images.md
This clarifies a point about `lazy-src` needing a fixed height in order to show the placeholder/lazy image.
=> docs(images.md): added lazy-src clarification

packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VField/VField.tsx
fixes #16925
fixes #16925
```vue
<template>
<v-app>
<v-main class="pa-8 w-50">
<v-card color="primary" class="d-flex flex-column w-100" title=":open-on-clear=default">
<v-autocomplete :items="items" hide-details="auto" v-model="item[0]" :clearable="true" label="autocomplete" />
<v-select :items="items" hide-details="auto" v-model="item[1]" :clearable="true" label="select" />
<v-combobox :items="items" hide-details="auto" v-model="item[2]" :clearable="true" label="combobox" />
</v-card>
<v-card color="success" class="d-flex flex-column w-100" title=":open-on-clear=true">
<v-autocomplete :items="items" hide-details="auto" v-model="item[3]" :clearable="true" label="autocomplete"
:open-on-clear="true" />
<v-select :items="items" hide-details="auto" v-model="item[4]" :clearable="true" …
```
=> fix(VField): stopPropagation mousedown event on clearable icon

packages/vuetify/src/composables/forwardRefs.ts
fixes #16035
<details>
```vue
<script setup>
const autocomplete = ref()
function focus () {
// autocomplete.value.focus()
console.log(autocomplete.value.focus())
}
</script>
<template>
<v-app>
<v-main>
ref="autocomplete"
:items="['California', 'Colorado', 'Florida', 'Georgia', 'Texas', 'Wyoming',
'Alaska', 'Arizona', 'Arkansas', 'Connecticut', 'Delaware', 'Hawaii',
'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey',
'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma',
'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', …
```
=> fix(forwardRefs): ref chain recursive search

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx
fixes #16153
This issue also happens to VComboBox.
Fixed VListItem to be re-rendered after search. 
```vue
<template>
<v-app>
<v-container>
<v-card class="pa-4 ma-8" width=400>
:items="items"
multiple
chips
closable-chips
:menu-props="{ maxHeight: 300 }"
</v-card>
<v-row>
<v-combobox
v-model="comboSelect"
:items="comboItems"
multiple
label="Select a favorite activity or create a new one"
></v-combobox>
</v-col>
</v-row>
</v-container>
</v-app>
</template>
<script setup>
"item-0",
"item-1",
"item-2",
"item-21",
"item-22",
"item-23",
];
const comboSelect =  ref(['Programming']);
const comboItems = [
'Programming',
'Design',
'Vue',
'Vuetify',
];
</script> …
```
=> fix(VAutocomplete,VCombobox): unselected items checked

packages/vuetify/src/labs/VDataTable/VDataTableRows.tsx
fixes #17067
```vue
<template>
<v-app>
<v-main>
<v-data-table
height="230px"
:items="_data"
show-expand
:expanded="expanded"
fixed-header
class="!tw-text-xs"
>
<template v-slot:item.serverType="{ item }">
<span> {{ item.raw.serverType }}</span>
<v-chip
size="x-small"
:color="getColor(item.raw.requestType)"
>
{{ item.raw.requestType }}
</v-chip>
</template>
<template v-slot:expanded-row="{ columns, item }">
<tr>
<td :colspan="columns.length">
Permission Groups:
<span class="tw-text-indigo-400">{{ item.raw.groups }}</span>
</td>
</tr>
</template>
</v-main>
</v-app>
</template>
const expanded = ref([]);
const _data = [
{
id: 1,
serverType: "Gerrit",
productline: "SmartPhone",
requestType: "department", …
```
=> fix(VDataTable): use DataTableItem interface for item slots

packages/vuetify/src/composables/proxiedModel.ts
`model` is relying on `isControlled` to propagate the dirty event. After https://github.com/vuejs/core/pull/5912, the dirty event will no longer be propagated if the new value of `isControlled` hasn't changed. This has caused some tests to fail.
=> fix: unreliable dependencies of `useProxiedModel()`

packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete.spec.cy.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx, packages/vuetify/src/components/VSelect/__tests__/VSelect.spec.cy.tsx, packages/vuetify/src/components/VTextField/VTextField.tsx
fixes #16055
fixes #7260
- Port #4853 to V3
```vue
<script setup>
import { ref } from 'vue' 
const items = ref(['Foo', 'Bar', 'Fizz', 'Buzz'])
</script>
<template>
<v-select
:items="items"
></v-select>
</template>
```
=> fix(VSelect): replicate html select hotkeys

packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.cy.tsx
fixes #17120
```vue
<template>
<v-app>
<v-main>
<v-combobox v-model="msg" class="pb-16" :items="itmes" />
</v-main>
</v-app>
</template>
<script setup>
const msg = ref(null)
const itmes = [...Array(40).keys()]
</script>
```
=> fix(VCombobox): allow falsy values in model

packages/docs/src/examples/v-data-table/misc-server-side-paginate-and-sort.vue, packages/docs/src/examples/v-data-table/prop-loading.vue, packages/docs/src/examples/v-data-table/server-search.vue, packages/docs/src/examples/v-data-table/server.vue, packages/docs/src/pages/en/components/data-tables/server-side-tables.md, packages/vuetify/src/labs/VDataTable/VDataTable.tsx, packages/vuetify/src/labs/VDataTable/VDataTableRows.tsx, packages/vuetify/src/labs/VDataTable/VDataTableServer.tsx, packages/vuetify/src/labs/VDataTable/VDataTableVirtual.tsx, packages/vuetify/src/labs/VDataTable/__tests__/VDataTableServer.spec.cy.tsx, packages/vuetify/src/labs/VDataTable/composables/options.ts
search prop is necessary so that we can signal table when update:options event is needed, so that we dont get double events, or none at all
closes #16959
```vue
<script lang="ts" setup>
import { computed, ref, watch } from 'vue'
{ title: 'id', key: 'id' },
{ title: 'title', key: 'title' },
]
const q = ref('')
const users = ref([])
const totalUsers = ref(0)
const isLoading = ref(false)
const options = ref<any>({})
const createUrl = opts => {
const url = 'https://jsonplaceholder.typicode.com/albums'
const params = new URLSearchParams()
const { page, itemsPerPage, q } = opts
const _start = (page - 1) * itemsPerPage
q && params.append('q', String(q))
params.append('_start', String(_start))
params.append('_limit', String(itemsPerPage))
return `${url}?${params.toString()}`
} …
```
=> fix(VDataTableServer): add search prop

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete.spec.cy.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.cy.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx, packages/vuetify/src/components/VSelect/__tests__/VSelect.spec.cy.tsx, packages/vuetify/src/components/VTextField/VTextField.tsx
Resolve the issue shown in video (select in open menu should keep text field stay focused)
```vue
<template>
<v-app>
<v-main>
<v-select
label="Select"
color="purple"
multiple
/>
label="Select"
color="purple"
multiple
/>
<v-combobox
color="purple"
label="Select"
multiple
/>
</v-main>
</v-app>
</template>
<script setup>
</script>
```
=> fix(VSelects): keep field focused when menu open

packages/vuetify/src/components/VOverlay/locationStrategies.ts
fixes #16628
Fixes issue with all elements that use VOverlay, opening in the incorrect position when in a RTL localization
```vue
<template>
<v-app>
<v-container>
<v-locale-provider rtl>
<v-main style="margin-top: 100px;">
RTL:
<VTooltip text="Tooltip" location="top">
<VBtn class="mx-3" v-bind="props">Tooltip</VBtn>
</template>
</VTooltip>
<VTooltip text="Tooltip" location="bottom">
<VBtn class="mx-3" v-bind="props">Tooltip</VBtn>
</template>
</VTooltip>
<VTooltip class="mx-3" text="Tooltip" location="start">
<VBtn class="mx-3" v-bind="props">Tooltip</VBtn>
</template>
</VTooltip>
<VTooltip class="mx-3" text="Tooltip" location="end">
<VBtn class="mx-3" …
```
=> fix(VOverlay): position on RTL

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx
Search text disappear after select an item in multiple typed VAutocomplete component.
I just removed the line that reset search value.
fixes #17136 
```vue
<template>
<div id="app">
v-model="values"
:items="items"
multiple
label="Default"
</v-app>
</div>
</template>
<script>
data: () => ({
values: 'foo',
}),
}
</script>
```
=> fix(VAutocomplete): search text when select item in multiple

packages/docs/src/pages/en/components/skeleton-loaders.md, packages/vuetify/src/labs/VSkeletonLoader/VSkeletonLoader.tsx
fixes #17107
VSkeletonLoader does not work when "table", "table-tbody", "table-row-divider", or "date-picker" is specified for the type because there is no "divider" in the type.
```vue
<template>
<v-app>
<v-container>
<template v-for="skeletonType in types" :key="skeletonType">
<v-chip class="mt-10" color="primary">{{ skeletonType }}</v-chip>
<v-skeleton-loader class="border mt-1" max-width="300" :type="skeletonType" />
</template>
</v-container>
</v-app>
</template>
<script setup>
// test all types
const types = ['actions', 'article', 'avatar', 'button', 'card', 'card-avatar', 'chip', 'date-picker', 'date-picker-options', 'date-picker-days', 'heading', 'image', 'list-item', 'list-item-avatar', 'list-item-two-line', 'list-item-avatar-two-line', 'list-item-three-line', …
```
=> fix(VSkeletonLoader): add missing divider type

packages/docs/src/pages/en/getting-started/upgrade-guide.md
Add a warning about missing components in Vuetify 3, that were available in Vuetify 2. This cost me a considerable amount of time.
```vue
```
=> docs(upgrade-guide): add info about missing components

packages/api-generator/src/locale/en/v-data-table.json
Changed the `dense` prop as it does not do anything. Instead I replaced it with `density` which does work on `v-data-table`, `v-data-table-server`, and `v-data-table-virtual`.
```json
"density": "Adjusts the vertical height of the table rows.",
```
=> docs(VDataTable): add density api description

packages/api-generator/src/locale/en/v-footer.json
Added description for the `app` prop in the `v-footer` component
The v-footer documentation has missing documentation for the `app` prop. This pull request adds a brief summary.
```vue
```
=> docs(VFooter): update app prop description

packages/vuetify/src/components/VTextField/VTextField.tsx, packages/vuetify/src/composables/focus.ts
fixes #17197
- `focused: boolean` so `onUpdate:focused` event type is also boolean
- should be a hiding issue which shows up after [strictly type EventProp events commit](https://github.com/vuetifyjs/vuetify/commit/d226a0f69c8b5955d7162e7692465dab76e9d366)
```vue
<template>
<v-app>
<v-main>
<v-text-field @update:focused="updateFocus" />
</v-main>
</v-app>
</template>
function updateFocus (focus: boolean) {
}
</script>
```
=> fix(types): change update:focused event type to boolean

packages/docs/src/pages/en/components/navigation-drawers.md
There is a caveat on the docs page for navbar that alerts dev that main contents are do not respond to the resizing of the navbar when `rail` and `expand-on-hover` are set. The warning suggests using `mini-variant.sync` to a data prop, however that:
1. Does not seem to work with the latest version of vuetify / vuejs (was mini-variant replaced by `rail`?)
2. It seems not consistent with 
https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/v-navigation-drawer/prop-mini-variant.vue#L6
What seems to work is:
```html
:rail="rail"
@mouseover="rail = false"
@mouseleave="rail = true">
```
and
```typescript
data() {
return {
rail: true
}
}
}
</script>
```
=> docs(VNavigationDrawer): add difference between v-model:rail and rail="true" props

packages/vuetify/src/composables/__tests__/__snapshots__/theme.spec.ts.snap, packages/vuetify/src/composables/theme.ts
Matched the opacity of the emphasis CSS variables to conform to the values stated in the documentation.
If this change is not wanted, the documentation should instead be updated to explain that there is no difference in opacity between the light and dark theme.
The [documentation](https://vuetifyjs.com/en/styles/text-and-typography/#opacity) states different opacity values for high, medium and disabled opacity text between light and dark mode. However, the theme only uses the values of the light theme. I've set the correct values as stated in the documentation for the dark theme (and the corresponding snapshot test). 
The PR that added these variables: https://github.com/vuetifyjs/vuetify/pull/13674/files#diff-53b5523de35fefbb957b3194ca376f52e49b1562b8715abbeec14437966fb0c6
```vue …
```
=> fix(theme): correct emphasis opacity in default dark theme

packages/vuetify/src/components/VAutocomplete/VAutocomplete.sass, packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx
Fixes #17291
```vue
<template>
<v-app>
<v-main>
v-model="friend"
color="blue-grey-lighten-2"
label="Select Without Multiple"
>
<template #selection="{ item }">
<div>
text:
<span>{{ item.title }}</span>
</div>
</template>
v-model="friend"
color="blue-grey-lighten-2"
label="Select Without Multiple"
chips
/>
v-model="friends"
color="blue-grey-lighten-2"
label="Select With Multiple"
:multiple="true"
>
<template #selection="{ item }">
<div>
text:
<span>{{ item.title }}</span>
</div>
</template>
</v-main>
</v-app>
</template>
<script setup>
const friend = ref()
const friends = ref()
const people = ['A', 'B', 'C']
</script>
```
=> fix(VAutocomplete): hide selection slot when focused

packages/vuetify/src/components/VChip/VChip.sass, packages/vuetify/src/components/VChip/VChip.tsx
fixes #16472
Ideally this would exist on `v-chip` all of the time but it causes a breaking change when using icons/avatars with the **start** or **end** prop for alignment.
```vue
<template>
<v-app>
<v-main>
<VCombobox
v-model="chips"
chips
multiple
clearable
closable-chips
clear-icon="mdi-close-circle-outline"
:items="items"
label="Your favorite hobbies"
prepend-icon="mdi-filter-variant"
/>
<v-card
max-width="250"
>
<v-row
align="center"
class="pa-6"
>
<span class="me-4">To</span>
<v-menu
v-model="menu"
location="top start"
origin="top start"
transition="scale-transition"
>
<v-chip
pill
v-bind="props"
link
>
<v-avatar start>
<v-img src="https://cdn.vuetifyjs.com/images/john.png" />
</v-avatar>
John Leider lorem ipsum
</v-chip>
</template> …
```
=> fix(VChip): overflow text in chip selections

packages/vuetify/src/composables/__tests__/group.spec.ts, packages/vuetify/src/composables/group.ts
fixes #17227
```vue
<template>
<v-app>
<div class="d-flex flex-column align-center bg-grey-lighten-4 pa-6">
<v-btn-toggle
v-model="toggle"
multiple
>
<v-btn  value="left">left</v-btn>
<v-btn  value="center">center</v-btn>
<v-btn  value="right">right</v-btn>
<v-btn  value="justify">just</v-btn>
<pre class="pt-2">{{ toggle }}</pre>
</div>
</v-app>
</template>
<script setup>
const toggle = ref([])
</script>
```
=> fix(group): respect selection order in v-model

packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.sass, packages/vuetify/src/components/VNavigationDrawer/__tests__/VNavigationDrawer.spec.cy.tsx
fixes #17367
fix `VNavigationDrawer` scrim position incorrect
```vue
<template>
<v-app>
<v-container>
<v-btn color="primary" @click.stop="visible = !visible">
Toggle
</v-btn>
<v-navigation-drawer v-model="visible" temporary>
<h1>Drawer</h1>
</v-container>
</v-app>
</template>
<script>
setup () {
const visible = ref(true)
return {
visible,
}
},
}
</script>
```
=> fix(VNavigationDrawer): correct scrim position

packages/vuetify/src/labs/VDataTable/types.ts
`DataTableHeader` type lacks several parameter types:
* `width` header parameter supports `string` type, which can be used with a percentage value. Adding the type resolves #17385
* This functionality is already supported, as both `width` and `minWidth` parameters of `style` call `convertToUnit` function: https://github.com/vuetifyjs/vuetify/blob/06815ef96240fc808388995e838ef43d7c63f344/packages/vuetify/src/labs/VDataTable/VDataTableHeaders.tsx#LL133C17-L133C17. 
* `align` header parameter supports `'center'` value, which correctly sets the center style to the row cells.
I have **one more request** for a discussion: there is an issue #16897 that should be still open, also referenced at #16680: please consider exporting the `DataTableHeader` type directly. (The `export type` in `types.ts` …
=> fix(VDataTable): add missing types

packages/vuetify/package.json
Fixes #17436
Reordered the default condition inside the package.json to be the last one. Vuetify-projects that use webpack will throw an error and won't compile otherwise.
Error thrown by webpack:
`Module not found: Error: Default condition should be last one Did you mean './vuetify'?"`
=> fix(package): reorder default exports condition

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx
fixes #17428 
```vue
<template>
<v-app>
<v-container>
<pre>{{ { c1, c2, a1, a2 } }}</pre>
<v-combobox v-model="c1" :items="items" placeholder="combobox single" />
<v-combobox v-model="c2" :items="items" multiple placeholder="combobox multiple" />
<v-autocomplete v-model="a1" :items="items" placeholder="autocomplete single" />
<v-autocomplete v-model="a2" :items="items" multiple placeholder="autocomplete multiple" />
</v-container>
</v-app>
</template>
<script setup>
const items = ['Gaming', 'Programming', 'Vue', 'Vuetify']
const c1 = ref()
const c2 = ref()
const a1 = ref()
const a2 = ref()
</script>
```
=> fix(VCombobox): show placeholder after clear input

packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete.spec.cy.tsx, packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.cy.tsx, packages/vuetify/src/components/VFileInput/__tests__/VFileInput.spec.cy.tsx, packages/vuetify/src/components/VSelect/__tests__/VSelect.spec.cy.tsx, packages/vuetify/src/components/VTextField/__tests__/VTextField.spec.cy.tsx
Problem in current percy snapshots:
Snapshot has everything and height increase from previous row push all following rows down. So only the first row makes sense but the remaining 90%ish doesn't. [demo link](https://percy.io/c458cb73/vuetify/builds/27716003/changed/1541889333?browser=chrome&browser_ids=38&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280)
Fixed height for each row
=> chore: fixed height rows in percy tests for field components

packages/vuetify/src/components/VResponsive/VResponsive.sass
fixes #17444
```vue
<template>
<v-app>
<v-container>
<v-parallax
src="https://cdn.vuetifyjs.com/images/backgrounds/vbanner.jpg"
>
<div class="d-flex flex-column fill-height justify-center align-center text-white">
<h1 class="text-h4 font-weight-thin mb-4">
Vuetify
</h1>
<h4 class="subheading">
Build your application today!
</h4>
</div>
</v-parallax>
</v-container>
</v-app>
</template>
```
=> fix(VParallax): show v-parallax content over image

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx
fixes #17526
```vue
<template>
<v-row>
<v-col>
:items="items"
hide-details
readonly
variant="solo-filled"
/>
<v-combobox
:items="items"
hide-details
readonly
variant="solo-filled"
/>
</v-col>
</v-row>
</template>
<script>
data: () => ({
}),
}
</script>
```
=> fix(VCombobox): prevent menu opening when readonly

packages/vuetify/src/labs/VDatePicker/VDatePickerMonth.tsx, packages/vuetify/src/labs/date/date.ts
Fix following eslint errors.
labs/date/date.tx:  
`More than 1 blank line not allowed.`  
labs/VDatePicker/VDatePickerMonth.tsx:  
`Imports should be sorted
../date/date should appear before ../VDateInput/composables`
These are causing the CI for #17578 to fail.
https://github.com/vuetifyjs/vuetify/actions/runs/5229429506/jobs/9442432104?pr=17578
``` vue
Nothing
```
=> chore: resolve linting errors

packages/docs/src/examples/v-img/slot-error.vue, packages/docs/src/pages/en/components/images.md
Added information about the v-img error slot and included a common use-case for a fallback image if the source image is cannot be loaded.
=> docs: add v-img error slot

packages/docs/src/examples/v-form/usage.vue
Small typo in the example code in the docs (https://vuetifyjs.com/en/components/forms/#usage)
```vue
```
=> docs(VForm): fix typo in the example code

packages/docs/src/examples/v-date-picker/misc-birthday.vue
Avoid using deprecated method to substring
Updating the example so that it avoids using deprecated method to substring
=> docs(VDatePicker): use `substring` instead of `substr`in misc-birthday.vue

packages/vuetify/src/components/VAutocomplete/VAutocomplete.sass, packages/vuetify/src/components/VCombobox/VCombobox.sass, packages/vuetify/src/components/VSelect/VSelect.sass, packages/vuetify/src/components/VTextField/VTextField.sass, packages/vuetify/src/components/VTextField/VTextField.tsx
fixes #17604
Input heights in select components are the same as when having chips (always include chip margin top/bottom). Therefore, input alignment should be consistent with chips.
This has been implemented in VCombobox and VAutocomplete but missed in VSelect
```vue
<template>
<v-app>
<v-container style="width: 250px">
<v-text-field placeholder="Hello" variant="outlined" density="compact" />
<v-select 
placeholder="Hello" variant="outlined" density="compact" />
<v-select
chips
placeholder="Hello"
/> …
```
=> fix(VSelect): Always align the input with chips

packages/vuetify/src/labs/VDataTable/__tests__/sort.spec.ts, packages/vuetify/src/labs/VDataTable/composables/sort.ts, packages/vuetify/src/util/__tests__/helpers.spec.ts, packages/vuetify/src/util/helpers.ts
fixes #17563 
```vue
<template>
<v-data-table
</template>
<script>
data() {
return {
itemsPerPage: 10,
headers: [
{
key: 'name',
},
{ title: 'Calories', align: 'end', key: 'calories' },
{ title: 'Fat (g)', align: 'end', key: 'fat' },
{ title: 'Carbs (g)', align: 'end', key: 'carbs' },
{ title: 'Protein (g)', align: 'end', key: 'protein' },
{ title: 'Iron (%)', align: 'end', key: 'iron' },
],
desserts: [
{
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1',
},
{
calories: 375,
fat: 0.0,
carbs: 94,
protein: 0.0,
iron: '0',
},
{ …
```
=> fix(VDataTable): fix sort table with nullable column

packages/vuetify/src/iconsets/fa.ts, packages/vuetify/src/iconsets/fa4.ts
Update fontawesome sort icons to match mdi icon defaults. 
**References:**
MDI:
https://pictogrammers.com/library/mdi/icon/arrow-up/
https://pictogrammers.com/library/mdi/icon/arrow-down/
Fontawesome:
v5
https://fontawesome.com/v5/icons/arrow-down?f=classic&s=solid
https://fontawesome.com/v5/icons/arrow-up?f=classic&s=solid
v4
https://fontawesome.com/v4/icon/arrow-down
https://fontawesome.com/v4/icon/arrow-up
v5
```typescript
const aliases: IconAliases = {
collapse: 'fas fa-chevron-up',
complete: 'fas fa-check',
cancel: 'fas fa-times-circle',
close: 'fas fa-times',
delete: 'fas fa-times-circle', // delete (e.g. v-chip close)
clear: 'fas fa-times-circle', // delete (e.g. v-chip close)
success: 'fas fa-check-circle',
info: 'fas fa-info-circle',
warning: 'fas fa-exclamation',
error: 'fas …
```
=> refactor: update fontawesome sort icons to match mdi icons defaults

packages/vuetify/src/components/VBtn/VBtn.sass
fixes #17414 
```vue
<template>
<v-app>
<v-main>
<v-card>
Rate
<v-spacer />
<v-btn-toggle divided variant="outlined">
<v-btn>+</v-btn>
<v-btn>-</v-btn>
<v-btn>+</v-btn>
<v-btn>-</v-btn>
</v-card>
</v-main>
</v-app>
</template>
<script>
setup () {
return {
//
}
},
}
</script>
```
=> fix(VBtnToggle): del margin for BtnToggle in card

packages/vuetify/src/components/VSlider/VSliderThumb.tsx
VSliderThumb was missed in bc0436d
fixes #16586
=> fix(VSliderThumb): add rtl class

packages/vuetify/src/components/VAutocomplete/VAutocomplete.sass, packages/vuetify/src/components/VAutocomplete/_variables.scss, packages/vuetify/src/components/VCombobox/VCombobox.sass, packages/vuetify/src/components/VCombobox/_variables.scss, packages/vuetify/src/components/VSelect/VSelect.sass
fixes #17627
In addition, VAutocomplete/VCombobx focused input should behaves the same as [v2](https://codepen.io/yuchaosydney/pen/eYQgQpL?editors=101)
```vue
<template>
<v-app>
<div style="width: 200px">
:items="['Hello i am a very very very very veeeeeery long text', 'bar', 'fizz', 'buzz']"
multiple
clearable
/>
<v-select
:items="['Hello i am a very very very very veeeeeery long text', 'bar', 'fizz', 'buzz']"
multiple
clearable
/>
<v-combobox
:items="['Hello i am a very very very very veeeeeery long text', 'bar', 'fizz', 'buzz']"
multiple
clearable
/>
</div>
</v-app>
</template>
```
=> fix(VSelect, VCombobox, VAutocomplete): truncate selection text regardless of singline-line

packages/vuetify/src/labs/VInfiniteScroll/VInfiniteScroll.tsx, packages/vuetify/src/labs/VInfiniteScroll/__tests__/VInfiniteScroll.spec.cy.tsx
fixes #17358
```vue
<template>
<v-app>
<v-main>
<v-list>
<v-infinite-scroll mode="intersect" @load="load">
<v-list-item v-for="(item, index) in items" :key="item">
Item #{{ item }}
</v-list-item>
<template v-slot:empty>
<v-alert type="warning">No more items!</v-alert>
</template>
<template v-slot:error="{ props }">
<v-alert type="error">
<div class="d-flex justify-space-between align-center">
Something went wrong...
<v-btn
color="white"
size="small"
v-bind="props"
>
Retry
</v-btn>
</div>
</v-alert>
</template>
</v-infinite-scroll>
</v-list>
</v-main>
</v-app>
</template>
<script setup>
const items = ref(Array.from({ length: 3 }, (k, v) => v + 1))
let count = 0
const load = async ({ done }) => { …
```
=> fix(VInfiniteScroll): keep triggering loading logic until isInterseting becomes false

packages/vuetify/src/util/injectSelf.ts
TypeScript 5.1 has improved checking for noImplicitReturns, and this function indeed has an implicit return of `undefined` off the bottom end.
=> chore(injectSelf): return from all paths

packages/vuetify/src/components/VFooter/VFooter.tsx
Pass missing height style to the component
fixes #17370 
```vue
<template>
<v-app>
<v-main>
<v-footer color="red" height="100px" />
</v-main>
</v-app>
</template>
```
=> fix(VFooter): pass missing height style

packages/vuetify/src/components/VField/VField.sass
fixes #17380
```vue
<template>
<v-app>
<v-container>
<v-locale-provider rtl>
<v-text-field v-model="msg" variant="outlined" rounded="lg" />
</v-locale-provider>
<v-text-field v-model="msg" variant="outlined" rounded="lg" />
</v-container>
</v-app>
</template>
<script setup>
</script>
```
=> fix(VTextField): inherit outlined border radius

packages/vuetify/src/components/VPagination/VPagination.ts
Added two props, one for text and other for background, which allows the navigation buttons being colored
Useful for:
- Color the navigation buttons without need to overwrite the Vuetify classes
Right now to color the navigation buttons you need to overwrite the CSS classes, having a prop to change the color is useful when you have dynamic colored navigation, and allow the developer to write less code instead.
It was tested visually only.
<details>
```vue
<template>
<v-container>
<v-pagination
v-model="page"
:length="5"
navigation-color="red"
navigation-text-color="white"
/>
</v-container>
</template>
<script>
data: () => ({
page: 0,
}),
}
</script>
```
</details>
=> feat(VPagination): add props for coloring navigation buttons

packages/vuetify/src/components/VSystemBar/VSystemBar.sass
fixes #14975
VIcon was not centered in VBtn in VSystemBar.
visually
<details>
```vue
<template>
<v-container>
<v-system-bar
dark
>
<v-btn icon class="red">
<v-icon>mdi-wifi-strength-4</v-icon>
</v-btn>
</v-system-bar>
</v-container>
</template>
<script>
data: () => ({
drawer: true,
}),
}
</script>
```
</details>
=> fix(VIcon): center button icon in system bar

packages/api-generator/src/locale/en/v-data-table.json, packages/vuetify/src/components/VDataTable/VDataTable.ts, packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts, packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap, packages/vuetify/types/index.d.ts
Closes #11600
I pretty much just restored the code from before #11575 as "union", keeping the current behaviour as "intersection"
=> feat(VDataTable): backport filterMode prop from v3

packages/vuetify/src/components/VIcon/VIcon.sass
fixes #17693
Not every icon is a square shape
```vue
<template>
<div>
<v-autocomplete :items="items" density="compact" label="Compact" />
<v-select
:items="items"
density="comfortable"
label="Comfortable"
></v-select>
<v-select :items="items" label="Default"></v-select>
</div>
</template>
<script>
data: () => ({
items: ['Foo', 'Bar', 'Fizz', 'Buzz'],
}),
}
</script>
```
=> fix(VIcon): enforce to display icon both vertically and horizontally in container

packages/vuetify/src/labs/VDataTable/composables/headers.ts
fixes #17672
column key is string type, nullish values should be converted to empty string
```vue
<template>
<v-data-table
/>
</template>
data () {
return {
itemsPerPage: 5,
headers: [
{
key: null,
},
{ title: 'Calories', align: 'end', key: 'calories' },
],
desserts: [
{
calories: 159,
},
{
calories: 375,
},
{
name: 'KitKat',
calories: 518,
},
{
calories: 262,
},
{
name: 'Gingerbread',
calories: 356,
},
{
calories: 237,
},
{
name: 'Lollipop',
calories: 392,
},
{
calories: …
```
=> fix(headers): enforce nullish column key to empty string

packages/vuetify/src/components/VBtn/VBtn.tsx
- When clicking on a `v-tab` with `href`/`to` property that opens in a new window/tab (via either `meta + click` or `target='__blank'`), the slider moves to the clicked tab rather than staying on the currently active tab.
- Since `v-tab` uses `v-btn` and `v-btn` renders as an `a` tag if `href` or `to` is passed to it, we can check when the button is being clicked if a link will open in a new window/tab and return early before the `group.toggle` is called to set that button as active and move the slider to it.
Here is a repro to show the issue:
https://github.com/BenGu3/vuetify-btn-link-bug
```vue
<script lang="ts" setup>
enum Option {
One = 'one',
Two = 'two',
Three = 'three',
Four = 'four',
}
const activeTab = ref<Option>()
</script>
<template>
<div …
```
=> fix(VBtn): don't toggle group if button should open new tab/window

packages/vuetify/src/components/VField/VField.sass
fixes #17740
`min-width: 0` prevents input tag overflows its container (which is a flex child)
```vue
<template>
<v-row>
<v-list-subheader>Suffix for weight</v-list-subheader>
</v-col>
<v-col cols="8">
<v-text-field
label="Weight"
model-value="28.00"
type="number"
suffix="litres"
/>
</v-col>
</v-row>
</v-container>
</template>
```
=> fix(VField): prevent input dom overflow v-field__input

packages/api-generator/src/locale/en/VNavigationDrawer.json
Added description of `rail` property of `v-navigation-drawer`
```vue
```
=> docs(VNavigationDrawer): update rail prop description

packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.cy.tsx
In filter items test of VCombobox component, in case of no result it checks input length instead of v-list-item.
I fixed this test case.
```vue
```
=> test(VCombobox): check .v-list-item length in filter items test

packages/vuetify/src/components/VOverlay/locationStrategies.ts
close #17314 
- The issue affect the overlay, such as tooltips, menus, etc...
- The issue is very specific, when switching locale, after opening a overlay (The overlay would still have a `left` or `right` attribute) thus cause it to not be displayed correctly after switching the language.
- A refresh fixes the issue, since the overlay no longer would have a `right` or `left` attribute in its styling.
- This should fix the issue without calling a second `updatelocation` call
```vue
<template>
<v-app>
<v-container>
<v-locale-provider :locale="toggle ? 'ar' : 'en'">
<v-switch v-model="toggle" label="Toggle Locale" />
<v-main style="margin-top: 100px;">
{{ toggle ? 'RTL:' : 'LTR:' }}
<VTooltip text="Tooltip" location="top">
<VBtn class="mx-3" …
```
=> fix(VOverlay): position on LTR/RTL after locale switch

packages/vuetify/src/components/VColorPicker/VColorPickerEdit.sass, packages/vuetify/src/components/VColorPicker/VColorPickerPreview.sass, packages/vuetify/src/components/VColorPicker/_variables.scss
fixes #16930
```vue
<script>
data() {
return {
slider: 100,
}
},
}
</script>
<template>
<div id="app">
<v-app>
<v-sheet class="pa-5">
<v-color-picker width="265" canvas-height="120" :hide-inputs="false">
</v-color-picker>
</v-sheet>
<v-sheet class="pa-5">
<v-color-picker width="265" canvas-height="120" :hide-inputs="true">
</v-color-picker>
</v-sheet>
</v-app>
</div>
</template>
```
=> fix(VColorPicker): remove extra margin with hide-input

packages/vuetify/src/labs/date/adapters/vuetify.ts
Fixes #17613
The date picker passes a standard date format like `2023-6-20` to the date utility method. Since it's a standard format, `Date.parse()` treats it as UTC time. If you're several time zones away this can result in the date picker selecting an incorrect date (one day before or, presumably, after). This update checks if the date format is that kind of standard date format and completes the date string to include GMT offset before parsing.
If the date is non-standard, it is passed through as-is, resulting in the current behavior. For example, the VDatePicker `watch(inputModel)` handler passes a value like `6/20/2023` instead.
```vue
<template>
<v-container>
Date: {{ myDate || 'None yet' }}
<v-date-picker
v-model="myDate"
/>
</v-container>
</template>
<script> …
```
=> fix(date): reconstruct date value to local tz

packages/vuetify/src/components/VTabs/_variables.scss
Resolves regression introdued in [#8253c7e](https://github.com/vuetifyjs/vuetify/commit/8253c7e6774345cc1cc85e35846403568f822aaa) where `uppercase` text transform should not be quoted for property to be applited correctly.
=> fix(VTabs): remove quotes from text-transform

packages/vuetify/src/components/VFileInput/VFileInput.tsx
readonly prop did not work in VFileInput component. I solve this issue by checking readonly prop in events like onFocus, onChange & onClear.
resolves #17851 
```vue
<template>
<v-app>
<v-container>
<v-file-input
accept="image/*" 
label="File input"
>
</v-file-input>
</v-container>
</v-app>
</template>
```
=> fix(VFileInput): readonly prop not working

packages/vuetify/src/components/VTable/VTable.sass
Position sticky should apply to all elements in tbody & thead
Issue
https://github.com/vuetifyjs/vuetify/issues/17806
```vue
<template>
<v-table fixed-header height="500">
<thead>
<tr>
<th colspan="2">Header of col 1 and 2</th>
</tr>
<tr>
<th>Col 1</th>
<th>Col 2</th>
</tr>
</thead>
<tbody>
<tr v-for="(item, index) in data" :key="index">
<td>{{ index }} in col 1</td>
<td>{{ index }} in col 2</td>
</tr>
</tbody>
</v-table>
</template>
const data = ref(Array(100).fill(null));
</script>
```
=> fix(VTable): fixed-header with multiple tr headers

packages/docs/src/pages/en/getting-started/upgrade-guide.md
Some of the components listed in the upgrade guide are now available, so we should remove them from the list
=> docs(upgrade-guide): remove components that are now available

packages/vuetify/src/components/VChip/VChip.tsx
The issue was missing 's' in v-slots.
fixes #17893 
```vue
<template>
<v-app>
<v-container>
<v-text-field v-model="msg" />
<v-chip-group
filter
column
multiple
mandatory
variant="text"
v-model="group"
>
<v-chip
v-for="category of array"
:key="'category-filter-' + category"
:value="category"
size="x-large"
rounded="lg"
>
<template #filter>
<span>X</span>
</template>
{{ category }}
</v-chip>
</v-container>
</v-app>
</template>
<script setup>
const group = ref(['one'])
const array = ['one', 'two', 'three', 'four'];
</script>
```
=> fix(VChip): fix v-chip filter slots

packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.tsx
fixes #17890
Provide eager prop to VExpansionPanelText from VExpansionPanel via provideDefaults.
```vue
<template>
<v-app>
<v-container>
<VExpansionPanels>
<VExpansionPanel title="Panel" eager>
<VExpansionPanelText>Text</VExpansionPanelText>
</VExpansionPanel>
</VExpansionPanels>
</v-container>
</v-app>
</template>
```
=> fix(VExpansionPanel): provide eager prop via defaults

packages/vuetify/package.json, packages/vuetify/src/labs/date/adapters/__tests__/vuetify.spec.ts, packages/vuetify/src/labs/date/adapters/vuetify.ts, yarn.lock
I was still having issues with date picker selecting incorrect date after https://github.com/vuetifyjs/vuetify/pull/17721. This _should_ work, but Date is a pain so who knows. @abea please check if I haven't broken anything.
I feel like we're going to regret using Date instead of plain strings :) 
Should fix https://github.com/vuetifyjs/vuetify/issues/17874
```vue
<template>
<v-app>
<v-container>
<v-date-picker v-model="selectedDate" hide-actions />
{{ selectedDate }}
</v-container>
</v-app>
</template>
<script setup>
const selectedDate = ref(new Date(2023, 0, 1))
</script>
```
=> fix(date): parse string dates in local time zone

packages/vuetify/src/labs/VInfiniteScroll/VInfiniteScroll.tsx
fixes #17583
When `margin: 0`, `IntersectionObserver` becomes closest scrollable div, then it keep loading items forever as intersectionRef is always intersecting scrollable div
[reproduction link](https://play.vuetifyjs.com/#eNqlVMtu2zAQ/JWterCMmlICt4caTpCgpxxaFE3RS5QDI61i1hJJkJQCw9C/d0nJlWynQIDexH3M7OxDD/voVuukbTBaRWubG6EdWHSNhorL56sscjaLrjMJIGqtjIM9KPlVNdJhsQCD5QJeuMs30EFpVA0zgppl0ifkSloHwmFt72teVXcyN1ijdHDlE+NbY/gu8VnxHiqUz26zgiV0C4i3C2jncHUNLXyAy/n8GO47mi+EF0AHrCWFjEGV4sUZJbc7mQNRFUoidAF+73PAC/4palSNi+OpnUSfV5+0vGow0Y3dxIcwgCRJJnpGO1DDDtpOa++RSPA0/Fj7v/m5i9nl3LdnzA59Gj4On15tPFPb2eCk9l5+urgIry6T67QfOo2YHsSmK+4wDHzdMq51+AwP6q3jQqIZTGQsROvbT2tSKvUDS1qVdUrGMeIdY/BNQc3Ns5CgjdIJwK87WQpJ2u5zo2iG1H8LjUULrcCXsGbcglHKAVb9/BgbMVsmhnxGxRPA2IFaFUjVCFpPYzF3WTT6Vn0R5L6Ymm/8tpDxfGnGqL/cgb0S1jE/GWhZqQ …
=> fix(VInfiniteScroll): always use viewpoint as IntersectionObserver root

packages/vuetify/src/components/VRating/VRating.tsx
Add missing `aria-label` to `VRatingItem` button. Fixes #17903 
```vue
<template>
<v-rating v-model="rating" />
</template>
<script setup>
const rating = ref(5)
</script>
```
=> fix(VRatingItem): add missing aria label

packages/vuetify/src/locale/ro.ts
Add `locale/ro.ts` missing translations. Fixes #17905 
```vue
<template>
<v-app>
<v-container>
<v-date-picker></v-date-picker>
</v-container>
</v-app>
</template>
```
=> fix: add locale/ro missing translations

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete.spec.cy.tsx
fixes #17910
- "tab" key shouldn't be related to `isPristine` for both VCombobox and VAutocomplete
- It makes sense to set `VCombobox` to pristine when pressing "Enter" & "Escape" keys as input value will become a concrete value and existing select items are still available to be selected 
- But for `VAutocomplete`,  "Escape" closes the menu which sets it to pristine, "Enter" shouldn't impact its `isPristine`
```vue
<template>
<v-card>
<v-row>
:items="items"
autoSelectFirst
label="Default"
</v-col>
<v-combobox
multiple
:items="items"
label="Default"
></v-combobox>
</v-col>
</v-row>
</v-container>
</v-card>
</template>
<script>
data: () => ({ …
```
=> fix(VAutocomplete): stop forcing to be pristine when pressing enter, escpe and tab

packages/vuetify/src/components/VTable/VTable.sass
Extra patch for https://github.com/vuetifyjs/vuetify/pull/17821/files
```vue
<template>
<v-table fixed-header height="500">
<thead>
<tr>
<th colspan="2">Header of col 1 and 2</th>
</tr>
<tr>
<th>Col 1</th>
<th>Col 2</th>
</tr>
</thead>
<tbody>
<tr v-for="(item, index) in data" :key="index">
<td>
</td>
<td>{{ index }} in col 2</td>
</tr>
</tbody>
</v-table>
</template>
const data = ref(Array(100).fill(null));
</script>
```
=> fix(VTable) set z-index to fixed header and footer elements

packages/vuetify/src/composables/theme.ts
These changes fix #17917 and #16156. Watch should only be used on client side because they cannot be automatically unwatched by vue since the watch is being called outside of the vue context. My performance testing showed that these changes finally fix the leaking problem.
=> fix(theme): only apply head watchers on client

packages/docs/src/pages/en/components/skeleton-loaders.md
According to documentation we can use type="card-header" but this is not true, because we have type "header".
https://vuetifyjs.com/en/components/skeleton-loaders/
This PR fix incorrect documentation.
This issue can be related but I am not sure
https://github.com/vuetifyjs/vuetify/issues/17156
```vue
```
=> docs(VSkeletonLoaders) In docs we use not existing type card-header

packages/vuetify/src/labs/VOtpInput/VOtpInput.sass, packages/vuetify/src/labs/VOtpInput/VOtpInput.tsx
reference: https://discord.com/channels/340160225338195969/660898563139567625/1136629895330533406
<details>
```vue
<template>
<v-app>
<form id="form" ref="form">
<v-otp-input v-model="model" name="otp" @input="onInput" />
</form>
</div>
</v-app>
</template>
<script setup>
const form = ref()
const model = ref('')
function onInput () {
const news = new FormData(form.value)
console.log(news.get('otp'))
}
</script>
```
</details>
=> fix(VOtpInput): form data support

packages/vuetify/src/components/VList/VListItem.tsx
`VListItem` anchor is missing the `title` prop. Fixes: https://github.com/vuetifyjs/vuetify/issues/17908
```vue
<template>
<v-app>
<v-container>
<v-card>
<v-list>
<v-list-item
:key="index"
:title="item.title"
:href="item.href"
/>
</v-list>
</v-card>
</v-container>
</v-app>
</template>
<script setup>
{
title: 'Vuetify',
href: 'https://vuetifyjs.com/en/',
},
{
title: 'Vue',
href: 'https://vuejs.org/',
},
])
</script>
```
=> fix(VListItem): add anchor title

packages/vuetify/src/labs/VDateInput/composables.ts, packages/vuetify/src/labs/VDatePicker/VDatePicker.tsx, packages/vuetify/src/labs/VDatePicker/__tests__/VDatePicker.spec.cy.tsx, packages/vuetify/src/labs/VDatePicker/composables.ts
closes https://github.com/vuetifyjs/vuetify/issues/17867, closes https://github.com/vuetifyjs/vuetify/issues/17872
```vue
<template>
<v-app>
<v-container>
<v-date-picker v-model="selectedDate" />
<v-date-picker v-model="selectedDate" hide-actions />
</v-container>
</v-app>
</template>
<script setup>
import { ref, watch } from 'vue'
const selectedDate = ref(new Date())
watch(
() => selectedDate.value,
newValue => {
console.log(`selectedDate changed to: ${newValue}`)
}
)
</script>
```
=> fix(VDatePicker): recursive update when using hide-actions

packages/docs/src/components/promoted/Base.vue, packages/docs/src/components/promoted/Carbon.vue
This PR loads Optimize ad tag as the fallback when Carbon is not available. There is no way to test the function locally because the domain has to be approved to load ads from demand partners, however I have made sure that the viewport is being set for each ad format.
- 300 × 250 banner if the viewport is less than 640px
- 728 × 90 banner if the viewport size is greater than 640px
=> docs: load optimize ad tag as carbon fallback

packages/vuetify/src/components/VSlider/VSlider.tsx
fixes #18043
```vue
<template>
<v-slider v-model="v" class="mt-8" thumb-label>
<template #thumb-label="{modelValue}">
{{ modelValue.toFixed(1) }}
</template>
<template #tick-label="{tick, index}">
{{ tick }} {{ index }}
</template>
</v-slider>
</template>
const v = ref(1)
</script>
```
=> fix(VSlider): correct thumb-label and tick label slot types

packages/vuetify/dev/App.vue, packages/vuetify/src/composables/directiveComponent.ts, packages/vuetify/src/globals.d.ts
The useDirectiveComponent directive is a powerful utility that allows you to render Vue components dynamically and mount them to DOM elements using directives. It simplifies the process of creating and managing dynamic components in your Vue applications.
```vue
<template>
<v-btn v-tooltip-directive="{ text: 'This is dynamic tooltip' }">Hello</v-btn>
</template>
<script setup>
import { useDirectiveComponent } from "vuetify/composables/directiveComponent";
const vTooltipDirective = useDirectiveComponent('VTooltip', { activator: 'parent' });
</script>
```
=> feat(directiveComponent): create new composable

packages/docs/src/pages/en/features/display-and-platform.md, packages/vuetify/src/components/VBanner/VBanner.tsx, packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.tsx, packages/vuetify/src/components/VSlideGroup/VSlideGroup.tsx, packages/vuetify/src/composables/__tests__/display.spec.cy.tsx, packages/vuetify/src/composables/__tests__/display.spec.ts, packages/vuetify/src/composables/display.ts
resolves #15381
<details>
```vue
<template>
<v-app>
<v-navigation-drawer mobile-breakpoint="xl" color="purple" />
<v-navigation-drawer location="end" color="primary" />
</v-app>
</template>
<script setup>
import { useDisplay } from '../src/composables/display'
const { mobile, isLocalMobile, displayClasses } = useDisplay({
mobileBreakpoint: 2156,
}, 'v-my-class')
console.log(mobile, isLocalMobile)
console.log(displayClasses.value)
</script>
```
</details>
=> feat(display): add local mobile-breakpoint support

packages/vuetify/src/locale/no.ts
Just a minor correction on `dateRangeInput.divider`
fixes #17988
=> fix(locale): update Norwegian dateRangeInput.divider placeholder translation

packages/vuetify/src/components/VTimeline/VTimeline.sass
fixes #18008
```vue
<template>
<v-app>
<v-container>
<v-timeline direction="vertical" side="end">
<v-timeline-item hide-dot>
<div>
<div class="text-h6">Content title</div>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua.
</p>
</div>
</v-timeline>
</v-container>
</v-app>
</template>
<script>
setup () {
return {
//
}
},
}
</script>
```
=> fix(VTimeline): vertical divider overlapping

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx
fixes #18050
Fixes a problem with the VAutocomplete component when both the auto-select-first and hide-selected props are set to true.  Hitting enter twice on a single search value that matches more than one item in the suggest list toggles the selected state of the first original item in the list, instead of adding additional item selections.  See reproduction here for more details:
https://play.vuetifyjs.com/#eNqlU8Fu2zAM/RVCl3RAbKNNdwnaocPWSzFgBbZb3YNiM7VWWxIk2m1R5N9HSXHjJIcF2MGA9fjIRz5RD+/iq7X50KNYiivCzraS8EupAa6GTFobf+OhMpqk0ui2UGL0ZCrDWUg4wgBD1pka2+tSeGyxIqzv0XmjS7HjLBWreaZYNJw+DXV9SypgH0iQyVKtbK2cp12oUTVuQ1jv4KpR1o/HXcfFfsvjdAzvjxeJcfqrYuIKH33llCXwSH0yR3XWOIJ3cLiGDayd6WDGhs4CnRsx2hOkIeEaHmZ3ptHwq1PUzOaQTt8Nzh6n9H3bOI1rn+m+bT8lVlHAeQ7fWlU9g9JkgBpMJk0vg1kXOfx+swiluDPJYgYXOdw79J7RW03oS …
=> fix(VAutocomplete): make hide-selected work with auto-select-first

packages/vuetify/src/components/VField/VField.sass, packages/vuetify/src/components/VField/_variables.scss
fixes #17838
```vue
<template>
<v-app>
<v-container>
<v-text-field
prepend-inner-icon="$vuetify"
rounded
/>
<v-text-field
prepend-inner-icon="$vuetify"
density="comfortable"
rounded
/>
<v-text-field
prepend-inner-icon="$vuetify"
rounded
/>
</v-container>
</v-app>
</template>
<script setup>
</script>
```
=> fix(VField): correctly calculate outline__start width

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx
fixes #17881
implements the v2 functionality of scrolling to the selected value by setting `menuProps="auto"`. ~~Since this doesn't go through VMenu, prop was renamed to `autoScroll`.~~
Currently, if a user needs to select a new value in the middle of a long list, the dropdown always resets to the top of the list, even if the new value is only just after the existing value. This change takes advantage of the virtual scrolling added to VSelect to quickly scroll to the current location.
```vue
<template>
<v-app>
<v-container>
<v-select v-model="selected2" label="Short Select" :items="[1, 2, 3]" />
<v-select v-model="selected3" label="Value not in items" :items="[1, 2, 3]" />
<v-select v-model="selected" label="Longer Select" :items="items" />
<v-autocomplete v-model="selected" …
```
=> fix(VSelect): auto scroll to selected value

packages/api-generator/src/locale/en/VNavigationDrawer.json
Make documentation description message for `disableResizeWatcher` more coherent with other messages such as `disableRouteWatcher`
See : https://vuetifyjs.com/en/api/v-navigation-drawer/
=> docs(VNavigationDrawer): update prop description

packages/docs/src/pages/en/components/avatars.md
In the docs of [V-Avatar](https://vuetifyjs.com/en/components/avatars/#profile-card), it mentioned we can use `tile` prop to control the border radius of avatar, but in the example code it gives, using `rounded="0"`。and we tried to use `tile` prop in playground, seems it has no effect. 
So I change the description of [V-Avatar](https://vuetifyjs.com/en/components/avatars/), replace all the text about `tile` with `rounded="0"`
=> docs(VAvatar): update page content

packages/docs/src/pages/en/components/autocompletes.md
Fixes docs for VAutocomplete refering to non-existing prop `filter`, instead the prop is called `custom-filter`.
=> docs(VAutocomplete): prop for filtering is "custom-filter"

README.md
Branch `next` does not exist anymore on the `vuetify-loader` repository
=> docs: fix vuetify-loader link in README

README.md
Fix `vuetify-loader` npm link and badge in README
=> docs: fix vuetify-loader npm link

packages/docs/src/pages/en/labs/introduction.md
This PR will fix the broken link from for VOtp on the lads introduction page
This change is required because it sends users to a 404 page when clicked
=> docs(VOtp): fix broken link to api

packages/vuetify/src/components/VField/VField.sass
fixes #18146
Approach in v2:
```vue
<template>
<v-app>
<v-container>
v-model:search.trim="modelSearch"
placeholder="good"
hide-no-data
/>
v-model:search.trim="modelSearch"
placeholder="bad"
:loading="true"
hide-no-data
/>
<v-text-field
v-model:search.trim="modelSearch"
placeholder="bad"
:loading="true"
hide-no-data
/>
class="fixed"
placeholder="fixed"
v-model:search.trim="modelSearch"
hide-no-data
/>
</v-container>
</v-app>
</template>
<script setup>
import { ref, watch } from 'vue'
const model = ref()
const modelSearch = ref('')
const loading = ref(false)
const items = ref([])
watch(modelSearch, async () => {
loading.value = true
await new …
```
=> fix(VField): make loader visible

packages/vuetify/src/components/VTabs/VTab.tsx
fixes #18177
Fixes tab transition clamp NaN scale to 0
This is a similar issue, so the same approach was taken to address it.
https://github.com/vuetifyjs/vuetify/commit/266f54837e297bbc9b2418338151d86cd9d10315
```vue
```
=> fix(tab-transition): clamp NaN scale to 0

packages/vuetify/src/components/VField/VField.sass, packages/vuetify/src/components/VField/_variables.scss
fixes: #18182
regression from #17995: label position has been moved to right
Good (<= v3.3.13)
Bad (<= v3.3.14)
```vue
<template>
<v-app>
<v-container>
<v-select
:model-value="'California'"
placeholder="Hello"
label="Compact"
/>
</v-container>
</v-app>
</template>
```
=> fix(VField): align label with input when rounded not applied

packages/vuetify/src/labs/VDatePicker/VDatePicker.tsx
fixes #18113
```vue
<template>
<v-app>
<v-container>
<v-date-picker v-model="date" min="2023-08-01" max="2023-09-01" input-mode="keyboard" />
</v-container>
</v-app>
</template>
<script setup>
</script>
```
=> fix(VDatePicker): enforce min/max on keyboard input

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx, packages/vuetify/src/composables/__tests__/filter.spec.ts, packages/vuetify/src/composables/__tests__/items.spec.ts, packages/vuetify/src/composables/list-items.ts
fixes #17997
continues from #16210, #16279, #16388, #16512
reverts #16859
kinda un-reverts #16546
Also cleaned up a bit:
- `selections` was redundant, replaced with a single map call in transformIn
- `selected` is only needed to pass to VList, renamed to `selectedValues` for clarity
- `selection` was only used in one place, replaced with a local variable
#17997 comparator is used for primitive model:
```vue
<template>
<v-app>
<v-container>
:items="items"
:value-comparator="comparator"
/>
</v-container>
</v-app>
</template>
<script setup>
{ id: '1', title: 'a' },
{ id: '2', title: 'b' },
{ id: '3', title: 'c' },
]
const model = ref(2)
const comparator = (a, b) => {
if (a === b) return true
const c = …
```
=> fix(Select): always use valueComparator to compare values

packages/docs/src/pages/en/features/display-and-platform.md
Fix broken `useDisplay` link in [Display & Platform](https://vuetifyjs.com/en/features/display-and-platform/).
=> docs: fix broken useDisplay link

packages/vuetify/src/components/VSelectionControl/VSelectionControl.sass, packages/vuetify/src/components/VSwitch/VSwitch.sass
fixes #18225 
**the problem:** VSwitch is clickable as a block element (it takes 100% of the screen width) as shown in the issue [reproduciton](https://play.vuetifyjs.com/#eNqNkUFuwjAQRa9iWV2ARGxVtJsoRfQMLDESIR6K29ix7ElohXL3OjZpESxglczY89//4/WJvlvLuhZoTgsEbesSYSEMIUWX+aPC6jAUhHSZbiTUb4LGr6CpfVASMglYqtqnjjIeMP3mdbmLI9tVVMrJ0ylOM2xW6JT5mEz7bZJaFHwEBnzBL7yE0ldOWYy+4Ns2DomEfdnWSE4JJUssJ9OxIsQBts7814REcE7QtTAbu3366WMjFAX/A9EZrZX58uzTNyYsJyoJWnkvaE7WaVDQA6L1OeeVNOFmIKjOMQPIjdU8rBXV/mc5Z3P2/Mql8jj2srAaz6LaILURpg9EpYdsmS7tFTYdRPQ5kqBBaajveFiGa9y1BpUOD9XoaOYlebloM/A627nm6MEFEUHPO4qYwfADqLtxA+NGmwdgBy5zYCQ4cI9Guhq7jHV1dBPt/Ng97Wc0joXNJ8908wuQiwTp)
**The solution:** 
changed `VSwitch`'s label width from 100% to `max-content` 
```vue
<template>
<v-switch
hide-details
inset …
```
=> fix(VSelectionControl): set width to max-content

packages/docs/src/pages/en/getting-started/unit-testing.md
Fixed the 'global' option to 'globals' in the vitest configuration
https://vitest.dev/config/#globals
=> docs(getting-started): 'global' to 'globals' in the vitest config

packages/vuetify/src/labs/VDataTable/composables/select.ts
Fix the issue by checking if items has length.
fixes #18268 
```vue
<template>
<v-app>
<v-container>
<v-data-table
:items="data"
select-strategy="all"
:show-select="true"
</v-container>
</v-app>
</template>
name: 'BrokenSelectAllStrategy',
data() {
const itemsPerPage: number = 10;
{
title: 'Foo',
key: 'foo',
},
{
title: 'Bar',
key: 'bar',
},
];
const data = [];
const selected = [];
return {
itemsPerPage,
headers,
data,
selected,
};
}
}
</script>
```
=> fix(VDataTable): don't check select-all when table has no rows

packages/vuetify/src/labs/VDatePicker/VDatePickerControls.tsx, packages/vuetify/src/labs/VDatePicker/VDatePickerYears.tsx
Solving the issue by calculating years range correctly. 
fixes #18112 #18132
```vue
<template>
<v-app>
<v-container>
<v-date-picker v-model="date" :max="max" />
</v-container>
</v-app>
</template>
<script setup>
const max = new Date('2024-07-01');
</script>
```
=> fix(VDatePicker): set correct max year

packages/docs/src/pages/en/components/virtual-scroller.md
Removed link to`v- virtual-scroll-item` as it does not appear to exist
```vue
```
=> docs(VVirtualScroll): remove outdated api link

packages/api-generator/src/maps/v-dialog.js
I used web-types of Vuetify 2 to generate global component types for Volar intellisense and type check. Then I found `attrs` is missing in `activator` slot in docs of VDialog, resulting into type error:
=> docs(VDialog): add missing slot props

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx
Fix ignoring disabled prop in VSelect, VAutocomplete & VCombobox components by passing items props to VChip.
fixes #18293 
```vue
<template>
<v-card>
<v-row>
<v-select
v-model="vSelectValues"
:items="vSelectItems"
label="VSelect"
multiple
chips
closable-chips
return-object
></v-select>
</v-col>
</v-row>
<v-row>
v-model="vAutocompleteValues"
:items="vAutocompleteItems"
label="VAutocomplete"
multiple
chips
closable-chips
return-object
</v-col>
</v-row>
<v-row>
<v-combobox
v-model="vComboboxValues"
:items="vComboboxItems"
label="VCombobox"
multiple
chips
closable-chips
return-object
></v-combobox>
</v-col>
</v-row>
</v-container>
</v-card>
</template>
<script>
data: …
```
=> fix: ignore disable props in v-select/v-autocomplete/v-combobox

packages/vuetify/src/labs/VOtpInput/VOtpInput.tsx
Fix the issue by casting prop length type to number.
fixes #18327
```vue
<template>
<v-otp-input
v-model="passCode"
length="4"
@finish="onFinish"
></v-otp-input>
</template>
<script setup>
const passCode = ref('')
const loading = ref(false)
function onFinish() {
loading.value = true
setTimeout(() => {
loading.value = false
}, 2000)
}
</script>
<style scoped lang="scss"></style>
```
=> fix(VOtpInput): cast length prop to number

packages/vuetify/src/components/VTable/VTable.sass, packages/vuetify/src/components/VTable/_variables.scss
Resolves #18295
Added transition properties to `VTable.sass` file into `.v-table` class. That's because `VDataTable` is an extension of `VTable` and adding transition properties to its files would conflict with `VTable` transitions and would not work, which I've tested.
Below an example I've used before, but this time using `VDataTable` from documentation:
```vue
<template>
<v-app>
<v-container>
<v-card>
<v-card-title>Table with theme</v-card-title>
<v-data-table
<v-btn @click="toggleTheme">Toggle theme</v-btn>
</v-card>
</v-container>
</v-app>
</template>
<script setup>
const theme = …
```
=> fix(VDataTable): Add transition properties

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx, packages/vuetify/src/components/VTextField/VTextField.tsx
fixes #17812
```vue
<template>
<v-text-field
label="Chips"
multiple
counter="5"
/>
<v-select
:items="items"
chips
label="VSelect"
multiple
counter="5"
persistent-counter
/>
:items="items"
chips
label="VAutocomplete"
multiple
counter="5"
persistent-counter
/>
<v-combobox
:items="items"
chips
label="VCombobox"
multiple
counter="5"
persistent-counter
/>
</template>
<script>
data: () => ({
value: ['foo', 'bar', 'fizz', 'buzz'],
}),
}
</script>
```
=> fix(VSelect/VAutocomplete/VCombobox): use selected items as counter value

packages/vuetify/src/labs/VBottomSheet/VBottomSheet.tsx
> VBottomSheet
> 
> ## Description
> ## Markup:
> I want to insert classes at the root of the dialog from the bottom sheet.
> 
> ```
> <v-bottom-sheet v-model="showDialog" class="classExample">
>     Content
> </v-bottom-sheet>
> ```
> 
> This class inserted it isn't merge with dialog classes.
=> fix(VBottomSheet): merge the bottom sheet classes with dialog classes

packages/vuetify/src/components/VTimeline/VTimeline.sass
fixes #18176 
```vue
<template>
<v-timeline direction="horizontal">
<v-timeline-item>
<template v-slot:opposite>
Opposite content
</template>
<div>
<div class="text-h6">Content title</div>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</p>
</div>
<v-timeline-item>
<template v-slot:opposite>
Opposite content
</template>
<div>
<div class="text-h6">Content title</div>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</p>
</div>
<v-timeline-item>
<template v-slot:opposite>
Opposite content
</template>
<div>
<div class="text-h6">Content title</div>
<p>
Lorem ipsum dolor sit amet, consectetur …
```
=> fix(VTimeline): fix style for centered horizontal timeline

packages/vuetify/src/components/VList/VList.tsx, packages/vuetify/src/components/VList/VListChildren.tsx
fixes #18304
```vue
<template>
<v-app>
<v-container>
<VMenu location="right">
<template #activator="{ props: menuProps }">
<VBtn v-bind="mergeProps(menuProps)">Test</VBtn>
</template>
<VList
:return-object="true"
:items="viewList"
v-model:selected="currentView"
item-title="title"
/>
</VMenu>
{{ currentView }}
</v-container>
</v-app>
</template>
<script setup>
import { ref, mergeProps } from 'vue'
const currentView = ref([])
const viewList = ref([
{ id: '1', title: 'Events' },
{ id: '2', title: 'Labour' },
{ id: '3', title: 'Equipment' },
])
</script>
```
=> fix(VList): respect return-object in list items

packages/docs/src/pages/en/getting-started/installation.md
This fixes the command that is shown for installing Vuetify with Nuxt 3. Before, the command would also try to install the [`dev`](https://www.npmjs.com/package/dev) Package, which looks like an oversight to me.
=> docs: Fix yarn install command for the nuxt 3 installation guide

packages/vuetify/src/components/VAutocomplete/VAutocomplete.sass, packages/vuetify/src/components/VAutocomplete/_variables.scss
fixes #18470
```vue
<template>
<div style="width: 200px">
clearable
:items="['California California California California California California California California', 'Colorado', 'Florida', 'Georgia', 'Texas', 'Wyoming']"
/>
</div>
</template>
```
=> fix(VAutocomplete): increase selection width by using 100% calc

packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/util/helpers.ts
fixes #18421
```vue
<template>
<v-app>
<v-container>
<v-combobox
chips
multiple
/>
</v-container>
</v-app>
</template>
<script setup>
</script>
```
=> fix(VCombobox): don't trigger keydown listener during composition session

packages/vuetify/src/components/VCard/VCard.sass
**hover** prop on v-card doesn't apply any hover effect.
Other things that not sure if is in
```vue
<v-card hover>
Im a Card
</v-card>
```
=> fix(VCard): apply elevation on hover

packages/docs/src/examples/v-skeleton-loader/usage.vue
Currently the loader is not visible either in black mode or light mode 
So a default type to card is good to have.
=> docs(VSkeletonLoader): make loader appear by default

packages/docs/src/examples/v-avatar/slot-default.vue
By default a `margin: -12px;` is applied in the whole documentation for v-row but in this case, it is messing up the UI.
=> docs(VAvatar): fix cropped icons

packages/docs/src/examples/v-chip/event-action-chips.vue
This PR fixes an issue created in this commit where the example is no longer clickable: https://github.com/vuetifyjs/vuetify/commit/c99f1af11d7cd731e8976ff3107f542a75f34f45#diff-c8bd9378bdae034fb0c54438765e9d59a153f0d443c97e4f48545c8b8252f45b
=> docs(VChip): fix action event examples.

packages/docs/src/pages/en/components/alerts.md, packages/docs/src/pages/en/components/buttons.md, packages/docs/src/pages/en/directives/mutate.md, packages/docs/src/pages/en/features/global-configuration.md
Fix small typos in the documentation  📝
=> docs: fix typos

packages/vuetify/src/labs/VOtpInput/VOtpInput.tsx
fix #18000
```vue
<template>
<v-app>
<v-container>
<v-otp-input />
</v-container>
</v-app>
</template>
<script setup>
</script>
```
=> fix(VOtpInput): Display numeric keyboard when type is number

packages/vuetify/src/labs/VDataTable/VDataTable.sass
fixes #18543
Adjusted the group header row colors to be more web accessible. 
VDataTable.sass
```sass
.v-data-table-group-header-row
td
background: lightgrey
```
to 
```sass
.v-data-table-group-header-row
td
background: rgba(var(--v-theme-surface))
color: rgba(var(--v-theme-on-surface))
```
=> fix(VDataTable): use theme surface color for group header rows

packages/vuetify/src/components/VOtpInput/VOtpInput.tsx
```vue
<template>
<v-app>
<v-container>
<v-otp-input />
</v-container>
</v-app>
</template>
```
=> fix(VOtpInput): limit length when type=number

packages/vuetify/src/labs/VDataTable/VDataTableColumn.tsx, packages/vuetify/src/labs/VDataTable/VDataTableHeaders.tsx, packages/vuetify/src/labs/VDataTable/VDataTableRow.tsx, packages/vuetify/src/labs/VDataTable/VDataTableRows.tsx, packages/vuetify/src/labs/VDataTable/composables/items.ts, packages/vuetify/src/labs/VDataTable/types.ts
closes #16648
closes #16991
```vue
<template>
<v-app>
<v-container>
<v-data-table :headers="headers" :items="items" :cell-props="getCellProps" />
</v-container>
</v-app>
</template>
<script setup>
function getCellProps (data) {
if (data.value > 25) {
return { class: 'text-error' }
}
if (data.value < 10) {
return { class: 'text-success' }
}
}
{ key: 'name', title: 'Name' },
{
key: 'calories',
title: 'Calories',
headerProps: { class: 'text-h4' },
},
{
key: 'fat',
title: 'Fat',
cellProps: ({ value }) => ({
class: value > 10 ? 'text-warning' : 'text-purple', // classes don't override, so specificity matters
}),
},
{ key: 'carbs', title: 'Carbs' },
{ key: 'protein', title: 'Protein' },
{ key: 'iron', title: 'Iron' },
]
{
calories: 159, …
```
=> feat(VDataTable): add headerProps/rowProps/cellProps

packages/vuetify/src/components/VGrid/VSpacer.ts
This Pull Request addresses an issue where VGrid.sass is not imported in the release build when only using the V-spacer component.
Problem Details:
When using the V-spacer component alone, VGrid.sass was not properly imported, causing the styles not to be applied.
Solution:
I have made adjustments to ensure that VGrid.sass is properly imported when the V-spacer component is used.
With this fix, the expected styles will be applied even when using the V-spacer component alone.
resolves #18604
resolves #18121
```vue
```
=> fix(VSpacer): import VGrid styles

packages/docs/src/examples/v-data-table/prop-filterable.vue, packages/docs/src/examples/v-data-table/slot-header.vue, packages/docs/src/examples/v-data-table/slot-main.vue, packages/docs/src/pages/en/components/data-tables/basics.md, packages/vuetify/src/components/VDataTable/VDataTableHeaders.tsx, packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.cy.tsx
closes #17206 + consistency with v2 + consistency with `v-slot:item`/`v-slot:item.something`
=> feat(VDataTable): rename `column.` slots to `header.`

packages/docs/src/pages/en/components/data-tables/introduction.md
The table was incorrect and had links that did not work. This PR fixes that
```vue
```
=> docs: fix data-table guide links

packages/api-generator/src/locale/en/VListItem.json
Fix typo in https://vuetifyjs.com/en/api/v-list-item/#props-active.
Currently:
```
Controls the active state of the item. This is typically used to highlight the component,
```
Expected:
```
Controls the active state of the item. This is typically used to highlight the component.
```
This is my first PR for Vuetify, hoping I follow the contributing correctly. Thank you.🙏
None
```vue
```
=> docs: fix typo in v-list-item active prop description

packages/vuetify/src/components/VOtpInput/VOtpInput.tsx
fixes #18690
```vue
<template>
<v-app>
<v-container>
<v-otp-input disabled></v-otp-input>
<v-text-field
disabled
</v-container>
</v-app>
</template>
```
=> fix(VOtpInput): disable input when prop.disabled is true

packages/vuetify/src/components/VSelectionControlGroup/VSelectionControlGroup.tsx
fixes #18424 
```vue
<template>
<v-app>
<v-container>
<v-form>
<v-radio-group readonly>
<template #label>
I'm a radio group inside a readonly form
</template>
<v-radio label="Radio 1" value="1"></v-radio>
<v-radio label="Radio 2" value="2"></v-radio>
</v-form>
</v-container>
</v-app>
</template>
```
=> fix(VSelectionControlGroup): fix readonly radio group in vform

packages/vuetify/src/components/VSelect/VSelect.tsx
This change fixes an accessibility issue where the items in a VSelect dropdown can not be navigated between by using the arrow keys when [NVDA](https://www.nvaccess.org/) is running. The VList element has a role of "listbox," and according to the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role), each child element should have a role of "option." After adding this role, the VSelect items can  be navigated between using the arrow keys while NVDA is open.
Note: You need to have NVDA running to test these changes out in the playground.
fixes #17767 
fixes #16881
```vue
<template>
<v-app>
<v-container>
<v-select :items="items" label="Select an Item" />
</v-container>
</v-app>
</template>
<script>
setup () { …
```
=> fix(VSelect): add option role to VListItem elements

packages/vuetify/src/locale/fr.ts
There was a typo in the fr locale, for ``dataFooter.itemsPerPageText``. Changed "Élements" to "Éléments"
````
// Other keys
dataFooter: {
itemsPerPageText: 'Éléments par page :',
// Other keys
},
}
````
=> fix(locale): Fix a typo in fr locale, for dataFooter.itemsPerPageText

packages/docs/src/examples/v-stepper/misc-dynamic.vue
The correct props is `disabled` instead of `disable` (see [documentation](https://vuetifyjs.com/en/api/v-stepper-actions/#props-disabled))
```vue
```
=> docs(VStepper): correctly use disabled prop in example

packages/docs/src/pages/en/components/forms.md
Added the words "further down this page" to the tip that mentions examples for integration with 3rd party validation libraries.
As a first time reader of the `forms.md` page I noticed the tip and was confused about where the examples mentioned in it can be found. The addition of some text would have saved me some time by referring me to read further down the page to find the examples.
=> docs(forms.md): add text to help find 3rd party integration examples

packages/docs/src/pages/en/labs/introduction.md
VDatatable doesn't need to be imported separately in 3.4.3, in fact it gives an error when trying to import it from labs (File not found)
```vue
```
=> docs:(introduction.md): update reference component

packages/docs/src/pages/en/getting-started/unit-testing.md
This PR fixes https://github.com/vuetifyjs/vuetify/issues/18396
The vitest config has changed with `vitest@0.34.0`.
`test.deps` has been deprecated and is supposed to be replaced with `test.server.deps`.
Check out these release notes: https://github.com/vitest-dev/vitest/releases/tag/v0.34.0
We now have to pass in the `deps` with `server.deps`, otherwise there is a deprecation warning printed.
=> docs: replace deprecated config for vitest@0.34.0

packages/vuetify/src/components/VDatePicker/VDatePicker.tsx
fixes: #18747 
I have moved the emit calls for `update:month` and `update:year` into the watch scope. This ensures that these events are only triggered when the corresponding values change, preventing unnecessary updates and improving overall performance.
```vue
<script setup>
const updateMonth = month => {
console.log('>> month', month)
}
const updateYear = year => {
console.log('>> year', year)
}
const updateModel = model => {
console.log('>> model', model)
}
</script>
<template>
<v-app>
<v-container>
<v-date-picker
@update:month="updateMonth"
@update:year="updateYear"
@update:model-value="updateModel"
</v-container>
</v-app>
</template>
```
=> fix(VDatePicker): issue on emited update:month and update:year fixed

packages/docs/src/pages/en/features/theme.md
The [Theme section](https://vuetifyjs.com/en/features/theme/) of the docs has two code examples that show wrong import statements of a type definition.
One is in the [TypeScript example](https://vuetifyjs.com/en/features/theme/#typescript) where the `type` keyword is missing.
The other one is in the [JavaScript example](https://vuetifyjs.com/en/features/theme/#javascript) where it shouldn't even be.
This PR fixes both.
=> docs(theme): fixes wrong type import statements in code examples

packages/vuetify/src/components/VInput/VInput.sass, packages/vuetify/src/components/VTextField/VTextField.sass
fixes #18671
Probably it's similar to [comment](https://github.com/vuetifyjs/vuetify/pull/18025#discussion_r1365007826) regarding where is the right place for this logic.
VInput by default doesn't have padding for hint, while VTextField is the one that defines `$text-field-details-padding-inline`. So whether to show/hide hint should be moved to VTextField and keep VInput intact.
```vue
<template>
<v-form>
<v-container>
<v-row>
<v-col cols="12" sm="6">
<v-text-field
label="Your product or service"
model-value="Grocery delivery"
hint="For example, flowers or used cars"
</v-col>
<v-col cols="12" sm="6">
<v-text-field
label="Your landing page"
hint="www.example.com/page"
</v-col>
<v-col cols="12" sm="6">
<v-text-field
label="Your product or …
```
=> fix(VTextField): hide v-input__details for underlined variant

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx
fixes #18562
```vue
<template>
<div>
<v-combobox
color="blue-grey-lighten-2"
label="Type text and counter on right should show #chars * 3"
item-title="name"
variant="underlined"
persistent-counter
counter="40"
multiple
:counterValue="calcLength"
>
<template v-slot:item="{ props, item }">
<v-list-item v-bind="props" :title="item.raw.name"></v-list-item>
</template>
</v-combobox>
<v-select
color="blue-grey-lighten-2"
label="Type text and counter on right should show #chars * 3"
item-title="name"
variant="underlined"
persistent-counter
counter="40"
multiple
:counterValue="calcLength"
>
<template v-slot:item="{ props, item }">
<v-list-item v-bind="props" :title="item.raw.name"></v-list-item>
</template>
</v-select> …
```
=> fix(VSelect/VAutocomplete/VCombobox): respect function counter-value

packages/docs/src/pages/en/components/text-fields.md
Maybe I'm getting this wrong, but right below the text stating hints would not be possible for solo fields is an example with a variant=solo field including a hint.
=> docs(VTextField): Hint possible for solo variant

packages/docs/src/pages/en/getting-started/installation.md
This PR adds the missing closing bracket when installing with Nuxt.
=> docs: missing closing bracket in Nuxt installation guide

packages/docs/src/examples/v-data-table/slot-loading.vue, packages/vuetify/src/components/VDataTable/VDataTable.sass, packages/vuetify/src/components/VDataTable/VDataTableHeaders.tsx, packages/vuetify/src/components/VDataTable/VDataTableRows.tsx, packages/vuetify/src/composables/loader.tsx
closes #18445
change in behavior to match v2. now loading slot will only be shown if it has been defined, and loading text will only show if there are no items.
```vue
<template>
<div class="pa-10">
:items-length="totalItems"
:items="serverItems"
@update:options="loadItems"
/>
</div>
</template>
<script>
const desserts = [
{
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1',
},
{
calories: 375,
fat: 0.0,
carbs: 94,
protein: 0.0,
iron: '0',
},
{
name: 'KitKat',
calories: 518,
fat: 26.0,
carbs: 65,
protein: 7,
iron: '6',
},
{
calories: 262,
fat: 16.0,
carbs: 23,
protein: 6.0,
iron: '7',
},
{ …
```
=> fix(VDataTable): only show loading slot if no items or slot provided

packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.tsx, packages/vuetify/src/components/VExpansionPanel/VExpansionPanels.tsx
Fix the issue by providing default readonly for VExpansionPanelTitle using VExapnsionPanel readonly prop.
fixes #18346 
```vue
<template>
<v-app>
<v-expansion-panels multiple>
<v-expansion-panel :disabled="true">
<v-expansion-panel-title
>I'm a disabled panel, everything is ok</v-expansion-panel-title
>
<v-expansion-panel-text> Some content </v-expansion-panel-text>
<v-expansion-panel :readonly="true">
<v-expansion-panel-title
>I'm a readonly panel, but you can still open me
:(</v-expansion-panel-title
>
<v-expansion-panel-text> Some content </v-expansion-panel-text>
</v-app>
</template>
```
=> fix(VExpansionPanel): fix v-expansion-panel readonly prop

.github/.git_commit_msg.txt
When configured with `commit.cleanup=scissors`, git uses `# ------------------------ >8 ------------------------` as seperator between commit message and comments, instead of treating lines starting with `#` as comments.
This fixes the template with `commit.cleanup=scissors` setup.
N/A
=> chore: fix commit template with commit.cleanup=scissors

packages/docs/src/pages/en/components/buttons.md
The role attribute is mentioned in the docs but was never set in all the implementations I tried. I worked with the m3 theme, so this might be the reason. I changed it to type since you do set a type on every button to type=button.
=> docs(buttons.md): changed role to type on button a11y description.

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx
fixes #18494
Root cause:
When input value becomes '', `model.value = []` is called in `onUpdateModelValue`, which triggers render function but `search.value` hasn't been updated, so its previous value is drilled into VTextField via `modelValue` and shows old value.
Therefore, use `v-model` resolves it
```vue
<template>
<v-app>
<v-container>
<v-autocomplete 
placeholder='Select Item'
v-model="selectedPerson"
/>
</v-container>
</v-app>
</template>
<script setup>
const people = ['John Smith', 'John Doe']
const selectedPerson = ref(null)
// Issue 1
// 1. Click into the auto-complete
// 2. Select "John Smith" (Observe that "John Smith" is added to the autocomplete selected list)
// 3. Start using the back-space to delete. (Observe that to delete "J" …
```
=> fix(VAutocomplete): Use v-model to modify search.value instead of using onInput

packages/vuetify/src/components/VSelect/VSelect.tsx
1. There shouldn't be nested interactive controls so I changed the role on the .v-field from 'button' to 'combobox'
2. `aria-haspopup` is being set to 'menu' by default in VMenu so I am passing down `aria-haspopup` as 'listbox' in VSelect and passing it down to the VMenu
* Both changes are fixing this a11y issue: 
Interactive controls must not be nested
fixes #18495
```vue
<template>
<v-app>
<v-container>
<v-select
label="Select"
/>
</v-container>
</v-app>
</template>
<script>
setup () {
},
}
</script>
```
=> fix(VSelect): fix accessibility

packages/api-generator/src/locale/en/VList.json
Clarifies the reduction of horizontal spacing to 8 pixels for badges, icons, tooltips, and avatars within slim list items, from a previous 32 pixels, ensuring a tighter, more compact visual structure.
related: #17562
Live demo: [playground](https://play.vuetifyjs.com/#eNrtU8tu2zAQ/JUFL7YBU/KjQAvBCdB7T0VvUQ4baZNsQ0oEuVIcGP73kpIfMvoDOeTGmd0dLmfAh4MKvsp/Opf1HalC7YSsMyh0XzYAu15X6GuoDIZwVyq719hJWyqwuNfvXMtrZLerVamG/mHCcJATumDNUffMAfT6ufVxcp7oJfACuIF0DqW6dhVv9BGb+Ibr0XSU2CQ4KVStGSSdZ4v+Y1oK3ZOwmDT1q/VkgV3oLNRpAgILoCWJAk2gSkg6D1iz48AVNy9AhmWq5jw5amqNPQqmG19FXCjy3GNTt7YL5DNLOTrOXevFI0vI31tLTf4j++terloXk25t0sOy0SOhvZxemqVzNHmX/9d4tXpaO8dx4iK8yQeC4XPPV0ifJ6QRpD8XwS6ffMYIQ+XZjV20T2tDTc/YGYHDKFTHxxYwX8DdPcxPHIyRFfBwgLRfAbPfhEb/YUuzmGp0NFK2Zl2ZtnqbwfFxOU4eF8PhmBa5XK2OS7XNvmUr/USC2VqN8Lu2GCSaullttnq90eu …
=> docs(VList): add description for `slim` prop

packages/api-generator/src/locale/en/VBtn.json
Adds missing documentation for the slim prop, detailing its use in reducing the vertical padding to render thinner buttons.
related: #17562
```vue
<v-btn slim>Slim button</v-btn>
```
=> docs(VBtn): add description for `slim` prop

packages/vuetify/src/components/VOtpInput/VOtpInput.sass, packages/vuetify/src/components/VOtpInput/VOtpInput.tsx
fixes #18809
```vue
<template>
<v-app>
<v-container>
<v-otp-input :loading="true">
<template v-slot:loader>
<v-progress-circular indeterminate ></v-progress-circular>
</template>
</v-otp-input>
<v-otp-input :loading="true">
<template v-slot:loader>
<v-progress-linear :location="'bottom'" indeterminate></v-progress-linear>
</template>
</v-otp-input>
</v-container>
</v-app>
</template>
```
=> fix(VOtpInput): exclude loader slot in VField slots

packages/vuetify/src/components/VDataTable/VDataTableFooter.tsx
resolves #18864 
```vue
<template>
<v-app>
<v-container>
:items="[]"
items-length="0"
first-page-label="go back to the first page"
prev-page-label="go back to the previous page"
next-page-label="go forward to the next page"
last-page-label="go forward to the last page"
/>
</v-container>
</v-app>
</template>
<script>
setup () {
return {
//
}
},
}
</script>
```
=> fix(VDataTableServer): correct mismatched prop name for the previous ARIA label

packages/api-generator/src/locale/en/VSwitch.json
This PR fixes a missing translation issue on the [VSwitch API Docs](https://vuetifyjs.com/en/api/v-switch/#events) page
This is the current docs:
And this is the docs after this fix has been implemented:
=> fix: Added the missing `update: indeterminate` translation string to `VSwitch.json`

packages/vuetify/src/locale/cs.ts
Fixes a typo in CZ translations.
=> fix(locale): typo in CZ translations

packages/docs/src/pages/en/getting-started/upgrade-guide.md
Fix typo in https://vuetifyjs.com/en/getting-started/upgrade-guide/#styles-and-utility-classes
Currently:
Typography classes are have been renamed for consistency and are all prefixed with text-, for example .display-4 is now .text-h1
Expected:
Typography classes have been renamed for consistency and are all prefixed with text-, for example .display-4 is now .text-h1
```vue
```
None
=> docs: fix typo in styles and utility classes description

packages/vuetify/src/components/VDataTable/VDataTable.sass, packages/vuetify/src/components/VDataTable/VDataTableHeaders.tsx
Fixes https://github.com/vuetifyjs/vuetify/issues/18984
```vue
```
=> fix(VDataTable): sticky header problem with bgColor

packages/docs/src/components/app/bar/Bar.vue, packages/vuetify/src/components/VTabs/VTab.sass
Fixes #18970
```vue
<template>
<v-app>
<v-container>
<v-tabs bg-color="primary">
<v-tab value="one">Item One</v-tab>
<v-tab value="two">Item Two</v-tab>
<v-tab value="three">Item Three</v-tab>
</v-tabs>
</v-container>
</v-app>
</template>
<script setup>
const msg = ref("Hello World!");
</script>
```
also change this in `vuetify.js`:
```js
export default createVuetify({
directives,
ssr: !!process.env.VITE_SSR,
date,
defaults,
icons,
locale,
theme: { defaultTheme: 'light' },
defaults: {
VTab: {
density: 'comfortable', // << added this
},
},
})
```
=> fix(VTab): VBtn height inside VTab with non-default density #18970

packages/vuetify/src/components/VAutocomplete/VAutocomplete.sass, packages/vuetify/src/components/VAutocomplete/_variables.scss, packages/vuetify/src/components/VCombobox/VCombobox.sass, packages/vuetify/src/components/VCombobox/_variables.scss
fixes #18894
Cause: `selection` + `inline-margin-end` occupies the whole flex container, so there is no pixel left to hold input in the same row
Solution: introduce a fixed 2px buffer placeholder to hold input and prevent it flow to next line
```vue
<template>
<v-app>
<v-container>
<div style="width: 200px">
:items="['Hello i am a very very very very veeeeeery long text']"
hide-details
clearable
/>
</div>
multiple
/>
style="width: 150px"
multiple
/>
style="width: 100px"
multiple …
```
=> fix(VAutocomplete/VCombobox): add buffer space after selection to hold input

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx
fixes #18933
```vue
<template>
<v-app>
<v-container>
<v-autocomplete :items="items" :item-props="itemProps" />
<v-combobox :items="items" :item-props="itemProps" />
<v-select :items="items" :item-props="itemProps" />
</v-container>
</v-app>
</template>
const items = ref(['Item 1'])
function itemProps (item: any) {
return {
title: item,
prependAvatar:
'https://avatars0.githubusercontent.com/u/9064066?v=4&s=460',
}
}
</script>
```
=> fix(VAutocomplete): fix usage with prependAvatar in VListItem

packages/vuetify/src/components/VDataTable/VDataTableFooter.tsx
fixes #18893 
```vue
<template>
<v-app>
<v-container>
<v-data-table
first-icon="mdi-alien"
last-icon="mdi-alien"
prev-icon="mdi-alien"
next-icon="mdi-alien"
:headers="tableHeaders"
/>
<v-data-table
:headers="tableHeaders"
/>
</v-container>
</v-app>
</template>
<script setup>
import { computed } from 'vue'
const tableHeaders = computed(() => [
{
key: 'id',
title: 'Id',
},
{
key: 'name',
title: 'Name',
},
])
</script>
```
=> fix(VDataTable): fix send props to VPagination

packages/vuetify/src/globals.d.ts
Vue 3.4 no longer implicitly registers global JSX namespace and this is necessary to preserve old behavior.
=> chore: explicitly register global Vue JSX types for 3.4

packages/vuetify/src/locale/pt.ts
I have fixed the portuguese locale to match the real description of some components, like the new VDatePicker, which have some minor errors in the translation (e.g header and title still in english). 
Beyond that, I've fixed some other missing translations in the file, as you can see in the commit.
resolves #19007
```ts
badge: 'Distintivo',
open: 'Abrir',
close: 'Fechar',
confirmEdit: {
ok: 'OK',
cancel: 'Cancel',
},
dataIterator: {
noResultsText: 'Nenhum dado encontrado',
loadingText: 'Carregando itens...',
},
dataTable: {
itemsPerPageText: 'Linhas por página:',
ariaLabel: {
sortDescending: 'Ordenado decrescente.',
sortAscending: 'Ordenado crescente.',
sortNone: 'Não ordenado.',
activateNone: 'Ative para remover a ordenação.',
activateDescending: 'Ative para ordenar …
```
=> fix(i18n): Updating Portuguese i18n locale for some components

packages/vuetify/src/composables/date/adapters/vuetify.ts
Use Date Intl weekday: narrow instead of slicing first character
=> fix(date): return unmodified DateTimeFormat

packages/docs/src/examples/v-otp-input/misc-divider.vue
`resolves` #18979
I have added the v-model to the divider example as discussed in #18979. This would allow the send new code button to empty the input field (desired behaviour).
=> docs(VOtpInput): add v-model to divider example

packages/docs/src/data/nav.json, packages/docs/src/examples/cursor/usage.vue, packages/docs/src/pages/en/styles/cursor.md, packages/vuetify/src/styles/settings/_utilities.scss
TODO: Documentation
Added all cursor classes to be used in any element:
auto default pointer text progress wait not-allowed grab grabbing help
```html
<div class="cursor-pointer" />
<div class="cursor-grab" />
```
=> feat(style): add cursor class utilities 

packages/docs/src/examples/v-data-table/prop-headers-sort-raw.vue, packages/docs/src/pages/en/components/data-tables/data-and-display.md, packages/vuetify/src/components/VDataTable/VDataTable.tsx, packages/vuetify/src/components/VDataTable/VDataTableVirtual.tsx, packages/vuetify/src/components/VDataTable/composables/headers.ts, packages/vuetify/src/components/VDataTable/composables/sort.ts, packages/vuetify/src/components/VDataTable/types.ts
closes #11226
TODO:
<details>
```vue
<template>
<v-app>
<v-data-table-virtual
height="500"
:items="items"
/>
</div>
</v-app>
</template>
<script setup>
function useSort (a, b) {
if (a.email === 'email31@example.com') return -1
if (b.email === 'email31@example.com') return 1
return a.first.localeCompare(b.first)
}
{ title: 'First Name', key: 'first', sortRaw: useSort },
{ title: 'Last Name', key: 'last' },
{ title: 'Email', key: 'email' },
{ title: 'Age', key: 'age' },
{ title: 'Company', key: 'company' },
]
const items = Array.from({ length: 500 }, (_, i) => ({
first: `First` + (i === 4 ? 'a' : 'ab'),
last: `Last`,
email: `email${i}@example.com`,
age: 20 + i,
company: `Company${i}`,
}))
</script>
```
</details>
=> feat(VDataTable/Virtual): add support for sorting raw objects

packages/api-generator/src/locale/en/VSelectionControl.json, packages/api-generator/src/locale/en/VSwitch.json, packages/docs/src/data/new-in.json, packages/vuetify/src/components/VSwitch/VSwitch.sass, packages/vuetify/src/components/VSwitch/VSwitch.tsx
<details>
```vue
<template>
<v-app>
<v-switch
label="Testing"
true-icon="mdi-check"
false-icon="mdi-close"
inset
>
<template #thumb="{ icon }">
<v-scale-transition>
<v-icon :key="icon" :color="model ? 'primary' : 'disabled'" size="12" />
</v-scale-transition>
</template>
</v-switch>
</div>
</v-app>
</template>
<script setup>
const model = ref(false)
</script>
```
</details>
=> feat(VSwitch): add thumb slot

packages/docs/src/pages/en/components/all.md
Inside all components showcase, there was a duplicated Bottom Sheet component. Just removed the last one as both of them redirects to the bottom sheet page.
=> docs(components/all): remove duplicated Bottom Sheet Component

packages/vuetify/src/composables/group.ts
closes #19107
<details>
```vue
<template>
<v-app>
<v-container>
<pre>{{ JSON.stringify(step, null, 2) }}</pre>
<v-stepper v-model="step">
<v-stepper-item title="step 1" />
<v-stepper-item title="step 2" />
</v-stepper-header>
<v-stepper-window>
<v-stepper-window-item> step 1 </v-stepper-window-item>
<v-stepper-window-item> step 2 </v-stepper-window-item>
</v-stepper-window>
</v-stepper>
</v-container>
</v-app>
</template>
<script setup>
const step = ref(1)
</script>
```
</details>
=> fix(group): use index as value if not provided

packages/docs/src/examples/v-tabs/misc-content.vue, packages/docs/src/examples/v-tabs/misc-dynamic-height.vue, packages/docs/src/examples/v-tabs/prop-stacked.vue
fix VTabs example in documentation
centered property (v2) => align-tabs="center" (v3)
=> docs(VTabs): correct centered to align-tabs center

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx
fixes #19235
Ensure consistency in the select logic between VAutocomplete and VSelect
```vue
<template>
<v-app>
<v-container>
<v-label text="V-Select without multiple prop"></v-label>
v-model="currentValue"
clearable
chips
closable-chips
label="Select"
/>
<v-select
v-model="currentValue"
clearable
chips
closable-chips
label="Select"
></v-select>
Current Value: {{currentValue}}
<hr />
<v-label class="mt-10" text="V-Select with multiple prop"></v-label>
<v-select
v-model="currentValue"
clearable
chips
closable-chips
label="Select"
multiple …
```
=> fix(VSelect): closing chip removes selection

packages/vuetify/src/components/VList/VListItem.sass, packages/vuetify/src/components/VList/_variables.scss
fixes #19233
reverts 74be064
```vue
```
=> fix(VList): set explicit overflow-wrap to break-word

packages/vuetify/src/components/VDatePicker/VDatePickerMonth.tsx
fixes #19218
```vue
<template>
<v-app>
<v-container>
<v-date-picker
v-model="date"
:month="pickerMonth"
:year="pickerYear"
:min="minDate"
/>
</v-container>
</v-app>
</template>
const minDate = '2024-02-20'
const date = ref(null)
const pickerMonth = !date.value ? new Date(minDate).getMonth() : undefined
const pickerYear = !date.value ? new Date(minDate).getFullYear() : undefined
</script>
```
=> fix(VDatePicker): mark current date when it's disabled

packages/vuetify/src/labs/VCalendar/VCalendar.tsx
Ensuring that a custom ordered weekdays will display properly and not be sorted.
See https://vuetifyjs.com/en/components/calendars/#usage
Ensuring that a custom ordered weekdays will display properly and not be sorted.
See https://vuetifyjs.com/en/components/calendars/#usage
```vue
<template>
<div>
<v-sheet
tile
height="54"
class="d-flex"
>
<v-select
v-model="type"
:items="types"
dense
hide-details
class="ma-2"
label="View Mode"
></v-select>
<v-select
dense
hide-details
class="ma-2"
></v-select>
</v-sheet>
<v-sheet>
<v-calendar
ref="calendar"
:weekdays="weekday"
:view-mode="type"
:interval-start="0"
title="test"
></v-calendar>
</v-sheet>
</div>
</template>
<script> …
```
=> fix(VCalendar): remove default sorting of weekdays

packages/vuetify/src/components/VDatePicker/VDatePicker.tsx, packages/vuetify/src/components/VDatePicker/VDatePickerMonths.tsx, packages/vuetify/src/components/VDatePicker/VDatePickerYears.tsx
fixes #19132 
```vue
<template>
<v-app>
<v-container>
<v-date-picker v-model="date" view-mode="months" />
<v-date-picker v-model="date" view-mode="year" />
<v-date-picker v-model="date" />
</v-container>
</v-app>
</template>
<script setup>
</script>
```
=> fix(VDatePicker): fix select current month or year

packages/vuetify/src/components/VTooltip/VTooltip.sass, packages/vuetify/src/components/VTooltip/_variables.scss
Tooltip set width，text too length, but text not wrap
```vue
```
=> fix(Tooltip): set width attr,text too length,but text not wrap

packages/vuetify/src/components/VDataTable/VDataTable.tsx, packages/vuetify/src/components/VDataTable/types.ts
Improve typing on value functions with generics.
With markup below, before:
```
Types of property 'value' are incompatible.
Type '(v: Data) => string' is not assignable to type 'SelectItemKey'.
Type '(v: Data) => string' is not assignable to type '(item: Record<string, any>, fallback?: any) => any'.
Types of parameters 'v' and 'item' are incompatible.
Property 'string' is missing in type 'Record<string, any>' but required in type 'Data'.
4       <v-data-table :items="items" :headers="headers" />
```
after: passes typecheck.
```vue
<template>
<v-app>
<v-container>
<v-data-table :items="items" :headers="headers" />
</v-container>
</v-app>
</template>
interface Data {
string: string
}
setup () {
return {
items: [
{ string: 'foo' },
{ …
```
=> fix(VDataTable): improve headers value function typing

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx
Screen readers need the options role in order to successfully redirect arrow navigation to the options. Without this change, keyboard navigation is broken when having a screen reader on.
fixes #18858
This is the same fix as https://github.com/vuetifyjs/vuetify/pull/18629 but now for VAutocomplete instead of VSelect.
You need to have a screen reader running to test these changes, as the screen reader changes keyboard navigation!
Tested with Orca and JAWS.
```vue
<template>
<v-app>
<v-container>
<v-autocomplete :items="items" label="Select an Item" />
</v-container>
</v-app>
</template>
<script>
setup () {
return {
//
}
},
data: () => ({
items: ['Apple', 'Orange', 'Pineapple']
})
}
</script>
```
=> fix(VAutocomplete): fix screenreader navigation

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete.spec.cy.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx, packages/vuetify/src/components/VSelect/__tests__/VSelect.spec.cy.tsx
fixes #19261
Made cy tests to prevent regressions: #19261 #19235 #18796
```vue
<template>
<v-app>
<v-container>
<h1>Without Multiple</h1>
<v-select v-model="msg" :items="['abc','def']" />
<v-autocomplete v-model="msg" :items="['abc','def']" />
<v-combobox v-model="msg" :items="['abc','def']" />
{{msg}}
<h1>Multiple</h1>
<v-select multiple v-model="msg" :items="['abc','def']" />
<v-autocomplete multiple v-model="msg" :items="['abc','def']" />
<v-combobox multiple v-model="msg" :items="['abc','def']" />
</v-container>
</v-app>
</template>
<script setup>
const msg = ref('abc')
</script>
```
=> fix(VSelect/VAutocomplete): prevent select function from toggling v-model in single selection mode

packages/docs/src/examples/accessibility/menu.vue
1. Go to https://vuetifyjs.com/en/features/accessibility/
2. Scroll down to `Focus management and keyboard interactions` section
3. On the example, click on `Click me` button.
4. Menu is open but text is not displayed
N/A
=> docs: fix accessibility page VMenu with VList example

packages/vuetify/src/components/VAutocomplete/VAutocomplete.sass, packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete.spec.cy.tsx, packages/vuetify/src/components/VCombobox/VCombobox.sass, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.cy.tsx
fixes #17573
Improve experience in #17291
When having chip or selection shot:
- Input shouldn't be absolute positioned
- Search value (input) should always be empty when unfocused
- I will do comprehensive testing, but extra eyes on testing always welcome
```vue
<template>
<v-app>
<v-container>
<h1>Single selection</h1>
<h2>Autocomplete</h2>
:items="items"
item-title="name"
item-value="age"
label="no selection slot"
@update:search="updateSearch"
/>
:items="items"
item-title="name"
item-value="age"
label="selection slot"
@update:search="updateSearch"
>
<template #selection="{ item }">
<VChip>{{ item.raw.name }} - {{ item.raw.age }}</VChip>
</template>
<template #item="{ item, props }">
<v-list-item v-bind="props" title="">
{{ item.raw.name }} - {{ …
```
=> fix(VAutocomplete/VCombobox): avoid input absolute position when having selection slot

packages/vuetify/src/components/VAutocomplete/VAutocomplete.sass, packages/vuetify/src/components/VCombobox/VCombobox.sass
fixes #19279
Input width changed when become focused, which impacts caret position. It's a default behaviour either in Vue or Js: [demo](https://play.vuejs.org/#eNqdVMlu2zAQ/ZWBgEIJ4FgOmpOqBF2QAinQBW1vVQ+KTDlMKJLgotgw/O99JC1baNMcoouoeTNv3izUNnun9XzwLCuzyraGa0eWOa+vasl7rYyjLRnW0Y46o3rK4ZrXslXSOmJrx+TyRmrv6DJ4nXSNsOx0xHu72tvzHMbOy9ZxJWFBipNT2taS8Exo5kMjPENQJAowOA7GHJlruZsw8RD0UbXe0sj3FJsz/l8yoeSKHNzprxOyIEdVpHagEfhwrNeicQxfRJUX8Y2T4FeflbeM1MAMuTtG1jXGcdBovEl1SeMsYJJawdsH6oLgGbWNYY60sjzVYunRIH9VgPS/9KjtJcytMoa17sBdFfsaqiUfENxYe1lnGJtruGSmzkYFU1hjlHwN7Fs8VAXA0S9qoeGsV0sm4ItW1xm9jYLweRwUrOVI+CvvNxHJZ7TN0+TycjrC3W/4F3vJY7rq1juHuoYz3oFl4h5Sxk7AvN8yyI2nqkhRYKiKyTgr6zYiHOaH6tMiLbmFz6akTrD1m2B55Et3V9LFYqGTYexwiZUGHR8YzNid+b6sRBTiSzpPSBKbgGN4c2uV8C6EH9KcLxavEh1Wca8xm2XOQmfHV/N7qyRubWQKo+s1F8x81YERXS7 …
=> fix(VAutocomplete/VCombobox): input always absolute position when not using selection slot/chips

packages/vuetify/src/components/VSwitch/VSwitch.sass, packages/vuetify/src/components/VSwitch/VSwitch.tsx, packages/vuetify/src/components/VSwitch/_variables.scss
fixes #19307 
```vue
<template>
<v-app>
<v-container>
<v-switch />
<v-switch flat />
</v-container>
</v-app>
</template>
```
=> fix(VSwitch): remove elevation with flat props

packages/docs/src/examples/v-sparkline/prop-fill.vue
`radius` property on VSparkline has been updated to [`smooth` in Vuetify 3](https://vuetifyjs.com/en/api/v-sparkline/#props-smooth).
This old migrated example was a bit unexplicit about it so I tried to refactor it.
[Preview here](https://play.vuetifyjs.com/#eNrVVs1u4zYQfpWBtoBtwHJk2cnuqo7bokB66aFADz3YAZaRKJkIJQoUbScw/O4dkvqhZSVF0L1skETkfMMZcuabITcnr5LxzW9lOTvsqRd5K0XzkhNF19sCYHXwY1EowgoqIeV7lhixAaqSyGeOiJUARCnj/H7r6c/Wa6WZJAmjhUKkopzGiiZ/1CJHSxvyjyxRO9TTk3/02FHIRUK5fyB8T1HDfB20JEnCigyReuRgVS6EMWsHHUL2SviJJEcrWK9unFPhQdujJuzAEiqNQjN2YCmOdVjqiHHAvwo9zsOtB3mCo7ut1+o0i4BwlhUIxhgLKlE15qTS63QI/R1l2Q5j5KwzKxmmyM+k2Jdw8E1YBkMLOSkSooR8vTDQOm98lcq/g5L7lzu88NYXAzpOhcTF4ya7U2ATYAU086oLc/cTPdNXXMSGMAw9F5okJyCxYgc6BSWyjFM4D5pqmNA4vFa6Oo3NDpHJNaBpol65NngaQgGeSPysg14kUXvIGadFpnawhvnwIoBf4JtmE5GYMbtoHCQ0m …
=> docs(VSparkline): fix radius usage in example

packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.cy.tsx
fixes #19319
Subject to more testing
```vue
<template>
<v-app>
<v-container>
<v-combobox
:items="[{id: 1, desc: 'item1'},{id: 2, desc: 'item2'}]"
v-model="comboRef"
item-title="desc"
multiple
/>
:items="[{id: 1, desc: 'item1'},{id: 2, desc: 'item2'}]"
v-model="comboRef"
item-title="desc"
return-object
/>
<span> Value: {{ comboRef }} </span>
</v-container>
</v-app>
</template>
<script setup>
const comboRef = ref(null)
</script>
```
=> fix(VCombobox): don't update v-model when it already contains the search text in single selection mode

packages/vuetify/src/components/VDatePicker/VDatePickerMonth.tsx, packages/vuetify/src/composables/date/adapters/vuetify.ts
fixes #19330 
```vue
<template>
<v-container>
<v-date-picker color="primary" multiple="range"></v-date-picker>
</v-row>
</v-container>
</template>
```
use date-io/dayjs adapter
```vue
import { createVuetify } from 'vuetify'
import DayJsAdapter from '@date-io/dayjs'
export const vuetify = createVuetify({
date: { adapter: DayJsAdapter },
})
```
=> fix(VDatePicker): fix crash when select date range with external adapter

packages/vuetify/src/composables/date/DateAdapter.ts, packages/vuetify/src/composables/date/adapters/__tests__/vuetify.spec.ts, packages/vuetify/src/composables/date/adapters/vuetify.ts
Add missing IUtil interface function: isBeforeYear
```vue
<template>
<v-app>
{{ adapter.date() }}
</div>
</v-app>
</template>
<script setup>
import { useDate } from '../src/composables/date'
const adapter = useDate()
console.log(adapter)
</script>
```
=> feat(VDatePicker): add isBeforeYear check

packages/vuetify/src/labs/VCalendar/VCalendarInterval.sass, packages/vuetify/src/labs/VCalendar/VCalendarIntervalEvent.sass, packages/vuetify/src/labs/VCalendar/VCalendarIntervalEvent.tsx
fixes #18968
```vue
<template>
<v-app>
<v-container>
<v-calendar v-model="msg" view-mode="week" :events="events"></v-calendar>
</v-container>
</v-app>
</template>
<script setup>
const events = [
{
title:
'The text is too long and overflow, end date is invalid, event only lasts an hour',
start: new Date('2024-01-23T03:00:00Z'),
end: new Date('2024-01-23T4:00:00Z'),
color: 'blue',
},
]
const msg = ref([new Date('2024-01-23T14:30:00Z')])
</script>
```
=> fix(VCalendar): Stop day row content overflowing its parent

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx
fixes #19369
In multiple selection mode, Backspace key selects the last item first then remove on second Backspace event.
In single selection mode, remove selected item directly on first Backspace event.
```vue
<template>
chips
/>
<v-combobox
chips
/>
</template>
```
=> fix(VAutocomplete/VCombobox): allow delete in single selection mode

packages/vuetify/src/composables/theme.ts
Adding in a null check if `dark` is undefined
```vue
if (current.value?.dark) {
createCssClass(lines, ':root', ['color-scheme: dark'])
}
```
=> fix(theme): add null check for current dark check

packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.tsx
fixes #19339
```vue
<template>
<v-app>
<v-container>
<v-breadcrumbs :items="['foo', 'bar']">
<template #item="{ item }">{{ item }}</template>
</v-breadcrumbs>
<v-breadcrumbs :items="['foo', 'bar']">
<template #item="{ item }">{{ item.title }}</template>
</v-breadcrumbs>
<v-breadcrumbs :items="['foo', 'bar'].map((entry) => { return { title: entry } })">
<template #item="{ item }">{{ item.title }}</template>
</v-breadcrumbs>
</v-container>
</v-app>
</template>
</script>
```
=> fix(VBreadcrumbs): fix types for slots

packages/vuetify/src/components/VMenu/VMenu.tsx
fixes #19361
This PR addresses issue #19361 by the VMenu closing when the Enter key is pressed. Previously, when navigate through the arrow keys and pressing Enter wouldn't close the menu, causing inconvenience for users. This change ensures that the menu closes when Enter is pressed, improving the user experience. Issue can be found [here](https://github.com/vuetifyjs/vuetify/issues/19361)
```vue
<template>
<v-app>
<v-container>
<v-menu>
<v-btn v-bind="props">Open Menu</v-btn>
</template>
<v-list>
<v-list-item @click="{}">1</v-list-item>
<v-list-item @click="{}">2</v-list-item>
</v-list>
</v-menu>
</v-container>
</v-app>
</template>
<script>
setup () {
return {
//
}
},
}
</script>
```
=> fix(VMenu): don't close when press enter

packages/vuetify/src/components/VDatePicker/VDatePickerMonth.tsx, packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.spec.cy.tsx, packages/vuetify/src/composables/date/adapters/vuetify.ts
fixes #19366
```vue
<template>
<v-app>
<v-container>
{{ data }}
<v-date-picker v-model="data" multiple="range"></v-date-picker>
</v-container>
</v-app>
</template>
<script>
setup () {
return {
data: ref(null)
}
},
}   
</script>
```
=> fix(VDatePickerMonth): set rangeStart/rangeStop from model

packages/vuetify/src/locale/no.ts
I'm guessing `open` here is the imperative, as you'd see on a button (and not a description of something being open)
(btw, `no` is a macrolanguage covering `nb` and `nn`; this file contains text in `nb`, but if the rot has spread then perhaps it's a bit late to change it now)
=> fix(locale): translate `open` for no.ts

packages/vuetify/src/components/VProgressLinear/VProgressLinear.sass
fixes #19410
`will-change` should be used as a last resort to resolve existing performance problem, it's doing strange pre-animation effect in Windows here.
```vue
<template>
<v-app>
<v-container>
<v-checkbox label="Show Loading" v-model="loading" />
<v-text-field
v-model="msg"
color="blue"
/>
<div class="h3 mb-2">Temporay Solution</div>
<v-text-field
v-model="msg"
color="blue"
>
<template #loader>
v-show="loading"
height="2"
color="blue"
indeterminate
/>
</template>
</v-text-field>
</v-container>
</v-app>
</template>
<script setup>
const loading = ref(false)
const msg = ref('Check to show loading')
</script>
```
=> fix(VProgressLinear): Remove will-change to prevent weird visual behaviour

packages/vuetify/src/components/VBreadcrumbs/__tests__/VBreadcrumbs.spec.cy.tsx, packages/vuetify/src/composables/router.tsx
If for example VCard to prop is evaluated as undefined and then changed, the changes were not be propagated to the href.
fixes #19300
Card link after enabling link (from undefined to page2)
| Before | After |
| -- | -- |
|  ![router-before](https://github.com/vuetifyjs/vuetify/assets/100124171/c5923da5-96d6-485f-94b0-9db76b30d118) | ![router-after](https://github.com/vuetifyjs/vuetify/assets/100124171/ebdf369e-950d-4d2d-a4e5-89c26ac492d7) |
```vue
<template>
<v-app>
<v-container>
Click button to toggle link state on list item
<v-breadcrumbs active-color="primary">
<v-breadcrumbs-item active>Hello</v-breadcrumbs-item>
<v-breadcrumbs-divider>/</v-breadcrumbs-divider>
<v-breadcrumbs-item to="/page2">Page 2</v-breadcrumbs-item>
</v-breadcrumbs>
<v-btn @click="setLink">Set link</v-btn> …
```
=> fix: make router useLink link reactive

packages/vuetify/src/components/VField/_variables.scss
fixes #19151
```vue
<template>
<div class="ma-5">
<v-combobox
label="Fruits"
rounded
multiple
chips
v-model="fruits"
></v-combobox>
<v-combobox
label="Fruits"
rounded
chips
></v-combobox>
</div>
</template>
<script setup>
const fruits = [
'Apple',
'Apricot',
'Avocado',
'Banana',
'Blackberry',
'Blackcurrant',
'Blueberry',
'Boysenberry',
'Breadfruit',
'Cantaloupe',
'Carambola',
'Cherimoya',
'Cherry',
'Clementine',
'Coconut',
'Cranberry',
'Date',
'Dragonfruit',
'Durian',
'Elderberry',
'Feijoa',
'Fig',
'Goji berry',
'Gooseberry',
'Grape',
'Grapefruit',
'Guava',
'Honeydew',
'Huckleberry',
'Jabuticaba',
'Jackfruit',
'Jambul',
'Jujube',
'Juniper berry',
'Kiwi',
'Kumquat',
'Lemon',
'Lime',
'Longan',
'Lychee',
'Mandarin',
'Mango',
'Mangosteen',
'Marionberry', …
```
=> fix(VField): use xl border-radius for rounded prop

packages/vuetify/src/components/VSelectionControlGroup/VSelectionControlGroup.tsx
fixes #19462
packages/vuetify/dev/Playground.vue
```vue
<template>
<v-app>
<v-container>
<v-switch />
<v-checkbox />
<v-radio-group />
<v-radio />
</v-container>
</v-app>
</template>
<script>
}
</script>
```
packages/vuetify/dev/vuetify/defaults.js
```js
global: {
ripple: { class: "text-error" },
},
};
```
=> fix(VSelectionContolGroup): add correct ripple prop type

packages/vuetify/src/composables/router.tsx
fixes #19487
I'll try to add `useLink` to `NuxtLink`, this PR just fixes the error when using latest Vuetify 3.5.12.
=> fix: check `RouterLink.useLink` exists before using it

packages/docs/src/pages/en/features/internationalization.md
Updates the link to `vue-i18n`, currently it's pointing to the v8 docs, you probably want to point to the v9 docs instead.
```vue
```
=> docs: change `vue-i18n` url to point to v9 docs

packages/vuetify/src/components/VDataTable/VDataTableServer.tsx
VDataTableServer was missing VDivider above the footer. This change now makes VDataTableServer more visually consistent with VDataTable
=> fix(VDataTableServer): was missing VDivider above the footer

packages/vuetify/src/components/VList/VListItem.sass, packages/vuetify/src/components/VList/VListItem.tsx
Fixes #19005
Removed the hover effect if list item isn't set to clickable if link or href isn't set
```vue
<template>
<v-app>
<v-container>
<v-list>
<v-list-item>Item 1</v-list-item>
<v-list-item active>Item 2</v-list-item>
<v-list-item link="#" active>Item 3</v-list-item>
<v-list-item link="#">Item 4</v-list-item>
<v-list-item>Item 5</v-list-item>
</v-list>
</v-container>
</v-app>
</template>
<script>
};
</script>
```
=> fix(VListItem): Removed hover effect if list item is not clickable

packages/vuetify/src/components/VBtn/VBtn.tsx
When the loading prop is true, Vbtn still lets the user select the button through the tab and register the enter event.
resolves #18524
```vue
<template>
<v-card
max-width="450"
title="Strengthen your passwords"
text="Update your weak or re-used passwords with Password Checkup. It's free and only takes a few minutes. Click the Take Checkup button to get started."
>
<template #actions>
<v-btn height="48"> No Thanks </v-btn>
<v-btn
class="flex-grow-1"
height="48"
variant="tonal"
@click="load"
>
Take Checkup
</v-btn>
</template>
</v-card>
</template>
```
=> fix(VBtn): prevent keyboard tab from triggering the loading button

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VField/VField.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx
If an icon is clickable, keyboard navigation to the icon should be allowed. If `onClick` is defined, I am setting the `tabindex` to 0
fixes #18482
```vue
<template>
<v-app>
<v-container>
<v-select
clearable
label="Select"
></v-select>
</v-container>
</v-app>
</template>
```
=> fix(VSelect/Auto/Combo): focus and activation of chips and clearable using keyboard

packages/vuetify/src/components/VSelect/VSelect.tsx, packages/vuetify/src/components/VSwitch/VSwitch.sass, packages/vuetify/src/components/VSwitch/_variables.scss
Feature to fix #18952
Added direction prop on ```VSelect``` and added styling to ```VSwitch```
```vue
<template>
<v-app>
<v-container>
<v-switch
label="Vertical"
></v-switch>
<v-switch
direction="horizontal"
label="Horizontal"
></v-switch>
<v-switch v-model="model" label="Default"></v-switch>
</v-container>
</v-app>
</template>
<script>
data: () => ({
model: false,
}),
};
</script>
```
=> fix(VSwitch): label when using direction vertical

packages/vuetify/dev/vuetify/locale.js, packages/vuetify/src/components/VDatePicker/VDatePicker.tsx, packages/vuetify/src/composables/date/DateAdapter.ts, packages/vuetify/src/composables/date/adapters/vuetify.ts
Fixed code to use adapter abstraction in text and header computed values
changed text and header computed values to use adapter abstraction while computing first day of month and header value.
resoves #18942
packages/vuetify/dev/vuetify/locale.js
```js
import { ar, en, fa, ja, sv } from 'vuetify/src/locale'
locale: 'fa',
messages: {
en,
ar,
sv,
ja,
fa,
},
}
```
packages/vuetify/dev/Playground.vue:
```vue
<template>
<v-app>
<v-container>
<v-date-picker
v-model="date"
/>
</v-container>
</v-app>
</template>
<script>
data: () => ({
date: new Date(),
}),
}
</script>
```
=> fix(VDatePicker): fixed missing adapter abstractions

packages/docs/src/pages/en/components/chips.md
I changed the Github and spec columns in the "features" section from "v-btn" to "v-chip".
There was an mistake in the "features" section of the v-chip.
The links for Github and the design specs were incorrectly set as buttons instead of chips.
This has been fixed.
=> docs(VChip): Fixed a mistake in the features section

packages/docs/src/pages/en/components/overlays.md
I got difficulties to have the overlay only over my parent, then I read on https://github.com/vuetifyjs/vuetify/issues/16086 that the parent should have the parent.
The API mentions but not the example, this could be helpful to have as it's not clear for the issuer of https://github.com/vuetifyjs/vuetify/issues/17071.
fixes #17071
=> docs(Overlay): add information about contained that the desirable container should be relative to be taken as container

packages/docs/src/examples/v-expansion-panels/misc-advanced.vue
Fixed the example for accessing passed props to `VExpansionPanelTitle`
The code example used in the documentation for `VExpansionPanelTitle` tried to use a non-existent prop called `open` which is in reality called `expanded`. This PR fixes that.
This is my first pull request to this repository so please excuse any mistakes and let me know what to fix. :)  
```vue
<template>
<v-expansion-panels>
<v-expansion-panel>
<v-expansion-panel-title>
<template v-slot:default="{ expanded }">
<v-row no-gutters>
<v-col class="d-flex justify-start" cols="4"> Trip name </v-col>
<v-col class="text-grey" cols="8">
<v-fade-transition leave-absolute>
<span v-if="expanded" key="0"> Enter a name for the trip </span>
<span v-else key="1"> {{ trip.name }} </span>
</v-fade-transition>
</v-col>
</v-row> …
```
=> docs(VExpansionPanel): Fixed broken code example 

packages/vuetify/src/components/VDataTable/VDataTable.sass, packages/vuetify/src/components/VDataTable/VDataTableColumn.tsx, packages/vuetify/src/components/VDataTable/VDataTableHeaders.tsx, packages/vuetify/src/components/VDataTable/VDataTableRow.tsx, packages/vuetify/src/components/VDataTable/types.ts
Fix for issue: https://github.com/vuetifyjs/vuetify/issues/18862
in this playground use props
maxWidth: '60px',
wrap: true,
```vue
<template>
:items-length="totalItems"
:items="serverItems"
@update:options="loadItems"
></v-data-table-server>
</template>
<script>
const desserts = [
{
name: 'Frozen Yogurt,Frozen Yogurt,Frozen Yogurt,Frozen Yogurt,Frozen Yogurt,Frozen Yogurt,Frozen Yogurt,',
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1',
},
{
calories: 262,
fat: 16.0,
carbs: 23,
protein: 6.0,
iron: '7',
},
{
name: 'Gingerbread',
calories: 356,
fat: 16.0,
carbs: 49,
protein: 3.9,
iron: '16',
},
{
calories: 237,
fat: 9.0, …
```
=> fix(VDataTable): max-width doesn work properly, new prop to wrap text when use maxWidth

packages/vuetify/src/components/VDataTable/composables/options.ts
fixes #17966
Fixes initial checking of old search value to include a check for undefined. Without it the condition was always true.
```vue
<template>
<v-text-field
label="Search"
/>
<v-data-table
:page="2"
/>
</template>
const search = ref('')
const headers = ref([
{
key: 'name',
},
{ title: '', key: 'data-table-expand' },
] as const)
const desserts = ref([
{
calories: 159,
fat: 6,
},
{
name: 'KitKat',
calories: 518,
fat: 26,
},
{
name: 'Ice cream sandwich with some really long name', …
```
=> fix(VDataTable): avoid changing page if oldOptions is not defined

packages/vuetify/src/labs/VTimePicker/VTimePickerClock.tsx
Change the event handlers to use window events instead of limiting to picker container.
```vue
<template>
<v-app>
<v-main>
<v-container>
<v-row>
{{ thisDate }}
<v-col>
<v-switch v-model="format24" color="primary" false-value="ampm" label="24hr" true-value="24hr" />
</v-col>
<v-col>
<v-switch v-model="seconds" color="primary" label="Seconds" />
</v-col>
</v-row>
<v-row>
<v-time-picker v-model="thisDate" :format="format24" :use-seconds="seconds" scrollable />
</v-col>
</v-row>
</v-container>
</v-main>
</v-app>
</template>
<script setup>
const thisDate = ref(new Date())
const format24 = ref('24hr')
const seconds = ref(false)
</script>
```
=> fix(VTimePicker): use window events instead of element

packages/docs/src/pages/en/components/data-tables/basics.md, packages/docs/src/pages/en/features/sass-variables.md
Just fix typo error `customisation` to `customization` in docs
=> docs: fix typo error

packages/vuetify/src/labs/VTimePicker/VTimePicker.tsx
```vue
<template>
<v-app>
<v-main>
<v-container>
<v-row>
<v-col>
<v-menu>
<v-text-field v-bind="props" v-model="thisDate" readonly />
</template>
<v-time-picker v-model="thisDate" format="24hr" @update:hour="hour = true" @update:minute="minute = true" @update:second="second = true" />
</v-menu>
</v-col>
{{ hour }}
{{ minute }}
{{ second }}
</v-row>
</v-container>
</v-main>
</v-app>
</template>
<script setup>
const thisDate = ref(new Date())
const minute = ref(false)
const hour = ref(false)
const second = ref(false)
</script>
```
=> fix(VTimePicker): Fix emits on change

packages/vuetify/src/components/VAppBar/VAppBar.tsx, packages/vuetify/src/composables/layout.ts
resolves #18020
```vue
<template>
<v-app>
<v-app-bar scroll-behavior="fully-hide" extended />
<v-main style="height: 500vh;" />
</v-app>
</template>
<script setup>
</script>
```
=> feat(VAppBar): add support for fully-hide scroll-behavior

packages/vuetify/src/components/VBtn/VBtn.tsx
fixes #17376
```vue
<template>
<v-app>
<v-btn>asdf</v-btn>
<v-btn icon="$vuetify" />
</div>
</v-app>
</template>
```
=> fix(VBtn): apply center ripple when using the icon prop

packages/vuetify/src/composables/calendar.ts, packages/vuetify/src/labs/VCalendar/VCalendar.tsx
v-calendar was not usable without supplying a v-model
```vue
<template>
<v-app>
<v-main>
<v-calendar />
</v-main>
</v-app>
</template>
```
=> fix(VCalendar): not usable without v-model

packages/vuetify/src/labs/VCalendar/VCalendarMonthDay.tsx
we should not show events on adjacent days unless show-adjacent-months is used
```vue
<template>
<v-app>
<v-container>
<v-calendar
v-model="date"
/>
</v-container>
</v-app>
</template>
<script>
setup () {
const date = ref([new Date(2024, 3, 1)])
return {
date,
events: [
{
start: new Date(2024, 3, 1),
end: new Date(2024, 3, 1),
title: 'foo',
},
{
start: new Date(2024, 4, 1),
end: new Date(2024, 4, 1),
title: 'bar',
},
],
}
},
}
</script>
```
=> fix(VCalendar): hide adjacent events when not using show-adjacent-months

packages/vuetify/src/components/VDatePicker/VDatePicker.tsx, packages/vuetify/src/components/VDatePicker/VDatePickerMonth.tsx, packages/vuetify/src/composables/calendar.ts
looking at previous art, most "fullscreen" calendars seem to go with a varying week length of either 5 or 6 depending on how the days in the month are arranged. this includes arguably the two biggest examples (google, microsoft). but there are ones that use a static 6 weeks, pretty much always together with showing adjacent days.
date-pickers also vary, but ones based on material design like MUI do use static 6 weeks so that the dialog does not jump when switching months
with this change, date-picker uses static by default, calendar uses dynamic
```vue
<template>
<v-app>
<v-container>
<v-calendar
v-model="date"
></v-calendar>
<v-calendar
v-model="date"
weeks-in-month="static"
></v-calendar>
</v-container>
</v-app>
</template>
<script>
import { ref } …
```
=> feat(calendar): prop to switch between dynamic/static number of weeks

packages/vuetify/src/composables/date/adapters/__tests__/vuetify.spec.ts, packages/vuetify/src/composables/date/adapters/vuetify.ts
v-calendar in week mode did not show the correct day order on other locales
```vue
<template>
<v-app>
<v-main>
<v-calendar view-mode="week" />
</v-main>
</v-app>
</template>
```
=> fix(date): startOfWeek/endOfWeek does not respect locale

packages/docs/src/pages/en/features/theme.md
Removed `.value` from `theme.global.name` and `theme.global.current`,
because it broke the function `toggleTheme`.
=> docs(Theme): theme.global.name/current shouldn't have .value

packages/vuetify/src/components/VSelect/VSelect.tsx
fixes #19574
```vue
<template>
<v-select
v-model="favorites"
:items="states"
hint="Pick your favorite state"
label="Select"
></v-select>
</template>
<script>
data() {
return {
favorites: [],
states: [
'Alabama',
'Alaska',
'American Samoa',
'Arizona',
'Arkansas',
'California',
'Colorado',
'Connecticut',
'Delaware',
'District of Columbia',
'Federated States of Micronesia',
'Florida',
'Georgia',
'Guam',
'Hawaii',
'Idaho',
'Illinois',
'Indiana',
'Iowa',
'Kansas',
'Kentucky',
'Louisiana',
'Maine',
'Marshall Islands',
'Maryland',
'Massachusetts',
'Michigan',
'Minnesota',
'Mississippi',
'Missouri',
'Montana',
'Nebraska',
'Nevada',
'New Hampshire',
'New Jersey',
'New Mexico',
'New York',
'North Carolina',
'North Dakota',
'Northern Mariana Islands',
'Ohio', …
```
=> fix(VSelect): auto scroll to selected item when using hotkeys

packages/vuetify/src/components/VInput/VInput.tsx
- Add `maxWidth`, `minWidth` & `width` props to VInput
- Heights are restricted by densities
```vue
<template>
<v-text-field
:max-width="550"
:min-width="500"
:width="600"
:style="{ width: '700px' }"
/>
<v-select
:max-width="550"
:min-width="500"
:width="600"
/>
:max-width="550"
:min-width="500"
:width="600"
/>
<v-combobox
:max-width="550"
:min-width="500"
:width="600"
/>
<v-file-input
:max-width="550"
:min-width="500"
:width="600"
/>
<v-textarea
:max-width="550"
:min-width="500"
:width="600"
/>
</template>
<script>
}
</script>
```
=> feat(VInput): add dimensions support to VInput

packages/vuetify/src/composables/router.tsx
fixes #19549
- Empty string is the one to represent real empty "to" that makes `RouterLink.useLink` happy [demo](https://play.vuejs.org/#eNp9U9uO2jAQ/RU3+wCrQsxetA8pi7atVqVVb9pWfWn6EJIBvMQX2Q5khfj3ju1Awpauosj2zJkzZ46TbcQzJuJHEyUR40pqS7Yk15BZeKsU2ZG5lpz01hX0UtEAtKws6CYT03Bs065un8uUikNtKg6sfXzPU0FIXBnoh/Jw5rIStt87w7LeeTSImnLUNrbAVYn1EwccLy8mUyhL6Zq9GlM8+rAKC21Wka39BrcPvstnJlYksfI2jXq9NJp8kMRKMpUcxrRFNCT76rFz6JjnF4MNoQ2uSY/pQSIqD1Od9PULcKmfpsxYXAZNMPB2/R4efEXrpDCN74bckt+p+PMsrDHcZepvnbhlaJKc6tw/HzhIIMXtDq8gFVB7rQXMs6rcc+M8YYYhzxTOJAVO5RukTcKkUUJ8xMVa9S6cRktrlUkorYRaLeJcctoi7q7jq3hECxTVicZg+HCm5cZ4E9PIa3XcdwiiBaytlKUZZor9r8U/wLub+Ca+oCWbUWSnTBRQe25HvUMDcExr0NM5WzwbEvkUK0F/U5ah50fDZvgZbj75mNUVHITmS8hXJ+KPpg6Sv2vA6dbQGc5megE2pO9/fIUa94ckl0VVIvqF5AMYWVZOY4C9q0SBsjs4r/ajvzMmFj/NfW1BmP1QTqh3w+P9Rb5 …
=> fix(router): empty string to represent real empty "to"

packages/vuetify/src/styles/settings/_variables.scss
Been like this since dbddc073d9ee4eca71a06aba8c4d8c70d84f6ef0
There's some more places in components with rem but I cbf, feel free to change them too I guess.
=> fix(typography): use relative line heights

packages/vuetify/src/labs/VNumberInput/VNumberInput.tsx, packages/vuetify/src/labs/VNumberInput/__tests__/VNumberInput.spec.cy.tsx
fixes #19438
fixes #19558
fixes #19538
fixes #19494
- Remove `type="number"` to avoid all sorts of weird behaviours in native number input. [More details from Why the GOV.UK Design System team changed the input type for numbers](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/)
- Always clamp modelValue between "min" and "max"
- Disable the increment and decrement buttons when clicking the next step would exceed the 'max' and 'min' values, respectively
- Up and down keys trigger increment and decrement respectively
- Right and left keys trigger go forward and backward navigation
- Only numbers, +, - and dot are allowed to type in
- Fully support decimal step, using `toFixed()` to cope with JS Floating-Point Precision Issues …
=> fix(VNumberInput): avoid native number input weird behaviours

packages/vuetify/src/components/VDialog/VDialog.tsx, packages/vuetify/src/components/VDialog/__test__/VDialog.spec.cy.tsx
fixes #19660 
```vue
<template>
<v-app>
<v-container>
<v-dialog v-model="showDialog" width="600" @after-leave="onAfterLeave()">
<div class="content">Content</div>
</v-dialog>
<v-btn @click="reset">Reset</v-btn>
<div>{{ hidden ? "hidden" : "visible" }}</div>
</v-container>
</v-app>
</template>
<script setup>
const showDialog = ref(true)
const hidden = ref(false)
function reset () {
showDialog.value = true
hidden.value = false
}
function onAfterLeave () {
hidden.value = true
}
</script>
<style scoped>
.content {
width: 200px;
height: 200px;
background-color: #fff;
}
</style>
```
=> fix(Dialog): add afterLeave event

packages/vuetify/src/components/VChip/VChip.sass
Dragging the cursor slightly while clicking a `VChip` with the `link` prop (or otherwise clickable with `@click` I think) would cause the text to become selected. This PR prevents text selection.
```vue
<template>
<v-app>
<v-main>
<v-chip link>Try selecting me</v-chip>
</v-main>
</v-app>
</template>
```
=> fix(VChip): prevent text selection for link chips

packages/vuetify/src/components/VList/VList.tsx
Fixes #19092
Up/down/home/end keys were not working in a VTextarea that is inside a VList
```vue
<template>
<v-form>
<v-list>
<v-list-item>
<v-textarea
name="input-1"
variant="filled"
auto-grow
rows="1"
:model-value="text"
/>
</v-list-item>
</v-list>
</v-form>
</template>
<script setup>
const text = `The Woodman set to work at once,
and so sharp was his
axe that the tree was soon
chopped nearly through.`
</script>
```
=> fix(VTextarea): up/down/home/end keys inside VList

packages/vuetify/src/composables/directiveComponent.ts
Fix error: Cannot read properties of undefined (reading 'text')
Fix warning: Non-function value encountered for default slot. Prefer function slots for better performance
=> fix(useDirectiveComponent): Cannot read properties of undefined (reading 'text')

packages/vuetify/src/components/VDatePicker/VDatePicker.tsx, packages/vuetify/src/composables/date/adapters/vuetify.ts
When using the next/previous control in the `VDatePicker`, the current logic could sometime pick the wrong month if the current date does not exists. For example, if it is `April 30th, 2024` - navigating back to March would work, but going to February would show March again. If the date range is between 1 and 28/29, the picker would work as expected. A similar issues was occuring with `VCalendar` within the `addMonth` function.
This is because:
[Date.prototype.setMonth()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setMonth)
> The current day of month will have an impact on the behavior of this method. Conceptually it will add the number of days given by the current day of the month to the 1st day of the new month specified as the parameter, to …
=> fix(VDatePicker): wrong month can be displayed in header.

packages/vuetify/src/components/VDataTable/VDataTableHeaders.tsx
Fixes the issue where the select all checkbox is showing up next to the sortby select on mobile when `data-table-select` is not present in the `columns`
```typescript
const appendIcon = computed(() => {
const showSelectColumn = columns.value.find(column => column.key === 'data-table-select')
if (showSelectColumn == null) {
return
}
return allSelected.value ? '$checkboxOn' : someSelected.value ? '$checkboxIndeterminate' : '$checkboxOff'
})
```
=> fix(VDataTable): select all checkbox showing when not enabled on mobile

packages/vuetify/src/components/VSlideGroup/__tests__/VSlideGroup.spec.cy.tsx, packages/vuetify/src/composables/__tests__/goto.spec.cy.tsx
There is no way, `VSlideGroup` cy test  cannot be fixed on CI ~~, but why is it failing if it is excluded (`it.skip`) ?~~.
I'll try to fix the `pointer-events` and CI issue...
=> chore(tests): fix flaky cypress tests

packages/api-generator/src/locale/en/display.json, packages/vuetify/src/composables/display.ts
Changes the `VDataTable` mobile prop to a default of `false`
Partially fixes https://github.com/vuetifyjs/vuetify/issues/19726
```vue
```
=> fix(VDataTable): change mobile default to false

packages/vuetify/src/labs/VNumberInput/VNumberInput.tsx
`type="number"` input has been removed, number-input should be really just a wrapper having number features on top of VTextField.
This approach reuses VTextFi19757eld features
fixes #19659
fixes #19757
```vue
<template>
<v-app>
<v-container>
<v-form fast-fail @submit.prevent>
<v-text-field
v-model="msg"
:rules="[v => v.length > 3 || 'min length 3'      ]"
/>
:rules="[v => v > 3        || 'value must be > 3' ]"
/>
<v-btn type="submit" text="test validate and error messages" />
</v-form>
</v-container>
</v-app>
</template>
<script setup>
const msg = ref('ms')
const value = ref(1)
</script>
```
```vue
<template>
<v-app>
<v-select
v-model="fieldVariant"
label="Variants"
:items="['underlined', 'outlined', 'filled', 'solo', …
```
=> fix(VNumberInput): use VTextField as the base component

packages/vuetify/src/components/VList/VListItem.tsx
fixes #19638 
```vue
<template>
<v-treeview :items="items" :lines="false" />
</template>
<script>
data: () => ({
items: [
{
id: 1,
children: [
{ id: 2, title: 'Calendar : app' },
],
},
],
}),
}
</script>
```
=> fix(VTreeview): lines prop supports boolean type

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx
resolves #19543
```vue
<template>
<v-app>
<v-container class="mx-2">
<v-row>
<v-col>
:items="lista"
item-title="n"
label="Label"
title="Choose one"
hide-no-data
@update:search="handleSearch"
/>
</v-col>
<v-col>
<v-btn @click="searchCount = 0">Clean Search Count</v-btn>
</v-col>
<v-col>Model: {{ model }} Search Count: {{ searchCount }}</v-col>
</v-row>
<v-row>
<v-col>
<ol>
<li>Choose one in list</li>
<li>Click outside autocomplete</li>
<li>Search occurs two times</li>
</ol>
</v-col>
</v-row>
</v-container>
</v-app>
</template>
const model = ref(0)
const searchCount = ref(0)
const lista = ref([{ n: 'Choose one', id: 0 }, { n: 'test', id: 1 }, { n: 'test2', …
```
=> fix(VAutocomplete): only clear search on blur in multiple mode or using chips/selection shots 

packages/vuetify/src/labs/VCalendar/VCalendar.sass, packages/vuetify/src/labs/VCalendar/_variables.scss
fixes #18988
regression https://github.com/vuetifyjs/vuetify/commit/4820347463f5ea139bea08a712dd4573c3f492b4
```vue
<template>
<v-container>
<v-calendar v-model="msg" view-mode="week" :events="events"></v-calendar>
</v-container>
</v-app>
</template>
<script setup>
const events = [
{
title: 'First',
start: new Date('2024-01-22T02:00:00Z'),
end: new Date('2024-01-22T04:30:00Z'),
color: 'blue',
},
{
title: 'Second',
start: new Date('2024-01-23T05:30:00Z'),
end: new Date('2024-01-23T08:30:00Z'),
color: 'red',
},
{
title: 'Third',
start: new Date('2024-01-23T08:30:00Z'),
end: new Date('2024-01-23T09:30:00Z'),
color: 'green',
},
{
title: 'Fourth',
start: new Date('2024-01-24T02:01:00Z'),
end: new Date('2024-01-24T04:01:00Z'),
color: 'green',
},
] …
```
=> fix(VCalendar): remove background for week view mode

packages/vuetify/src/locale/hu.ts
Add more Hungarian translations
I added more translations. I have not found Hungarian at Crowdin
=> fix(locale): update hu translation

packages/vuetify/src/labs/VTreeview/VTreeviewChildren.tsx
fixes #19579
resolves #19566
fixes #19390
Addresses the issue of only one tree item only ever being able to load any child data via the `load-children` callback prop, this change allows all tree items to each load their own children once.
The issue of all tree items showing a loading state when any one item is loading is resolved, now only the item that is loading its children will show a loading state.
```vue
<script lang="ts" setup>
import {reactive, ref} from 'vue'
const selection = ref([])
function generateRandomBookName() {
const adjectives = ['The Great', 'The Secret', 'Brave', 'Mysterious', 'Fantastic', 'Magical'];
const nouns = ['Adventure', 'Journey', 'Quest', 'Discovery', 'Encounter', 'Escape'];
const adjective = adjectives[Math.floor(Math.random() * adjectives.length)];
const …
```
=> fix(VTreeview): Allow child load on many items and scoped loading state

packages/vuetify/src/components/VSelect/VSelect.tsx, packages/vuetify/src/components/VSelect/__tests__/VSelect.spec.cy.tsx
fix #19806 
```vue
<template>
<v-switch v-model="returnObject" color="primary" label="Return Object" />
<v-select
:hint="`${select.state}, ${select.abbr}`"
:items="items"
:return-object="returnObject"
item-title="state"
item-value="abbr"
label="Select"
hide-selected
/>
</template>
<script>
data () {
return {
select: { state: 'Florida', abbr: 'FL' },
returnObject: false,
items: [
{ state: 'Florida', abbr: 'FL' },
{ state: 'Georgia', abbr: 'GA' },
{ state: 'Nebraska', abbr: 'NE' },
{ state: 'California', abbr: 'CA' },
{ state: 'New York', abbr: 'NY' },
],
}
},
}
</script>
```
=> fix(VSelect): fix hide-selected with return-object

packages/vuetify/src/components/VMenu/VMenu.tsx
When using nested v-menus, if the parent has persistent set to true, it should remain open on an outside click even when the child menu is closed with an outside click.
When using a v-menu to get input from the user we set the parent menu to be persistent and expect it to remain open until the user cancels/saves. 
* Added check to `closeParents` function to take into account if the menu is persistent or not. 
This is related to #19239, which kept the parent menu open if the child menu was closed by clicking on the parent menu content. This extends this check to account for the parent being persistent, thus keeping the menu open even on outside clicks and resolves #19780.
```vue
<template>
<v-app>
<v-container>
<v-btn id="rootButton">
Open Menu 1
</v-btn>
<v-menu
v-model="menu1" …
```
=> fix(V-Menu): only closing menu in closeParents if persistent is not set

packages/docs/src/pages/en/components/avatars.md
Fixed the incorrect link to the v-icon component in the documentation. The v-icon component is located in the `/components/icons/`directory, so the link destination has been changed from `/components/images/` to `/components/icons/`. With this fix, the documentation now provides the correct link to the v-icon component.
```vue
```
=> docs: fix v-icon component link

packages/docs/src/pages/en/components/checkboxes.md
In the v-checkbox documentation, a tip is mentioning v-simple-checkbox. This seems to be a leftover from vuetify 2. Now we have v-checkbox-btn instead. I corrected that and also added a link to more information about v-checkbox-btn.
=> docs(checkboxes.md): update v-simple-checkbox description.

packages/vuetify/src/components/VDivider/VDivider.sass
Assuming `<v-divider vertical>` makes sense only inside flexbox container, the `height: auto` allows `align-self: stretch` to take effect when container does not have explicit height.
Example in [docs](https://vuetifyjs.com/en/components/dividers/#usage) does not expose the issue, because `d-flex` gets additional explicit height, but in real life, we usually leave height to be dynamic and determined based on the children height.
After the change I did not notice any negative effects, but I may not know about use cases outside flexbox.
fixes #19827
=> fix(VDivider): visiblity in container with dynamic height

packages/vuetify/src/labs/VCalendar/VCalendar.tsx
fixes #19814 
```vue
<template>
<v-app>
<v-calendar />
</v-app>
</template>
```
Add `LuxonAdapter` as your DateAdapter (need to install `luxon` as well)
```vue
import { createVuetify } from 'vuetify'
import LuxonAdapter from "@date-io/luxon"
export default createVuetify({
date: {
adapter: LuxonAdapter,
},
})
```
=> fix(VCalendar): use date adapter to create new date

packages/vuetify/src/components/VDataTable/VDataTable.sass, packages/vuetify/src/composables/defaults.ts
* Fixes null getting changed to false value
Ref: https://discord.com/channels/340160225338195969/1241152212038717482/1242216293017325569
```vue
```
=> fix(defaults): allow null component and global values

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx
For autocomplete/comobobox, "Tab" key is equivalent to "blur", so remove tab key listener and let `isFocused === false` watcher handle "auto-select-first"
fixes #19840
```vue
<template>
<v-app>
<v-container>
<v-combobox
chips
:items="['California1', 'California2', 'California3', 'Colorado', 'Florida', 'Georgia', 'Texas', 'Wyoming']"
multiple
hide-selected
auto-select-first
/>
chips
:items="['California1', 'California2', 'California3', 'Colorado', 'Florida', 'Georgia', 'Texas', 'Wyoming']"
multiple
hide-selected
auto-select-first
/>
</v-container>
</v-app>
</template>
```
=> fix(VAutocomplete/VCombobox): remove tab key listener

packages/vuetify/src/components/VDatePicker/VDatePicker.tsx, packages/vuetify/src/components/VDatePicker/VDatePickerMonths.tsx
fixes #19810 
```vue
<template>
<v-app>
<v-container>
<v-date-picker
:max="new Date(2025, 7, 15)"
:min="new Date(2022, 2, 15)"
/>
</v-container>
</v-app>
</template>
```
=> fix(VDatePicker): disable months outside min/max value

packages/vuetify/src/components/VDataTable/VDataTable.sass
Fixes the data table row height now fit to content on mobile
```vue
```
=> fix(VDataTable): fit mobile row height to content

packages/api-generator/src/locale/en/VDataTable.json, packages/vuetify/src/components/VDataTable/VDataTable.tsx, packages/vuetify/src/components/VDataTable/VDataTableServer.tsx, packages/vuetify/src/components/VDataTable/VDataTableVirtual.tsx
Brings back ability to replace the default `tbody`
resolves #18854
```vue
<template>
<v-data-table
hide-default-body
:items="[
{ id: 1, text: '1' },
{ id: 2, text: '2' },
]"
>
<template #tbody="{ items }">
<tbody>
<tr v-for="item in items" :key="item.id">
<td>{{ item.id }}</td>
<td>{{ item.text }}</td>
</tr>
</tbody>
</template>
</template>
```
=> fix(VDataTable): hide default body

packages/vuetify/src/components/VSlider/VSlider.tsx, packages/vuetify/src/components/VSlider/VSliderThumb.tsx
Accessability problem with v-slider component.
The code pass `name` prop to slider thumb component and uses name as an aria-label value. If name prop isn't passed it just uses `Slider` as a default aria-label value.
=> fix(VSlider): add aria-label to v-slider-thumb

packages/vuetify/src/labs/VNumberInput/VNumberInput.tsx, packages/vuetify/src/labs/VNumberInput/__tests__/VNumberInput.spec.cy.tsx
VNumberInput should keep original value as long as it has `readonly`, or `disabled` attributes or is contained within `readonly` form. (similar to other controls).
Fix is inspired by similar change for VAutocomplete and aims to render controls as disabled instead of just suppressing event handlers. Test cases should be self-explanatory.
Idea to consider: hiding controls and showing `mdi-lock-outline` instead would be a nice touch, but should probably follow internal discussion about consistency with other components accepting `readonly` prop.
fixes #19896
```vue
<template>
<v-app>
<v-container>
<v-card class="mx-auto pa-6 my-4" style="max-width: 1200px">
<v-row>
<v-col><v-switch color="success" hide-details v-model="inputDisabled" label="Disable input" /></v-col>
<v-col><v-switch …
```
=> fix(VNumberInput): disable keyboard up/down for readonly state

packages/api-generator/src/locale/en/VDataTable.json, packages/docs/src/pages/en/components/data-tables/basics.md
Fixed wrong`VDataTableHeaders` links in `VDataTable`-related docs .
1. `packages/docs/src/pages/en/components/data-tables/basics.md`
-> fixed `v-data-table-headers`' description (wrongly subtitled as `v-data-table-footer`)
2. `packages/api-generator/src/locale/en/VDataTable.json`
-> fixed `v-data-table-headers` link (wrongly noted as 'v-data-table-header' - the last 's' was omitted)
=> docs(VDataTable): fix wrong v-data-table-headers links

packages/vuetify/src/components/VCheckbox/__tests__/VCheckboxBtn.spec.cy.tsx, packages/vuetify/src/components/VSelectionControl/VSelectionControl.tsx
fixes #19137
How to reproduce the bug is described in the referenced issue, but shortly, the `input` internal checked state was out of sync with modelValue when the `readonly` flag is `true`.
That caused the bug, when the checkbox becomes interactive again, and sometimes it would not update the model value on the first click on the checkbox.
```vue
<template>
<v-app>
<v-container>
<v-checkbox-btn
label="Checkbox #1:"
v-model="checkboxState"
:readonly="shouldLockCheckboxUpdates"
/>
<v-checkbox-btn
v-model="shouldLockCheckboxUpdates"
label="Checkbox #2:"
/>
</v-container>
</v-app>
</template>
const checkboxState = ref(false);
const shouldLockCheckboxUpdates = ref(false);
</script>
```
=> fix(VCheckboxBtn): reset checked state when readonly is true

packages/api-generator/src/locale/en/VTabs.json, packages/vuetify/src/components/VTabs/VTabs.tsx, packages/vuetify/src/components/VTabs/__tests__/VTabs.spec.cy.tsx
fixes #19855 
```vue
<template>
<v-app>
<v-container>
<v-tabs v-model="value">
<v-tab :value="1">A</v-tab>
<v-tab :value="2">B</v-tab>
<v-tab :value="3">C</v-tab>
</v-tabs>
<v-divider class="my-8" />
<v-tabs v-model="value" :items="items" />
</v-container>
</v-app>
</template>
<script setup>
const value = ref(2)
{ text: 'A', value: 1 },
{ text: 'B', value: 2 },
{ text: 'C', value: 3 },
]
</script>
```
=> fix(VTabs): render tabs correctly using items

packages/vuetify/src/composables/__tests__/filter.spec.ts, packages/vuetify/src/composables/filter.ts
fixes #19596 
```vue
<template>
<v-app>
<v-container>
<v-data-table
:custom-filter="filterOnlyCapsText"
>
<template #top>
<v-text-field
class="mx-4"
label="Search (UPPER CASE ONLY)"
/>
</template>
<template #body.append>
<tr>
<td />
<td>
<v-text-field
v-model="calories"
label="Less than"
type="number"
/>
</td>
<td colspan="4" />
</tr>
</template>
</v-container>
</v-app>
</template>
<script setup>
const search = ref('')
const calories = ref('')
const desserts = ref([
{
calories: 159,
},
{
calories: 237,
},
{
calories: 262,
},
{
calories: 305,
},
{ …
```
=> fix(VDataTable): fix filter not work

packages/vuetify/src/labs/VNumberInput/VNumberInput.tsx
fix https://github.com/vuetifyjs/vuetify/issues/19953
I fixed it because attr was not used.
```vue
<v-app>
<v-container>
<v-text-field
aria-autocomplete="none"
autocomplete="off"
label="Label"
aru
:hideInput="false"
:inset="false"
:reverse="false"
aria-autocomplete="none"
autocomplete="off"
controlVariant="default"
label=""
></v-number-input>
</v-container>
</v-app>
```
=> fix(VNumberInput): attributes fall through to root

packages/vuetify/src/components/VList/VList.tsx, packages/vuetify/src/labs/VTreeview/VTreeview.tsx
fixes #19919
- Open action **SHOULD NOT** trigger any re-rendering
- VTreeview has redundant re-rendering from `v-model:opened` change
- This fix should prevent some of redundant renderings and enhance performance noticeably
- After this PR, the remaining redundant rendering should be resolved in the upstream library babel-plugin-jsx
```vue
<template>
<v-treeview 
:items="items"
@update:opened="openedUpdate"
></v-treeview>
</template>
<script>
computed: {
items: () => {
const GetChildren = id => {
const nodes = []
for (let i = 0; i < 100; i++) {
nodes.push({
id: `${id}-${i}`,
title: `Example child item ${i}`,
})
}
return nodes
}
const nodes = []
for (let i = 0; i < 100; i++) {
nodes.push({
id: i,
title: `Example item ${i}`,
children: GetChildren(i),
})
}
return nodes
}, …
```
=> fix(VTreeview): prevent redundant treeview re-render during open

packages/vuetify/src/labs/VTimePicker/VTimePickerClock.tsx, packages/vuetify/src/labs/VTimePicker/VTimePickerControls.tsx
**Actual Behavior**
When using `disabled` props, only style changed, VTimePicker can still be interacted https://play.vuetifyjs.com/#eNqVUMFOwzAM/RUr4gDS2t6rMmkfwYlyCImHAmkSJU5hmvrvuInKQNqBXSK/5+fn+D2fRYqqO4TQzhlFLwbCKVhJuB8dwDA30X+CtObNPY5CoSOMo4D3nMgcT0ylIBU2Mvrs9CjKUBkjM2ETjPrACHMzeY2W1ZVgA22SfLWo90P3R/tvg6Sit3b1uM2rcnDFcuv0VjqdlAzIzTtOZb205SUcy6lN08Hpp3CRb9srvvqHleMYuR66X/Ey5CtMoCLCr+AjgcajzJbgXP20JHn/sCGAiJSju2CAuqcHl63dbfRSi6UQDIbuZ5NYdkW6Pi/f6kepuA==
**Expected Behavior**
Can not interact with VTimePicker when using `disabled`
```vue
<template>
<v-row
align="center"
justify="space-around"
>
<v-time-picker
v-model="picker"
disabled
scrollable
></v-time-picker>
<v-time-picker
v-model="picker"
scrollable
></v-time-picker>
<v-time-picker
v-model="picker" …
```
=> fix(VTimePicker): fix disabled props

packages/docs/src/examples/v-time-picker/prop-ampm-in-title.vue, packages/docs/src/examples/v-time-picker/prop-disabled.vue
1. Go to https://vuetifyjs.com/en/components/time-pickers/#disabled
2. The example isn't shown up
=> The reason is the example code using `$vuetify.breakpoint` which is deprecated: https://vuetifyjs.com/en/getting-started/upgrade-guide/#layout
*Note: Although after this fixed, the example is shown up, but `disabled` props doesn't work correctly. It might need to fix in another PR
=> docs(VTimePicker): fix example using display information

packages/vuetify/src/components/VFab/VFab.tsx
fixes #19944 
```vue
<template>
<v-card class="mx-auto" max-width="360">
<v-layout>
<v-app-bar absolute extended>
<template #extension>
<v-fab
:active="!hidden"
class="ms-4"
icon="mdi-plus"
location="bottom start"
size="small"
absolute
offset
/>
</template>
</v-app-bar>
<v-main>
<v-sheet class="pa-4 text-center" color="surface-light" height="300">
<v-btn
:text="hidden ? 'Show' : 'Hide'"
color="surface-variant"
width="80"
@click="hidden = !hidden"
/>
</v-sheet>
<v-sheet height="125">
<v-fab
:active="!hidden"
class="me-4"
icon="mdi-plus"
location="top end"
absolute
offset
/>
</v-sheet>
</v-main>
</v-layout>
</v-card>
</template>
const hidden = ref(false)
</script>
```
=> fix(VFab): change type for location prop

packages/vuetify/src/components/VOverlay/VOverlay.tsx
This checks if the target of VOverlay is an shadow dom element and attaches it to that one. This fixes issues when mounting app on shadow dom. This fixes #19943
Playground is not provided because this is setup in a different way, it can be examined by the repro here:
https://github.com/joelmandell/shadow_dom
Without applying this PR, v-overlay-container will be attached outside the shadow dom and not working correctly.
=> fix(VOverlay): App mounted in shadow dom

packages/docs/src/components/api/ApiTable.vue
When I open docs in Dark theme (which can be the default System theme) contrast of "name", "type" and "default" varies between `1` and `2.9` making crucial elements of component API table almost unreadable. It get's worse on other dark themes especially the one named "High Contrast" where gold text on nearly white background gets contrast score of `1.12`.
I wish I could add a `bg-opacity-10` like in TailwindCSS, but we don't have such capabilities in Vuetify. This `rgba(0,0,0,.1)` is my current override (pasted to Amino browser extension), but it sucks that other developers need to experience this.. hence this quick PR.
Note: Maybe [themes](https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/plugins/vuetify.ts#L121) should be adjusted to have better `surface-bright` color, …
=> fix(Docs): Quick remedy to contrast issues for dark themes

packages/vuetify/src/components/VAppBar/__tests__/VAppBar.spec.cy.tsx, packages/vuetify/src/composables/scroll.ts
fixes #19090 
After altering scrollHeight, determining scroll direction becomes invalid.
```vue
<template>
<v-layout ref="app" class="rounded rounded-md">
<v-app-bar color="grey-lighten-2" name="app-bar" scroll-behavior="hide" />
color="grey-darken-2"
name="drawer"
expand-on-hover
permanent
rail
/>
<v-main
class="d-flex flex-column align-center justify-center"
style="min-height: 300px"
>
<div v-for="n in 17" :key="n" class="pa-16 ma-2 w-50 bg-green text-center">
box {{ n }}
</div>
</v-main>
<v-footer class="justify-center" color="grey" name="footer" app>
FOOTER
</v-footer>
</v-layout>
</template>
```
=> fix(VAppBar): fix inability to scroll to the bottom

packages/vuetify/src/labs/VTreeview/VTreeview.tsx, packages/vuetify/src/labs/VTreeview/__tests__/VTreeview.spec.cy.tsx
Keep the fix for #19919
Add cy tests & fixes #20024
fixes #19997
```vue
<template>
<v-treeview
:items="items"
/>
</template>
<script>
computed: {
items: () => {
const GetChildren = id => {
const nodes = []
for (let i = 0; i < 100; i++) {
nodes.push({
id: `${id}-${i}`,
title: `Example child item ${i}`,
})
}
return nodes
}
const nodes = []
for (let i = 0; i < 2; i++) {
nodes.push({
id: i,
title: `Example item ${i}`,
children: GetChildren(i),
})
}
return nodes
},
},
methods: {
openedUpdate: function(e) {
this.opened = e;
console.log('openedUpdate', e)
}
},
data: () => ({
opened: [],
}),
}
</script>
```
=> refactor(VTreeview): avoid re-render by opened & respect openAll

packages/docs/src/pages/en/features/treeshaking.md
It confuses users that somehow vue or vuetify is looking at a boolean called btn and making it into full form button based on some naming convention.
=> docs(TreeShaking): Example code constant button should be same as used in template

packages/vuetify/src/components/VSlideGroup/VSlideGroup.tsx
fixes #20049
I am seeking to implement custom navigation buttons in the v-slide-group component and control their disabled state based on hasNext and hasPrev computed flags. The v-slide-group component already utilizes these flags internally, but they are not exposed, making it impossible to access them via ref. I used it like that in Vuetify 2, so that would also improve compatibility with previous version.
```javascript
<template>
<v-app>
<v-container>
<v-btn :disabled="prevDisabled" @click="prev">Prev</v-btn>
<v-btn :disabled="nextDisabled" @click="next">Next</v-btn>
<v-slide-group ref="slideGroup">
<v-slide-group-item v-for="n in 20" :key="n">
<v-card height="200" width="200">{{ n }}</v-card>
</v-slide-group-item>
</v-slide-group>
</v-container>
</v-app>
</template>
<script>
import { …
```
=> feat(VSlideGroup): Expose hasNext and hasPrev in v-slide-group

packages/vuetify/src/labs/VStepperVertical/VStepperVertical.tsx
fixes #20025 
```vue
<template>
<v-stepper-vertical eager>
<template v-slot:default="{ step }">
<v-stepper-vertical-item
:complete="step > 1"
subtitle="Personal details"
title="Step one"
value="1"
>
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi,
ratione debitis quis est labore voluptatibus! Eaque cupiditate minima,
at placeat totam, magni doloremque veniam neque porro libero rerum unde
voluptatem!
<template v-slot:next="{ next }">
<v-btn color="primary" @click="next"></v-btn>
</template>
<template v-slot:prev></template>
</v-stepper-vertical-item>
<v-stepper-vertical-item
:complete="step > 2"
subtitle="Contact Details"
title="Step two"
value="2"
>
Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi,
ratione debitis quis est labore voluptatibus! Eaque …
```
=> fix(VStepperVertical): provide defaults props eager for VStepperVerticalItem

packages/vuetify/src/labs/VNumberInput/VNumberInput.tsx
fixes #20056 
```vue
<template>
<v-app>
<v-container>
<v-number-input control-variant="default" />
<v-number-input control-variant="default">
<template #increment> inc </template>
<template #decrement> dec </template>
</v-number-input>
<v-number-input control-variant="split" />
<v-number-input control-variant="split">
<template #increment> inc </template>
<template #decrement> dec </template>
</v-number-input>
<v-number-input control-variant="stacked" />
<v-number-input control-variant="stacked">
<template #increment> inc </template>
<template #decrement> dec </template>
</v-number-input>
</v-container>
</v-app>
</template>
```
=> fix(VNumberInput): fix inc/dec slots with split control variant

packages/vuetify/src/labs/VTimePicker/VTimePicker.tsx, packages/vuetify/src/labs/VTimePicker/VTimePickerClock.tsx, packages/vuetify/src/labs/VTimePicker/VTimePickerControls.tsx
fixes #20085 
```vue
<template>
<v-app>
<v-container>
<v-time-picker
v-model="time"
format="24hr"
max="22:15"
min="9:30"
scrollable
/>
</v-container>
</v-app>
</template>
<script setup>
const time = ref()
</script>
```
=> fix(VTimePicker): fix types for emit events

packages/vuetify/src/labs/VNumberInput/VNumberInput.tsx
fixes #20083
```vue
<template>
<v-app>
<v-container>
v-model.trim="msg"
:hide-input="false"
control-variant="stacked"
suffix="€"
type="number"
width="250"
inset
/>
{{ msg }}
</v-container>
</v-app>
</template>
<script setup>
const msg = ref('')
</script>
```
=> fix(VNumberInput): allow press delete key

packages/api-generator/src/locale/en/VListItem.json
Added descriptions for the properties `lines`, `nav`, and `slim` to the `VListItem.json` documentation. These properties were missing and this addition aims to provide clarity and completeness to the documentation.
Not applicable for this documentation change.
=> docs(VListItem): Add descriptions for lines, nav, and slim properties

packages/vuetify/src/components/VDatePicker/VDatePickerMonth.tsx, packages/vuetify/src/composables/calendar.ts, packages/vuetify/src/composables/date/DateAdapter.ts, packages/vuetify/src/composables/date/adapters/vuetify.ts, packages/vuetify/src/labs/VCalendar/VCalendar.tsx
- Add missing first-day-of-week functionality
closes #19398 
<details>
```vue
<template>
<v-number-input v-model="firstDayOfWeek" />
<v-date-picker :first-day-of-week="firstDayOfWeek" />
<v-calendar :first-day-of-week="firstDayOfWeek" />
</v-container>
</template>
<script setup>
const firstDayOfWeek = ref(1)
</script>
```
</details>
=> fix(calendar): add missing first-day-of-week property support

packages/vuetify/src/components/VProgressLinear/VProgressLinear.sass, packages/vuetify/src/components/VProgressLinear/VProgressLinear.tsx
fixes #20111 
```vue
<template>
<v-app>
<v-container>
<v-row dense>
<v-col>
<h1 class="text-subtitle-1">Native Progress Indicator Element</h1>
<progress id="file" max="100" value="70" />
<br>
<progress id="progress-bar" aria-label="Content loading…" />
</v-col>
<v-col>
<h1 class="text-subtitle-1">Vuetify Progress Indicator</h1>
<v-progress-linear color="orange" model-value="20" />
<br>
<v-progress-linear color="green" indeterminate />
<br>
<v-progress-linear model-value="20" rounded />
<br>
<v-progress-linear indeterminate rounded />
<br>
:buffer-value="bufferValue"
color="deep-orange"
/>
<br>
buffer-value="60"
color="red-lighten-2"
model-value="40"
stream
/>
</v-col>
</v-row>
</v-container>
</v-app>
</template>
<script>
export default …
```
=> fix(VProgressLinear): render in forced-colors mode

packages/api-generator/src/locale/en/VField.json, packages/api-generator/src/locale/en/VInput.json, packages/api-generator/src/locale/en/VTextField.json, packages/vuetify/src/components/VField/VField.sass, packages/vuetify/src/components/VField/VField.tsx, packages/vuetify/src/components/VInput/VInput.sass, packages/vuetify/src/components/VInput/VInput.tsx, packages/vuetify/src/components/VTextField/VTextField.tsx, packages/vuetify/src/components/VTextarea/VTextarea.tsx
Automatically apply singleLine under the hood, and vertically align **appendInner**, **prependInner**, **clearIcon**, **label** and **input field** in the center.
```vue
<template>
<v-container class="pa-md-12 bg-grey">
<v-row>
<v-text-field
bg-color="white"
prepend-icon="$vuetify"
prepend-inner-icon="$vuetify"
placeholder="solo"
label="solo"
variant="solo"
center-affix
/>
<v-text-field
bg-color="white"
prepend-icon="$vuetify"
prepend-inner-icon="$vuetify"
placeholder="outlined"
label="outlined"
center-affix
/>
<v-text-field
bg-color="white"
prepend-icon="$vuetify"
prepend-inner-icon="$vuetify"
placeholder="filled"
label="filled"
variant="filled"
center-affix
/>
<v-text-field
bg-color="white"
clearable
prepend-icon="$vuetify" …
```
=> fix(VField/VInput): centerAffix doesn't work for underlined/plain

packages/vuetify/src/components/VDataTable/VDataTable.tsx, packages/vuetify/src/components/VDataTable/VDataTableServer.tsx, packages/vuetify/src/components/VDataTable/VDataTableVirtual.tsx, packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.cy.tsx, packages/vuetify/src/components/VDataTable/composables/group.ts, packages/vuetify/src/components/VDataTable/composables/sort.ts
fixes #20046 
```vue
<template>
<v-data-table
:group-by="groupBy"
disable-sort
/>
</template>
<script>
data () {
return {
groupBy: [
{
key: 'group',
order: 'desc',
},
],
headers: [
{ title: 'Dessert (100g serving)', key: 'name' },
{ title: 'Iron (%)', key: 'iron' },
{ title: 'Group', key: 'group' },
],
desserts: [
{
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1%',
gluten: false,
group: 1,
},
{
calories: 237,
fat: 9.0,
carbs: 37,
protein: 4.3,
iron: '1%',
gluten: false,
group: 1,
},
{ …
```
=> fix(VDataTable): support groupBy when sorting is disabled

packages/api-generator/src/locale/en/VField.json, packages/api-generator/src/locale/en/VInput.json, packages/vuetify/src/components/VField/VField.sass, packages/vuetify/src/components/VField/VField.tsx, packages/vuetify/src/components/VInput/VInput.sass, packages/vuetify/src/components/VInput/VInput.tsx, packages/vuetify/src/components/VTextField/VTextField.tsx, packages/vuetify/src/components/VTextarea/VTextarea.tsx, packages/vuetify/src/labs/VNumberInput/VNumberInput.tsx
This reverts commits b1f74e1703389b4e0c3ac7e2dbca44d378d31387 & 650ba2549aaeebfdd49842fdffec4d711c4f5980 & bc2f96a7d1e8f46eacd0704e986a978dc4b556d8.
#20064 introduces a breaking change that requires users to manually apply `center-affix` to `v-text-field` when their affix slots contain content that occupies the entire row. These changes will instead be cherry-picked to the `dev` branch.
=> Revert "fix(VField/VInput): centerAffix prop for underlined/plain (#20064)"

packages/vuetify/src/shims.d.ts
Starting with the VScode Volar extension `v2.0.20`, Vuetify components when using auto imports will show as `Unknown` by IntelliSense. 
This module augmentation has been done in many projects so far, i.e: https://github.com/nuxt/nuxt/pull/26541
The idea is to augment modules `vue`, `@vue/runtime-dom` and `@vue/runtime-core`
After augmenting all the proper modules, IntelliSense starts to work again.
=> fix: augment GlobalComponents in multiple vue modules

packages/vuetify/src/components/VDatePicker/VDatePickerMonth.tsx
Fix: When a startDate is set programmatically after Date Picker is rendered, rangeStart value should also be updated. So that when we click a date for the end date, the rangeStart won't get reset into what we click as endDate. 
Resolves #20168
```vue
<template>
<v-app>
<v-container>
<v-btn @click="handleSetDeliveryDateToEarliestPossible">
Set {{ earliestPossibleDeliveryDate.toLocaleDateString('de-DE') }} as
initial start date
</v-btn>
<v-date-picker
v-model="selectedDateRange"
color="secondary"
multiple="range"
width="100%"
hide-header
/>
</v-container>
</v-app>
</template>
<script setup>
import { ref } from 'vue';
const selectedDateRange = ref([])
const earliestPossibleDeliveryDate = ref(new Date()) // can be any date, here it's today for simplicity
function …
```
=> fix(VDatePickerMonth): range bug with programmatic startdate

packages/docs/src/examples/v-toolbar/prop-floating-with-search.vue
This just uses the normal 'image' prop, instead of 'img', that doesn't work in Vuetify 3
```vue
```
=> docs(v-toolbar): fix example with image prop

packages/vuetify/src/labs/VDateInput/VDateInput.tsx
fixes #20147 
```vue
<template>
<v-app>
<v-container>
<v-date-input v-model="date" readonly></v-date-input>
</v-container>
</v-app>
</template>
<script setup>
</script>
```
=> fix(VDateInput): apply readonly

packages/vuetify/src/components/VDataTable/VDataTable.tsx, packages/vuetify/src/components/VDataTable/VDataTableVirtual.tsx, packages/vuetify/src/components/VDataTable/composables/sort.ts
fixes #20045 
```vue
<template>
<v-data-table
:group-by="groupBy"
>
</template>
<script>
data() {
return {
groupBy: [
{
key: 'group.deep', // work with deep key now
order: 'desc',
},
],
headers: [
{ title: 'Dessert (100g serving)', key: 'name' },
{ title: 'Iron (%)', key: 'iron' },
],
desserts: [
{
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1%',
gluten: false,
group: {
deep: 1,
}
},
{
calories: 237,
fat: 9.0,
carbs: 37,
protein: 4.3,
iron: '1%',
gluten: false,
group: {
deep: 1,
}
},
{ …
```
=> fix(VDataTable): use item.raw and columns in sorting transform

packages/vuetify/src/components/VOtpInput/VOtpInput.tsx
fixes #20158 
```vue
<template>
<v-app>
<v-container>
// Copy and paste: 12345678
<v-otp-input v-model="otp" :length="5" />
Value: {{ otp }}
</v-container>
</v-app>
</template>
<script setup>
const otp = ref('')
</script>
```
=> fix(VOtpInput): slice value on paste

packages/vuetify/src/components/VList/__tests__/VListGroup.spec.cy.tsx, packages/vuetify/src/composables/nested/nested.ts
fixes #20199 
```vue
<template>
<v-card>
<v-layout>
:rail="rail"
permanent
@click="rail = false"
>
<v-list-item
prepend-avatar="https://randomuser.me/api/portraits/men/85.jpg"
title="John Leider"
nav
>
<v-btn
icon="mdi-chevron-left"
variant="text"
@click.stop="rail = !rail"
/>
</template>
</v-list-item>
<v-divider />
<v-list v-model:opened="open">
<v-list-item prepend-icon="mdi-home" title="Home"/>
<v-list-group v-if="!rail" value="Users">
<v-list-item
v-bind="props"
prepend-icon="mdi-account-circle"
title="Users"
/>
</template>
<v-list-group value="Admin">
<v-list-item v-bind="props" title="Admin" />
</template>
<v-list-item
v-for="([title, icon], i) in admins" …
```
=> fix(VListGroup): fix unmounting to clear opened

packages/vuetify/build/rollup.config.mjs
If it fixes an open issue, please link to the issue here.
resolves #https://github.com/vuetifyjs/vuetify/issues/19169
I checked it still works on linux/mac, but double check !
=> chore: fix build script output paths on windows

packages/vuetify/src/components/VMenu/VMenu.tsx
fixes #20248 
Instead of using the `!` operator, I just added some null checks before using the `overlay.value.contentEl`.
I don't think it should cause any issue since the issue occurs when the view is completely destroyed (through the router in the reported case), so there is no cleanup to do anyways
I used the same reproduction repo I provided in the issue to validate the changes:
https://github.com/Arinono/vuetify-vmenu-bug
```vue
<v-menu v-if="open" :close-on-content-click="false">
<v-btn v-bind="props">Open</v-btn>
</template>
<v-sheet class="pa-4">
<div class="d-flex">
<v-menu>
<v-btn style="display: block" v-bind="props">Sub menu</v-btn>
</template>
<v-sheet class="pa-4"> Click back in the input</v-sheet> …
```
=> fix(VMenu): check if element still exists before closing parent

packages/vuetify/src/directives/click-outside/__tests__/click-outside-shadow-dom.spec.ts, packages/vuetify/src/directives/click-outside/__tests__/click-outside.spec.ts, packages/vuetify/src/directives/click-outside/index.ts
ClickOutside directive uses global `onmousedown` and `click` events in the parent shadowRoot of the element when the element is inside the Shadow DOM.
When unmounted, the directive tries to remove those event handlers, but since the element is already unmounted, it can't find the parent shadowRoot, so the events are never removed.
This causes VOverlay content clicks to behave incorrectly, closing menus and submenus when they should stay open.
Using beforeUnmount instead of unmounted to remove event handlers in ClickOutside directive solves the issue.
fixes #19616
```vue
<template>
<v-menu v-bind="$attrs" location="right">
<v-btn v-bind="props" class="ma-5">Normal Menu</v-btn>
</template>
<v-list>
<v-menu location="right"> …
```
=> fix(click-outside): correctly remove shadow DOM event listeners

packages/vuetify/src/components/VSpeedDial/VSpeedDial.tsx
`content-class` is mentioned by [VSpeedDial API docs](https://vuetifyjs.com/en/api/v-speed-dial/#props-content-class) and should be applied down to the VMenu.
resolves #20051
```vue
<template>
<v-card class="pa-6">
<v-fab size="large" icon>
<v-icon>mdi-comment</v-icon>
<v-speed-dial
v-model="fabOpen"
:content-class="['bg-grey-lighten-3','rounded-pill','elevation-2','pa-2']"
activator="parent"
location="right center"
>
<v-btn key="1" color="success" icon="$success" />
<v-btn key="2" color="info" icon="$info" />
<v-btn key="3" color="warning" icon="$warning" />
<v-btn key="4" color="error" icon="$error" />
</v-speed-dial>
</v-fab>
</v-card>
</template>
<script setup>
const fabOpen = ref(true)
</script>
```
=> fix(VSpeedDial): Use `content-class`

packages/vuetify/src/components/VSnackbar/VSnackbar.tsx
fixes #20306
- **Problem:** When hovering over `SnackBar`, `isHovering` is truthy as expected but closing `SnackBar` does not fire `onPointerLeave` => `isHovering` is still truthy after the component is closed.
And due to this condition `!isHovering && <VProgressLinear>` from `VSnackBar.tsx:239`, the `ProgressBar` does not appear when reopening the `SnackBar`.
- **Cause**: I found that this causes by the transition duration/delay from `MaybeTransition` in `VOverlay`. Therefore, I think that hover state should be correctly handled after the transition ends, which is addressed in this PR.
I reuse the example from https://github.com/vuetifyjs/vuetify/issues/20306
```vue
<template>
<v-btn color="orange-darken-2" @click="snackbar = true">
Open Snackbar
</v-btn> …
```
=> fix(VSnackbar): handle pointerleave event after transition ends

packages/vuetify/src/components/VFileInput/VFileInput.tsx
fixes #20101
reproduce example
```
<template>
<v-app>
<v-container>
<v-form ref="form">
<v-file-input v-model="files" />
</v-form>
<v-btn @click="resetForm">reset form</v-btn>
</v-container>
</v-app>
</template>
<script setup>
const files = ref()
const form = ref()
const resetForm = () => form.value.reset()
</script>
```
=> fix(VFileInput): emit null after VForm reset()

packages/docs/src/examples/v-form/misc-exposed.vue, packages/docs/src/examples/v-form/misc-vee-validate.vue, packages/docs/src/examples/v-form/prop-fast-fail.vue
The VForm docs examples include a few example components, which contain some example validation rules to demonstrate their usage.
However a few of these have some mistakes in them, which are not a huge deal, but a bit confusing, when you are encoutering them.
This PR fixes three of these mistakes I found, e.g. where the displayed "count" property or the validation message was not matching the actual validation rule.
=> docs(VForm): fix validation mistakes in examples

packages/docs/package.json, packages/vuetify/package.json, pnpm-lock.yaml
This PR bumps vite to 5.4.0 in vuetify and docs packages: sass modern options only in docs, we can also include in vuetify package (no idea if vue-ssr will work: the package seems out dated, doesn't support vite 5.0)
NA
=> chore: update vite to 5.4.0

packages/vuetify/build/rollup.config.mjs
`node.id` from sass not normalized, styles nodes in `labs` bundler empty when filtering: this PR checks paths via upath normalize
NA
=> chore: fix missing labs components css on Windows

packages/docs/src/examples/v-tooltip/usage.vue
=> docs(VTooltip): fix usage example button text

packages/vuetify/src/labs/VTreeview/VTreeviewChildren.tsx
resolves #20360
```vue
<template>
<v-container>
<p>Click exactly the icon to verify</p>
<v-treeview
v-model:activated="active"
v-model:opened="open"
:items="items"
:load-children="fetchUsers"
item-title="name"
activatable
open-on-click
/>
</v-container>
</template>
<script setup>
const active = ref([])
const open = ref([])
const users = ref([])
const items = computed(() => {
return [
{
name: 'Users',
children: users.value,
},
]
})
async function fetchUsers(item) {
await new Promise(r => setTimeout(r, 1500))
return fetch('https://jsonplaceholder.typicode.com/users')
.then(res => res.json())
.then(json => item.children.push(...json))
.catch(err => console.warn(err))
}
</script>
```
=> fix(VTreeview): Load children when expanded

packages/vuetify/src/components/VList/VList.tsx, packages/vuetify/src/components/VList/VListItem.tsx, packages/vuetify/src/composables/nested/nested.ts, packages/vuetify/src/labs/VTreeview/VTreeview.tsx, packages/vuetify/src/labs/VTreeview/VTreeviewItem.tsx, packages/vuetify/src/util/nested.ts
While loops used by components with nesting need some safety check to prevent freezing end-users tab. Performance overhead of the checks is close to none, while it makes a big difference in the field.
Error does not necessarily need to be developers fault. Data from the API may contain duplicates or it may be a result of some drag & copy functionality built on top of Vuetify's components.
I was advised to log a warning, but I just don't think it is better than throwing error
- warning inside while loop does not help – tabs usually freeze DevTools as well and devs might work with simplified data, leaving potential for errors in the field
- warning after validating `path`/`parents` collection – unnecessary performance overhead if we can have cheaper solutions
- warning + breaking from the …
=> fix(nested): Prevent infinite loops when resolving path

packages/vuetify/src/components/VDialog/VDialog.tsx
Remove useless `aria-expanded` attribute on dialog activators to follow [WAI-ARIA recommandations](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/).
When focusing a dialog activator, dialog will never already be expanded, so this information is useless and will pollute screen readers users.
```vue
<template>
<v-app>
<v-container>
<v-dialog>
<template #activator={ props }>
<v-btn v-bind="props">Open</v-btn>
</template> 
</v-dialog>
</v-container>
</v-app>
</template>
```
=> fix(VDialog): remove `aria-expanded` from activator

packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbsItem.tsx, packages/vuetify/src/components/VBtn/VBtn.tsx, packages/vuetify/src/components/VCard/VCard.tsx, packages/vuetify/src/components/VChip/VChip.tsx, packages/vuetify/src/components/VList/VListItem.tsx, packages/vuetify/src/composables/router.tsx
This PR adds an `aria-current="page"` attribute to VBtn, VCard, VChip, VListItem and VBreadcrumbsItem when active value from router is `true`.
closes #20399
=> fix(a11y): add `aria-current="page"` attribute to links

packages/vuetify/src/composables/nested/nested.ts, packages/vuetify/src/labs/VTreeview/VTreeview.tsx, packages/vuetify/src/labs/VTreeview/__tests__/VTreeview.spec.cy.tsx
fixes #20488
fixes #19404
```vue
<template>
<v-card class="mx-auto" max-width="500">
<v-sheet class="pa-4 bg-primary">
<v-text-field
clear-icon="mdi-close-circle-outline"
label="Search Company Directory"
clearable
dark
flat
hide-details
solo-inverted
<v-checkbox
v-model="caseSensitive"
label="Case sensitive search"
dark
hide-details
></v-checkbox>
</v-sheet>
<v-card-text>
<v-treeview
:custom-filter="filterFn"
:items="items"
return-object
open-all
>
<template v-slot:prepend="{ item }">
<v-icon
v-if="item.children"
:icon="`mdi-${item.id === 1 ? 'home-variant' : 'folder-network'}`"
></v-icon>
</template>
</v-treeview>
</v-card-text>
</v-card>
</template>
<script setup>
{
id: 1, …
```
=> fix(VTreeview): search doesn't work with return-object

packages/docs/src/examples/v-form/usage.vue
In the [form validation demo](https://vuetifyjs.com/en/components/forms/#usage) the validation error messages are not visible when the fields are invalid. Removing `hide-details` fixes this.
```vue
https://play.vuetifyjs.com/#eNrVU01v2zAM/SuEL0mQxm6HnQwn2w7badhh17oH1aYXAbLsSVRaoMh/L6UkstOmHyjaQw3YkEjqPfH58fIusabKfvR9unGY5ElB2PZKEK5KDVBsFk1nWtgs2q5GtSyTjVCyLpOQDfmq0ySkRrMPhaDpbuJ2X6WAX8sIF1/KBNqaV18jTqwjvKVFI1HV4wSMLtBIY0mLFsvkuCSvOqcJjac4f5Q0TqFn9yf/+vXDCiWuA/4vjw+nCAz+d9Lg0c1WRTa+9LhpTnDHHPkgIZT4UB1+M/xnkAFbIdWTbYbss33+XJwCeGuTw34YgV12PCU+4ueKN0U2Gjje2srInkIV3vadIaixEU4R3O3QakEih+kMliuY7mOshx/LHBqhLJ4dgnFUcphMYvTgm6NgtEMOl0NfjOrQE0Ue/8gGpiEzY5nIGQ1kHI5/sNcvJCZ/GBekjXqmk6FqG9lfZPqWKtT/aA3FEi7OX8vbOrbwNQK3ZYHWQvNZqNbCiIrnw56+y1VcBe8cqTS46Z1l2pnwINSbdMrS+fd0XpZpOs9SQkt78tezH+QKXnpenO0sLLbev9 …
```
=> docs(VForm): remove hide-details from usage example

packages/docs/src/pages/en/components/inputs.md
If `persistent-hint` props is true, hint will overwrite `messages` but not `error-messages`. 
It's less confusing to replace the word 'messages' to 'error-messages' I guess.
Note:
| persistent-hint | focus | precedence |
|--------|--------|--------|
| false | false | error-messages > messages ~> hint~ |
| false | true | error-messages > hint > messages |
| true | false | error-messages > hint > messages |
| true | true | error-messages > hint > messages | 
https://github.com/t407o/vuetify/blob/e8b80cd66a0ca76a24e7ef4c92ea1357391b1e81/packages/vuetify/src/components/VInput/VInput.tsx#L113-L121
It looks the behavior of `hint` with `persistent-hint = true` is almost the same as `messages` (always be displayed if no error). I don't know how we use them properly... never mind.
=> docs(VInput): correct hint props description

packages/docs/src/examples/v-treeview/misc-selectable-icons.vue
I have stumbled upon a misaligned divider and initially thought it should be rather `border-e`, but opted to make it play with responsive layout of this example.
```vue
<v-divider vertical />
replaced with:
<v-divider :vertical="$vuetify.display.mdAndUp" class="my-md-3" />
```
Technically we could make it default by including `.v-divider--vertical` in `VGrid.sass`, but since after migration I have `.v-row.my-0` all over my project, I suspect more people might have some margins or paddings that will make this small change introduce unnecessary visual regression... although maybe it is not a strong argument. Feel free to update this PR and include these rules.
```sass
.v-row > .v-divider--vertical
margin-bottom: settings.$grid-gutter * .5
margin-top: settings.$grid-gutter * .5
// and again …
```
=> docs(VTreeView): fix divider in example

packages/docs/src/examples/v-data-table/slot-headers.vue
Noticed that the example https://vuetifyjs.com/en/components/data-tables/basics/#headers-slot was missing the horizontal divider below the headers - it was using `<td>` instead of `<th>`.   Minor change to make this example consistent with the others on that docs page.
[Original](https://vuetifyjs.com/en/components/data-tables/basics/#headers-slot) on the left, [updated version (play.vuetify.js)](https://play.vuetifyjs.com/#eNqtmNtu4zYQhl+FNVrEBmzF8Wk3Qhy0yPaQbi8K9KpY54KWaZuILAoU5TY1/O4dSqJISqStbZqLRBqRw48zQ86PfDn1Mh7d/pCmwTEnvbD3IMghjbEgj6sEoYfjaIMFHgm8jgkK9wRvCM+Wq171tOqhkMIMadqQLCNcSJs0jY44zgnYE3wgq17hDhwq9+g4ymImDJcnFLE4PyTZENHsD8YF2QzRjgj5+ByxZIgE2+1iIt/RufYoffL62V5hyzg4Lt0imqgFJPUreas/BfBi+Cu97K13sGQpBg8xziTsgY8mKMp5xvgoZTQRhIPX76OYRq/wuT9Ay0eDt18uNFj1bKcIPZ7UvgNBBQT5fH64lUvZA5swxibp …
=> docs(VDataTable): update slot-headers example to use header cells

packages/vuetify/src/components/VBtnToggle/VBtnToggle.sass
fixes #20142 
```vue
<template>
<v-container>
<v-row>
<v-col class="py-2" cols="12" sm="6">
<p>Mandatory</p>
<v-btn-toggle v-model="toggle_one">
<v-btn value="eins">
<v-icon>mdi-format-align-left</v-icon>
</v-btn>
<v-btn value="zwei">
<v-icon>mdi-format-align-center</v-icon>
</v-btn>
<v-btn value="drei">
<v-icon>mdi-format-align-right</v-icon>
</v-btn>
<v-btn value="vier">
<v-icon>mdi-format-align-justify</v-icon>
</v-btn>
</v-col>
<v-col class="py-2" cols="12" sm="6">
<p>Mandatory</p>
<v-btn-toggle v-model="toggle_one" variant="plain">
<v-btn value="eins">
<v-icon>mdi-format-align-left</v-icon>
</v-btn>
<v-btn value="zwei">
<v-icon>mdi-format-align-center</v-icon>
</v-btn>
<v-btn value="drei">
<v-icon>mdi-format-align-right</v-icon>
</v-btn>
<v-btn value="vier"> …
```
=> fix(VBtnToggle): plain variant button opacity when selected

packages/docs/src/components/about/TeamMember.vue, packages/docs/src/components/about/TeamMembers.vue
- (`about/TeamMembers.vue`) component styles were leaking and affecting `ApiTable.vue`
- (`about/TeamMembers.vue`) page styles were overlapping and not really required
Bug was introduced around 1 month ago ([6b69a72](https://github.com/vuetifyjs/vuetify/commit/6b69a72759b0fc6e934c31df3197e993c9e4fee2)), so hopefully there are no more places that include additional bottom spacing to compensate for leaking styles.
fixes #20664
=> docs: fix styles leaking from TeamMember

packages/docs/src/pages/en/components/lists.md
Prop name `selection-strategy` is actually called `select-strategy`.
=> docs(VList): fix misnamed prop

packages/docs/components.d.ts, packages/docs/src/components/home/EpicmaxSupport.vue, packages/docs/src/i18n/messages/en.json, packages/docs/src/pages/en/index.md
This PR adds Epicmax support section for `home`  page.
PR contains new component for the section and markup changes.
```vue
<template>
<section class="bg-light-blue-darken-4 py-8">
<h2 class="v-heading mb-2 text-h4 text-sm-h4">{{ t("epicmax.title") }}</h2>
<p class="mx-auto" style="max-width: 700px">{{ t("epicmax.message") }}</p>
<v-btn
:aria-label="t('epicmax.learn-more')"
class="px-16 text-light-blue-darken-4"
color="grey-lighten-5"
href="https://www.epicmax.co/?ref=vuetify"
rounded="0"
size="large"
variant="flat"
>
<span
class="text-capitalize font-weight-regular"
v-text="t('epicmax.learn-more')"
/>
</v-btn>
</section>
</template>
<script setup>
const { t } = useI18n()
</script>
```
=> docs: add Epicmax support section to home page

packages/vuetify/src/components/VBadge/VBadge.sass
Applies `$badge-font-family` and `$badge-icon-padding`. Both were not used after migration from v2 to v3. I assume it was not intentional.
resolves #19834
[Demo on Stackblitz](https://stackblitz.com/edit/vuetify-sass-variables-vbadge?file=app.vue%2Cassets%2Fmain.scss%2Cassets%2Fsettings.scss%2Cpackage.json)
=> fix(VBadge): restore unused SASS variables

packages/vuetify/src/components/VChip/VChip.tsx, packages/vuetify/src/components/VDatePicker/VDatePickerHeader.tsx, packages/vuetify/src/components/VList/VList.tsx, packages/vuetify/src/components/VStepper/VStepper.tsx, packages/vuetify/src/components/VStepper/VStepperItem.tsx
- followup to [a4ef229](https://github.com/vuetifyjs/vuetify/commit/a4ef229402e730e39546b9afc2c5de49de13cf6f)
- does not cover labs components (VTreeView, VCalendar) to avoid merge conflicts
fixes #19858 
```vue
<template>
<div style="zoom: 1.2">
<v-card class="mx-auto my-3" width="300">
<v-list :expand-icon="expandIcon" :collapse-icon="collapseIcon">
<v-list-group value="Animals">
<template #activator="{ props: on }">
<v-list-item v-bind="on" title="Animals" />
</template>
<v-list-item v-for="(t, i) in ['Ant', 'Boar']" :title="t" :key="i" />
</v-list-group>
</v-list>
</v-card>
<v-card class="mx-auto my-3" width="600">
<v-stepper :complete-icon="checkIcon" :edit-icon="editIcon" :error-icon="bugIcon">
<v-stepper-item title="Problem" value="0" error />
<v-divider /> …
```
=> fix: expand accepted icon prop types

packages/api-generator/src/locale/en/VChipGroup.json, packages/vuetify/src/components/VChip/VChip.tsx, packages/vuetify/src/components/VChipGroup/VChipGroup.tsx
Very quick fix, I did not dwell on it too much.
resolves #19678
<details>
<summary>Playground</summary>
```vue
<template>
<v-col cols="12" sm="7" md="6" lg="5">
<h5 class="mt-6 mb-3">`base-color` + `selected-class`</h5>
<v-sheet elevation="10" rounded="xl">
<div class="pa-4">
<v-chip-group column>
<v-chip base-color="red" selected-class="text-primary" v-for="tag in 3" :key="tag">
chip {{ tag }}
</v-chip>
<v-chip-group selected-class="text-primary" column base-color="red">
<v-chip v-for="tag in 3" :key="tag">
chip {{ tag }}
</v-chip>
<div class="d-flex ga-2 py-2">
<v-chip base-color="red">base color</v-chip>
<v-chip color="red">color</v-chip>
</div>
</div>
</v-sheet>
<h5 class="mt-6 mb-3">Without `selected-class`</h5>
<v-sheet …
```
=> feat(VChip): add base-color prop

packages/docs/src/examples/border/colors.vue
=> docs(border): fix typo in colors example

packages/docs/src/examples/v-progress-linear/usage.vue
=> docs(VProgressLinear): change dark-blue color selection

packages/vuetify/src/components/VChip/VChip.tsx
`active-class` on VChip was working in v2, but not in v3.
I could not find any related issue.
```vue
<template>
<v-app>
<v-container>
<v-chip active-class="text-red" text="Home (should be red)" to="/" />
<v-chip active-class="text-red" text="Another" to="/another" />
<v-chip text="Regular" />
</v-container>
</v-app>
</template>
```
=> fix(VChip): utilize `active-class`

packages/vuetify/src/components/VField/VField.tsx
fixes #20427 
```vue
<template>
<v-app>
<v-container>
<v-text-field label="Label" />
</v-container>
</v-app>
</template>
```
=> fix(VField): only render field label if label is passed

packages/vuetify/src/components/VSelectionControl/VSelectionControl.sass
fixes #18804
- Q: do we need it for `v-checkbox-btn` as well? I cannot imagine anyone using it with `label` prop, but it is available nevertheless.
```vue
<template>
<v-container>
<v-checkbox hide-details label="Checkbox"></v-checkbox>
<v-checkbox hide-details disabled label="Checkbox disabled"></v-checkbox>
<v-checkbox hide-details :model-value='true' label="Checkbox selected"></v-checkbox>
<v-switch hide-details label="Checkbox"></v-switch>
<v-switch hide-details disabled label="Checkbox disabled"></v-switch>
<v-switch hide-details :model-value='true' label="Checkbox selected"></v-switch>
<v-radio label="Radio button"></v-radio>
<v-radio disabled label="Radio button disabled"></v-radio>
<v-radio :model-value='true' label="Radio button selected"></v-radio> …
```
=> fix(VSelectionControl): label opacity matching regular text

packages/docs/src/examples/v-combobox/misc-advanced.vue, packages/docs/src/pages/en/components/combobox.md
Advanced example for VCombobox ported [from v2 docs](https://v2.vuetifyjs.com/en/components/combobox/#advanced-custom-options)
<details><summary>Playground</summary>
```vue
<template>
<v-combobox
v-model:search="search"
:custom-filter="filter"
:items="items"
label="Search for an option"
variant="solo"
hide-selected
multiple
return-object
>
<template v-slot:selection="{ item, index }">
<v-chip
v-if="item === Object(item)"
:color="`${item.raw.color}-lighten-3`"
:text="item.title"
size="small"
variant="flat"
closable
label
@click:close="removeSelection(index)"
></v-chip>
</template>
<template v-slot:item="{ props, item }">
<v-list-item v-if="item.raw.header && search">
<span class="mr-3">Create</span>
<v-chip
:color="`${colors[nonce - 1]}-lighten-3`" …
```
=> docs(VCombobox): restore advanced example

packages/vuetify/src/labs/VNumberInput/VNumberInput.tsx
The `useValidation` composable doesn't perform validation when the input value changes to `null`. When resetting the input, it sets the value to an empty string. Instead of assigning 0, the model should be reset to match this behavior. Using `null` for resetting is not viable because validation won't be triggered. Therefore, the model value should remain as the empty string in such cases to ensure proper validation behavior.
fixes #20607 
```vue
<template>
<v-app>
<v-container>
ref="input"
:model-value="model"
:rules="rules"
validate-on="input"
@update:model-value="onChange"
/>
<br />
<pre>{{ inputToJSON }}</pre>
</v-container>
</v-app>
</template>
<script setup>
import { ref, computed } from 'vue'
const input = ref()
const model = ref()
const rules = ref([
// required …
```
=> fix(VNumberInput): clearing v-number-input with backspace resets to 0

packages/docs/src/pages/en/features/theme.md, packages/vuetify/src/composables/__tests__/theme.spec.ts, packages/vuetify/src/composables/theme.ts
This PR adds two new optional properties to `ThemeOptions` that enable a conflict-free usage of multiple Vuetify instances, e.g., in an app with microfrontends using Vuetify with different themes.
- `stylesheetId`: Customizable `id` for generated `<style>` element to allow for multiple Vuetify instances accros microfrontends.
- `scope`: Customizable scope for classes in generated `<style>` element.
closes #4065
=> feat(theme): add stylesheetId and scope options

packages/vuetify/src/components/VProgressLinear/VProgressLinear.tsx
fixes #19894 
```vue
<template>
<v-app>
<v-container>
<v-progress-linear v-model="current" max="4" />
</v-container>
</v-app>
</template>
<script setup>
const current = ref(2)
</script>
```
=> fix(VProgressLinear): set aria-valuenow to current value

packages/vuetify/src/components/VSparkline/VBarline.tsx, packages/vuetify/src/components/VSparkline/VTrendline.tsx, packages/vuetify/src/components/VSparkline/util/line.ts
fixes #19262
```vue
<template>
<v-app>
<v-container>
<v-sparkline :model-value="values" :smooth="4" />
<v-sparkline :model-value="values" smooth />
<v-sparkline :model-value="values" smooth="1" />
<v-sparkline :model-value="values" :smooth="1" />
</v-container>
</v-app>
</template>
<script setup>
const values = [80, 75, 60, 55, 65, 60, 62, 58, 55, 65, 60, 68, 62, 58, 65, 70, 65, 75, 70]
</script>
```
=> fix(VSparkline): accept numeric value for smooth

packages/vuetify/src/labs/VDateInput/VDateInput.tsx
resolves #20690
```vue
<template>
<v-app>
<v-container>
<v-date-input />
<v-date-input>
<template #actions="{ save, cancel, isPristine }">
<v-btn variant="outlined" @click="cancel">
<v-icon>mdi-arrow-left</v-icon>
</v-btn>
<v-btn :disabled="isPristine" variant="outlined" class="flex-grow-1" @click="save">Save</v-btn>
</template>
</v-date-input>
</v-container>
</v-app>
</template>
```
=> feat(VDateInput): actions slot

packages/api-generator/src/locale/en/VTimeline.json, packages/api-generator/src/locale/en/VTimelineItem.json, packages/vuetify/src/components/VTimeline/VTimeline.sass, packages/vuetify/src/components/VTimeline/VTimelineItem.tsx
Restores control over `side` for individual VTimeline items
resolves #19363
```vue
<template>
<v-btn-toggle v-model="direction">
<v-btn value="vertical">vertical</v-btn>
<v-btn value="horizontal">horizontal</v-btn>
<v-container>
<h4>Default</h4>
<v-timeline :direction="direction">
<v-timeline-item
v-for="(item, i) in items"
:key="i"
size="x-small"
>
<v-card :color="item.color" :title="`Item ${i + 1}`" />
</v-timeline>
</v-container>
<v-container>
<h4>Side on items</h4>
<v-timeline :direction="direction">
<v-timeline-item
v-for="(item, i) in items"
:key="i"
:side="item.side"
size="x-small"
>
<v-card :color="item.color" :title="`Item ${i + 1} | ${item.side}`" />
</v-timeline>
</v-container>
<v-container>
<h4>Side on …
```
=> feat(VTimeline): side prop for individual items

packages/vuetify/src/composables/nested/nested.ts, packages/vuetify/src/composables/nested/openStrategies.ts, packages/vuetify/src/labs/VTreeview/VTreeviewChildren.tsx, packages/vuetify/src/labs/VTreeview/VTreeviewItem.tsx, packages/vuetify/src/labs/VTreeview/__tests__/VTreeview.spec.browser.tsx
fixes #20830
```vue
<template>
<h1>{{ opened }}</h1>
<v-treeview
:items="items"
return-object
:value-comparator="compare"
v-model:selected="selected"
v-model:opened="opened"
>
<template #prepend="{ isOpen }"> [{{isOpen}}] </template>
<template #append="{ isOpen }"> [{{isOpen}}] </template>
</v-treeview>
</template>
<script setup>
import { ref, watch } from 'vue'
function compare(a, b) {
console.log(a, b)
return a.id === b.id
}
const selected = ref([])
const opened = ref([])
watch(selected, v => {
console.log('selected', v)
})
{
id: 1,
title: 'Vuetify Human Resources',
children: [
{
id: 2,
title: 'Core team',
children: [
{
id: 201,
title: 'John',
},
],
},
],
},
])
</script>
```
=> fix(VTreeview): Incorrect isOpen state in the prepend slot when using return-object

packages/api-generator/src/locale/en/VChip.json
Custom description for `size` to avoid confusion. 
resolves #19356
closes #19374
Ad. [John's comment](https://github.com/vuetifyjs/vuetify/pull/19374#issuecomment-2028479123), I don't agree developers would really benefit from additional 6 props from `useDimension`. Chips are flexible pieces that are usually expected to adapt to the text inside. Using explicit width/height would fight against their nature. IMO padding helper classes are already good enough when I want to bump the size a little.
=> docs(VChip): more precise description for `size` prop

packages/docs/src/examples/v-data-table/misc-server-side-paginate-and-sort.vue, packages/docs/src/examples/v-data-table/server-search.vue
When selecting the  'All' pagination setting, the table would display all rows except for the last one, which would be chopped off due to a minor issue in the pagination logic. I added a check to see if the 'end' variable was -1 and if so, set the end parameter of the slice to undefined so it returns the whole array of items. I wanted to make this change to ensure that if anyone used the pagination logic included in the examples as a reference for their own, this minor issue wouldn't slip through the cracks and cause problems.
=> docs(VDataTableServer): fixes pagination examples

packages/api-generator/src/locale/en/VFileInput.json, packages/api-generator/src/locale/en/VSelect.json, packages/docs/src/examples/v-combobox/slot-no-data.vue, packages/docs/src/examples/v-date-picker/prop-multiple.vue, packages/docs/src/examples/v-file-input/prop-chips.vue, packages/vuetify/playgrounds/Playground.items.vue
`small-chips` prop does not exist, but the examples were not updated (until now)
=> docs: cleanup removed prop `small-chips`

packages/api-generator/src/locale/en/VEmptyState.json
Added descriptions for the property `size` to the `VEmptyState.json` documentation. 
**This addition aims to provide clarity and completeness to the documentation.**
Not applicable for this documentation change.
=> docs(VEmptyState): Improve description for "size" prop

packages/docs/src/examples/v-rating/slot-item.vue
remove onClick from v-rating item slot props
Click events are handled by a parent HTML element inside the v-rating component.
Therefore, they don't have to be implemented in the item slot. Also, the onClick function does not exist on the slot props.
=> docs(VRating): remove onClick from v-rating item slot props

packages/vuetify/src/components/VList/VListGroup.tsx, packages/vuetify/src/components/VList/VListItem.tsx
fixes #20523
```vue
<template>
<v-treeview :items="items" selectable>
<template #title="{item}">
<v-text-field placeholder="click or type something with spaces" />
</template>
</v-treeview>
</template>
<script>
data: () => ({
items: [
{
id: 1,
children: [
{ id: 2, title: 'Calendar : app' },
],
},
],
}),
}
</script>
```
=> fix(VList): ignore input element interactions

packages/docs/src/examples/v-list/misc-action-stack.vue, packages/docs/src/pages/en/components/lists.md
Adapted example for so called "action stack".
- ~~I wish it would not require so many margin and text color tweaks~~ reduced to just 2 margin tweaks
- ~~I had to override `line-clamp` for subtitle, because it follows `lines='...'` prop – is it a bug or intended behavior?~~ replaced `lines='two'` with `py-3`
```vue
<template>
<v-card class="mx-auto" max-width="500">
<v-toolbar color="pink">
<v-btn icon="mdi-menu"></v-btn>
<v-toolbar-title>Inbox</v-toolbar-title>
<v-btn icon="mdi-magnify"></v-btn>
<v-btn icon="mdi-checkbox-marked-circle"></v-btn>
</v-toolbar>
<v-list v-model:selected="selected" select-strategy="leaf">
<v-list-item
:key="item.id"
:value="item.id"
class="py-3"
active-class="text-pink"
>
<v-list-item-title>{{ item.title …
```
=> docs(VList): restore example for advanced action use

packages/vuetify/src/components/VImg/VImg.tsx
fixes #20914
ref #17848 
As per information in vuejs/core#4680, fix the behavior of Safari,
which changes depending on the order in which the attributes are 
described, causing the cache to be unexpected.
The only way to check if this is reproduced is with Safari on macos or Safari on iPhone/iPad.
```vue
<template>
<v-app>
<v-container>
<v-img crossorigin="anonymous" src="https://t3.ftcdn.net/jpg/00/92/53/56/360_F_92535664_IvFsQeHjBzfE6sD4VHdO8u5OHUSc6yHF.jpg" />
</v-container>
</v-app>
</template>
<script>
setup () {
return {
//
}
},
}
</script>
```
=> fix(VImg): set crossOrigin attribute before src

packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbsDivider.tsx
A divider in a list of breadcrumbs is only visual. It should be ignored by screenreaders.
```vue
<v-breadcrumbs :items="['Foo', 'Bar', 'Fizz']"></v-breadcrumbs>
```
```html
<ul class="v-breadcrumbs v-breadcrumbs--density-default">
<li class="v-breadcrumbs-item">Foo</li>
<li class="v-breadcrumbs-divider" aria-hidden="true">/</li>
<li class="v-breadcrumbs-item">Bar</li>
<li class="v-breadcrumbs-divider" aria-hidden="true">/</li>
<li class="v-breadcrumbs-item v-breadcrumbs-item--disabled">Fizz</li>
</ul>
```
=> fix(VBreadcrumbsDivider): add aria-hidden attribute

packages/vuetify/src/components/VField/VField.tsx
fixes #20751 
fixes #20772
```vue
<template>
<v-app>
<v-container>
<v-text-field :label="msg" />
<v-text-field :label="msg" single-line />
</v-container>
</v-app>
</template>
<script setup>
</script>
```
=> fix(VField): hide label with single-line

packages/vuetify/src/components/VMenu/VMenu.tsx
Because of the use of aria-own, vmenu's could not be used with screen readers.
Vemnu uses aria-control and no longer aria-owns because with aria-owns it was not possible to use the menu with some screen readers. It could be improved by setting role="menu" on the slot and role="menuItem" at every single item, but this could break things depending on slot content.
```vue
<template>
<div class="d-flex justify-space-around">
<v-menu>
<v-btn
v-bind="props"
>
Activator slot
</v-btn>
</template>
<v-list role="menu">
<v-list-item
:key="index"
:value="index"
role="menuItem"
>
</v-list-item>
</v-list>
</v-menu>
<v-btn
>
Parent activator
<v-menu …
```
=> fix(VMenu): replace aria-owns with aria-controls

packages/vuetify/src/composables/router.tsx
Make use of $router global safer.
Code breaks if something that isn't a vue-router inhabits the global Vue var "$router". For example, I'm using a different router and it installed itself to the global name "$router" but it doesn't have a beforeEach method. I don't think "$router" has been reserved specifically for vue-router or any router implementation.
```vue
```
=> fix(router): check $router.beforeEach exists before using

packages/vuetify/src/components/VSelect/VSelect.tsx
fixes #20358 
Description
This PR addresses an issue where the keyboard navigation in the v-select component was not working properly when multiple was set to true. Users were unable to use the keyboard for select any item.
please let me know if debouncing should be applied in this.
Changes Made
Remove the condition in the return statement which stops the function execution
Testing:
Verified the fix locally by passing .
All relevant tests are passing.
Recording
https://github.com/user-attachments/assets/c9a9c1a0-6fbe-4d55-8070-34a3d0369204
=> fix(VSelect): remove multiple check for keyboard lookup

packages/vuetify/src/components/VDataTable/composables/paginate.ts
Follow-up on [a2f16f4](https://github.com/vuetifyjs/vuetify/commit/a2f16f44f43d8a0996ee4992b01f7a0ef13d42b7) from 8 months ago. `immediate: true` was used in V2 ([VData.ts - line 266](https://github.dev/vuetifyjs/vuetify/blob/v2-stable/packages/vuetify/src/components/VData/VData.ts)), but it was not obvious from the wording in the documentation. I think it was not intentional to write `watch` without it.
fixes #20440
```vue
<template>
<v-data-table
:items="items"
@update:current-items="console.log('current-items', $event)"
/>
</template>
<script setup>
{ title: 'Vegetable', key: 'name' },
]
const …
```
=> fix(VDataTable): emit current items immediately

packages/vuetify/src/components/VInput/VInput.tsx, packages/vuetify/src/components/VMessages/VMessages.tsx
This PR moves `id`, `role="alert"` and `aria-live="polite"` attributes from `VMessages` to `VInput` details content.
This improve ARIA support for additional details that are not messages, such as counter or other custom details slot.
```vue
<template>
<v-app>
<v-container>
<v-textarea label="Body" maxlength="255" counter />
</v-container>
</v-app>
</template>
```
=> fix(VInput/VMessages): move aria attributes to details

packages/vuetify/src/components/VField/VField.sass
fixes  [#20305](https://github.com/vuetifyjs/vuetify/issues/20305)
- Problem: The end of the text field won't be rounded, and the text field will be bigger than the max-width set.
- Cause: `.v-field__outline__notch` sets a width larger than the specified max-width value.
- Solution: `.v-field__outline__notch` sets max-width according to the element's height.
I reused reproduction provided by  [#20305](https://github.com/vuetifyjs/vuetify/issues/20305)
```vue
<template>
<v-app>
<v-container>
<v-text-field
label="ravuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuusuuus"
rounded
/>
</v-container>
</v-app>
</template>
<script>
setup () {
return {
//
}
},
}
</script>
```
=> fix(VField): rounded with long label border-radius

packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.cy.tsx, packages/vuetify/src/components/VDataTable/composables/group.ts
fixes #20313 
* Problem: `items` slot prop contains duplicated items when a group is expanded
* Cause: `items` slot prop in the parent component is `paginatedItemsWithoutGroups`. This items are first flattened from its group in `useGroupedItems` (`VDataTable.jsx:163`) and then extracted to rows in `extractRows` (`VDataTable.jsx:169`). The extraction again flattens the items from its group which causes the duplication
* Solution: make `extractRows` operation returns unique items
I reused reproduction provided by https://github.com/vuetifyjs/vuetify/issues/20313
```vue
<template>
<v-data-table
:group-by="groupBy"
items-per-page="-1"
>
<template #body.append="{ items }"> {{ items.length }} </template>
</template>
<script> …
```
=> fix(VDataTable): show correct items count after expanding group

packages/vuetify/src/composables/display.ts
resolves #19883 
The `mobile-breakpoint` prop requires `:mobile='null'` to work, otherwise it is ignored. It is not intuitive and developers ask about it on Discord or assume it does not work, because components' API docs don't mention this requirement.
> The reason Docs do not use description from api-generator » ... » [display.json](https://github.com/vuetifyjs/vuetify/blob/master/packages/api-generator/src/locale/en/display.json) is that most components already have their own description for `mobile` prop.
I wish we could let user work with `mobile-breakpoint` and don't bother about the other prop. The logic could then be:
1. If `mobile === true`, then force mobile view
2. If `mobile-breakpoint` is set, accept it's value to resolve mobile state
3. All defaults (not using these props) …
=> fix(useDisplay): more intuitive use of `mobile-breakpoint`

packages/vuetify/src/components/VField/VField.sass
fixes #20734
```vue
<template>
<v-form>
<v-text-field
variant="solo"
v-model="label"
/>
<div class="d-flex ga-3 align-center">
rounded:
<v-chip-group filter color="primary" v-model="rounded">
<v-chip value="sm" text="sm" />
<v-chip value="lg" text="lg" />
<v-chip value="xl" text="xl" />
<v-chip :value="true" text="true" />
<v-chip value="pill" text="pill" />
</div>
<v-row>
<v-col cols="12" sm="6">
<v-text-field :label="label" model-value="asd" prepend-icon="mdi-map-marker" :rounded="rounded" />
<v-text-field :label="label" model-value="asd" prepend-inner-icon="mdi-map-marker" :rounded="rounded" />
<v-text-field append-icon="mdi-map-marker" :label="label" model-value="asd" :rounded="rounded" />
<v-text-field …
```
=> fix(VField): floating label respect paddings to avoid overflow

packages/vuetify/src/components/VDataTable/types.ts
`mobile` should not appear on [API docs for v-data-table](https://vuetifyjs.com/en/api/v-data-table/#props-headers), because it is not utilized anywhere.
~~I wish I could fully verify the change locally, but the project does not build at the moment due to chai TS issues. Hopefully it is the only place to change.~~ Verified locally.
=> docs(VDataTable): remove unused mobile prop from headers type

packages/vuetify/src/composables/display.ts
follow-up to #20311
and alternative to #20930
resolves #20932
```ts
const { mobile } = useDisplay()
console.log({ mobile }) // used to work before v3.7.8, now it is always false
// workaround: useDisplay({ mobile: null })
```
=> fix(useDisplay): keep default behavior when used without args

packages/vuetify/src/labs/VTreeview/VTreeview.tsx, packages/vuetify/src/labs/VTreeview/VTreeviewChildren.tsx
fixes #20781
```vue
<template>
<v-treeview :items="items" item-value="id" activatable>
<template v-slot:title="{ item }"> <b>title - {{ item.title }}</b>  </template>
<template v-slot:subtitle> subtitle </template>
<template v-slot:append> append </template>
<template v-slot:prepend> prepend </template>
<template v-slot:divider> <v-divider /> </template>
</v-treeview>
</template>
<script>
data: () => ({
items: [
{
id: 1,
children: [
{ id: 2, title: 'Calendar : app', subtitle: 'CSub' },
{ type: 'divider' },
{ type: 'divider' },
],
},
{ type: 'divider' },
{
id: 5,
title: 'Documents :',
children: [
{
id: 6,
title: 'vuetify :',
children: [
{
id: 7,
title: 'src :',
children: [
{ id: …
```
=> feat(VTreeview): Add subtitle & divider slots support 

packages/api-generator/src/locale/en/VStepperVerticalItem.json
Fixed missing event description in documentation:
=> docs(VStepperVertical): fix "click:prev" event name

packages/vuetify/.eslintrc.js, packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VList/VList.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx, packages/vuetify/src/components/VSelect/__tests__/VSelect.spec.browser.tsx, packages/vuetify/src/composables/list-items.ts, packages/vuetify/src/composables/nested/selectStrategies.ts, packages/vuetify/src/util/helpers.ts
fixes #20703
Time to run `transformIn`, primitive values:
| Item # | Before | ~~After~~ | After |
|--------|--------|--------|--------|
| 1k | 320ms | ~~56ms~~ | 0.5ms |
| 10k | 40sec | ~~780ms~~ | 1ms |
| 100k | &infin; | ~~75sec~~ | 8ms |
| 1M | &infin; | ~~&infin;~~ | 125ms |
Object values (`{ key: i }`):
| Item # | Before | After |
|--------|--------|--------|
| 1k | 900ms | 33ms |
| 10k | 88sec | 2.5sec |
| 100k | &infin; | &infin; |
| 1M | &infin; | &infin; |
return-object with item-value set appropriately uses primitive value lookup
```vue
<template>
<v-app>
<v-container>
v-model="selectedItems"
:items="items"
label="test"
multiple
>
<template #prepend-item>
<v-list-item @click="selectAll()">
<v-list-item-title> Select all </v-list-item-title>
</v-list-item> …
```
=> fix(VSelect): improve selection performance

packages/vuetify/src/components/VTimeline/VTimeline.sass
The alignment of timeline items is not consistent across various usage types:
- when using default alignment
- when using `side` on `VTimeline`
- when using `side` on `VTimelineItems`
I aimed to keep all items (body and opposite) close to the center line. It then behaves the same as in v2.
Users that wish to restore previous behavior can do it with `[align|justify]-self: stretch !important`. For example:
```css
/* justify-self for vertical / align-self for horizontal */
.v-timeline-item__body { justify-self: stretch !important; }
.v-timeline-item__opposite { justify-self: stretch !important; } 
```
```vue
<template>
<v-toolbar theme="dark">
<v-btn-toggle class="my-2 mx-auto" v-model="direction">
<v-btn value="vertical">vertical</v-btn>
<v-btn value="horizontal">horizontal</v-btn> …
```
=> fix(VTimeline): alignment consistency

packages/vuetify/src/directives/ripple/index.ts
fixes #12288
Resolve the issue of the fixed ripple animation not displaying properly, as reported in #12288
I didn't solve the problem of incorrect touch position because I didn't reproduce the problem
```vue
<template>
<v-app>
<v-container>
<v-btn />
</v-container>
</v-app>
</template>
<script>
setup () {
return {
//
}
},
}
</script>
```
=> fix(VRipple): no animation on mobile

packages/vuetify/src/components/VDatePicker/VDatePickerMonth.tsx, packages/vuetify/src/composables/calendar.ts
`display-value` does not affect VDatePicker and should not appear in API docs to avoid confusion
resolves #20863
=> docs(VDatePicker): remove display-value from props list

packages/vuetify/src/labs/VDateInput/VDateInput.tsx
- noticed by colleague on Discord
```vue
<template>
<v-app>
<v-container>
<v-select rounded="pill" :items="['item', 'item2', 'item3']" />
<v-date-input rounded="pill" />
<v-date-input rounded="xl" />
</v-container>
</v-app>
</template>
```
=> fix(VDateInput): do not pass `rounded` to the picker

packages/api-generator/src/locale/en/VVirtualScroll.json
I fought for hours with this: VVirtualScroll's `renderless` prop needs a scrolling parent which much be positioned. Otherwise, `markerRef` is the wrong reference, and offsets are the wrong one.
```vue
```
=> docs(VVirtualScroll): renderless needs a positioned ancestor

packages/docs/src/pages/en/getting-started/contributing.md
This might help some people, as without doing this you get unexpected behaviour
=> docs(contributing): suggest to clear vite's cache when using pnpm link

packages/vuetify/src/components/VDataTable/composables/sort.ts
Fixes #20985
What I Did: The issue was with must-sort and multi-sort enabled, sorted columns couldn't be removed, only toggled ascending/descending. I modified toggleSort so in multi-sort mode, columns sorting descending are removed if multiple sorts are active, but toggle back to ascending if they're the only sorted column (satisfying must-sort).
How to Verify: Click a column header to sort ascending, then again for descending. Add another sorted column to test multi-sort - when you click the descending column, it should get removed since there's multiple sorts. Try with just one sorted column too - clicking it should just flip the sort direction instead of removing it.
```vue
<template>
<v-app>
<v-container>
<v-data-table
:must-sort="true" …
```
=> fix(DataTable): allow removal of additional sortings

packages/docs/src/examples/v-number-input/prop-control-variant.vue, packages/docs/src/pages/en/components/number-inputs.md, packages/vuetify/src/labs/VNumberInput/VNumberInput.sass, packages/vuetify/src/labs/VNumberInput/VNumberInput.tsx
- `control-variant="hidden"` allows us replace controls with icon (e.g. for readonly state)
- `append-inner-icon` and `prepend-inner-icon` have been already restored, but need a minor CSS fix for spacing
resolves #19897
fixes #20782
```vue
<template>
<v-app>
<v-container>
<v-card class="mx-auto pa-6 my-4" style="max-width: 600px">
<h5>v-number-input</h5>
<div class="d-flex ga-3 align-center">
<v-switch
hide-details
v-model="fieldConfig.reverse"
label="reverse"
/>
<v-spacer />
<v-radio-group hide-details v-model="fieldConfig.controlVariant">
<div class="d-flex ga-3 align-center">
<v-radio value="default" label="default" />
<v-radio value="stacked" label="stacked" />
<v-radio value="split" label="split" />
</div>
</div>
<div class="d-flex flex-column ga-2"> …
```
=> feat(VNumberInput): ability to hide controls + spacing tweaks

packages/vuetify/src/locale/ja.ts
I just updated the translation file
```vue
```
=> fix(locale): add missing japanese translations

packages/vuetify/src/labs/VNumberInput/VNumberInput.tsx
fixes https://github.com/vuetifyjs/vuetify/issues/21005
```vue
<template>
<v-app>
<v-container>
<v-number-input v-model="number" :precision="3" />
<v-number-input v-model="number" :precision="3" disabled />
<v-number-input v-model="number" :precision="3" readonly />
</v-container>
</v-app>
</template>
<script setup>
const number = ref(1.23)
</script>
```
=> fix(VNumberInput): apply precision even when disabled/readonly

packages/vuetify/src/components/VDataTable/VDataTableVirtual.tsx
Exposes virtual scroller scrollToIndex and calculateVisibleItems function
```vue
<template>
<v-app>
<v-container>
<v-btn @click="scrollTo(0)">
Scroll to 0
</v-btn>
<v-btn @click="scrollTo(100)">
Scroll to 100
</v-btn>
<v-btn @click="scrollTo(200)">
Scroll to 200
</v-btn>
<v-btn @click="scrollTo(300)">
Scroll to 300
</v-btn>
<v-data-table-virtual
ref="table"
:items="virtualBoats"
fixed-header
height="400"
/>
</v-container>
</v-app>
</template>
<script setup>
{ title: 'Boat Type', align: 'start', key: 'name' },
{ title: 'Speed (knots)', align: 'end', key: 'speed' },
{ title: 'Length (m)', align: 'end', key: 'length' },
{ title: 'Price ($)', align: 'end', key: 'price' },
{ title: 'Year', align: 'end', …
```
=> feat(VDataTableVirtual): expose scrollToIndex

packages/docs/src/examples/v-menu/misc-transition.vue, packages/docs/src/examples/v-menu/misc-use-in-components.vue, packages/docs/src/examples/v-menu/prop-absolute.vue, packages/docs/src/examples/v-menu/prop-close-on-content-click.vue, packages/docs/src/examples/v-menu/prop-disabled.vue, packages/docs/src/examples/v-menu/prop-location.vue, packages/docs/src/examples/v-menu/prop-open-on-hover.vue, packages/docs/src/examples/v-menu/slot-activator-and-tooltip.vue
Follow the sample in usage section, added value in v-for to display mouse pointer instead of cursor
Some of  the `v-menu` examples shows cursor when activated:
Copy the behavior from the **Usage** section:
=> docs(VMenu): update examples to show pointer

packages/vuetify/src/components/VSlider/slider.ts
fixes #19021
```vue
<template>
<v-app>
<v-container>
<v-slider />
<v-range-slider />
</v-container>
</v-app>
</template>
```
=> fix(VSlider): allow mousedown with left button only

packages/vuetify/src/components/VOtpInput/VOtpInput.tsx
This PR enhances the `v-otp-input` component to properly support autofill functionality, particularly on mobile devices. The current implementation, with `maxlength="1"` on each input field, prevents browsers from recognizing and autofilling the entire OTP string.
This change modifies the component to set `maxlength` to the total number of OTP digits on the *first* input field only. This allows the browser to autofill the entire OTP string into the first input, while the component's existing logic correctly distributes the digits to the individual input fields. This approach was inspired by the solution described in https://stackoverflow.com/a/76906193/14799432.
**Previous attempts to address this issue by removing the `maxlength` attribute entirely (as suggested in …
=> fix(VOTPInput): enable autofill support

packages/vuetify/src/composables/theme.ts
This PR writes the Vuetify style tag using `textContent` instead `children`, `children` is deprecated in the current version used here (`1.9.4` ).
Latest Nuxt version 3.16.0 using `unhead v2 rc` and the vuetify style tag without content, just the children attribute with all the css.
Check https://github.com/vuetifyjs/nuxt-module/issues/298
fixes #21112
Use the default playground and check the style is there.
_using textContent instead children_
_vuetify style in the dom_
=> fix(theme): support unhead v2

packages/api-generator/src/locale/en/VAlert.json
resolves #21100
Currently it is not clear that the **borderProp** of the [VAlert](https://vuetifyjs.com/en/api/v-alert/#props-border-color) does nothing if not combined with the **border** prop.
=> docs(api): clarify borderColor usage of VAlert

packages/docs/src/pages/en/components/data-tables/basics.md
related to vuetifyjs#20672
Documentation updated to remove misleading description regarding `v-checkbox-btn` respecting the `v-data-table` header alignment.
=> docs(v-checkbox-btn): remove misleading description

packages/docs/src/pages/en/components/slide-groups.md
That's about it. The `active-class` prop is not being used on `slide-groups`. Rather, we are using `selected-class` according to the [API](https://vuetifyjs.com/en/api/v-slide-group/).
=> docs(VSlideGroup): Update active class prop

packages/vuetify/src/components/VDataTable/VDataTableRow.tsx
When using the special **item.data-table-select** and **item.data-table-expand** slots, would always return at:
and never actually get to the code that called **slots['item.data-table-expand']** or select.
Since I was fixing that, I brought the slots in line with how we handle defaults in other components, so that you can actually modify these with relative ease now.
```vue
<template>
<v-data-table :items="items" show-expand show-select>
<template #item.data-table-select="{ props: selectProps }">
<v-checkbox-btn v-bind="selectProps" />
</template>
<template #item.data-table-expand="{ props: expandProps }">
<v-btn v-bind="expandProps" />
</template>
<template #expanded-row="{ columns, item }">
<tr>
<td :colspan="columns.length">
I'm expanded for item {{ …
```
=> fix(VDataTableRow): provide correct defaults for special slots

packages/vuetify/src/components/VField/VField.tsx
A small QOL change for working with VField.
```vue
<template>
<v-app>
<v-container>
<v-input>
<v-field
append-icon="$vuetify"
label="Foobar"
prepend-icon="$vuetify"
/>
<v-menu activator="parent" eager>
<v-list v-model:selected="selected">
<v-list-item title="Foobar" value="one" />
<v-list-item title="Foobar" value="two" />
</v-list>
</v-menu>
</v-input>
</v-container>
</v-app>
</template>
<script setup>
const file = ref()
const isFocused = ref(false)
const selected = ref([])
</script>
```
=> refactor(VField): default slot fallback

packages/docs/src/pages/en/features/sass-variables.md
Current examples are not working. `$utilities` and `$color-pack` have to be put in `@use 'vuetify' { ... }` instead of the block for components settings.
Can be verified on [Stackblitz](https://stackblitz.com/edit/vuetify-sass-variables)
I did not ever used `$layers` and I am not sure if they also need this fix. Kael added these to documentation later and I hope he did not just copy/paste the section.
=> docs(sass-variables): correct use of `$utilities` and `$color-pack`

packages/docs/src/examples/v-input/usage.vue
This script section appears to be unnecessary in this example, as the declared variables and functions are not being utilized, so I removed the script section.
=> docs(VInput): remove unused script section

packages/docs/src/pages/en/features/icon-fonts.md
Added missing properties 'sortAsc', 'sortDesc' & 'calendar' to custom icon set aliases docs example [[here](https://vuetifyjs.com/en/features/icon-fonts/#creating-a-custom-icon-set)]
fixes type error:
=> docs: added missing IconAliases properties

packages/vuetify/src/labs/VDateInput/VDateInput.tsx
1. We were using `makeDisplayProps` but were doing nothing with it. Passed the display props inside `useDisplay`.
2. Since we already have a watcher for `menu`, the `onUpdateMenuModel` function was redundant because both of them are doing the same thing
=> refactor(VDateInput): use display props and remove extra code

packages/vuetify/src/components/VColorPicker/VColorPickerPreview.tsx
fixes #21179
```vue
<template>
<v-app>
<v-container>
<v-color-picker disabled />
<v-color-picker />
</v-container>
</v-app>
</template>
```
=> fix(VColorPicker): disabled EyeDropper when component is disabled

packages/vuetify/src/components/VEmptyState/VEmptyState.tsx
fixes #21170 
```vue
<template>
<v-app>
<v-container>
<v-empty-state
action-text="Contact Support"
headline="Whoops, 404"
href="https://vuetifyjs.com"
image="https://vuetifyjs.b-cdn.net/docs/images/logos/v.png"
text="The page you were looking for does not exist"
title="Page not found"
/>
</v-container>
</v-app>
</template>
```
=> fix(VEmptyState): pass href/to props to VBtn

packages/vuetify/src/composables/virtual.ts
`scrollToIndex` does not scroll to fractional values. Fractional values would allow scrolling to a point _between_ two elements.
For example, `scrollToIndex(1.5)` should scroll halfway between indices 1 and 2.
`scrollToIndex` also does not support scroll options, which makes it difficult to programmatically use `smooth` vs `instant` scrolling.
This change should be backwards compatible with existing consumers of this API:
* fractional values did not work at all prior to this change, and would fail.
* the second options argument did not exist.
Playground
```vue
<template>
<v-app>
<v-container>
<v-btn @click="scroll">scroll</v-btn>
<v-virtual-scroll ref="scroller" :height="300"
:items="['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', …
```
=> feat(VVirtualScroll): support fractional scroll index

packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.tsx
fixes: #19874
fixes #19874 
```typescript
// file: components/VNavigationDrawer/VNavigationDrawer.tsx
// line: 180
const { layoutItemStyles, layoutItemScrimStyles } = useLayoutItem({
id: props.name,
order: computed(() => parseInt(props.order, 10)),
position: location,
layoutSize,
elementSize: width,
active: computed(() => isActive.value || isDragging.value), // <-- This line
disableTransitions: computed(() => isDragging.value),
absolute: computed(() =>
// eslint-disable-next-line @typescript-eslint/no-use-before-define
props.absolute || (isSticky.value && typeof isStuck.value !== 'string')
),
})
```
The value of `active` on line 186 of `VNavigationDrawer.tsx` changes depending on `isDragging`.
```typescript
// file: composables/layout.ts
// line: 291
const styles = {
[position.value]: 0, …
```
=> fix(VNavigationDrawer): swipe glitch

packages/vuetify/src/components/VTextField/VTextField.sass
fixes #21191
```vue
<template>
<v-app>
<v-container>
<v-row>
<v-col>
<h4>Number fields</h4>
<v-number-input v-bind="withSuffix" control-variant="stacked" />
<v-number-input v-bind="withSuffix" control-variant="stacked" :reverse="true" />
<v-number-input v-bind="withSuffix" />
<v-number-input v-bind="withSuffix" :reverse="true" />
<v-divider class="mb-6" />
<h4>Text fields</h4>
<v-text-field v-bind="withSuffix" />
<v-text-field v-bind="withSuffix" :reverse="true" />
</v-col>
<v-col>
<h4>Number fields</h4>
<v-number-input v-bind="withIcons" control-variant="stacked" />
<v-number-input v-bind="withIcons" control-variant="stacked" :reverse="true" />
<v-number-input v-bind="withIcons" />
<v-number-input v-bind="withIcons" :reverse="true" />
<v-divider class="mb-6" />
<h4>Text fields</h4> …
```
=> fix(VTextField): padding adjustment for `reverse` mode

packages/vuetify/src/components/VDataTable/composables/select.ts
fixes #21190 
```vue
<template>
<v-data-table
:items="items"
show-select
:sort-by="[{ key: 'location', order: 'asc' }]"
</template>
<script setup>
const selected = ref([])
{
name: '🍎 Apple',
location: 'Washington',
height: '0.1',
base: '0.07',
volume: '0.0001',
},
{
name: '🍌 Banana',
location: 'Ecuador',
height: '0.2',
base: '0.05',
volume: '0.0002',
},
{
name: '🍇 Grapes',
location: 'Italy',
height: '0.02',
base: '0.02',
volume: '0.00001',
},
{
name: '🍉 Watermelon',
location: 'China',
height: '0.4',
base: '0.3',
volume: '0.03',
},
{
name: '🍍 Pineapple',
location: 'Thailand',
height: '0.3',
base: '0.2',
volume: '0.005',
},
{
name: '🍒 Cherries',
location: 'Turkey',
height: '0.02',
base: '0.02', …
```
=> fix(select): use current page items for shift click selection

packages/docs/src/pages/en/features/dates.md
Corrected the Day.js import and usage details to match the actual code requirements.
This change corrects the Day.js import and usage details in the Dates documentation. The previous instructions contained errors in the import statement and usage examples, which could confuse developers integrating Day.js with Vuetify. This update ensures that the documentation now accurately reflects the proper usage, improving the developer experience.
=> docs: fix Day.js usage example in the Dates documentation

packages/vuetify/src/components/VDataTable/VDataTable.sass
- Button content on `VDataTable` on mobile display / mode data table expand button content overflows
Fixes: https://github.com/vuetifyjs/vuetify/issues/20545
=> fix(VDataTable): data table expand button content overflows

packages/vuetify/package.json, packages/vuetify/src/composables/calendar.ts, packages/vuetify/src/composables/date/DateAdapter.ts, packages/vuetify/src/composables/date/__tests__/date.spec.ts, packages/vuetify/src/composables/date/adapters/vuetify.ts, packages/vuetify/src/composables/date/date.ts, pnpm-lock.yaml
fixes #20724
fixes #20490
- ~~ISO-ish 4-day requirement for the first week~~ defaults to match `en-US`
```vue
<template>
<v-app style="background-color: rgba(var(--v-theme-on-surface), 0.2)">
<v-container>
<div class="d-flex justify-center align-center ga-3">
<span class="opacity-70">locale:</span>
<v-chip-group v-model="currentLocale">
<v-chip filter label text="en" value="en"></v-chip>
<v-chip filter label text="pl" value="pl"></v-chip>
<v-chip filter label text="fr" value="fr"></v-chip>
<v-chip filter label text="pt" value="pt"></v-chip>
</div>
<div class="d-flex justify-center align-center ga-3">
<span class="opacity-70">startOfWeek:</span>
<v-chip-group v-model="startOfWeek">
<v-chip
v-for="o in startOfWeekOptions"
v-bind="o"
:key="o.value"
filter
label
></v-chip> …
```
=> fix(VDatePicker): use start of week to calculate week numbers

packages/vuetify/src/composables/validation.ts
Skip validation if disabled.
~~TODO: Should this occur on readonly as well?~~ Yes
<details>
```vue
<template>
<v-form v-model="valid">
<v-text-field :rules="[val => !!val || 'Required']" label="Regular" />
<v-text-field :rules="[val => !!val || 'Required']" label="Disabled" disabled />
</v-form>
<pre>{{ JSON.stringify(valid, null, 2) }}</pre>
</v-container>
</template>
<script setup>
const valid = ref(false)
</script>
```
</details>
=> fix(validation): a disabled field should always be valid

packages/api-generator/src/locale/en/useTheme.json, packages/docs/src/data/new-in.json, packages/docs/src/data/page-to-api.json, packages/docs/src/pages/en/features/theme.md, packages/vuetify/src/composables/__tests__/theme.spec.ts, packages/vuetify/src/composables/theme.ts
- Make it easier to change the theme
- Reduce cognitive load when working with themes
- More to come in future P.R.s
<details>
```vue
<template>
<v-app>
<v-main>
<v-container>
<v-btn @click="theme.toggle()">
Toggle Light / Dark
</v-btn>
<v-btn @click="theme.change('dark')">
Change to Dark
</v-btn>
<v-btn @click="theme.cycle()">
Cycle All Themes
</v-btn>
<v-btn @click="theme.cycle(['custom', 'light', 'utopia'])">
Cycle Specific Themes
</v-btn>
</v-container>
</v-main>
</v-app>
</template>
<script setup>
const theme = useTheme()
</script>
```
</details>
=> feat(theme): add toggle function

packages/vuetify/src/components/VOverlay/_variables.scss
It only really affects dark mode. No need for dedicated CSS variable - we might introduce one, when we drop Sass. For now I would leave it to be customized using typical method. Fans of MD3 might be disappointed, but it is pragmatic.
I don't feel like targeting `dev` is necessary. Whoever is going to merge it (assuming it gets approved), can decide on keeping or changing it to `master`.
closes #20244
```diff
- $overlay-scrim-background: rgb(var(--v-theme-on-surface)) !default;
+ $overlay-scrim-background: #000 !default;
```
=> feat(VOverlay): align scrim color with MD3

packages/api-generator/src/locale/en/VDatePicker.json, packages/api-generator/src/locale/en/VDatePickerMonth.json, packages/api-generator/src/locale/en/generic.json, packages/vuetify/src/composables/calendar.ts
Marks `first-day-of-week` as deprecated because it does not work when using date adapters. We want developers to use `<v-locale-provider>` instead and get both first day of the week as well as correct week number calculations.
closes #21204
=> feat: deprecate `firstDayOfWeek` prop

packages/vuetify/src/composables/calendar.ts
Follow-up to recently merged #21199 that introduced regression - locale changes should affect firstDayOfWeek, but since `0` is now recognized as valid prop value, all locales are locked at Sunday (possible to [reproduce](https://play.vuetifyjs.com/#eNq9VkuP2zYQ/isDXewFTGkf2bYw1ov0klOLHLJoDlUPtDSymaVIgqRkG2v/9w4pPySv27g59GKLw2/eL/75ljhbZG2DXlSb9JtLpomojbYe3qCwyD3+0d3BDiqraxjtsaNcHYGoJmDkhAD078+RmdQFl0gMucJ1ZCm0ch729zAbahq/5QrAL7HGKcRvgBIr3kj/0hFHUiyWfjTp7rIs/O/iqVN1ZDscR6gO6Bqd4wt0hHlnd4SE391NrpJJDM2vxqRkKMXlyWNtJNn5HGBPLePGgPMbibM8mfPidWF1o0pWaKntFOxizsctt2PGWha9YVox19iKF3gzgdv0/iZPoqwojWLiuVBooeZrthKlX5Lcnx5vjyCClaKFQnLn6KpklcQ1fGtciBorUHli5hQbdTgsOHvosZMAZ7g6StCGF8Jv2M9Bxz5WT1mA9FnItKUwLHhnoGW1LlESc9FYS1p+i2wDJUceqIQMZkg+Rwke1574UOUJtFw2IWzh8PyUdfCrRRjZExEO/11EZXsiwuEHrPB9K+hwScSB1IXvlMi …
=> fix(VDatePicker): resolve firstDayOfWeek from locale

packages/docs/src/pages/en/styles/overflow.md
Sorry, I didn't follow the proper contribution process. My edit concerns what I believe is an oversight in the docs:
The table of overflow utility classes does not include the utilities for overflow: visible. They do however exist and are mentioned in the examples.
=> docs: update overflow.md

packages/docs/src/pages/en/getting-started/upgrade-guide.md, packages/vuetify/src/styles/settings/_variables.scss
Be less opinionated.
<details>
```vue
```
</details>
=> feat(VBtn): remove default text transform

packages/vuetify/src/components/VOverlay/locationStrategies.ts, packages/vuetify/src/components/transitions/dialog-transition.tsx, packages/vuetify/src/util/box.ts
fixes #20515
```vue
<template>
<v-app>
<v-container>
<div style="height: 200px" />
<div class="CONTAINER">
<v-menu v-model="menu">
<v-btn class="BUTTON" color="primary" v-bind="props">
Activator slot
</v-btn>
</template>
<v-list>
<v-list-item
:key="index"
:value="index"
>
</v-list-item>
</v-list>
</v-menu>
</div>
<div style="height: 2000px" />
</v-container>
</v-app>
</template>
<script setup>
{ title: 'Click Me' },
{ title: 'Click Me' },
{ title: 'Click Me' },
{ title: 'Click Me 2' },
])
const menu = ref(false)
</script>
<style>
.CONTAINER {
display: flex;
justify-content: center;
padding: 16px;
background-color: lightblue; …
```
=> fix(VMenu): use last known position if target is hidden

packages/docs/auto-imports.d.ts, packages/docs/src/components/about/TeamMember.vue, packages/docs/src/components/about/TeamMembers.vue, packages/docs/src/data/team.json, packages/docs/src/pages/en/blog/state-of-the-union-2024.md, packages/docs/src/stores/team-members.ts
There is a `useTeamStore` from vuetify/one conflicting with the local one in docs. Thus, team members are not showing and state of the union 2024 is empty.
N/A
=> docs: team members not showing

packages/docs/src/components/PageFeatures.vue
Resolves #21296
Hiding button on API page to avoid redirecting to non existing github pages on autogenerated data.
=> docs: remove edit this page button on API pages

packages/docs/src/examples/v-dialog/misc-data-table.vue, packages/docs/src/pages/en/components/dialogs.md
An example of `VDialog` being called by rows in`VDataTable`. This highlights how the **activator** prop can be used to call the same instance dialog.
[Playround Sample](https://play.vuetifyjs.com/#eNqNV0tz2zYQ/itb9SF5RqT80qTRWKo9zaE9tJNp0lPsA0SCEhq+BgRpezT6710sQBCkqMS6kFx8u/j2Bay+HCaVjBYPZRk2NZ+sJneKZ2XKFN885gB3TcDKkl7pIypyxUTOpRWRMGaKBYptUw4rgerV+nFCz8cJrPacxVxqkX17nDhd1G53gx+1RljKYid5peEH0BI49vC0XwsKUmTCpL8KsIqKtJCoT89Zz+rF46QP3nOx2ysEXy+HS6usiHkaNCytufXH2elje/R6LsU8YXWq7R+ADJ14QwqVkkW+2xwc6Pjz3cIKB7YXvex04pOg+DH2lc6HnkVKFPk3A79Vnr7+CayHvqRhUrBcu6z4ixoG9T4r6orzXHGdIcl3osLX2U+8QdlJdu6jVERfEchjoSiTA8gwOk2gCW2yWAQlzyOR6sCQaBgt9GTEOfLnxIWOh+RZ0XBTUyJGMt8ggMXDFX8jgZG8alDXWG0HotBvQdeXsWBpsYMmoKpFqkagG1DntWGKesK940LGXoJnEas9ypeXl54zps8TIbNAR76j2Zmnp58MyRPqOVLzF+4r1ugG0g9fXnwNdHhHVu4jlkeeE7CGhKW …
=> docs(VDialog): example for activator prop one dialog instance

packages/vuetify/src/components/VOverlay/locationStrategies.ts, packages/vuetify/src/util/helpers.ts
fixes #21098
replaces #21229
```vue
<template>
<v-app>
<div>
<v-select
v-model="location"
:items="[
'bottom','top' ,'center' ,'end' ,'left' ,'right' ,'start' ,'bottom top' ,'bottom center' ,'bottom end',
'bottom left' ,'bottom right' ,'bottom start' ,'top center' ,'top end' ,'top left' ,'top right',
'top start' ,'center end' ,'center left' ,'center right' ,'center start' ,'end left' ,'end right',
'end start' ,'left right' ,'left start' ,'right start'
]"
label="Location"
/>
</div>
<div class="container">
lorem<br>
ipsum<br>
lorem<br>
ipsum<br>
{{ location }}<br>
This select menu should flicker on chrome browser:<br>
<div id="select-wrapper">
<v-select
:items="[
'bottom','top' ,'center' ,'end' ,'left' ,'right' ,'start' ,'bottom top' ,'bottom center' ,'bottom end',
'bottom left' ,'bottom …
```
=> fix(VOverlay): prevent flip logic resizeObserver loop

packages/docs/package.json, packages/docs/src/components/app/Btn.vue, packages/docs/vite.config.mts, pnpm-lock.yaml
In mobile screens, the login button is cut off. This change will update the login button to an icon button.
Before:
After:
https://github.com/vuetifyjs/one/pull/23 needs to be merged & released first. Then this PR will be updated to the latest `@vuetify/one` release version
=> docs: app bar fully visible in mobile

packages/docs/src/components/api/Section.vue, packages/docs/src/components/api/View.vue, packages/docs/src/composables/frontmatter.ts
Adds support for generating and displaying a table of contents for dynamically generated API pages. The TOC is generated based on the available sections (props, events, slots, etc.) and is automatically updated when navigating between API pages.
This change was necessary because the API pages are dynamically generated from `[name].md` and previously didn't have a TOC, making navigation through the documentation more difficult.
This is a documentation-only change that affects the API documentation pages. No markup changes are required as it works with the existing structure of the API pages.
=> docs(api): add dynamic toc support for api pages

packages/docs/src/pages/en/features/sass-variables.md
This PR adds a note to the documentation about how to set SCSS variables that have commas inside them.
Currently, neither this project nor the SASS project have documentation about commas in values in a `@use` block.
The following code doesn't work, because the comma is interpreted by the SCSS parser as the end of the value, and it expects another variable name after the comma:
```scss
@use 'vuetify/settings' with (
$body-font-family: 'Roboto Variable', sans-serif
);
```
Surrounding the whole value in quotes doesn't work either.
With a lot of trial and error, I figured out that this syntax works:
```scss
@use 'vuetify/settings' with (
$body-font-family: ('Roboto Variable', sans-serif)
);
```
I figured this should be documented to save other people the headache.
=> docs(sass-variables): mention how to use variable values containing commas

packages/api-generator/package.json, packages/api-generator/src/index.ts, packages/api-generator/src/locale/en/VDataTableVirtual.json, packages/api-generator/src/locale/en/VField.json, packages/api-generator/src/locale/en/VIconBtn.json, packages/api-generator/src/utils.ts, packages/api-generator/templates/component.d.ts
1. `CleanHTMLInputElement` will filter out native `HTMLInputElement` inferred props. Currently, these components are the ones that uses `VTextField` (and consequently an `input`, where the native props are coming from)
2. A non-blocking warning after build that shows the components with missing API descriptions.
N/A
=> docs: type inference issue on exposed API documentation

packages/vuetify/src/components/VDataTable/composables/select.ts
fixes #21328 
```vue
<template>
<v-data-table
show-select
:model-value="selection"
:sort-by="[{ key: 'fat', order: 'asc' }]"
:item-selectable="(item) => !['Ice cream sandwich', 'Eclair'].includes(item.name)"
/>
</template>
<script setup>
const desserts = [
{
calories: 159,
fat: 6,
carbs: 24,
protein: 4,
iron: 1,
},
{
calories: 237,
fat: 9,
carbs: 37,
protein: 4.3,
iron: 1,
},
{
calories: 262,
fat: 16,
carbs: 23,
protein: 6,
iron: 7,
},
{
calories: 305,
fat: 3.7,
carbs: 67,
protein: 4.3,
iron: 8,
},
{
name: 'Gingerbread',
calories: 356,
fat: 16,
carbs: 49,
protein: 3.9,
iron: 16,
},
{
calories: 375,
fat: 0,
carbs: 94,
protein: 0,
iron: 0,
},
{
name: …
```
=> fix(VDataTable): only toggle select with selectable row by shift click

packages/docs/src/examples/v-file-input/prop-validation.vue, packages/docs/src/pages/en/components/file-inputs.md
- Resolves #21099 
- Showcase that validation rule function's `value` arg will be an array if `multiple` prop is passed (multiple file uploads)
N/A
=> docs(VFileInput): updated validation example for multiple file upload

packages/vuetify/src/components/VDialog/VDialog.tsx
fixes https://github.com/vuetifyjs/vuetify/issues/21301
```vue
<template>
<div class="pa-8 text-center">
<p>{{seconds}}</p>
<p><span v-if="sheet">Focus lost in textarea</span></p>
<v-textarea ref="textArea"> </v-textarea>
<v-bottom-sheet
v-model="sheet"
inset
hide-overlay
persistent
no-click-animation
:retain-focus="false"
scroll-strategy="none"
:scrim="false"
tabindex="-1"
>
<v-card class="text-center" height="200">
<v-card-text>
<v-btn text="Close" variant="text" @click="sheet = !sheet"></v-btn>
<br />
<br />
<div>This is a bottom sheet that shouldn't gain focus</div>
</v-card-text>
</v-card>
</v-bottom-sheet>
</div>
</template>
<script setup>
import { shallowRef, onMounted } from 'vue'
const sheet = shallowRef(false)
const seconds = shallowRef(5)
const textArea = shallowRef() …
```
=> fix(VDialog): only take focus on open if scrim or retainFocus

packages/vuetify/src/labs/VTimePicker/VTimePickerClock.tsx
Rounded left and top values for VTimePickerClock to fix ssr hydration mismatch error
```vue
<v-time-picker />
```
=> fix(VTimePicker): fix ssr hydration mismatch error

packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx
- copied from VCombobox
- forces the `isDirty` to be evaluated. Otherwise, the computed in [validation.ts:96](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/composables/validation.ts#L96) does not trigger
fixes #20718
```vue
<template>
<v-card>
<v-text-field label="v-text-field" v-model="model" />
<v-select label="v-select" :items="shortList" v-model="model" />
<v-combobox
label="v-combobox"
:items="shortList"
v-model:search="search1"
/>
label="v-autocomplete"
:items="shortList"
v-model:search="search2"
/>
</v-container>
<pre class="px-5 pb-5">{{ JSON.stringify({ search1, search2 }) }}</pre>
</v-card>
<pre class="mt-5">
1. Select value in …
```
=> fix(VAutocomplete): re-evaluate dirty on external change

packages/docs/src/examples/transitions/create-css-transition-component.vue, packages/docs/src/examples/transitions/create-css-transition-prop.vue, packages/docs/src/pages/en/styles/transitions.md, packages/vuetify/src/components/transitions/index.ts
Exposed `createCssTransition` function and added proper documentation on it's usage and example.
fixes #16050
```vue
<template>
<v-container>
<v-col class="text-center">
<v-btn
@click="show = !show"
>
My Transition
</v-btn>
<MyTransition>
<v-card
v-show="show"
width="100"
height="100"
color="secondary"
class="mx-auto mt-5"
></v-card>
</MyTransition>
</v-col>
</v-row>
</v-container>
</template>
<script setup>
import { createCssTransition } from 'vuetify/components/transitions';
const MyTransition = createCssTransition('my-transition')
const show = ref(false)
</script>
<style lang="scss">
.my-transition {
&-enter-active,
&-leave-active {
transition: 0.3s cubic-bezier(0.68, -0.55, 0.265, 1.55);
}
&-enter-from,
&-leave-to { …
```
=> feat(transition): expose create transition classes

packages/docs/src/pages/en/getting-started/installation.md
Update Getting Started with Laravel documentation. `vite.config.ts` is preferred over `webpack.mix.js` starting at Laravel 9
N/A
=> docs: update laravel getting started

packages/vuetify/src/labs/VDateInput/VDateInput.tsx, packages/vuetify/src/labs/VDateInput/__tests__/VDateInput.spec.browser.tsx
`[Enter]` should not clear the input.
related to #21221
```vue
<template>
<v-app>
<v-container>
<pre>value: {{ value }} | {{ typeof value }}</pre>
<v-date-input v-model="value" />
</v-container>
</v-app>
</template>
<script setup>
const value = ref()
</script>
```
=> fix(VDateInput): accept value when picker is hidden

packages/api-generator/src/locale/en/VIconBtn.json, packages/api-generator/src/locale/en/generic.json, packages/vuetify/src/components/VAlert/VAlert.sass, packages/vuetify/src/components/VAlert/VAlert.tsx, packages/vuetify/src/composables/iconSizes.ts, packages/vuetify/src/labs/VIconBtn/VIconBtn.tsx
resolves #20636
<details>
<summary>Playground</summary>
```vue
<template>
<v-app>
<v-container :max-width="650" class="space-y-6">
<div class="d-flex ga-6">
<v-switch hide-details color="primary" v-model="dense" label="compact" />
<v-switch hide-details color="primary" v-model="prominent" label="prominent" />
<v-switch hide-details color="primary" v-model="closable" label="closable" />
</div>
<v-alert v-bind='alertConfigWithTitle' />
<v-alert v-bind='alertConfigWithTitleAndText' />
<v-alert v-bind='alertConfigWithShortText' />
<v-alert v-bind='alertConfigWithLongText' />
<div class="mt-6 d-flex ga-3 align-center">
<v-number-input hide-details density="compact" variant="outlined" v-model="iconSize" label="icon size" max-width="200" suffix="px" @update:model-value="onIconSizeNumberChange" …
```
=> feat(VAlert): better aligment with prepend icon

packages/vuetify/src/components/VBtn/VBtn.sass, packages/vuetify/src/components/VBtn/_variables.scss
fixes #20120
```vue
<template>
<v-app>
<v-container>
<v-row>
<v-col>
<v-number-input v-model="page" label="page" />
</v-col>
<v-col>
<v-select v-model="density" :items="densityOptions" label="density" return-object />
</v-col>
<v-col>
<v-select v-model="rounded" :items="roundedOptions" label="rounded" return-object />
</v-col>
</v-row>
<v-pagination
v-model="page"
:density="density.value"
:length="244444"
:rounded="rounded.value"
:total-visible="page > 10000 ? 4 : page > 1000 ? 5 : page > 100 ? 6 : 7"
class="my-12"
/>
</v-container>
</v-app>
</template>
const page = ref(1)
interface DensityOption { title: string, value: 'compact' | 'comfortable' | undefined }
const densityOptions = [...['compact', 'comfortable'].map(x => ({ title: x, …
```
=> fix(VPagination): adapt button width for large values

packages/api-generator/src/locale/en/VDateInput.json, packages/vuetify/src/composables/dateFormat.ts, packages/vuetify/src/labs/VDateInput/VDateInput.tsx, packages/vuetify/src/labs/VDateInput/__tests__/VDateInput.spec.browser.tsx
> reopened #21401
- drops 'function' mode
- detects the separator and sign order
- infers format from locale
- supplements placeholder
- included #21375 to avoid breaking `multiple`
fixes #21397
```vue
<template>
<v-defaults-provider :defaults="{ VDateInput: { persistentPlaceholder: true, persistentHint: true } }">
<v-container max-width="400" class="d-flex flex-column ga-6 py-6">
<v-locale-provider locale="de-DE">
<v-date-input label="matching locale" input-format="dd.mm.yyyy" hint="locale: de-DE (dd.mm.yyyy)" />
</v-locale-provider>
<v-locale-provider locale="en-GB">
<v-date-input label="from locale" hint="locale: en-GB (dd/mm/yyyy)" />
</v-locale-provider>
<v-locale-provider locale="hr-HR">
<v-date-input label="from locale" hint="locale: hr-HR (dd. mm. yyyy.)" /> …
```
=> feat(VDateInput): sync with placeholder, infer from locale

packages/vuetify/src/components/VBottomSheet/VBottomSheet.sass
- Fixes: https://github.com/vuetifyjs/vuetify/issues/21316
- Change `margin-inline` from `0` to `auto` no impact on default behavior
```vue
<template>
<div class="text-center pa-8">
<v-btn
class="ma-auto"
size="x-large"
text="Click Me"
@click="sheet = !sheet"
></v-btn>
<v-bottom-sheet v-model="sheet" max-width="300">
<v-card height="500">
<v-card-text> Content </v-card-text>
</v-card>
</v-bottom-sheet>
</div>
</template>
<script setup>
import { shallowRef } from 'vue'
const sheet = shallowRef(false)
</script>
```
=> fix(VBottomNavigation): set inline margin to auto

packages/api-generator/src/locale/en/VDataTable.json, packages/api-generator/src/locale/en/VDataTableServer.json, packages/api-generator/src/locale/en/VDataTableVirtual.json
fixes #21377 
Updated event descriptions to correctly refer to their respective props directly instead of the outdated `options` property in `VDataTable`, `VDataTableVirtual`, `VDataTableServer` json file.
=> docs(VDataTable): description copy correction

packages/vuetify/src/components/VCombobox/VCombobox.tsx
- Fixes: https://github.com/vuetifyjs/vuetify/issues/20572
- Issue is the first item auto selected is hidden by default when you double click on the initial value "foo" and then type "fi" on the input.
- Actual result: `fi2` onwards shown and `fi1` is hidden.
- Expected result: `fi1` should still be displayed
```vue
<template>
<v-combobox
auto-scroll
:items="items"
label="Default"
auto-select-first
/>
</template>
<script>
data: () => ({
items: [
'bar',
'buzz',
'fi1',
'fi2',
'fi3',
'fi4',
'fi5',
'fi6',
'fizz',
'foo',
],
value: 'foo',
}),
}
</script>
```
=> feat(VCombobox): scroll to first item on search result (#20572)

packages/api-generator/src/locale/en/VCalendarMonthly.json, packages/api-generator/src/locale/en/VCalendarWeekly.json, packages/api-generator/src/locale/en/VDatePicker.json, packages/api-generator/src/locale/en/generic.json, packages/vuetify/src/components/VDatePicker/VDatePickerMonth.tsx, packages/vuetify/src/composables/calendar.ts, packages/vuetify/src/composables/date/DateAdapter.ts, packages/vuetify/src/composables/date/adapters/vuetify.ts
`weekdayFormat` existed in v2, but was not yet re-implemented.
Note: It is going to be ignored by custom date adapters until those packages get updated by community.
- `date-fns` is already printing with `EEEEEE` which equals to Intl's `short`
- day.js has `dd` hardcoded - i.e. `narrow`
- luxon uses `Intl` with `short` hardcoded
```vue
<template>
<v-container>
<v-select
label="Locale"
v-model="locale.current.value"
:items="['en', 'de', 'pl', 'fr', 'ar']"
/>
<v-date-picker
:key="locale.current.value"
class="mt-3"
weekday-format="short"
/>
</v-container>
</template>
<script setup>
import { useLocale } from 'vuetify'
const locale = useLocale()
</script>
```
=> feat(VDatePicker): restore `weekday-format`

packages/vuetify/src/components/VNumberInput/VNumberInput.sass
- VNumberInput does not play well with `append-inner-icon` and devs will usually use `#append-inner` to append icons
- I am trying to address the spacing & inconsitency
**Note**: (about the playground) it might appear that suffix is too close to the `hr`, but it has the same 6px distance as the prefix. Please ignore. I think the default spacing should be 2x larger, but it is out of scope for this PR.
```vue
<template>
<v-container max-width="400">
<v-alert type="info" density="compact">
toggle between <v-code>none</v-code> &amp; <v-code>slot</v-code>
</v-alert>
<h5 class="mt-4">prepend</h5>
<v-btn-toggle v-model="prepend" density="compact">
<v-btn value="none" text="none" />
<v-btn value="icon" text="icon" />
<v-btn value="slot" text="slot" />
<h5 …
```
=> fix(VNumberInput): inner spacing adjustments

packages/docs/src/examples/v-autocomplete/prop-items.vue, packages/docs/src/pages/en/components/autocompletes.md, packages/vuetify/src/components/VAutocomplete/VAutocomplete.tsx, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VList/VListChildren.tsx, packages/vuetify/src/components/VSelect/VSelect.tsx, packages/vuetify/src/composables/filter.tsx
While workarounds are possible with `#item` slot we lose matches highlights when filtering and introduces anomalies (e.g. try typing "t " in this [example](https://play.vuetifyjs.com/playgrounds/1dMGUw)). Developers also need to remember about `tabindex='-1'` when they use `#item` slot and place checkbox or any focusable element, otherwise keyboard navigation is broken. Once dropdown components accept `type` right from the `items` it will be much easier to achieve functionality they need without compromising on quality.
- add support for **subheader** and **divider** (incl. slots)
- exclude them when filtering
resolves #15721
resolves #5014
closes #19912
closes #5014
```vue
<template>
<v-app>
<v-container>
<v-select multiple label="v-select" v-model="selection" :items="items" chips /> …
```
=> feat(VSelects): support divider and subheader

packages/api-generator/src/locale/en/VNumberInput.json, packages/vuetify/src/components/VNumberInput/VNumberInput.tsx
resolves #21306
```vue
<template>
<v-app>
<v-container>
<v-card class="mx-auto pa-6 my-4" style="max-width: 1200px">
<v-row class="mt-3">
<div class="mb-3"><small>(:precision='1')</small></div>
<v-number-input label="Tax rate" v-model="exampleValue1" suffix="%" :precision="1" :min-fraction-digits='0' :step=".5" />
</v-col>
<div class="mb-3"><small>(:precision='5' :min-fraction-digits='2')</small></div>
<v-number-input v-model="exampleValue2" :precision="5" :min-fraction-digits='2' :step=".005" />
</v-col>
<div class="mb-3"><small>(:precision='2' :min-fraction-digits='1')</small></div>
<v-number-input v-model="exampleValue3" grouping :precision="example3_precision" :min-fraction-digits="example3_minFractionDigits" :step="1000" />
<label> …
```
=> feat(VNumberInput): more flexible precision display

packages/docs/src/components/app/search/SearchDialog.vue
Replace hyphens with spaces on search term passed to algolia (hyphens are not tokenized). This prevents empty search results in doc search dialog.
Reference: https://www.algolia.com/doc/guides/managing-results/optimize-search-results/typo-tolerance/how-to/how-to-search-in-hyphenated-attributes/
N/A
=> docs: replace hyphens in search term for algolia

packages/vuetify/src/components/VSelect/VSelect.tsx
- Typing the same letter multiple times (with no matches) will now try the next matching item instead of continuing to build the lookup prefix
- Switching to a different letter (with no matches) begins a new search
```vue
<template>
<v-app>
<v-container>
<v-select v-model="selectedItems" :items="items" />
</v-container>
</v-app>
</template>
<script setup>
const selectedItems = ref([])
'Aruba-1',
'Aruba-2',
'Aruba-3',
'Aruba-4',
'Bonaire-1',
'Bonaire-2',
'Bonaire-3',
'Bonaire-4',
'Curaçao-1',
'Curaçao-2',
'Curaçao-3',
'Curaçao-4',
])
</script>
```
Typing `b` repeatedly will cycle through all "Bonaire-" items instead of getting stuck on the first one.
Typing `b` then `c` within KEYBOARD_LOOKUP_THRESHOLD will select "Curaçao-1" instead of staying …
=> fix(VSelect): keyboard match multiple items with the same prefix

packages/vuetify/src/components/VDatePicker/VDatePicker.tsx
fixes https://github.com/vuetifyjs/vuetify/issues/20465
Disable month and year buttons based on `allowed-dates` prop when:
‼️  This is a follow up PR for https://github.com/vuetifyjs/vuetify/pull/21466 and completes the second checkbox from list above. The changes in this PR are slightly computation heavy so wanted to have some discussion and see if the code is worth it.
If the `allowed-dates` prop is function then:
- Code inside `allowedYears` will execute approx 366 * 150 = **54900 times**
- Code inside `allowedMonths` will execute approx 31 * 12 = **372 times**
```vue
<template>
<v-app>
<v-container>
<h2>Date picker</h2>
<v-date-picker
mode="month"
hide-header
:allowed-dates="allowedDates"
<h2>Date picker years</h2>
<VDatePickerYears
:allowed-years="[2025, 2026]" …
```
=> feat(VDatePicker): Calculate disabled year and month 

packages/docs/src/pages/en/components/textareas.md
fix typo background-color to bg-color
The info of using 'background-color' create confusion should be 'bg-color'.
=> docs: textareas.md - background color

packages/vuetify/src/components/VNumberInput/VNumberInput.tsx, packages/vuetify/src/components/VNumberInput/__tests__/VNumberInput.spec.browser.tsx, packages/vuetify/src/util/__tests__/helpers.spec.ts, packages/vuetify/src/util/helpers.ts
Currently user action is completely ignored if even one character causes `onBeforeinput` to bail. A nicer UX would be to extract the digits to support copy/pasting from spreadsheets or PDFs.
I would prefer to merge it to `master` as it can be considered a bug by many developers at this point.
```vue
<template>
<v-container>
<v-row>
<v-col cols="6" lg="3">
<h5>(default precision="0" max="200")</h5>
<v-number-input v-model="example1" clearable hide-details="auto" :max="200" />
<code class="d-block pt-3">value: {{ example1 ?? 'null' }}</code>
<input class="border-md pa-2 mt-2" type="number" v-model="example1" />
</v-col>
<v-col cols="6" lg="3">
<h5>(precision="1")</h5>
<v-number-input v-model="example2" :precision="1" hide-details="auto"></v-number-input>
<code class="d-block pt-3">value: {{ …
```
=> feat(VNumberInput): extract number from pasted text

packages/docs/src/App.vue
More context on meta title for API pages
Before: 
After:
N/A
=> docs: meta title on api pages

packages/api-generator/src/locale/en/VDataTableHeaders.json, packages/docs/src/data/new-in.json, packages/vuetify/src/components/VDataTable/VDataTableHeaders.tsx
Utilize props `lastFixed` and make column header fixed on the right.
- Fixes: #21153
=> feat(VDataTable): add new lastFixed property (#21153)

packages/vuetify/src/components/VOtpInput/VOtpInput.tsx
- Resolves: #21275
- Add new prop to keep focus on paste to `VOtpInput`, retains the default behavior of blur on paste
```vue
<template>
<v-app>
<v-container>
<v-otp-input v-model="token" keep-focus  />
</v-container>
</v-app>
</template>
<script setup>
const token = ref()
</script>
```
=> feat(VOtpInput): allow to keep focus on paste (#21275)

packages/api-generator/src/locale/en/VSlideGroup.json, packages/docs/src/data/new-in.json, packages/vuetify/src/components/VSlideGroup/VSlideGroup.tsx
- Add new props `contentClass` to `VSlideGroup` 
- Resolves https://github.com/vuetifyjs/vuetify/issues/20853
```vue
<template>
<v-sheet class="mx-auto" max-width="600">
<v-slide-group show-arrows content-class="bg-red">
<v-slide-group-item
v-for="n in 25"
:key="n"
v-slot="{ isSelected, toggle }"
>
<v-btn
:color="isSelected ? 'primary' : undefined"
class="ma-2"
rounded
@click="toggle"
>
Options {{ n }}
</v-btn>
</v-slide-group-item>
</v-slide-group>
</v-sheet>
</template>
<style>
.bg-red {
background-color: red;
}
</style>
```
<image src="https://github.com/user-attachments/assets/955a8b6e-8857-488b-9eb7-4333e23a6684" />
=> feat(VSlideGroup): add content class to VSlideGroup props

packages/api-generator/src/locale/en/VNumberInput.json, packages/vuetify/src/components/VNumberInput/VNumberInput.tsx, packages/vuetify/src/components/VNumberInput/__tests__/VNumberInput.spec.browser.tsx, packages/vuetify/src/util/__tests__/helpers.spec.ts, packages/vuetify/src/util/helpers.ts
- only decimal separator, no dependency on the locale, no grouping
- we would do this simple prop anyway
- needs to be coordinated with #21263, not sure which one will be merged first
resolves #20254
```vue
<template>
<v-container max-width="400">
v-model="num"
control-variant="stacked"
decimal-separator=","
:precision="2"
:step=".5"
/>
</v-container>
</v-app>
</template>
const num = ref(32.5)
</script>
```
=> feat(VNumberInput): custom decimal separator

packages/api-generator/src/locale/en/VDatePickerMonths.json, packages/api-generator/src/locale/en/VDatePickerYears.json, packages/vuetify/src/components/VDatePicker/VDatePicker.tsx, packages/vuetify/src/components/VDatePicker/VDatePickerMonths.tsx, packages/vuetify/src/components/VDatePicker/VDatePickerYears.tsx
fixes #20465
Disable month and year buttons based on `allowed-dates` prop when:
```vue
<template>
<v-app>
<v-container>
<h2>Date picker</h2>
<v-date-picker
mode="month"
hide-header
:allowed-dates="['2025-05-01', '2025-03-02', '2024-02-01']"
<h2>Date picker years</h2>
<VDatePickerYears
:allowed-years="[2025, 2026]"
class="mb-10"
/>
<h2>Date picker months</h2>
<VDatePickerMonths
:allowed-months="[2, 3]"
/>
</v-container>
</v-app>
</template>
```
=> feat(VDatePicker): disable months and years if not allowed

packages/api-generator/src/locale/en/VToolbar.json, packages/vuetify/src/components/VToolbar/VToolbar.tsx
fixes #7317 
<details>
```vue
<template>
<v-toolbar>
<template #extension>
Fizzbuzz
</template>
</v-toolbar>
<v-toolbar extended></v-toolbar>
<v-toolbar :extended="false">
<template #extension>
Fizzbuzz
</template>
</v-toolbar>
</v-container>
</template>
<script setup>
</script>
```
</details>
=> feat(VToolbar): allow for explicit false for extension

packages/vuetify/src/components/VAutocomplete/VAutocomplete.sass, packages/vuetify/src/components/VCombobox/VCombobox.sass, packages/vuetify/src/components/VSelect/VSelect.sass, packages/vuetify/src/components/VSelect/_mixins.scss
fixes #19677
Fix chips size overlapping with label when using compact density and chips for a v-select component.
This wasn't a problem on VAutocomplete and VCombobox due to a css which was missing on VSelect
```vue
<template>
<v-app>
<v-container>
<v-select
chips
label="Select"
multiple
:closable-chips="true"
></v-select>
chips
multiple
:closable-chips="true"
<v-combobox
chips
multiple
:closable-chips="true"
></v-combobox> …
```
=> fix(VSelect): reuse compact chip label style

packages/vuetify/src/components/VSlider/VSliderThumb.tsx, packages/vuetify/src/components/VSlider/slider.ts
fixes #21351
This PR fixes a bug where v-range-slider (and other slider components) 
couldn't reach the maximum value when the max wasn't perfectly divisible 
by the step size.
For example, with a step of 10 and max of 104, attempting to drag the 
slider to the maximum would stop at 100 instead of reaching 104. This was 
due to the rounding logic in the roundValue function.
The fix adds a special case to ensure the exact maximum value is always 
reachable, while maintaining proper step behavior for all other values.
```vue
<template>
<v-app>
<v-container class="fill-height">
<v-row justify="center" align="center">
<v-col cols="12" md="8">
<v-card class="pa-6" elevation="4">
<v-card-title class="text-h5 mb-4">
v-range-slider Bug Fix Test
<v-card-text>
<p …
```
=> fix(VSlider): correct step rounding for max value

packages/docs/src/pages/en/styles/text-and-typography.md
This pull request addresses a typographical error in the documentation where the CSS property 'font-size' was declared twice within a explanation. 
N/A
=> docs: correct duplicate 'font-size' declaration

packages/vuetify/src/components/VOtpInput/VOtpInput.tsx, packages/vuetify/src/components/VOtpInput/__tests__/VOtpInput.spec.browser.tsx
This PR implements improvements to the `v-otp-input` component, addressing paste trimming and enhancing the autofill focus behavior discussed in #21131.
Specifically, the changes in this PR include:
1.  **Improved Paste Handling:**
*   Leading/trailing whitespace is now removed using `trim()`.
2.  **Enhanced `finish` event:**
*   Within the watcher that detects when the model's length equals the target length (signaling a completed OTP, often after autofill), the component now explicitly sets the `focusIndex` to the last input field.
*   This change ensures that after a successful autofill, the focus is directed to the final input element, which provides a more intuitive user experience compared to the focus remaining on the second element.
```vue
<template>
<v-app>
<v-container> …
```
=> fix(VOtpInput): trim clipboard text and update focus on finish

packages/docs/src/examples/v-data-table/misc-select-all.vue, packages/docs/src/pages/en/components/data-tables/basics.md
resolved #21065 
An example showcasing how to have keyboard shortcuts `Ctrl+A` or `Cmd+A`  select all rows in `v-data-table`.
https://github.com/user-attachments/assets/acfd18ef-690b-4295-a46d-c214f2ebd4d4
=> docs(VDataTable): select all via short key example

packages/vuetify/src/components/VFileInput/VFileInput.tsx, packages/vuetify/src/composables/fileDrop.ts, packages/vuetify/src/labs/VFileUpload/VFileUpload.tsx
fixes #21494
```vue
<template>
<v-app>
<v-row>
<v-col class="elevation-5 pa-6" cols="3">
<div class="text-caption">Drag & Drop verification checklist:</div>
<v-list class="bg-transparent" density="compact" select-strategy="independent" selectable>
<v-list-item v-for="c in checklist" :key="c" :title="c" :value="c">
<template #prepend="{ isSelected, select }">
<v-checkbox-btn :model-value="isSelected" @update:model-value="select" />
</template>
</v-list-item>
</v-list>
</v-col>
<v-col>
<v-container>
<v-file-input v-model="files" multiple webkitdirectory />
<pre>files: {{ files }}</pre>
<v-file-upload multiple webkitdirectory />
<img
alt="Vue logo"
height="100px"
src="https://cdn.vuetifyjs.com/docs/images/one/logos/vplay-logo-dark.png"
>
</v-container>
</v-col>
</v-row>
</v-app>
</template> …
```
=> fix(VFileInput,VFileUpload): handle folders drop

packages/vuetify/src/components/VDataTable/VDataTableColumn.tsx, packages/vuetify/src/components/VDataTable/VDataTableHeaders.tsx
fixes #20899 
Added default tabindex to 0 for the cells in the table.
```vue
<template>
<v-data-table :headers="headers" :items="items" />
</template>
<script>
data: () => ({
headers: [
{ title: 'Dessert (100g serving)', align: 'start', key: 'name' },
{ title: 'Calories', key: 'calories', align: 'end', sortable: false },
{ title: 'Fat (g)', key: 'fat', align: 'end' },
{ title: 'Carbs (g)', key: 'carbs', align: 'end' },
{ title: 'Protein (g)', key: 'protein', align: 'end' },
{ title: 'Iron (%)', key: 'iron', align: 'end' },
],
items: [
{
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1',
},
{
calories: 375,
fat: 0.0,
carbs: 94,
protein: 0.0,
iron: '0',
},
{
name: 'KitKat',
calories: 518,
fat: 26.0,
carbs: 65,
protein: 7, …
```
=> fix(VDataTableColumn): columns are not keyboard-accessible fixes #20899

packages/vuetify/src/components/VSlider/VSliderThumb.tsx
fixes #21527
appy textcolor to slider label
```vue
<template>
<v-app>
<v-container class="mt-5">
<v-slider color="primary" thumb-label="always" thumb-color="red">
</v-slider>
</v-container>
</v-app>
</template>
```
=> fix(VSlider): Apply color to slider label

packages/vuetify/src/components/VBadge/VBadge.tsx
- Resolves: https://github.com/vuetifyjs/vuetify/issues/20837
- Adds new props `width` and `height` using our `DimensionProps`
```vue
<template>
<v-container>
<v-badge width="28px" height="30px" content="1" />
</v-container>
</template>
```
=> feat(VBadge): add size width and height props to VBadge (#28037)

packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.date.spec.ts, packages/vuetify/src/composables/date/__tests__/date.spec.ts, packages/vuetify/src/composables/date/adapters/vuetify.ts, packages/vuetify/src/composables/date/date.ts
fixes #21366
```vue
<template>
<v-app>
<v-container max-width="1200">
<div class="d-flex ga-6">
<v-date-picker :month="3" show-week />
<v-row>
<v-col>
<v-date-input v-model="rangeSelection" :month="2" :year="2025" multiple="range" show-week />
</v-col>
<v-col>
<v-alert type="info" variant="outlined">
<ul>
<li>1. select 3/29 ~ 3/31.</li>
<li>2. re-open the picker.</li>
</ul>
</v-alert>
<pre>rangeSelection: {{ rangeSelection }}</pre>
</v-col>
</v-row>
</div>
</v-container>
</v-app>
</template>
const rangeSelection = ref([])
</script>
```
=> fix(date): week number for DST

packages/vuetify/src/components/VSpeedDial/VSpeedDial.sass
fixes #21017
```vue
<template>
<v-app>
<v-container>
<v-fab app icon="mdi-arrow-up" location="bottom center">
<v-icon />
<v-speed-dial
location="top"
activator="parent"
transition="slide-y-reverse-transition"
>
<v-btn
v-for="i in 9"
:key="i"
prepend-icon="mdi-home"
:text="`Hello #${i}`"
size="small"
/>
</v-speed-dial>
</v-fab>
</v-container>
</v-app>
</template>
```
=> fix(VSpeedDial): avoid position glitch when reopening menu

packages/vuetify/src/components/VList/VListItem.sass, packages/vuetify/src/components/VList/_variables.scss
Tree view gets horizontal overflow and shows the items. It is not easy to guess how to work around this issue. It would be great if people would not need to resort to for CSS tricks. The idea is that they can inspect the title, see `40px` for `min-width` and eventually find a Sass variable or override it with CSS.
There is a side-effect of pushing append-icon's to the right. I don't think anyone would really mind it as it only occurs when the nesting is so deep the whole thing is already in a bad shape.
Feel free to switch `v-treeview` to `v-list` on the examples linked below.
resolves #21387
Playgrounds with a toggle to see before/after:
<details>
<summary>deep nesting</summary>
```vue
<template>
<v-app>
<v-app-bar>
<v-btn class="ml-auto" text="expand all" @click="openAll" /> …
```
=> fix(VTreeview): avoid inaccessible items when overflow

packages/vuetify/src/labs/VFileUpload/VFileUploadItem.tsx
- Fixes: https://github.com/vuetifyjs/vuetify/issues/21319
```vue
<template>
<v-app>
<v-container>
<VFileUpload v-model="files">
<template #title>
<p>Drag and Drop Here</p>
</template>
</VFileUpload>
</v-container>
</v-app>
</template>
<script setup>
const files = ref([])
</script>
```
=> fix(VFileUpload): file name not passed correctly

packages/docs/src/examples/v-combobox/prop-placeholder.vue, packages/docs/src/pages/en/components/combobox.md
resolves #20402 
A new example for using **persistent-placeholder** on `VCombobox`.
=> docs(VCombobox): persistent placeholder example

packages/docs/src/examples/v-carousel/misc-vertical.vue, packages/docs/src/pages/en/components/carousels.md, packages/vuetify/src/components/VWindow/VWindow.sass, packages/vuetify/src/components/VWindow/VWindow.tsx, packages/vuetify/src/components/VWindow/_variables.scss, packages/vuetify/src/styles/utilities/_index.sass, packages/vuetify/src/styles/utilities/_pointer-events.sass
On v2 `vertical-delimiters` on VCarousel caused the arrows to be hidden (to avoid obstructing the delimiters). I think we can have both coexisting.
Example in Docs is VCarousel scope because the feature is primarily intended for carousels.
```vue
<template>
<v-app>
<v-container max-width="700">
<v-card elevation="24" rounded="xl">
<v-carousel
height="400"
vertical-arrows="left"
vertical-delimiters="right"
>
<v-carousel-item v-for="i in 5" :key="i">
<v-sheet height="100%">
<div class="d-flex h-100 justify-center align-center">
<div class="text-h2">Slide #{{ i }}</div>
</div>
</v-sheet>
</v-carousel>
</v-card>
</v-container>
</v-app>
</template>
```
=> feat(VWindow): vertical arrows

packages/vuetify/src/components/VBtn/VBtn.sass
- resolves #21600
Fixes regression after #21574
- noticed [by Matthew](https://github.com/vuetifyjs/vuetify/pull/21574/files/78470e826d8981a6242c38f3d5e742b07e444fc5#r2155200407)
```sass
$button-text-letter-spacing: initial
```
=> fix(VBtn): allow text values for letter-spacing Sass variable

packages/vuetify/src/labs/VTimePicker/VTimePicker.tsx, packages/vuetify/src/labs/VTimePicker/VTimePickerControls.tsx
closes #19637
closes #19957
reverts #20178, there's no other am/pm button, so without setting `ampmInTitle` or `format="24hour"` you can't use pm times at all.
```vue
<template>
<v-app>
<v-container>
<v-time-picker v-model="time" />
<pre>{{ time }}</pre>
</v-container>
</v-app>
</template>
<script setup>
import { computed, ref, watch } from 'vue'
const time = ref()
</script>
```
=> feat(VTimePicker): remove ampmInTitle prop

packages/vuetify/src/components/VField/VField.tsx, packages/vuetify/src/components/VSelect/__tests__/VSelect.spec.browser.tsx
Fixes #21607
Reverts #21217
Developers facing problems with VNumberInput are advised to use `@mousedown.stop` on the injected buttons.
This reverts commit 14524423646a06fe6962183cda84a38c68feb6fe.
=> fix(VSelect, VAutocomplete, VCombobox): open menu on icon click

packages/vuetify/src/components/VDatePicker/VDatePickerMonth.sass, packages/vuetify/src/components/VDatePicker/VDatePickerMonth.tsx, packages/vuetify/src/composables/calendar.ts
reverts b1f270b
alternate to #21619
fixes #21492
fixes #19718
```vue
<template>
<v-app>
<v-container>
<v-date-picker :weekdays="[1, 2, 3, 4, 5]" />
<v-date-picker show-week />
<v-date-picker :weekdays="[1, 2, 3, 4, 5]" show-week />
<v-calendar
:weekdays="[1, 2, 3, 4, 5]"
view-mode="month"
hide-week-number
/>
<v-calendar
:weekdays="[1, 2, 3, 4, 5]"
view-mode="month"
/>
</v-container>
</v-app>
</template>
```
=> fix(VDatePicker): completely hide days not in weekdays array

packages/vuetify/src/components/VTextField/VTextField.tsx, packages/vuetify/src/components/VTextField/__tests__/VTextField.spec.browser.tsx, packages/vuetify/test/setup/browser-commands.ts
Password managers attempt use `.focus()` when inserting value.
When 2 fields get focus, the `nextTick` makes them compete for focus in an infinite loop.
fixes #21626
[Playground](https://play.vuetifyjs.com/#eNrFVctu2zAQ/BWCF9uAZcduixaGE7QFGqBAD0VflygHmlrZRCiSpZZ+wMi/dynFD9mCE7SH6sQdzu6Sw1nobstLL4cfnBssA/AJnyIUTguEm9QwNl0mwrlqWQWFUOYpqmJpDRIEfg/WsPAZk1qU5XXKi3UiAtqUs0Ksk5XKcEHo66urlB9l7fMSVKjh5oudK8NurS9Ywn4FQJVv2McwZ9/AeZsFicqa6bCR01oN1tjYqLZyqnuCVnhkJ7kCnZ1uMqbFDDSd/GcJ3ogCUn7OiThRwgVK1EJa0hjwOarz4MBkiSKZo5CZSoSUNhhsYy+FV8IgEW1ATY+SnbOGdOm/vPZXes2V9S1F99d2Fyi4cc9RTpSRwXswmFxKaVFIW/nwL/I0pCF/tViFFJuhYdJq6+OdvCqE35DBZ7E5ey+1kg+0ES+UK63J6LtlrEi5TavuXdz06g4/DFwETiYuYvupjEE9r9Ph0RxTWEqvHLISMNTjnAdTjVClejxZt8e2dUlqUSJTxgUcsWuWWRkKeojB7wB+8x00SLS+26kId2eOv+/06jJ1gUFO6WW3iS2FDkClO8WG7TI7DUamSidQL …
=> fix(VTextField): avoid infinite focus loop

packages/vuetify/src/composables/virtual.ts
This PR fixes an issue in `useVirtual` composable for dynamic item heights. If a static `item-height` is not provided, the height is calculated for each item dynamically. However, depending on the timing when the table gets rendered initially, it may happen that the `calculateVisibleItems` function is being called before the item heights have been determined.
If all heights are still 0, `binaryClosest` function calculates an index in the middle of the item array which leads to all items being rendered instead of lazy rendering.
See the behavior in the playground [here](https://play.vuetifyjs.com/#eNqlWHtz2kYQ/yo7lBYxQQKMnTiMiZs0SdtpHHuMp56O8YwP6QSqJZ16OuFQhu/evdOdHgjqJvUftrSP++3rdle+27RS7vbfJomzymhr3DoTNEpCIuibWQxwtrI9IogtyDyk9irgIiOhZABw6k9mLRreSNaslRPHS0o8ylPk6KeCE+DBkq4PeceIKJhLGiyWApnH …
=> fix(useVirtual): calculateVisibleItems: return if itemHeight is 0

packages/vuetify/src/components/VDatePicker/VDatePickerMonth.tsx, packages/vuetify/src/composables/__tests__/calendar.spec.ts, packages/vuetify/src/composables/calendar.ts, packages/vuetify/src/labs/VCalendar/VCalendar.tsx
Note: it might conflict with `weekday-format` (merged to `dev`), but should be easy to resolve
fixes #21645
fixes #21332
closes #21647
```vue
<template>
<v-app>
<v-container class="d-flex ga-6" fluid>
<v-date-picker title="first: default" />
<v-date-picker :weekdays="[1,2,3,4,5]" title="first: default + weekdays subset" />
<v-date-picker :first-day-of-week="0" title="first: 0" />
<v-date-picker :first-day-of-week="1" title="first: 1" />
<v-date-picker :first-day-of-week="1" :weekdays="[1,2,3,4,5]" title="first: 1 + weekdays subset" show-week />
</v-container>
<v-container>
<v-calendar view-mode="month" />
<v-calendar view-mode="month" :weekdays="[1,2,3,4,5]" />
<v-calendar view-mode="month" :first-day-of-week="1" />
<v-calendar view-mode="month" :first-day-of-week="1" …
```
=> fix(VDatePicker): correct week labels

packages/vuetify/src/composables/date/adapters/vuetify.ts
fixes #21667
```vue
<template>
<v-app>
<v-container>
<div>{{ fullDate }}</div>
</v-container>
</v-app>
</template>
<script setup>
import { useDate } from 'vuetify'
const adapter = useDate()
const fullDate = adapter.format(new Date(), 'fullDate')
</script>
```
=> fix(date): align `fullDate` format with documentation and other adapters

packages/vuetify/src/labs/VCalendar/VCalendar.tsx
=> fix(VCalendar): use adapter for day.date.getTime

packages/vuetify/src/components/VTreeview/VTreeviewItem.tsx
- makes it possible to use VTreeview as a navigation item
Note: very quick PR, I did not check for any regression
```vue
<template>
<v-app>
<v-navigation-drawer permanent>
<v-alert>
<small>
(after patch) item is activated when route changes
</small>
</v-alert>
<v-treeview
:item-props="addProps"
:items="items"
open-all
/>
<v-alert>
<small>
VList worked before. In both cases <b>item-value="id"</b> interrupts active state
</small>
</v-alert>
<v-list :item-props="addProps" :items="items" />
<v-main>
<router-view />
</v-main>
</v-app>
</template>
<script setup>
function addProps (item) {
return !item.children
? {
to: item.id ? `/page${item.id}` : '/',
nav: true,
}
: {}
}
{
id: 9,
children: [
{ id: 0, title: 'Home' },
{ id: 1, …
```
=> fix(VTreeview): active state from router

packages/docs/src/examples/hotkey/platform.vue, packages/docs/src/pages/en/features/hotkey.md, packages/docs/src/pages/en/introduction/why-vuetify.md, packages/docs/src/pages/en/labs/introduction.md
- Fixes an example that suggests usage of the windows key is supported
- Adds link in introduction/why-vuetify page to useHotkey
- Adds link to VHotkey in labs/introduction
=> docs(useHotkey): Fix Eratta

packages/vuetify/src/components/VField/VField.tsx, packages/vuetify/src/components/VField/VFieldLabel.tsx
fixes #21025
For floating labels, set `aria-hidden` to true if field is active, false if not active
```vue
<template>
<v-app>
<v-form>
<v-container>
<v-row>
<v-col cols="12" md="4" sm="6">
<v-text-field
label="Regular"
</v-col>
<v-col cols="12" md="4" sm="6">
<v-text-field
label="Solo"
variant="solo"
</v-col>
<v-col cols="12" md="4" sm="6">
<v-text-field
label="Filled"
variant="filled"
</v-col>
<v-col cols="12" md="4" sm="6">
<v-text-field
label="Outlined"
</v-col>
<v-col cols="12" md="4" sm="6">
<v-text-field
label="Plain"
variant="plain"
</v-col>
<v-col …
```
=> fix(VField): Fix label accessibility

packages/vuetify/src/labs/VDateInput/VDateInput.tsx
fixes #21683
Assign a type to display-format callback parameter
```vue
<template>
<v-date-input
v-model="date"
:display-format="(date) => date.toLocaleDateString()"
label="Date"
/>
</v-container>
</template>
</script>
```
=> fix(VDateInput): assign type to displayFormat function

packages/docs/src/data/page-to-api.json, packages/docs/src/examples/hotkey/usage.vue, packages/docs/src/pages/en/features/hotkey.md
=> docs(hotkey): fix links and usage demo

packages/vuetify/src/components/VList/VList.tsx
- re-enables ArrowUp/ArrowDown when `<input>` has focus
fixes #21516
<details>
<summary>Details</summary>
```vue
<template>
<v-container max-width="550">
<v-treeview
:items="items"
item-value="title"
select-strategy="classic"
open-all
selectable
>
<template #item="{ props }">
<v-list-item v-bind="props">
<template #prepend="{ isSelected, select }">
<v-checkbox-btn
:model-value="isSelected"
@update:model-value="select"
/>
</template>
<template v-if="currentItemToEdit === props.title" #append>
<v-form
ref="editForm"
class="d-flex ga-2 align-center"
@submit.prevent="saveChanges"
>
<v-text-field
v-model="newName"
:rules="[(v) => !!v || 'Required']"
class="mb-n6"
min-width="180"
placeholder="type something..."
variant="solo-filled"
@keydown.space.stop …
```
=> fix(VListItem): keyboard navigation when list contains checkboxes

packages/docs/src/examples/v-toolbar/misc-tooltips-and-speed-dial.vue, packages/docs/src/pages/en/components/toolbars.md
- new example guides users to use `v-btn` instead of `v-fab` inside toolbar
resolves #20575
- same code on [playground](https://play.vuetifyjs.com/#eNqFVd9r2zAQ/lduZuAU4pRSBsWk3crY22DQ7q3pgyKfG1FZEpKctgv533eS7VhOtjYvkU6fPt2P784Pu8xZfn5rzGLbYlZmS4+NkczjzUoBLLcFZ7aK67jzWss1s1ByLSUzDq9X2bBcZeCFl8H0u4Otsv5mvLv2atgBcMmcI2Qji8tVNtoF1yqYK1E07EmJ+i097RzwwpRr7b1uCJnfI7N8A0xKMFZXLfcuH+/cLM/jy+TIh67Y/7pSae+KLVovOJMpxok/IV7X0PMTR5kVTHk6QolbSmeVuDTCyJXwSnQyLiZHziBWRSWYhFJqzryIDgXDz35LOWfcC3pBWzoyzKLyZNQGVaFVsdHkdcJ6Gn2X1jpenwmq/hzEGQgF4Zlb4tbKpZGFX/mMbwQXJ3aSQiQKPIu4OYH0WY2IsD4GHEpMoB0MYZfQW4fA5+Dx1ZcQefoz2E/JktofoifLmNZRnRNg2PVCP8im74QivHpQTNgUnDKOFgwrrt7RexmwSbPAV8h/vBqmqhxKyL/35kS5JMw+m661NeNY9KJKId+4FPw55b2GT2ND/qMLhgAP0XSN3ltoszxPRgBtHbfCeHDoWxOxojHaetiB25Dq9csd1lQNTX+wh9rqBnKaJXmXOaqwo4SN3o2XZjWT …
=> docs(VToolbar): example with tooltips and VSpeedDial

packages/vuetify/src/labs/VFileUpload/VFileUploadItem.tsx
- aligns component with API docs claiming there is a `title` slot
```vue
<template>
<v-app>
<v-container>
<v-file-upload multiple title="title" clearable show-size>
<template v-slot:item="{ props: itemProps }">
<v-file-upload-item v-bind="itemProps">
<template v-slot:title="{ title }"> title: {{ title.substring(0, 10) }}... </template>
<template v-slot:subtitle> subtitle </template>
</v-file-upload-item>
</template>
</v-file-upload>
</v-container>
</v-app>
</template>
```
=> fix(VFileUploadItem): accept `title` slot

packages/vuetify/src/components/VCarousel/VCarousel.tsx
- `additional` slot should not be exposed in API docs for VCarousel because it is not used
=> docs(VCarousel): remove unused slot

packages/vuetify/src/components/VFileInput/VFileInput.sass
fixes #21707
```vue
<template>
<v-container max-width="300">
<v-alert
text="Choose files with long name fragments that do not contain spaces or dashes"
/>
<br />
<v-file-input label="File input" multiple></v-file-input>
<v-alert
text="Chips won't break. `truncate-length` will help here once #17972 gets merged."
/>
<br />
<v-file-input label="File input w/ chips" chips multiple></v-file-input>
</v-container>
</v-app>
</template>
```
=> fix(VFileInput): avoid text overflow with long file names

packages/vuetify/src/components/VProgressLinear/VProgressLinear.sass, packages/vuetify/src/components/VProgressLinear/VProgressLinear.tsx
- judging by git blame history for the [VProgressLinear.sass:43](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VProgressLinear/VProgressLinear.sass?rgh-link-date=2025-07-03T18%3A42%3A36.000Z#L43), it looks like a mistake or simplification
- changes aim to let user put interactive elements inside the content slot when `clickable` is not used
resolves #21690
<details>
<summary>Playground</summary>
```vue
<template>
<v-app>
<v-container max-width="500">
:clickable="false"
color="#0070CB"
height="30"
model-value="66"
rounded
striped
>
<v-chip class="ml-2" size="x-small" text="Operation #1" variant="flat" />
<v-btn
class="ml-auto mr-2"
color="red"
rounded="pill"
size="x-small"
text="Stop"
/>
</v-progress-linear>
<div class="pt-4" /> …
```
=> fix(VProgressLinear): accept pointer events unless `clickable` is used

packages/vuetify/src/components/VSlider/VSliderThumb.sass, packages/vuetify/src/components/VSlider/VSliderThumb.tsx, packages/vuetify/src/components/VSlider/slider.ts
fixes #21832
```vue
<template>
<v-container class="d-flex ga-6" max-width="600">
<v-card v-for="th in ['dark', 'light']" :key="th" :theme="th" class="d-flex flex-column ga-12 pt-16 flex-1-1-100">
<v-slider
thumb-label="always"
/>
<v-slider
thumb-color="primary"
thumb-label="always"
/>
<v-slider
thumb-color="primary"
thumb-label="always"
/>
</v-card>
</v-container>
<v-container class="d-flex ga-6" max-width="600">
<v-card class="flex-1-1-100 d-flex justify-center pt-6">
<v-slider
thumb-label="always"
/>
</v-card>
<v-card class="flex-1-1-100 d-flex justify-center pt-6">
<v-slider …
```
=> fix(VSlider): correctly apply `thumb-color`

packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.browser.tsx
resolves #21838
```vue
<template>
<v-container>
<v-combobox v-model="values" :delimiters="delimiters" chips multiple />
</v-container>
<pre>text to copy/paste: foo,bar,baz</pre>
</v-app>
</template>
<script setup>
const values = ref([])
const delimiters = [',']
</script>
```
=> fix(VCombobox): select all values from pasted text

packages/vuetify/src/composables/theme.ts
- makes it possible to call `.change('system')`
- exposes `.isSystem` boolean ref
Note: I don't think `theme.cycle(['dark', 'light', 'system'])` is something we should support. It would encourage devs to put out a single button that once every 3 clicks does not do anything (i.e. UX footgun).
fixes #21819
```vue
<template>
<v-app>
<v-container> Theme name: {{ theme.name }} <span v-if="theme.isSystem.value">(SYSTEM)</span> </v-container>
<v-container class="d-flex ga-3">
<v-btn text="Toggle Light / Dark" @click="theme.toggle()" />
<v-btn text="use 'system'" @click="theme.change('system')" />
<v-btn text="Cycle" @click="theme.cycle()" />
</v-container>
</v-app>
</template>
<script setup>
const theme = useTheme()
</script>
```
=> fix(theme): ability to restore "system"

packages/api-generator/src/locale/en/VPicker.json, packages/docs/src/data/new-in.json, packages/vuetify/src/labs/VPicker/VPicker.tsx
resolves #21545
```vue
<template>
<v-container>
<v-date-picker color="primary" hide-title />
</v-row>
</v-container>
</template>
```
=> feat(VPicker): hide the title slot

packages/api-generator/src/locale/en/VTimePicker.json, packages/docs/src/data/new-in.json, packages/vuetify/src/components/VTimePicker/VTimePicker.tsx
resolves #15405
```vue
<template>
<v-app>
<v-container>
<div class="d-flex justify-center ga-12">
<v-switch v-model="useSeconds" label="with seconds" />
<v-switch v-model="use24h" label="24h format" />
</div>
<v-row class="justify-center ga-10" no-gutters>
<v-card class="pa-6">
<v-time-picker
v-model="time"
v-model:period="period"
:ampm-in-title="!use24h"
:format="use24h ? '24hr' : 'ampm'"
:use-seconds="useSeconds"
scrollable
/>
</v-card>
<v-card class="pa-6" width="300">
<pre class="mb-6">value: <b>{{ time }}</b></pre>
<v-select
v-if="!use24h"
v-model="period"
:items="['am', 'pm']"
label="Period"
clearable
/>
</v-card>
</v-row>
</v-container>
</v-app>
</template>
<script setup>
const useSeconds = ref(false)
const use24h = ref(false)
const time = ref('11:15') …
```
=> feat(VTimePicker): accept external changes to the period

packages/api-generator/src/locale/en/VBtn.json, packages/docs/src/data/new-in.json, packages/docs/src/examples/v-btn/prop-spaced.vue, packages/docs/src/examples/v-tabs/prop-spaced.vue, packages/docs/src/pages/en/components/buttons.md, packages/docs/src/pages/en/components/tabs.md, packages/vuetify/src/components/VAppBar/VAppBarNavIcon.tsx, packages/vuetify/src/components/VBtn/VBtn.sass, packages/vuetify/src/components/VBtn/VBtn.tsx, packages/vuetify/src/components/VBtn/__tests__/VBtn.spec.browser.tsx, packages/vuetify/src/components/VFab/VFab.tsx, packages/vuetify/src/components/VTabs/VTabs.tsx
- new `spaced` prop accepts `start`, `end` and `both`
resolves #21652
```vue
<template>
<v-app>
<v-container max-width="800" class="d-flex align-center justify-center ga-3">
<v-btn color="red" spaced="start" width="150" prepend-icon="$prev" text="Left" />
<v-btn color="red" spaced="both" width="250" append-icon="$next" prepend-icon="$prev" text="Center" />
<v-btn color="red" spaced="end" width="150" append-icon="$next" text="Right" />
</v-container>
<v-container max-width="800">
<v-tabs :items="tabs" density="compact" slider-color="red" spaced="end" grow />
<v-tabs :items="tabs" density="comfortable" slider-color="red" spaced="start" grow />
<v-tabs :items="tabs" density="default" slider-color="red" spaced="both" grow />
</v-container>
<v-container max-width="800">
<v-tabs :items="tabs" …
```
=> feat(VBtn): `spaced` prop to move icons to the edges

packages/vuetify/src/components/VNumberInput/VNumberInput.tsx
fixes #21735
fixes #21804
```vue
<template>
<v-app>
<v-container max-width="200">
v-model="currentNumber"
control-variant="hidden"
rounded="pill"
:step="0.1"
:precision="1"
>
<template #prepend-inner>
<v-icon-btn
v-ripple
icon="mdi-numeric-negative-1"
@click.stop="currentNumber += 1"
/>
</template>
<template #append-inner>
<v-icon-btn
v-ripple
icon="mdi-numeric-positive-1"
@click.stop="currentNumber += 1"
/>
</template>
</v-number-input>
</v-container>
</v-app>
</template>
<script setup>
const currentNumber = ref(5.5)
</script>
<style>
.v-number-input .v-field {
padding-inline: 6px;
input {
text-align: center;
font-weight: bold;
font-size: 1.25rem;
margin-block: -0.125rem;
line-height: 1;
} …
```
=> fix(VNumberInput): accept external changes when focused

packages/vuetify/src/components/VNumberInput/VNumberInput.tsx
resolves #17083
```vue
<template>
<v-app>
<v-main>
<v-container :max-width="650">
<p>
Text field outside of list (type number), value can be inc/decremented
with arrow keys
</p>
<v-text-field type="number" />
<v-list>
<v-list-item
title="Field 1"
subtitle="Text field in list, arrow keys don't work here"
>
<v-text-field
label="v-text-field"
type="number"
width="200"
hide-details
/>
</template>
</v-list-item>
<v-list-item
title="Field 2"
subtitle="Text field in list, arrow keys don't work here"
>
label="v-number-input"
width="200"
hide-details
/>
</template>
</v-list-item>
</v-list>
</v-container>
</v-main>
</v-app>
</template>
```
=> fix(VNumberInput): keep focus when incrementing in the list

packages/api-generator/src/locale/en/VColorInput.json, packages/docs/src/examples/v-color-input/prop-pip-location.vue, packages/docs/src/examples/v-color-input/prop-pip-variant.vue, packages/docs/src/examples/v-color-input/usage.vue, packages/docs/src/pages/en/components/color-inputs.md, packages/vuetify/src/labs/VColorInput/VColorInput.sass, packages/vuetify/src/labs/VColorInput/VColorInput.tsx, packages/vuetify/src/labs/VColorInput/_variables.scss
- introduces `hide-pip`
- introduces `pip-location`
- renames existing `pip` to `color-pip` (as it was named in the docs)
- introduces `pip-variant`
resolves #21712
```vue
<template>
<v-sheet class="px-6 py-2 border-b" color="surface">
<div class="d-flex gx-3 flex-wrap">
<div class="d-flex align-center ga-3">
<span class="mr-3">Lines:</span>
<v-chip-group v-model="density" mandatory>
<v-chip text="default" value="default" filter label />
<v-chip text="comfortable" value="comfortable" filter label />
<v-chip text="compact" value="compact" filter label />
</div>
<v-spacer />
<v-switch
v-model="hasLabel"
:color="selection"
:label="`label ${hasLabel ? 'ON' : 'OFF'}`"
hide-details
/>
</div>
</v-sheet>
<v-sheet class="px-6 py-2 border-b" color="surface"> …
```
=> feat(VColorInput): pip customization

packages/vuetify/src/components/VTreeview/VTreeviewChildren.tsx, packages/vuetify/src/components/VTreeview/VTreeviewItem.sass, packages/vuetify/src/components/VTreeview/VTreeviewItem.tsx
- make the tree support `prependIcon` and `prependAvatar` (mostly copied from VListItem)
- changes `<div>` around checkbox to `<v-list-item-action start>`
- there is a chance that devs already have CSS workarounds to shift checkboxes or space out prepended icons. We need a clear hint in release notes for 3.10.0 --- it is better than dragging bad defaults until v4
resolves #21812
```vue
<template>
<v-app>
<v-toolbar class="pl-8" height="50">
<span class="mr-3">Density:</span>
<v-chip-group v-model="density" mandatory>
<v-chip text="default" value="default" filter label />
<v-chip text="comfortable" value="comfortable" filter label />
<v-chip text="compact" value="compact" filter label />
<v-chip text="narrow" value="narrow" filter label />
</v-toolbar>
<v-toolbar …
```
=> fix(VTreeview): support prepend icon and avatar

packages/vuetify/src/components/VDataTable/VDataTable.sass, packages/vuetify/src/components/VTable/VTable.sass
- quick fix for missing stripes on the fixed columns
Note: the changes cut deep and require a bit more consideration for potential consequences. Please share your thoughts.
```vue
<template>
<v-app theme="_dark">
<v-container>
<v-card max-width="540">
<v-data-table
:headers="header"
:items="items"
fixed-header
striped="even"
>
<template #item.icon>
<v-icon icon="mdi-truck" />
</template>
<template #item.status>
<v-icon icon="mdi-cow" />
</template>
<template #item.actions>
<v-btn>action btn</v-btn>
</template>
</v-card>
</v-container>
</v-app>
</template>
<script setup>
{ category: 'G1', key1: 100000, key2: 200000, key3: 300000, key4: 400000, key5: 500000 },
{ category: 'G1', key1: 100000, key2: 200000, key3: 300000, key4: 400000, key5: 500000 },
{ …
```
=> fix(VDataTable): missing stripes on fixed columns

packages/vuetify/src/util/getScrollParent.ts
fixes #20625
```vue
<template>
<v-app>
<v-container class="overflow-auto">
<div style="width: 200vw; padding-left: 300px">
<v-btn color="primary">
`overflow-auto`
<v-menu scroll-strategy="reposition" activator="parent">
<v-list :items="items" item-props />
</v-menu>
</v-btn>
</div>
</v-container>
<v-container class="overflow-scroll">
<div style="width: 200vw; padding-left: 300px">
<v-btn color="primary">
`overflow-scroll`
<v-menu scroll-strategy="reposition" activator="parent">
<v-list :items="items" item-props />
</v-menu>
</v-btn>
</div>
</v-container>
<v-container class="overflow-auto pa-12 border-lg" style="max-height: 300px">
<v-container class="overflow-auto border-md" style="height: 600px">
<div style="width: 200vw; padding-left: 300px">
<v-btn color="primary">
nested
<v-menu …
```
=> fix(VMenu, VTooltip): scroll strategy reposition for horizontal overflow

packages/api-generator/src/locale/en/VTreeviewItem.json, packages/docs/src/data/new-in.json, packages/docs/src/examples/v-treeview/slot-toggle.vue, packages/docs/src/pages/en/components/treeview.md, packages/vuetify/src/components/VTreeview/VTreeview.tsx, packages/vuetify/src/components/VTreeview/VTreeviewChildren.tsx, packages/vuetify/src/components/VTreeview/VTreeviewItem.tsx, packages/vuetify/src/components/VTreeview/__tests__/VTreeview.spec.browser.tsx, packages/vuetify/src/components/VTreeview/shared.ts
fixes #20307
```vue
<template>
<v-app>
<v-container max-width="500">
<v-alert text="Icon gets smaller with depth" type="info" />
<v-treeview
:items="items"
collapse-icon="mdi-chevron-down"
expand-icon="mdi-chevron-right"
select-strategy="classic"
open-all
selectable
>
<template #toggle="{ props: toggleProps, depth }">
<v-btn v-bind="toggleProps">
<v-icon :size="24 - 2 * depth" />
</v-btn>
</template>
<template #title="{ item }">
<span class="text-caption">{{ item.title }}</span>
</template>
</v-treeview>
</v-container>
</v-app>
</template>
<script setup>
const model = ref()
const GetChildren = (id, depth) => {
if (depth > 4) return undefined
const nodes = []
nodes.push({
id: `${id}-${1}`,
title: `Example child item …
```
=> feat(VTreeview): add slot to replace expand toggle btn

packages/vuetify/src/components/VDataTable/VDataTable.sass, packages/vuetify/src/components/VDataTable/VDataTableColumn.tsx, packages/vuetify/src/components/VDataTable/VDataTableGroupHeaderRow.tsx, packages/vuetify/src/components/VDataTable/VDataTableHeaders.tsx, packages/vuetify/src/components/VDataTable/VDataTableRow.tsx, packages/vuetify/src/components/VDataTable/types.ts
- removes padding entirely for group column with `title: '', width: 0`
- introduces `indent` field to align group items
- adds colspan to handle longer group names (and support empty column)
- resolves #17863
<details>
<summary>Preview</summary>
</details>
```vue
<template>
<v-sheet class="px-6 py-2 border-b" color="surface">
<div class="d-flex ga-8 flex-wrap justify-center">
<v-chip-group v-model="features" multiple>
<v-chip text="debug lines" value="outline" filter label />
<v-chip text="show-expand" value="show-expand" filter label />
<v-chip text="show-select" value="show-select" filter label />
</div>
</v-sheet>
<v-container :class="{ debugLines: features.includes('outline') }" max-width="800">
<v-data-table
v-model="selection"
:group-by="groupBy" …
```
=> fix(VDataTable): more flexible alignment with grouping

packages/vuetify/src/components/VDataIterator/VDataIterator.tsx
``` vue
<template>
<v-text-field v-model="search" label="Search" />
<v-data-iterator v-model:page="page" :items="items" :items-per-page="10" :search="search">
<template #default="{ items }">
<v-card
v-for="(item, i) in items"
:key="i"
v-bind="item.raw"
/>
</template>
<template #footer="{ pageCount, itemsCount }">
<v-pagination
v-model="page"
:length="pageCount"
/>
<pre>Total items found: {{ itemsCount }}</pre>
</template>
</v-data-iterator>
</v-container>
</v-app>
</template>
<script setup>
const search = ref(null)
const page = ref(1)
const items = ref(Array.from({ length: 77 }, (_, i) => ({ title: `Item #${i}` })))
</script>
```
=> feat(VDataIterator): add filtered items count to slot data

packages/docs/src/examples/application-layout/layout-information-composable.vue
In order to get the "GET DATA" button work properly for all layout components.
```vue
```
=> docs: wrap <v-footer> in <child> in example

packages/docs/src/examples/v-autocomplete/prop-filter-keys.vue, packages/docs/src/pages/en/components/autocompletes.md
Closes #21799
Added section to the documentation page explaining the behavior of the `filter-keys` prop with related example
=> docs(VAutocomplete): add filter-keys prop section and example

packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete.spec.browser.tsx, packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.browser.tsx, packages/vuetify/src/components/VTextField/VTextField.tsx
fixes #18125
Add role attribute to <input element in VTextField so that when it is passed in as a prop, it is assigned to the input element. This ensures screen readers read out the role of input field
This PR fixes the linked issue because VTextField is used in VSelect and role prop is passed as combobox.
```vue
<template>
<v-app>
<v-container>
<v-select label="Select" :items="['item1', 'item2', 'item3']" />
</v-container>
</v-app>
</template>
<script setup>
</script>
```
=> fix(VTextField): assign role to input element

packages/vuetify/src/components/VSelect/VSelect.tsx
fixes #21097
Make screen readers read selected text instead of selected value when navigated to the component.
```vue
<template>
<v-select
:items="items"
item-title="state"
item-value="abbr"
label="Select"
return-object
single-line
aria-describedby="selected-state"
>
<template v-slot:selection="{ item }">
<span id="selected-state">{{ item.title }}</span>
</template>
</v-select>
</template>
<script>
methods: {
mapper: props => {
props.key = props.title
return props
},
},
data() {
return {
select: { state: 'Florida', abbr: 'FL' },
items: [
{ state: 'Florida', abbr: 'FL' },
{ state: 'Georgia', abbr: 'GA' },
{ state: 'Nebraska', abbr: 'NE' },
{ state: 'California', abbr: 'CA' },
{ state: 'New York', abbr: 'NY' },
],
}
},
}
</script>
```
=> fix(VSelect): use selected text instead of value

packages/vuetify/src/components/VDatePicker/VDatePicker.tsx
fixes #21911
Prioritize allowed-months and allowed-years
```vue
<template>
<v-app>
<v-container>
<v-date-input
label="Date selection"
:allowed-dates="allowedDates"
/>
<v-date-input
label="Date selection"
:allowed-months="[7, 8]"
:allowed-years="[2024, 2025]"
/>
</v-container>
</v-app>
</template>
<script setup>
function allowedDates (date) {
const isAllowedYear = [2024, 2025].includes(new Date(date).getFullYear())
const isAllowedMonth = [7,8].includes(new Date(date).getMonth())
return isAllowedYear && isAllowedMonth
}
</script>
```
=> fix(VDatePicker): Prioritize allowed-months and allowed-years

packages/vuetify/src/components/VSelect/VSelect.sass
fixes #21922
Fix VSelect placeholder overlap with menu icon
```vue
<template>
<v-app>
<v-container>
<v-select
width="200px"
placeholder="This is a long placeholder asdas. asd asd asd"
/>
</v-container>
</v-app>
</template>
```
=> fix(VSelect): Select placeholder overlap

packages/vuetify/src/components/VCard/VCard.sass
fixes #21835 
```vue
<template>
<v-row dense>
<v-card
:variant="variant"
color="surface-variant"
max-width="344"
subtitle="Greyhound divisely hello coldly fonwderfully"
title="Headline"
>
<template v-slot:actions>
<v-btn text="Button"></v-btn>
</template>
</v-card>
<div class="text-center text-caption">{{ variant }}</div>
</v-col>
</v-row>
<v-row dense>
<v-card
:variant="variant"
color="surface-variant"
max-width="344"
subtitle="Greyhound divisely hello coldly fonwderfully"
title="Headline (Loading)"
loading
>
<template v-slot:actions>
<v-btn text="Button"></v-btn>
</template>
</v-card>
<div class="text-center …
```
=> fix(VCard): hide progress border in forced-colors mode

packages/vuetify/src/components/VBtn/VBtn.sass
This addresses the request for High Contrast Support https://github.com/vuetifyjs/vuetify/issues/21515 for the VBtn component by adding a border to all v-btns except for the text & plain variant when forced-color mode (For example, High Contrast Mode in Windows) is enabled.
Before:
After:
```vue
<template>
<v-row dense>
<v-btn :variant="variant" color="primary">
{{ variant }}
</v-btn>
</v-col>
</v-row>
</template>
<script>
data: () => ({
variants: ['elevated', 'flat', 'tonal', 'outlined', 'text', 'plain'],
}),
}
</script>
```
=> feat(VBtn): High Contrast Support (Forced-colors mode)

packages/vuetify/src/labs/VMaskInput/VMaskInput.tsx, packages/vuetify/src/labs/VMaskInput/__tests__/VMaskInput.spec.browser.tsx
fixes #21776
Fix caret position while editing mask value from middle
```vue
<template>
<v-app>
<v-container>
<v-row>
<v-mask-input
v-model="msg"
:mask="mask"
:placeholder="mask"
/>
</v-row>
</v-container>
</v-app>
</template>
<script setup>
import { ref, computed } from 'vue';
const mask = ref('(AA)-###-NNN-##-##')
const msg = ref('AS123XYZ4567');
</script>
```
=> fix(VMaskInput): fix caret position while editing

packages/docs/src/composables/markdown.ts
Include examples as code snippets and improve error handling
Resolves #21711
=> docs: include example as snippets in the exported markdown

packages/vuetify/src/composables/filter.tsx
resolves #7424
```vue
<template>
<v-container>
:items="items"
autocomplete="off"
label="I will keep subheaders and dividers when it makes sense"
multiple
/>
</v-container>
</template>
<script setup>
{ type: 'subheader', title: 'Group 1' },
{ title: 'Item 1.1', value: 11 },
{ title: 'Item 1.2', value: 12 },
{ title: 'Item 1.3', value: 13 },
{ title: 'Item 1.4', value: 14 },
{ type: 'divider' },
{ type: 'subheader', title: 'Group 2' },
{ title: 'Item 2.1', value: 21 },
{ title: 'Item 2.2', value: 22 },
{ title: 'Item 2.3', value: 23 },
]
</script>
```
=> feat(filter): keep dividers and subheaders

packages/vuetify/src/components/VFileInput/VFileInput.tsx, packages/vuetify/src/components/VTextField/VTextField.tsx, packages/vuetify/src/components/VTextarea/VTextarea.tsx
Note: changes are done in components built on top of VField
fixes #21417
```vue
<template>
<v-text-field
label="v-text-field"
prepend-inner-icon="mdi-cow"
model-value="text value"
clearable
@click:clear="onClear"
/>
<v-file-input
label="v-file-input"
clearable
@click:clear="onClear"
/>
<v-textarea
label="v-textarea"
prepend-inner-icon="mdi-cow"
model-value="text value"
clearable
@click:clear="onClear"
/>
<v-select
label="v-select"
prepend-inner-icon="mdi-cow"
model-value="text value"
clearable
@click:clear="onClear"
/>
<v-combobox
label="v-combobox"
prepend-inner-icon="mdi-cow"
model-value="text value"
clearable
@click:clear="onClear"
/>
label="v-autocomplete"
prepend-inner-icon="mdi-cow"
model-value="text value"
clearable …
```
=> fix(VField): avoid duplicated emits on clear

packages/vuetify/src/components/VDatePicker/VDatePickerYears.tsx
fixes #21950
Make sure VDateInput scrolls to selected year when view-mode="year"
```vue
<template>
<v-app>
<v-container>
<v-date-input v-model="date" view-mode="year" hide-header />
</v-container>
</v-app>
</template>
<script setup>
</script>
```
=> fix(VDatePickerYears): fix scroll/focus of selected year

packages/vuetify/src/components/VAlert/VAlert.sass
This improves the appearance of the VAlert component when in forced-colors mode (For example, High Contrast Mode in Windows):
Since an alert is meant to get the user's attention, this will add a border (when forced-colors mode is active) to all alerts with the width reflecting based on the visual hierarchy of the variants. Since the elevated and flat variants appear to have the strongest visual hierarchy, they both have been grouped with a thick border. As text & plain have the weakest visual hierarchy they have been grouped with a thin border with the plain variant having a dashed border instead of a solid border since it stands out the least. 
_VAlert when not in forced-colors mode (High Contrast Mode in Windows):_
_VAlert Component when in forced-colors mode (High Contrast Mode in …
=> feat(VAlert): High Contrast Support (Forced-colors mode)

packages/vuetify/src/components/VCard/VCard.sass
This addresses the request for High Contrast Support #21515 for the VCard component by adding a border to all v-cards except for the text & plain variant when forced-color mode (For example, High Contrast Mode in Windows) is enabled.
Before: 
After: 
```vue
<template>
<v-row dense>
<v-card
:variant="variant"
color="surface-variant"
max-width="344"
subtitle="Greyhound divisely hello coldly fonwderfully"
title="Headline"
>
<template v-slot:actions>
<v-btn text="Button"></v-btn>
</template>
</v-card>
<div class="text-center text-caption">{{ variant }}</div>
</v-col>
</v-row>
<v-row dense>
<v-card
:variant="variant" …
```
=> fix(VCard): render border in forced-colors mode

packages/vuetify/src/components/VChip/VChip.sass
This addresses the request for High Contrast Support https://github.com/vuetifyjs/vuetify/issues/21515 for the VChip component by adding a border to all v-chips except for the text & plain variant when forced-color mode (For example, High Contrast Mode in Windows) is enabled.
Before:
After:
```vue
<template>
<v-row>
<v-chip :variant="variant" color="primary">
{{ variant }}
</v-chip>
</v-col>
</v-row>
</template>
<script>
data: () => ({
variants: ['elevated', 'flat', 'tonal', 'outlined', 'text', 'plain'],
}),
}
</script>
```
=> fix(VChip): render border in forced-colors mode

packages/vuetify/src/labs/VDateInput/VDateInput.tsx
- enables deeper customization without forcing devs to rebuild the component
```vue
<template>
<v-app>
<v-container class="text-center">
<v-date-input hide-header>
<template #day="{ props, item }">
<v-btn
v-bind="props"
:color="!item.isSelected && isWeekend(item.isoDate) ? 'grey' : undefined"
:text="item.localized"
:variant="!item.isSelected && isWeekend(item.isoDate) ? 'flat' : 'outlined'"
rounded="lg"
/>
</template>
<template #month="{ props, month }">
<v-btn v-bind="props" rounded="lg" variant="outlined">
{{ monthText(month.value) }}
</v-btn>
</template>
<template #year="{ props, year }">
<v-badge :model-value="year.value % 4 === 0" dot>
<v-btn v-bind="props" rounded="lg" variant="outlined">
{{ year.value }}
</v-btn>
</v-badge>
</template>
</v-date-input>
</v-container>
</v-app> …
```
=> feat(VDateInput): pass-through picker slots

packages/vuetify/src/composables/__tests__/filter.spec.ts, packages/vuetify/src/composables/filter.tsx
- `intersection` (default) causes all rows to be filtered out when all headers have `filter` function
- the test case seems to be wrong
<details>
<summary>Minimal example</summary>
```vue
<template>
<v-container>
<v-data-table
:items="plants"
/>
</v-container>
</v-app>
</template>
const plants = [
{ name: 'Fern', light: 'Low', height: '20cm', petFriendly: 'Yes', price: 20 },
{ name: 'Snake Plant', light: 'Low', height: '50cm', petFriendly: 'No', price: 35 },
{ name: 'Monstera', light: 'Medium', height: '60cm', petFriendly: 'No', price: 50 },
{ name: 'Pothos', light: 'Low to medium', height: '40cm', petFriendly: 'Yes', price: 25 },
{ name: 'ZZ Plant', light: 'Low to medium', height: '90cm', petFriendly: 'Yes', …
```
=> fix(VDataTable): allow filters on all columns

packages/vuetify/src/components/VOtpInput/VOtpInput.tsx
fixes #21680 
```vue
<template>
<v-app>
<v-container>
<v-otp-input :model-value="123456" />
</v-container>
</v-app>
</template>
```
=> fix(VOtpInput): focus jumps to the end when correcting filled input

packages/docs/src/examples/v-menu/prop-positioningmenu.vue, packages/docs/src/examples/v-select/prop-avoid-duplicate-text.vue, packages/docs/src/pages/en/components/selects.md
Add example for avoiding duplicate text when using item slot in v-select
Resolves #19396
=> docs: add example for avoiding duplicate text using item slot

packages/vuetify/src/components/VChipGroup/VChipGroup.sass
This addresses the request for High Contrast Support https://github.com/vuetifyjs/vuetify/issues/21515 for the VChipGroup component by fixing the rendering of the selected v-chip when using a `v-chip-group` when in forced-colors mode (e.g. Windows Accessibility > Contrast themes)  
Before & After gif
```vue
<template>
<v-chip-group>
<v-chip>Chip 1</v-chip>
<v-chip>Chip 2</v-chip>
<v-chip>Chip 3</v-chip>
</template>
```
=> fix(VChipGroup): render selected in forced-colors mode

packages/vuetify/src/components/VChip/_variables.scss
This pull request fixes the opacity for `v-chip` when set to the `plain` variant, all other components have their plain-opacity set to `.62`, however the `v-chip` had a default of `0.26` which that value seems to be used for `disabled-opacity` in other components.
```vue
```
=> fix(VChip): fix plain opacity

packages/api-generator/src/locale/en/VProgressCircular.json, packages/docs/src/data/new-in.json, packages/vuetify/src/components/VProgressCircular/VProgressCircular.tsx
This change adds a `rounded` prop to the `VProgressCircular` component to provide rounded stroke caps for a softer, more polished appearance.
The current `VProgressCircular` component only supports square stroke caps, which can appear harsh or less visually appealing in certain design contexts. Many modern UI libraries and design systems offer rounded stroke caps as a standard option for progress indicators, as they provide:
1. **Better visual consistency** with other rounded UI elements
2. **Softer, more modern appearance** that aligns with current design trends
3. **Enhanced user experience** through more polished visual feedback
4. **Design flexibility** for developers who want to match their brand's aesthetic
- **Design limitation**: Currently, developers cannot achieve rounded stroke …
=> feat(VProgressCircular): add rounded prop for rounded stroke caps

packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.browser.tsx
`hideNoData` was changed to `true` in #21901 and it was hiding regression - every 2nd event, typing with no match opens/closes menu.
`hideNoData` was reverted as a last-minute call before publishing 3.10.0, I have no strong opinions, let's roll with it. As a side-effect, the default behavior is noticably broken:
[Screencast from 2025-09-11 01-44-54.webm](https://github.com/user-attachments/assets/eadfebfc-fb21-4b6d-988b-a01554a96c49)
TODO:
```vue
<template>
<v-container>
<v-combobox
v-model="msg"
autocomplete="suppress"
/>
</v-container>
</v-app>
</template>
<script setup>
const msg = ref('xx')
</script>
```
=> fix(VCombobox): unstable menu state while typing

packages/vuetify/src/components/VDataTable/composables/expand.ts
fixes https://github.com/vuetifyjs/vuetify/issues/21096
Changed to use key when it's an object.
There might be a better function name.
```vue
<template>
<v-data-table
:items="movies"
item-value="title"
return-object
show-expand
>
<template
v-slot:item.data-table-expand="{ internalItem, isExpanded, toggleExpand }"
>
<v-btn
:append-icon="isExpanded(internalItem) ? 'mdi-chevron-up' : 'mdi-chevron-down'"
:text="isExpanded(internalItem) ? 'Collapse' : 'More info'"
class="text-none"
color="medium-emphasis"
size="small"
variant="text"
border
slim
@click="toggleExpand(internalItem)"
></v-btn>
</template>
<template v-slot:expanded-row="{ columns, item }">
<tr>
<td :colspan="columns.length" class="py-2">
<v-sheet rounded="lg" border>
<v-table …
```
=> fix(VDataTable): enable expand when return-object is true

packages/vuetify/src/components/VBtn/VBtn.tsx, packages/vuetify/src/components/VChip/VChip.tsx, packages/vuetify/src/composables/router.tsx
fixes #21594
Added handling for when navigation fails
Similar modifications may be required in other places where you use navigate.
[https://play.vuetifyjs.com/#eNqN...](https://play.vuetifyjs.com/#eNqNVV1v2jAU/Stu9pAgQTygqyYEjE176MOmTdNepqYPaXIpmRI7sh0oqvjvu/7AhMAKDy329bnnftknD6+BFBmt0oLFf2UwCYqq5kKRV5IJSBV8rmuyI0vBKxKuGwgT5gG4VcVy649j6ixIdMAJ3igQHmK3RwgdYn+M6/goDNokqKa2HgnLOJOKpOgyO2QY4V8vYWiN8XxZPMcgBBf3KctLjD0jQGZzol15CfYsAnSwLo2EyGXuSLTFJupBFW+YisJ3uA7RGPRN21y62LapgqouMZ15wgiZrgcINEuzUemTdLv9nig+SwJap88wGCbB/CcuyA8GU2qO30CP9ujfG34ZPfbolYAOu9vp1Hyq+iYc6GwXBusCNoS2vDxKb2ypU9pqAfbHDhCRenacYY9etUPiDmQSTIixaBs2Ue+TYKVULSeUZrm+jzmUxVrEDBRldUUXCKMCB1FUMMh5tRjHH+LhHc0Lqdr2GGQ1eBJ8I81VS4J+K46e8xWxHBJDfIyH720IZxuU2DMd44Qb76pYY78EsBwEiGtr6rgd1dU5e7O2gZ3XdeU58OIWgx0KdNb/hzEJ57BWnJcSZ19cW2TbZ3EX38 …
=> fix(VBtn): handle navigation failures in click behavior

packages/vuetify/src/labs/VCalendar/VCalendar.tsx, packages/vuetify/src/labs/VCalendar/composables/calendarBase.ts, packages/vuetify/src/labs/VCalendar/composables/calendarWithEvents.tsx
- issue occurs when `firstWeekday` is `0` while effective visible week starts at a different (see last example in docs)
- migration to v3 changed the logic resolving `eventWeekdays` ([VCalendar.ts:144](https://github.com/vuetifyjs/vuetify/blob/v2-stable/packages/vuetify/src/components/VCalendar/VCalendar.ts#L144)) - it was meant to get weekdays after applying `props.type`
=> fix(VCalendar): avoid head expanding on mousedown

packages/docs/src/examples/v-infinite-scroll/usage.vue
`items` is not a `v-infinite-scroll`  prop.
=> Delete items prop from v-infinite-scroll usage

packages/api-generator/src/locale/en/VCombobox.json, packages/docs/src/data/new-in.json, packages/vuetify/src/components/VCombobox/VCombobox.tsx, packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.browser.tsx
closes #22060
Relates to: https://github.com/vuetifyjs/vuetify/pull/21901
####
- Add new props `alwaysFilter` defaults to `false` to allow the previous behavior consistent with components like `VSelect` and `VAutocomplete`
- ~~If set to `true` it will prevent to set the `isPristine` to `false` on initial load~~
- ~~Instead of passing the `search` immediately check `isPristine` and determine the value to pass~~
```vue
// This example will show the previous behavior
// On menu show it should show all the items
// Pass always-filter to see it filter on load
<template>
<v-app>
<v-container>
<v-combobox
v-model="msg"
:items="['Colorado', 'Florida', 'Georgia', 'Texas', 'Wyoming', 'California']"
/>
</v-container>
</v-app>
</template>
<script setup>
const msg = …
```
=> feat(VCombobox): always show only matching suggestions

packages/vuetify/src/components/VDialog/VDialog.tsx, packages/vuetify/src/components/VDialog/__test__/VDialog.spec.browser.tsx
- Registers a keydown event listener on VDialog to focus on the first focusable element when the Tab key is pressed on the last focusable element in the dialog.
- Added two tests to test focus behavior when focus moves from the first and last buttons in a VDialog.
fixes #21945 
```vue
<template>
<div class="text-center pa-4">
<v-dialog v-model="dialog" max-width="400">
<template v-slot:activator="{ props: activatorProps }">
<v-btn v-bind="activatorProps"> Open Dialog </v-btn>
</template>
<v-btn @click="dialog = false"> Disagree </v-btn>
<v-btn @click="dialog = false"> Agree </v-btn>
</v-dialog>
</div>
</template>
<script setup>
const dialog = ref(false)
// for debugging
const showPressedKey = (e) => {
const now = new Date()
const msg = `[${now.toISOString()}] …
```
=> fix(VDialog): fix focus trap when tabbing forward

packages/vuetify/src/util/animation.ts, packages/vuetify/src/util/box.ts
When the zoom is forced with CSS, browser calculates wrong offsets for elements (`getBoundingClientRect`) and transforms for tooltips and menus are skewed.
fixes #20719
> **NOTE:** Safari does not support `document.body.currentCSSZoom`, but you should be able to set this value manually (and keep in sync with forced zoom value).
> Note: you have to `pnpm build` for the playground to pick up changes in the **box.ts**
<details>
<summary>dev/index.html</summary>
```diff
<!DOCTYPE html>
-<html lang="en">
+<html lang="en" style="zoom: .75;">
<body>
<div id="app"></div>
+    <script>window.pageScale = 0.75</script>
<script type="module" src="/index.js"></script>
</body>
</html>
```
</details>
<details>
<summary>dev/Playground.vue</summary>
```vue
<template>
<v-container> …
```
=> feat(locationStrategies): support CSS zoom

packages/docs/src/components/introduction/ConsultingServices.vue, packages/docs/src/pages/en/introduction/enterprise-support.md
This PR updates `ConsultingServices.vue` component related to Epicmax consulting services section for `/introduction/enterprise-support` page.
PR contains small template and data changes.
```vue
<template>
<v-sheet
border="s e b"
class="overflow-hidden"
max-width="900"
rounded
>
<v-divider
class="border-opacity-100"
thickness="4"
/>
<v-container class="pt-9 px-5" fluid>
<v-row justify="space-around" dense>
<template v-for="({ text, href, name, btnText, notes }, i) in cards" :key="i">
<v-col cols="12" md="6">
<v-responsive class="h-100" content-class="d-flex flex-column">
<h3 class="d-flex align-center text-h6 font-weight-medium mb-4">
{{ name }}
</h3>
<div class="mb-auto text-caption">
<div class="mb-4">{{ text }}</div>
<ul v-if="notes && notes.length" class="mb-0 ml-5"> …
```
=> docs: epicmax consulting services update

packages/vuetify/src/components/VNumberInput/VNumberInput.tsx, packages/vuetify/src/components/VNumberInput/__tests__/VNumberInput.spec.browser.tsx
It is not obvious when typing the value and it gets out of range. There is also no indication of a problem when `min` and `max` change and the value does not fit in between - forcing developers to always add `rules`.
Note: "error" state will only trigger when typing, changing the range or updating `model-value` with delay. Auto-clamp on mount will be dropped in 4.0.0 to respect the initial value (except enforcing precision, as it is useful to prevent JS quirks)
```vue
<template>
<v-app>
<v-container>
<v-card class="mx-auto pa-6 my-4" style="max-width: 900px">
<v-row>
<v-number-input v-model="model.min" label="Min" />
</v-col>
<v-number-input v-model="model.value" label="Value" :min="model.min" :max="model.max" />
</v-col> …
```
=> feat(VNumberInput): show error state when out of range

packages/vuetify/src/components/VNumberInput/VNumberInput.tsx, packages/vuetify/src/components/VNumberInput/__tests__/VNumberInput.spec.browser.tsx
Clamping initial value is not consistent in general - e.g. value can be loaded from API with a slight delay, and then it is not auto-corrected.
Component should respect the value, and only show error state (#21825)
```vue
<template>
<v-app>
<v-container>
<v-card class="mx-auto pa-6 my-4" style="max-width: 900px">
<v-row>
<v-number-input v-model="model.min" label="Min" />
</v-col>
<v-number-input v-model="model.value" label="Value" :min="model.min" :max="model.max" />
</v-col>
<v-number-input v-model="model.max" label="Max" />
</v-col>
</v-row>
<small>Note: currently only "error" state triggers when typing or changing the range</small>
<br />
<small>In v4: we will drop auto-clamp onMounted</small>
</v-card>
</v-container>
</v-app> …
```
=> feat(VNumberInput): do not clamp value on mounted

packages/docs/src/data/new-in.json, packages/vuetify/src/components/VTabs/VTabs.tsx
resolves #21969
```vue
<template>
<v-card>
<v-tabs
bg-color="teal-darken-3"
slider-color="teal-lighten-3"
show-arrows
>
<v-tab
v-for="i in 30"
:key="i"
:text="'Item ' + i"
:value="'tab-' + i"
/>
<template #prev>
<v-btn icon="$prev" rounded="lg" size="small" v-tooltip:left="'Move left'" />
</template>
<template #next>
<v-btn icon="$next" rounded="lg" size="small" v-tooltip:right="'Move right'" />
</template>
</v-tabs>
</v-card>
</v-container>
<v-container max-width="300" class="mt-12">
<v-card>
<v-tabs
bg-color="teal-darken-3"
slider-color="teal-lighten-3"
style="max-height: 450px"
show-arrows
>
<v-tab v-for="i in 30" :key="i" :text="'Item ' + i" :value="'tab-' + i"/>
<template #prev>
<v-icon-btn
class="ma-2" …
```
=> feat(VTabs): slots for prev/next

packages/docs/src/data/new-in.json, packages/docs/src/examples/v-treeview/slot-no-data.vue, packages/docs/src/pages/en/components/treeview.md, packages/vuetify/src/components/VTreeview/VTreeview.tsx
- introduces `no-data` slot along with `hide-no-data` and `no-data-text` props
> uses `VListItem` instead of `VTreeviewItem` because the latter injects `visibleIds` and hides itself. `VTreeviewItem` was also my first pick for an element inside the custom slot - it my be confusing to many devs.
- [TBD] `VTreeviewItem` might benefit from an additional `filterable` prop that could be passed down using `VDefaultsProvider`, so the same component outside of `VTreeviewChildren` would ignore `visibleIds`
resolves #21954
```vue
<template>
<v-app>
<v-container max-width="500">
<v-text-field v-model="search" prepend-inner-icon="mdi-magnify" clearable />
<v-treeview
:items="items"
open-all
>
<template #no-data>
<v-list-item :title="`There are no …
```
=> feat(VTreeview): add `no-data` slot
