- src/components/collapsible/CollapsibleHeader.vue
The introduced method `getNextSibling` will look for the next **element**-sibling (nodeType 1) and thus ignoring any text nodes.
#17
> nextSibling whitespace (fix #17)

- src/directives/click-outside.js
as discussed on gitter. the bind() method of a directive can run before the component it's in has been mounted and added to the DOM, so install the click event handler after that.
> delay adding click-outside event handler until after v-app has been mounted

- src/components/avatars/index.js
Currently computed classes get ignored on v-avatar
> Allow the use of computed classes on v-avatar

- src/stylus/components/_menus.styl
Selects have a longer bottom margin/distance compared to other inputs. Can be observed here http://codepen.io/anon/pen/gmoZEj
Left and right columns to compare, right shows this fix
> Selects have long bottom margin/distance

- src/stylus/tools/_elevations.styl
Elevation helper classes don't seem to take precedence after certain elements which have a default elevation set. The toolbar is an example. If I add `class="elevation-0"` to toolbar, it does not override the existing box-shadow: http://codepen.io/anon/pen/MpdjxB
Simple suggested fix in this PR is to make elevation helper classes important.
> make elevation helpers important

- src/stylus/components/_tabs.styl
**The problem:**
Centered tabs using `justify-content: center` has a known problem with flexbox where items will go outside their container.  
**To repeat the problem:**
1. Check out this full page codepen here: http://codepen.io/prograhammer/full/PprezM/
2. Switch to a mobile view (ie. iPhone 6) and notice the first tab gets cut off. 
**The fix:**
We can use auto margins on first and last tab, instead of `justify-content: center`. You can see the fix working in this jsFiddle: https://jsfiddle.net/s9wxL055/
> Use auto margins for centered tabs instead of justify-content.

- src/components/tables/DataTable.js
In my opinion data tables should be sorted on their first sortable column by default. Not sure if what I've done is the best way to do it though
> Sort data tables on first sortable column by default

- src/components/dialogs/Dialog.js
- src/components/overlay/index.js
- src/stylus/components/_cards.styl
- src/stylus/components/_dialogs.styl
This PR contains a few enhancements on top of what was requested in #415.
* Fullscreen now fixes toolbar to the top and will scroll.
* Added max height for non full screen dialog for scroll, even when not using scrollable
* Removed overlay body overflow removal to avoid jump
* Removed baked in ```v-card```
> Enhancement for #415

- src/components/tables/DataTable.js
- src/util/helpers.js
Right now, when setting up the headers and their corresponding values, a key of the v-model is specified. That key is only valid for plain objects.
For example, in an object like `{a: 1, b: 2, c: {d:3, e: e}}` I can only access `a` and `b`.
This PR will allow the dev to setup headers like this:
```
addressHeaders: [
{text: 'Header label', value: 'obj.nested.value'},
]
```
> add support for sorting nested properties

- package.json
`npm run dev` caused an error on my windows. Now, it works on both of windows cmd and bash.
> fix build command on windows

- src/stylus/elements/_global.styl
This resolve https://github.com/vuetifyjs/vuetify/issues/537
> Hide native icons on inputs for the Edge browser

- src/components/forms/TextField.js
Allows setting these attributes on number and date-time type inputs.
Min and max are passed through as attributes unless using a counter,
and so are used as min and max lengths for the counter instead.
> [#576] Pass through min, max, and step attributes for v-text-field

- src/components/menus/Menu.js
- src/components/menus/mixins/activator.js
- src/components/menus/mixins/generators.js
- src/components/menus/mixins/position.js
Allows one to use the menu without an activator by manually positioning it using `position-x` and `position-y` props. Example can be seen in PR to docs.
> Added positionX/Y props to menu

- src/components/buttons/ButtonToggle.vue
- test/unit/specs/ButtonToggle.spec.js
Added mandatory prop to ButtonToggle. With it activated, you are unable to deselect all buttons. At least one button will always be active.
Can be seen in the updated example https://github.com/vuetifyjs/docs/pull/82
> ButtonToggle mandatory prop

- src/components/menus/Menu.js
- src/components/menus/mixins/position.js
There are cases when the width of `activator` element of Menu component is wider than the needed width of `content` element. For example, Date picker `content` is 290px wide, but if the `activator` is wider, then by setting `min-width` style on `content`, unneeded white space appears right to the Date picker.
Here is a CodePen to show the issue - https://codepen.io/anon/pen/bReKmX. Click on the input field and see the extra white space on the right of the Date picker.
I have added a new prop for Menu element - `disableContentMinWidth`, which sets the `min-width` style of the `content` to `0` if set to `true`.
> Allow to disable min-width on content element.

- src/components/progress/ProgressLinear.vue
Allows one to set front and back colors independently on progress-linear. 
See https://github.com/vuetifyjs/docs/pull/84 for example
> Custom colors on progress-linear

- src/mixins/route-link.js
Any component that uses route-link can now take a `download` prop. It can have a value, or just be the attribute. If a value is given, and the URL is same-origin, the value will be used for the file name (can still be changed by the user). If no value is given, the file name of the file being downloaded will be used.
> Use download prop on route-link

- src/components/dialogs/Dialog.js
Fixed bug where dialog__container created empty space when not using an activator slot
> Fixed dialog bug when not using activator slot

- src/stylus/components/_toolbar.styl
"Default" toolbars are displayed in front of fixed toolbars if the toolbar is scrolled.
This PR fixes this and sets the `z-index` only for fixed toolbars.
As I had no time to test this, this PR is more like a issue with a proposed solution.
> Display fixed toolbars in front of "default" toolbars

- src/stylus/components/_tables.styl
According to the [specs](https://material.io/guidelines/components/data-tables.html#data-tables-structure)
Table content (table.table tbody td) should be 13sp Roboto Regular
Column headers (table.table thead th) should be 12sp Roboto Medium
Hover background Grey 200 (#EEEEEE)
Selected row background Grey 100 (#F5F5F5)
> Comply with the Datatable specs

- src/components/selects/mixins/generators.js
The function genTile now has an optional boolean variable for disabled items. I changed the noDataText item to be disabled. This prevents someone from clicking "No Data Available" and it returning that as the selected item. Now it merely returns an empty string. 
This would also allow in the future a public API addition that allowed disabled divider items in lists.
> Added disabled items option

- src/stylus/settings/_variables.styl
This is to fix issue #944, which will make the all the hidden-{size}-only classes work.
> Add small-only and fix all the -only display breakpoints

- src/components/tables/mixins/body.js
With this change, it's possible to use component in datatable body such as:
```
<v-data-table
v-bind:headers="headers"
v-bind:items="items"
>
<template slot="items" scope="props">
<foo-row :bar="props.item"></foo-row>
</template>
```
BTW I think it would be better if `<tr>` were required (explicit is better than implicit).
> Allow component as row in datatable

- package.json
warning babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
> fix babel warning

- src/components/toolbar/Toolbar.js
- src/mixins/overlayable.js
- src/stylus/components/_toolbar.styl
Better `<main>` section responsibility depends on toolbar state.
now css rule `padding-top` of  folowing `<main>`  take into consideration toolbar modifiers:
* toolbar-fixed
* toolbar-extended
* toolbar-dense
* toolbar-prominent
in all combinations
[old behavior](https://codepen.io/anon/pen/RgEeBy)
[new behavior](https://codepen.io/anon/pen/BZvqwO)
> Improved toolbar behavior

- src/components/subheaders/VSubheader.js
Fix by analogy with the `<v-divider>`
[VDivider.js#L17](https://github.com/vuetifyjs/vuetify/blob/16515c3ebb9734218ef3d833b6c5cc56a7cc65c7/src/components/dividers/VDivider.js#L17)
> Fix support dark theme

- src/index.js
Ensures people using the wrong version are aware, since we've seen several people with this as their problem's root cause.
> Check Vue version satisfies minimum requirements, in CDN use-case

- src/index.js
The current implementation is a bit hard-coded and implies changing the vue version in that file at every vue version change.
Also, changed the `console.error` to `console.warn` since some features would also be ok with earlier vue versions.
Don't know if it's really useful but it seems a little easier to maintain this way.
> Little change on Vue version checking for easier maintenance

- src/components/menus/VMenu.js
This will allow the components outside and inside to respond to the closing and opening
> Add activate and deactivate events

- src/util/helpers.js
For objects with a constructor like:
`var MyClass = (function () {
function MyClass(foo, bar) {
this.foo = foo;
this.bar = bar;
}
return MyClass;
}());`
Condition (`obj.constructor === Object`) fails.
> support typescript class constructor

- index.d.ts
- package.json
- src/util/helpers.d.ts
If you're writing a Vue app with TypeScript and you write `Vue.use(Vuetify)`, TypeScript throws an error because the Vuetify module hasn't been declared.
This pull request includes a tiny TypeScript definition file for the Vuetify plugin and one for the `createSimpleTransition` method as documented here: https://vuetifyjs.com/motion/transitions
I believe this covers the entire documented API surface area of Vuetify imports in a TypeScript application.
> Add TypeScript definitions for Vuetify plugin and createSimpleTransition

- build/webpack.dev.config.js
- package.json
- postcss.config.js
debug-build script is useful for debugging webpack configs.
Extracting the css without nano makes diagnosing css issues easier.
> Add new debug-build script, and add vuetify.css without nano to dev playground

- src/mixins/selectable.js
This will allow the mixin to be used within other projects without hard-coding webpack alias.
> normalize mixin import

- .eslintignore
- .gitignore
- package.json
- src/components/icons/VIcon.spec.js
- src/components/selection-controls/VCheckbox.js
- src/components/selection-controls/VCheckbox.spec.js
- src/components/tables/VDataTable.spec.js
- src/components/text-fields/VTextField.js
- src/components/text-fields/VTextField.spec.js
- src/mixins/input.js
- src/mixins/selectable.js
- src/util/testing.js
- src/util/to-have-been-warned.js
Accessibility changes to VTextField and VCheckbox.  Removed console.warn mock in favor of spy's and new expect() matchers, toHaveBeenWarned and toHaveBeenTipped, with failure on unexpected console.error and console.warn messages.  Compensating changes where console.warn was being asserted.
> Accessibility and testing changes

- src/components/tables/VDataTable.js
- src/components/tables/mixins/body.js
- src/components/tables/mixins/foot.js
- src/components/tables/mixins/head.js
> Updated data-table slots

- src/stylus/components/_overlay.styl
Hi,
The overlay menu, is a bit sluggish on low power device, I notice it's a bit better without (the barely noticeable) blur effect.
Since the 10% of blur is slightly noticeable, removing it, seems not a big loss, but on mobile (like a Nexus 5) make the animation more smooth.
I hope this little deletion will be merge.
> Remove CSS Blur

- src/components/VSelect/VSelect.vue
This small PR fixes an error occurring after the 'multiple' prop is dynamically changed and a new value is selected.
It just sets the input value to an empty array or null depending on the multiple prop value.
> v-select multiple prop toggling fix

- src/stylus/components/_progress-circular.styl
IE11 doesn't support SVG CSS Transitions and Animation, this PR provides fallback and changes the default layout of progress keeping only rotating animation
https://stackoverflow.com/questions/33812303/svg-animation-is-not-working-on-ie11
This PR makes circular indeterminate progress look like in this codepen
https://codepen.io/anon/pen/Yxaqdd
> IE11 progress circular issue

- src/stylus/components/_input-groups.styl
It still doesn't match MD specs in 100%, but at least it uses `$theme.text.disabled` color instead of `$theme.text.secondary` for disabled label/value
`$material-light.text.disabled` is defined as `rgba(#000, .38)` instead of `rgba(#000, .42)`, I didn't change it
> fixes disabled textfield colors #1472

- src/components/VMenu/VMenu.vue
- src/components/VMenu/__snapshots__/VMenu.spec.js.snap
There was a "cursor: not-allowed" for .menu--disabled, but the menu--disabled class was not added to the disabled menu
I'm only not sure if it shouldn't be "cursor: default" to be consistent with disabled buttons, text fields etc
> Add menu--disabled class for disabled v-menu

- src/stylus/components/_menus.styl
If menu activator contains readonly input then cursor is set to default instead of pointer, it's visible for example in "#3 Date pickers - In dialog and menu" - https://codepen.io/anon/pen/WEYZvx
Playground.vue
```
<template>
<v-app>
<v-menu>
<v-text-field slot="activator" label="Input" readonly></v-text-field>
<v-card><v-card-text>Hello world!</v-card-text></v-card>
</v-menu>
</v-app>
</template>
<script>
data: () => ({date:null})
}
</script>
```
> fixes cursor on readonly input in menu activator

- src/stylus/components/_selection-controls.styl
The selector on selection controls label wasn't right so pointer-events were disabled and the z-index was too low.  Fixed selector so it applies the right styles.
> Bug 0.15 - Fix labels on selection-controls to be clickable

- src/components/VForm/VForm.js
Form validation (`<v-form v-model="valid">`) is kinda useless right now: 
- It only works on immediate children, so nested components such as date pickers don't count
- `valid` only changes when every single form field has been updated, whether they require validation or not. This makes optional fields impossible without having to call `form.validate()`
- If a field is dynamically added to the form (with `v-if` or similar), it doesn't *ever* count towards validation, even if `form.validate()` is called
- If a field is dynamically removed from the form and is invalid, the form will remain in an invalid state, even if `form.reset()` or `form.validate()` is called
This PR fixes all these issues, making validation of [forms like this](https://codepen.io/anon/pen/VzRKEW?editors=1010) or …
> Make v-form validation great again

- src/mixins/validatable.js
Fixes #1626
Also happens to fix the same issue for text fields that have `validate-on-blur`
> Re-validate inputs on reset

- src/stylus/components/_input-groups.styl
- src/stylus/components/_text-fields.styl
fixes issue #1638, also makes box text field matching the MD specs
Before and after:
Solo input label (vertical align issue) - before:
Solo input label (vertical align issue) - after:
Playground.vue for screenshots:
```vue
<template>
<div id="app">
<v-app id="inspire" class="pa-4">
<v-text-field :error-messages="['Wrong icon position!']" box label="Box field"></v-text-field>
<v-text-field hint="Am I OK?" persistent-hint box label="Box field"></v-text-field>
<v-text-field solo label="Solo field"></v-text-field>
<v-text-field prepend-icon="check" label="Normal field"></v-text-field>
<v-text-field prepend-icon="check" :error-messages="['Wrong icon position!']" box label="Box field"></v-text-field>
<v-text-field prepend-icon="check" solo label="Solo field"></v-text-field>
<v-text-field …
```
> Fixes styling issues with box and solo text-fields

- src/components/VBtn/VBtn.vue
- src/components/VBtnToggle/__snapshots__/VBtnToggle.spec.js.snap
- src/mixins/button-group.js
This PR adds a `value` prop to `v-btn` that lets you store any type of data on it. This allows `v-btn-toggle` to toggle anything instead of just strings, it also fixes the bug where the button's index is returned if its value is `false`
Sample codepen: https://codepen.io/anon/pen/RZmPgx?editors=1010
Fixes #1596
> Allow any data type in button values

- src/components/VDatePicker/mixins/date-table.js
- src/components/VDatePicker/mixins/date-title.js
- src/components/VDatePicker/mixins/date-years.js
No tests for this PR as avoriaz/jsdom (?) doesn't support locale formatting for years/days (only months are displayed as "M01" instead of "January")
This PR is ready for 0.15.3 (no need to wait for month picker integration)
Before:
After:
> Fixes date picker locale formatting (fixes #1649)

- src/components/VDatePicker/VDatePicker.vue
- src/components/VDatePicker/mixins/date-header.js
- src/components/VDatePicker/mixins/date-table.js
- src/components/VDatePicker/mixins/date-title.js
- src/components/VDatePicker/mixins/date-years.js
Fix (fallback) for #1655
Date picker in firefox android:
With farsi locale:
> fallback for date formating in android firefox

- src/components/VDatePicker/mixins/date-table.js
It's already fixed in month picker PR - https://github.com/vuetifyjs/vuetify/pull/1435/files#diff-57ddfb4d0c97aefae512d6e644ca4447R52
Playground.vue
```vue
<template>
<div id="app">
<v-layout row>
<v-date-picker :key="f" v-for="f in 7"
:first-day-of-week="f - 1"
v-model="picker"
</v-layout>
</v-app>
</div></template>
<script>
data () {
return {
picker: '2017-09-11'
}
},
}
</script>
```
> date picker 's first-day-of-week props is not working properly. for :first-day-of-week="6"

- src/stylus/components/_tabs.styl
https://codepen.io/anon/pen/bobYZZ
Icons with left/right prop located in `v-tabs-content` have wrong color, probably the lines below:
```styl
.icon--left,
.icon--right
color: $material.icons.active
```
were supposed to affect only icons in `v-tabs-item`, but affected icons in `v-tabs-content` as well
> fixes icon colors in v-tabs-content

- src/components/VTextField/VTextField.vue
Fixes #1712
All tests passed with Vue 2.4.3
> [Vue 2.4.3] Cannot add property blur, object is not extensible

- src/util/helpers.js
Probably it would be better to find out why `data.on` is not extensible and change it to extensible, but i'm not sure how to approach it
**Edit:**
Changing `on: this.$listeners` to `on: { ...this.$listeners }` could do the thing, but actually maybe it's better to create extensible object only when needed, so this PR should be enough
> [vue 2.4.3] fixes #1719

- src/components/VDataTable/VDataTable.vue
customSort() receives an index set to undefined (and checks against null) then it doesn't
return items but try to sort them.
https://github.com/stephane/vuetify/blob/0912ccdd41e1efc106560a31286ecb12660796a4/src/components/VDataTable/VDataTable.vue#L100
BTW Do you think it would an improvement to rename `index` argument to `sortBy`?
> defaultPagination.sortBy isn't initialized

- src/stylus/components/_menus.styl
- src/stylus/components/_select.styl
Disabled menu has "not-allowed" cursor on activator, other disabled elements (text fields or disabled dialog) have default cursor
This PR changed not-allowed cursor to default so that it is same for all disabled elements
Example of disabled menu (left) and dialog (right)
https://codepen.io/anon/pen/RLPOQj
> fixes mouse cursor on disabled menu/select

- src/components/VTabs/VTabsContent.js
It looks like the "id" dom attribute is not used and can be removed. This solves the problem of duplicated **id**s (html document can have only 1 element with specified id) and allows to create the following code:
```html
<div>
<v-tabs dark>
<v-tabs-bar>
<v-tabs-item href="one">One</v-tabs-item>
<v-tabs-item href="two">Two</v-tabs-item>
</v-tabs-bar>
<v-tabs-items>
<v-tabs-content id="one">One</v-tabs-content>
<v-tabs-content id="two">Two</v-tabs-content>
</v-tabs>
</div>
<div>
<v-tabs dark>
<v-tabs-bar>
<v-tabs-item href="one">One</v-tabs-item>
<v-tabs-item href="two">Two</v-tabs-item>
</v-tabs-bar>
<v-tabs-items>
<v-tabs-content id="one">One</v-tabs-content>
<v-tabs-content id="two">Two</v-tabs-content>
</v-tabs>
</div>
```
Note that the **'#'** in `href` …
> removes id attribute from tab content element

- src/components/VSelect/VSelect.js
- src/components/VSelect/VSelect.spec.js
Fixes #1743 
`selectedItems` should probably be a computed property instead of data, but I don't feel like wading through that much spaghetti today.
> VSelect -  Re-evaluate selection when items changes

- src/stylus/components/_steppers.styl
https://github.com/vuetifyjs/vuetify/blob/0887f9a20e2ed9e82aa8de83c4c971df15333ce1/src/stylus/components/_steppers.styl#L181
The proper line should be:
`margin: -8px -36px -16px 36px;`
See the image from [Mobile steppers](https://material.io/guidelines/components/steppers.html#steppers-specs) section of the Material Design spec. However, it is not explicitly specified in writing.
The empty space on the right looks noticeably wasted on extra small display, making the content looks overly shrunken.
> Fixed right margin of vertical .stepper__content

- src/components/VDatePicker/VDatePicker.spec.js
I've had a couple of people ask me why their fresh copy of the dev branch is failing tests, and it's always been this one. 
@bdeo had this:
```diff
>
<div class="picker__title">
<div class="picker--date__title-year">
-       2013
+       ۱۳۹۲ ه.ش.
</div>
```
@bkpratt84 had this:
```diff
@@ -5,11 +5,11 @@
<div class="picker--date__title-year">
2013
</div>
<div class="picker--date__title-date active">
<div>
-         M05 7, Tue
+         Tue, May 7
</div>
</div>
</div>
<div class="picker__body">
<div class="picker--date__header">
@@ -23,11 +23,11 @@
</i>
</div>
</button>
<div class="picker--date__header-selector-date">
<strong>
-             2013 M05
+             May 2013
</strong>
</div>
<button type="button"
class="btn btn--icon btn--raised"
>
```
> Skip randomly failing VDatePicker test

- src/mixins/overlayable.js
- src/stylus/components/_dialogs.styl
`mousewheel` is non-standard, it should be `wheel` instead. 
In unrelated news, I've discovered that firefox is absolutely terrible and I have no idea why anyone still uses it. 
Fixes #1816
Fixes #1725
Related to #1457
> Prevent scrolling in firefox when a dialog is open

- src/components/VTabs/VTabs.js
- src/components/VTabs/VTabsItems.js
When swiping the first tab to the right:
- without `cycle` prop - nothing happens
- with `cycle` prop - will switch to the last tab
Needs docs update if merged
> adds cycle prop to v-tabs-items

- src/components/VDataTable/VDataTable.spec.js
- src/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
- src/components/VDataTable/mixins/head.js
Fixes #1548
Accepts strings and arrays:
```js
headers: [
{
align: 'left',
value: 'name',
class: 'some-class' // or ['some-class', 'other-class']
},
```
> v-data-table: adds header 'class' parameter

- package.json
- src/components/VSlider/VSlider.js
Added three new properties to v-slider component: track-color, track-fill-color and thumb-color. Works similar to the color-front property for the v-progress-linear component.
thumb-color also changes the thumb-label color to match the thumb-color.
Usage:
```
<v-slider
v-model="progress"
track-color="pink"
track-fill-color="green"
thumb-color="purple"
label="Dev Slider"
thumb-label
></v-slider>
```
> Enhancement/v-slider: Added three color props.

- src/mixins/maskable.js
fix proposal for #1910
Maybe the current code is not WET, but at least a bit humid, especially when you notice that `input.setSelectionRange()` always comes in pair with `this.selection = ...`, so this is my proposal to keep it together.
Maybe `this.selection` should be synchronized somehow with input selection, now there's a bunch of issues when changes the caret position and continues typing
> setSelectionRange refactoring

- src/stylus/components/_dialogs.styl
- src/stylus/components/_dividers.styl
Currently, on scrollable dialogs, you need to set `v-card-text`'s height for it to properly show its contents. Also, where `v-card-text`'s height is too high, it will hide `v-card-actions`. This PR will auto adjust `v-card-text`'s height based on content and it will not hide `v-card-actions`.
> Auto adjust scrollable dialog's height based on content

- src/mixins/maskable.js
Fixed the bug where the `selection()` is not called at certain situations when the caret position changes. The actual caret position will be moved to the end of input field particularly when the mask changes dynamically, and it should be re-positioned to the value of `this.selection`. However, because `this.selection` is observed (watched) as unchanged, `selection()` is not called to fix the caret position.
> Fixed the bug where the caret position is not properly watched.

- src/components/VAlert/VAlert.js
- src/components/VAlert/VAlert.spec.js
- src/components/VAlert/__snapshots__/VAlert.spec.js.snap
In 0.15 icon depended on the context (`<a-alert error>` had an `warning` icon etc), should it still depend on the color in `colorable` version? This would made transition from 0.15 to 0.16 a bit easier (just `primary` => `color="primary"` etc, no need to specify icon for every alert), but it's not semantic - color is color, not the context
I've also set the default color to `error`, so just `<v-alert>Error</v-alert>` could work.
In future versions there could be some global settings that sets the default icon for contextual colors
Docs: https://github.com/vuetifyjs/docs/pull/260
> colorable alerts

- src/components/VDatePicker/VDatePicker.js
fixes #1939
Based on https://stackoverflow.com/questions/10830357/javascript-toisostring-ignores-timezone-offset
> toISOString() ignores timezone offset

- src/components/VSelect/VSelect.js
`listIndex` is set in `$nextTick`, meanwhile menu can be removed so before setting `listIndex` we should make sure that `this.$refs.menu` exists
Fixes #1943 
Edit: #1943 is fixed in line 571 https://github.com/vuetifyjs/vuetify/pull/1958/files#diff-ebb3da5567a5b11ea831789469bcc709L571, but I've added check also in 2 more places
> check if menu exists before setting listIndex

- src/components/VList/VListTile.js
Can be seen on dev docs. The v-list holding the version select throws an error since there is no check to see if `$listeners` actually exists before trying to access `.click`. I simply reused existing isLink computed prop instead.
> fixed bug with unchecked property read

- src/components/VProgressCircular/VProgressCircular.js
Fix a case where importing VProgressCircular to declare as app local component triggers the arrow function behavior (`this` will be undefined).
> Fix VProgressCircular's error in a-la-carte import

- src/components/VTextField/VTextField.js
In some case, the input doesn't exist. For example, in http://owfhx5zzh.bkt.clouddn.com/#/, after logged in, if you refresh the page, the username with autofocus prop doesn't exisit.
Login info for http://owfhx5zzh.bkt.clouddn.com/#/
username: Mario, password: password
The error message got from console if you refresh the page:
> Uncaught TypeError: Cannot read property 'focus' of undefined
>     at s.focus (vendor.3a18aedfd787638103a2.js:6)
>     at s.n [as focus] (vendor.3a18aedfd787638103a2.js:6)
>     at vendor.3a18aedfd787638103a2.js:6
> focus @ vendor.3a18aedfd787638103a2.js:6
> n @ vendor.3a18aedfd787638103a2.js:6
> (anonymous) @ vendor.3a18aedfd787638103a2.js:6
> Make sure the input exists

- src/components/VTextField/VTextField.js
- src/mixins/maskable.js
Android stores the caret position to later restore it after the component gets rendered. This exhibits a caret bug when we internally change the input text using masks. We need to delay our caret update right after Android is done with it's restoration.
> fixes #2031

- src/stylus/components/_buttons.styl
Before
and after
with this playground
```vue
<template>
<main>
<v-content>
No theme<br>
<v-btn href="/" color="primary"><v-icon>block</v-icon>Button</v-btn>
<v-btn href="/" flat color="primary"><v-icon>block</v-icon>Button</v-btn>
<v-btn href="/"><v-icon>block</v-icon>Button</v-btn>
<v-btn href="/" flat><v-icon>block</v-icon>Button</v-btn>
Dark theme<br>
<v-btn href="/" dark color="primary"><v-icon>block</v-icon>Button</v-btn>
<v-btn href="/" dark flat color="primary"><v-icon>block</v-icon>Button</v-btn>
<v-btn href="/" dark><v-icon>block</v-icon>Button</v-btn>
<v-btn href="/" dark flat><v-icon>block</v-icon>Button</v-btn>
Light theme<br>
<v-btn href="/" light color="primary"><v-icon>block</v-icon>Button</v-btn>
<v-btn …
```
> fixes button icon colors

- src/components/VSlider/VSlider.js
It was not possible to set the max value with this codepen https://codepen.io/anon/pen/boLmqq
This PR uses `Math.round` instead of `parseInt`, so if the new value calculated in `onMouseMove` is for example 4.56 then the slider value will be set to 5, before it was set to 4
> round input value instead of floor

- src/components/VTextField/VTextField.js
- src/mixins/maskable.js
Android chrome selects the last entered character, so we should use
selectionEnd instead of selectionStart.
It also has a slight delay before deselecting the character, so a
timeout of 0 is set to ensure the correct update order.
Better than #2049
Fixes #2031
> Fix cursor position in masked inputs on android

- src/stylus/components/_chips.styl
Fixes #2086
```css
.red--text.text--darken-1 {
color: #e53935!important;
}
```
overridden chip's
```css
.chip--outline {
background: transparent!important;
}
```
because of highter specificity
PR changes `.chip--outline` to `.chip.chip--outline`
> fixes #2086

- src/stylus/components/_app.styl
- src/stylus/components/_buttons.styl
Fixes #2105 
Reverting to 0.16.1 version where links didn't have hover styles at all. This removes also hover styles from breadcrumbs (which are just links) and buttons (hence no need to override it in _buttons.styl) and navigation links
In 0.16.1 afair breadcrumbs had their own hover styles but they also didn't play well with dark theme
> removes hover styles for links and buttons

- src/components/VTooltip/VTooltip.js
Reproduction:
https://codepen.io/jayblanchard/pen/WZJvRG?editors=1010
Hover over button, click to show menu, move mouse onto menu, tooltip goes away and takes menu with it.
I can't think of a scenario where a tooltip should be responsible for closing dependent elements.  So maybe a larger question is, should VTooltip actually implement Dependent mixin at all?
> Tooltip shouldn't close dependents

- src/components/VSelect/mixins/select-generators.js
Checkboxes in disabled list-tiles are already styled differently, so there's no
reason to uncheck them too
Fixes #2113
> Check v-select checkbox even if the item is disabled

- src/components/VDataTable/mixins/head.js
This PR will allow to set the header width in % or px, for example:
```
headers: [
{ text: 'Dessert (100g serving)', value: 'name', width: '20%'},
{ text: 'Calories', value: 'calories', width: '50%' },
{ text: 'Carbs (g)', value: 'carbs', width: '200px' },
],
```
Fixes #1856
> Option to set v-data-table header width

- src/components/VSelect/VSelect.js
- src/stylus/components/_select.styl
The extra padding on input-group__selections__comma is to prevent a jump
in line height when the element is focused
- Also scroll to the end when focusing autocomplete selects that have
overflow
Fixes #1691
> fix: Hide text field in blurred autocomplete v-selects

- src/components/VSelect/VSelect.js
Fixed a bug where when trying to blur a `v-select` component it would immediately refocus when using
the Edge browser
fixes #2152
> fix: Fixed select blur in Edge

- src/directives/touch.js
Swipe event should be triggered only where there is no doubt that user
wants to swipe in the specified direction
fixes #2125
> fix: trigger swipe events only for proper swiping angle

- src/components/VTooltip/VTooltip.js
Currently there is no way to programmaticaly disable tooltip
fixes #2002
> feat: add disabled prop for tooltips

- src/components/VDatePicker/VDatePicker.js
- src/components/VDatePicker/VDatePicker.spec.js
- src/components/VDatePicker/__snapshots__/VDatePicker.spec.js.snap
- src/components/VDatePicker/mixins/date-header.js
- src/components/VDatePicker/mixins/date-table.js
- src/components/VDatePicker/mixins/date-title.js
- src/components/VDatePicker/mixins/date-years.js
- src/components/VDatePicker/mixins/month-table.js
Besides solving the problem with time zones on Chrome/OSX it also introduces few minor breaking changes:
- removes `dateFormat` and `formattedValue` props - setting `dateFormat` prop only to send a function to Vuetify, call it and get the result back doesn't make sense to me, dev can just run the formatting function by himself on the model
- all input/output values are strings, `value`, `allowedDates` etc must be strings in `YYYY-MM-DD` or `YYYY-MM` format
Fixes #2022 
Fixes #2173
> operate on strings instead of Date objects

- src/components/VSelect/__snapshots__/VSelect.spec.js.snap
- src/components/VSelect/__snapshots__/VSelect2.spec.js.snap
- src/components/VSelect/mixins/select-generators.js
This commit changes also the default colors of list tiles from teal
(checkbox) and primary/accent (text) to primary (default color of select),
so it may need a discussion
see #2174
```vue
<template>
<v-app>
<main>
<v-content>
<v-container>
<v-select v-bind:items="items" color="green lighten-2" v-model="select" label="Select" single-line item-text="state" item-value="abbr" return-object></v-select>
<v-select v-bind:items="items" color="green lighten-2" multiple v-model="select2" label="Select" single-line item-text="state" item-value="abbr" return-object></v-select>
<v-select v-bind:items="items" v-model="select" label="Select" single-line item-text="state" item-value="abbr" return-object></v-select>
<v-select v-bind:items="items" multiple v-model="select2" label="Select" single-line …
```
> feat: inherit checkbox/text color of selected item from v-select

- src/stylus/components/_tooltips.styl
Fixed a bug where when wrapping a **selection-control** component with a `v-tooltip` would cause the
tooltip to not flex the available space, causing a text overflow
fixes #2171
> fix(v-tooltip): increased flex width of tooltip

- src/components/VTextField/VTextField.js
- src/mixins/maskable.js
- src/util/mask.js
1. Resolves #2057
2. Resolves #2096
3. Resolves #2097
4. Resolves #2136 
5. Resolves #2137 
6. Resolves #2158
> Bug fixes on v-text-field

- src/components/VSlider/VSlider.js
- src/stylus/components/_sliders.styl
fixes #1914
- removes `snap` prop
- adds `ticks` prop - for displaying ticks (if `step` > 0)
- `step` - default value changed to 1, if `step` > 0 then slider value rounds to the closest possible value (same behaviour as with `snap` prop before this PR)
```vue
<template>
<v-app>
<main>
<v-content>
<v-container style="margin-bottom: 100%">
<h5>{{s0}}</h5>
<v-slider label="Defaults" v-model="s0" thumb-label></v-slider>
<h5>{{s1}}</h5>
<v-slider label="Max = 1000" v-model="s1" max="1000" thumb-label></v-slider>
<h5>{{s2}}</h5>
<v-slider label="Step = 0" step="0" v-model="s2" thumb-label></v-slider>
<h5>{{s2}}</h5>
<v-slider label="Step = null" :step="null" v-model="s2" thumb-label></v-slider>
<h5>{{s2}}</h5>
<v-slider label="Step = ''" step="" v-model="s2" thumb-label></v-slider> …
```
> feat: add support for float values in slider

- src/directives/click-outside.js
> fix: don't trigger click-outside when click() is called programmaticaly

- src/components/VSelect/VSelect.js
- src/components/VSelect/mixins/select-generators.js
With hide-selected prop items that are selected are not listed
in the menu (and there is also no need to display checkbox on
in the menu)
```vue
<template>
<main>
<v-content>
<v-container>
<p style="font-size: 2em">Click the "Open dialog" button, click the select, type "I", press TAB</p>
<v-btn @click="dialog = true">Open dialog</v-btn><v-btn @click="select = null">Clear value</v-btn>
<v-checkbox label="Hide selected" v-model="hide"></v-checkbox>
<v-dialog v-model="dialog">
<v-card>
<v-card-text>
<v-select :items="items" chips tags v-model="select1" label="chips tags" :hide-selected="hide"></v-select>
<v-select :items="items" tags v-model="select1" label="tags" :hide-selected="hide"></v-select>
<v-select :items="items" tags multiple v-model="select1" label="tags …
```
> feat: hideSelected prop for v-select

- src/components/transitions/row-expand-transition.js
Expanded row height doesn't change automaticly when content's height changes
```vue
<template>
<v-app>
<main>
<v-content>
<v-data-table v-bind:headers="headers" v-bind:items="items" v-bind:search="search" item-key="ID">
<template slot="items" slot-scope="props" no-data-text>
<td>
<v-btn dark block color="green" @click="props.expanded = !props.expanded">Expand row</v-btn>
</td>
</template>
<template slot="expand" slot-scope="props">
<v-tabs v-model="tab" dark centered>
<v-tabs-bar>
<v-tabs-item href="one">
One
</v-tabs-item>
<v-tabs-item href="two">
Two
</v-tabs-item>
</v-tabs-bar>
<v-tabs-items>
<v-tabs-content id="one">
<div style="height: 100px; background: #888" class="headline white--text">I'm 100px tall</div>
</v-tabs-content>
<v-tabs-content id="two">
<div …
```
> fix: auto height of data table expanded row

- src/components/VDataTable/VDataTable.js
- src/components/VDataTable/VDataTable.spec.js
Previously customFilter would search through the entire object passed to
items, including properties not displayed in actual table. This change
limits customFilter to only searching properties used in columns.
Fixed #1045
Docs update in https://github.com/vuetifyjs/docs/pull/312
> fix(VDataTable): customFilter function now only filters on header values

- src/directives/touch.js
fixes #2248
```vue
<template>
<v-app>
<v-navigation-drawer v-model="drawer1" temporary :touchless="touchless1"></v-navigation-drawer>
<v-navigation-drawer v-model="drawer2" temporary :touchless="touchless2" right></v-navigation-drawer>
<v-toolbar app flat>
<v-btn class="white--text" :color="touchless1 ? 'error' : 'success'" @click="touchless1 = !touchless1">{{ touchless1 ? 'OFF' : 'ON' }}</v-btn>
<v-btn class="white--text" :color="touchless2 ? 'error' : 'success'" @click="touchless2 = !touchless2">{{ touchless2 ? 'OFF' : 'ON' }}</v-btn>
</v-toolbar>
</v-app>
</template>
<script>
data: () => ({
drawer1: false,
drawer2: false,
touchless1: false,
touchless2: true
})
};
</script>
```
> fix: proper unbinding of touch events

- src/directives/ripple.js
- src/directives/ripple.spec.js
```<div v-ripple>Test</div>```  should have ripple.  Ripple reactivity fix broke this use case.
> Fix v-ripple with no expression should be enabled.

- src/components/VApp/VApp.js
- src/components/VApp/VApp.spec.js
- src/components/VApp/__snapshots__/VApp.spec.js.snap
- src/components/VGrid/VContent.js
- src/stylus/components/_app.styl
- src/stylus/components/_content.styl
- src/stylus/elements/_global.styl
0.16.9: https://codepen.io/anon/pen/NaQJbG?editors=1010
0.17 beta: https://codepen.io/anon/pen/xXvBEW?editors=1010 - This works in firefox and edge which is really weird as it's typically the other way around. 
This has been broken in IE for a while too, here's a pen with babel and 0.16.1: https://codepen.io/anon/pen/XevGwP?editors=1010
- Added a prop to set the `v-content` tag
- Reverted back to having a wrapper around `.content` due to flexbugs #3 and #11, but it's generated automatically now
- Removed height and min-height from `body, html` and added `min-height` to `.application`, with a flex row wrapper to prevent flexbugs #3
Throw whatever you can at this, I tried what I could think of and it holds up so far.
> fix(layout): fix layout regression from #2298

- src/components/VCheckbox/VCheckbox.js
- src/components/VCheckbox/VCheckbox.spec.js
- src/components/VRadioGroup/VRadio.js
- src/components/VRadioGroup/VRadio.spec.js
- src/components/VSwitch/VSwitch.spec.js
- src/mixins/rippleable.js
VSwitch has to render ripple always, currently, due to the switch knob being part of the ripple styles.
> Rippleable (VCheckbox, VRadio, VSwitch) ripple prop with tests

- src/components/VParallax/VParallax.js
- src/components/VSlider/VSlider.js
- src/stylus/components/_bottom-navs.styl
- src/stylus/components/_cards.styl
- src/stylus/components/_input-groups.styl
- src/stylus/components/_navigation-drawer.styl
- src/stylus/components/_parallax.styl
- src/stylus/components/_progress-circular.styl
- src/stylus/components/_selection-controls.styl
- src/stylus/components/_sliders.styl
- src/stylus/components/_snackbars.styl
- src/stylus/components/_switch.styl
- src/stylus/components/_tables.styl
- src/stylus/components/_text-fields.styl
- src/stylus/components/_time-picker.styl
- src/stylus/generic/_transitions.styl
The over-use of 3d transforms was causing massive memory leaks on complex pages. This PR replaces them all with 2d transforms instead. 
This is **very heavy-handed**, there are probably some cases where a new compositing layer was actually needed. If any of these *were* needed, they should be added back in with the proper methods instead - `backface-visibility` or `will-change` 
Other things that managed to sneak in:
- ~~Removed `position: relative` from `v-card`, it was also causing memory issues~~ **REVERTED**, this broke bottom-nav in cards
- Removed two redundant `pointer-events` declarations from `.input-group--selection-controls label`
The first commit is all that's really needed to fix this codepen: https://codepen.io/anon/pen/WXbjjz?editors=1000
> performance: Remove 3d transform hack (and a few other things)

- src/components/VSelect/VSelect.js
fixes #2255
```vue
<template>
<input style="border: 1px solid red; padding: 1em; width: 100%">
<v-select combobox :items="['abc', 'def']" v-model="v1"></v-select>
<v-select tags :items="['abc', 'def']" v-model="v2"></v-select>
<v-select autocomplete :items="['abc', 'def']" v-model="v3"></v-select>
<v-select autocomplete multiple :items="['abc', 'def']" v-model="v4"></v-select>
<input style="border: 1px solid red; padding: 1em; width: 100%">
</v-container>
</v-app>
</template>
<script>
data: () => ({
v1: 'test',
v2: ['abc'],
v3: 'abc',
v4: ['abc']
})
}
</script>
```
> feat: selects input value when focusing autocomplete

- src/components/VExpansionPanel/VExpansionPanel.js
If we would register component locally like this:
```js
import VExpansionPanel from 'vuetify/es5/components/VExpansionPanel/VExpansionPanel'
name: 'my-component',
components: {
'expansion-panel-with-my-name': VExpansionPanel
}
}
```
The component would be named as  'expansion-panel-with-my-name'. But $options._componentTag would be equal to 'expansion-panel-with-my-name' and toogle would not work, but $options.name will still have a name equal to 'v-expansion-panel-content' and toogle work as expected.
> fix: (VExpansionPanel) use component name instead

- src/stylus/components/_chips.styl
When the state of the element changes (normal / outline), the adjacent elements begin to shift by 2px due to the addition of border
> fix(chips): prevent changing the size of an element in outline mode

- src/components/VAlert/VAlert.js
- src/stylus/components/_alerts.styl
- src/stylus/settings/_variables.styl
The button component supports an outline display mode and users may want to display alerts this way for certain designs.
Docs PR: https://github.com/vuetifyjs/docs/pull/353
> Add outline support to Alert component

- src/components/VApp/VApp.js
- src/components/VApp/mixins/app-theme.js
- src/components/Vuetify/index.js
- src/mixins/picker.js
```vue
<template>
<v-app id="inspire" :dark="dark">
<v-content>
<v-container>
<v-checkbox label="Dark" v-model="dark"></v-checkbox>
<v-text-field label="Primary color" :value="$vuetify.theme.primary" @input="$vuetify.theme.primary = $event"></v-text-field>
<v-date-picker></v-date-picker>
</v-container>
</v-content>
</v-app>
</template>
<script>
data: () => ({
dark: false
})
}
</script>
```
> fix: picker header color in dark theme

- .env
- build/webpack.dev.config.js
- package.json
- yarn.lock
Allows the dev server host and port to be changed without messing around with environment variables
Changes to the .env file will be ignored thanks to the `prepare` script in package.json
> chore: Add .env file to hold dev server config

- src/stylus/components/_chips.styl
Fixes #2501
Also prevents images and text from darkening when chips are selected
> fix(chip): Move chip__content in front of background

- src/stylus/components/_text-fields.styl
Regression from aba924a
See #2063, #895
Fixes #2517
> fix: remove extra padding from text field hint with prepended icon

- src/components/VNavigationDrawer/VNavigationDrawer.js
Due to the Vue bug with slots forcing re-render, having
updateApplication in the render function causes buggy behaviour with
multiple drawers on the same side.
Fixes #2512
Playground.vue:
```html
<template>
<v-navigation-drawer fixed app v-model="drawer">
first
<v-navigation-drawer fixed app v-model="drawer2">
second
<v-toolbar app fixed flat>
<v-toolbar-side-icon @click="toggleDrawer"/>
<v-toolbar-title>test</v-toolbar-title>
</v-toolbar>
<v-content>
<v-card>
<v-card-text>
<v-btn @click="toggleDrawer">Toggle main</v-btn>
<v-btn @click="toggleDrawer2">Toggle 2</v-btn>
</v-card-text>
</v-card>
</v-container>
</v-content>
</v-app>
</template>
<script>
data: () => ({
drawer: false, …
```
> fix(drawer): only update layout when isActive changes

- src/components/VNavigationDrawer/VNavigationDrawer.js
- src/components/VNavigationDrawer/VNavigationDrawer.spec.js
I want to refactor this whole thing to be less messy, but this fixes it for now.
> fix(drawer): set correct content padding when temporary is toggled

- src/components/VTextField/VTextField.js
This whole function is a mess and I have no idea what's actually going on here, @azaars is going to have to take a look too. 
Fixes #2498
- What is `internalChange` for?
- What should *really* be happening when it is `true` or `false`?
- Is there a better way to determine `internalChange` that doesn't involve keypress events or anything like that?
From azaars on discord:
> Well, as far as I could remember, the internalChange is there to avoid unnecessary overhead processing in watched.value
which is more needed if the input is externally changed
> fix(text-field): update lazyValue when bound value is changed by keydown

- src/components/VDataTable/VDataTable.js
* Added a new `default-sort` prop to DataTable, which defaults to `true` (no breaking behavior)
* Use new prop to help determine the initial value for `defaultPagination.sortBy`, if any.
_Closes #2366_
> Add `disable-initial-sort` prop to VDataTable

- index.d.ts
TypeScript require ‘export default class’ when using es2015 module. It can't be 'export = class'  .
> fix: TypeScript import error

- src/components/VCard/index.js
- src/components/VDataTable/index.js
- src/components/VExpansionPanel/index.js
- src/components/VGrid/index.js
- src/components/VList/index.js
- src/components/VStepper/index.js
- src/components/VTabs/index.js
- src/components/VToolbar/index.js
When importing a-la-carte components in SFCs, the install function is
not used, which means that we were missing some components that were not
explicitly exported.
closes #2472
> fix: added missing exports

- src/components/VCarousel/VCarousel.js
- src/components/VCarousel/VCarouselItem.js
- src/mixins/registrable.js
Puts registrable methods in a namespace to avoid collisions
> refactor(registrable): namespaced methods to not collide

- src/components/VTooltip/VTooltip.js
> fix: tooltip not initially visible when v-model is true

- src/mixins/routable.js
After merging this, a few scenarios came up that have convinced me otherwise of this change. The use-case can be handled with the .native modifier, which I now believe would be the correct way to handle this. Arbitrarily stripping events feels like a bad practice.
Reverts vuetifyjs/vuetify#2487
> Revert "Fix v-btn modifier triggering twice"

- src/components/Vuetify/index.js
- src/util/colors.js
This adds about 1.7kB to the gzipped js bundle. 
Resolves #2564
UPDATE: This no longer adds colors to $vuetify, but you can import them manually from `'vuetify/es5/util/colors'`
> feat(theme): Create util file with color variables

- src/components/VRadioGroup/__snapshots__/VRadioGroup.spec.js.snap
- src/components/VSelect/__snapshots__/VSelect.spec.js.snap
- src/components/VSelect/__snapshots__/VSelect2.spec.js.snap
- src/components/VSlider/__snapshots__/VSlider.spec.js.snap
- src/components/VTextField/__snapshots__/VTextField.spec.js.snap
- src/mixins/input.js
- src/stylus/components/_input-groups.styl
- Optimized away the array and don't bother rendering the transition if no children
- Combined input-group__messages into hint and error content gen.  (Could look at getting rid of this class altogether in the future maybe)
- Consistency fix in .styl
- Snapshots updated
> Switch input group transition group to transition

- src/stylus/components/_buttons.styl
- Uses `:last-child` instead of `.icon:last-of-type` to allow non-icon elements
Fixes #1318
Playground.vue:
```html
<template>
<boilerplate>
<v-card>
<v-card-text>
<v-speed-dial
v-model="fab"
>
<v-btn
slot="activator"
fab
hover
v-model="fab"
>
<v-avatar>
</v-avatar>
</v-btn>
<v-btn
fab
dark
small
color="green"
>
<v-icon>edit</v-icon>
</v-btn>
<v-btn
fab
dark
small
color="indigo"
>
<v-icon>add</v-icon>
</v-btn>
<v-btn
fab
dark
small
color="red"
>
<v-icon>delete</v-icon>
</v-btn>
</v-speed-dial>
</v-card-text>
</v-card>
</boilerplate>
</template>
<script>
data: () => ({
fab: false
})
}
</script>
```
> fix(speed-dial): Allow any element inside the activator button

- src/components/VSelect/VSelect-autocomplete.spec.js
- src/components/VSelect/VSelect.js
Hi everyone! It's my first contribution to vuetify.
First :items passed via prop to v-select aren't cached with :cacheItems flag, but I think it's should.
You can check provided tests to better understand what I mean.
> fix(v-select) Initial items passed via prop should be cached too

- src/components/VBottomNav/VBottomNav.js
- src/components/VBottomNav/VBottomNav.spec.js
- src/components/VBottomNav/__snapshots__/VBottomNav.spec.js.snap
- src/components/VFooter/VFooter.js
- src/components/VFooter/VFooter.spec.js
- src/components/VFooter/__snapshots__/VFooter.spec.js.snap
- src/components/VGrid/VContent.js
- src/components/VNavigationDrawer/VNavigationDrawer.js
- src/components/VSystemBar/VSystemBar.js
- src/components/VSystemBar/VSystemBar.spec.js
- src/components/VToolbar/VToolbar.js
- src/components/VToolbar/VToolbar.spec.js
- src/components/Vuetify/mixins/application.js
- src/mixins/applicationable.js
- src/mixins/applicationable.spec.js
- src/stylus/components/_bottom-navs.styl
- src/stylus/components/_footer.styl
- src/stylus/components/_menus.styl
Turned applicationable into a factory function, added ability to have a `v-bottom-nav` and `v-footer`. Using the **app** prop now automatically adds **fixed** as we will not support any other behavior. Added **height** prop to `v-bottom-nav`, `v-footer`, and `v-system-bar`. Add tons of new tests. Added missing directive **scroll** in `v-toolbar`. Normalized property names in layout files. Added **inset** prop to `v-footer`. Updated style declarations to be lazy.
fixes #2679
> fix(application): abstracting applicationable functionality

- README.md
Issue: Storybook for Vue with Vuetify Material Component Framework takes some time to setup. Also new users to Vue may not understand how to wrap a layout around a component in a story (which isn't addressed in the Storybook Vue docs).
What I did
Created a boilerplate Storybook-for-Vue project using Vuetify Material Component Framework. Having something like this would have helped me get started much faster. So I'm sharing for others. Includes stories for a component with two states and a layout which wraps the component.
> add vue storybook boilerplate

- src/components/VNavigationDrawer/VNavigationDrawer.js
On `dev` branch, PR #2703 seems to have broken initial render of `<v-navigation-drawer>`.
Before the PR, if `v-model` is set to null, it would automatically expand the navigation drawer on desktop.
After the PR, if `v-model` is set to null, it internally sets `this.isActive` in `.init()`, but it never removes the `transform` property, leading to an "invisible" navigation drawer. The body (highlighted yellow) has been shifted as if the drawer was there, but the drawer is still transformed out of the viewport (its initial render state).
After some _experimenting_ with the [dark application layout example](https://github.com/vuetifyjs/docs/blob/dev/examples/layouts/dark.vue), it seems the change in behavior was due to the [lazy styling introduced in …
> fix(v-navigation-drawer): revert lazy styles

- index.d.ts
Adds more definitions to Vuetify definitions file that would allow using $vuetify property in Vue instances.
Resolves #2723
> Enhancement/ Typescript module augumentation

- src/mixins/menuable.js
If `$refs.content` is removed between `sneakPeek` being called and the animation frame fires, it becomes undefined in the callback.
Then it results with a `Uncaught TypeError: Cannot read property 'style' of undefined`
This fix ensure that $refs.content exists.
===
Thanks Kael for the help to debug it :-)
> fix(menuable): Enforce the check that $refs.content exist in sneakPeek

- src/components/VPagination/VPagination.js
This PR fixes #2707 by changing the pagination items to use their array index as `key` instead of their string value.
Managed to find reproduction steps and cause of bug on `1.0.0-alpha1`. The bug was introduced in #2630 ([line diff](https://github.com/vuetifyjs/vuetify/pull/2630/commits/c80d13fff56a658d059a6126faf06339f3958651#diff-79ad00af4d60169a3e20640b9456f6bcR149)). The bug occurs when the `<v-pagination>` has a length larger than what it can fit on-screen. When you scroll to the right, there are 2 `...`, one at the beginning and one at the end, and using them as keys causes the duplicate key error.
* It starts off fine: `[1] [2] [3] [4] [...] [97] [98] [99] [100]`.
* But when scrolling right: `[1] [...] [49] [50] [51] [52] [...] [100]`.
Normally I wouldn't use array indexes as …
> fix(v-pagination): change keys to use array index

- src/stylus/components/_text-fields.styl
This only fixes the css for text-fields for bug https://github.com/vuetifyjs/vuetify/issues/2239. Is it more appropriate to add these code to individual component css or make a global declaration for .input-group__details and .input-group__input.
```
.input-group__details, .input-group__input
user-select: none
```
> avoid activation of text selection controls in mobile Firefox

- src/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
- src/components/VDataTable/VDataTable.js
- src/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
- src/components/VDataTable/mixins/foot.js
- src/mixins/data-iterable.js
- src/stylus/components/_data-iterator.styl
- src/stylus/components/_data-table.styl
- src/stylus/components/_tables.styl
Fixes #2161 
Pull actions into its own div, outside of the table overflow, accounting for footer slot, heights and borders, make pagination controls wrap nicely on mobile
> Pagination separation

- src/components/VTooltip/VTooltip.js
- src/mixins/detachable.js
fix: Added a deactivated Life cycle hook that will simple set isActive to false when the element is deactivated
fixes #2480
> fix(detachable): Hide when deactivated

- src/components/VSelect/mixins/select-watchers.js
- src/mixins/menuable.js
- src/stylus/components/_menus.styl
fixes #2269
The menu transition was added in 7cff47738badc512452a4eaa1974c7512488dfca without any explanation, I had to remove it so the v-select menu doesn't animate its position while you're typing. 
Playground.vue:
```html
<template>
<v-app>
<v-content>
<v-container fill-height align-end style="padding-bottom: 150px">
<v-select autocomplete v-model="select" :items="items"/>
<v-menu>
<v-btn slot="activator">menu</v-btn>
<v-list>
<v-list-tile v-for="item in items" @click :key="item">
<v-list-tile-title>
{{ item }}
</v-list-tile-title>
</v-list-tile>
</v-list>
</v-menu>
</v-container>
</v-content>
</v-app>
</template>
<script>
data: () => ({
select: null,
items: ['foo', 'bar', 'baz', 'lorem', 'ipsunm', 'dolor', 'sit', 'amet']
})
}
</script>
<style lang="stylus"> …
```
> fix(VSelect): refresh menu position when filteredItems changes

- src/stylus/components/_tabs.styl
- src/stylus/settings/_variables.styl
In `stylus/settings/_variables.styl`a new variable `$tab-text-transform` can be set to configure whether to use or not to use text-capitalization in `v-tab-items`.
fixes #2857
> [Feature Request] #2857 introduce new stylus variable $tab-text-transform and use it in tab

- src/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
- src/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
- src/mixins/routable.js
Disables ripple effect on disabled routable
This change solves the problem of applying ripple effect on disabled routables
Manually + snapshots
```vue
<v-tabs centered>
<v-tab to="/page1" disabled>a</v-tab>
</v-tabs> 
```
> fix: do not apply ripple on disabled routable

- package-lock.json
- package.json
- src/components/VProgressLinear/__snapshots__/VProgressLinear.spec.js.snap
- src/components/VRadioGroup/__snapshots__/VRadioGroup.spec.js.snap
- src/components/VSelect/__snapshots__/VSelect.spec.js.snap
- src/components/VSelect/__snapshots__/VSelect2.spec.js.snap
- src/components/VSlider/__snapshots__/VSlider.spec.js.snap
- src/components/VTabs/__snapshots__/VTabs.spec.js.snap
- src/components/VTextField/__snapshots__/VTextField.spec.js.snap
- yarn.lock
This PR updates the https://github.com/rayrutjes/jest-serializer-html to v5.0.0.
This new version strips out HTML comments making the Jest snapshots even cleaner.
> chore: removes HTML comments from jest snapshots

- src/components/VSpeedDial/VSpeedDial.js
- src/components/VSpeedDial/VSpeedDial.spec.js
Renamed prop `hover` to `open-on-hover` . Done to match similar prop in v-menu
API consistency
Tests updated and run
N/A
> fix(v-speed-dial): renamed hover prop to open-on-hover

- src/components/VIcon/VIcon.js
- src/components/VIcon/VIcon.spec.js
Font Awesome 5 introduces new type of icons, like regular, light, brands and logos. When using these icons, each prefix name is different. For example, when using `facebook` icon, the class name should be `fab fa-facebook` instead of `fa fa-facebook`.
Currently, when using font awesome 5 icons and the icon is not solid type(solid is default type, prefix with `fa`), the icon class name is incorrect. This pull request add the function that support font awesome 5 icons.
Icon class name comparison:
| icon | before | after |
|-----|---------|---------|
| fa-check | fa icon fa-check| fa icon fa-check |
| far-check | far icon far-check | far icon fa-check |
| fab-facebook | fab icon fab-facebook | fab icon fa-facebook |
> support font awesome 5 icons

- src/stylus/components/_select.styl
Change css class so that the input is not hidden when deleting a chip, resulting in loss of focus to the input.
fixes #2791
Tested in Playground
> fixes #2791, VSelect input loses focus after chip is removed

- src/components/VAlert/VAlert.js
- src/components/VAvatar/VAvatar.js
- src/components/VChip/VChip.js
- src/components/VIcon/VIcon.js
- src/components/VPicker/VPicker.js
- src/components/VSlider/VSlider.js
- src/components/VTimePicker/VTimePickerClock.js
- src/mixins/colorable.js
Changes the way of passing color to colorable mixin
Currently the colorable mixin takes the name of the prop/computed
to get the color. This is not enough if the color is more dynamic,
for example planned events in date picker PR (#2946) could potentially use
different colors for different event and this needs the actual color to
be passed instead of the prop name
jest
n/a
> enhancement: changes the way of passing color to colorable mixin

- src/components/VDatePicker/VDatePickerDateTable.js
- src/components/VDatePicker/VDatePickerMonthTable.js
- src/components/VDatePicker/__snapshots__/VDatePicker.date.spec.js.snap
- src/components/VDatePicker/__snapshots__/VDatePicker.month.spec.js.snap
- src/components/VDatePicker/__snapshots__/VDatePickerDateTable.spec.js.snap
- src/components/VDatePicker/__snapshots__/VDatePickerMonthTable.spec.js.snap
- src/components/VPicker/VPicker.js
- src/stylus/components/_buttons.styl
- src/stylus/components/_date-picker-title.styl
- src/stylus/components/_pickers.styl
- src/stylus/components/_time-picker-title.styl
- removed unused class string from button generation
- adjusted content tag to match what is output by `v-btn` normally
- added conditional for class generation type, **outline** uses
**addTextColorClasses** normally within `v-btn`
- fixed bug where on some browsers the text inside of the generated button would not be vertically center
The `v-date-picker` had incorrect styles for the currently active day. This component generates a mock `v-btn` and was not using logic that normally would change the classes added by the **colorable** mixin.  This lead me to the incorrect html tag for the **.btn__content** class. Fixed a bug caused by my merge conflict resolution where **this.current** was not being passed to `v-date-picker-date-table`. There was a weird bug caused by recent changes where …
> fix(v-date-picker): adjusted styles and markup

- src/stylus/components/_navigation-drawer.styl
A v-navigation-drawer with the app param causes Safari to repeatedly
invalidate and recalculate the layout, permanently consuming a CPU
core.
This is a bug in Safari (fixed in current tech preview) which is
triggered by the combination of using calc in the max-height,
transition-property including max-height and the element being created
using document.createElement (as vue does).
fixes #2773
Explicitly list a wide range of CSS properties in transition-property for navigation drawers but exclude max-height to avoid triggering a bug in Safari.
https://github.com/vuetifyjs/vuetify/issues/2773
Note this bug only applies to the dev branch.
No new tests - can only verify fix works by checking activity monitor and the Timeline tab in Safari dev tools to confirm the layout is no longer …
> fix: Avoid high CPU usage in Safari

- src/components/VMenu/VMenu.spec.js
- src/components/VMenu/__snapshots__/VMenu.spec.js.snap
- src/mixins/menuable.js
There is sometimes a pixel gap between a menu dropdown and the menu dropdown's scrollbar, as well as an occasional pixel of background bleed-through on the right side of the scrollbar.  This is caused by fractional pixel values.
This rounds the bounded client rect values to their nearest pixel integer for use in calculating menu position and width.  Math.round was chosen based on research that seems to indicate that browsers render sub-pixel values at the nearest pixel.  Math.round also seems to be the fastest alternative for rounding:  https://jsperf.com/math-round-vs-hack/5
New test added as well as playground
```
<template>
<Boilerplate>
<v-flex xs6>
<v-subheader>Standard</v-subheader>
</v-flex>
<v-flex xs6>
<v-select
v-bind:items="items" …
```
> Fix for pixel gap between and after menu and scrollbar

- src/components/VDataTable/VDataTable.spec.js
- src/components/VDataTable/mixins/head.js
- src/mixins/data-iterable.js
The property 'all' in 'mixins/data-iterable.js' seems to be a duplicate of 'everyItem' This PR replaces the occurrences of 'all' with 'everyItem' because VDataTable is the only component affected.
Although this is a bug fix, this PR is submitted to 'dev' as VDataTable has already been split up here to 'data-iterable' mixin.
See bug for VDataTable [#2841](https://github.com/vuetifyjs/vuetify/issues/2841).
No new tests - searched project for occurrences of data-iterable and 'all'
> #2841 remove occurences of "all" property in data-iterable mixin

- src/components/VForm/VForm.spec.js
- src/components/VTextField/VTextField.js
- src/components/VTextField/VTextField.spec.js
- src/components/VTextField/__snapshots__/VTextField.spec.js.snap
- src/stylus/components/_text-fields.styl
Add the `resize: none` css attribute when a multiline input is `auto-grow`, or by manual `no-resize` attribute.
Also refactor all of the places that depend on the type of domnode to use a single `isTextarea` computed.
Also extract `row-height` as an attribute.
Also add validators to `row-height` and `rows` attributes.
Manually resizing auto-grow inputs was undefined behavior and a bug.
Also visually removes the resize handle.
Added snapshot and unit tests.
Manual testing.
```vue
<template>
<v-app>
<v-content>
<v-layout flex>
<v-card>
<v-text-field v-model='model' auto-grow multi-line rows='1'>
</v-text-field>
</v-card>
</v-layout>
</v-content>
</v-app>
</template>
<script>
data: () => ({
model: null
})
}
</script>
```
> feat(v-text-field) Add noResize prop

- src/components/VExpansionPanel/VExpansionPanel.js
- src/components/VExpansionPanel/VExpansionPanelContent.js
- src/components/VExpansionPanel/VExpansionPanelContent.spec.js
- src/mixins/registrable.js
expansion-panel only looked for expansion-panel-content in direct children.
moved to use registrable mixin instead.
fixes #2617
using markup from issue, and making sure tests pass
https://codepen.io/anon/pen/RjydZy
> fix: expansion-panel can't find nested content

- src/stylus/components/_pickers.styl
manually
`<v-date-picker></v-date-picker>`
> fix (v-date-picker): picker body doesnt't show in IE11

- build/babel-transform-stylus-paths.js
In `es5/index.js` the path to stylus is wrong
```js
require('./stylus/app.styl');  // should be ../src/stylus/app.styl
```
This patch fixes it.
> Fixed stylus path for es5/index.js

- src/stylus/components/_icons.styl
Icons in IE11 when Compatibility View is enabled don't display. This has something to do with the way IE is handling font ligatures. While `<meta http-equiv="x-ua-compatible" content="ie=edge">` does force the browser to render IE without Compatibility View, for whatever reason font ligatures are still broken. 
Fixes #3020
No new automated tests.
Tested in IE11 with Compatibility View enabled for `localhost`.
> fix: icons now show in IE11 when Compatibility View is enabled

- src/stylus/components/_steppers.styl
stepper specific btn margins were bleeding into other components.
limited it to direct children of stepper__content
closes #3094
checked manually in provided markup
```
<v-stepper v-model="e1">
<v-stepper-step step="1" :complete="e1 > 1">Name of step 1</v-stepper-step>
</v-stepper-header>
<v-stepper-items>
<v-stepper-content step="1">
<v-layout>
<v-flex xs12>
<v-date-picker :first-day-of-week="1" locale="fr-fr" v-model="picker"></v-date-picker>
</v-flex>
</v-layout>
<v-btn color="primary" @click.native="e1 = 2">Continue</v-btn>
<v-btn flat>Cancel</v-btn>
</v-stepper-content>
</v-stepper-items>
</v-stepper>
```
> fix: stepper style bleed

- src/components/VDataTable/VDataTable.js
- src/components/VDataTable/VDataTable.spec.js
- src/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
- src/components/VDataTable/mixins/body.js
- src/components/VDataTable/mixins/foot.js
- src/components/VDataTable/mixins/head.js
make sure to generate tr/td for no-data slot when needed
closes #3088
created test. tested manually
```
<v-data-table
:items="items"
>
<template slot="no-data">
<v-alert :value="true" color="error" icon="warning">
Sorry, nothing to display here :(
</v-alert>
</template>
```
> fix: generate row in data-table no-data slot

- src/components/VDialog/VDialog.js
dialog activator should not propagate click event
closes #2942
was unable to create test, tested manually with markup
```
<v-layout @click="alert">
<v-dialog>
<v-btn slot="activator">Open Dialog</v-btn>
</v-dialog>
</v-layout>
```
> fix: stopped dialog activator event propagation

- src/components/VTimePicker/VTimePicker.js
- src/components/VTimePicker/VTimePicker.spec.js
- src/components/VTimePicker/VTimePickerClock.js
- src/components/VTimePicker/VTimePickerTitle.js
- src/components/VTimePicker/VTimePickerTitle.spec.js
- src/stylus/components/_time-picker-clock.styl
- src/stylus/settings/_theme.styl
Null value doesn't set the picker internals to the current time anymore
fixes #2616
jest, manually
```vue
<template>
<v-app id="app">
<v-content>
<v-layout>
<v-flex xs6>
<v-dialog ref="dialog" full-width v-model="modal" lazy width="330px" :return-value.sync="time">
<v-text-field clearable readonly slot="activator" :value="displayTime" @input="time = null"></v-text-field>
<v-time-picker v-model="time">
<v-btn flat @click="modal = false">Cancel</v-btn>
<v-btn flat @click="$refs.dialog.save(time)">Save</v-btn>
</v-time-picker>
</v-dialog>
</v-flex>
<v-flex xs6>
<v-time-picker v-model="time"></v-time-picker>
</v-flex>
</v-layout>
</v-container>
</v-content>
</v-app>
</template>
<script>
data: () => ({
modal: false,
time: …
```
> fix (v-time-picker): allow null value

- src/stylus/components/_selection-controls.styl
- src/stylus/components/_switch.styl
fixes #2418
```vue
<template>
<v-content>
<v-subheader>append &amp; prepend icon</v-subheader>
<v-checkbox v-model="light" prepend-icon="lightbulb_outline" append-icon="lightbulb_outline"></v-checkbox>
<v-checkbox label="test" v-model="light" prepend-icon="lightbulb_outline" append-icon="lightbulb_outline"></v-checkbox>
<v-subheader>prepend icon</v-subheader>
<v-switch v-model="light" prepend-icon="lightbulb_outline"></v-switch>
<v-checkbox v-model="light" prepend-icon="lightbulb_outline"></v-checkbox>
<v-switch label="test" v-model="light" prepend-icon="lightbulb_outline"></v-switch>
<v-checkbox label="test" v-model="light" prepend-icon="lightbulb_outline"></v-checkbox>
<v-subheader>append icon</v-subheader>
<v-switch v-model="light" …
```
> fix: append/prepend icon position for switch and checkbox

- src/stylus/settings/_elevations.styl
Changed the `=` operator to `:=` for all variables in [_elevations.styl](https://github.com/vuetifyjs/vuetify/blob/master/src/stylus/settings/_elevations.styl).
It’s currently not possible to change `box-shadow` variations across the framework via Stylus, and a developer has to work around it with CSS.
Manually: I declared the variables before the imported [main.styl](https://github.com/vuetifyjs/vuetify/blob/master/src/stylus/main.styl) to make sure that the default ones can be overridden.
> fix: allow to override the elevation’s Stylus variables

- src/components/VSelect/VSelect-tags.spec.js
- src/components/VSelect/mixins/select-computed.js
- src/components/VSelect/mixins/select-events.js
- src/components/VSelect/mixins/select-generators.js
- src/stylus/components/_select.styl
when selecting with left and right, should always hide and remove input from updating the
searchValue
fixes #3069
jest
```vue
<template>
<div id="app">
<v-flex xs12 sm6>
<v-subheader v-text="'Slots'"></v-subheader>
</v-flex>
<v-flex xs12 sm6>
<v-select
label="Select"
v-bind:items="people"
v-model="e11"
item-text="name"
multiple
tags
chips
deletable-chips
max-height="auto"
autocomplete
>
<template slot="item" slot-scope="data">
<template v-if="typeof data.item !== 'object'">
<v-list-tile-content v-text="data.item"></v-list-tile-content>
</template>
<template v-else>
<v-list-tile-avatar>
</v-list-tile-avatar>
<v-list-tile-title v-html="data.item.name"></v-list-tile-title> …
```
> fix(v-select): fixed select keyboard functionality

- src/components/VSelect/VSelect-autocomplete.spec.js
- src/components/VSelect/VSelect.js
- src/components/VSelect/mixins/select-computed.js
- src/components/VSelect/mixins/select-props.js
- src/components/VSelect/mixins/select-watchers.js
this was added early on in the framework. Just as Vue removed this from the framework, this should
be handled by the developer
resolves #2978
n/a
n/a
> feat(v-select): removed debounce prop

- src/components/VCarousel/VCarousel.js
- src/components/VCarousel/VCarousel.spec.js
- src/components/VCarousel/__snapshots__/VCarousel.spec.js.snap
- src/components/VDatePicker/VDatePicker.date.spec.js
- src/components/VDatePicker/VDatePicker.js
- src/components/VDatePicker/VDatePicker.month.spec.js
- src/components/VDatePicker/VDatePickerHeader.js
- src/components/VDatePicker/VDatePickerHeader.spec.js
- src/components/VExpansionPanel/VExpansionPanelContent.js
- src/components/VExpansionPanel/VExpansionPanelContent.spec.js
- src/components/VTabs/VTabs.js
- src/components/VTabs/VTabs.spec.js
- src/components/VTabs/mixins/tabs-generators.js
- src/components/VTabs/mixins/tabs-props.js
- src/components/VTabs/mixins/tabs-touch.js
- src/components/VTabs/mixins/tabs-watchers.js
- src/mixins/data-iterable.js
- src/stylus/components/_tabs.styl
- `v-carousel`: renamed **append-icon** and **prepend-icon** props to **next-icon** and **prev-icon**
- `v-date-picker`: renamed **append-icon** and **prepend-icon** props to **next-icon** and **prev-icon**
- `v-tabs`: renamed **append-icon** and **prepend-icon** props to **next-icon** and **prev-icon**
- `data-iterable` (affects `v-data-table` and `v-data-iterator`): added **next-icon** and **prev-icon** props
- `v-expansion-panel-content`: added **expand-icon** prop
Unification of prop names and making their names matching their semantics
jest, docs
docs for carousel, tabs, picker, pagination
https://github.com/vuetifyjs/vuetifyjs.com/pull/253
> prev/next-icon & expand-icon props

- src/components/VDatePicker/VDatePicker.js
- src/components/VDatePicker/VDatePickerTitle.js
- src/components/VDatePicker/VDatePickerTitle.spec.js
was comparing the formatted string value of `date` when determining the transition direction.
updated to use the iso value
incorrect transition when changing dates
jest/visually
```vue
<template>
<v-app id="app" dark>
<v-content>
<v-layout>
<v-flex xs4>
<v-dialog ref="dialog" full-width v-model="modal" lazy width="330px">
<v-text-field label="Date" readonly slot="activator" v-model="date" clearable></v-text-field>
<v-date-picker v-model="date" @input="modal = false"></v-date-picker>
</v-dialog>
</v-flex>
<v-flex xs4>
<div class="headline">reactive: true</div>
<v-date-picker reactive v-model="date"></v-date-picker>
</v-flex>
<v-flex xs4>
<div class="headline">reactive: false</div>
<v-date-picker v-model="date"></v-date-picker>
</v-flex>
</v-layout>
</v-container> …
```
> fix(v-date-picker-title): fixed improper comparison for transition

- src/components/VDataTable/mixins/head.js
Adds the ability to set as a prop the v-icon for data table sort. 
`
<v-data-table  sort-icon="arrow_drop_down" .../>
`
- Added property "sortIcon"
- use this.sortIcon in genHeaderSortingData
There is currently no way to override the default icon for sort in Data Tables
Ran locally, testing in company storybook
> paramaterize sort icon

- src/components/VSnackbar/VSnackbar.js
- src/stylus/components/_snackbars.styl
- src/stylus/settings/_variables.styl
- add `auto-height` prop, similar to #3149
- use auto width instead of locking it to 50% of the viewport
- hide top snackbars a bit more to prevent the shadow from flashing
- increase margins on >xs to match material spec
- add 100ms delay to fade part of transition
- messed with button dimensions a bit, particularly on vertical snackbars. still not sure about this one
fixes #2970
replaces #3149 
testing is for chumps
```html
<template>
<v-app>
<v-content>
<v-container>
<v-btn @click="snack = !snack">show</v-btn>
<v-slider v-model="length" :label="'' + length" max="30"></v-slider>
<v-checkbox label="second button" v-model="second"></v-checkbox>
<v-checkbox label="vertical" v-model="vertical"></v-checkbox>
<v-checkbox label="multi-line" v-model="multiline"></v-checkbox>
<v-checkbox …
```
> Fix snackbar width on sm, add auto-height prop

- src/components/VDatePicker/__snapshots__/VDatePicker.date.spec.js.snap
- src/components/VDatePicker/__snapshots__/VDatePicker.month.spec.js.snap
- src/components/VPicker/VPicker.js
- src/components/VPicker/__snapshots__/VPicker.spec.js.snap
- src/components/VTimePicker/__snapshots__/VTimePicker.spec.js.snap
- src/mixins/picker.js
- src/stylus/components/_date-picker-table.styl
Change default picker width from 330px to 290px (like it was in 0.17)
It's a breaking change comparing to previous beta, but not comparing to 0.17 branch
330px width was a breaking change that also made pickers cropped in new docs
https://github.com/vuetifyjs/vuetifyjs.com/pull/261
> fix (v-picker): reverted default width to 290px

- src/components/VSnackbar/VSnackbar.js
- src/components/VSnackbar/VSnackbar.spec.js
This PR fixes the color prop for `v-select`.
Due to https://github.com/vuetifyjs/vuetify/pull/3155, the color was applied to the wrong DOM element.
Fixes https://github.com/vuetifyjs/vuetify/issues/3199
> Fix v-snackbar color prop

- src/components/VDataTable/VEditDialog.js
Adds **persistent** prop to `v-edit-dialog`
fixes #3195
docs
`<v-edit-dialog persistent>...</v-edit-dialog>`
https://github.com/vuetifyjs/vuetifyjs.com/pull/267
> feat: **persistent** prop for v-edit-dialog

- src/components/VTabs/VTab.js
was evaluating before the route change was actually resolved
fixes #3203
visually
```vue
<template lang="pug">
v-app#app
v-container
v-card
v-card-title
.title.indigo--text v-tabs with v-model
v-divider
v-card-text.hide-overflow
p The problem is that in Beta.6 clicking on a tab with a <code>:to</code> attribute delays the change of tab contents, that is, it is lagging. Follow the instructions in Tab 1 contents, below.
p This used to work as expected in Beta.5
pre.blue.white--text.pa-2: b active_tab: {{ active_tab }}
v-tabs(
v-model="active_tab",
slider-color="blue lighten-2",
)
v-tab(:to="{ path:'/page1' }") One
v-tab(:to="{ path:'/page2' }") Two
v-tab(:to="{ path:'/page3' }") Three
v-card(v-if="active_tab=='/page1'", key="1")
v-card-text
h1 Tab 1 contents
li Click on tab TWO and notice …
```
> fix(v-tab): added back removed nextTick

- src/mixins/detachable.js
fixes #3226 
```html
<template>
<v-app>
<v-content>
<my-component/>
</v-content>
</v-app>
</template>
<script>
components: {
'my-component': {
data: function () {
return {
showTooltip: false
}
},
template: `
<v-layout id="test">
<v-tooltip v-if="showTooltip" lazy :attach="$el">
<span slot="activator">This text has a tooltip</span>
<slot>
<span>Tooltip</span>
</slot>
</v-tooltip>
</v-layout>
`,
mounted () {
this.showTooltip = true
}
}
}
}
</script>
```
> fix(detachable): allow any object in the attach prop

- src/components/VSelect/VSelect-tags.spec.js
- src/components/VSelect/mixins/select-autocomplete.js
- also resets the menu index afterwards for more consistent behaviour
Since 0.17, it hasn't been possible to add a *new* tag with the tab key if there is a search match. This change was made in e6993e5aac5ec4bd417841365e416d54778a1b0d judging by the test changes. 
```html
<template>
<v-app>
<v-content>
<v-container>
<v-select chips tags v-model="tags" :items="['foo', 'bar', 'baz', 'Programming']"/>
<v-select combobox :items="['foo', 'bar', 'baz', 'Programming']" v-model="combo"/>
</v-container>
</v-content>
</v-app>
</template>
<script>
data: () => ({
tags: [],
combo: ''
})
}
</script>
```
- type `pro`
- press tab
- `pro` should be added as a tag, but instead nothing happens
> fix(VSelect): add tags with tab when the menu is open

- src/components/VFooter/VFooter.js
- src/mixins/applicationable.js
`this.$el` is undefined when `updateApplication` is called in `created`, causing an error. 
Apparently also fixes #3274 and fixes #3280 
```html
<template>
<v-app>
<v-content>
<v-container>
<v-card height="2000">
card
</v-card>
</v-container>
</v-content>
<v-footer app inset height="auto">
footer
</v-footer>
</v-app>
</template>
```
> fix(VFooter): update application after mount when using auto height

- build/config.js
- build/webpack.base.config.js
- build/webpack.dev.config.js
- build/webpack.prod.config.js
- src/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
- src/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
- src/components/VSelect/__snapshots__/VSelect.spec.js.snap
- src/components/VSelect/__snapshots__/VSelect2.spec.js.snap
- src/components/Vuetify/index.js
- src/index.js
- ~~**BREAKING CHANGE:** must `Vue.use(Vuetify)` when using CDN package~~
- ~~You can now set the theme easily when using a CDN~~
- No longer includes the entire package.json in the dist
- Vue version is checked in the Vuetify component, now works with a-la-carte too
- $vuetify is a proper vue instance instead of the hacky defineReactive
- Vuetify.version is now available to CDN users
- Replaced semver with a basic custom function, reduces gzipped size from 62KB to 56KB
- vuetify dev environment with Playground.vue
- vuetifyjs.com repo
- ~~basic html file with markup from below~~
```html
<link rel="stylesheet" href="../dist/vuetify.min.css">
<script src="https://unpkg.com/vue"></script>
<script src="../dist/vuetify.min.js"></script>
<div id="app">
<v-app>
<v-content>
<v-text-field …
```
> refactor: improve install function

- src/components/VList/VListTileAvatar.js
restores `tile` prop removed in #2554
fixes #3117
playground
```vue
<template>
<v-content>
<v-checkbox v-model="tile" label="Tile"></v-checkbox>
<v-list>
<v-list-tile avatar>
<v-list-tile-avatar :tile="tile">
</v-list-tile-avatar>
</v-list-tile>
</v-list>
</v-content>
</v-app>
</template>
<script>
data () {
return {
tile: true
}
}
}
</script>
```
> fix (v-list-tile-avatar); restores removed tile prop

- src/stylus/elements/_typography.styl
- src/stylus/settings/_variables.styl
- Follow existing method used for `$badge-font-family`
- Headers default to `$body-font-family`
- Defined in `_variables.styl`, not `theme.styl`
- Sets the font for:
- classes: `.display-4`, `.display-3`, `.display-2`, `.display-1`, `.headline`, `.title`
Add the ability to set a different font for headings.
It is common for web applications to use a separate font for headings and body copy.  Currently, there is no standard way to do that in Vuetify.
I raised the question in Discord and suggested iusing `$heading-font-family` similar to how `$badge-font-family` is used. @johnleider said to submit a PR.
Tested via `Playground.vue`
I didn't see any existing tests related to stylus variables.
```vue
$body-font-family = 'Open Sans'
$heading-font-family = 'Roboto'
@import …
```
> feat: Set header font via `$header-font-family`

- src/mixins/data-iterable.js
Pagination should reset when changing sortBy.
There is very little correlation between page 5 of sorting on X and sorting on Y.
Quick test in playground
N/A
> fix: reset page to 1 when sorting changes

- src/components/VApp/mixins/app-theme.js
> fix(theme): only apply theme to head element when not using vue-meta

- src/components/VTabs/VTabs.js
- test/unit/components/VTabs/VTabs.spec.js
- test/unit/components/VTabs/__snapshots__/VTabs.spec.js.snap
bde89441229b2240de8fe5c8ab59e78480d16d0c was supposed to fix this, but I forgot to account for non-components (any vnode without `componentOptions`)
fixes #3434
> fix(tabs): render all other elements in the tabs container

- src/stylus/components/_chips.styl
`.chip.chip--outline { background }` was overridden by `.primary.darken-1 { background-color }` due to declaration order. 
fixes #3374
```html
<template>
<v-app>
<v-content>
<v-chip outline color="blue">blue</v-chip>
<v-chip outline text-color="green">green</v-chip>
<v-chip outline color="blue" text-color="green">blue + green</v-chip>
<br>
<v-chip outline color="primary darken-1">primary</v-chip>
<v-chip outline text-color="secondary darken-1">secondary</v-chip>
<v-chip outline color="primary darken-1" text-color="secondary darken-1">primary + secondary</v-chip>
<br>
<v-chip outline color="primary">primary Border</v-chip>
<v-chip outline color="primary lighten-4">primary Border lighten-4</v-chip>
<v-chip outline color="primary darken-4">primary Border darken-4</v-chip>
<br>
<v-chip …
```
> fix: increase specificity of outline chips to override theme background

- src/components/VApp/mixins/app-theme.js
Setting `$options.metaInfo` causes a race condition on the client-side. I didn't notice this with #3440 because I only tested it with SSR. 
fixes #3482
Tested with playground (below) and a vuetifyjs/nuxt project
index.html:
```html
<script src="https://unpkg.com/vue-meta"></script>
```
index.js:
```js
Vue.use(VueMeta)
```
Playground:
```html
<template>
<v-app>
<v-content>
<v-container fluid fill-height>
<v-layout align-center justify-center>
<v-flex xs12 sm8 md4>
<v-card class="elevation-12">
<v-toolbar dark color="primary">
<v-toolbar-title>Login form</v-toolbar-title>
</v-toolbar>
<v-card-text>
<v-form>
<v-text-field prepend-icon="person" name="login" label="Login" type="text"></v-text-field>
<v-text-field prepend-icon="lock" name="password" label="Password" id="password" …
```
> refactor(theme): use metaInfo() and nuxt() instead of hacking $options

- src/components/VList/VList.js
- src/components/VList/VListGroup.js
- src/components/VList/VListTile.js
- src/components/VSubheader/VSubheader.js
- src/stylus/components/_lists.styl
- test/unit/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
- test/unit/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
- test/unit/components/VList/VListTile.spec.js
- test/unit/components/VList/__snapshots__/VList.spec.js.snap
- test/unit/components/VList/__snapshots__/VListGroup.spec.js.snap
- test/unit/components/VList/__snapshots__/VListTile.spec.js.snap
- test/unit/components/VSelect/VSelect-combobox.spec.js
- test/unit/components/VSelect/VSelect.spec.js
- test/unit/components/VSelect/VSelect2.spec.js
- test/unit/components/VSelect/__snapshots__/VSelect.spec.js.snap
- test/unit/components/VSelect/__snapshots__/VSelect2.spec.js.snap
Fixes a bug where `v-list` would render list styles in certain scenarios. In order to fix this problem, I have changed all render functions to rendering divs. `v-subheader` was also updated to render divs instead of li's
Also had to update specs and snapshots to reflect the render function changes
Fixes #3348 
```vue
<template>
<v-app>
<v-content>
<v-container>
<v-flex xs12>
<v-card>
<v-list>
<v-list-group v-model="showDetail">
<v-list-tile slot="activator">
<v-list-tile-title>Details</v-list-tile-title>
</v-list-tile>
<v-subheader>
Test 1
</v-subheader>
<v-list-tile>
weird
</v-list-tile>
<v-subheader>
Test 2
</v-subheader>
<v-list-tile>
weird
</v-list-tile>
<v-subheader>
Test 3
</v-subheader>
<v-list-tile> …
```
> refactor(VList): use divs instead of ul and li

- src/components/VSelect/mixins/select-generators.js
fixes #3526
```html
<template>
<v-app>
<v-content>
<v-container>
<v-select autocomplete :items="['']"/>
</v-container>
</v-content>
</v-app>
</template>
```
> fix(VSelect): disable the menu transition with false instead of ''

- src/components/VTextField/VTextField.js
fixes #3467
```vue
<template>
<v-app>
<v-content>
<v-container>
<v-layout v-for="type in dirtyTypes" :key="type">
<v-text-field v-bind="{ type, label: type }"/>
</v-layout>
</v-container>
</v-content>
</v-app>
</template>
<script>
const dirtyTypes = ['color', 'file', 'time', 'date', 'datetime-local', 'week', 'month']
data: () => ({
dirtyTypes
})
}
</script>
```
> fix(text-field): add color and file to dirty types

- src/stylus/components/_input-groups.styl
- src/stylus/components/_text-fields.styl
Turns out that flex rule isn't even needed, it hasn't been touched since e735b181e32ae6123f24f0043aa20a8b927b826c  
I still prevented the counter from wrapping, there isn't any scenario I can think of that you would want that to happen.
fixes #3381
Avoids regression of #3077
```html
<template>
<v-app>
<v-content>
<v-container>
<v-text-field :counter="10" required :rules="[v => !!v || 'Required']"/>
</v-container>
</v-content>
</v-app>
</template>
```
---
```html
<template>
<v-app>
<v-content>
<v-container text-xs-center>
<v-text-field
:counter="10"
hint="foobar longish hint this should wrap at some point"
required
:rules="[v => !!v || 'Required']"
/>
</v-container>
</v-content>
</v-app>
</template>
```
---
```html
<template>
<v-app>
<v-content>
<v-container>
<v-text-field …
```
> fix(VTextField): allow error container to shrink

- src/stylus/components/_grid.styl
- Use `flex-grow: 0` instead of `max-width` to allow setting the height of rows in a column v-layout (#3470)
fixes #3470
coming soon...
> fix(grid): prevent .flex from growing instead of using max-width

- src/components/VToolbar/VToolbar.js
- test/unit/components/VToolbar/VToolbar.spec.js
Functionality to only hide the toolbar (not extension) was accidentally removed in the layout refactor (0.17)
Documentation update: https://github.com/vuetifyjs/vuetifyjs.com/pull/348
fixes #3484 
jest
``` vue
<template>
<v-app style="height: 500vh;">
<v-toolbar app scroll-toolbar-off-screen>
<v-toolbar-title>Hello</v-toolbar-title>
<v-toolbar-title slot="extension">Hello 2</v-toolbar-title>
</v-toolbar>
<v-content>
<v-container>
<v-layout wrap>
<v-flex
v-for="n in 50"
:key="n"
xs4
>
<v-card height="200px"></v-card
></v-flex>
</v-layout>
</v-container>
</v-content>
</v-app>
</template>
```
> fix(v-toolbar): added back missing functionality

- src/components/VTabs/VTab.js
- test/unit/components/VTabs/VTab.spec.js
vue-router dynamically updates the to prop which causes issues with our logic, instead use their
same method to resolve the proper path
fixes #3418
none - cannot mock vue router. it is understood if the using is using the **to** prop, they have the $router instance
``` vue
<template>
<boilerplate>
<v-tabs centered v-model="tabs">
<v-tab :to="{name: 'Register'}" key="register">
Regular Page
</v-tab>
<v-tab to="/login/1" key="login-1">
Test 1
</v-tab>
<v-tab :to="{name: 'Login', params:{id:2}}" key="login-2">
Test 2
</v-tab>
<v-tab :to="{name: 'Login', params:{id:3}}" key="login-3">
Test 3
</v-tab>
</v-tabs>
{{ tabs }}
<router-view></router-view>
</boilerplate>
</template>
<script>
data: () => ({
isFocused: false,
input: 'asdf',
tabs: null
}),
methods: {
onBlur () { …
```
> fix(v-tab): updated logic for determining action

- src/mixins/bootable.js
- src/mixins/detachable.js
- test/unit/components/VDialog/VDialog.spec.js
- test/unit/components/VMenu/VMenu.spec.js
- test/unit/mixins/bootable.spec.js
- test/unit/mixins/detachable.spec.js
Lazy will now affect the detaching of the content at mount. This avoids unnecessary DOM manipulation when specified as lazy
fixes #3570
jest
``` vue
<template>
<div id="app">
<v-content>
<v-data-table
:pagination.sync="pagination"
:items="items"
>
<td>
<v-edit-dialog
:return-value.sync="props.item.name"
lazy
> {{ props.item.name }}
<v-text-field
slot="input"
label="Edit"
v-model="props.item.name"
single-line
counter
:rules="[max25chars]"
</td>
<td …
```
> fix(detachable): apply lazy behavior to initDetach

- src/components/VTabs/VTabs.js
- test/unit/components/VTabs/VTabs.spec.js
#3560 
```vue
<template>
<v-app>
<v-content>
<v-tabs
slider-color="yellow"
@input="changeInput"
>
<v-tab
v-for="i in 3"
:key="i"
:href="`#tab-${i}`"
>
Item {{ i }}
</v-tab>
<v-tab-item
v-for="i in 3"
:key="i"
:id="`tab-${i}`"
>
<v-card flat>
<v-card-text v-text="text"></v-card-text>
</v-card>
</v-tab-item>
</v-tabs>
</v-content>
</v-app>
</template>
<script>
data() {
return {
model: 'tab-2',
text:
'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
};
},
methods: {
changeInput(val) {
console.log(val);
},
},
};
</script>
```
> fix(tabs): fixed twice emit input

- src/mixins/rippleable.js
- test/unit/mixins/__snapshots__/rippleable.spec.js.snap
- test/unit/mixins/rippleable.spec.js
Rippleable mixin did not explicitly emit a click event, and bound click events would overwrite the default
fixes #3554
jest
``` vue
<template>
<div id="app">
<v-switch :label="`Switch 1: ${switch1.toString()}`"
v-model="switch1"
@click="toggleMessage">
</v-switch>
<p v-if="showMessage">I'm showing!</p>
</v-container>
</v-app>
</div>
</template>
<script>
data () {
return {
switch1: false,
showMessage: false,
}
},
methods: {
toggleMessage() {
this.$data.showMessage = !this.$data.showMessage
}
}
}
</script>
```
> fix(rippleable): added explicit click event

- src/stylus/components/_dialogs.styl
- src/util/helpers.js
safari returns 0 instead of 'auto' if an element's parent is positioned,
inheriting the z-index should prevent that
fixes #2111
I don't have any apple devices, so this will need testing by someone else (@chewy94?)
I did verify that it doesn't affect anything in win10 chrome however
```vue
<template>
<boilerplate>
<v-dialog max-width="320">
<v-btn slot="activator">Open dialog</v-btn>
<v-card>
<v-card-text>
<v-menu>
<v-btn slot="activator">Open menu</v-btn>
<v-list>
<v-list-tile v-for="i in 10" :key="i">
<v-list-tile-title>Item {{ i }}</v-list-tile-title>
</v-list-tile>
</v-list>
</v-menu>
</v-card-text>
</v-card>
</v-dialog>
</boilerplate>
</template>
```
> fix(VDialog): inherit z-index from wrapper

- src/components/Vuetify/util/goTo.js
constructor.name isn't reliable for type checking when function names
are minified, but vue components will always have an _isVue property
Also fixed position calculation of elements in relative contexts,
Element.offsetTop only returns the offset to the offsetParent in such
cases
Fixes #3611
N/A, used http://localhost:8095/motion/scrolling
> fix(goTo): validate target correctly when vue is minified

- src/components/VTabs/VTab.js
- test/unit/components/VTabs/VTab.spec.js
This is a particularly tricky thing to get right. I've added a useless mock in the test so we can at least start to test the expected output, but it would be better if vue-router was testable. The previous implementation wasn't using all available args in **router.resolve** which was the cause for @sindrepm 's issue (he commented in #3654). The actual fix for 3654 was the comparison of the `to` prop as a string without an associated route. While we never explicitly supported this, and the correct way would be to simply use **href**, it is an easy enough change to handle both.
- Added additional args to **resolve** function in order to allow for implicit params from routes
- Added type check for `to` prop to skip resolve
fixes #3654
jest (kind of)
See attached issue
> fix(v-tab): fixed resolve comparison and args

- src/stylus/components/_tabs.styl
Fixes wrong styling and adds `pointer-events: none` to avoid calling click handler on click
fixes #3644
visually
```vue
<template>
<v-app>
<v-content>
<v-tabs v-model="tab">
<v-tab>One</v-tab>
<v-tab disabled>Two</v-tab>
<v-tab>Three</v-tab>
</v-tabs>
</v-content>
</v-app>
</template>
<script>
data () {
return {
tab: null
}
},
}
</script>
```
> fix (v-tabs): disabled tab is not disabled

- src/mixins/returnable.js
This PR fixes the problem, that the `update:returnValue` event is emitted twice by `returnable` mixin `save` method.
The `returnable` mixin emits `update:returnValue` event twice on save.
The first time inside `save` method, the second time directly after
this when the value of `isActive` flag is changed to `false`
(in this case the watcher emits the event), so it is enough to just
set the `isActive` flag to false inside `save` method and the
`update:returnValue` event will be called "automatically" by watcher.
The PR fixes the issue #3688.
The changes was locally integrated in my project and visually tested in browser.
> fix(3688): twice emitted `update:returnValue` event on save

- src/stylus/components/_avatars.styl
Fixes wrong vertical alignment for icon avatar when import Vuetify CSS before Google font CSS.
Fixes #3612
https://github.com/vuetifyjs/vuetifyjs.com/issues/353 can be closed
visually
> fix (VAlatar): Icon avatar alignment

- src/components/VTabs/VTabs.js
- test/unit/components/VTabs/VTabs.spec.js
when the local **tabs** changes, re-evaluate overflow
fixes #3643
jest
``` vue
<template>
<div id="app">
<v-tabs
dark
color="cyan"
show-arrows
>
<v-tabs-slider color="yellow"></v-tabs-slider>
<v-tab
v-for="i in tabs"
:key="i"
:href="'#tab-' + i"
>
Item {{ i }}
</v-tab>
<v-tabs-items>
<v-tab-item
v-for="i in tabs"
:key="i"
:id="'tab-' + i"
>
<v-card flat>
<v-btn @click.native="addTab">Add tab</v-btn>
<v-btn @click.native="removeTab">Remove tab</v-btn>
</v-card>
</v-tab-item>
</v-tabs>
</v-app>
</div>
</template>
<script>
data () {
return {
text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis …
```
> fix(v-tabs): recalculate overflow on tabs change

- src/components/VBadge/VBadge.js
- src/stylus/components/_badges.styl
- test/unit/components/VBadge/VBadge.spec.js
- test/unit/components/VBadge/__snapshots__/VBadge.spec.js.snap
> Refactor (VBadge): Add v- prefix to badge classes

- src/components/VBreadcrumbs/VBreadcrumbs.js
- src/components/VBreadcrumbs/VBreadcrumbsItem.js
- src/stylus/components/_breadcrumbs.styl
- test/unit/components/VBreadcrumbs/VBreadcrumbs.spec.js
- test/unit/components/VBreadcrumbs/VBreadcrumbsItem.spec.js
- test/unit/components/VBreadcrumbs/__snapshots__/VBreadcrumbs.spec.js.snap
> Refactor (VBreadcrumbs): Add v- prefix on breadcrumbs classes

- src/components/VDataTable/VDataTable.js
- src/components/VDataTable/index.js
- src/components/VDataTable/mixins/body.js
- src/components/VDataTable/mixins/progress.js
- src/stylus/components/_data-table.styl
- test/unit/components/VDataTable/VDataTable.spec.js
- test/unit/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
> Refactor (VDataTable): Add v- prefix on datatable classes

- src/components/VDivider/VDivider.js
- src/stylus/components/_dividers.styl
- test/unit/components/VDivider/VDivider.spec.js
- test/unit/components/VDivider/__snapshots__/VDivider.spec.js.snap
> Refactor (VDivider): Add v- prefix to divider classes

- src/components/VFooter/VFooter.js
- src/stylus/components/_footer.styl
- test/unit/components/VFooter/VFooter.spec.js
- test/unit/components/VFooter/__snapshots__/VFooter.spec.js.snap
> Refactor (VFooter): Add v- prefix to footer classes

- src/components/VExpansionPanel/VExpansionPanel.js
- src/components/VExpansionPanel/VExpansionPanelContent.js
- src/stylus/components/_expansion-panel.styl
- test/unit/components/VExpansionPanel/VExpansionPanel.spec.js
- test/unit/components/VExpansionPanel/VExpansionPanelContent.spec.js
- test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanel.spec.js.snap
- test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanelContent.spec.js.snap
> Refactor (VExpansionPanel): Add v- prefix to expansion-panel classes

- src/stylus/components/_footer.styl
* Fix stylus missing v- prefix
* Yarn test
> Refactor (VFooter): Add v- prefix on footer classes

- src/components/VSystemBar/VSystemBar.js
- src/stylus/components/_system-bars.styl
- test/unit/components/VSystemBar/VSystemBar.spec.js
> refactor (VSystemBar): Add v- prefix on system bar classes

- src/stylus/components/_data-iterator.styl
* Fix stylus missing v- prefix
* Yarn test
> Refactor (VDataIterator): Add v- prefix to data-iterator classes

- src/components/VNavigationDrawer/VNavigationDrawer.js
- src/components/VPagination/VPagination.js
- src/stylus/components/_grid.styl
- test/unit/components/VPagination/VPagination.spec.js
`v-layout` had no maximum width, allowing its children to extend its box model. This is the primary source of determining **maxButtons**. `v-navigation-drawer` was not triggering a resize after its transition ended, causing another problem with the above.
fixes #3759
jest
``` vue
<template>
<div id="app">
fixed
app
>
<v-list dense>
<v-list-tile @click="">
<v-list-tile-action>
<v-icon>home</v-icon>
</v-list-tile-action>
<v-list-tile-title>Home</v-list-tile-title>
</v-list-tile>
<v-list-tile @click="">
<v-list-tile-action>
<v-icon>contact_mail</v-icon>
</v-list-tile-action>
<v-list-tile-title>Contact</v-list-tile-title>
</v-list-tile>
</v-list> …
```
> fix(v-pagination): fixed responsive pagination

- src/components/transitions/expand-transition.js
expand-transition generated error if it started expanded, as el._parent was not set
closes #3812, closes #3050
manually with markup for both issues
see issues
> fix: expand-transition error

- src/components/VTabs/VTabs.js
- test/unit/components/VTabs/VTabs.spec.js
When `v-tabs` is scrolling items into view, it was possible
fixes #3294
jest
``` vue
<template>
<v-app>
<v-toolbar
dark
dense
>
<v-tabs
grow
>
<v-tabs-slider></v-tabs-slider>
<v-tab
v-for="item in tabs"
:key="item.key"
>
{{ item.label }}
</v-tab>
<v-tab
v-for="(item, index) in tabs"
:key="index + 3"
>
{{ item.label }}
</v-tab>
<v-tab
v-for="(item, index) in tabs"
:key="index + 6"
>
{{ item.label }}
</v-tab>
</v-tabs>
</v-toolbar>
</v-app>
</template>
<script>
data() {
return {
tabs: [
{
key: 'about',
label: 'About',
target: '/about/'
},
{
key: 'resume',
label: 'Resume',
target: '/resume/'
},
{
key: 'contact',
label: 'Contact',
target: '/contact/'
}
]
}
}
}
</script>
```
> fix(v-tabs): reset scrollOffset if not overflowing

- src/stylus/components/_grid.styl
Add missing `d-inline` class as listed at https://vuetifyjs.com/en/layout/display
There was a missing implementation of the `d-inline` class.
Simply.
`<div class="d-inline"></div>`
> Add missing `d-inline` class

- index.d.ts
Type hints should now be shown for all options in Vue.use(Vuetify, ...)
Also includes types for #3591
> feat(types): add icons and Vuetify plugin to type definition

- src/components/VTooltip/VTooltip.js
Fixes #3016.
Position on top was based on activator's height and not content's height.
Tested all positions: `top`, `right`, `bottom` and `left`. Tested also multi-line and single-line text inside the tooltip.
> fix (VTooltip): top

- index.d.ts
- src/components/VApp/mixins/app-theme.js
- src/components/Vuetify/mixins/options.js
- test/unit/components/VApp/VApp.spec.js
resolves #3950 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_inline_script
```js
Vue.use(Vuetify, {
options: {
cspNonce: '2726c7f26c'
}
})
```
Resulting HTML:
```html
<style type="text/css" id="vuetify-theme-stylesheet" nonce="2726c7f26c">
...
```
> feat(theme): allow a nonce to be specified for the stylesheet

- src/mixins/routable.js
Removes limitations for `target` attribute in the `routable` mixin.
The `target` attribute only works on anchor elements. But it should also work on router/nuxt links. There is no need to limit it. It does no harm on a normal button. Anyway why would you provide `target` on a button?
Playground.vue
```vue
<template>
<v-app>
<v-btn to="/page2">
open in the same tab
</v-btn>
<v-btn to="/page2" target="_blank">
open in a new tab
</v-btn>
<v-btn @click="alert" target="_blank">
just an alert button
</v-btn>
<router-view/>
</v-app>
</template>
<script>
methods: {
alert() {
alert('hi')
}
}
}
</script>
```
In the documentation the text
`Specify the target attribute, only works with anchor tag.`
should be changed to this
`Specify the target attribute.`
I can create a PR in the …
> feat: routable target prop NOT for anchors only

- src/stylus/components/_grid.styl
- src/stylus/generic/_bootstrap.styl
- src/stylus/trumps/_display.styl
- src/stylus/trumps/_spacing.styl
- src/stylus/trumps/_text.styl
This bugfix prevents the final value of the stylus iteration variable "query" from being injected as the v-linear-progress component's animation title of the same name.
"query" is used as both a non-prefixed variable in _display.styl and an animation name used in v-linear-progress:
This results in the final iteration value being injected in place of the animation name "query":
Proposed change allows building app.css with intended animation name:
> Fix: Prevent stylus variable vs. animation name collision ("query")

- src/directives/ripple.js
Fixed the `removeChild` console errors that could occur if the mouse was moved outside of focus (blur) within the ripple timer period.
The problem was producing console errors, an attempt to remove a child that no longer existed.
Visually based on steps that were easy to reproduce before the changes (and not possible to reproduce after the changes) and by placing a breakpoint inside the timer code and tracing and inspecting.
> removeChild error when moving mouse away from an active ripple

- src/components/VSelect/VSelect.js
Fixed the one remaining hard-coded internal icon name.
To allow Vuetify users to replace the iconfont set or individual icons.
Visually, also reran the tests. All automated tests continue to pass.
The dropdown icon in `v-select` now defaults to MD but can be overriden, with code such as:
```
Vue.use(Vuetify, { iconfont: 'fa' })
```
which replaces it with a Font-Awesome 5 icon (if they are available in the app).  Prior to this commit, it was hard-coded to use the Material Design (MD) icon.
> Fix: missed icon updates for 1.1

- src/components/VAutocomplete/VAutocomplete.js
- src/components/VSelect/VSelect.js
Uses a computed property to cache the list VNode instead of rendering a new one with each update. 
Turns out it's fairly safe to use scoped slots in computed properties, it's just regular ones that won't update. 
I felt like it. 
It improves performance quite a bit with a large number of items, here I have 5000:
Search is still slow as a dog but we can't really do much about that other than virtualise the list again. 
```vue
<template>
<v-content>
<v-container>
<v-autocomplete label="5k items" :items="items" v-model="selected">
<template slot="item" slot-scope="props">
<v-list-tile-title>
{{ props.item }} - {{ time }}
</v-list-tile-title>
</template>
<template slot="label">{{ time }}</template>
<v-autocomplete :items="['foo', 'bar']"/>
</v-container> …
```
> perf(VSelect): cache list VNode

- src/components/VAutocomplete/VAutocomplete.js
- src/components/VSelect/VSelect.js
- test/unit/components/VSelect/VSelect3.spec.js
select used to at least try to reduce the burden on massive lists, accidentally removed
Added back functionality that would slice the list (fake virtualization)
Performance issues
n/a
``` vue
<template>
<v-content>
<v-container>
<v-autocomplete label="5k items" :items="items" v-model="selected">
<template slot="item" slot-scope="props">
<v-list-tile-title>
{{ props.item }} - {{ time }}
</v-list-tile-title>
</template>
<template slot="label">{{ time }}</template>
<v-autocomplete :items="['foo', 'bar']"/>
</v-container>
</v-content>
</v-app>
</template>
<script>
data: () => ({
selected: '',
items: [...Array(5000).keys()],
time: 0
}),
mounted () {
this.count()
},
methods: {
count () {
// setTimeout(() => {
//   this.time++
// …
```
> fix(v-select): add back fake virtualization

- src/components/VTextField/VTextField.js
`VTextField` had a hard-coded `clear` icon, preventing config-based iconfont replacement.
Fixes a missing update from the 1.1 enhancement for configurable icon sets.
Before/after testing with "fa" iconfont and a clearable v-select input.  "clear" prior to fix, proper icon after fix.
> Fixed one more case of hard-coded icon (clear, if clearable)

- src/stylus/components/_inputs.styl
fixes #4022
<details>
```vue
<template>
<v-container>
<v-layout row>
<v-flex>
<v-text-field label="normal width"/>
</v-flex>
</v-layout>
<v-layout row>
<v-flex>
<v-menu full-width>
<v-text-field slot="activator" label="broken width"/>
</v-menu>
</v-flex>
</v-layout>
</v-container>
</v-app>
</template>
```
</details>
> fix(VInput): allow input to fill width when in a flex container

- src/components/VTextField/VTextField.js
- test/unit/components/VTextField/VTextField.spec.js
in 1.0 you could call focus and blur directly, but they were renamed in the refactor
<details>
```vue
<template>
<v-card>
<v-card-text>
<v-layout align-center>
<v-checkbox v-model="enabled" hide-details class="shrink mr-2"/>
<v-text-field ref="textField" label="I want to be edited without clicking on this field!" :disabled="!enabled"/>
</v-layout>
</v-card-text>
</v-card>
</v-app>
</template>
<script>
data: () => ({
includeFiles: true,
enabled: false
}),
watch: {
enabled (val) {
this.$nextTick(() => {
val
? this.$refs.textField.focus()
: this.$refs.textField.blur()
})
}
}
}
</script>
```
</details>
> fix(VTextField): add back focus and blur methods

- src/components/VToolbar/VToolbarSideIcon.js
- src/components/Vuetify/mixins/icons.js
- types/index.d.ts
Fixed the undesired requirement when using `v-toolbar-side-icon` for MD icons to be available, even if the `iconfont` option was used to specify 'mdi', 'fa' or 'fa4'.
This PR allow a Vuetify app to rely solely on a single icon font, such as Font-Awesome or MDI.
Visually, with [a test app](https://github.com/appurist/vuetify-test-wp) and verified all unit tests continue to pass.
Load Vuetify with: `Vue.use(Vuetify, { iconfont: 'fa' })` and then include:
```vue
<v-toolbar app>
<v-toolbar-side-icon></v-toolbar-side-icon>
</v-toolbar>
```
The above would show "MENU" rather than the three-bars hamburger icon unless the MD icons were loaded.
See a complete app example here:
https://github.com/appurist/vuetify-test-wp/blob/master/src/App.vue
</details>
This change adds `menu` to the list of …
> Fixed missing hamburger 'menu' icon from customizable icon map.

- src/components/VSlider/VSlider.js
- test/unit/components/VRangeSlider/VRangeSlider.spec.js
- test/unit/components/VSlider/VSlider.spec.js
~In v1.0 sliders didn't have stepping by default~
The cause looks like a5ed2f5419a456a01b85fdb3b01f0e44265bcbd2, ~~but for some reason I had to change the default prop value too, even though it was `1` in 1.0 as well.~~ Default was 1 in 1.0, but you could set it to 0 to override. 
<details>
```vue
<template>
<v-app>
<v-container>
<v-slider v-model="slider" min="0" max="1" ticks step="0.1"></v-slider>
<v-slider v-model="slider" min="-1" max="2" ticks step="0.01"></v-slider>
<pre>{{ slider }}</pre>
</v-container>
</v-app>
</template>
<script>
data: () => ({
slider: 0
})
}
</script>
```
</details>
> fix(VSlider): allow step to be set to 0

- src/components/VMenu/mixins/menu-position.js
If the component is destroyed before the 50ms it takes to call this function, an exception is thrown.
The `calculateScroll` method is called after a 50ms timeout to wait for the animation to finish (if I understand correctly).
However, while running automated tests, I happen to destroy the component faster than 50ms. It results in an exception being thrown because `this.$refs.content` is undefined.
It avoids an exception being thrown and my app's automated tests to break.
I've tested this visually. No more exception with this simple `if` clause.
<details>
```vue
```
</details>
> Fix exception when menu is destroyed quickly

- src/stylus/components/_cards.styl
- src/stylus/components/_dialogs.styl
- src/stylus/components/_radio-group.styl
- src/stylus/components/_radios.styl
- src/stylus/components/_selection-controls.styl
reverts 33d46ce. updated selection control styles to prevent overflow bug
fixes #4168
n/a
<details>
```vue
<template>
<div id="app">
<v-dialog v-model="dialog" width="600px">
<v-btn slot="activator" color="primary" dark>Open Dialog</v-btn>
<v-card>
<v-card-title>
<span class="headline">Use Google's location service?</span>
<v-card-text>Lorem ipsum dolor sit amet, semper quis, sapien id natoque elit. Nostra urna at, magna at neque sed sed ante imperdiet, dolor mauris cursus velit, velit non, sem nec. Volutpat sem ridiculus placerat leo, augue in, duis erat proin condimentum in a eget, sed fermentum sed vestibulum varius ac, vestibulum volutpat orci ut elit eget tortor. Ultrices nascetur nulla gravida ante arcu. Pharetra …
```
> fix(v-dialog/selection-controls): style updates

- src/components/VTextField/VTextField.js
- test/unit/components/VTextField/VTextField.spec.js
fixes #4223
added unit test
<details>
```vue
<template>
<v-app id="app">
<v-container>
<v-text-field required />
<v-autocomplete required />
<v-select required />
</v-container>
</v-app>
</template>
```
</details>
> fix (v-text-field): required attr stripped off

- src/components/VStepper/VStepper.js
Find v-stepper-step & v-stepper-content by component name.
We are using jsx instead of html template.  
Our code will look like this:  
```js
import {VStepper, VStepperContent} from 'vuetify/src/components/VStepper'
// ...
render (h) {
return (
<VStepper>
<VStepperContent />
</VStepper>
}
```
So the `_compoentTag` will be `undefined`.
nono
> fix(VStepper): Use name instead of tag name

- src/components/VTimePicker/VTimePicker.js
- test/unit/components/VTimePicker/VTimePicker.spec.js
fixes #3371
visually, updated unit test
<details>
```vue
<template>
<v-app>
<v-content>
<v-time-picker v-model="t" />
<v-menu :close-on-content-click="false">
<v-btn slot="activator">Picker in popup</v-btn>
<v-time-picker v-model="t" />
</v-menu>
</v-content>
</v-app>
</template>
<script>
data: () => ({t: null})
}
</script>
```
</details>
It works fine with standalone picker, but I'm not sure if the behaviour is now correct with the picker in menu. Afair @nekosaur was ok with this
> fix(v-time-picker): don't switch to hours after selecting minutes

- src/components/VTextField/VTextField.js
- test/unit/components/VTextField/VTextField.spec.js
Fixes label and additionally moves some code to a computed prop
The main fix introduces a minor issue with `reversed` field, see the second text field in playground
fixes #4187
visually
<details>
```vue
<template>
<v-app>
<v-content>
<v-text-field label="test" type="time" />
<v-text-field label="test" reverse type="time" />
<v-text-field label="test" solo type="time" />
</v-content>
</v-app>
</template>
```
</details>
> fix(v-text-field): wrong label position in empty time input

- src/components/VTimePicker/VTimePickerClock.js
- test/unit/components/VTimePicker/VTimePickerClock.spec.js
fixes #4195
visually, added unit test
<details>
```vue
<template>
<v-app>
<v-content>
<v-time-picker v-model="t" scrollable :allowed-hours="h => h === 7 || h === 14" :allowed-minutes="h => !(h%3)"></v-time-picker>
<v-time-picker v-model="t" scrollable min="14:03" max="17:27"></v-time-picker>
</v-content>
</v-app>
</template>
<script>
data: () => ({t: null})
}
</script>
```
</details>
> fix(v-time-picker-clock): allows time picker clock to be scrollable with allowed-values

- src/stylus/elements/_lists.styl
Add padding to the html list to be more like standard html list.
Right now bullets are left of the content https://i.imgur.com/EvYjEvm.png , which is pretty unusual, doesnt happen on any other major sites and doesnt match standard behaviour of html lists.
visually
<details>
```vue
<div id="app">
<main>
<v-container>
<p>content</p>
<ol>
<li>list item</li>
</ol>
<ul>
<li>list item</li>
</ul>
</v-container>
</main>
</v-app>
</div>
new Vue({
el: '#app',  
})
```
</details>
> add padding to html list (ul, ol)

- src/components/VAutocomplete/VAutocomplete.js
- test/unit/components/VAutocomplete/VAutocomplete.spec.js
Should show "State 1": https://codepen.io/anon/pen/yEgxOV?editors=1010
Similar to #1788 but for v-autocomplete
<details>
```vue
<template>
<v-app>
<v-flex xs6>
<v-subheader>Standard</v-subheader>
</v-flex>
<v-flex xs6>
<v-autocomplete :items="items" v-model="selected" label="Select"></v-autocomplete>
</v-flex>
</v-layout>
<pre>selected: {{ selected }}</pre>
<pre>items: {{ items }}</pre>
</v-container>
</v-app>
</template>
<script>
data: () => ({
selected: 1,
items: []
}),
mounted () {
setTimeout(() => {
this.items = [
{ text: "State 1", value: 1 },
{ text: "State 2", value: 2 },
{ text: "State 3", value: 3 },
{ text: "State 4", value: 4 },
{ text: "State 5", value: 5 },
{ text: "State 6", value: 6 },
{ text: "State 7", value: 7 }
] …
```
> fix(VAutocomplete): update input value when items change

- src/components/VInput/VInput.js
- src/components/VTextField/VTextField.js
- test/unit/components/VInput/VInput.spec.js
- test/unit/components/VInput/__snapshots__/VInput.spec.js.snap
Removed `prepend-icon` and `append-icon` slots from input components
Also added missing `appendOuterIconCb` prop
These two were marked for deprecation, even though none of these slots existed before v1.1
Resolves #4209
> feat(inputs): remove icon slots

- src/components/VTextField/VTextField.js
- src/components/VTextarea/VTextarea.js
- src/stylus/components/_textarea.styl
- test/unit/components/VTextField/VTextField.spec.js
- test/unit/components/VTextarea/VTextarea.spec.js
- test/unit/components/VTextarea/__snapshots__/VTextarea.spec.js.snap
use input.scrollHeight instead of a mask element
If you press enter, the field flickers as it has to wait for vue to update. The mask element also doesn't handle trailing newlines very well. 
<details>
```vue
<template>
<v-content>
<v-layout>
<v-container>
<v-switch v-model="outline" label="outline"/>
<v-textarea v-model="title" label="Message" auto-grow :outline="outline"></v-textarea>
<v-textarea v-model="title" label="static"></v-textarea>
<v-text-field v-model="text" @keyup.enter="text = ''"></v-text-field>
<v-text-field v-model="text"></v-text-field>
</v-container>
</v-layout>
</v-content>
</v-app>
</template>
<script>
data: () => ({
outline: false,
title: '1\n2\n3\n4\n6\n7\n8\n9\n0',
text: ''
})
}
</script>
```
</details>
> fix(VTextArea): prevent layout flickering with auto-grow

- src/mixins/validatable.js
fixes #4247
<details>
```vue
<template>
<v-app>
<v-container>
<v-form ref="form" v-model="valid" lazy-validation>
<v-text-field
v-model="name"
:counter="10"
label="Name"
required
validate-on-blur
<v-text-field
:rules="emailRules"
label="E-mail"
required
<v-select
:items="items"
:rules="[v => !!v || 'Item is required']"
label="Item"
required
></v-select>
<v-checkbox
v-model="checkbox"
:rules="[v => !!v || 'You must agree to continue!']"
label="Do you agree?"
required
></v-checkbox>
<v-btn
:disabled="!valid"
@click="submit"
>
submit
</v-btn>
<v-btn @click="clear">clear</v-btn>
</v-form>
</v-container>
</v-app>
</template>
<script>
data: () => ({
valid: true,
name: '',
nameRules: [
v => !!v …
```
> fix(VTextField): force validation with validate-on-blur

- src/stylus/components/_tabs.styl
- src/stylus/components/_toolbar.styl
removed code that wasn't even working, reduced complexity of gutter
[Reference](https://material.io/design/layout/responsive-layout-grid.html#breakpoints)
Gutters were not dynamic and not matching `v-container` on the different resolution. Refactored a function that wasn't event working to begin with
visually chrome, ie, edge, ff
<details>
```vue
<template>
<v-app>
<v-toolbar>
<v-toolbar-side-icon />
<v-toolbar-title>Title</v-toolbar-title>
<v-spacer />
<v-icon>menu</v-icon>
<template slot="extension">
<v-toolbar-title>Hello</v-toolbar-title>
</template>
</v-toolbar>
<v-toolbar>
<v-toolbar-title>Title</v-toolbar-title>
<v-spacer />
<v-menu>
<v-icon slot="activator">menu</v-icon>
</v-menu>
</v-toolbar>
<v-toolbar>
<v-toolbar-title>Title</v-toolbar-title>
<v-spacer />
<v-menu> …
```
> feat(v-toolbar): normalize gutter functionality

- src/components/VAutocomplete/VAutocomplete.js
- test/unit/components/VAutocomplete/VAutocomplete.spec.js
fixes #4220
unit test
<details>
```vue
<template>
<v-select combobox label="Select a Bookmark Post">
<div slot="no-data">No data</div>
</v-select>
</v-container>
</v-app>
</template>
```
</details>
> fix(VAutocomplete): combobox - show no-data slot if provided

- src/components/VSelect/VSelectList.js
- test/unit/components/VSelect/VSelectList.spec.js
- test/unit/components/VSelect/__snapshots__/VSelectList.spec.js.snap
fixes #4217
visually, unit test
<details>
```vue
<template>
<boilerplate>
:items="items"
label="items"
return-object
item-text="name"
item-value="username"
required
>
<template
slot="selection"
slot-scope="data"
>
<template>
<v-list-tile-avatar>
</v-list-tile-avatar>
<v-list-tile-title v-html="data.item.name"/>
</template>
</template>
<template
slot="item"
slot-scope="data"
>
<template>
<v-list-tile-avatar>
</v-list-tile-avatar>
<v-list-tile-title v-html="data.item.name"/>
<v-list-tile-sub-title v-html="data.item.username"/>
</template>
</template>
</boilerplate>
</template>
<script>
data: () => ({
selected: null, …
```
> fix(VSelectList): use noDataText if item slot is provided

- src/components/VTextField/VTextField.js
Fixed invalid label position for text fields with placeholder or reversed
https://codepen.io/anon/pen/yEMpQb - focus the field
visually
<details>
```vue
<template>
<div class=heading>With placeholder</div>
<v-text-field
label="Label"
value=""
prefix="$"
<v-text-field
label="Label"
value=""
<v-text-field
label="Label"
type="time"
value=""
prefix="$"
<v-text-field
label="Label"
type="time"
value=""
<div class=heading>Without placeholder</div>
<v-text-field
label="Label"
value=""
prefix="$"
<v-text-field
label="Label"
value=""
<div …
```
> fix(VTextField): invalid label position with placeholder

- src/stylus/components/_grid.styl
reverts a4b5ce8
fixes #4258
<details>
```vue
<template>
<v-content>
<v-container fluid fill-height>
<v-flex xs6>
<h1> This should fill the whole width </h1>
</v-flex>
</v-layout>
</v-container>
</v-content>
</v-app>
</template>
<style>
.flex {
background: blue;
}
</style>
```
</details>
> fix(grid): set v-flex max-width in column layouts

- src/components/VDataTable/VDataTable.js
- src/components/Vuetify/mixins/lang.ts
- src/mixins/data-iterable.js
- src/mixins/filterable.js
- test/unit/components/Vuetify/Vuetify.lang.spec.js
- types/index.d.ts
Allows one to specify a custom translation function to use for internal translations.
Allows integration of 3rd party translation plugins such as vue-i18n
manually
```vue
import VueI18n from 'vue-i18n'
Vue.use(VueI18n)
const messages = {
en: {
$vuetify: {
message: {
hello: 'hello world',
params: 'hello {0}'
}
},
},
ja: {
$vuetify: {
message: {
hello: 'こんにちは、世界',
params: 'こんにちは、{0}'
}
},
}
}
// Create VueI18n instance with options
const i18n = new VueI18n({
locale: 'ja', // set locale
messages, // set locale messages
})
Vue.use(Vuetify, {
lang: {
t: (key, ...params) => i18n.t(key, params)
}
})
```
> feat: Specify custom translation function

- src/components/VTextField/VTextField.js
- test/unit/components/VTextField/VTextField.spec.js
- test/unit/components/VTextField/__snapshots__/VTextField.spec.js.snap
`:counter="undefined"` shows the counter, worked properly in 1.0
1.0
https://codepen.io/anon/pen/aKEGXe
1.1
https://codepen.io/anon/pen/GGydeW
The difference between 1.0 and this PR is that in 1.0 it doesn't show the counter when value is `0`, in PR it shows, but not showing it when the numeric value is passed i'd consider as a bug
unit
```vue
<template>
<v-app>
<v-container>
<v-text-field label="10" :counter="10" />
<v-text-field label="0" :counter="0" />
<v-text-field label="null" :counter="null" />
<v-text-field label="undefined" :counter="undefined" />
<v-text-field label="false" :counter="false" />
</v-container>
</v-app>
</template>
```
> fix(VTextField): don't show v-counter if counter is null/undefined

- src/stylus/components/_toolbar.styl
Fix `v-list` negative margin when it is inside a `v-toolbar` along other elements.
A full width `v-list` works inside a `v-toolbar`, but this fix is needed when placing buttons or other components with it.
visually
playground
Windows 10
Chrome 67
<details>
```vue
<template>
<v-toolbar>
<v-list class="pa-0">
<v-list-tile>
<v-list-tile-title>My list title</v-list-tile-title>
</v-list-tile>
</v-list>
<v-btn></v-btn>
<v-btn></v-btn>
</v-toolbar>
<v-toolbar>
<v-btn></v-btn>
<v-btn></v-btn>
<v-list class="pa-0">
<v-list-tile>
<v-list-tile-title>My list title</v-list-tile-title>
</v-list-tile>
</v-list>
</v-toolbar>
<v-toolbar>
<v-list …
```
> fix(v-toolbar): fix toolbar list alignment

- src/components/VCard/VCard.js
- src/util/helpers.ts
- test/unit/components/VCard/__snapshots__/VCard.spec.js.snap
- test/unit/components/VMenu/__snapshots__/VMenu.spec.js.snap
- test/unit/util/helpers.spec.js
Updates `convertToUnit()` to return undefined when value is null/undefined/empty string
Removes default value ('auto') from `v-card`'s `height` prop
fixes #4344
visually
<details>
```vue
<template>
<v-app>
<v-container>
<v-card ref="0" class="ma-3 pa-3"></v-card>
<v-card ref="1" class="ma-3 pa-3" height=""></v-card>
<v-card ref="2" class="ma-3 pa-3" :height="undefined"></v-card>
<v-card ref="3" class="ma-3 pa-3" :height="null"></v-card>
<v-card ref="4" class="ma-3 pa-3" height="0"></v-card>
<v-card ref="5" class="ma-3 pa-3" :height="0"></v-card>
<v-card ref="6" class="ma-3 pa-3" height="60"></v-card>
<v-card ref="7" class="ma-3 pa-3" :height="60"></v-card>
<v-card ref="8" class="ma-3 pa-3" height="invalid-string"></v-card>
<v-card ref="9" class="ma-3 pa-3" height="auto"></v-card> …
```
> fix(VCard, converToUnit): set proper styles with falsy height prop

- src/components/VTabs/VTabs.js
fixes #3294
Check if active tab is last in list and don't add an offset when scrolling if it is.
When using `grow` sometimes tabs would get scrolled (and offset) incorrectly.
This change also improves look and feel of normal scrolling tabs
visually
```vue
<template>
<v-app>
<v-toolbar
dark
dense
>
<v-tabs
grow
>
<v-tabs-slider></v-tabs-slider>
<v-tab
v-for="item in tabs"
:key="item.key"
>
{{ item.label }}
</v-tab>
<v-tab
v-for="(item, index) in tabs"
:key="index + 3"
>
{{ item.label }}
</v-tab>
<v-tab
v-for="(item, index) in tabs"
:key="index + 6"
>
{{ item.label }}
</v-tab>
</v-tabs>
</v-toolbar>
</v-app>
</template>
<script>
data() {
return {
tabs: [
{
key: 'about',
label: 'About',
target: '/about/'
},
{
key: 'resume',
label: 'Resume',
target: '/resume/'
},
{
key: …
```
> Don't offset last tab when scrolling

- src/components/VNavigationDrawer/VNavigationDrawer.js
Hover and click event on components in a navigation-drawer is currently emitting resize events on the navigation-drawer. This is breaking mapbox transitions i my app.
This PR ensures that resize event only are emitted when the navigation-drawer changes
Preventing the navigation-drawer to emit resize event when clicking af hovering components in the navigation-drawer. 
I have a solution with a Mapbox map and a navigation drawer with a button to fit the map.
When clicking the button, the map should zoom out with an animation, but the animation stops because the navigation-drawer is emitting a resize event.
This PR ensures that resize event only are emitted when the navigation-drawer changes.
visually
<details>
```vue
<template>
<v-app>
<v-navigation-drawer app>
<v-btn @click="fitMap">Fit …
```
> Fix navigation drawer resize events

- src/stylus/components/_progress-circular.styl
Added the vertical alignment : middle property to the icon so that it will align itself properly. 
fixes #4285.
Credits : @jacekkarczmarczyk
Source of inspiration: https://codepen.io/anon/pen/ERvjEE
> fix(VProgressCircular): added vertical alignment

- src/components/VSelect/VSelect.js
Makes easier to simulate clicking outside programmatically. Also calling onKeyDown in the handler was useless
manually
<details>
```vue
<template>
<v-container>
<v-btn @click="click">Click and wait for it...</v-btn>
<v-select :items="['foo']" ref="ref" />
</v-container>
</v-app>
</template>
<script>
methods: {
click () {
const ref = this.$refs.ref
setTimeout(() => {
ref.onClick()
ref.focus()
setTimeout(ref.onClickOutside, 1000)
});
}
}
}
</script>
```
</details>
> fix(VSelect): override v-text-field's blur method

- src/components/VTabs/VTabs.js
- src/components/VTabs/mixins/tabs-computed.js
- test/unit/components/VTabs/VTabs.spec.js
v-tabs should now update v-model if swiping on v-tab
closes #4402
manually with markup
added one test
<details>
```vue
<template>
<v-app>
<v-container>
<v-layout align-center justify-center>
<v-flex xs12 sm6>
<br>
V-model: {{ active }}
<br>
<v-tabs
color="cyan"
dark
slider-color="yellow"
>
<v-tab
v-for="n in 3"
:key="n"
ripple
>
Item {{ n }}
</v-tab>
<v-tab-item
v-for="n in 3"
:key="n"
>
<v-card flat>
</v-card>
</v-tab-item>
</v-tabs>
<v-tabs
v-model="active"
color="cyan"
dark
slider-color="yellow"
>
<v-tab
v-for="n in 3"
:key="n"
ripple
>
Item {{ n }}
</v-tab>
<v-tab-item
v-for="n in 3"
:key="n"
>
<v-card flat>
</v-card>
</v-tab-item>
</v-tabs>
<v-tabs
v-model="active"
color="cyan"
dark
slider-color="yellow"
> …
```
> fix: v-tabs should now update v-model if swiping on v-tab

- src/locale/ru.js
> feat: add russian locale

- src/components/VSelect/VSelect.js
- test/unit/components/VSelect/VSelect.spec.js
Not sure if initialValue is used for anything other than change detection. 
fixes #4481
<details>
```vue
<template>
<v-app>
<v-container>
<v-select
autocomplete
:items="employees"
item-text="compoundName"
label="Employees"
required
return-object
@change="onEmployeeChange"
></v-select>
</v-container>
</v-app>
</template>
<script>
data: () => ({
employee: null,
employees: [
{
compoundName: '1: Guy1',
id: '1'
},
{
compoundName: '2: Guy2',
id: '2'
}
],
orders: [
{
compoundName: "Order1"
},
{
compoundName: 'Order2'
}
]
}),
methods: {
onEmployeeChange (event) {
console.log('onEmployeeChange', event)
}
}
}
</script>
```
</details>
> fix(VSelect): prevent emitting change again on blur

- src/components/VTextField/VTextField.js
- src/stylus/components/_text-fields.styl
- test/unit/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
- test/unit/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
Fixes `genMessages` for `v-text-field` and resolves some spacing for the inner icon for `v-autocomplete`
Inside the `genMessages` function for `VTextField.js` we were missing a check to return null if `hideDetails` was true. Also changed some css to account for `single-line` prop. The enclosed drop down icon for `autocomplete` was spaced wrong
There is an example on the docs that these issues were causing to look weird. Doc example found here: https://vuetifyjs.com/en/components/text-fields#example-full-width-with-character-counter
unit
<details>
```vue
<template>
<boilerplate>
<v-card>
<v-toolbar
card
color="pink"
dark
>
<v-icon>arrow_back</v-icon>
<v-toolbar-title>Compose</v-toolbar-title>
<v-icon>send</v-icon>
</v-toolbar>
<v-form> …
```
> Fix Weird Text Field Spacing

- build/config.js
cssnano minifies the keyframes names so they conflict with other reduced keyframes from other libs
fixes #4563
related to #1141
related to #4143
> fix: don't reduce animation keyframes

- src/components/VForm/VForm.js
- test/unit/components/VForm/VForm.spec.js
Restores the ability to work directly with input components in a v-form through `$refs.inputs` by registering the entire instance.
In 1.0 you could access the input components in a v-form through `$refs.form.inputs`. This is not possible in 1.1 and has created problems for people using the inputs array for more complex validation features such as focusing on or scrolling to invalid inputs, or getting all validation errors from a form (#4573).
manually
<details>
```vue
<template>
<v-app>
<v-form ref="form" v-model="valid" lazy-validation>
<v-text-field
v-model="name"
:counter="10"
label="Name"
required
<v-text-field
v-if="show"
:rules="emailRules"
label="E-mail"
required
<v-select
:items="items" …
```
> fix(v-form): restore ability to work with inputs through $refs

- src/stylus/components/_dividers.styl
- src/stylus/components/_text-fields.styl
fixes #3847
fixes #3588
fixes #3090
Currently all thin lines in Vuetify components look inconsistent and confusing (depends on the page zoom and element position on the page):
- Some lines are rendered too thick
- Some lines become invisible
The problem occurs because of approximation in rendering which becomes noticable for thin elements (e.g. `v-divider`, `v-divider vertical`, `v-select`, `v-input-field`)
There's currently only 1 solution to this problem - to use borders as lines.
It fixes the problem on all Chromium and Firefox browsers (and possibly on Safari, haven't tested).
Visually:
**Codepen example:** https://codepen.io/anon/pen/yqYdbB?editors=1100
- Open the link
- Change the page zoom around (50% - 200%) to notice the problem with lines (some will dissapear, some will become …
> fix: thin lines are rendered inconsistently

- src/mixins/validatable.js
fixes #4635
visually
<details>
```vue
<template>
<v-app>
<v-content>
<v-container>
<v-text-field v-model="a" :rules="validation" />
<v-text-field v-model="errorMessage" />
</v-container>
</v-content>
</v-app>
</template>
<script>
data: () => ({
a: '',
errorMessage: 'error',
}),
computed: {
validation () {
return [(message => v => !v || message)(this.errorMessage)]
}
}
}
</script>
```
</details>
Don't know how to reproduce the issue from the removed comment
> fix(validatable): revalidate on rules change

- src/components/VAutocomplete/VAutocomplete.js
- src/components/VSelect/VSelect.js
- test/unit/components/VAutocomplete/VAutocomplete.spec.js
- test/unit/components/VSelect/VSelect2.spec.js
- test/unit/components/VSelect/VSelect3.spec.js
fixes #4431
Clearable still needs work, if you clear the select it'll revert to `null` and select the first item again. 
~~No idea what those original checks were there for, it seems to work fine and tests still pass.~~
The `internalValue === ''` check was for #4032, but that's a separate component now and doesn't seem to have regressed. 
<details>
```vue
<template>
<v-app>
<v-container>
:items="items"
clearable
<pre>{{ JSON.stringify(selected) }}</pre>
</v-container>
</v-app>
</template>
<script>
data: () => ({
selected: null,
items: [
{ text: 'all of them', value: null },
{ text: 'fizz', value: 'Fizz' },
{ text: 'buzz', value: 'Buzz' },
{ text: 'foo', value: 'Foo' }
]
})
}
</script>
```
</details>
> fix(VSelect): allow null values to be selected

- src/util/helpers.ts
- test/unit/util/helpers.spec.js
Add Date comparison in deepEqual function in helper.
`deepEqual` function can't compare `Date`. When `Date` are use as values in `v-radio`, all radio are selected when user check one.It's because comparison between selected value and radio value return true every time.
Fixes #4637 
test visually and unit test
<details>
```vue
<template>
<v-container fluid px-0>
<v-radio-group v-model="radioGroup">
<v-radio label="one"
:value="dates.one"
></v-radio>
<v-radio label="two"
:value="dates.two"
></v-radio>
<v-radio label="three"
:value="dates.three"
></v-radio>
</v-container>
</template>
<script>
data () {
return {
radioGroup: 'default date',
}
},
computed: {
dates () {
return {
one: new Date(),
two: new Date(1000),
three: new Date(2000)
}
}
}
}
</script>
``` …
> Fix deepEqual helper - Enable Date values for v-radio

- src/stylus/components/_navigation-drawer.styl
- src/stylus/components/_steppers.styl
The default divider uses `border-color` to set its color.
So, navigation drawer and stepper should overwrite the divider `border-color`, not its `background`.
Different divider colors on navigation drawer and stepper.
none
All `<v-divider>` should have the same color in the codepen markup below:
Light theme: https://codepen.io/anon/pen/KBvwqN?&editors=101
Dark theme: https://codepen.io/anon/pen/BPdydN?&editors=101
> Fix divider color on navigation drawer and steppers

- src/components/VForm/VForm.js
- src/mixins/validatable.js
resolves #3316
<details>
```vue
<template>
<v-app>
<v-container>
<v-form v-model="valid" ref="form" lazy-validation>
<v-text-field v-model="text" :rules="[long]"/>
<v-layout>
<v-btn @click="reset">reset</v-btn>
<v-btn @click="customReset">custom reset</v-btn>
<v-btn @click="resetValidation">reset validation</v-btn>
</v-layout>
</v-form>
<pre>{{ valid }}</pre>
</v-container>
</v-app>
</template>
<script>
data: () => ({
valid: true,
text: '',
long: v => v.length > 5 || 'must be >5 characters'
}),
methods: {
reset () {
// This will error, the rule doesn't account for null
this.$refs.form.reset()
},
customReset () {
this.text = ''
this.$refs.form.resetValidation()
},
resetValidation () {
this.$refs.form.resetValidation()
}
}
}
</script>
```
</details>
> feat(VForm): add public resetValidation method

- src/stylus/components/_inputs.styl
- src/stylus/components/_selection-controls.styl
- src/stylus/components/_sliders.styl
- src/stylus/components/_text-fields.styl
- src/stylus/settings/_variables.styl
Fixes #4787 
<details>
```vue
<template>
<v-app>
<div class="line-helper" style="top: 44px"></div> 
<div class="line-helper" style="top: 65px"></div> 
<div class="line-helper" style="top: 76px"></div> 
<div class="line-helper" style="top: 96px"></div> 
<v-container grid-list-md>
<v-layout>
<v-flex shrink>
<v-radio-group label="label" hint="hint" persistent-hint>
<v-radio label="label"></v-radio>
</v-flex>
<v-flex shrink>
<v-text-field label="label" hint="hint" persistent-hint></v-text-field>
</v-flex>
<v-flex shrink>
<v-text-field label="label" hint="hint" persistent-hint></v-text-field>
</v-flex>
<v-flex shrink>
<v-checkbox label="label" hint="hint" persistent-hint></v-checkbox>
</v-flex>
<v-flex shrink>
<v-slider label="label" hint="hint" persistent-hint></v-slider> …
```
> fix(inputs): tweak vertical alignment

- src/components/VDatePicker/VDatePickerTitle.js
- src/components/VTimePicker/VTimePicker.js
- src/components/VTimePicker/VTimePickerClock.js
- src/components/VTimePicker/VTimePickerTitle.js
- src/mixins/picker-button.js
- src/stylus/components/_pickers.styl
- test/unit/components/VDatePicker/__snapshots__/VDatePicker.date.spec.js.snap
- test/unit/components/VDatePicker/__snapshots__/VDatePicker.month.spec.js.snap
- test/unit/components/VDatePicker/__snapshots__/VDatePickerTitle.spec.js.snap
- test/unit/components/VTimePicker/VTimePickerClock.spec.js
- test/unit/components/VTimePicker/VTimePickerTitle.spec.js
- test/unit/components/VTimePicker/__snapshots__/VTimePicker.spec.js.snap
- test/unit/components/VTimePicker/__snapshots__/VTimePickerTitle.spec.js.snap
Add `readonly` prop to **VTimePicker**
fixes #3715
<details>
```vue
<template>
<v-app>
<v-content class="pa-5">
<v-time-picker readonly v-model="time"></v-time-picker>
<v-time-picker v-model="time"></v-time-picker>
</v-content>
</v-app>
</template>
<script>
data: () => ({ time: '12:17' })
}
</script>
```
</details>
> feat(VTimePicker): readonly prop

- src/components/VStepper/VStepperContent.js
- test/unit/components/VStepper/VStepperContent.spec.js
Fixed a desync issue with the visibility of `v-stepper-content`.
Added a test for `this.isActive` before setting `this.height` in a `setTimeout`-called function.
The issue occurs when toggling the visibility (via `toggle`) faster than the `setTimeout`'s 450ms.
yes, i also added an additional test that fails w/o the fix
<details>
```vue
<template>
<v-app class="ma-4">
<v-stepper v-model="step" vertical>
<template v-for="i of steps">
<v-stepper-step :complete="step > i" :step="i">
Step {{i}}
<v-stepper-content :step="i">
Some text
</v-stepper-content>
</template>
</v-stepper>
</v-app>
</template>
<script>
data () {
return {
step: 0,
steps: 3,
}
},
async mounted() {
this.step = 1;
await new Promise(resolve => setTimeout(resolve, 100));
this.step = 2;
}
} …
```
> fix(v-stepper-content): visibility desync

- src/mixins/data-iterable.js
Added a scoped slot for adding additional things to the data table's actions footer.
It allows for more customisability. Currently, to add anything to the actions footer one needs to remake whole table's footer.
Visually
<details>
```vue
<template>
<v-data-table
hide-actions
>
<td class="text-xs-right">{{ props.item.iron }}</td>
</template>
<template slot="actions-extras">
<v-btn color="green">New</v-btn>
</template>
</template> …
```
> Allow for more customisability - New slot for the VDataTable

- src/components/VMenu/VMenu.js
- src/components/VMenu/mixins/menu-keyable.js
- src/components/VSelect/VSelect.js
- src/stylus/components/_autocompletes.styl
- src/stylus/components/_overflow-buttons.styl
- src/stylus/components/_select.styl
- test/unit/components/VCombobox/VCombobox-multiple.spec.js
- test/unit/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
- test/unit/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
- test/unit/components/VOverflowBtn/__snapshots__/VOverflowBtn.spec.js.snap
- test/unit/components/VSelect/VSelect2.spec.js
- test/unit/components/VSelect/__snapshots__/VSelect.spec.js.snap
- test/unit/components/VSelect/__snapshots__/VSelect2.spec.js.snap
The new theme propagation causes icons in the activator slot to be the wrong colour if `menu-props="light"` is used. 
<details>
```vue
<template>
<v-app dark>
<v-container>
<v-select v-bind="{ items }"></v-select>
<v-combobox v-bind="{ items }"></v-combobox>
<v-autocomplete v-bind="{ items }" menu-props="light"></v-autocomplete>
</v-container>
</v-app>
</template>
<script>
data: () => ({
items: ['a', 'b', 'c']
})
}
</script>
```
</details>
<details>
```vue
<template>
<v-app>
<v-flex xs12>
<v-select
v-bind="{
chips: true,
deletableChips: true,
items: ['foo'],
value: 'foo'
}"
/>
<v-radio-group row v-model="selectedStyle">
<v-radio
v-for="type in inputStyles"
:value="type"
:key="type"
:label="type || 'default'"
/> …
```
>  refactor(VSelect): remove menu activator slot

- src/components/VList/VListTileAction.js
- test/unit/components/VList/VListTileAction.spec.js
- test/unit/components/VList/__snapshots__/VListTileAction.spec.js.snap
Fixes #4114 
unit ( snapshot)
<details>
```vue
<template>
<v-list two-line>
<v-list-tile>
<v-list-tile-title>some title</v-list-tile-title>
<v-list-tile-action>
<v-list-tile-action-text>Something</v-list-tile-action-text>
<v-btn v-if="true">a</v-btn>
<v-btn v-if="false">b</v-btn>
</v-list-tile-action>
</v-list-tile>
</v-list>
<v-list two-line>
<v-list-tile>
<v-list-tile-title>some title</v-list-tile-title>
<v-list-tile-action>
<v-btn v-if="true">a</v-btn>
<v-btn v-if="false">b</v-btn>
</v-list-tile-action>
</v-list-tile>
</v-list>
<v-list two-line>
<v-list-tile>
<v-list-tile-title>some title</v-list-tile-title>
<v-list-tile-action> …
```
> Filter comments to count actual rendered elements

- src/stylus/components/_selection-controls.styl
Expanded the height and width of the html input box to 100% of the parent div and added a mouse pointer to the label/checkbox in order to handle when no ripple is present
Fixes #4696 
Visually
<details>
```vue
<template>
<v-app>
<div>
<v-checkbox
hide-details
:ripple="false"
label="No Ripple"/>
</div>
<div>
<v-checkbox
hide-details
label="Ripple"/>
</div>
</v-app>
</template>
<script>
data: () => ({
})
}
</script>
```
</details>
> Fix #4696: Checkbox is hard to click with ripple disabled

- src/components/VProgressCircular/VProgressCircular.ts
- src/components/VProgressLinear/VProgressLinear.ts
- test/unit/components/VBtn/__snapshots__/VBtn.spec.js.snap
- test/unit/components/VProgressCircular/VProgressCircular.spec.js
- test/unit/components/VProgressCircular/__snapshots__/VProgressCircular.spec.js.snap
- test/unit/components/VProgressLinear/VProgressLinear.spec.js
- test/unit/components/VProgressLinear/__snapshots__/VProgressLinear.spec.js.snap
- test/unit/components/VTextField/__snapshots__/VTextField.spec.js.snap
Added role, aria-valuemin, valuemax and valuenow (if not indeterminate) to progressbars - https://w3c.github.io/aria/#progressbar
Also normalized value (and buffervalue for linear) input (in Circular it was Number|String with min 0 max 100) in Linear it was just Number without minmax
Increase a11y, normalize properties between similar components
existing unit + playground with NVDA screenreader
<details>
```vue
<template>
<v-app>
<br/>
<h2>Linear with number and string</h2>
:value=50
></v-progress-linear>
value=50
></v-progress-linear>
<br/>
<h2>Circular with number and string</h2>
<v-progress-circular
:value=75
></v-progress-circular>
<v-progress-circular
value="75"
></v-progress-circular>
<br/>
<h2>indeterminate</h2>
indeterminate …
```
> feat(VProgress): normalized value and buffer, add a11y

- src/components/VBtn/VBtn.ts
- src/directives/ripple.ts
- src/globals.d.ts
- src/mixins/routable.ts
- src/stylus/components/_ripples.styl
- src/stylus/components/_selection-controls.styl
- src/stylus/settings/_variables.styl
Updated ripple effect to hopefully more closely resemble material design ripple.
I was unable to find a good single solution for both rectangular and circular ripples, so I've added a `circle` option to the ripple directive. Someone smarter than me might have a better solution?
because (also fixes #5021)
with provided markup
```vue
<template>
<v-container fluid fill-height>
<v-layout column wrap fill-height align-center justify-center>
<v-flex class="d-flex no-grow align-center">
<v-card class="ma-3" ripple height="132px" width="232px"></v-card>
<v-card :ripple="{ circle: true, center: true }" height="200px" width="200px" class="ma-3 border"></v-card>
<v-btn color="purple" flat>baseline</v-btn>
<v-btn>hello</v-btn>
<v-btn icon large>
<v-icon>home</v-icon>
</v-btn> …
```
> refactor: ripple should more closely resemble MD spec

- src/stylus/components/_date-picker-title.styl
Before
After
It's ugly.
Visually.
> fix(DatePicker): Title spacing when month === August

- src/components/VTreeview/VTreeview.ts
- test/unit/components/VTreeview/VTreeview.spec.js
switched caches from array to set
cleaner code and potential performance improvement
tests, visually
<details>
```vue
<template>
<v-app>
<v-content>
<v-container fluid grid-list-xl>
<v-flex xs6>
Default
<v-treeview :items="items"></v-treeview>
</v-flex>
<v-flex xs6>
Selectable
<v-treeview :items="items" selectable :selected.sync="selected"></v-treeview>
</v-flex>
<v-flex xs6>
Transition
<v-treeview :items="items" transition></v-treeview>
</v-flex>
<v-flex xs6>
Slots prepend & append
<v-treeview :items="items">
<v-icon slot="prepend" slot-scope="props">{{ props.item.icon }}</v-icon>
<div class="d-flex grow justify-end" slot="append" slot-scope="props">
<v-btn class="shrink" v-if="props.active" small icon @click.stop="remove(items, props.item.id)">
<v-icon …
```
> enh/v-treeview: switched from array to set for caches

- src/components/VNavigationDrawer/VNavigationDrawer.js
Pulls in the dependent mixin for the `click-outside` directive, this will include all of the dependent children (in this case `v-dialog`) and ensure those are closed first.
@johnleider I've tested this with multiple use-cases (mobile, nested navigation-drawers, drawers inside dialogs etc.) and I don't see a difference in z-index regarding `v-navigation-drawer`. as I understand it the `include` in the `click-outside` directive will just track the children and ensures those are closed first (just like in nested dialogs).
https://github.com/vuetifyjs/vuetify/issues/5089
visually, inspect element and logging
<details>
```vue
<template>
<v-navigation-drawer app temporary :value="drawer">
<v-dialog v-model="dialog" width="500">
<v-btn slot="activator" color="red lighten-2" …
```
> fix(v-navigation-drawer): pull in Dependent mixin for click-outside

- src/mixins/dependent.ts
Convert `dependent` mixin to TS. Not entirely sure about how to handle this https://github.com/vuetifyjs/vuetify/pull/5105/files#diff-f2a871db5433a55bc434c6526c30edecR16 , looking for feedback
Update framework to TS
jest
> feat(dependent): convert to ts

- src/components/VAutocomplete/VAutocomplete.js
- test/unit/components/VAutocomplete/VAutocomplete.spec.js
This will change the default behaviour of opening the menu every time the source items change, to only opening when the `hide-no-data` has been enabled, and the previous `items` was empty. 
Adds `hide-no-data` prop as a condition for opening the menu when the source items have changed (along with focus, the menu being closed already, and the old result set being empty)
This fixes the issue of the menu opening at undesired times due to non-asynchronous manipulation of the source items.  Fixes #4663 
I've added unit tests to cover the changes
<details>
```vue
<template>
<p>Issue is when combo has focus after selecting item 2, and then button is pressed</p>
<li>menu should not re-open</li>
<li>menu will not close when selecting item</li>
<br />
<v-btn @click=updateItems>Update Items</v-btn> …
```
> V-Autocomplete: hide-no-data also controls opening menu upon item update

- src/stylus/components/_pagination.styl
When props:length is a very large number,
the number of the button protrudes.
So set the `min-width: 34px` in class `.v-pagination__item`.
And set `padding` as style fine adjustment.
fixes #5126 
visually and inspect element
<details>
```vue
<template>
<v-app>
<v-pagination :length="100000000" :total-visible="6" :value="999999" />
</v-app>
</template>
<script>
data: () => ({
})
}
</script>
```
</details>
> style(v-pagination): button cutting the page number

- src/components/VDataTable/VEditDialog.js
- src/components/VDialog/VDialog.js
- src/components/VMenu/VMenu.js
- src/components/VMenu/mixins/menu-generators.js
- src/globals.d.ts
- src/mixins/themeable.ts
- src/util/ThemeProvider.ts
- test/unit/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
- test/unit/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
- test/unit/components/VMenu/__snapshots__/VMenu.spec.js.snap
fixes #5127
alternative to #5150 
Also DRYed up ThemeProvider when inheriting from root
<details>
```vue
<template>
<v-app v-bind="{ dark }">
<v-toolbar app dark color="primary">
<v-menu>
<v-btn slot="activator">menu - root</v-btn>
<v-list>
<v-list-tile>
<v-list-tile-title>list - {{ dark ? 'dark' : 'light' }}</v-list-tile-title>
</v-list-tile>
</v-list>
</v-menu>
<v-menu light>
<v-btn slot="activator">menu - light</v-btn>
<v-list>
<v-list-tile>
<v-list-tile-title>list - light</v-list-tile-title>
</v-list-tile>
</v-list>
</v-menu>
<v-menu dark>
<v-btn slot="activator">menu - dark</v-btn>
<v-list>
<v-list-tile>
<v-list-tile-title>list - dark</v-list-tile-title>
</v-list-tile>
</v-list>
</v-menu>
<v-divider vertical></v-divider>
<v-dialog>
<v-btn slot="activator">dialog - root</v-btn> …
```
> fix(VEditDialog): apply theme classes to content

- src/stylus/components/_selection-controls.styl
hopefully removes instances where click targets overlap between adjacent inputs. keep in mind that click target is still larger than actual input to account for mobile users.
closes #2661
visually in playground
<details>
```vue
<template>
<v-app>
<v-container>
<v-layout>
<v-checkbox
:label="`Checkbox 1: ${checkbox.toString()}`"
v-model="checkbox"
></v-checkbox>
<v-radio-group v-model="radioGroup">
<v-radio
v-for="n in 3"
:key="n"
:label="`Radio ${n}`"
:value="n"
></v-radio>
<v-switch
:label="`Switch 1: ${switch1.toString()}`"
v-model="switch1"
></v-switch>
</v-layout>
</v-container>
</v-app>
</template>
<script>
data () {
return {
checkbox: true,
radioGroup: 1,
switch1: true
}
}
}
</script>
```
</details>
> fix(v-ripple): decrease click target size on selection control ripple

- src/directives/ripple.ts
solves problems when using for example position sticky
closes #2573
visually, playground
<details>
```vue
<template>
<v-content>
<v-card ripple hover style="width:300px;margin:20px">
<v-card-title>
<div class="headline">awesome title</div>
<v-card-text>
blueberry muffins are amazing!!!!
</v-card-text>
</v-card>
<v-card ripple hover style="width:300px;margin:20px;position:static">
<v-card-title>
<div class="headline">awesome title</div>
<v-card-text>
blueberry muffins are amazing!!!!
</v-card-text>
</v-card>
<v-card ripple hover style="width:300px;margin:20px" class="static">
<v-card-title>
<div class="headline">awesome title</div>
<v-card-text>
blueberry muffins are amazing!!!!
</v-card-text>
</v-card>
<v-card ripple …
```
> fix(v-ripple): only modify position if current one is static

- src/components/VRating/VRating.ts
- test/unit/components/VRating/VRating.spec.js
Firefox always seem to return 0 for offsetX in mousemove event.
Fixes #5240
playground and tests
<details>
```vue
<template>
<div class="text-xs-center">
<v-rating v-model="rating" half-increments hover></v-rating>
</div>
</v-app>
</template>
<script>
data: () => ({
rating: 3
})
}
</script>
```
</details>
> fix(v-rating): switched from using offsetX to calculate half-increments

- src/components/VTimePicker/VTimePicker.js
- test/unit/components/VTimePicker/VTimePicker.spec.js
I have enhanced the check on setInputData to also validate for empty strings instead of only null values.
Otherwise, if empty string provided as value, it produces NaN:NaN
Changed the line, tested it - it fixed the issues. Now it will be treated as null value (--:--)
<details>
```vue
<template>
<div>
<v-checkbox v-model="landscape" label="Landscape"></v-checkbox>
<v-time-picker v-model="picker" :landscape="landscape"></v-time-picker>
</div>
</template>
<script>
data () {
return {
picker: '',
landscape: false
}
}
}
</script>
```
</details>
> time picker bugfix for empty string

- src/stylus/components/_timeline.styl
This fixes a css bug when using v-card in the opposite slot, which makes the indication arrow point in the wrong direction.
[https://codepen.io/jvanst/pen/zmJgao](https://codepen.io/jvanst/pen/zmJgao)
This change is required because its incredibly annoying and only a minor style change is needed.
I have visually tested this change by creating a playground with v-timeline.
<details>
```vue
<v-container>
<v-timeline>
<v-timeline-item>
<span slot="opposite">
<v-card height="200">
</v-card>
</span>
<v-card height="200">
</v-card>
</v-timeline>
</v-container>
```
</details>
> Fix v-timeline, opposite slot css bug

- src/stylus/components/_sliders.styl
The PR solves the issue with the click on the prepend icon when the v-slider is set to `readonly`. I had to move the CSS property `pointer-events: none` from `.v-input--slider.v-input--is-readonly` to `.v-input--slider.v-input--is-readonly .v-input__control`
Fixes #5389 
Manually in the local development environment.
> Fix v-slider readonly bug

- src/stylus/components/_data-table.styl
Fix data table sort icon not working when using font awesome 5 as default icon font.
Fixes #3548
> fix data table sort icon not working when using font awesome 5

- src/components/VPagination/VPagination.ts
- test/unit/components/VPagination/__snapshots__/VPagination.spec.js.snap
Currently `v-pagination`'s buttons acts like submit buttons, so it's not possible to use `v-pagination` inside a form.  
Fix #5212 
Tested locally with webpack
> Fix: VPagination acts as submit in forms (#5212)

- src/stylus/components/_pagination.styl
The current styles for `.v-pagination__item` are using `display: inline-flex` to centre the button text, which is actually unnecessary since button text is inheriting `text-align: center`. I removed the offending code and it seems to be rendering proper now on all devices.
Fixes #5016
Tested visually using BrowserStack
> Fix: Centres pagination button text on iOS 9.3.5

- packages/vuetify/src/stylus/components/_radio-group.styl
fixes #5455
visually
<details>
```vue
<template>
<v-radio-group v-model="radios" row label="foo (row)">
<v-radio value="Google" label="bar" />
<v-radio-group v-model="radios" label="foo (column)">
<v-radio value="Google" label="bar" />
</v-container>
</v-app>
</template>
```
</details>
> fix(VRadioGroup): main label spacing

- packages/api-generator/src/map.js
Added Pagination Props as an example in the dataIterable Props Array, so it gets added as example in to both the v-data-table and the v-data-iterable doc pages.
This answers a frequent questions seen on the Discord channel. Such as:
* How do I change sort direction by default?
* How do I sort by a specific column?
* How do I set the Rows Per Page by default?
* How do I set/change the page the component is on?
Resolves https://github.com/vuetifyjs/vuetifyjs.com/issues/503
> Added Pagination Props as example

- packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
- packages/vuetify/test/unit/components/VTreeview/VTreeview.spec.js
- packages/vuetify/test/unit/components/VTreeview/__snapshots__/VTreeview.spec.js.snap
changed logic for rendering expand icon to only show when children has items, or load-children prop is used
fixes #5357
playground and tests
<details>
```vue
<template>
<v-app>
<v-content>
<v-container>
<v-treeview :items="items"></v-treeview>
<v-treeview :items="items" :load-children="fn"></v-treeview>
</v-container>
</v-content>
</v-app>
</template>
<script>
methods: {
fn() {}
},
data: () => ({
items: [
{
'id': 1,
'name': 'root',
children: [
{
id: 2,
'name': 'child',
'children' : []
},
{
id: 3,
'name': 'child',
}
]
}
]
})
}
</script>
```
</details>
> fix(v-treeview): empty children expand icon

- packages/vuetify/src/components/VSelect/VSelect.js
fixes #5568
Markup works without the fix, but this is because the `.application` gets the `data-v` attribute. If `<v-select>` is in another .vue file then then `<v-select-list>` won't be a child of the component's root so this is where the fix starts working, but you can see the it gets the proper `data-v` attr
It would be better to add `data-v` to the `.v-menu__content` but I couldn't figure out the smart way of doing this
visually 
<details>
```vue
<template>
<v-app>
<v-container>
<v-select :items="['a']" />
</v-container>
</v-app>
</template>
<style scoped>
>>> .v-list__tile__title {
border: 4px solid red;
}
</style>
```
</details>
> fix(VSelect): add scopeId to VSelectList

- packages/vuetify/src/components/VDatePicker/VDatePicker.js
- packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.js
- packages/vuetify/src/stylus/components/_date-picker-table.styl
- packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePickerDateTable.spec.js.snap
- packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePickerMonthTable.spec.js.snap
- packages/vuetifyjs.com/src/examples/date-pickers/dateEvents.vue
- packages/vuetifyjs.com/src/examples/date-pickers/monthEvents.vue
- packages/vuetifyjs.com/src/lang/en/components/DatePickers.json
fixes #5501
visually, updated snaps
<details>
```vue
<template>
<v-app>
<v-content>
<v-date-picker value="2018-01-05" :events="eventsDateArray" :event-color="['red', 'blue']"></v-date-picker>
<v-date-picker type="month" value="2018-05" :events="eventsMonthArray" :event-color="['red', 'blue']"></v-date-picker>
<v-date-picker value="2018-01-05" :events="eventsDateObject"></v-date-picker>
<v-date-picker type="month" value="2018-05" :events="eventsMonthObject"></v-date-picker>
</v-content>
</v-app>
</template>
<script>
data: () => ({
eventsDateArray: ['2018-01-04', '2018-01-05', '2018-01-07'],
eventsMonthArray: ['2018-01', '2018-05', '2018-07'],
eventsDateObject: {'2018-01-03': false, '2018-01-04': true, '2018-01-05': 'red', '2018-01-07': ['blue', 'green', 'black']}, …
```
> feat(VDatePicker): multiple event indicators

- packages/vuetify/src/components/VWindow/VWindowItem.ts
- packages/vuetify/test/unit/components/VWindow/VWindowItem.spec.js
beforeLeave was causing issues, possibly due to some rendering black magic going on, not sure.
Window was scrolling to incorrect location when changing tabs.
fixes #5582
<details>
```vue
<template>
<div id="app">
<v-app>
<v-content>
<v-tabs
v-model="active1"
fixed-tabs>
<v-tab
ripple
>
First
</v-tab>
<v-tab
ripple
>
Second
</v-tab>
<v-tab-item
>
<v-container>
<v-card height="400px">
Next and previous buttons work correct
</v-card>
<v-btn color="indigo darken-3" outline @click="active1 = parseInt(1)">Next card</v-btn>
</v-container>
</v-tab-item>
<v-tab-item
>
<v-container>
<v-card height="400px">
</v-card>
<v-btn color="indigo darken-3" outline @click="active1 = parseInt(0)">Previous Card</v-btn>
</v-container>
</v-tab-item>
</v-tabs>
<v-tabs
v-model="active2" …
```
> fix(WindowItem): calculate height on leave

- packages/vuetify/src/stylus/components/_text-fields.styl
Use `$material.text.disabled` color for prefix and suffix in disabled VTextField
Fix #5481
visually
<details>
```vue
<template>
<v-text-field
disabled
prefix="P"
suffix="S"
label="Label"
value="Value"
</template>
<script>
export default {}
</script>
```
</details>
> Fix #5481: use correct color for prefix in disabled VTextField

- packages/vuetify/src/components/transitions/expand-transition.js
fixes #5607
also fixes an unreported bug caused by the use of `scrollHeight`, remove the inline style to see it
<details>
```vue
<template>
<v-app>
<v-container>
<v-img
:aspect-ratio="16/9"
src="https://cdn.vuetifyjs.com/images/cards/kitchen.png"
>
<v-expand-transition>
<div
v-if="show"
class="d-flex transition-fast-in-fast-out orange darken-2 v-card--reveal display-3 white--text"
style="height: 100%"
>
$14.99
</div>
</v-expand-transition>
</v-img>
<v-switch v-model="show"></v-switch>
</v-container>
</v-app>
</template>
<script>
data: () => ({
show: false
})
}
</script>
<style>
.v-card--reveal {
align-items: center;
bottom: 0;
justify-content: center;
opacity: .5;
position: absolute;
width: 100%;
}
</style>
```
</details>
> fix(expand-transition): use a proper FLIP animation w/ offsetHeight

- packages/vuetify/src/components/VDialog/VDialog.js
- packages/vuetify/src/mixins/overlayable.js
fixes #2201
<details>
```vue
<template>
<v-app>
<v-container>
<v-btn primary dark v-on:click.stop="dialog = true">Open Dialog</v-btn>
<pre>{{ dialog }}</pre>
<div style="height: 1000px"></div>
<v-dialog
:fullscreen="is_mobile"
:transition="is_mobile ? 'dialog-bottom-transition' : 'scale-transition'"
v-resize="onResize"
width="80%"
>
<v-card>
<v-toolbar dark class="primary">
<v-btn icon @click.native="dialog = false" dark>
</v-btn>
<v-toolbar-title>Settings</v-toolbar-title>
<v-btn dark flat @click.native="dialog = false">Save</v-btn>
</v-toolbar>
<v-card-title primary-title>
<div>
<h3 class="headline mb-0">Kangaroo Valley Safari</h3>
<div>Located two hours south of Sydney in the <br>Southern …
```
> fix(VDialog): add/remove overlay and scroll when fullscreen is changed

- packages/vuetify/src/components/VMenu/VMenu.js
- packages/vuetify/src/components/VMenu/mixins/menu-position.js
- packages/vuetify/src/mixins/menuable.js
- packages/vuetify/src/stylus/components/_menus.styl
adds dense prop to menu, fixes dense list item height and menu position when opened first time
fixes #5149
visually
<details>
```vue
<template>
<v-app>
<v-container>
<v-btn v-for="state in [null, 'Alabama', 'Missouri', 'Wyoming']" @click="e1 = state" :key="state || ''">{{ state || 'null' }}</v-btn>
<div style="height: 200px"></div>
<v-select :items="states" v-model="e1" menu-props="auto" label="select, auto, dense" dense></v-select>
<v-select :items="states" v-model="e1" menu-props="auto" label="select, auto, normal"></v-select>
<v-autocomplete :items="states" v-model="e1" menu-props="auto" label="autocomplete, auto, dense" dense></v-autocomplete>
<v-autocomplete :items="states" v-model="e1" menu-props="auto" label="autocomplete, auto, normal"></v-autocomplete>
<v-combobox :items="states" …
```
> fix(VMenu): auto positioning with dense prop

- packages/vuetify/src/components/VDatePicker/VDatePicker.js
- packages/vuetify/test/unit/components/VDatePicker/VDatePicker.date.spec.js
fixes #5663
visually, unit
<details>
```vue
<template>
<v-app>
<v-content>
<v-date-picker
v-model="date1"
<v-date-picker
v-model="date2"
<v-date-picker
v-model="date1"
:picker-date.sync="pickerDate"
<v-date-picker
v-model="date2"
:picker-date.sync="pickerDate"
</v-content>
</v-app>
</template>
<script>
data: () => ({
date1: null,
date2: '2015-05',
pickerDate: '2013-05'
})
}
</script>
```
</details>
> fix(VDatePicker): display proper year when model is null

- packages/vuetifyjs.com/src/lang/en/mixins/DataIterable.json
Use of before and after are mixed up for actions-prepend and actions-append slots for the Data Table.
> docs: correct affix position description

- packages/vuetify/src/components/VDatePicker/VDatePickerHeader.js
- packages/vuetify/src/stylus/components/_date-picker-header.styl
- packages/vuetify/test/unit/components/VDatePicker/VDatePicker.date.spec.js
- packages/vuetify/test/unit/components/VDatePicker/VDatePicker.month.spec.js
- packages/vuetify/test/unit/components/VDatePicker/VDatePickerHeader.spec.js
- packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePicker.date.spec.js.snap
- packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePicker.month.spec.js.snap
- packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePickerHeader.spec.js.snap
Makes only header text clickable instead of the whole header
fixes #5725
visually, updated units 
<details>
```vue
<template>
<v-content>
<v-container
<v-date-picker color="red" />
<v-date-picker readonly />
<v-date-picker color="red" readonly />
<v-date-picker disabled />
<v-date-picker color="red" disabled />
</v-container>
</v-content>
</v-app>
</template>
```
</details>
> fix(VDatePicker): change clickable area of month/year in header

- packages/vuetify/src/components/VBottomNav/VBottomNav.ts
- packages/vuetify/src/stylus/components/_bottom-navs.styl
- packages/vuetifyjs.com/src/examples/bottom-navigation/colorAndShift.vue
resolves #2685
Changed inactive styles for `v-btn` when used inside of `v-bottom-nav`. 
- Converted styles to match`v-tabs` spec
- https://material.io/archive/guidelines/components/tabs.html
- Added **Themeable** mixin. 
- User no longer has to explicitly define **dark** or **light** on `v-btn`. 
- Can now use `v-badge` when using the **shift** prop
There is no defined color on the spec pages for `v-bottom-nav`:
- https://material.io/design/components/bottom-navigation.html
- https://material.io/archive/guidelines/components/bottom-navigation.html
The current implementation doesn't closely resemble the pictures.
visually
<details>
```vue
<template>
<boilerplate>
<div id="app">
<v-card height="200px">
<div class="headline text-xs-center pa-5">Active: {{ e1 }}</div> …
```
> fix(VBottomNav): correct inactive colors

- packages/vuetify/src/mixins/menuable.js
It's possible for a mouseLeaveEvent to finish closing a menu before the corresponding mouseEnterEvent's animation frame has run, resulting in a stuck open menu. I have added some logic to double check at and make sure the menu is still active at the time the animation frame runs. 
In this situation, isActive has been reset to false between the time runDelay(open) was called and when we were provisioned this animation frame, sync up hasJustFocused to false and do a no-op assign to isContentActive which doesn't trigger the watcher. Tried to minimize branching to match project style.
This is a fix for https://github.com/vuetifyjs/vuetify/issues/5843, the issue is fully documented over there including related codepen.
I have tested the hover functionality of v-menu and v-tooltip, including …
> fix(VMenu): hover stuck open when mouse exits page

- packages/vuetify/src/components/VExpansionPanel/VExpansionPanelContent.ts
- packages/vuetify/test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanel.spec.js.snap
- packages/vuetify/test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanelContent.spec.js.snap
Add `aria-expanded` attribute when `VExpansionPanel` is expanded.
Fixes #5879.
jest
<details>
```vue
<template>
<v-app>
<v-expansion-panel>
<v-expansion-panel-content
v-for="(item,i) in 5"
:key="i"
>
<div slot="header">Item</div>
<v-card>
<v-card-text>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</v-card-text>
</v-card>
</v-expansion-panel-content>
</v-app>
</template>
<script>
data: () => ({
})
}
</script>
```
</details>
> refactor(VExpansionPanel): add `aria-expanded` attribute

- packages/vuetify/src/components/VParallax/VParallax.ts
- packages/vuetify/test/unit/components/VParallax/VParallax.spec.js
- packages/vuetify/test/unit/components/VParallax/__snapshots__/VParallax.spec.js.snap
Adds an empty alt tag to the `v-parallax` component if no alt tag is supplied.
`v-parallax` component does not come with an empty alt tag by default.
Providing an empty alt tag yourself is also not possible.
For example, if you have: `<v-parallax alt="" src="header.jpg" />` the resulting HTML will omit the alt tag completely.
Why this is necessary: (taken from reference 1)
```
Images with only visual value should have an empty alt attribute set on them.  Omitting the alt attribute makes most screen readers read out the entire image URL and providing an alt attribute when the image is for visual purposes only is just as useless.
```
References: 
- [https://davidwalsh.name/accessibility-tip-empty-alt-attributes](https://davidwalsh.name/accessibility-tip-empty-alt-attributes)
- …
> feat(VParallax): add alt tag by default

- packages/vuetify/src/components/VCombobox/VCombobox.js
There is method `onInternalSearchChanged` in `v-combobox`. If combobox has `multiple` prop, then this method may return earlier than method `updateMenuDimensions` is called. It is the reason for issue #5082. This pr change `onInternalSearchChanged` method, so now `updateMenuDimensions` will always be called.
Fix #5082
visually
<details>
```vue
<template>
<v-layout
class="wrapper"
align-end
>
<v-combobox
chips
multiple
:items="items"
/>
<v-spacer />
<v-combobox
chips
multiple
:items="items"
:delimiters="[',']"
/>
</v-layout>
</template>
<style scoped>
.wrapper {
height: 95vh;
}
</style>
<script>
data: () => ({
items: ['Gaming', 'Programming', 'Vue', 'Vuetify'],
model: ['Vuetify'],
}),
};
</script>
```
</details>
> fix(VCombobox): menu position may not update if multiple

- packages/vuetify/src/components/VMenu/VMenu.js
- packages/vuetify/src/components/VMenu/mixins/menu-keyable.js
- packages/vuetify/test/unit/components/VMenu/VMenu.spec.js
- packages/vuetifyjs.com/src/lang/en/components/Menus.json
Adds `disable-keys` prop to disable the keyboard event handlers used only when the `v-menu` is used as a real menu with selecting items by pressing up/down/enter etc
fixes #5103
visually, unit
<details>
```vue
<template>
<v-app>
<v-content>
<v-container>
<v-menu attach :close-on-content-click="false" :close-on-click="false" disable-keys>
<v-btn slot="activator">Open</v-btn>
<v-card class="pa-3" width="800">
<v-text-field label="Focus me and press TAB"></v-text-field>
<v-text-field></v-text-field>
</v-card>
</v-menu>
</v-container>
</v-content>
</v-app>
</template>
```
</details>
> feat(VMenu): disable-keys prop

- packages/vuetifyjs.com/src/lang/en/framework/ALaCarte.json
Skipping template since it's just a typo if that is OK.
> docs(ALaCarte) Typo correction "secnarios" -> "scenarios"

- packages/vuetifyjs.com/src/data/pages/framework/Icons.json
- packages/vuetifyjs.com/src/lang/en/framework/Icons.json
- packages/vuetifyjs.com/src/snippets/js/vuetify_custom_fa_svg_icons.txt
Setting icon weights with FA is incredibly easy, but not well documented.
* Add example of setting Font Awesome Pro icon weights using component icons.
* In keeping with the progressive nature of the Icons page, the example is added to the Component Icons section
* For brevity, I did not show advanced features of `vue-fontawesome`
Alternatively, we could add a new section below Component Icons specifically for Font Awesome Pro. This would allow going into more detail about using `faSvg` combined with `component` icons, including the use of additional `props` like `transform` and `mask`.
> docs(Icons): add new example

- packages/vuetify/src/components/VTreeview/VTreeview.ts
- packages/vuetify/test/unit/components/VTreeview/VTreeview.spec.js
- packages/vuetify/test/unit/components/VTreeview/__snapshots__/VTreeview.spec.js.snap
There was a bug when removing a child, and then adding another one,
where the internal state would keep the removed child and not trigger
a rebuild of tree since the number of nodes was still the same
fixes #5719
manually and added unit test
<details>
```vue
<template>
<v-app>
<v-btn @click="addNode($event)">Add to Applications</v-btn>
<v-btn @click="removeNode($event)">Remove from Applications</v-btn>
<v-treeview activatable :items="items"></v-treeview>
</v-app>
</template>
<script>
data: () => ({
items: [
{
id: 1,
name: 'Applications :',
children: [
{ id: 2, name: 'Calendar : app' },
{ id: 3, name: 'Chrome : app' },
{ id: 4, name: 'Webstorm : app' }
]
},
{
id: 5,
name: 'Documents :',
children: [
{
id: 6,
name: 'vuetify :',
children: [
{
id: 7,
name: 'src :',
children: [ …
```
> fix(VTreeview): bug when removing and adding children

- packages/vuetify/src/components/VTreeview/VTreeview.ts
- packages/vuetify/test/unit/components/VTreeview/VTreeview.spec.js
VTreeview tried to cast all item keys to numbers, which caused issues
when using a string such as 012 as a key.
fixes #5711
manually & unit tests
<details>
```vue
<template>
<v-app>
<v-treeview activatable :items="items" open-all></v-treeview>
<v-treeview selectable activatable :items="items2" open-all :active.sync="active"></v-treeview>
</v-app>
</template>
<script>
data: () => ({
active: [13],
items: [
{
id: "11",
name: "First",
},
{
//id: "12", works
id: "012", //does not work
name: 'Second',
children: [
{id: "013", name: "Third"}, // Ignored as this is a leaf node
{id: "014", name: "Fourth"}, // Ignored as this is a leaf node
{id: "015", name: "Fifth"} // Ignored as this is a leaf node
]
}
],
items2: [
{
id: 11,
name: "First",
},
{
//id: "12", works
id: 12, //does not …
```
> fix(VTreeview): open-all not working with some item keys

- packages/vuetify/src/components/VSelect/VSelect.js
- packages/vuetify/test/unit/components/VSelect/VSelect.spec.js
- packages/vuetify/test/unit/components/VSelect/VSelect3.spec.js
Don't emit change event when clicked on the selected item 
#6052
`jest`
<details>
```vue
<template>
<v-app>
<v-select
:items="types"
label="Types"
v-model="type"
@change="onchange"
hide-details
></v-select>
</v-app>
</template>
<script>
data: () => ({
types:["type1","type2","type3","type4"],
type:"type1"
}),
methods: {
onchange(){
alert(this.type)
}
}
}
</script>
```
</details>
> fix(VSelect): don't emit change event when clicked on the selected item 

- packages/vuetify/src/components/VAutocomplete/VAutocomplete.js
- packages/vuetify/src/components/VCombobox/VCombobox.js
- packages/vuetify/test/unit/components/VAutocomplete/VAutocomplete.spec.js
Modify `displayedItemsCount` method in VAutocomplete to work correctly with `hide-selected` prop. Previous code (`this.filteredItems.length - this.selectedItems.length`) didn't work if there exists selected item which doesn't match search. Now explicit check is used (thus helpers methods are added — `hasItem` and `selectedValues`).
Fix #4580
<details>
```vue
<template>
<v-app>
<div>
<div>Type <code>Cali</code> in VAutocomplete. Expect to see menu with one item (California)</div>
:items="states"
chips
multiple
hide-no-data
hide-selected
/>
</div>
</v-app>
</template>
<script>
data: () => ({
model: ['Alabama'],
states: [
'Alabama', 'Alaska', 'American Samoa', 'Arizona',
'Arkansas', 'California', 'Colorado', 'Connecticut', …
```
> fix(VAutocomplete): may not show menu with hide-selected

- packages/vuetify/src/components/VTimePicker/VTimePicker.ts
fixes #5951
visually
<details>
```vue
<template>
<v-content>
<v-container>
<v-subheader>#5266</v-subheader>
<v-time-picker v-model="time1" @input="input" @change="change"></v-time-picker>
<v-time-picker @input="input" @change="change"></v-time-picker>
<v-subheader>#5951</v-subheader>
<v-menu ref="menu" v-model="menu2" :close-on-content-click="false" offset-y>
<v-text-field slot="activator" v-model="time" label="Picker in menu" />
<v-time-picker v-if="menu2" v-model="time" @change="$refs.menu.save(time)" />
</v-menu>
</v-container>
</v-content>
</v-app>
</template>
<script>
data: () => ({
time1: null,
time: '14:14',
menu2: false,
}),
methods:{
input: time => console.log('input', time),
change: time => console.log('change', time),
}
}
</script>
``` …
> fix(VTimePicker): emit change event after clicking minutes/seconds

- packages/docs/src/examples/data-tables/expand.vue
- packages/docs/src/lang/en/components/DataTables.json
- packages/docs/src/lang/es-MX/components/DataTables.json
In the documentation for `data-table`, i modified the `expand` explanation and example.
* Add `expand` prop to the example. Users can toggle this prop.
* Rephrase text to make clearer the distinction between `expand` slot and `expand` prop.
Documentation for `v-data-table` includes an example for `expand` slot but not for `expand` prop. Also, both the slot and the prop have the same name which can be confusing. The explanation could be easier to understand if more **space** and context is added between both concepts.
This [codepen works](https://codepen.io/anon/pen/REmpLy?&editable=true&editors=101)
<details>
```vue
<template>
<div>
<v-toolbar flat color="white">
<v-toolbar-title>Expandable Table</v-toolbar-title>
<v-btn color="primary" dark @click="expand = …
```
> docs(VDataTable): improve expand documentation

- packages/vuetify/src/components/VTreeview/VTreeview.ts
- packages/vuetify/src/util/helpers.spec.js
- packages/vuetify/src/util/helpers.ts
- packages/vuetify/test/unit/components/VTreeview/VTreeview.spec.js
- packages/vuetify/test/unit/components/VTreeview/__snapshots__/VTreeview.spec.js.snap
the VTreeview component did not handle updating items prop with an array
of equal size as current array.
fixes #6181
unit tests and manual playground testing
<details>
```vue
<template>
<v-treeview
v-model="tree"
:open="open"
:items="items"
activatable
item-children="children"
open-on-click
>
</v-treeview>
<v-btn  @click="reload">Test</v-btn>
<v-btn @click="second">Second</v-btn>
<v-btn @click="third">Third</v-btn>
</v-app>
</template>
<script>
data: () => ({
open: ['public'],
tree: [],
items: [
{
name: 'one'
},
{
name: 'two'
}
]
}),
methods: {
reload () {
this.items = [
{
name: 'one'
}
]
},
second () {
this.items = [
{
name: 'one'
},
{
name: 'three'
}
]
},
third () {
this.items = [
{
name: 'four'
},
{
name: 'five'
}
]
}
}
}
</script> …
```
> fix(VTreeview): correcly handle updating items array of equal size

- packages/kitchen/src/views/Home.vue
Use `VAutocomplete` on the home page.
It's much more convenient to use with big component list:
> docs(kitchen): use VAutocomplete on the Home page

- packages/docs/src/pages/documentation/Page.vue
In server-side rendered html for documentation pages (like [`/buttons`](https://vuetifyjs.com/en/components/buttons)) both left and right navigation drawers are hidden and content is horizantolly centered and has `max-width: 1185px`. (It can be checked by disabling javascript). Here is screenshot:
But after ssr hydradation both navigation drawers become visible. Left navigation drawer has width `300px` and right has width `210px`. Because navigation drawers has different widths, after hydradation content is shifting a bit (up to `45px`). Here is screenshot:
This pr explicitly set horizontal padding for content to match padding after hydration.
A little smoother loading of the documentation.
> docs: prevent content shifting during loading (ssr hydration)

- packages/docs/src/lang/en/getting-started/Roadmap.json
The caption for the release of v1.5 incorrectly said "February 2018" instead of "February 2019".
Change the caption for the item "v1.5 Release" from "February 2018" to "February 2019"
The listed year was incorrect.
Just visually.
<details>
```vue
```
</details>
> Changed year in caption for v1.5 Release

- packages/docs/src/data/pages/framework/Scroll.json
- packages/docs/src/lang/en-US/framework/Scroll.json
- packages/docs/src/snippets/js/import_goto_router.txt
- packages/vuetify/src/components/Vuetify/goTo/index.ts
allows `goTo()` call instead of `this.$vuetify.goTo()`
Allows to use goTo in vue-router
playground
<details>
```vue
<template>
<v-app>
<v-toolbar app>Toolbar</v-toolbar>
<v-content>
<v-btn @click="goTo">Scroll</v-btn>
<div style="height: 3000px"></div>
<div id="target" style="height: 100px; border-top: 4px solid green; background: red"></div>
<div style="height: 3000px"></div>
</v-content>
</v-app>
</template>
<script>
import goTo from '../src/components/Vuetify/goTo'
methods: {
goTo () {
goTo('#target')
}
}
}
</script>
```
</details>
> fix(goTo): allow standalone call

- packages/api-generator/src/map.js
- packages/docs/src/examples/time-pickers/timeDialogAndMenu.vue
- packages/vuetify/src/components/VTimePicker/VTimePicker.ts
- packages/vuetify/test/unit/components/VTimePicker/VTimePicker.spec.js
Adds `click:hour`, `click:minute` and `click:second` events
fixes #6163
jest, visually
<details>
```vue
<template>
<v-app>
<v-content>
<v-menu v-model="menu" ref="menu" :close-on-content-click="false" :return-value.sync="time" offset-y max-width="290px" min-width="290px">
<v-text-field slot="activator" v-model="time" label="Picker in menu" readonly />
<v-time-picker v-if="menu" v-model="time" full-width @click:minute="$refs.menu.save(time)" />
</v-menu>
</v-content>
</v-app>
</template>
<script>
data: () => ({
menu: false,
time: '21:37'
})
}
</script>
```
</details>
> feat(VTimePicker): emit click:xxx events

- packages/vuetify/src/components/VAutocomplete/VAutocomplete.js
- packages/vuetify/src/components/VSelect/VSelectList.js
Search results with this fix:
"İ" - 'İstanbul', 'izmir'
"i" - 'İstanbul', 'izmir'
"ı" - 'ılgaz', 'Irak'
"I" - 'ılgaz', 'Irak'
fixes #4811
visually
For non-turkish browsers this PR can be verified by changing `toLocaleLowerCase()` to `toLocaleLowerCase('tr')`
<details>
```vue
<template>
<v-app>
<v-content>
<v-autocomplete box :items="['İstanbul', 'izmir', 'ılgaz', 'Irak']" />
</v-content>
</v-app>
</template>
```
</details>
> fix(VAutocomplete): use toLocaleLowerCase when filtering items

- packages/vuetify/src/components/VTooltip/VTooltip.js
- packages/vuetify/src/mixins/menuable.js
- packages/vuetify/test/unit/components/VMenu/VMenu.spec.js
- packages/vuetify/test/unit/components/VMenu/__snapshots__/VMenu.spec.js.snap
Moves watchers for `positionX` and `positionY` (added in #5967) from `VTooltip` to `menuable` mixin, so now position of `VMenu` can also be dynamically updated.
Fix #4956
visually
<details>
```vue
<template>
<v-app>
<v-layout align-center justify-center>
<v-flex xs4 text-xs-center>
<div>Click "Open menu". Then click "Change menu position".</div>
<v-btn @click="openMenu">Open menu</v-btn>
<v-btn @click="changePosition">Change menu position</v-btn>
<v-menu
absolute
:value="visible"
:position-x="x"
:position-y="100"
:close-on-click="false"
content-class="pa-2"
>
Menu position-x: {{ x }}
</v-menu>
</v-flex>
</v-layout>
</v-app>
</template>
<script>
data: () => ({
visible: false,
x: 100,
}),
methods: {
openMenu() {
this.visible = true;
},
changePosition() {
this.x += 100;
}, …
```
> fix(VMenu): Update position dynamically

- packages/vuetify/src/components/VDatePicker/VDatePickerHeader.ts
- packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePicker.date.spec.js.snap
- packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePicker.month.spec.js.snap
- packages/vuetify/test/unit/components/VDatePicker/__snapshots__/VDatePickerHeader.spec.js.snap
If a DatePicker is used within a form, a click on the month in the DatePicker header will cause an unwanted submit of the form. 
My change will correct this behavior.
I would like to create a form where the user can select a date.
I tested with the existing tests.
https://jsfiddle.net/jkd4rbo8/21/
> fix(VDatePicker): Unwanted form submission on header click.

- packages/docs/src/lang/en-US/components/Treeview.json
- packages/vuetify/src/components/VTreeview/VTreeview.ts
- packages/vuetify/test/unit/components/VTreeview/VTreeview.spec.js
Allows opening and closing of all nodes programatically
playground, jest
<details>
```vue
<template>
<v-app>
<v-container>
<v-btn @click="$refs.treeview.updateAll(true)">Open all</v-btn>
<v-btn @click="$refs.treeview.updateAll(false)">Close all</v-btn>
<v-treeview ref="treeview" :items="items" />
</v-container>
</v-app>
</template>
<script>
data: () => ({
items: [
{
id: 1,
name: 'Applications :',
children: [
{ id: 2, name: 'Calendar : app' },
{ id: 3, name: 'Chrome : app' },
{ id: 4, name: 'Webstorm : app' }
]
},
{
id: 5,
name: 'Documents :',
children: [
{
id: 6,
name: 'vuetify :',
children: [
{
id: 7,
name: 'src :',
children: [
{ id: 8, name: 'index : ts' },
{ id: 9, name: 'bootstrap : ts' }
]
}
]
},
{
id: 10,
name: 'material2 :',
children: [
{
id: 11,
name: 'src :', …
```
> feat(VTreeview): updateAll public method

- packages/vuetify/src/components/VTooltip/_variables.sass
- packages/vuetify/src/styles/base/_variables.scss
- packages/vuetify/src/stylus/components/_bottom-navs.styl
- packages/vuetify/src/stylus/components/_date-picker-table.styl
- packages/vuetify/src/stylus/components/_parallax.styl
- packages/vuetify/src/stylus/components/_pickers.styl
- packages/vuetify/src/stylus/components/_sliders.styl
- packages/vuetify/src/stylus/components/_time-picker-clock.styl
- packages/vuetify/src/stylus/components/_time-picker-title.styl
- packages/vuetify/src/stylus/elements/_code.styl
- packages/vuetify/src/stylus/settings/_theme.styl
- packages/vuetify/src/stylus/settings/_variables.styl
Use variables instead of hard-coded colors in styles
Fixes #6437
none
<details>
```vue
none
```
</details>
> refactor(styles): use variables instead of hard-coded colors

- packages/vuetify/src/directives/ripple.ts
- packages/vuetify/src/globals.d.ts
Always bind touch events, and skip the fake mouse events if ripple was triggered by a touch
fixes #6418
<details>
```vue
<template>
<v-app>
<v-container>
<v-card ripple>
<v-card-text>
ripple
</v-card-text>
</v-card>
</v-container>
</v-app>
</template>
```
</details>
> fix(v-ripple): skip mouse events if triggered by touch

- packages/vuetify/src/stylus/components/_dialogs.styl
When `flex: 1 1 0px` get's applied to a scrollable dialog it takes up the full width, so change it so it only gets applied to the form that's nested within a scrollable dialog
Fixes #6479 
visually
<details>
```vue
```
</details>
> Fix issue width get's ignored with scrollable dialogs

- packages/vuetify/src/directives/ripple.ts
Instead of assuming `element._ripple` won't be undefined/null (which it could be), verify that this is the case.
Deleting a `v-btn` on click results in a console error "Cannot set property 'touched' of undefined at ripple.ts:148". This occurs when the ripple directive's unbind() function is called before rippleHide()'s setTimeout finishes.
Steps to reproduce ([codepen](https://codepen.io/anon/pen/zeaJZp)):
1. Open browser devtools console
2. Click on the "delete me" button in the test page
3. Observe the error message in the console
visually (added the undefined guard manually to a vuetify build)
> fix(ripple): ensure _ripple data is not undefined

- packages/docs/src/lang/en/components/Cards.json
Removes v-card-media as mentioned in issue #6579.
Corrects a typo in the warning.
> Docs: Removes v-card-media + correctes a typo

- packages/vuetify/src/components/VCalendar/VCalendarWeekly.ts
- packages/vuetify/src/components/VCalendar/mixins/calendar-base.ts
- packages/vuetify/src/components/VCalendar/mixins/calendar-with-intervals.ts
- packages/vuetify/src/components/VCalendar/util/props.ts
use the global locale instead of defining it for every calendar component
see https://github.com/vuetifyjs/vuetify/pull/6320
it wasn't
> feat(VCalendar): use $vuetify.lang.current as default language

- packages/vuetify/src/directives/ripple.ts
The function window.getComputedStyle was returning null under certain conditions on Firefox before version 62, see https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle#Browser_compatibility.
JS Error on Firefox.
Bug only happens on old Firefox versions. Is this something you want to explicitly test?
> fix(ripple): allow getComputedStyle to return null

- packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.ts
- packages/vuetify/test/unit/components/VBreadcrumbs/VBreadcrumbs.spec.js
Allows breadcrumbs with identical texts
closes #5454
playground, test
<details>
```vue
<template>
<v-breadcrumbs :items="items" divider=">"></v-breadcrumbs>
</v-app>
</template>
<script>
data: () => ({
items: [
{
text: 'Dashboard',
disabled: false,
href: 'breadcrumbs_dashboard'
},
{
text: 'Link 1',
disabled: false,
href: 'breadcrumbs_link_1'
},
{
text: 'Dashboard',
disabled: true,
href: 'breadcrumbs_link_2'
}
]
})
}
</script>
```
</details>
> fix(VBreadcrumbs): v-for key error when two items have identical texts

- packages/vuetify/src/components/VSlider/VSlider.js
- packages/vuetify/test/unit/components/VSlider/VSlider.spec.js
Forces the slider value to be within the boundaries set by min and max props.
fixes #6604 
Tested visually with the provided playground code.
<details>
```vue
<template>
<v-app>
<v-layout justify-center wrap>
<v-flex xs7>
<v-slider
v-model="val"
min="55"
max="80" />
</v-flex>
</v-layout>
</v-app>
</template>
<script>
data: () => ({
val: 50
}),
}
</script>
```
</details>
> fix(VSlider): set value to min if it's less than min (#6604)

- packages/vuetify/src/stylus/components/_progress-linear.styl
set v-progress-linear__content height to 100%
Fixes #6707
visually
<details>
```vue
<template>
<v-container>
<v-card flat width="60%">
<v-progress-linear color="red lighten-2" background-color="grey lighten-2" height="30" width="60%" value="75">
<v-layout align-center fill-height>
<v-flex xs1 text-xs-center>37%</v-flex>
<v-flex xs11 text-xs-center>vue</v-flex>
</v-layout>
</v-progress-linear>
</v-card>
</v-container>
</template>
<script>
data: () => ({
valueDeterminate: 50
})
}
</script>
```
</details>
> fix(progressbar): allow vertical centering of inner content

- packages/docs/src/examples/windows/onboarding.vue
The current example code for the onboarding example on the Windows component doesn't work as expected.
This PR fixes the example code so that it works as expected.
> docs(windows): Fix bug in next() method of onboarding example

- packages/vuetify/src/components/VDialog/VDialog.js
- packages/vuetify/src/components/VMenu/VMenu.js
- packages/vuetify/src/components/VMenu/mixins/menu-generators.js
- packages/vuetify/src/components/VMenu/mixins/menu-keyable.js
- packages/vuetify/src/directives/click-outside.ts
- packages/vuetify/src/mixins/dependent.ts
- packages/vuetify/src/mixins/returnable.ts
- packages/vuetify/test/unit/components/VDialog/VDialog.spec.js
- packages/vuetify/test/unit/directives/click-outside.spec.js
These are all somewhat related and are just here for testing, can be rebased onto master. 
The big one is #2538, the tab key can no longer escape from dialogs. The others got in the way of this working properly with nested dialogs and menus so I fixed them at the same time.
Builds on #1932
@Webifi If you could take a look at my click-outside changes that'd be cool
This PR greatly improves use of dialogs with just the keyboard, it is now possible to navigate and close deeply nested dialogs and menus. 
fixes #2538
fixes #5200
fixes #6352
and some other bugs that I found during
<details>
```vue
<template>
<v-app>
<v-container>
<v-dialog content-class="first">
<v-btn slot="activator">dialog</v-btn>
<v-card>
<v-card-text>
<v-text-field label="Input in dialog"></v-text-field>
<v-text-field …
```
> fix(VDialog, VMenu): improve keyboard navigation

- packages/vuetify/src/components/VSnackbar/__tests__/VSnackbar.spec.ts
Test for VSnackbar was migrated to vue-test-utils:
* test file with vue-test-utils added in components/[component_name]/__tests__
* test file with avoriaz removed from test/unit/... folder
Requirements of vuetify 2.0
unit
> test(VSnackbar): Migrate to vue-test-utils

- packages/vuetify/src/components/VSwitch/__tests__/VSwitch.spec.ts
- packages/vuetify/src/components/VSwitch/__tests__/__snapshots__/VSwitch.spec.ts.snap
Test was migrated to vue-test-utils:
* test file with vue-test-utils added in components/[component_name]/tests
* test file with avoriaz removed from test/unit/... folder
Requirement for v2
unit
* `.v-input--selection-controls__ripple` is not found while present when logging `wrapper.html()`
> test(VSwitch): Migrate to vue-test-utils

- packages/vuetify/src/stylus/components/_messages.styl
There is a problem with letters like "qygjp" being cropped in input hints or error messages. While line-height: 1 seems like a potentially reasonable value, it happens to be not enough. I think it should be left for the browser to decide what line-height should be applied to display this element correctly.
visually in chrome, firefox, safari (all up to date)
```vue
<template>
<v-app>
<v-flex
md12
xs12
>
<v-text-field
v-model="test"
error-messages="qygjp"
hint="qygjp"
/>
</v-flex>
</v-container>
</v-app>
</template>
<script>
data: () => ({
test: ''
})
}
</script>
```
> fix(v-messages): increase line-height of inputs messages

- packages/vuetify/build/babel-transform-sass-paths.js
Fixes`babel-transform-sass-paths` custom plugin to correctly resolve `.sass` paths when building `es5` & `lib` folders.
This PR fixes the issue.
```js
// vuetify/lib/framework.js
...
import '../src/stylus/app.styl';
import '../../../src/components/undefined/styles/main.sass';
...
```
```js
// vuetify/lib/components/VPicker/VPicker.js
...
import '../../../src/stylus/components/_pickers.styl';
import '../../../../src/components/VPicker/VCard/VCard.sass';
...
```
```js
// vuetify/lib/framework.js
...
import '../src/stylus/app.styl';
import '../src/styles/main.sass';
...
```
```js
// vuetify/lib/components/VPicker/VPicker.js
...
import '../../../src/stylus/components/_pickers.styl';
import '../../../src/components/VCard/VCard.sass';
...
```
> fix: fix babel-transform-sass-paths

- packages/vuetify/src/stylus/components/_treeview.styl
Automatic height v-treeview.
Replace height with min-height on v-treeview-node__root.
resolves https://github.com/vuetifyjs/vuetify/issues/6630
<details>
```vue
&__root
display: flex
align-items: center
min-height: 34px // from height to min-height
```
</details>
> fix(v-treeview) height limitation

- packages/vuetify/src/components/VTimePicker/VTimePickerClock.sass
Fix SASS indent for VTimePickerClock to fix the warning showing up when using `vuetify-loader` with `vuetify@2.0.0-alpha.12`
> fix(VTimePickerClock): fix sass indent

- packages/vuetify/src/components/VDialog/VDialog.ts
- packages/vuetify/src/components/VDialog/__tests__/VDialog.spec.ts
- packages/vuetify/src/components/VForm/__tests__/VForm.spec.ts
Adds an emitter which emits `click:outside` when the `closeConditional()` gets called.
Duplicate of this PR: #5593 
Fixes #5533 
A new unit test has been created to check if `click:outside` has been called.
<details>
```vue
<template>
<div id="app">
<v-app>
<v-content>
<v-dialog
v-model="open"
persistent
@click:outside="callback"
width="300"
>
<v-btn slot="activator"> Open </v-btn>
<v-card>
My Dialog Content
</v-card>
</v-dialog>
<v-dialog
v-model="areYouSureDialog"
persistent
width="300"
>
<v-card>
<v-flex>
Are you sure?
</v-flex>
<v-flex>
<v-btn @click="closeBoth"> Yes </v-btn>
<v-btn @click="areYouSureDialog = false"> No </v-btn>
</v-flex>
</v-card>
</v-dialog>
</v-layout>
</v-container>
</v-content>
</v-app>
</div>
</template> …
```
> feat(v-dialog): adds click:outside call

- packages/vuetify/src/mixins/overlayable.ts
- packages/vuetify/src/util/helpers.ts
check browser support for passive events and only pass in options object if browser supports it
fixes #6617 
playground (scroll, open dialog, confirm scrolling doesn't happen while dialog is open, close and scroll page again)
<details>
```vue
<template>
<v-app><v-content><v-container fluid>
<div class="text-xs-center">
<v-dialog
width="500"
>
<v-btn
color="red lighten-2"
dark
v-on="on"
>
Click Me
</v-btn>
</template>
<v-card>
<v-card-title
class="headline grey lighten-2"
primary-title
>
Privacy Policy
<v-card-text>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip …
```
> fix(overlayable): check browser support for passive events

- packages/vuetify/src/components/VSpeedDial/VSpeedDial.js
Adding a `typeof !== 'undefined'` check so only slots with `componentOptions` will be adding an animation.
it fixes #6901 
I've tested this in my project with the same code as the issues codepen: https://codepen.io/anon/pen/BENVJK?editors=1111
and with the playground as documented below
<details>
Playground.vue
```
<template>
<v-app>
<child>
<div slot="speedDialAfter">
test
</div>
</child>
</v-app>
</template>
<script>
import Child from './Child.vue';
components: {Child},
data: () => ({
})
}
</script>
```
Child.vue
```
<template>
<div>
<v-fab-transition>
<v-speed-dial
v-model="fab"
:top="true"
:right="true"
:open-on-hover="true"
direction="bottom"
transition="slide-y-reverse-transition"
>
<v-btn slot="activator" color="accent" dark fab hover v-model="fab"> …
```
> added check for componentOptions existing on slot fixes #6901

- packages/vuetify/src/components/VCounter/VCounter.ts
- packages/vuetify/src/components/VLabel/VLabel.ts
- packages/vuetify/src/components/VRadioGroup/VRadio.js
fixes #6981
https://github.com/vuetifyjs/vuetify/blob/189cbd20330be6e42ed190ebe3cfd9b26295c51b/packages/vuetify/src/components/VTextField/VTextField.js#L300 is coerced to `true` if VLabel has `Boolean`
lol
> fix(VTextField): prevent TypeError when color is an empty string

- packages/docs/src/examples/calendars/weekly.vue
The v-slot should be "dayHeader" not "dayHeadere".  
This typo prevents the all day events from displaying at the top when using the example code.
I'm a total GitHub newbie so I apologize if I didn't do this right!
<details>
```vue
```
</details>
> Fixing typo in line 14 

- packages/vuetify/src/components/VDialog/VDialog.js
- packages/vuetify/test/unit/components/VDialog/VDialog.spec.js
removed `[Vuetify] No activator found` error on escape keypress when dialog is active.
fixes #7008 
visually
<details>
```vue
<template>
<v-app>
<v-content>
<v-btn
dark
@click.stop="dialog = true"
>
Open Dialog
</v-btn>
<v-dialog
max-width="290"
>
<v-card>
<v-card-title class="headline">Use Google's location service?</v-card-title>
<v-card-text>
Let Google help apps determine location. This means sending anonymous location data to Google, even when no apps are running.
</v-card-text>
<v-spacer />
<v-btn
color="green darken-1"
flat="flat"
@click="dialog = false"
>
Disagree
</v-btn>
<v-btn
color="green darken-1"
flat="flat"
@click="dialog = false"
>
Agree
</v-btn>
</v-card>
</v-dialog> …
```
> fix(VDialog): remove console error on escape keypress

- packages/vuetify/src/components/VParallax/VParallax.ts
- packages/vuetify/src/components/VParallax/__tests__/__snapshots__/VParallax.spec.ts.snap
relied on translate to be called in order to boot, this doesn't occur when image is the same size as
the container
fixes #7010
<details>
```vue
```
</details>
> refactor(VParallax): update for v2

- packages/vuetify/src/components/VList/VListItem.sass
This fix is made because of issue #7117
Any v-badge inside v-list-tile-title now has margin-top to create additional space for badge circle
This is fix for issue https://github.com/vuetifyjs/vuetify/issues/7117
> fix(VListTileTitle): don't cut badge

- packages/docs/src/examples/data-tables/crud.vue
Fix v-datatable broken with inline actions.
It's a tiny fix, just test it in codepen.
remove "column" in this demo.
https://codepen.io/pen/?&editable=true&editors=101
<details>
```vue
```
</details>
> fix: fix column slot param

- packages/vuetify/src/services/theme/index.ts
When using Nuxt, Vuetify SSR styles are pushed with a "hack" using `root.$children.push()` with `vue-meta` options. But as it it wasn't a proper Vue instance, it was breaking Vue DevTools, cause `$children` should be only Vue instances.
Not having Vue DevTools working was a pain :D
I tested locally on 2 Nuxt + Vuetify projects and that fixed Vue DevTools.
> fix: fix vue-devtools when using nuxt

- packages/vuetify/.npmignore
When a new Vuetify Alpha is released - the types folder is missing two sibling folders called `services` and `presets`. During development you likely would not notice this - but when consuming the npm package in your own project - you receive numerous typescript errors about missing referenced files.
This commit should ensure the two folders are now included in the published package, removing the errors at compile time.
We've been testing the Alpha locally, but find it hard to develop because the errors and warnings produced without these two folders overwhelm any actual errors you might have.
I've run an `npm pack` locally to ensure the generated package includes the two missing folders.
> (fix) ensure required typescript folders are included during packaging

- packages/vuetify/src/components/VDataIterator/VDataIterator.ts
- packages/vuetify/src/components/VDataIterator/__tests__/VDataIterator.spec.ts
due to using $set, watch handler was unable to see new values when toggling all selected on/off
fixes #7115
<details>
```vue
<template>
<div>
<h2>Currently {{selected.length}} rows are selected</h2>
<v-data-table
show-select
</div>
</template>
<script>
data () {
return {
selected: [],
headers: [
{
text: 'Dessert (100g servin)',
align: 'left',
value: 'name'
},
{ text: 'Iron (%)', value: 'iron' }
],
desserts: [
{
calories: 159,
fat: 6.0,
carbs: 24, …
```
> fix(VDataIterator): it should now emit event when toggling all selected

- packages/vuetify/src/components/VSlideGroup/VSlideGroup.ts
- packages/vuetify/src/components/VSlideGroup/__tests__/VSlideGroup.spec.ts
- packages/vuetify/src/components/VTabs/VTabs.sass
fixes #7245 and other issues:
- https://codepen.io/anon/pen/pmLGao
- tabs are initially not visible
- click right arrow as long as tabs will be aligned to the right
- click left arrow (tabs shift correctly), click left arrow again (tabs go back to the initial position)
- click left arrow, click the most left tab, tabs get crazy
- click anywhere, nothing works as it should
visually, unit
<details>
```vue
<template>
<v-app>
<v-content>
<v-tabs show-arrows>
<v-tab v-for="i in 50" :key=i>{{ i }}</v-tab>
</v-tabs>
<v-tabs centered>
<v-tab v-for="i in 4" :key=i>{{ i }}</v-tab>
</v-tabs>
</v-content>
</v-app>
</template>
<script>
created () {
}
}
</script>
```
</details>
> fix: tabs in RTL mode

- packages/vuetify/src/components/VDataTable/VDataTableHeader.sass
- packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
- packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTableHeader.spec.ts.snap
- packages/vuetify/src/components/VDataTable/mixins/__tests__/__snapshots__/header.spec.ts.snap
- packages/vuetify/src/components/VDataTable/mixins/header.ts
header sort icons should respect size and rotate regardless of type
closes #7338
playground
<details>
```vue
<template>
<div>
<v-data-table fixed-header :headers="headers"></v-data-table>
</div>
</template>
<script>
data () {
return {
headers: [
{
align: 'left',
value: 'name'
},
{ text: 'Iron (%)', value: 'iron' }
]
}
}
}
</script>
```
</details>
> fix(VDataTable): header icons should respect type (svg/non-svg)

- packages/vuetify/package.json
Fixes `path` to `jest` binary of the `debug:test` script.
Fixes #7350 
By running the script after the patch.
<details>
```vue
```
</details>
> Fix path to jest binary in debug:test script

- packages/vuetify/src/components/VTextField/VTextField.ts
- packages/vuetify/src/components/VTextField/__tests__/VTextField.spec.ts
- packages/vuetify/src/components/VTextarea/VTextarea.ts
`internalChange` was used only for masks. Change my mind
fixes #4683
fixes #6978
visually
<details>
```vue
<template>
<v-app>
<v-content>
<v-container>
<v-textarea
auto-grow
v-model="message"
@keydown.prevent.enter="message = ''"
:rows="1"
></v-textarea>
</v-container>
</v-content>
</v-app>
</template>
<script>
data: () => ({
message: Array(40).fill('aaaaa ').join('')
})
}
</script>
```
</details>
> fix(VTextarea): recalculate height on model update

- packages/docs/src/lang/en/components/TextFields.json
Just replacing outline with outlined
Removes old use of outline instead of outlined
none 
<details>
```vue
```
</details>
> Docs(VTextField): outline -> outlined

- packages/vuetify/src/services/theme/index.ts
When using SSR, `vue-theme-stylesheet` is already in DOM, but there's missing check that make client add an empty `style` tag with a duplicated id. Having two same `id` in DOM is not HTML valid.
Assuming comment here https://github.com/vuetifyjs/vuetify/blob/next/packages/vuetify/src/services/theme/index.ts#L138, I think it's just a check that have been forgotten but already thought.
I checked locally with an SSR project that there was no duplicatd tag with same id anymore.
> fix: prevent duplicated theme stylesheet id

- packages/vuetify/src/components/VToolbar/VToolbar.sass
The width was most likely missing when being converted to sass
Without the width it changes the behavior of `v-toolbar`
none - this is a single line css change
<details>
```vue
<template>
<v-app>
<v-content>
<v-card>
<v-card-title>
<v-toolbar>
<v-toolbar-title>Title</v-toolbar-title>
</v-toolbar>
<v-card-text>Hello world</v-card-text>
</v-card>
</v-container>
</v-content>
</v-app>
</div>
</template>
```
</details>
> fix(VToolbar): styles missing width 100%

- packages/vuetify/src/components/VDialog/VDialog.js
onFocusin method in VDialog.js uses `e` as an argument representing the event and then uses `event` in the function body.
Have observed `event is undefined` error in Firefox whenever an input element is focused inside of a v-dialog.
I used the dialog with form example from the docs. Observed the error in Firefox without my fix and observed no error with my fix.
<details>
```vue
<template>
<v-app>
<v-dialog v-model="dialog" persistent max-width="600px">
<v-btn color="primary" dark v-on="on">Open Dialog</v-btn>
</template>
<v-card>
<v-card-title>
<span class="headline">User Profile</span>
<v-card-text>
<v-container grid-list-md>
<v-layout wrap>
<v-flex xs12 sm6 md4>
<v-text-field label="Legal first name*" …
```
> fix(VDialog.js): fixed event variable ref in onFocusin

- packages/vuetify/src/util/helpers.ts
> fix(VMenu): skip elements with 0 or NaN z-index

- packages/docs/src/lang/en/components/SystemBars.json
- packages/vuetify/src/components/VSystemBar/VSystemBar.sass
- packages/vuetify/src/components/VSystemBar/VSystemBar.ts
- packages/vuetify/src/components/VSystemBar/_variables.scss
removes the `status` prop from VSystemBar.
It serves no functional value.
visually
<details>
```vue
<template>
<div>
<v-system-bar color="green">
<v-icon>mdi-gmail</v-icon>normal
</v-system-bar>
<v-system-bar
window
color="orange"
>
<v-icon>mdi-gmail</v-icon>window
</v-system-bar>
</div>
</template>
<script>
data () {
return {}
},
}
</script>
```
</details>
> refactor(VSystemBar): remove status prop

- packages/docs/src/lang/ja-JP/components/DataTables.json
Fix japanese translation of DataTable
Issue: https://github.com/vuetifyjs/vuetify/issues/7597
Make same with the property of en
https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/lang/en/components/DataTables.json#L5
none
<details>
```vue
```
</details>
> Fix japanese translation of DataTable

- packages/vuetify/src/util/__tests__/helpers.spec.ts
- packages/vuetify/src/util/helpers.ts
Return early if key exists directly on object to improve performance
solves #7302 
<details>
```vue
<template>
<v-container>
<v-text-field v-model="search" label="search"></v-text-field>
<v-data-table
:items="moreDesserts"
</v-container>
</template>
<script>
data () {
return {
search: '',
headers: [
{
align: 'left',
value: 'name'
},
{ text: 'Iron (%)', value: 'iron' }
],
desserts: [
{
value: false,
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1%'
},
{
value: …
```
> fix(getObjectValueByPath): fix getObjectValueByPath

- packages/vuetify/src/directives/ripple/index.ts
- packages/vuetify/src/globals.d.ts
Mouse events can fire with touch on Android/iOS, this sets a ripple prop to allow that to be ignored
on touch devices.
fixes #7605
Android/iOS through Browserstack
<details>
```vue
<template>
<div
v-ripple
class="text-xs-center elevation-2 pa-5 headline"
>
HTML element with v-ripple
</div>
</template>
```
</details>
> fix(Ripple): add ripple property to denote touch enabled

- packages/vuetify/src/components/VDataTable/VDataTable.ts
- packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts
- packages/vuetify/src/components/VDataTable/VDataTableHeaderMobile.ts
- packages/vuetify/src/components/VDataTable/mixins/header.ts
disable clicking on headers to sort when `disable-sort` is active
fix #7657 
playground
<details>
```vue
<template>
<v-data-table
disable-sort
</template>
<script>
data () {
return {
headers: [
{
align: 'left',
value: 'name',
},
],
desserts: [
{
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1%',
},
{
calories: 237,
fat: 9.0,
carbs: 37,
protein: 4.3,
iron: '1%',
},
{
name: …
```
> fix(VDataTable): disable header sorting if disable-sort is true

- packages/vuetify/src/components/VCalendar/VCalendarDaily.ts
- packages/vuetify/src/components/VCalendar/util/__tests__/__snapshots__/timestamp.spec.ts.snap
- packages/vuetify/src/components/VCalendar/util/__tests__/timestamp.spec.ts
- packages/vuetify/src/components/VCalendar/util/timestamp.ts
there are scenarios where a given start date, end date, and weekdays results
in no days being in range. we should throw a sensible error here instead of
the component just breaking
closes #7155
<details>
```vue
<template>
<v-calendar
ref="calendar"
v-model="start"
:type="type"
:weekdays="weekdays"
></v-calendar>
</template>
<script>
data: () => ({
start: '2019-01-12',
type: 'day',
weekdays: [1, 2, 3, 4, 5],
})
}
</script>
```
</details>
> fix(VCalendar): throw error when no days available

- packages/docs/src/examples/sparklines/playground.vue
- packages/docs/src/lang/en/components/Sparklines.json
- packages/vuetify/src/components/VSparkline/VSparkline.ts
- packages/vuetify/src/components/VSparkline/__tests__/__snapshots__/VSparkline.spec.ts.snap
- packages/vuetify/src/components/VSparkline/helpers/core.ts
negative values were not displayed correctly in bars. labels were also being cut off in certain scenarios. refactored the generation and displaying of bars to make it a bit less confusing.
because
playground, unit tests
<details>
```vue
<template>
<v-sparkline
:value="value"
:type="type"
></v-sparkline>
</template>
<script>
data: () => ({
value: [-5, 5],
type: 'bar',
}),
}
</script>
```
</details>
> fix(VSparkline): negative values, labels being cut off

- packages/vuetify/src/components/VDivider/VDivider.ts
- packages/vuetify/src/components/VDivider/__tests__/VDivider.spec.ts
- packages/vuetify/src/components/VDivider/__tests__/__snapshots__/VDivider.spec.ts.snap
- packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelectList.spec.ts.snap
Adding WAI-ARIA accessibility attributes (role and orientation) to the `VDivider` component.
This is the 2nd PR in a 3-PR bundle (see #7707 and #7709) looking to add an "Accessibility Considerations" section to the standard UI Components documentation pages. This PR adds the recommended WAI-ARIA roles to the `VDivider` component.
Bring the `VDivider` component into compliance with the [WAI-ARIA recommendations for `<hr>` elements](https://www.w3.org/TR/wai-aria/#separator).
5 unit tests added to `src/components/VDivider/__tests__/VDivider.spec.ts`.
> feat(VDivider): Add a11y attributes

- packages/docs/src/components/core/FileBtn.vue
- packages/docs/src/components/core/Page.vue
- packages/docs/src/components/doc/Contribution.vue
- packages/docs/src/components/doc/Example.vue
- packages/docs/src/components/doc/Markup.vue
Updated hard coded branch pathing (for things like "open in github")
Allows for dynamic pathing between master/dev/next
removes some hardcoded links
current process with process.env doesn't work on live sites as they are always prod, also excluded next.
visually
> docs: update branch path logic

- packages/docs/src/data/pages/customization/Icons.json
- packages/docs/src/lang/en/customization/Icons.json
- packages/docs/src/snippets/html/using_missing_material_icons_component.txt
- packages/docs/src/snippets/html/using_missing_material_icons_font.txt
- packages/docs/src/snippets/html/using_missing_material_icons_usage.txt
- packages/docs/src/snippets/js/using_missing_material_icons.txt
This PR is identical to #7735, but for `next`. 
I added a kind description of how to use missing material icons.
Some material icons are missing by default. For example, `person` and `person_outline` are available, but `visibility_outline` isn't while `visibility` is. This has been a known issue for a while, but I personally had a bit embarrassing experience finding how to solve this inconsistency as there wasn't a clear and explicit description. Therefore I thought it would be helpful or at least convenient for other people if I can add some guide that can be easily copied and pasted.
Fixes https://github.com/vuetifyjs/vuetify/issues/4164
Of course I run docs server on my local machine and found no problem.
> docs: kind guide for using missing material icons

- packages/api-generator/src/helpers/merge.js
- packages/api-generator/src/index.js
- packages/api-generator/src/maps/v-data-iterator.js
- packages/api-generator/src/maps/v-data-table.js
- packages/docs/src/data/pages/components/DataTables.json
- packages/docs/src/examples/data-tables/intermediate/custom-filter.vue
- packages/docs/src/lang/en/components/DataTables.json
- packages/vuetify/src/components/VDataTable/VDataTable.ts
- packages/vuetify/src/components/VDataTable/mixins/header.ts
- packages/vuetify/src/util/helpers.ts
change custom-filter signature, added example of custom-filter prop usage and filtering on specific columns.
new signature is `(value: any, search: string | null, item: any): boolean`
early on in the data-table refactor I combined it and `filter` to make things a bit more straightforward. but I see now that the resulting `customFilter` function went the wrong way. Replacing it right now is not very straightforward (with a signature of `(items: any[],  search: string | null,  headersWithCustomFilters: TableHeader[],  headersWithoutCustomFilters: TableHeader[])`)
playground, doc example
<details>
```vue
<template>
<div>
<v-data-table
:custom-filter="filterOnlyCapsText"
>
<template v-slot:top> …
```
> fix(VDataTable): make it easier to use custom-filter

- packages/docs/src/examples/calendars/complex/events.vue
- packages/docs/src/examples/calendars/simple/weekly.vue
- packages/docs/src/examples/icons/simple/md.vue
- packages/docs/src/examples/layouts/google-keep.vue
- packages/docs/src/examples/menus/intermediate/absolute-without-activator.vue
- packages/docs/src/examples/progress-circular/simple/circular-colored.vue
- packages/docs/src/examples/progress-circular/simple/circular-indeterminate.vue
- packages/docs/src/examples/progress-circular/simple/circular-rotate.vue
- packages/docs/src/examples/progress-circular/simple/circular-size-and-width.vue
- packages/docs/src/examples/progress-circular/usage.vue
- packages/docs/src/examples/sliders/simple/editable-numeric-value.vue
Codepen component removes first 2 spaces from styles which breaks codepen if using sass (for example click the codepen btn on last calendars example)
https://vuetifyjscom-rbididdjsi.now.sh/en/components/calendars
vs
https://next.vuetifyjs.com/en/components/calendars
> docs: broken styles in codepen

- Dockerfile
- now.json
- package.json
- packages/docs/package.json
- packages/vuetify/package.json
- scripts/deploy-and-alias.js
- yarn.lock
This reverts commit 1e28f5a2addf4bcf3403337b8f7f2d66591104a8.
Zeit claims to support node 10.15, but only installs up to 10.7
> chore: deploy docs with a docker container

- README.md
- packages/docs/src/components/doc/Codepen.vue
- packages/docs/src/examples/autocompletes/usage.vue
- packages/docs/src/examples/forms/intermediate/vee-validate.vue
- packages/docs/src/examples/windows/playground.vue
- packages/docs/src/examples/windows/simple/reverse.vue
- packages/docs/src/examples/windows/simple/vertical.vue
- packages/docs/src/snippets/html/cdn_quickstart.txt
- packages/docs/src/snippets/html/fa4_link.txt
- packages/docs/src/snippets/html/material_design_icons_link.txt
- packages/docs/src/themes/parallax-starter/index.html
- packages/kitchen/public/index.html
- packages/kitchen/src/components/Codepen.vue
replaces `npm/vuetify/dist` with `npm/vuetify@^2/dist` to avoid breaking apps after releasing next major
> chore: restrict vuetify and other libs version to current major

- packages/vuetify/src/components/VDataIterator/VDataFooter.ts
- packages/vuetify/src/components/VDataIterator/__tests__/VDataFooter.spec.ts
- packages/vuetify/src/components/VDataIterator/__tests__/__snapshots__/VDataFooter.spec.ts.snap
fixes #8026
When providing custom itemsPerPageOptions, if the current item did not exist in the options, it was pushed into the array. This means if no options are provided, 10 is the default and was being pushed into the array.
Now the system simply determines if the provided itemsPerPage exists in the items and if not, the first item is selected.
itemsPerPage has a default value of 10, which consequently was getting pushed into the footers items array because it was a value that did not exist within the provided list. This causes issues when adding custom itemsPerPageOptions that does not contain the value 10, (or whatever value is defined for the options).
jest / visually
<details>
```vue
<template>
<div class="ma-5 pa-5">
<v-data-table …
```
> fix(VDataFooter): better handle custom item options

- packages/vuetify/src/components/VDataTable/VDataTableHeader.sass
- packages/vuetify/src/components/VDataTable/VDataTableHeaderMobile.ts
hides disabled headers in sort VSelect, hides VSelect if there's no sortable headers at all
Alternatively it can show disabled VSelect if there's no sortable headers @vuetifyjs/core-team ?
fixes #8036 
playground
<details>
```vue
<template>
<v-container>
<v-data-table :headers="headers" :items="desserts" :items-per-page="5" class="elevation-1" />
<v-data-table :headers="headers2" :items="desserts" :items-per-page="5" class="elevation-1" />
</v-container>
</template>
<script>
data: () => ({
headers: [
{ text: 'Dessert (100g serving)', sortable: false, value: 'name' },
],
headers2: [
{ text: 'Dessert (100g serving)', sortable: false, value: 'name' },
{ text: 'Calories', sortable: false, value: 'calories' },
],
desserts: [
{ name: …
```
> fix(VDataTableHeaderMobile): don't show disabled headers in sort select

- packages/vuetify/src/components/VFileInput/VFileInput.ts
- packages/vuetify/src/components/VFileInput/__tests__/VFileInput.spec.ts
- packages/vuetify/src/components/VFileInput/__tests__/__snapshots__/VFileInput.spec.ts.snap
also removes tab index from icon, it allowed to tab the icon but enter/space didn't do anything, without it it's still clickable
fixes #8049
<details>
```vue
<template>
<v-container>
<v-file-input prepend-icon="" />
<v-file-input />
<v-file-input prepend-icon="mdi-home" />
</v-container>
</template>
```
</details>
> fix(VFileInput): unindent input when icon is empty

- packages/vuetify/src/components/VApp/VApp.ts
I've tried `consoleError` as well but imho the message wasn't visible enough
replace `vuetify` with `v: vuetify` in dev/index.js
> chore: throw if vuetify is not bootstrapped properly

- packages/docs/src/examples/spacing/playground.vue
MIssing spacing values in playgroun (6-12, negative margins)
https://vuetifyjscom-wguujrtcta.now.sh/en/styles/spacing
> docs: more spacings in playground

- packages/vuetify/src/components/VDataTable/VDataTable.sass
- packages/vuetify/src/components/VDataTable/VDataTable.ts
- packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
1. centers the no data / no results text
2. add disabled style to the text
3. removes hover effect on no data / no results row
fixes #8102
playground, updated snapshots
<details>
```vue
<template>
<v-container>
<v-data-table :headers="[{text:'a',value:'a'},{text:'b',value:'b'}]" :items="[]" hide-default-footer></v-data-table>
<v-data-table search="foo" :headers="[{text:'a',value:'a'},{text:'b',value:'b'}]" :items="[{}, {}]" hide-default-footer></v-data-table>
</v-container>
</template>
```
</details>
> fix(VDataTable): no-data/no-results text improvements

- packages/docs/src/components/core/Toolbar.vue
adds message for users wanting to find the upgrade guide / release notes.
I found it strange that we don't link to release notes from the docs.
running locally
<details>
```vue
```
</details>
> fix(docs): add link to release notes in front page message

- packages/vuetify/src/components/VDataTable/VSimpleTable.sass
Fixes missing `hover` styling for **VSimpleTable** which was relying on `hover` of **VDataTable**, leading to an issue when not using **VDataTable** with **tree-shaking** enabled.
https://github.com/nuxt-community/vuetify-module/issues/73
Visually when using VSimpleTable in production with treeShaking, `hover` gets fixed with this change.
> fix(VSimpleTable): fix hover when using tree-shaking

- packages/vuetify/src/services/theme/__tests__/__snapshots__/theme.spec.ts.snap
- packages/vuetify/src/services/theme/__tests__/theme.spec.ts
- packages/vuetify/src/services/theme/index.ts
1) Reverts #8079 as it breaks in more cases than the ones it was aiming to fix. 
> We still need to find a solution to not have duplicated stylesheet in SPA projects that uses VueMeta.
2) Makes `head` a function instead of object for VueMeta theme to fix theme when navigating pages
#7879 
https://github.com/nuxt-community/vuetify-module/issues/91
https://github.com/nuxt-community/vuetify-module/issues/63
This PR *should* fix these 3 issues.
Jest
> fix(Theme): fix vue-meta theme on page navigation

- packages/vuetify/src/components/VDataIterator/__tests__/__snapshots__/VDataFooter.spec.ts.snap
- packages/vuetify/src/components/VDataIterator/__tests__/__snapshots__/VDataIterator.spec.ts.snap
- packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
- packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTableHeader.spec.ts.snap
- packages/vuetify/src/components/VOverflowBtn/__tests__/__snapshots__/VOverflowBtn.spec.ts.snap
- packages/vuetify/src/components/VSelect/VSelect.ts
- packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect.spec.ts.snap
- packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect2.spec.ts.snap
- packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect3.spec.ts.snap
Change default menu `max-height` of VSelect from 300px to 304px to avoid vertical scrollbar from appearing unnecessarily.
To display six menu items, a max-height of 304px is required, rather than 300px. This avoids the
unsightly appearance of a vertical scrollbar.
Checked in Playground. Existing tests were updated across several components related to this change.
None.
<details>
```vue
<template>
<v-container>
<v-layout
wrap
align-center
>
<v-flex
xs12
sm6
d-flex
>
<v-select
:items="items"
></v-select>
</v-flex>
<v-flex
xs12
sm6
d-flex
>
<v-select
:items="items"
filled
label="Filled style"
></v-select>
</v-flex>
<v-flex
xs12
sm6
d-flex
>
<v-select
:items="items"
label="Outline style"
outlined
></v-select>
</v-flex>
<v-flex
xs12
sm6 …
```
> fix(VSelect): tweak default menu max-height value

- packages/vuetify/src/components/VFileInput/VFileInput.ts
- packages/vuetify/src/components/VFileInput/__tests__/VFileInput.spec.ts
v-file-input was emitting a change event both when pressing enter, and when it was blurred
closes #8167
playground, unit tests
<details>
```vue
<template>
<v-content>
<v-card>
<v-card-title>
<v-layout justify-center pa-3>
<h4>Upload</h4>
</v-layout>
<v-card-text>
<v-layout mt-3>
<v-flex md12>
<v-file-input
@change = "imageSelected"
label = "upload"
ref = "myUpload"></v-file-input>
</v-flex>
</v-layout>
<v-layout pa-3 v-if = "imageUrl !== ''">
<v-flex md12>
<v-img :src = "imageUrl"></v-img>
</v-flex>
</v-layout>
</v-card-text>
</v-card>
</v-container>
</v-content>
</template>
<script>
data: () => ({
imageUrl: '',
}),
methods: {
imageSelected(file) {
if (Array.isArray(file) && !file.length) return …
```
> [Bug] fix(VFileInput): fix rogue change events

- packages/vuetify/src/components/VSwitch/VSwitch.sass
- packages/vuetify/src/components/VSwitch/_variables.sass
fixes #8130
and minor bug (2px offset) for normal `v-switch`
visually
<details>
```vue
<template>
<v-btn block @click="$vuetify.rtl = !$vuetify.rtl">Toggle rtl</v-btn>
<v-switch inset :input-value="false"></v-switch>
<v-switch inset :input-value="true"></v-switch>
<v-switch :input-value="false"></v-switch>
<v-switch :input-value="true"></v-switch>
</v-container>
</template>
<style>
.theme--light.v-input--switch .v-input--switch__thumb,
.theme--light.v-input--switch .v-input--switch__thumb.accent--text {
color: rgba(255, 255, 255, 0.5) !important;
}
</style>
```
</details>
> fix(VSwitch): thumb position in inset v-switch in RTL mode

- packages/vuetify/src/components/VWindow/VWindow.sass
- packages/vuetify/src/components/VWindow/VWindow.ts
increased size of buttons
prev/next buttons were too small
<details>
```vue
<template>
<v-carousel>
v-for="(color, i) in colors"
:key="color"
>
<v-sheet
:color="color"
height="100%"
tile
>
<v-layout
align-center
fill-height
justify-center
>
<div class="display-3">Slide {{ i + 1 }}</div>
</v-layout>
</v-sheet>
</v-carousel>
</template>
<script>
data () {
return {
colors: [
'primary',
'secondary',
'yellow darken-2',
'red',
'orange',
],
}
},
}
</script>
```
</details>
> fix(VCarousel): prev/next buttons were too small

- packages/docs/src/lang/en/components/Selects.json
docs(Selects): document the special handling of objects with header and divider properties
Added documentation regarding the treatment of items objects that have a **header** or **divider** property.
Documents the existing treatment of objects that contain a **header** or **divider** property.  This is important because
* It enabled users to make use of this feature in their code in the knowledge that it is a documented feature
* It prevents users getting unexpected behavior when their objects contain one of these special properties
> docs(Selects): add info about header and divider items

- packages/vuetify/src/components/VSelect/VSelect.ts
- packages/vuetify/src/components/VSelect/__tests__/VSelect4.spec.ts
Ignore `keypress` when **VSelect** is `readonly`
Add a test in `vuetify\src\components\VSelect\__tests__\VSelect4.spec.ts`
> fix(VSelect): ignore keypress when readonly

- packages/vuetify/src/components/VData/VData.ts
- packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts
initial values of options prop were ignored. now we create initial object
by combining individual prop values with options prop object if it exists
solves #8266
<details>
```vue
<template>
<v-data-table
</template>
<script>
data () {
return {
desserts: [
{
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1%',
},
{
calories: 237,
fat: 9.0,
carbs: 37,
protein: 4.3,
iron: '1%',
},
{
calories: 262,
fat: 16.0,
carbs: 23,
protein: 6.0,
iron: '7%',
},
{
calories: 305,
fat: 3.7,
carbs: 67,
protein: 4.3,
iron: '8%',
},
{
name: 'Gingerbread',
calories: 356,
fat: 16.0, …
```
> [Bug] fix(VDataTable): fix options prop not setting initial values

- packages/api-generator/src/maps/v-data-table.js
- packages/vuetify/src/components/VDataTable/VDataTable.ts
- packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
this is the index of the row in the currently display page, not the index
in the original array of items passed to data table
closes #8199
<details>
```vue
<template>
<v-data-table
>
<template v-slot:item="{ item, index, isSelected, select }">
<tr @click="select(!isSelected)">
<td>{{ index }}</td>
<td>{{ isSelected }}</td>
</tr>
</template>
</template>
<script>
data () {
return {
desserts: [
{
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1%',
},
{
calories: 237,
fat: 9.0,
carbs: 37,
protein: 4.3,
iron: '1%',
},
{
calories: 262,
fat: 16.0,
carbs: 23,
protein: 6.0,
iron: '7%',
},
{
name: …
```
> [Bug] fix(VDataTable): add missing index variable in item scoped slot

- packages/vuetify/src/components/VDataTable/VDataTable.ts
- packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts
- packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
setting both width and min-width as styles on header row was the only
way I could get a consistent result
closes #5072, #7623
<details>
```vue
<template>
<v-container>
<v-data-table
:items="items"
show-select
</v-container>
</template>
<script>
data: () => ({
headers: [
{ text: 'Firstname', value: 'firstname', width: '300px' },
{ text: 'Lastname', value: 'lastname' },
{ text: 'Starship Name', value: 'starship', width:'400px' },
{ text: 'Nationality', value: 'nationality' },
{ text: 'Hobbies', value: 'hobbies' },
{ text: 'Likes', value: 'likes' },
{ text: 'Dislikes', value: 'dislikes' },
],
items: [
{ firstname: 'Jean-Luc', lastname: 'Picard', rank: 'Captain', starship: 'Enterprise NCC1701D', …
```
> [Bug] fix(VDataTable): fix header column widths not being respected

- packages/vuetify/src/components/VDataTable/VSimpleTable.sass
- packages/vuetify/src/styles/settings/_dark.scss
- packages/vuetify/src/styles/settings/_light.scss
this is an attempt at a workaround for the long standing bug in chrome when using
colspan and border-collapse together.
see https://bugs.chromium.org/p/chromium/issues/detail?id=356132
close #8251
playground
<details>
```vue
<template>
<div>
<v-data-table
group-by="category"
show-group-by
<v-switch v-model="$vuetify.theme.dark" label="dark"></v-switch>
</div>
</template>
<script>
data () {
return {
headers: [
{ text: 'Id', value: 'id' },
{
align: 'left',
value: 'name',
},
{ text: 'Category', value: 'category' },
],
desserts: [
{
id: 0,
category: 'Ice cream',
},
{
id: 1,
category: 'Ice cream',
},
{
id: …
```
> [Bug] fix(VDataTable): workaround for chrome colspan border-collapse bug

- packages/vuetify/src/components/VFileInput/VFileInput.ts
- packages/vuetify/src/components/VFileInput/__tests__/__snapshots__/VFileInput.spec.ts.snap
Description
Counter + null values throw `Cannot read property 'length' of null` error
fixes #8372 
visually
<details>
```vue
<template>
<v-container grid-list-md>
<v-file-input
counter
label="Single File"
placeholder="Select File"
outlined
chips
<v-file-input
v-model="filesMultiple"
label="Multiple Files"
placeholder="Select Files"
outlined
multiple
counter
chips
</v-container>
</template>
<script>
data: () => ({
files: null,
filesMultiple: [],
}),
}
</script>
```
</details>
> fix(VFileInput): counter should update for null and value type

- packages/vuetify/src/components/VDivider/VDivider.sass
fixes #8397
visually
<details>
```vue
<template>
<v-container>
<v-btn block @click="$vuetify.rtl = !$vuetify.rtl">{{ $vuetify.rtl ? 'rtl' : 'ltr' }}</v-btn>
<v-list shaped>
<v-list-item>
<v-icon>mdi-view-dashboard</v-icon>
<v-list-item-title>Test</v-list-item-title>
</v-list-item>
<v-divider inset />
</v-list>
</v-container>
</template>
```
</details>
> fix(VDivider): missing rtl styles

- packages/vuetify/src/components/VList/VList.sass
- packages/vuetify/src/components/VList/VListItem.sass
- packages/vuetify/src/components/VList/_mixins.sass
fixes #8403
fixes #8378
visually
<details>
```vue
<template>
<v-container>
<v-btn block @click="$vuetify.rtl = !$vuetify.rtl">{{ $vuetify.rtl ? 'rtl' : 'ltr' }}</v-btn>
<v-list shaped style="width: 180px">
<v-list-item to="/page1">
<v-icon>mdi-view-dashboard</v-icon>
<v-list-item-title>Test</v-list-item-title>
<v-icon>mdi-view-dashboard</v-icon>
</v-list-item>
</v-list>
</v-container>
</template>
```
</details>
> fix(VList): missing rtl styles

- packages/vuetify/src/components/VColorPicker/VColorPicker.ts
- packages/vuetify/src/components/VColorPicker/VColorPickerEdit.ts
- packages/vuetify/src/components/VColorPicker/VColorPickerPreview.sass
- packages/vuetify/src/components/VColorPicker/VColorPickerPreview.ts
- packages/vuetify/src/components/VColorPicker/__tests__/VColorPicker.spec.ts
- packages/vuetify/src/components/VColorPicker/__tests__/__snapshots__/VColorPicker.spec.ts.snap
- packages/vuetify/src/components/VColorPicker/util/index.ts
- packages/vuetify/src/util/colorUtils.ts
alpha controls will be hidden when given a hex color without alpha channel.
currently color-picker will parse an object color without alpha channel by adding the channel. this might not be desirable, and means you can not currently disable alpha controls by passing for example `{ r, g, b }` object. this however is a bigger change (and possibly a breaking one) so it is not included in this fix
closes #8390
<details>
```vue
<template>
<div>
<v-color-picker></v-color-picker>
<v-color-picker v-model="hex" mode="hexa"></v-color-picker>
{{ hex }}
<v-color-picker v-model="hexa" mode="hexa"></v-color-picker>
{{ hexa }}
<v-color-picker v-model="rgb" mode="hexa"></v-color-picker>
{{ rgb }}
</div>
</template>
<script>
data () {
return {
hex: '#00FF00',
hexa: …
```
> [Bug] fix(VColorPicker): alpha controls showing when they shouldnt

- packages/vuetify/src/components/VDataTable/VDataTable.ts
- packages/vuetify/src/components/VDataTable/VDataTableHeaderMobile.ts
- packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTableHeader.spec.ts.snap
colspan just seems unnecessary in mobile mode
visually, updated snapshots
<details>
```vue
<template>
<v-container>
<v-data-table
:expanded.sync="expanded"
show-select
show-expand
>
<template v-slot:expanded-item="{ headers }">
<td>
<div style="width: 200px; height: 10px; background: red" />
</td>
</template>
</v-container>
</template>
<script>
data () {
return {
expanded: [],
headers: [
{
align: 'left',
value: 'name',
},
],
desserts: [
{
calories: 159,
fat: 6.0,
},
{
calories: 237,
fat: 9.0,
},
],
}
},
} …
```
> fix(VDataTable): remove unnecessary colspan in mobile view

- packages/vuetify/src/components/VDialog/VDialog.ts
- packages/vuetify/src/components/VMenu/VMenu.ts
- packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts
- packages/vuetify/src/components/VSelect/VSelect.ts
fixes #6976
<details>
```vue
<template>
<v-menu offset-y v-if="$route.name === 'Page 1'">
<v-btn
dark
v-on="on"
>
Dropdown
</v-btn>
</template>
<v-list>
<v-list-item
:key="index"
@click=""
>
</v-list-item>
</v-list>
</v-menu>
<v-btn to="/page2">go</v-btn>
<v-btn to="/page1">go</v-btn>
</div>
</template>
<script>
data: () => ({
items: [
{ title: 'Click Me' },
{ title: 'Click Me' },
{ title: 'Click Me' },
{ title: 'Click Me 2' },
],
}),
}
</script>
```
</details>
> fix: ignore click outside if component is being destroyed

- packages/vuetify/src/components/VDataTable/VEditDialog.sass
- packages/vuetify/src/components/VDataTable/VEditDialog.ts
- packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VEditDialog.spec.ts.snap
Fix editability of VEditDialog with empty content
Wrap with `<div>` tag to keep activation region instead of single `<span>` tag
Fixes #8465 
- tweak unit test
- visually
<details>
```vue
<template>
<v-card max-width=400>
<v-container>
<v-data-table
>
<template v-slot:item.name="props">
<v-edit-dialog
:return-value.sync="props.item.name"
> {{ props.item.name }}
<template v-slot:input>
<v-text-field
v-model="props.item.name"
:rules="[max25chars]"
label="Edit"
single-line
counter
</template>
</template>
<template v-slot:item.iron="props">
<v-edit-dialog
:return-value.sync="props.item.iron"
large
persistent
@save="save"
@cancel="cancel"
@open="open"
@close="close"
>
<div>{{ props.item.iron }}</div>
<template v-slot:input> …
```
> fix(VEditDialog): fix editability of VEditDialog

- packages/docs/src/lang/en/components/ExpansionPanels.json
While migrating from 1.5.x to 2.x I noticed a behavioral change with v-expansion-panels.  The
documentation for the value prop is incorrect.  It says its an array (of booleans, not integers) for
when the 'expand' prop is used.  'expand' is now deprecated and has been replaced with 'multiple'
To ease the path of migration from 1.5.x to 2.0, for those that use v-expansion-panels.
1. ```yarn build dev```
1. Visit the documentation server
1. Search for v-expansion-panels
1. Verify the text for the value prop has been updated and is correct.
> docs(v-expansion-panels): incorrect documentation for the value prop

- packages/vuetify/src/components/VDataTable/VDataTable.sass
fixes #8492
visually 
<details>
```vue
<template>
<div>
<v-data-table :items="[]" :headers="[{ value: 'foo' }]" #no-data>
<v-btn>Click</v-btn>
</div>
</template>
```
</details>
> fix(VDataTable): remove pointer-events: none for empty wrapper

- packages/docs/src/data/pages/components/Grids.json
- packages/docs/src/data/pages/styles/Flex.json
- packages/docs/src/examples/grids/playground.vue
- packages/docs/src/examples/grids/simple/vertical-alignment.vue
- packages/docs/src/lang/en/components/Grids.json
- packages/docs/src/lang/en/styles/Flex.json
The new grid struggles with vertical alignment if there is no explicit `height` set, `min-height` is not enough, @KaelWD @johnleider maybe this is something we could document as caveat? the bootstrap grid has the same problem. 
visually
<details>
```vue
```
</details>
> docs(VGrid): fix examples for IE11 usage

- packages/vuetify/src/mixins/data-iterable.js
- packages/vuetify/test/unit/mixins/data-iterable.spec.js
Selection should not be changed when totalItems is set (that is when server-side pagination is involved).
Fixes #6472 
unit
<details>
```vue
<template>
<v-data-table
select-all
:pagination.sync="pagination"
:total-items="totalDesserts"
>
<td>
<v-checkbox
v-model="props.selected"
primary
hide-details
></v-checkbox>
</td>
<td class="text-xs-right">{{ props.item.iron }}</td>
</template> …
```
> fix(DataIterable): do not update selection if totalItems is set

- packages/vuetify/src/components/VAppBar/VAppBar.ts
- packages/vuetify/src/components/VAppBar/__tests__/VAppBar.spec.ts
When using **hide-on-scroll** in combination with **extended**, **elevate-on-scroll** would not work
as expected.
fixes #8516
When using **hide-on-scroll** in combination with **extended**, **elevate-on-scroll** would not work as expected.
fixes #8516
Unit tests
Visually
<details>
```vue
<template>
<v-container>
<div>
<v-col cols="3" md="2">
<v-switch v-model="elevateOnScroll" label="Elevate-on-scroll"></v-switch>
</v-col>
<v-col cols="3" md="2">
<v-switch v-model="hideOnScroll" label="Hide-on-scroll"></v-switch>
</v-col>
<v-col cols="3" md="2">
<v-switch v-model="extended" label="Extended"></v-switch>
</v-col>
</v-row>
<v-card class="overflow-hidden">
<v-app-bar
absolute
scroll-target="#playground-example"
:color="color"
:elevate-on-scroll="elevateOnScroll" …
```
> fix(VAppBar): fix elevation issue when extended

- packages/vuetify/src/components/VFileInput/VFileInput.ts
Safari does not seem to emit an input event when selecting a file, even though
from what I can see the HTML spec says both an input and change event should
be emitted.
closes #7941
playground
<details>
```vue
<template>
<v-container class="pa-0">
<v-file-input label="File input" v-model="asd"></v-file-input>
{{ asd }}
</v-container>
</template>
<script>
data: () => ({
asd: null,
mode: 'hex',
color: '#ff00ff'
}),
watch: {
asd (v) {
console.log(v)
}
}
}
</script>
```
</details>
> fix(VFileInput): bug in Safari where file is not added

- packages/vuetify/src/components/VDataTable/VDataTable.ts
- packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts
- packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
footer.page-text slot was not being passed on to data-footer
closes #8120
<details>
```vue
<template>
<v-data-table :items=[{}]>
<template v-slot:footer.page-text="{ pageStart, pageStop }">
Items: {{ pageStart }} - {{ pageStop }}
</template>
</v-container>
</template>
```
</details>
> fix(VDataTable): footer.page-text slot not being used

- packages/vuetify/src/components/VDataTable/VDataTable.ts
mismatch of nodes because ssr renders in mobile
closes #7410>
visually
<details>
tested with https://github.com/csheppard/nuxt-vuetify-2
</details>
> fix(VDataTable): mismatch of nodes when using ssr

- packages/vuetify/src/components/VDataIterator/VDataFooter.ts
- packages/vuetify/src/components/VDataIterator/__tests__/VDataFooter.spec.ts
- packages/vuetify/src/components/VDataIterator/__tests__/__snapshots__/VDataFooter.spec.ts.snap
fixes #8577
visually, jest
<details>
```vue
<template>
<div>
<v-data-table
:headers="[]"
:items="[]"
:footer-props="{showFirstLastPage: true}"
<v-data-table
:headers="[{value:'foo'}]"
:items="[{foo: 'foo'}]"
:footer-props="{showFirstLastPage: true}"
<v-data-table
:headers="[{value:'foo'}]"
:items-per-page="2"
:items="[{foo: 'foo'},{foo: 'foo'},{foo: 'foo'},{foo: 'foo'}]"
:footer-props="{showFirstLastPage: true}"
<v-data-table
:headers="[{value:'foo'}]"
:items-per-page="2"
:items="[{foo: 'foo'},{foo: 'foo'}]"
:footer-props="{showFirstLastPage: true}"
</div>
</template>
```
</details>
> fix(VDataFooter): disable last page button if there's no items

- packages/vuetify/src/components/VData/VData.ts
- packages/vuetify/src/components/VDataIterator/VDataIterator.ts
- packages/vuetify/src/components/VDataTable/VDataTable.ts
- packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts
default to first itemsPerPage option if itemsPerPage is not found in list of options
closes #8184
<details>
```vue
<template>
<div>
<v-data-table
:items="items"
:footer-props="{itemsPerPageOptions: [{text: 'five', value: 5},6,7]}"
<v-data-table
:items="items"
:items-per-page.sync="itemsPerPage"
:footer-props="{itemsPerPageOptions: [{text: 'five', value: 5},6,7]}"
{{ itemsPerPage }}
<v-data-table
:items="items"
:footer-props="{itemsPerPageOptions: [{text: 'five', value: 5},6,7]}"
{{ options }}
<v-data-table
:items="items" …
```
> fix(VDataTable): default to first itemsPerPage option

- packages/docs/src/data/pages/components/FileInputs.json
The link in the docs went to the directory for VAutocomplete instead of VFileInput. I fixed it so it links to the right component directory
While browsing the docs, clicking the link for the source went to the directory for the wrong component.
No, just a documentation/metadata fix
> Fix link to component for VFileInput

- packages/docs/src/examples/file-inputs/complex/advanced.vue
- packages/docs/src/examples/file-inputs/simple/counter.vue
- packages/kitchen/src/pan/File Inputs.vue
Updated 2 examples that were not working as expected, and the kitchen pan file
Changed the uses of the prop `display-size` to `show-size` in FileInputs examples and in the kitchen pan file.
The examples that were supposed to show the file size were not working in the docs.
Visually
> Doc examples for FileInputs: display-size -> show-size

- packages/docs/src/lang/en/components/DataTables.json
That text paragraph is displaying `hide-default-headers` right now, but the prop name is in the singular, `hide-default-header`.
Thanks for Vuetify!
Wrong prop name in doc.
The other prop to hide the footer is correct.
<details>
```vue
```
</details>
> docs(VDataTable): fix prop name for hide-default-header

- packages/vuetify/src/components/VItemGroup/VItemGroup.ts
- packages/vuetify/src/components/VWindow/VWindow.ts
- packages/vuetify/src/components/VWindow/VWindowItem.ts
- packages/vuetify/src/components/VWindow/__tests__/VWindowItem.spec.ts
From time to time, the transition state of the VWindow container is
not finished and the height will be fixed. This change fixed this
problem.
FINDINGS:
- If transitionend fired before nextTick(), then done() is never
going to be invoked.
- onEnter() itself may be re-entered during transiton. Then the
state is messed up.
- onBeforeLeave() may be called after cancel, then the height
is stuck.
- onBeforeEnter() may be re-entered after first call. Calling
this multiple times also wrongly reset transition state.
SOLUTION:
- Put correct guards on each event handler. Check of isActive and
wasCancelled accordingly for each event to prevent re-entrant.
- Put a timer in onEnter() to ensure done() is always invoked and
deactivate() after timeout if anything goes wrong.
TESTS:
- Add log …
> fix(#6962): Fix race conditions in VWindowItem.ts during transition.

- packages/vuetify/src/components/VDatePicker/VDatePickerYears.ts
When only min property is set with no active year, the scroll top position is defined to be equal to the scroll height.
When only max property is set with no active year, the scroll top position is defined to 0.
When min/max properties are used and lower than current selected date for max property or higher for min property, the initial scroll on mount event was not practical.
playground
<details>
```vue
<template>
<v-date-picker
v-model="start"
:max="end"
reactive
/>
<v-date-picker
v-model="end"
:min="start"
reactive
/>
</v-row>
</v-container>
</template>
<script>
data: () => ({
end: null,
start: null
})
}
</script>
```
</details>
> fix(VDatePicker): improve scroll position of years selector

- packages/vuetify/src/services/theme/__tests__/__snapshots__/theme.spec.ts.snap
- packages/vuetify/src/services/theme/__tests__/theme.spec.ts
- packages/vuetify/src/services/theme/index.ts
Ensure Vuetify theme works with both `vue-meta@1` & `vue-meta@2`
People using `vue-meta@1` are having errors when upgrading Vuetify and have no clues about upgrading `vue-meta`. Cause `$meta().getOptions()` only exist in `vue-meta@2`.
```
TypeError: root.$meta(...).getOptions is not a function
```
jest
> fix(Theme): provide backward compatibility for vue-meta@1

- packages/vuetify/src/services/icons/__tests__/__snapshots__/icons.spec.ts.snap
- packages/vuetify/src/services/icons/presets/fa4.ts
Use correct icon: `far fa-square` instead of `fa fa-square-o`.
Fixes #8998
Updated snapshot.
https://codepen.io/leftclickben/pen/rNBZQOa
> fix(VCheckbox): use correct unchecked checkbox icon using FA4

- packages/vuetify/src/components/VPicker/VPicker.sass
make time picker clock in center when using seconds and am/pm in title
**Before:**
**After:**
:guitar: 
visually
```vue
<v-time-picker
v-model="picker"
ampm-in-title
use-seconds
></v-time-picker>
```
> fix(VTimePicker) Center Picker Clock 

- packages/docs/src/lang/en/components/Buttons.json
- packages/vuetify/src/components/VBtn/VBtn.ts
- packages/vuetify/src/components/VBtn/__tests__/VBtn.spec.ts
Add `retainFocusOnClick` prop.
@johnleider asked.
`jest` + visually
<details>
```vue
<template>
<v-btn>Button</v-btn>
</v-container>
</template>
```
</details>
> feat(VBtn): add retainFocusOnClick property

- packages/vuetify/src/components/VData/VData.ts
- packages/vuetify/src/components/VDataIterator/VDataIterator.ts
- packages/vuetify/src/components/VDataTable/VDataTable.ts
changed logic around showing empty messages so that it uses original items length and filtered items length instead of relying on `search` prop.
closes #8131
playground
<details>
```vue
<template>
<div>
<v-data-table
:items="items"
/>
<v-data-table
:items="[]"
/>
<v-data-table
:items="[]"
loading
/>
<v-data-table
:headers="headers2"
:items="items"
search="ö"
/>
<v-data-table
:headers="headers2"
:items="items"
/>
</div>
</template>
<script>
data: () => ({
headers: [
{
value: 'foo',
text: 'Foo',
filter: () => false
}
],
headers2: [
{
value: 'foo',
text: 'Foo',
}
],
items: [
{ foo: 1 }
]
})
}
</script>
```
</details>
> [Bug] fix(VDataTable): show no-results when custom filter returns zero rows

- packages/vuetify/src/components/VCalendar/VCalendarWeekly.sass
As per specification, flex child elements should have `min-height:0` (min-width for rows) to
prevent element overflow. See https://bugzilla.mozilla.org/show_bug.cgi?id=1114904
Without this properties, the `v-calendar-weekly__week` expands to include all event elements and calendar overflows parent element. In cases where there are a lot of events, and `event-more="true"` is set, `updateEventVisibility` method in the `calendar-with-events` mixin can't properly hide events.
Fixes #8319
visually
<details>
```vue
<template>
<v-sheet height="600">
<v-calendar
v-model="focus"
:event-margin-bottom="3"
:now="today"
type="month"
></v-calendar>
</v-sheet>
</template>
<script>
data: () => ({
today: "2019-01-08",
focus: "2019-01-08",
events: [
{
name: …
```
> fix(VCalendar): proper week height in month view on Firefox

- packages/vuetify/src/components/VCarousel/VCarousel.ts
- packages/vuetify/src/components/VCarousel/VCarouselItem.ts
- packages/vuetify/src/components/VWindow/VWindow.ts
- packages/vuetify/src/components/VWindow/VWindowItem.ts
- packages/vuetify/src/components/VWindow/__tests__/VWindowItem.spec.ts
Add an intermediate height to overwrite component internal height if internalHeight is undefined.
This change makes VWindow universally respect internalHeight if set without special flags.
Improve VWindow.
Test on v-tabs and v-carousel docs.
> fix(VCarousel): Always respect original internal height of VWindow.

- packages/docs/src/lang/en/components/BottomSheets.json
- packages/docs/src/lang/en/components/Dialogs.json
- packages/docs/src/lang/en/components/NavigationDrawers.json
- packages/docs/src/lang/en/mixins/Overlayable.json
- packages/vuetify/src/mixins/overlayable/index.ts
Added overlay-color and overlay-opacity props to overlayable mixin
Added overlayable translation strings file in english
There was no way to control the opacity or color of the overlay on VBottomSheet, VDialog and
VNavigationDrawer components.  
The overlayable mixin was apparently only used for the hide-overlay prop.
Fixes #8301
visually
<details>
```vue
<v-dialog
overlay-opacity="0.9"
overlay-color="red"
> ... </v-dialog>
<v-bottom-sheet
v-model="sheet"
overlay-opacity="1"
overlay-color="green"
> ... </v-bottom-sheet>
overlay-opacity="0.5"
overlay-color="blue"
absolute
temporary
> ... </v-navigation-drawer>
```
</details>
> feat: added color and opacity props to overlayable mixin

- packages/docs/src/data/pages/components/DatePickers.json
- packages/docs/src/examples/date-pickers/intermediate/date-range.vue
- packages/docs/src/lang/en/components/DatePickers.json
- packages/kitchen/src/pan/Date pickers.vue
- packages/vuetify/src/components/VDatePicker/VDatePicker.ts
- packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.date.spec.ts
#1646
Allow datepicker to pick range.
By add new prop "Range", a workaround is provided to handle range picking.
- Value will be kept as an array of size 2 to save [From, To].  New click will clear the array
- Any dates between will be displayed as "selected"
- Can select with both direction (From then To, or To then From)
[#1646 ](https://github.com/vuetifyjs/vuetify/issues/1646)
visually and unit
<details>
```vue
<template>
<v-container>
<v-date-picker v-model="dates" range width="290" class="mt-4"></v-date-picker>
v-model value: {{ dates }}
<v-menu ref="menu" v-model="menu" :close-on-content-click="false" transition="scale-transition" offset-y min-width="290px">
<v-text-field :value="dateRangeText" label="Date range" prepend-icon="event" readonly …
```
> feat(VDatePicker): pick date range

- packages/vuetify/src/components/VInput/VInput.ts
- packages/vuetify/src/components/VInput/__tests__/__snapshots__/VInput.spec.ts.snap
Adds role alert to `v-messages__wrapper` so that screenreader can read message/error/hint
Fixes #8431
visually | chromevox
<details>
```vue
<template>
<v-container>
<v-switch
v-model="success"
label="Success"
/>
<v-switch
v-model="error"
label="Error"
/>
<v-switch
v-model="hint"
label="Hint"
/>
<v-input
:error="error"
:error-messages="error ? message : ''"
:hint="message"
:success="success"
:success-messages="success ? message : ''"
:persistent-hint="hint"
>
Input
</v-input>
<v-text-field
label="Textfield"
:error="error"
:error-messages="error ? message : ''"
:hint="message"
:success="success"
:success-messages="success ? message : ''"
:persistent-hint="hint"
<v-select
label="Select"
:error="error"
:error-messages="error ? message : ''"
:hint="message"
:success="success" …
```
> fix(VInput): add role alert to success/error messages

- packages/vuetify/src/components/VDialog/VDialog.sass
- packages/vuetify/src/components/VDialog/VDialog.ts
- packages/vuetify/src/components/VMenu/VMenu.sass
- packages/vuetify/src/components/VMenu/VMenu.ts
- packages/vuetify/src/components/VTooltip/VTooltip.sass
- packages/vuetify/src/components/VTooltip/VTooltip.ts
Adds `display: none` to the root element unless it's attached to itself (because then we'd be hiding the content too)
fixes #6951
The previous commit 97681ce only helps in an inline context
> fix(VDialog/VMenu/VTooltip): hide wrapper element when not attached

- packages/vuetify/src/locale/tr.ts
Full turkish language update of current release
I translated fully the tr.ts
There was a lot of translation missing.
Tested on my last project.
<details>
```vue
```
</details>
> Turkish translate

- packages/vuetify/src/components/VCard/__tests__/VCard.spec.ts
- packages/vuetify/src/components/VProgressLinear/VProgressLinear.ts
- packages/vuetify/src/components/VProgressLinear/__tests__/VProgressLinear.spec.ts
- packages/vuetify/src/components/VProgressLinear/__tests__/__snapshots__/VProgressLinear.spec.ts.snap
- packages/vuetify/src/components/VTextField/__tests__/VTextField.spec.ts
- packages/vuetify/src/components/VTextField/__tests__/__snapshots__/VTextField.spec.ts.snap
fixes #8419
visually, added snapshots
<details>
```vue
<template>
<v-container>
<v-btn block @click="$vuetify.rtl = !$vuetify.rtl">{{ $vuetify.rtl ? 'rtl' : 'ltr' }}</v-btn>
<v-row>
<v-col cols="12" class="align-self-center text-center my-0 py-0">
<v-card class="pa-2 mx-auto mt-2" width="250">
<v-progress-linear value="100" />
</v-card>
<v-card class="pa-2 mx-auto mt-2" width="250">
<v-progress-linear value="90" />
</v-card>
<v-card class="pa-2 mx-auto mt-2" width="250">
<v-progress-linear value="80" />
</v-card>
<v-card class="pa-2 mx-auto mt-2" width="250">
<v-progress-linear value="70" />
</v-card>
<v-card class="pa-2 mx-auto mt-2" width="250">
<v-progress-linear value="60" />
</v-card>
<v-card class="pa-2 mx-auto mt-2" width="250">
<v-progress-linear value="50" />
</v-card>
<v-card …
```
> fix(VProgressLinear): invalid background position in RTL mode

- packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts
blur and focus events should fire on `v-autocomplete` and `v-combobox`
resolves #9204
<details>
```vue
<template>
<v-row>
Blur: {{ blur }}
Focus: {{ focus }}
<v-combobox
v-model="combo"
:items="items"
@blur="blur++"
@focus="focus++"
></v-combobox>
v-model="auto"
:items="items"
label="Select a favorite activity or create a new one"
@blur="blur++"
@focus="focus++"
</v-col>
</v-row>
<v-row>
chips
:items="['Aaa', 'Bbb', 'Ccc', 'Ddd']"
:value="select1"
label="1. Chips"
/>
multiple
:items="['Aaa', 'Bbb', 'Ccc', 'Ddd']"
:value="select2"
label="2. Multiple"
/>
multiple
chips
:items="['Aaa', 'Bbb', 'Ccc', 'Ddd']" …
```
> fix(vautocomplete): make focus and blur events fire

- packages/vuetify/src/mixins/binds-attrs/index.ts
fix #9171
The watchers with `immediate: true` is removed as using $set in it causes issue in transition groups. Instead, the immediate watchers' initialization are moved to created.
The current bind-attrs uses $set inside immediate watchers to set attrs$ and listeners$, this causes issues with transition groups where the enter animation directly "snaps". It seems to be a bug in Vue and I have opened [an issue there](https://github.com/vuejs/vue/issues/10596).
It fixes #9171.
The changes are tested in [codesandbox](https://codesandbox.io/s/vue-transition-group-bug-wnvwv) and on my personal project.
<details>
```vue
<template>
<div id="app">
<input v-model="open" id="toggle" type="checkbox">
<label for="toggle">Toggle transition</label>
<transition-group name="scale">
<test v-if="open" …
```
> fix(bind-attrs): fix transition-group animation

- packages/vuetify/src/components/VDatePicker/VDatePicker.ts
- packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.ts
Check date selection for range in the current month only.
Currently smooth to support range as big as '0000-01-01', '2019-09-20', should be enough.
https://github.com/vuetifyjs/vuetify/issues/9120
visually
<details>
```vue
<template>
<v-container>
<v-date-picker v-model="dates" range width="290" class="mt-4"></v-date-picker>
v-model value: {{ dates }}
</v-container>
</template>
<script>
data: () => ({
dates: ['0000-01-01', '2019-09-20'],
})
}
</script>
```
</details>
> Fix/#9120 VDatePicker range performance

- packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.date.spec.ts
- packages/vuetify/src/components/VDatePicker/util/isDateAllowed.ts
fix #9039
Fix min date compare logic (Inclusive)
https://github.com/vuetifyjs/vuetify/issues/9039
Visually and added unit test
<details>
```vue
<template>
<v-container>
{{ min }}
<v-date-picker :min="min"></v-date-picker>
</v-container>
</template>
<script>
data: () => ({
min: '2019-09-28T15:55:56.441Z'
})
}
</script>
```
</details>
> fix(vdatepicker): fix min date

- packages/vuetify/src/components/VTextField/VTextField.ts
Element.scrollWidth returns full element width while Element.offsetWidth returns width of visible part
Without this fix input border has incorrect notch width
https://codepen.io/djaler/pen/abbzeMw
visually
> fix(VTextField): use scrollWidth instead to calculate label width

- packages/docs/src/lang/en/components/Grids.json
As per MDN web docs and component `VRow.ts` alignValidator, `align` property on `v-row` component does not accept `space-between` nor `space-around` options. However, it does accept `baseline`
option. Changes made on documentation to reflect those constraints
* Why is this change required? What problem does it solve?
I found out about this documentation error trying to apply `align="space-around"` on a `v-row` component. This throws an error by [VRow.ts alignValidator](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VGrid/VRow.ts#L19)
I followed the [Contribution Guide](https://vuetifyjs.com/en/getting-started/contributing) to create a local repo.
Visually tested modifications on the [Grid Page](https://vuetifyjs.com/en/components/grids#api)
> [Docs]: Grid > VRow: align property changed to match validator

- packages/vuetify/src/components/VRating/VRating.ts
passes `x-small` size into `v-icon`
fixes #9350 
visually
<details>
```vue
<template>
<v-row>
<v-rating small></v-rating>
<v-rating x-small></v-rating>
</v-col>
</v-row>
</v-container>
</template>
<script>
data: () => ({}),
}
</script>
```
</details>
> fix(VRating): pass in x-small icon size

- packages/docs/src/examples/data-iterators/filter.vue
Fixed bug with highlight color that was not being applied when the user sort the data. The old code was applying a color dinamically if the sortBy === key, but that color was being overwritten by a v-list-item default style, so the text always keep the original color.
Motivation: I'm happy with Vue and Vuetify and i would feel good with myself helping this great community.
Context: I used this code and saw the bug.
I am not test anything, but here is my adaptation and works:
<details>
```vue
```
</details>
> Fixed bug with highlight color when sorting

- packages/vuetify/src/components/VTextField/VTextField.sass
Fix dense text fields when it outlined and filled
fixes #9256 
visually
<details>
```vue
<v-text-field outlined filled dense label="TextField"></v-text-field>
```
</details>
> fix(VTextField): dense filled & outlined

- packages/vuetify/src/components/VPagination/VPagination.ts
- packages/vuetify/src/components/VPagination/__tests__/VPagination.spec.ts
Fix calculation of max pagination length.
Pagination should not show more pages than was setted in totalVisible. 
I have over 74000 pages and now VPagination render them all before maxButtons is calculated, it cause some performance issues. 
unit
> fix(VPagination): max length

- packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.ts
Fixed bug with calendar that could run html with a event name.
I found that event name of calendar can run html. This causes an XSS vulnerability just by loading the calendar. As a countermeasure, escape html of calendar event name.
visually
This is same as `docs/src/examples/calendars/complex/events.vue` expect for "Large Event" name is `<h1>Large Event</h1>`.
<details>
```vue
<template>
<v-row class="fill-height">
<v-col>
<v-sheet height="64">
<v-toolbar flat color="white">
<v-btn outlined class="mr-4" @click="setToday">
Today
</v-btn>
<v-btn fab text small @click="prev">
<v-icon small>mdi-chevron-left</v-icon>
</v-btn>
<v-btn fab text small @click="next">
<v-icon small>mdi-chevron-right</v-icon>
</v-btn>
<v-toolbar-title>{{ title }}</v-toolbar-title>
<div …
```
> fix(VCalendar): escape html of event name

- packages/api-generator/src/maps/v-data.js
- packages/docs/src/lang/en/components/Data.json
- packages/kitchen/src/pan/Table.vue
- packages/vuetify/src/components/VData/VData.ts
- packages/vuetify/src/components/VData/__tests__/VData.spec.ts
- packages/vuetify/src/util/helpers.ts
By setting the customGroup property a custom function executed while grouping can be defined similar to the customSort property.
Example use cases: group alphabetically by first char, group by numeric ranges, group by properties which contain an object
<details>
```vue
<template>
<v-data-table
:items="items"
:group-by="'value'"
:custom-group="groupBy"
>
</v-container>
</template>
<script>
data: () => ({
headers: [
{text: 'ID', value: 'id'},
{text: 'Name', value: 'name'},
{text: 'Value', value: 'value'},
],
items: [
{id: 1, name: 'Test1', value: 2},
{id: 2, name: 'Test2', value: 3},
{id: 3, name: 'Test3', value: 1},
{id: 4, name: 'Test4', value: 2},
{id: 5, name: 'Test5', value: 3},
{id: 6, name: 'Test6', value: 1},
], …
```
> feat(vdata): custom grouping functions

- packages/vuetify/src/components/VIcon/VIcon.sass
The `dense` prop not working on VIcon.
The Issue
https://codepen.io/dev0x0/pen/rNNzdwp
visually
> fix(VIcon): Dense Font Size Selector

- packages/vuetify/src/services/theme/utils.ts
Very simple. Exporting two helper functions (`lighten` and `darken`) from `services/theme/utils`.
I use these functions in my app -- user can input their own color theme, and then I uses these functions to lighten/darken their inputs in various places in the UI. (There are many color choices users make, more than the standard `primary`, `secondary`, `info`, etc will allow, therefore I keep my own color state and need to call these function directly.)
Currently, I have to duplicate these functions to make use of them. I.e. In my app I have this code:
```javascript
import * as sRGB from 'vuetify/es5/util/color/transformSRGB'
import * as LAB from 'vuetify/es5/util/color/transformCIELAB'
function lighten(value, amount) {
const lab = LAB.fromXYZ(sRGB.toXYZ(value))
lab[0] = lab[0] + amount * 10 …
```
> Export `lighten` and `darken` functions

- packages/docs/src/snippets/ts/create_translation.txt
Adding missing translation to the example in documentation, which has been added to the general codebase in [this commit](https://github.com/vuetifyjs/vuetify/commit/6c491286b0bbda6d7b29334804094c2327071297), discussed in [this issue](https://github.com/vuetifyjs/vuetify/issues/8083).
When using a custom translation (Czech for example), there is default English label "Sort by".
> Add missing example translation: Sort by

- packages/docs/src/layouts/layouts/demos/google-contacts.vue
Change the icons used in the Google Contacts demo layout to use the proper mdi icons.
Icons being used in the demo are not compatible with a freshly created vuetify app.
visually
> docs: fix icons used in google contacts demo layout

- packages/docs/src/snippets/ts/create_translation.txt
This undocumented translation results in `[Vuetify] Translation key "dataFooter.pageText" not found, falling back to default` notice in the console and default English text being displayed when using custom language.
Similar to previous MR https://github.com/vuetifyjs/vuetify/pull/9558
When using a custom translation (Czech for example), there is default English label "of", and notice in the console.
I've added the translation to my `vuetify.cs.js` and the table paging now has correct label.
> Add missing example translation: pageText

- packages/vuetify/src/components/VColorPicker/__tests__/VColorPicker.spec.ts
- packages/vuetify/src/components/VColorPicker/__tests__/__snapshots__/VColorPicker.spec.ts.snap
- packages/vuetify/src/components/VColorPicker/util/index.ts
fixes issue when initial value is null
closes #9472
<details>
```vue
<template>
<v-container>
<v-color-picker v-model="color"></v-color-picker>
Color: {{color}}
</v-container>
</template>
<script>
data () {
return {
color: null
}
},
}
</script>
```
</details>
> fix(VColorPicker): allow null as initial value

- packages/docs/src/examples/cards/complex/weather.vue
- packages/docs/src/examples/chips/complex/photos.vue
- packages/docs/src/examples/data-tables/intermediate/expand.vue
Hard coded colors used in 
https://github.com/vuetifyjs/vuetify/blob/master/packages/docs/src/examples/data-tables/intermediate/expand.vue
https://github.com/vuetifyjs/vuetify/tree/master/packages/docs/src/examples/cards/complex/weather.vue
https://github.com/vuetifyjs/vuetify/tree/master/packages/docs/src/examples/chips/complex/photos.vue
Causing components to appear white in dark theme
> docs: removed hard coded colors to work with dark theme

- packages/vuetify/types/services/theme.d.ts
Do we want `parsedTheme` and `generatedStyles` as well?
Probably not, seems that it's only for internal use
fixes #9546
> fix(types): missing currentTheme in Theme interface

- packages/vuetify/src/components/VSlider/VSlider.sass
fixes #9660
playground
<details>
```vue
<template>
<v-container>
<v-slider 
:value="30" 
prepend-icon="storage" 
:messages="['Message']" 
append-icon="storage" 
label="Slider" 
@click:append="alert" 
@click:prepend="alert" 
readonly 
/>
<v-range-slider 
:value="[30,70]" 
prepend-icon="storage" 
:messages="['Message']" 
append-icon="storage" 
label="Slider" 
@click:append="alert" 
@click:prepend="alert" 
readonly 
/>
</v-container>
</template>
<script>
methods: {
alert: () => alert('clicked')
}
}
</script>
```
</details>
> fix(VSlider): label is not disabled in readonly slider

- packages/vuetify/src/locale/ca.ts
Update catalan translations were missing.
Update catalan translations were missing.
Catalan translations were missing.
<details>
```vue
```
</details>
> fix(translations): Update catalan translations

- packages/vuetify/src/components/VCombobox/VCombobox.ts
- packages/vuetify/src/components/VFileInput/VFileInput.ts
- packages/vuetify/src/components/VSelect/VSelect.ts
- packages/vuetify/src/components/VSelect/__tests__/VSelect2.spec.ts
- packages/vuetify/src/components/VTextField/VTextField.ts
- packages/vuetify/src/components/VTextField/__tests__/VTextField.spec.ts
- packages/vuetify/src/components/VTextField/__tests__/__snapshots__/VTextField.spec.ts.snap
added customizable counter value via optional function
_I messed up a previous branch #8790, this is the same but recreated_
closes #8788 
unit test
<details>
```vue
<template>
<v-text-field
counter
:counter-length="(value) => (value || '').replace(/\s/g).length"
</template>
```
</details>
> feat(VTextField): add customizable counter value

- packages/vuetify/src/components/VIcon/VIcon.ts
Add support for Font Awesome duotone icons
fix #8398 
I was not able to test this as i don't have a Font Awesome Pro license, but judging by the other types of Font Awesome icons it shouldn't require more than this. Would love if someone could test it for me.
> feat(vicon): add font awesome duotone support fix #8398

- packages/docs/src/lang/en/components/Selects.json
- packages/vuetify/src/components/VSelect/VSelect.ts
Currently, there's no way to disable keyboard lookup when using VSelect.
Add a new prop to disable the lookup.
When the user is typing, the intermediate search result items are selected. This can break other things on the page. See #9271
Visually.
<details>
```vue
```
</details>
> feat: Add prop for disabling keyboard lookup in VSelect

- packages/vuetify/src/components/VTreeview/VTreeview.ts
- packages/vuetify/src/components/VTreeview/__tests__/VTreeview.spec.ts
- packages/vuetify/src/components/VTreeview/__tests__/__snapshots__/VTreeview.spec.ts.snap
the initial loading of active/open/selected items did not take into account `return-object` prop.
closes #8709
<details>
```vue
<template>
<v-container>
<v-row>
</v-col>
<v-card>
<v-card-title>Treeview</v-card-title>
<v-treeview selectable v-model="selection" :items="items" activatable :active.sync="asd" :open.sync="open" return-object></v-treeview>
<v-btn color="primary" @click="selection = [{id: '1', name: 'One'}]">Select One</v-btn>
</v-card>
</v-col>
<v-card>
{{ selection }}
</v-card>
</v-col>
</v-row>
</v-container>
</template>
<script>
const one = {id: '1', name: 'One'}
const three = { id: '3', name: 'Three' }
const two = {id: '2', name: 'Two', children: [three]}
export …
```
> fix(VTreeview): load initial selection when using return-object

- packages/vuetify/src/components/VDataIterator/VDataIterator.ts
- packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts
bug where in single-select mode we did not emit a 'deselect' item-select event for previously selected item when selecting a new one.
closes #8477
<details>
```vue
<template>
<div>
<v-data-table :headers="header" :items="people" single-select show-select @item-selected="itemSelected">
<template v-slot:item.libelle="{ item }">
<td class="text-xs">{{ item.libelle }}</td>
</template>
</div>
</template>
<script>
data: () => ({
header: [
{
value: 'name',
text: 'Name'
}
],
people: [
{
id: 1,
name: 'John D.'
},
{
id: 2,
name: 'Jack M.'
}
]
}),
methods: {
itemSelected(item) {
console.log('Item : ' + item.item.name + ' value : ' + item.value)
}
}
}
</script>
```
</details>
> fix(VDataIterator): emit two item-selected events in single-select mode

- packages/vuetify/src/components/VTextField/VTextField.ts
- packages/vuetify/src/mixins/intersectable/__tests__/intersectable.spec.ts
- packages/vuetify/src/mixins/intersectable/index.ts
fixes #9299
Use IntersectionObserver (if it available) to recalculate element width after input becomes visible, 
Cause they have zero width on mount in hidden state (inside expansion panel, for example)
https://github.com/vuetifyjs/vuetify/issues/9299
visually
https://codepen.io/djaler/pen/oNNXywM
> fix(VTextField): use intersect to recalculate elements width

- packages/api-generator/src/maps/v-data-iterator.js
- packages/vuetify/src/components/VDataIterator/VDataIterator.ts
- packages/vuetify/src/components/VDataIterator/__tests__/VDataIterator.spec.ts
the toggle-select-all event was added in #8975, but it only has checked value, not the actual items
closes #8532
<details>
```vue
<template>
<v-data-table
:single-select="singleSelect"
show-select
</template>
<script>
data () {
return {
singleSelect: false,
selected: [],
headers: [
{
align: 'left',
value: 'name',
},
],
desserts: [
{
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0, …
```
> feat(VDataIterator): add current items to toggle-select-all event

- packages/vuetify/src/components/VSelect/VSelect.ts
- packages/vuetify/src/components/VSelect/__tests__/VSelect4.spec.ts
When append-inner was clicked, the menu could be opened but not closed, this was cause by onClick
always setting the isMenuActive to true. Made a change to only allow onMouseUp totoggle isMenuActive
state when the append-inner icon is clicked
fix #6564
I create tests for the bug and ran the unit tests
<details>
```vue
<template>
<v-autocomplete  :items="states"></v-autocomplete>
</template>
<script>
data () {
return {
states: [
'Alabama', 'Alaska', 'American Samoa', 'Arizona',
'Arkansas', 'California', 'Colorado', 'Connecticut',
'Delaware', 'District of Columbia', 'Federated States of Micronesia',
'Florida', 'Georgia', 'Guam', 'Hawaii', 'Idaho',
'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky',
'Louisiana', 'Maine', 'Marshall Islands', 'Maryland',
'Massachusetts', …
```
> fix(VSelect): change onMouseUp to handle menu toggle on mouse events

- MIGRATION.md
Add missing '>' to activator example in migration guide
The migration guide is missing the closing > for the new activator slot syntax which may be confusing to those who have not seen the syntax before.
> Add missing '>' to activator example in migration guide

- packages/api-generator/src/maps/v-data-table.js
- packages/vuetify/src/components/VDataTable/VDataTable.ts
Adds 'isOpen' as a prop to the group.header slot.
Currently, the `toggle` function is passed as a prop to the `group.header` slot. However, when utilizing this method, you probably want to display a different icon depending on whether the header is opened or not (as is happening in the default implementation). 
Visually (playground)
<details>
```vue
<template>
<v-container>
<v-data-table :items="items" :headers="headers" group-by="type">
<template #group.header="{ isOpen, toggle }">
<v-btn @click="toggle" icon>
<v-icon>
{{ isOpen ? '$minus' : '$plus' }}
</v-icon>
</v-btn>
</template>
</v-container>
</template>
<script>
data: () => ({
items: [{
type: 1,
name: 'First',
}, {
type: 2,
name: 'Second',
}, {
type: 1,
name: 'Third'
}],
headers: [{
text: 'Type', …
```
> feat(VDataTable): add isOpen to group.header slot

- packages/vuetify/src/components/VDatePicker/VDatePicker.ts
- packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.month.spec.ts
fixes #9885
<details>
```vue
<template>
<v-date-picker v-model="dates" range type="month"></v-date-picker>
</template>
<script>
data: () => ({
dates: ['2019-09', '2019-11'],
}),
}
</script>
```
</details>
> fix(VDatePicker): range not working with month picker

- packages/vuetify/src/components/VTextarea/VTextarea.sass
The padding of VTextarea caused a VTextarea with one row to be 1px taller than a VTextField.  This pull request fixes the 1px difference.
When a VTextarea with one row is placed next to a VTextarea on the same row the 1px difference is noticeable. [This Codepen demonstrates the problem](https://codepen.io/logikgate/pen/QWwGoev)
Visually tested
[This Codepen demonstrates the problem](https://codepen.io/logikgate/pen/QWwGoev)
> fix(VTextarea): make height of 1 row equal to v-text-field

- packages/vuetify/src/components/VIcon/VIcon.ts
- packages/vuetify/src/components/VIcon/__tests__/__snapshots__/VIcon.spec.ts.snap
Fixes SVG icon style for prominent VAlert cound't be applied on SVG. This commit fixes the issue by wrapping the SVG with a span element. Relevant classes are applied to the wrapper.
fix #9670
Tested visually. Updated snapshots.
Steps to reproduce from #9670:
https://codepen.io/janvennemann/pen/gOOdpvq
How it should look:  https://codepen.io/janvennemann/pen/xxxaGmY
> fix(VIcon): svg icon style when using the prominent prop

- packages/docs/src/examples/data-tables/intermediate/sort.vue
Update VDataTable docs to reflect updated naming of `descending` prop.
It might be confusing for users to see description only here while everywhere else sortDesc is used now. especially migrating from 1.5.
Yes, I am that user :P
> chore: keep aligned with general naming of prop

- packages/docs/src/snippets/js/using_missing_material_icons.txt
The docs include an import of the outdated stylus file. Removing this to be aligned with other examples and current version.
Avoid confusion for readers.  
I think the example should still work because all other examples don't have this import.  
I'm not a 100% sure here.
Not tested.
> docs(icons): remove outdated stylus import

- packages/vuetify/src/components/VResponsive/VResponsive.sass
Alternate method of enforcing aspect ratio which works around buggy behavior in Firefox.
This is yet another attempt at fixing the issue. Unfortunately the previous fix, #10027 had unexpected regressions due to how it changed the DOM structure.
This fix is purely CSS, so it should be less prone to unexpected behavior. Can confirm it does not have the issues from #10094.
It seems the bug in Firefox is isolated to giving `flex: 0 0 0px` to the sizer element. Allowing it to have a size avoids the bug in Firefox, and the negative margin pulls the content back into the correct place. According to the flex spec, you should be able to use `visibility: collapse` on the sizer element to get this same result without the negative margin, [but the MDN documentation points out that Chrome and Safari …
> fix(VResponsive): tweak styles to work with Firefox

- packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts
- packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete3.spec.ts
fix #10036
e2e
<details>
```vue
<template>
<v-row>
<v-combobox
:items="items"
label="Select a favorite activity or create a new one"
></v-combobox>
</v-col>
</v-row>
</v-container>
</template>
<script>
data () {
return {
select: 'f',
items: [
'f',
'b',
],
}
},
}
</script>
```
</details>
> fix(vautocomplete): avoid setting selectedIndex to 0 after delete

- packages/vuetify/src/components/VDataTable/VSimpleTable.sass
[#9766](https://github.com/vuetifyjs/vuetify/pull/9766/files#diff-72b8d9f8f633be49d3762ae7ce4f9253L23-R23) introduced a bug causing all headers of data-table to be of primary text color instead of only active or hovered ones.
See: https://vuetifyjs.com/en/components/data-tables#usage
IMO only active or hovered headers should be of primary text color as it used to be before v2.2
visually
> fix(VDataTable): fix default table header color

- packages/vuetify/src/styles/elements/_global.sass
Overlayable adds the `overflow-y-hidden` class to the `html` element, but `overflow-y-hidden` is scoped to `v-application`, so the class has no effect.
https://github.com/vuetifyjs/vuetify/blob/4c616747b1142e2ad88a22994971ec5a27070f80/packages/vuetify/src/mixins/overlayable/index.ts#L217
Fixes #10086. This is causing issues with background scrolling on fullscreen dialogs, and open navigation drawers. @johnleider, this is also the suggested fix in #8105, so not sure if this hasn't been moved on due to a shortcoming in the fix.
Manually.
<details>
```vue
<template>
<v-dialog v-model="dialog" fullscreen hide-overlay transition="dialog-bottom-transition">
<v-btn color="primary" dark v-on="on">Open Dialog</v-btn>
</template> …
```
> fix(Overlayable): add html.overflow-y-hidden style

- packages/vuetify/src/components/VFileInput/VFileInput.sass
- packages/vuetify/src/components/VInput/VInput.sass
- packages/vuetify/src/components/VInput/VInput.ts
- packages/vuetify/src/components/VOverflowBtn/VOverflowBtn.sass
- packages/vuetify/src/components/VSelect/VSelect.sass
- packages/vuetify/src/components/VTextField/VTextField.sass
- packages/vuetify/src/components/VTextarea/VTextarea.sass
fixes #9488
fixes #10154
Restructured how colors are propagated through form controls, removed a lot of unneeded css. Fixed selection control label disabled color in the process.
Disabled styles had issues when a form control wrapped another form control.
visually
<details>
```vue
https://gist.github.com/johnleider/7b01f5f3fff3310c3b06fcf20f7b7e9a
```
</details>
> fix(form-controls): fix disabled styles

- packages/vuetify/src/components/VTextField/VTextField.sass
fix #10277
This PR fixes styling of legend in reverse outlined text field.
Issue #10277 
Visually tested
<details>
```vue
<template>
<v-container>
<v-text-field label="Label" value="Value" outlined reverse></v-text-field>
</v-container>
</template>
<script>
data: () => ({
//
})
}
</script>
```
</details>
> fix(VTextfield): legend position with reverse prop

- packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.sass
- packages/vuetify/src/styles/tools/_display.sass
- packages/vuetify/src/styles/tools/_index.sass
This makes the labels in VNavigationDrawer readable by screen readers by hiding them visually instead of using `display: none;`.
fixes #9741
I have tested it visually and using NVDA.
<details>
```vue
<template>
<v-container>
<v-card>
:mini-variant.sync="mini"
permanent
>
<v-list-item>
<v-list-item-avatar>
<v-img src="https://randomuser.me/api/portraits/men/85.jpg"></v-img>
</v-list-item-avatar>
<v-list-item-title>John Leider</v-list-item-title>
<v-btn
icon
@click.stop="mini = !mini"
>
<v-icon>mdi-chevron-left</v-icon>
</v-btn>
</v-list-item>
<v-list dense>
<v-list-item
:key="item.title"
:aria-label="item.title"
link
>
<v-icon>{{ item.icon }}</v-icon> …
```
> fix(VNavigationDrawer): hide navigation drawer labels visually

- packages/vuetify/src/components/VStepper/VStepper.sass
- packages/vuetify/src/components/VStepper/_variables.scss
Added a right border on RLT for the VStepper component and also fixed its margins
fix #10098
A new variable was created to hold the margins on RTL mode, and so, the old $stepper-vertical-content-margin was renamed to $stepper-vertical-content-ltr-margin
Fixes: https://github.com/vuetifyjs/vuetify/issues/10098
unit and visually tested
<details>
```vue
<template>
<v-container>
<v-stepper
v-model="e6"
vertical
>
<v-stepper-step
:complete="e6 > 1"
step="1"
>
Select an app
<small>Summarize if needed</small>
<v-stepper-content step="1">
<v-card
color="grey lighten-1"
class="mb-12"
height="200px"
></v-card>
<v-btn
@click="e6 = 2"
>Continue</v-btn>
<v-btn text>Cancel</v-btn>
</v-stepper-content>
<v-stepper-step
:complete="e6 > 2"
step="2" …
```
> fix(VStepper): fix the behaviour of the VStepper style on RTL

- packages/docs/src/lang/en/components/DataTables.json
Fix grammatical error caused by wrong tense usage
Makes the documentation read well
> docs: fix grammatical error caused by wrong tense usage

- packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.ts
- packages/vuetify/src/components/VSelect/VSelect.ts
- packages/vuetify/src/components/VSelect/__tests__/VSelect3.spec.ts
Resolves Issue #10152, a regression introduced by merging #9598.
This fixes the missing `name` attribute on the inner hidden input element inside `VSelect`. Since `name` is now removed from the inner text input, it needed to be manually added to the hidden input from the `VSelect` attribute list.
For users that rely on the traditional form input name/value structure to validate and/or submit forms, it's essential that all Vuetify field components maintain this underlying behavior.
This PR Includes unit tests on VSelect and VCombobox to confirm the bug and verify the fix. It also completes the related unit test for the VSelect hidden input value by properly testing that changing the selected item updates the input value.
> fix(VSelect): propagate name attribute to hidden input

- packages/vuetify/src/components/VDatePicker/_variables.scss
- packages/vuetify/src/components/VPicker/VPicker.sass
1. sets full-width picker to 100%
2. fixes the years height to be the same as month/date
3. moves picker title in landscape mode to the right side in RTL
fixes #9258
playground
<details>
```vue
<template>
<v-container>
<div>
<v-btn @click="$vuetify.rtl = !$vuetify.rtl">rtl: {{ $vuetify.rtl }}</v-btn>
<v-btn @click="landscape = !landscape">landscape: {{ landscape }}</v-btn>
<v-btn @click="fullWidth = !fullWidth">full width: {{ fullWidth }}</v-btn>
<v-btn @click="noTitle = !noTitle">noTitle: {{ noTitle }}</v-btn>
</div>
<v-row align="center">
<v-date-picker
:full-width="fullWidth"
:landscape="landscape"
:no-title="noTitle"
/>
</v-row>
<v-btn @click="menu = true">Open menu</v-btn>
<v-menu
v-model="menu"
min-width="600"
:close-on-content-click="false"
>
<v-date-picker …
```
> fix(VPicker): content position in landscape mode

- packages/vuetify/src/components/VDatePicker/VDatePickerTable.sass
- packages/vuetify/src/components/VDatePicker/__tests__/__snapshots__/VDatePickerMonthTable.spec.ts.snap
- packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.ts
fixes #8182
unit,  playground
<details>
```vue
<template>
<v-container>
<v-date-picker value="2020-01" :events="['2020-11', '2020-12']" show-current="2020-11" type="month"></v-date-picker>
<v-date-picker value="2020-11-01" :events="['2020-11-05', '2020-11-06']" show-current="2020-11-05" type="date"></v-date-picker>
</v-container>
</template>
```
</details>
> fix(VDatePicker): events alignment on current date

- packages/vuetify/src/components/VTimePicker/VTimePickerClock.ts
- packages/vuetify/src/components/VTimePicker/VTimePickerTitle.sass
- packages/vuetify/src/components/VTimePicker/_variables.scss
- packages/vuetify/src/locale/fa.ts
Fixes few issues from https://github.com/vuetifyjs/vuetify/issues/6757:
- margins of am/pm in title
- Farsi translations of am/pm
- typing of VTimePickerTItle.format prop
playground
<details>
```vue
<template>
<v-container fluid style="width: 314px">
<v-btn block @click="$vuetify.rtl = !$vuetify.rtl">RTL: {{ $vuetify.rtl }}</v-btn>
<v-time-picker />
<v-time-picker format="24hr" />
<v-time-picker ampm-in-title />
<v-time-picker format="24hr" ampm-in-title />
</v-container>
</template>
<script>
import Vue from 'vue';
import { fa } from '../src/locale'
export default Vue.extend({
created () {
this.$vuetify.lang.locales.en = fa
}
})
</script>
```
</details>
> fix(VTimePicker): AM/PM farsi translation and margins in RTL mode

- packages/vuetify/src/styles/components/_selection-controls.sass
VCheckBox and VRadioGroup had a spacing issue when using the dense prop during the hover effect.
fix #10336
Updated _selection-controls.sass to center the position of the checkbox/radio button icon when the dense prop was being used and was in hover state.  Adjusted the positioning by 2px.
fixes #10336 
This change was required because when hovering over the checkbox or radio button, the icon was not centered inside the hover effect.
fixes #10336 
Tested these changes visually in 
Chrome Version 79.0.3945.130
Firefox 72.0.2 
Edge Version 79.0.309.71
IE 11
<details>
```vue
<template>
<v-container>
<v-checkbox label="Normal checkbox"></v-checkbox>
<v-checkbox dense label="Densed checkbox"> </v-checkbox>
<v-radio-group v-model="radioGroup" dense>
<v-radio label="Radio"></v-radio> …
```
> fix(vcheckbox): spacing issue with VCheckbox

- packages/docs/src/examples/cards/complex/loading.vue
There was an unfortunate typo in the docs, and the sentence itself was a little confusing. Just cleaning that up.
Doesn't necessarily solve a problem, but helps the docs to be more clear and more professional.
- [x ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ x] My code follows the code style of this project.
- [ x] I've added relevant changes to the documentation (applies to new features and breaking changes in core library)
> docs(vcard): fix typo and make example sentence more clear

- packages/docs/src/lang/en/components/Autocompletes.json
Fixes a typo in Autocompletes.json. Specifically the documentation for the `search-input` prop.
Fixes a typo
N/A
N/A
> Fixed typo in Autocompletes.json

- packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete2.spec.ts
- packages/vuetify/src/components/VFileInput/__tests__/__snapshots__/VFileInput.spec.ts.snap
- packages/vuetify/src/components/VIcon/VIcon.sass
- packages/vuetify/src/components/VInput/VInput.ts
- packages/vuetify/src/components/VSelect/VSelect.ts
- packages/vuetify/src/components/VSelect/__tests__/VSelect4.spec.ts
- packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect2.spec.ts.snap
- packages/vuetify/src/components/VTextField/VTextField.ts
jest, playground
<details>
```vue
<template>
<v-container>
<v-file-input />
<v-text-field clearable />
<v-select :items="['foo']" clearable />
<v-autocomplete :items="['foo']" clearable />
<v-combobox :items="['foo']" clearable />
</v-container>
</template>
```
</details>
> fix(VTextField/VSelect): don't focus clear icon if dirty

- packages/vuetify/src/components/VFileInput/__tests__/__snapshots__/VFileInput.spec.ts.snap
- packages/vuetify/src/components/VInput/VInput.sass
- packages/vuetify/src/components/VInput/VInput.ts
- packages/vuetify/src/components/VSelect/VSelect.ts
- packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect2.spec.ts.snap
- packages/vuetify/src/components/VTextField/VTextField.ts
- packages/vuetify/src/util/mergeData.ts
Related: #10461, #10439
<details>
```vue
<template>
<v-container>
<v-select clearable prepend-inner-icon="mdi-vuetify" menu-props="offsetY" @click:prepend-inner="" :items="['a', 'b', 'c']" v-model="selected"></v-select>
</v-container>
</template>
<script>
data: () => ({
selected: null
})
}
</script>
```
</details>
> fix(VSelect): expose clickable icons to screen readers

- packages/docs/src/components/style/Font.vue
- packages/docs/src/data/pages/styles/Text.json
- packages/docs/src/examples/text/opacity.vue
- packages/docs/src/lang/en/styles/Text.json
Added examples of `text--primary`, `text--secondary`, and `text--disabled` to Styles and Weights section of Typography. 
These classes provide support for the text emphasis guidelines in MD2. There was no existing documentation for this feature of Vuetify, though the classes are used in several examples.
I made this change to Typography over Text because the style of examples are more user-friendly in Typography.
- [*] The PR title is no longer than 64 characters.
- [*] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [*] My code follows the code style of this project.
- [*] I've added relevant changes to the documentation (applies to new …
> docs(text): add text emphasis / opacity examples

- packages/vuetify/src/components/VDataIterator/VDataIterator.ts
- packages/vuetify/src/components/VDataIterator/__tests__/VDataIterator.spec.ts
- packages/vuetify/src/components/VDataIterator/__tests__/__snapshots__/VDataIterator.spec.ts.snap
- packages/vuetify/src/components/VDataTable/VDataTable.ts
- packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
Add possibility to customize 'item' slot in DataTable and DataIterator in mobile view by introducing
isMobile property to be available in the scope.
fix #9436
Custom `item` slots in DataTable render badly on mobiles. Header in table is responsive but the slot is not, which causes it to look really bad (https://codepen.io/AshrafBasry/pen/QWWdeML). The proposed solution is the easiest possible - by adding `isMobile` prop into the scope, we can allow the developer to customize their `item` slot both for normal and mobile view.
https://github.com/vuetifyjs/vuetify/issues/9436
https://github.com/vuetifyjs/vuetify/issues/8394
Visually.
<details>
```vue
<template>
<v-container>
<v-data-table :headers="tableHeaders" :items="tableData">
<template v-slot:item="{item, isMobile}">
<tr …
```
> fix(VDataIterator): add isMobile property to custom item slot scope

- packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete2.spec.ts
- packages/vuetify/src/components/VDataIterator/__tests__/__snapshots__/VDataFooter.spec.ts.snap
- packages/vuetify/src/components/VDataIterator/__tests__/__snapshots__/VDataIterator.spec.ts.snap
- packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
- packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTableHeader.spec.ts.snap
- packages/vuetify/src/components/VMenu/VMenu.ts
- packages/vuetify/src/components/VMenu/__tests__/VMenu.spec.ts
- packages/vuetify/src/components/VMenu/__tests__/__snapshots__/VMenu.spec.ts.snap
- packages/vuetify/src/components/VOverflowBtn/__tests__/__snapshots__/VOverflowBtn.spec.ts.snap
- packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect.spec.ts.snap
- packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect2.spec.ts.snap
- packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect3.spec.ts.snap
fixes #10522
related https://github.com/vuetifyjs/vuetify/commit/cc17fe19751826d950ca5207749699935d227020
<details>
```vue
<template>
<v-container>
<v-subheader>VEditDialog</v-subheader>
<v-edit-dialog large>
<template #input><span>foo</span><span>bar</span></template>
<span>foo</span><span>bar</span>
<v-subheader>VMenu</v-subheader>
<v-menu
offset-y
content-class="white"
>
<v-btn v-on="on">Menu</v-btn>
</template>
<div>Foo</div>
<div>Bar</div>
</v-menu>
<v-subheader>VTooltip</v-subheader>
<v-tooltip bottom>
<v-btn v-on="on">Tooltip</v-btn>
</template>
<div>Foo</div>
<div>Bar</div>
</v-tooltip>
<v-subheader>VWindow</v-subheader>
<v-window>
<v-window-item>
<span>foo</span>
<span>bar</span> …
```
> fix(VMenu): allow more than 1 content node

- packages/docs/src/examples/text/opacity.vue
Fix missing dash "-" in the text opacity demo for 'text--disabled'
> docs: Fix opacity demo for 'text--disabled'

- packages/vuetify/src/components/VDataTable/VSimpleTable.sass
Removes unnecessary hover effect on `no data`/`no results` row
https://codepen.io/jkarczm/pen/WNvxwRE
playground
```vue
<template>
<v-container>
<v-data-table :headers="[{ text: 'Foo' }]" :items="[]" />
<v-data-table :headers="[{ text: 'Foo' }]" :items="[{}]" search="foo" />
</v-container>
</template>
```
> fix(VDataTable): remove hover on empty (no data) wrapper

- packages/vuetify/src/components/VDataTable/VSimpleTable.sass
Adds bottom border to `tbody th`
https://codepen.io/jkarczm/pen/bGdpMzB?editors=1000
playground
<details>
```vue
<template>
<v-container>
<v-simple-table>
<tbody>
<tr v-for="i in 3">
<th scope="row">TH - has no bottom border</th>
<td>TD - has bottom border</td>
<td>TD - has bottom border</td>
</tr>
</tbody>
</v-simple-table>
</v-container>
</template>
```
</details>
> fix(VSimpleTable): missing bottom border of tbody th

- packages/vuetify/src/components/VDataTable/VDataTable.ts
- packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts
- packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
group-by functionality skipped potential item slot
closes #10289
<details>
```vue
<template>
<v-data-table
group-by="category"
>
<template v-slot:group.header="{toggle,group,isOpen}">
<td colspan="2" class="pl-0">
<v-btn @click="toggle()" icon>
<v-icon>mdi-{{isOpen?'arrow-up-drop-circle-outline':'arrow-down-drop-circle-outline'}}</v-icon>
</v-btn>
<span class="info--text">category:</span>
{{group}}
</td>
</template>
<template v-slot:item="{item}">
<tr @click="Alert(item.name)">
<td>
{{item.name}}
</td>
<td>
{{item.category}}
</td>
</tr>
</template>
</template>
<script>
data () {
return {
headers: [
{
align: 'left',
value: 'name', …
```
> fix(VDataTable): group-by should use correct slot

- packages/vuetify/src/components/VTimePicker/VTimePicker.ts
- packages/vuetify/src/components/VTimePicker/VTimePickerTitle.sass
- packages/vuetify/src/components/VTimePicker/VTimePickerTitle.ts
- packages/vuetify/src/components/VTimePicker/__tests__/__snapshots__/VTimePicker.spec.ts.snap
fixes #9572
unit, playground
<details>
```vue
<template>
<v-container>
<v-time-picker></v-time-picker>
<v-time-picker ampm-in-title></v-time-picker>
<v-time-picker format="24hr"></v-time-picker>
</v-container>
</template>
```
</details>
> fix(VTimePicker): show 12 hr time in title in ampm mode

- packages/docs/src/examples/forms/intermediate/vee-validate.vue
Return the name of the fields under validation.
I have changed the field in the validation messages to {_field_}. This would return the name of the field under validation instead of just field as it is now.
For instance 
```js
extend('required', {
...required, message: "The {_field_} is required"
})
```
```vue
<ValidationProvider name="Username" rules="required" v-slot="{errors}">
<v-text-field :error-messages="errors" v-model="username" name="name" label="Username"></v-text-field>
</ValidationProvider>
```
Would return **The Username is required**
This change is just an enhancement to the documentation example
I tested the changes locally.
<details>
```vue
```
</details>
> docs(Forms): update vee-validate example

- packages/docs/src/examples/data-tables/simple/search.vue
In the documentation, for the search section at the data-tables components, they are a wrong append-icon props documented
the search icon doesn't show off. when i try the example.
Read the commit file or the doc
> docs: data-tables simple search append-icon wrong props

- packages/vuetify/src/components/VSelect/VSelect.js
- packages/vuetify/src/components/VTextField/VTextField.js
- packages/vuetify/test/unit/components/VTextField/VTextField.spec.js
The ordering of events in Safari/Edge/IE caused our manual blur of the input to break tabbing
through inputs. Additionally resolving duplicate blur events
"fix #10609"
Fixing tabbing so that it doesn't return to the first focusable element in Safari/Edge/IE (and possibly other browsers). Additionally fixing duplicate blur event. This PR piggy backs off of this PR for 2.0 here: https://github.com/vuetifyjs/vuetify/commit/5fa6a682634a0c159cf7c37897535bc2894131b9 
This change is required to fix this open issue: https://github.com/vuetifyjs/vuetify/issues/10609
I have updated an existing test, all tests pass, and additionally I was able to test in these environments:
- Chrome Version 80.0.3987.106 (Official Build) (64-bit)
- Firefox Version 73.0
- Microsoft Edge 41.16299.1004.0
- Internet …
> fix(vselect): resolve bug in browsers with event order disparity

- packages/docs/src/examples/data-tables/complex/crud.vue
- packages/docs/src/examples/data-tables/complex/edit-dialog.vue
- packages/docs/src/examples/data-tables/intermediate/custom-filter.vue
- packages/docs/src/examples/data-tables/intermediate/customize-footer.vue
- packages/docs/src/examples/data-tables/intermediate/customize-header.vue
- packages/docs/src/examples/data-tables/intermediate/customize-rows.vue
- packages/docs/src/examples/data-tables/intermediate/expand.vue
- packages/docs/src/examples/data-tables/intermediate/paginate.vue
- packages/docs/src/examples/data-tables/intermediate/server.vue
- packages/docs/src/examples/data-tables/intermediate/simple-checkbox.vue
- packages/docs/src/examples/data-tables/intermediate/slots.vue
- packages/docs/src/examples/data-tables/intermediate/sort.vue
- packages/docs/src/examples/data-tables/playground.vue
- packages/docs/src/examples/data-tables/simple/dense.vue
- packages/docs/src/examples/data-tables/simple/filterable-columns.vue
- packages/docs/src/examples/data-tables/simple/footer-props.vue
- packages/docs/src/examples/data-tables/simple/group.vue
- packages/docs/src/examples/data-tables/simple/headerless.vue
- packages/docs/src/examples/data-tables/simple/multi-sort.vue
- packages/docs/src/examples/data-tables/simple/search.vue
- packages/docs/src/examples/data-tables/simple/select.vue
- packages/docs/src/examples/data-tables/simple/virtualized.vue
- packages/docs/src/examples/data-tables/usage.vue
Type TableHeader requires either `start`,`center` or `right` as `align` value, in the examples `left` was used. changed all occurrences from `left` to `start`
No testing, it is a change in the documentation example
> docs(tables): change TableHeader align:left to align:start

- packages/vuetify/src/components/VDataIterator/VDataIterator.ts
- packages/vuetify/src/components/VDataIterator/__tests__/VDataIterator.spec.ts
we were not emitting the page-count event at all
closes #8886
<details>
```vue
<template>
<div>
<v-text-field label="search" v-model="search"></v-text-field>
<v-data-iterator
:items-per-page="pageSize"
:page="page"
@page-count="pageCountChanged"
>
<template v-slot:default="props">
<v-row>
<v-col cols="12" md="3" v-for="item in props.items" :key="item.name">
<v-card role="button">
<v-card-text class="text-center">
<h4>{{ item.name }}</h4>
</v-card-text>
</v-card>
</v-col>
</v-row>
</template>
</v-data-iterator>
<v-pagination v-model="page" :length="pageCount"></v-pagination>
</div>
</template>
<script>
data () {
return {
search: '',
pageCount: 0,
page: 1, …
```
> fix(VDataIterator): emit page-count event

- packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts
- packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete.spec.ts
fix #9757
Check for internalSeach value instead of directly replacing it will null
<details>
```vue
<template>
<div id="app">
<v-app>
<v-content>
<v-container>
:items="items"
/>
</v-container>
</v-content>
</v-app>
</div>
</template>
<script>
data: () => ({
search: 'foo',
}),
}
</script>
```
```vue
<template>
<div id="app">
<v-app>
<v-content>
<v-container>
/>
</v-container>
</v-content>
</v-app>
</div>
</template>
<script>
data: () => ({
search: 'foo',
}),
}
</script>
```
</details>
> fix(VAutocomplete): check for inital search input prop

- packages/vuetify/src/components/VData/VData.ts
- packages/vuetify/src/components/VData/__tests__/VData.spec.ts
- packages/vuetify/src/components/VDataIterator/VDataFooter.ts
passing zero to itemsPerPage would cause a couple of computed values to turn NaN which broke things.
closes #10372
unit test, playground
<details>
```vue
<template>
<v-container>
<v-data-table
:items-per-page="itemsPerPage"
<v-btn @click="handleClickButton">increase item </v-btn>
<v-btn @click="itemsPerPage++">items per page</v-btn>
</v-container>
</template>
<script>
data () {
return {
itemsPerPage: 0,
headers: [
{
align: 'left',
value: 'name',
},
], …
```
> fix(VDataTable): handle passing zero to itemsPerPage

- packages/docs/src/examples/buttons/simple/icon.vue
Removes useless attribute `text` with `icon` on buttons from the documentation, for the icon example. Avoid confusion.
As you can see `icon` and `text icon` provide the same result: https://codepen.io/elfayer/pen/gOpWrXB
<details>
```vue
<div id="app">
<v-card flat>
<v-card-text>
<v-container fluid class="pa-0">
<v-row>
<v-btn text icon color="pink">
<v-icon>mdi-heart</v-icon>
</v-btn>
</v-col>
<v-btn icon color="pink">
<v-icon>mdi-heart</v-icon>
</v-btn>
</v-col>
</v-row>
</v-container>
</v-card-text>
</v-card>
</v-app>
</div>
```
</details>
> docs(VButton): remove text prop when using icon

- packages/vuetify/src/styles/elements/_typography.sass
Following the pattern of how the classes are arranged, everything is sorted descendingly except for `.subtitle-1` and `.subtitle-2`.
The patterns should be consistent.
none
> refactor(typography): reorder subtitle-1 and 2

- packages/docs/src/examples/data-tables/intermediate/sort.vue
The property being flipped in the _toggleOrder_ method is not correct.  It is currently _descending_ instead of the correct value of **sortDesc**.
The **External Sorting** example for _Data table_ has a bug.  The _Toggle Sort Order_ button has no affect.  In the method, it is changing a property that does not exist.  
To correct a minor issue to a code example.
I made the change on CodePen.io
<details>
`
toggleOrder () {
/*this.descending = !this.descending;*/
this.sortDesc = !this.sortDesc
}`
</details>
> docs(VDataTable): fix "toggleOrder" method in sort example

- packages/vuetify/src/components/VTreeview/VTreeview.sass
After this fix treeview items are now vertically centered on IE11.
fix #10534
fixes #10534
On IE11 treeview items are not vertically centered. This PR fixes this issue.
I want to fix the bug which exists only on IE11.
I have tested the changes visually on different browsers including IE11.
<details>
```vue
<template>
<v-container>
<v-treeview activatable color="warning" :items="items"></v-treeview>
</v-container>
</template>
<script>
data() {
return {
items: [
{
id: 1,
name: "Applications :",
children: [
{ id: 2, name: "Calendar : app" },
{ id: 3, name: "Chrome : app" },
{ id: 4, name: "Webstorm : app" }
]
},
{
id: 5,
name: "Documents :",
children: [
{
id: 6,
name: "vuetify :",
children: [
{
id: 7,
name: "src :",
children: [
{ id: 8, name: "index : ts" },
{ id: 9, name: …
```
> fix(VTreeview.sass): center vertically treeview items on IE11

- packages/vuetify/src/locale/de.ts
The translation of `carousel.ariaLabel.delimiter` was still english.
Hopefully done by CI. :)
> fix(locale): Fix german translation `carousel.ariaLabel`

- packages/vuetify/src/components/VData/VData.ts
- packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts
hopefully this does not lead to any further regressions. it seems to be nigh impossible to replicate the double emit in the unit tests.
closes #10715
<details>
```vue
<template>
<div>
<v-text-field v-model="search" label="search"></v-text-field>
<v-data-table
:server-items-length="totalDesserts"
@pagination="doPage"
</div>
</template>
<script>
data () {
return {
search: '',
desserts: [],
loading: true,
options: {},
headers: [
{
value: 'name',
},
{ text: 'Carbs …
```
> fix(VDataTable): pagination event fires twice in a row

- packages/vuetify/src/components/VInput/VInput.ts
- packages/vuetify/src/components/VTextField/VTextField.ts
- packages/vuetify/src/components/VTextField/__tests__/VTextField.spec.ts
- packages/vuetify/src/components/VTextField/__tests__/__snapshots__/VTextField.spec.ts.snap
fixes #10701
playground, jest 
<details>
```vue
<template>
<v-container>
<v-text-field
counter="1024"
hide-details="auto"
/>
<v-text-field
counter="1024"
/>
<v-text-field
counter="1024"
hide-details
/>
</v-container>
</template>
```
</details>
> fix(VTextField): incorrectly displayed counter with hide-details=auto

- packages/vuetify/src/components/VTextField/VTextField.sass
The dense input style on the empty text input of a dense mode VSelect is causing the element to be
too short. When an item is selected, the element visibly grows and returns to the proper size. By
exluding the dense padding override on the text field, the Empty Dense VSelect now matches other
dense form controls like autocomplete.
Fix #10635 
Bug reproduced [here](https://codepen.io/amoliski/pen/NWqjdyR) - Note that the red outlined elements are much smaller than the other elements, and will grow to the proper size once an element is selected.
This is an alternative to my previous pull request that modified the padding on the selected VSelect element- upon further inspection, the previous fix was less consistent with other dense components. It also impacted the visual appearance of …
> fix(VSelect): incorrect dense height

- packages/vuetify/src/components/VTreeview/VTreeview.ts
- packages/vuetify/src/components/VTreeview/__tests__/VTreeview.spec.ts
when rebuilding the tree we did not take selection-type into account
closes #8720
<details>
```vue
<template>
<v-treeview
v-model="selectedItems"
:items="items"
selectable
open-all
selection-type="leaf"
> </v-treeview>
<v-btn @click="onClicked"> Change Array Set </v-btn>
<v-col> {{ selectedItems }} </v-col>
</v-container>
</template>
<script>
data: () => ({
selectedItems: ['C1', 'C2', 'C3', 'C4'],
items: [
{
id: 'PARENT',
name: "Parent",
disabled: false,
children: [
{ id: 'C1', name: "Child 1" },
{ id: 'C2', name: "Child 2" },
{ id: 'C3', name: "Child 3", disabled: true },
{ id: 'C4', name: "Child 4" }
]
}
]
}),
methods: {
onClicked() {
this.items = [
{
id: 'PARENT',
name: "Parent",
disabled: false,
children: [
{ id: 'C1', …
```
> fix(VTreeview): respect selection-type when rebuilding tree

- packages/vuetify/src/components/VAppBar/VAppBar.ts
- packages/vuetify/src/components/VAppBar/__tests__/VAppBar.spec.ts
Fixes an issue with VAppBar where if inverted-scroll is enabled while the page is scrolled down, and
then the page is scrolled to the top, the app bar would not hide.
fixes #10590 
fixes #10590 
Added a unit test, and tested visually.
<details>
```vue
<template>
<v-app>
<v-app-bar app :hide-on-scroll="toggle" :inverted-scroll="toggle">
<v-toolbar-title>Page title</v-toolbar-title>
</v-app-bar>
<v-container style="height: 3000px; margin-top: 100px">
<div>
How to reproduce:
<ol>
<li>Scroll down a little bit.</li>
<li>Toggle the switch below on.</li>
<li>Immediately scroll to the top of the page.</li>
<li>Observe that the app bar does not hide.</li>
</ol>
</div>
<v-switch v-model="toggle" label="Toggle" />
</v-container>
</v-app>
</template>
<script> …
```
> fix(VAppBar): inverted scroll not hiding the app bar in an edge case

- packages/vuetify/src/components/VDataTable/VSimpleTable.sass
fixes #8993
playground
<details>
```vue
<template>
<div>
<v-container class="fill-height">
<v-data-table
:headers="new Array(30).fill({ text: 'foo' })"
:items="[]"
</v-container>
<v-container class="fill-height">
<v-data-table
:headers="[{text: 'foo'}]"
:items="[]"
</v-container>
</div>
</template>
```
</details>
Current solution:
It could be also `width: 100%`:
Not sure which is better (the current one is less breaking, EDIT: and more in line with native tables
> fix(VSimpleTable): set max width to 100%

- packages/vuetify/src/components/VSelect/VSelect.sass
- packages/vuetify/src/components/VSelect/_variables.scss
- packages/vuetify/src/components/VTextField/VTextField.sass
- packages/vuetify/src/components/VTextField/_variables.scss
Reduced the height of the VSelect in dense mode to match the height of the VTextField.
Fixes #10877 
When in dense mode, the VSelect height is bigger than the VTextField height, resulting in the text and underline of the elements being misaligned when placed side to side. The problem also happens when using a append or prepend inner icon in a VTextField, but the difference is smaller. One of the changes here reverts PR #10694, which fixed the changing height of the VSelect, but it would still be misaligned in relation to the VTextField.
Visually
Before
After
<details>
```vue
<template>
<v-container>
<v-row class="title">Standard</v-row>
<v-row>
<v-col>
<v-select v-model="select" label="Select" :items="list"></v-select>
</v-col>
<v-col>
<v-select v-model="select_2" label="Empty Select" …
```
> fix(VSelect): make the VSelect height the same of VTextField

- packages/vuetify/src/components/VSkeletonLoader/VSkeletonLoader.sass
Remove the border-radius property when a card-heading is following an image in skeleton-loader.
When rendering `skeleton-loader` type `"card"` a `border-radius` property break the seams between the image and the card-heading. This is more easy to notice on dark theme.
I can't find any open related issue. However, this is related to the addition of 74bc9011152b61b36b636249d38a6b9c367d5e99 that raised the issue #9447.
I don't see why https://github.com/vuetifyjs/vuetify/commit/74bc9011152b61b36b636249d38a6b9c367d5e99#diff-e99f6b3f7c8208735fbabc77e06b7e33R111 was added and what it add to the code. I tried every `skeleton-loader` without this and I can't see any difference.
visually 
<details>
```vue
<template>
<v-skeleton-loader type="card"></v-skeleton-loader>
</template>
```
</details>
> fix(VSkeletonLoader): remove unnecessary border-radius on skeleton-loader card style

- packages/docs/src/lang/en/components/Lists.json
Sorry for not filling out the template, here is a simple change.
> docs(lists): fix typo

- packages/vuetify/src/components/VDataIterator/VDataIterator.ts
Description
Also emit the page-count event from the inner VData component to update the external pagination on async item changes
This feature is already documented but not implemented at this time
It makes a pagination pageCount update possible if the Iterator items changes in a async matter
No additional tests because I don't find any similar tests in the VDataTable component who already implements this feature
</details>
> feat(VDataIterator): emit the page-count event from VData

- packages/vuetify/src/components/VSparkline/VSparkline.ts
- packages/vuetify/src/components/VSparkline/__tests__/__snapshots__/VSparkline.spec.ts.snap
This makes sure that material colors also work for the stop-color and fill properties, which are the reason this didn't work. As the `<svg>` tag has a `color` class applied:
https://github.com/vuetifyjs/vuetify/blob/f57b7a7c6247e1b496ae87a1e4b4c014a7dcdc1d/packages/vuetify/src/components/VSparkline/VSparkline.ts#L400-L402
using `currentColor` will always work, as the color will simply propagate downwards.
Another option would be to translate the color to some hex value, as such:
```typescript
parsedColor (): string {
if (isCssColor(this.color)) {
return this.color
} else {
const parsedTheme = (this.$vuetify.theme as Theme & { parsedTheme: VuetifyParsedTheme}).parsedTheme
const colorParts = this.color.split(' ')
if (colorParts.length === 1) {
return parsedTheme[this.color].base
} else { …
```
> fix(sparkline): stop-color and fill not using material colors

- packages/vuetify/src/directives/ripple/__tests__/ripple.spec.ts
- packages/vuetify/src/directives/ripple/index.ts
This PR makes it possible to trigger the ripple effect by pressing the space or enter key on the focused element.
#10285
<details>
```vue
<template>
<v-container>
<v-btn color="primary">Primary</v-btn>
</v-container>
</template>
<script>
data: () => ({
//
})
}
</script>
```
</details>
> fix(VRipple): add keyboard trigger support

- packages/docs/src/lang/en/customization/Internationalization.json
- packages/docs/src/snippets/ts/create_translation.txt
Use shorter and less error-prone snippet for custom i18n.
Current snippet suggests to copy-paste file's content, while it's better to inherit properties, so you won't need to manually check and sync copied content during updates.
N/A
N/A
> docs(i18n): add shorter snippet for custom i18n

- packages/docs/src/lang/en/components/Sliders.json
Removed duplication of the word "It" from the en docs for the v-slider component, in the description for "Thumb".
> It It can have a custom color...
changed to
> It can have a custom color...
Proper grammar is important for a professional image.
> docs: remove duplicate word

- packages/vuetify/src/components/VCalendar/VCalendar.ts
- packages/vuetify/src/components/VCalendar/__tests__/__snapshots__/VCalendar.spec.ts.snap
- packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.ts
- packages/vuetify/src/components/VCalendar/util/timestamp.ts
fixes #11025
When day or 4day type are used, ignore weekday settings - they don't make sense in these views.
#11025 
<details>
```vue
<template>
<v-sheet class="v-fullscreen">
<v-sheet
tile
height="54"
color="grey lighten-3"
class="d-flex"
>
<v-btn
icon
class="ma-2"
@click="$refs.calendar.prev()"
>
<v-icon>mdi-chevron-left</v-icon>
</v-btn>
<v-select
v-model="type"
:items="types"
dense
outlined
hide-details
class="ma-2"
label="type"
></v-select>
<v-select
v-model="mode"
:items="modes"
dense
outlined
hide-details
label="event-overlap-mode"
class="ma-2"
></v-select>
<v-select
dense
outlined
hide-details
class="ma-2"
></v-select>
<v-btn
icon
class="ma-2"
@click="$refs.calendar.next()"
> …
```
> fix(VCalendar): weekdays and day views conflict (#11025)

- packages/api-generator/src/maps/v-calendar.js
- packages/docs/src/lang/en/components/Calendars.json
- packages/docs/src/lang/fr-FR/components/Calendars.json
- packages/docs/src/lang/zh-CN/components/Calendars.json
- packages/vuetify/src/components/VCalendar/VCalendarDaily.ts
fixes #11069
resolves #11069
Calendar slots were inconsistent
visually
<details>
```vue
```
</details>
> fix(VCalendar): missing day-label slot for daily (#11069)

- packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.ts
fixes #11090
resolves #11090
When using slots, event rendering can malfunction and not work
visually
<details>
```vue
<template>
<v-sheet class="v-fullscreen">
<v-sheet
tile
height="54"
color="grey lighten-3"
class="d-flex"
>
<v-btn
icon
class="ma-2"
@click="$refs.calendar.prev()"
>
<v-icon>mdi-chevron-left</v-icon>
</v-btn>
<v-select
v-model="type"
:items="types"
dense
outlined
hide-details
class="ma-2"
label="type"
></v-select>
<v-select
v-model="mode"
:items="modes"
dense
outlined
hide-details
label="event-overlap-mode"
class="ma-2"
></v-select>
<v-select
dense
outlined
hide-details
class="ma-2"
></v-select>
<v-btn
icon
class="ma-2"
@click="$refs.calendar.next()"
>
<v-icon>mdi-chevron-right</v-icon>
</v-btn> …
```
> fix(VCalendar): no event rendering without default slot (#11090)

- packages/api-generator/src/maps/v-data-table.js
- packages/vuetify/src/components/VDataTable/VDataTable.ts
Add the missing isOpen and toggle props to the group.summary slot of the VDataTable component.
The group.summary slot doesn't have the `isOpen` and `toggle` props. The `isOpen` prop would be useful for hiding (parts of) the summary when the group is closed. The `toggle` prop might also be useful if a developer wants the user to be able to close the group from within the summary.
Visually (playground)
<details>
```vue
<template>
<v-container>
<v-data-table :items="items" :headers="headers" group-by="type">
<template #group.summary="{ isOpen, toggle }">
<v-btn icon @click="toggle">
<v-icon>
{{ isOpen ? '$minus' : '$plus' }}
</v-icon>
</v-btn>
</template>
</v-container>
</template>
<script>
data: () => ({
items: [{
type: 1,
name: 'First',
}, {
type: 2,
name: …
```
> docs(VDataTable): add missing props to group.summary slot

- packages/api-generator/src/maps/v-data-table.js
- packages/docs/src/lang/en/components/DataTables.json
- packages/vuetify/src/components/VDataTable/VDataTable.ts
- packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts
- packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
add contextmenu:row event for data table
resolves #9382 
<details>
```vue
<template>
<v-container>
<v-data-table
@contextmenu:row="onRowContextmenu"
/>
<v-menu
v-model="showMenu"
:position-x="menuX"
:position-y="menuY"
absolute
offset-y
>
<v-list>
<v-list-item
:key="item.title"
@click=""
>
</v-list-item>
</v-list>
</v-menu>
</v-container>
</template>
<script>
data: () => ({
desserts: [
{
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1%',
},
{
calories: 237,
fat: 9.0,
carbs: 37,
protein: 4.3,
iron: '1%',
},
{
calories: 262,
fat: …
```
> feat(VDataTable): add contexmenu:row event for data table

- packages/vuetify/src/components/VSelect/VSelect.ts
- packages/vuetify/src/components/VSelect/__tests__/VSelect4.spec.ts
fixes #10406
<details>
```vue
<template>
<v-container>
<v-select :items="items" v-model="selected"></v-select>
<pre>{{ selected }}</pre>
</v-container>
</template>
<script>
data: () => ({
items: [
'Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Federated States of Micronesia', 'Florida', 'Georgia', 'Guam', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Marshall Islands', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Northern Mariana Islands', 'Ohio', 'Oklahoma', 'Oregon', …
```
> fix(VSelect): scroll to newly selected item in long lists

- packages/vuetify/src/util/colorUtils.ts
Firefox wil not load application because of error on regexp with lookbehind part.
Changed code without using lookbehind
fix #11214
Fixes #11214 
unit
<details>
```vue
```
</details>
> fix(colorutils.ts): lookbehind regexp causing FF throw error

- packages/api-generator/src/maps/v-scroll.js
- packages/docs/src/data/pages/directives/Scrolling.pug
- packages/docs/src/examples/scrolling/simple/self.vue
- packages/docs/src/lang/en/directives/Scrolling.json
- packages/vuetify/src/directives/scroll/__tests__/scroll.spec.ts
- packages/vuetify/src/directives/scroll/index.ts
- packages/vuetify/src/globals.d.ts
* Custom options should now work and accept an object containing a **handler** and/or **options** keys:
```vue
<template>
<div
v-scroll="{
handler: onScroll, 
options: { passive: false }
}"
/>
</template>
```
* A new modifier, **self**, which automatically targets the binding element. This was cumbersome to accomplish prior:
```vue
<template>
<div  
id="foo"
v-scroll:#foo="onScroll"
/>
<div  v-scroll.self="onScroll" />
</template>
```
Currently you must use `querySelector` to target the binding element. This became an issue when wanting to utilize the scroll directive for the upcoming [v-virtual-scroll](https://github.com/vuetifyjs/vuetify/pull/10944) components.
With this implemented, there are components (part of another PR), that could be updated to use this instead of manually: …
> feat(v-scroll): add self modifier to target the bound element

- packages/docs/src/examples/intersect/simple/options.vue
- packages/docs/src/examples/intersect/usage.vue
I have a friend who didn't understand the Intersect colored dot example because he has deuteranomaly color blindness.
To help that friend to understand the example I created this PR to increase the colored dot contrast (lighter green, darker red).
With his eyes.
> docs(Intersect): increase colored dot contrast

- packages/vuetify/src/components/VSparkline/VSparkline.ts
- packages/vuetify/src/components/VSparkline/__tests__/__snapshots__/VSparkline.spec.ts.snap
This MR removes the `id` property on the SVG `path` element from VSparkline.
VSparkline has a duplicated `id`. It uses the same `id` for it's `path` element and the `linearGradient`.
This creates an issue during SSR rehydration where the path disappear as it can't find the gradient.
This has been tested visually to check it's still renders properly. The snapshots have also been updated.
I haven't been able to link my local Vuetify to a Nuxt project to check removing the duplicated `id` does fix the issue, however it seems very likely it will.
<details>
```vue
<template>
<v-container>
<v-sparkline
auto-draw
:value="[0, 2, 5, 9, 5, 10, 3, 5, 0, 0, 1, 8, 2, 9, 0]"
:gradient="['#623195', '#9e6dd1']"
:line-width="2"
/>
</v-container>
</template>
<script>
data: () => ({
//
}), …
```
> fix(VSparkline): fix duplicate id on VSparkline path

- packages/vuetify/src/components/VRangeSlider/VRangeSlider.ts
- packages/vuetify/src/components/VRangeSlider/__tests__/VRangeSlider.spec.ts
- packages/vuetify/src/components/VRangeSlider/__tests__/__snapshots__/VRangeSlider.spec.ts.snap
fixed padded width of disabled slider
also refactored rendering of slider sections to get rid of an ugly transition jump when toggling disabled state
closes #11302
<details>
```vue
<template>
<div>
<v-switch label="vertical" v-model="vertical"></v-switch>
<v-switch label="rtl" v-model="$vuetify.rtl"></v-switch>
<v-switch label="disabled ticks" v-model="enabledTicks"></v-switch>
<v-range-slider max="100" min="0"  :disabled="!enabledNoTicks" v-model="slide3" :vertical="vertical"></v-range-slider>
</div>
</template>
<script>
data: () => ({
enabledNoTicks: true,
slide3: [30, 50],
vertical: false,
}),
}
</script>
```
</details>
> fix(VRangeSlider): incorrect slider width when disabled

- packages/vuetify/src/components/VDataTable/VDataTable.ts
- packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts
Currently, if a custom filter is used on a header config, it won't evaluate on any `search` term that exclusively match this custom filter. The term must match one or more columns that fall under `headersWithoutCustomFilters`.
Closes #9887 
Behaviour is inconsistent since the custom filter will be evaluated up until the point that a search term is entered. Once a term is entered, even if the term matches the custom filter, the row is excluded from the results if none of the other columns match.
A simple example is provided in the Codepen in the linked issue: by adding a custom filter with a case-sensitive search for Dessert Name, the ability to search is lost.
- Tested in our own project which uses Vuetify
- Playground reproduction (below)
- Added a unit test verifying the …
> fix(VDataTable): include rows that exclusively match custom filters

- packages/vuetify/src/components/VSlider/VSlider.sass
- packages/vuetify/src/components/VSlider/VSlider.ts
fixes #11028
playground
<details>
```vue
<template>
<v-container>
<v-btn block @click="$vuetify.rtl = !$vuetify.rtl">{{ $vuetify.rtl ? 'rtl' : 'ltr' }}</v-btn>
<v-range-slider
v-model="v"
:tick-labels="['Winter', 'Spring', 'Summer', 'Fall']"
min="0"
max="6"
step="2"
ticks="always"
tick-size="4"
/>
<v-range-slider
v-model="v"
min="0"
max="50"
step="2"
ticks="always"
tick-size="4"
/>
</v-container>
</template>
<script>
data: () => ({ v: [2, 4] }),
}
</script>
```
</details>
> fix(VSlider): wrong tick labels positions in RTL mode

- packages/vuetify/src/components/VTextField/VTextField.ts
fixes #11269
playground
<details>
```vue
<template>
<v-container>
<v-text-field
:label="label"
outlined
value="I am value"
/>
<div>PR doesn't fix issue with label slot</div>
<v-text-field
#label
outlined
value="I am value"
>{{ label }}</v-text-field>
</v-container>
</template>
<script>
data: () => ({
label: '',
}),
async mounted () {
setTimeout(() => {
this.label = 'foo'
setTimeout(() => {
this.label = ''
}, 1000)
}, 1000)
},
}
</script>
```
</details>
> fix(VTextField): remove gap when outlined label changes to empty

- packages/docs/src/lang/en/components/Alerts.json
Fixes a typo on the [Alert page](https://vuetifyjs.com/en/components/alerts/).
> docs(alerts): fix typo

- packages/docs/src/data/pages/styles/Display.pug
- packages/docs/src/lang/en/styles/Display.json
- packages/vuetify/src/styles/utilities/_index.sass
- packages/vuetify/src/styles/utilities/_screenreaders.sass
fix #10914
This adds visually hidden utility classes to Vuetify. This can be used to make items visible to screen readers only.
The two classes are:
- `v-sr-only`: Make the element visually hidden and only visible to screen readers
- `v-sr-only-focusable`: Make the element visually hidden and only visible to screen readers, but make it visible when focused. Can be used to implement skip links.
resolves #10914
This resolves the following feature request: https://github.com/vuetifyjs/vuetify/issues/10914
Tested visually in Vuetify playground.
Implementation comes from Bootstrap so it should be thoroughly tested by them.
<details>
```vue
<template>
<v-container>
<div class="v-sr-only">Hello Screen Reader</div>
<a href="https://google.com">Focusable</a>
<a href="https://google.com" …
```
> feat(accessibility): add visually hidden css utility classes

- packages/vuetify/src/util/__tests__/mergeData.spec.ts
- packages/vuetify/src/util/mergeData.ts
Provides utilities for merging parts of VNodeData. Sometimes we just want to merge only classes or listeners instead of full data object.
Might be used for instance here: https://github.com/vuetifyjs/vuetify/pull/11126/files#diff-27a9bd669f7e558ec66554510a51c4afR81
unit
> refactor: mergeClasses, mergeStyles, mergeListeners

- packages/vuetify/src/components/VDatePicker/VDatePicker.ts
- packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.date.spec.ts
fixes #6714
jest, playground
<details>
```vue
<template>
<div>
<v-date-picker
value="2030-05-04"
show-current="2030-05-20"
/>
<v-date-picker show-current="2030-05-20" />
<v-date-picker value="2030-04-04" />
</div>
</template>
```
</details>
> fix(VDatePicker): set proper tableDate if showCurrent is set

- packages/vuetify/src/components/VTreeview/VTreeview.sass
- packages/vuetify/src/components/VTreeview/VTreeview.ts
- packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
- packages/vuetify/src/components/VTreeview/__tests__/VTreeview.spec.ts
- packages/vuetify/src/components/VTreeview/__tests__/__snapshots__/VTreeviewNode.spec.ts.snap
it was not possible to select children of disabled parents in independent mode
closes #10770, closes #10990
<details>
```vue
<template>
<v-container>
<v-treeview
open-on-click
:items="tree"
item-text="text"
item-key="id"
selectable
:value="selected"
selection-type="independent"
item-disabled="item_disabled"
></v-treeview>
<hr/>
<v-treeview
open-on-click
:items="tree"
item-text="text"
item-key="id"
selectable
:value="selected2"
item-disabled="item_disabled"
></v-treeview>
<v-treeview
v-model="selected3"
activatable
selectable
selection-type="independent"
:active.sync="selected3"
hoverable
return-object
dense
open-all
open-on-click
:items="items"
:open.sync="open"
item-disabled="disabled"
>
<template v-slot:prepend="{ item }">
<v-icon …
```
> fix(VTreeview): independent children should be selectable when parent is disabled

- packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
- packages/vuetify/src/components/VTreeview/__tests__/VTreeview.spec.ts
- packages/vuetify/src/components/VTreeview/__tests__/__snapshots__/VTreeview.spec.ts.snap
using load-children together with open-on-click and clicking on
root div of node, treeview was not emitting the newly opened node.
closes #9693
<details>
```vue
<template>
<v-container>
<v-treeview
:active.sync="active"
:items="items"
:load-children="fetchUsers"
:open.sync="open"
activatable
color="warning"
open-on-click
transition
>
<template v-slot:prepend="{ item }">
<v-icon v-if="!item.children">mdi-account</v-icon>
</template>
</v-treeview>
<div><b>Opened:</b> {{ open.join(", ") }}</div>
</v-container>
</template>
<script>
const pause = ms => new Promise(resolve => setTimeout(resolve, ms))
data: () => ({
active: [],
avatar: null,
open: [],
users: [],
}),
computed: {
items () {
return [
{
id: 'Folder1',
name: 'Folder1',
children: this.users,
},
] …
```
> fix(VTreeview): emit opened nodes when using load-children

- packages/vuetify/src/components/VGrid/_grid.sass
- packages/vuetify/src/components/VGrid/_mixins.sass
fixes #6317
playground
<details>
```vue
<template>
<v-container>
<v-btn @click="$vuetify.rtl = !$vuetify.rtl">RTL</v-btn>
<v-row class="yellow">
<v-col
cols="2"
offset="1"
class="blue"
/>
<v-col
cols="5"
offset="4"
class="blue"
/>
</v-row>
<v-layout yellow>
<v-flex
xs2
offset-xs1
blue
>foo</v-flex>
<v-flex
xs5
offset-xs4
blue
>foo</v-flex>
</v-layout>
</v-container>
</template>
```
</details>
> fix(VGrid): offset in RTL mode

- packages/vuetify/src/components/VVirtualScroll/VVirtualScroll.ts
The key of the items is not right. It should never change to avoid unnecessary re-renders
Change key value from the index of the element based on the rendered to the index of the element based on all items
This change will improve the component performance.
Playground example.
See example provided in the section below and test it with browser cache disabled to visually see the issue
<details>
```vue
<template>
<v-container>
<v-virtual-scroll height="750px" :items="items" item-height="250">
<template v-slot="{ item }">
<div class="item">
I'm item number {{ item.id }}
<v-img width="200" height="200" :src="'https://picsum.photos/id/'+ item.id +'/200/200'"></v-img>
</div>
</template>
</v-virtual-scroll>
</v-container>
</template>
<script>
import VVirtualScroll from '../src/components'
const …
```
> fix(vvirtualscroll): the key of the children is not right

- packages/docs/src/snippets/js/using_missing_material_icons.txt
The example doesn't work as is. The values object is missing as per the other examples.
> Fix missing Material Icons example

- packages/vuetify/src/styles/generic/_reset.scss
Changed the selector for "cursor: default" to `[aria-disabled="true"]` so that the behavior does not apply to `[aria-disabled="false"]`
Resolves #11003 
Tested in the playground.
<details>
```vue
<template>
<v-container>
<v-btn>
button1 (cursor default)
</v-btn>
<v-btn aria-disabled="true">
button2 (cursor pointer)
</v-btn>
<v-btn aria-disabled="false">
button3 (cursor default)
</v-btn>
</v-container>
</template>
<script>
data: () => ({
//
}),
}
</script>
```
</details>
> fix: change curser:default selector to [aria-disabled="true"]

- packages/vuetify/src/components/VDataTable/VDataTableHeaderMobile.ts
v-select also uses divider boolean to render divider in menu
closes #11399
playground
<details>
```vue
<template>
<v-data-table
sort-by="calories"
</template>
<script>
data () {
return {
headers: [
{
value: 'name',
divider: true,
},
// { text: 'Calories', value: 'calories' },
// { text: 'Fat (g)', value: 'fat' },
// { text: 'Carbs (g)', value: 'carbs' },
// { text: 'Protein (g)', value: 'protein' },
// { text: 'Iron (%)', value: 'iron' },
],
desserts: [
{
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1%',
},
{
calories: 237,
fat: 9.0,
carbs: 37,
protein: 4.3,
iron: '1%',
},
{ …
```
> fix(VDataTable): header with divider rendered incorrectly in mobile sort select

- packages/docs/src/layouts/layouts/demos/baseline-flipped.vue
- packages/docs/src/layouts/layouts/demos/baseline.vue
- packages/docs/src/layouts/layouts/demos/centered.vue
- packages/docs/src/layouts/layouts/demos/dark.vue
- packages/docs/src/layouts/layouts/demos/google-contacts.vue
- packages/docs/src/layouts/layouts/demos/google-youtube.vue
* mdi-settings -> mdi-cog according to https://materialdesignicons.com/icon/cog
Signed-off-by: Victor Lourme <victor.lourme@icloud.com>
Change the mdi icon to **cog** instead of **settings**. `mdi-settings` seems not working anymore and is not referenced in https://materialdesignicons.com/.
As these demos are accessible from the vuetifyjs.com docs, now the demo does not have any bugs.
Edit: the Codepen has the bug also.
Tested visually.
> docs/demos: fix icons

- packages/vuetify/src/components/VDataTable/VSimpleTable.sass
fixes #11567
fixes #11566
playground
```vue
<template>
<v-data-table dense :headers="[{text:'foo',value:'foo'}]" :items="[{foo: 'foo'}, {foo: 'bar'}]" />
</template>
```
> fix(VDataTable): dense mode not working, missing header border

- packages/vuetify/src/components/VSlideGroup/VSlideGroup.sass
partially implements #10673
Fixes slide group issue on mobile where browser scrolls vertically when you are trying to only scroll horizontally.
When using touch to scroll in a slide group the browser also scrolls vertically which is undesired.
Visually in the docs
> fix(VSlideGroup): vertical scroll lock for touch

- packages/vuetify/src/components/VSelect/VSelect.sass
Due to flex laylout of `.v-select__slot` element(parent has `display: flex`), need to set min-width to zero
fix #11524
> fix(VSelect): fix width of long items

- packages/vuetify/src/components/VDataTable/VDataTable.ts
- packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts
Ensure that filters and search terms are combined to display the intersection of results, rather than the union - so each filter applied makes the set of matches smaller for refined searching.
fixes #11402 
There is some discussion on issue #11402 , but the current behaviour is very surprising and unlikely to be what a majority of users would want.
Note that I have not marked this as a breaking change, though it changes behaviour - as in the wording below "would cause existing functionality to not work as expected", I don't believe the current behaviour is what would be expected..
Unit tests included for the case where we have column filtering only, search term only and both. I replaced a previous test which would no longer pass, since it would include items which matched EITHER search …
> fix(VDataTable): union column filter with search results

- packages/docs/src/examples/bottom-sheets/simple/persistent.vue
Updating 'flat' props by 'text' for v-btn into v-bottom-sheet. This fix the breaking change error.
> docs(VBottomSheet): Updating 'flat' by 'text'

- packages/docs/src/examples/text-fields/simple/icon.vue
[Reference](https://vuetifyjs.com/en/components/text-fields/#text-fields)
Text field / icons
> docs: Fixed icon reference

- packages/vuetify/src/components/VVirtualScroll/VVirtualScroll.ts
- packages/vuetify/src/components/VVirtualScroll/__tests__/VVirtualScroll.spec.ts
fix #11707
resolves #11707 
Calculate children to render on mounted instead of created.
This is because if the user instantiate a vvirtualscroller without providing a value for the `height` prop in the created we were falling back to $el.clientHeight value, but in created there is no DOM
https://github.com/vuetifyjs/vuetify/issues/11707
Playground and update a unit test that were affected by this change
<details>
```vue
<template>
<v-container>
<v-card
max-width="400"
height="300"
>
<v-card-title class="white--text orange darken-4">
User Directory
<v-btn
color="white"
class="text--primary"
fab
small
>
<v-icon>mdi-plus</v-icon>
</v-btn>
<v-card-text class="pt-4">
Lorem ipsum dolor sit, amet consectetur adipisicing …
```
> fix(VVirtualscroll): calculate child on mounted instead of created

- packages/vuetify/src/locale/hu.ts
Fixed hu-Hungarian i18n
Following keys were changed:
- datePicker.itemsSelected
- carousel.prev
- carousel.next
- pagination.ariaLabel.wrapper
- pagination.ariaLabel.page
- pagination.ariaLabel.currentPage
- close
- dataIterator.loadingText
- dataTable.ariaLabel.sortDescending
- dataTable.ariaLabel.sortAscending
- dataTable.ariaLabel.sortNone
- dataTable.ariaLabel.activateNone
- dataTable.ariaLabel.activateDescending
- dataTable.ariaLabel.activateAscending
- dataTable.sortBy
- carousel.ariaLabel.delimiter
- fileInput.counter
- fileInput.counterSize
- timePicker.am
- timePicker.pm
The hungarian translation was incomplete and incorrect.
As far as the changes are only visual, every occurrence in components are tested by implementing them in a project.
> fix(locales): hu-Hungarian 1i8n translation

- packages/docs/src/lang/en/customization/SassVariables.json
- packages/docs/src/snippets/js/webpack_sass_variables.txt
this was changed with v9.0.0
https://github.com/webpack-contrib/sass-loader/releases/tag/v9.0.0
Our setup is using [sass-variables with `prependData` like described in the docs](https://vuetifyjs.com/en/customization/sass-variables/#webpack-install).
After upgrading [sass-loader](https://github.com/webpack-contrib/sass-loader/releases/tag/v9.0.0) to `9.0.0/9.0.1` builds started to fail with this error:
```
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
- options has an unknown property 'prependData'. These properties are valid:
object { implementation?, sassOptions?, additionalData?, sourceMap?, webpackImporter? }
```
Checking the release-notes of sass-loader 9.0.0 it states:
> the prependData option …
> docs(SassVariables): add additionalData for sass-loader v9.0.0 update

- packages/vuetify/src/components/VDatePicker/VDatePicker.ts
- packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.date.spec.ts
- packages/vuetify/src/components/VDatePicker/__tests__/__snapshots__/VDatePicker.date.spec.ts.snap
Allows null/undefined value for range/multiple date pickers
fix, but deliberately dev branch
fixes #9529
jest, playground
<details>
```vue
<template>
<v-menu
:close-on-content-click="false"
max-width="290"
>
<v-text-field
clearable
:label="JSON.stringify(value)"
readonly
v-on="on"
/>
<v-checkbox
v-model="isRange"
label="true = range, false = mutliple"
/>
</template>
<v-date-picker
v-bind="{ [isRange ? 'range' : 'multiple']: true }"
/>
</v-menu>
</template>
<script>
data: () => ({ value: null, isRange: true }),
}
</script>
```
</details>
> fix(VDatePicker): allow null value for multiple date picker

- packages/vuetify/src/components/VDataTable/MobileRow.ts
- packages/vuetify/src/components/VDataTable/VDataTable.ts
- packages/vuetify/src/components/VDataTable/__tests__/MobileRow.spec.ts
- packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/MobileRow.spec.ts.snap
Don't render the inline column headers on mobile when hide-default-header is specified on the VDataTable. Fixes #8774
Fixes #8774
unit, visually
<details>
```vue
<template>
<v-container>
<h1>Table below</h1>
<v-data-table
:items="names"
</v-container>
</template>
<script>
data: () => ({
headers: [
{
text: "Name",
value: "name",
},
],
names: [
{
name: "Oscar",
},
{
name: "Orlando",
},
{
name: "Osvaldo",
},
],
}),
};
</script>
```
</details>
> fix(VDataTable): respect hide-default-header prop on mobile

- packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts
Call `document.removeEventListener` when component is destroyed
VAutocomplete component leaks when the copy listener is attached to `document` but never released
Manually. Please let me know how this is usually automatically tested.
</details>
> fix(VAutocomplete): removeEventListener when destroyed

- packages/docs/src/lang/en/mixins/Detachable.json
The start of a sentence just after a period is missing a space.
```
Specifies which DOM element that this component should detach to.String can be any valid querySelector
^
```
N/A
N/A
<details>
```vue
```
</details>
> docs(Detachable): Add space after a period

- packages/docs/src/lang/en/components/Snackbars.json
Fixed the translation key for the `text` prop in the lang file for Snackbars.
From `VAlert` to `Alerts`.
The translation key for the `text` prop was incorrect.
> docs(v-snackbar): fixed translation key in Snackbars.json

- packages/vuetify/src/util/__tests__/mergeData.spec.ts
- packages/vuetify/src/util/mergeData.ts
fixes https://github.com/vuetifyjs/vuetify/issues/12018
https://github.com/vuetifyjs/vuetify/issues/12018
visually
<details>
```vue
<template>
<v-container>
<v-btn @click="visible = !visible">toggle</v-btn>
<v-expand-transition @afterEnter="afterEnter">
<div v-if="visible" style="height: 100px; background: red">
{{text}}
</div>
</v-expand-transition>
</v-container>
</template>
<script>
data: () => ({
visible: false,
text: 'afterEnter was NOT triggered'
}),
methods: {
afterEnter(el) {
this.text = 'afterEnter WAS triggered'
}
}
}
</script>
```
</details>
> fix(VExpandTransition): Properly trigger transition listeners

- packages/vuetify/src/components/VList/VListItem.sass
- packages/vuetify/src/components/VMenu/VMenu.sass
fix #12021
<details>
```vue
<template>
<div id="app">
<v-menu top>
<template v-slot:activator="{ on, attrs }">
<v-btn
dark
v-bind="attrs"
v-on="on"
>
Dropdown
</v-btn>
</template>
<v-list>
<v-list-item
:key="index"
disabled
@click="onClick($event)"
>
</v-list-item>
</v-list>
</v-menu>
</div>
</v-app>
</div>
</template>
<script>
data: () => ({
items: [
{ title: 'Click Me Disabled' },
{ title: 'Click Me' },
{ title: 'Click Me' },
{ title: 'Click Me 2' },
],
}),
methods: {
onClick (d) {
alert('ups, clicked on a disabled item')
console.log(d)
},
},
}
</script>
```
</details>
> fix(VListitem): disable mouse click in animating menu

- packages/vuetify/src/locale/ckb.ts
- packages/vuetify/src/locale/index.ts
This PR adds locale in CKB, [Central Kurdish AKA Sorani](https://en.wikipedia.org/wiki/Sorani), language.
I have been using Vuetify for a very long time, and I would like to see the support for my language.
It's been unit tested.
<details>
```vue
```
</details>
> add: Central Kurdish locale

- packages/vuetify/src/mixins/mobile/index.ts
- packages/vuetify/types/services/breakpoint.d.ts
`Breakpoint['name']` is now `number | 'xs' | 'xm' | ... `, should be only `'xs' | 'sm' | ...`
```vue
import Vue from 'vue'
export default Vue.extend({
mounted () {
this.$vuetify.breakpoint.name.trim()
},
})
</script>
```
> fix(types): number should not be allowed as a current breakpoint name

- packages/docs/src/examples/v-btn/prop-loaders.vue
The loading button icon is missing the 'mdi-' part. This causes the text 'cached' to rotate inside the button as instead to the icon. 
Does not look good son. 
None at all, doing this is from my phone at the moment.
> Icon missing the mdi- part

- packages/vuetify/src/components/VFileInput/VFileInput.sass
This pull request avoids that the native `input[type="file"]` field receives events when clicking on the input part of v-file-input.
Fixes #10832.
With this change, v-file-input works as expected in Safari, as described in #10832.
I tested the change locally with the code provided in https://codepen.io/anon/pen/RXaPOX?&editable=true&editors=101.
<details>
```vue
<div id="app">
<v-file-input label="File input"></v-file-input>
</v-app>
</div>
```
</details>
> fix(VFileInput): avoid input field event capturing in safari

- packages/vuetify/src/components/VIcon/VIcon.sass
- packages/vuetify/src/components/VIcon/VIcon.ts
- packages/vuetify/src/components/VIcon/__tests__/VIcon.spec.ts
- packages/vuetify/src/components/VIcon/__tests__/__snapshots__/VIcon.spec.ts.snap
fixes #10623
Font icons and SVG strings had a `<span>` or `<button>` put around them, but icon components were just rendered directly. This PR normalises the rendering behaviour between different types of icons. This probably fixes #9999 properly too as the click listener is now on the wrapping button instead of the provided component. 
Switch to `iconfont: 'faSvg'` in `dev/vuetify.js` first
```vue
<template>
<v-container>
<v-text-field clearable value="value" label="clearable"></v-text-field>
</v-container>
</template>
```
IDK if anyone has a complete icon playground, mostly just relying on snapshot tests for this.
> fix(VIcon): render a button element around clickable component icons

- packages/vuetify/src/styles/settings/_dark.scss
https://vuetifyjs.com/en/features/sass-variables/#variable-api lists `$material-dark-elevation-colors` as a variable which can be overridden, however that is not currently possible since the value was always being overridden since it was not merged with any other values provided.
The dark theme is very dark, I would like to be able to customize it without having to individually override the `$material-dark` individual elements.
I made this change locally and was able to override the `$material-dark-elevation-colors` variable as described on https://vuetifyjs.com/en/features/sass-variables/#variable-api
> fix: allow $material-dark-elevation-colors to be overridden

- packages/vuetify/src/components/VProgressCircular/VProgressCircular.sass
- packages/vuetify/src/components/VProgressCircular/_variables.scss
Tweaked the background color of circular progress bar
Background color of circular progress bar clashes with the default app background color on the dark theme. Tweaked the background color to make it more visible.
fixes #12149 
Manual visual inspection
<details>
```vue
<template>
<v-container>
<VProgressCircular
:value="10"
/>
</v-container>
</template>
<script>
data: () => ({
//
}),
}
</script>
```
</details>
> fix(VProgressCircular): dark theme background color clash

- packages/vuetify/types/services/icons.d.ts
Add missing icons (file|plus|minus) to VuetifyIcons interface
Added file, plus, minus to icons.d.ts to bring it into line with the icons listed in the preset [files](https://github.com/vuetifyjs/vuetify/tree/master/packages/vuetify/src/services/icons/presets)
Consistency
Untested
N/A
N/A
> fix(types): add missing icons to VuetifyIcons interface

- packages/docs/src/pages/en/features/icons.md
When using Material Design Icons webfont, the dependency is `@mdi/font` (not `@mdi/js`) as described in [this repository](https://github.com/Templarian/MaterialDesign-Webfont#webfont---material-design-icons).
Closes #12359
Unknown import when following the current ["Installing iconfonts / Material Design Icons"](https://vuetifyjs.com/en/features/icons/#material-design-icons) documentation:
```
```
> docs(icons): fix mdi webfont dependency name

- packages/vuetify/src/components/VDataTable/VDataTable.sass
There was already a rule resetting the row height for mobile row, but looks like after #11325 it no longer had enough CSS specificity to apply.
I increased the specificity of the rule, and also added padding for the mobile column header, which was brought up in a comment to #8411.
Fixes #8411
Fixes #8411
visually
<details>
```vue
<template>
<v-data-table
</template>
<script>
data: () => ({
headers: [
{
text: "Dessert (100g serving)",
align: "left",
value: "name",
},
{ text: "Calories", value: "calories" },
{ text: "Fat (g)", value: "fat" },
{ text: "Carbs (g)", value: "carbs" },
{ text: "Protein (g)", value: "protein" },
{ text: "Test", value: "iron" },
], …
```
> fix(VDataTable): on mobile, expand rows to fit text

- packages/vuetify/src/components/VIcon/VIcon.ts
- packages/vuetify/src/components/VIcon/__tests__/__snapshots__/VIcon.spec.ts.snap
Fixes regression from #12148 preventing size props from working
fixes #12372
<details>
```vue
<template>
<v-container>
<v-btn color="primary" icon>
<v-icon large>{{ mdiAccountCircle }}</v-icon>
</v-btn>
<v-btn color="primary" icon>
<v-icon>{{ mdiAccountCircle }}</v-icon>
</v-btn>
</v-container>
</template>
<script>
import { mdiAccountCircle } from '@mdi/js'
data: () => ({
mdiAccountCircle,
}),
}
</script>
```
</details>
> fix(VIcon): set svg dimensions in style instead of attributes

- packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts
- packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete.spec.ts
- packages/vuetify/src/components/VSelect/VSelect.ts
fix #11989
Copied idea from VTextField
<details>
```vue
<template>
<div id="app">
<v-app>
<div style="width: 200px; margin: auto;">
ref="autocomplete"
:items="items"
<v-btn @click.stop="focusAutocomplete">focus</v-btn>
<v-text-field
ref="textfield"
<v-btn @click.stop="focusTextField">focus</v-btn>
</div>
</v-app></div>
</template>
<script>
data: () => ({
model: null,
items: [
'Autocompletes', 'Comboboxes', 'Forms', 'Inputs', 'Overflow Buttons', 'Selects', 'Selection Controls', 'Sliders', 'Textareas', 'Text Fields',
],
}),
computed: {
dateRangeText () {
return this.dates.join(' ~ ')
},
},
methods: {
focusAutocomplete () {
this.$refs.autocomplete.focus()
},
focusTextField () { …
```
> fix(VAutocomplete): set isFocused to false on blur

- packages/vuetify/src/components/VSelect/VSelectList.ts
when genFilteredText could not find the supplied text, it would always highlight the entire string. This behavior was unwanted, especially when using genFilteredText multiple times within an item slot, where it would highlight all other strings that did not match. With this change, it will instead not highlight the string when it can't find a match. fixes #10843
fixes #10843
I visually tested the change locally.
> fix(VSelect): do not highlight search text without an item match

- packages/docs/src/examples/v-combobox/usage.vue
Fix length of null error for the settings for usage in docs
Fixed data structure to fix error: `TypeError: Cannot read property 'length' of undefined` on combobox documents usage section
Moved the tabs data from within the options object to the data root as should be.
Fix for error: `TypeError: Cannot read property 'length' of undefined` on combobox documents usage section
> docs: Fix Combobox Docs Error

- packages/docs/src/components/doc/BreakpointsTable.vue
Changed the breakpoint range of lg screen from '960px > < 1264px*' to '1264px > < 1904px*' in the <breakpoint-table> component
Fixes a typographical error
> docs: correct typo in breakpoint table

- packages/api-generator/src/locale/en/v-card.json
Fixes a broken link at https://vuetifyjs.com/en/api/v-card/#props at "v-img example here"
> docs: fix broken link in documentation of v-card img

- packages/vuetify/src/services/icons/__tests__/__snapshots__/icons.spec.ts.snap
- packages/vuetify/src/services/icons/presets/mdi.ts
fixes the `mdi-` rating-half icon to match mdi-svg and docs
resolves #12336
visually
> fix(icons): use correct mdi icon for rating-half

- packages/vuetify/src/components/VTextField/VTextField.ts
Fixed the counter to be able to count surrogate pairs.
We can try it on the console of web browser.
```js
const internalValue = '𠝏'; // should be 1
(internalValue || '').toString().length; // 2
[...(internalValue || '')].length; // 1
```
> fix(VTextField): count characters instead of codepoints

- packages/vuetify/src/components/VProgressLinear/VProgressLinear.sass
z-index values caused issue when used in v-data-table
closes #11847
manually
<details>
```vue
<template>
<v-data-table
fixed-header
height="70vh"
>
<template v-slot:item.fat="{ item }">
:background-opacity="0.3"
:buffer-value="100"
:height="25"
:width="150"
:rounded="true"
:value="item.fat"
>
<div>{{ item.fat }}</div>
</v-progress-linear>
</template>
</template>
<script>
data () {
return {
search: '',
headers: [
{
value: 'name',
},
],
desserts: [
{
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1%',
},
{
calories: 237,
fat: …
```
> fix(VLinearProgress): remove unnecessary z-index

- packages/vuetify/src/components/VTextField/VTextField.ts
fixed #12451 that is the issue with number and boolean types that could cause errors.
```html
<v-text-field
v-model.number="age"
counter="3"
/>
```
> fix(VTextField): count non-string types

- packages/api-generator/src/maps/v-app-bar-title.js
- packages/docs/src/examples/v-app-bar/prop-img-fade.vue
- packages/docs/src/examples/v-app-bar/prop-img.vue
- packages/docs/src/examples/v-app-bar/prop-prominent.vue
- packages/docs/src/examples/v-app-bar/prop-scroll-threshold.vue
- packages/docs/src/pages/en/components/app-bars.md
- packages/vuetify/src/components/VAppBar/VAppBar.sass
- packages/vuetify/src/components/VAppBar/VAppBar.ts
- packages/vuetify/src/components/VAppBar/VAppBarTitle.ts
- packages/vuetify/src/components/VAppBar/__tests__/VAppBar.spec.ts
- packages/vuetify/src/components/VAppBar/index.ts
Adds a new v-app-bar-title component which uses absolute positioning to avoid
being truncated when there isn't enough space in the main part of the toolbar
closes #12514
<details>
```vue
<template>
<v-container style="height: 1200px">
<v-app-bar
fixed
shrink-on-scroll
>
<v-app-bar-title>Vuetify.js</v-app-bar-title>
<v-spacer />
<v-btn icon>
<v-icon>mdi-chart-box-outline</v-icon>
</v-btn>
<v-btn icon>
<v-icon>mdi-cog-outline</v-icon>
</v-btn>
<v-responsive max-width="260">
<v-text-field
class="ml-1"
dense
flat
placeholder="Search Anywhere"
hide-details
rounded
solo-inverted
prepend-inner-icon="mdi-magnify"
/>
</v-responsive>
<v-btn icon>
<v-icon>mdi-menu</v-icon>
</v-btn>
</v-app-bar>
</v-container>
</template>
```
</details>
> feat(VAppBar): don't truncate title with shrink-on-scroll

- packages/vuetify/src/components/VBanner/VBanner.sass
fixes https://github.com/vuetifyjs/vuetify/issues/12172
fixes https://github.com/vuetifyjs/vuetify/issues/12172
visually
---
before behavior
after behavior
<details>
```vue
<template>
<v-container>
<v-row class="ma-4">
<div
d-flex
flex-row
class="ma-4"
>
<p class="teal">normal</p>
<v-banner
width="400px"
class="ma-4"
> {{ message }}
</v-banner>
</div>
</v-row>
<v-row class="ma-4">
<div
d-flex
flex-row
class="ma-4"
>
<p class="teal">outlined</p>
<v-banner
outlined
width="400px"
class="ma-4"
> {{ message }}
</v-banner>
</div>
</v-row>
<v-row class="ma-4">
<div
d-flex
flex-row
class="ma-4"
>
<p class="teal">elevation</p>
<v-banner
width="400px"
class="ma-4"
elevation="4"
> {{ message }}
</v-banner>
</div>
</v-row>
<v-row class="ma-4">
<div
d-flex
flex-row
class="ma-4"
>
<p …
```
> fix(VBanner): remove bottom-border on outlined banner

- packages/api-generator/.gitignore
- packages/api-generator/src/locale/en/v-chip.json
- packages/vuetify/src/components/VChip/VChip.ts
- packages/vuetify/src/components/VChip/__tests__/VChip.spec.ts
- packages/vuetify/src/components/VChip/__tests__/__snapshots__/VChip.spec.ts.snap
fixes #11165 by adding a default aria-label of `'$vuetify.close'` to the close `<button>` tag on VChip. This change also created a new prop of `close-label` on VChip.
#11165
Tested in playground and with unit tests. Added a unit test to check for new aria-label when expected.
```vue
<template>
<v-container>
<v-chip
close
close-icon="mdi-close-outline"
color="green"
>Hello Vuetify (default aria label)</v-chip>
<v-chip
close
close-icon="mdi-close-outline"
color="purple"
close-label="custom aria label"
>Hello Vuetify (custom aria label)</v-chip>
</v-container>
</template>
<script>
data: () => ({
//
}),
}
</script>
```
</details>
> fix(VChip): add aria-label to chip close button

- packages/vuetify/src/components/VMenu/VMenu.ts
fixes #12412  
I fixed it so that VMenu closes the hover with a single click when open-on-hover is enabled in mobile.
fixes #12412  
Without this fix, VMenu would behave twice  with open-on-hover  enabled in mobile.
visually
---
**before behavior**  
**after behavior**  
<details>
```vue
<template>
<v-container>
<v-menu open-on-hover top offset-y @change=temp()>
<template v-slot:activator="{ on, attrs }">
<v-btn color="primary" dark v-bind="attrs" v-on="on">
Dropdown
</v-btn>
</template>
<v-list>
<v-list-item v-for="(item, index) in items" :key="index">
</v-list-item>
</v-list>
</v-menu>
</div>
</v-container>
</template>
<script>
data: () => ({
items: [
{ title: 'Click 1' },
{ title: 'Click …
```
> fix(VMenu): open-on-hover does not close-on-content-click

- packages/api-generator/src/locale/en/v-color-picker.json
- packages/docs/src/examples/v-color-picker/usage.vue
- packages/docs/src/pages/en/components/color-pickers.md
- packages/vuetify/src/components/VColorPicker/VColorPicker.ts
- packages/vuetify/src/components/VColorPicker/__tests__/VColorPicker.spec.ts
- packages/vuetify/src/components/VColorPicker/__tests__/__snapshots__/VColorPicker.spec.ts.snap
Added the ability to hide sliders in VColorPicker.
**This is the same what has been done in https://github.com/vuetifyjs/vuetify/pull/11827. However this PR had some merge conflicts and it seems like it is abondoned now. That's why I have created a new PR.**
re #11138
resolves #11138
Added new prop `hide-sliders` for in `VColorPicker`. When this prop is true, the sliders are hidden.
Right it is not possible to have a `VColorPicker` with swatches only. Thanks, to the new prop, you can hide canvas, inputs and sliders, which gives the possibility to show only swatches.
visually and unit tests
<details>
```vue
<template>
<v-container>
<v-color-picker v-model="color" show-swatches :swatches="swatches" hide-sliders hide-inputs hide-canvas />
<div>color</div>
<pre>{{ color }}</pre> …
```
> feat(vcolorpicker): add hideSliders prop

- packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts
- packages/vuetify/src/components/VCombobox/VCombobox.ts
fixes #12322
I can't think of a good reason to count `''` as clean, search is reset to null on blur anyway so it can only mean:
- value is `''` and nothing was changed, or
- value is set and search was deleted by the user
Only checked with combobox, probably doesn't break autocomplete though. 
<details>
```vue
<template>
<v-container>
<pre>{{ JSON.stringify(String(select)) }}</pre>
<pre>{{ JSON.stringify(String(search)) }}</pre>
<v-combobox v-model="select" :search-input.sync="search"></v-combobox>
<v-btn @click="select = ''">reset</v-btn>
<v-btn @click="search = ''">reset search</v-btn>
</v-container>
</template>
<script>
data: () => ({
select: '',
search: '',
}),
}
</script>
```
</details>
> fix(VCombobox): don't reset value to null if search is empty

- packages/vuetify/src/components/VTextField/VTextField.ts
resolves #12499
Having both label and placeholder displayed can be a usability problem as the placeholder looks very similar to typed text and could be confused with user input at a glance.
Potentially breaking change, you can't show both label and placeholder any more but this should be discouraged anyway. 
EDIT: This is actually MD2 spec now:
<details>
```vue
<template>
<v-container>
<v-text-field label="Label"></v-text-field>
<v-text-field
label="Label"
<v-text-field
label="Label"
single-line
<v-text-field
label="Label"
value="Value"
</v-container>
</template>
```
</details>
> feat(VTextField): only show placeholder on focus if label is set

- packages/vuetify/src/locale/bg.ts
- packages/vuetify/src/locale/index.ts
Add new bulgarian localization
New localization added to vuetify
Tested some of the visual changes (data-table footer)
<details>
```vue
```
</details>
> fix(locale) Add bulgarian localization

- packages/vuetify/src/components/VCarousel/VCarousel.ts
- packages/vuetify/src/components/VWindow/VWindow.ts
- packages/vuetify/src/components/VWindow/__tests__/VWindow.spec.ts
- packages/vuetify/src/components/VWindow/__tests__/VWindowItem.spec.ts
using touch would result in incorrect transition when looping around
closes #11280
<details>
```vue
<template>
<div>
<v-switch
v-model="$vuetify.rtl"
label="RTL"
/>
<v-btn @click="foo = foo - 1 < 0 ? slides.length - 1 : foo - 1">prev</v-btn>
<v-btn @click="foo = foo + 1 >= slides.length ? 0 : foo + 1">next</v-btn>
<v-carousel
v-model="foo"
height="400"
hide-delimiter-background
show-arrows-on-hover
>
v-for="(slide, i) in slides"
:key="i"
>
<v-sheet
:color="colors[i]"
height="100%"
>
<v-row
class="fill-height"
align="center"
justify="center"
>
<div class="display-3">{{ slide }} Slide</div>
</v-row>
</v-sheet>
</v-carousel>
<v-carousel
height="400"
hide-delimiter-background
show-arrows-on-hover
reverse
>
v-for="(slide, i) in slides" …
```
> fix(VCarousel): incorrect transition direction when using touch

- packages/vuetify/src/components/VDataIterator/VDataFooter.ts
This resolves #11829.
`footer.page-text` template will always be applied even if there are no items in the table.
Solves the issue where one always wants to show the set custom `footer.page-text` even if table is empty.
Only tested visually, with the given example from issue #11829
<details>
```vue
<template>
<v-container>
<v-data-table :items="tableItems">
<template v-slot:footer.page-text="props">
Custom page-text
</template>
</v-container>
</template>
<script>
data: () => ({
tableItems: []
// tableItems: [{}]
}),
}
</script>
```
</details>
> fix(VDataFooter): Show set footer.page-text on empty data table

- packages/vuetify/src/components/VWindow/VWindow.ts
fixes #12672
Issue  #12672 is caused by a recent change from [PR 12357](https://github.com/vuetifyjs/vuetify/pull/12357). Its change results in wrong animation reverse logic when items length is less than 3. 
This pull request is making it fully support all items length in terms of animation reverse logic on top of the code from [PR 12357](https://github.com/vuetifyjs/vuetify/pull/12357). 
@nekosaur please help to check it out to see this change would raise any concerns from you and please also feel free to leave any feedback :). 
closes #12672
visually
<details>
```vue
<template>
<v-container>
<v-card>
<v-toolbar flat>
<template v-slot:extension>
<v-tabs
v-model="tabs"
fixed-tabs
>
<v-tabs-slider></v-tabs-slider>
<v-tab
href="#mobile-tabs-5-1"
class="primary--text"
> …
```
> fix(VWindow): fix wrong reverse animation logic for only 2 items

- packages/vuetify/src/components/VTextField/VTextField.sass
- packages/vuetify/src/components/VTextField/_variables.scss
fixed #12660
fixes #12401
This is a small update to the bug I just recently submitted allowing for explicitly setting the padding-top of .v-text-field__details as error messages get cut off when using some fonts.  One line was added to _variables.scss and one line to VTextField.sass.
Resolves #12660 / #12401 by simply adding padding-top custom variable to VTextField
Error message in VTextField is cut off on top if using certain fonts like Nunito
Has not been tested as this does not change anything because default padding-top on .v-text-field__details was already 0.  Now it is just explicitly being set.
> fix(VTextField): add padding-top custom variable to details

- packages/vuetify/src/components/VInput/VInput.ts
- packages/vuetify/src/components/VInput/__tests__/VInput.spec.ts
- packages/vuetify/src/components/VInput/__tests__/__snapshots__/VInput.spec.ts.snap
- packages/vuetify/src/components/VTextField/VTextField.ts
- packages/vuetify/src/components/VTextField/__tests__/__snapshots__/VTextField.spec.ts.snap
Partial revert of #12554.
#12554 introduced unintended regression of the functionality of `hide-details="auto"`
resolves #12755
visual | jest
<details>
```vue
<template>
<v-container>
<v-checkbox
v-model="hasMessage"
label="Show Message"
/>
<v-checkbox
v-model="hideDetails"
label="hideDetails"
/>
<v-row>
<v-col>
<v-text-field
label="Test Message Animation"
:hide-details="d"
:error="hasMessage"
:messages="hasMessage ? 'Message to see' : undefined"
/>
</v-col>
<v-col>
<v-radio-group
:error="hasMessage"
:messages="hasMessage ? 'Message to see' : undefined"
hide-details="auto"
>
<v-radio label="Test" />
</v-col>
</v-row>
</v-container>
</template>
<script>
data: () => ({
hasMessage: false,
hideDetails: false,
}),
computed: {
d () {
return this.hideDetails ? …
```
> revert(VTextField): partial revert of #12554

- packages/vuetify/src/components/VDivider/VDivider.sass
Reverts vuetifyjs/vuetify#12735
regression caused by #12755
resolves #12752
visual
<details>
```vue
```
</details>
> revert(VDivider): vertical v-divider not displayed when inside div

- packages/vuetify/src/components/VCard/_variables.scss
- packages/vuetify/src/components/VDialog/VDialog.sass
- packages/vuetify/src/components/VDialog/_variables.scss
fixes #10605
Incorrect positioning for v-card-actions when v-card is used in v-dialog is fixed by changing the default padding for v-card-actions to get it into correct position.
Changed default padding for v-card-actions in variables file in order to make it correctly positioned .
fixes #10605
In order to start phase # 1 of Vuetify Titan all bugs with vcard had to be resolved.
Resolves Following Issue.
#10605
This has been tested visually.
<details>
```
<template>
<v-container>
<v-dialog v-model="showDialog">
<v-card>
<v-card-title>This is positioned correctly</v-card-title>
<v-card-subtitle>This is positioned too far to the left</v-card-subtitle>
<v-card-text>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque in ipsum purus. Vestibulum non diam ultricies, scelerisque ex …
```
> fix(VCard): Incorrect positioning for v-card-actions in v-dialog

- packages/vuetify/src/components/VData/__tests__/VData.spec.ts
- packages/vuetify/src/util/helpers.ts
- packages/vuetify/types/index.d.ts
If the property which is used as groupBy contains null a TypeError is thrown (TypeError: Cannot read property 'items' of undefined) in https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/util/helpers.ts#L278 as the variable `current` is initialized with null.
Reproduction: https://codepen.io/WOL-Soft/pen/VweojBr
With this fix all items which are provided with null values or which completely miss the property used for grouping are grouped under a 'empty' group. The null group can be identified via the property `name` of the `ItemGroup` (name will be set to an empty string).
Fixes #12069
Fixes #12501 
* unit tests
> fix(helpers): coerce name value to string in groupItems

- packages/vuetify/src/components/VSnackbar/VSnackbar.sass
Apply either `left` or `right`, and either `top` or `bottom` CSS properties to snackbar component, to avoid confusing some mobile browsers (Android Chrome, Firefox) causing unwanted positioning.
fixes #11781 
Scrolling up or down would make the snackbar up and down when positioned at the bottom. So if the browser address bar is visible, the snackbar is hidden when positioned at the bottom.
fixes #11781 
Tested with remote debugging on Android Chrome (version 87.0.4280.101) and Android Firefox (version 82.1.3).
With these changes, the snackbar is not hidden anymore behind the browser address bar, and remains fixed when scrolling (so long as the `absolute` prop is not provided).
I don't see how the `absolute` prop is useful on mobile, since depending on `top` or `bottom` positioning the …
> fix(VSnackbar): set position of opposite direction values

- packages/vuetify/src/components/VImg/VImg.ts
fixes #11426 
https://bugzilla.mozilla.org/show_bug.cgi?id=700533
In Firefox, the image.onload callback is not called (size 0 for SVG)
visually
<details>
```vue
<template>
<div id="app">
<v-app>
<v-container>
<v-row>
svg no given height/width
<v-img src="https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/410.svg"></v-img>
</v-row>
<v-row>
svg with height/width
<v-img src="https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/AJ_Digital_Camera.svg"></v-img>
</v-row>
<v-row>
data-url:
<v-img src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3Ccircle r='50' cx='50' cy='50' fill='tomato'/%3E%3Ccircle r='41' cx='47' cy='50' fill='orange'/%3E%3Ccircle r='33' cx='48' cy='53' fill='gold'/%3E%3Ccircle r='25' cx='49' cy='51' fill='yellowgreen'/%3E%3Ccircle r='17' cx='52' …
```
> fix(VImg): default ratio to 1:1 for SVG images

- packages/vuetify/src/components/VTextField/VTextField.sass
fixes #12743
fixes #12743
(https://github.com/vuetifyjs/vuetify/issues/12743)
Since this change was strictly a matter of specific sass rules, I tested using Chrome inspector to confirm style application and visually confirming that elements are aligned precisely in the proper context
<details>
```vue
<template>
<v-container>
<v-row>
<v-text-field
label="Amount"
value="10.00"
prefix="0x"
suffix="2x"
<v-select
label="Amount"
value="10.00"
suffix="2x"
prefix="0x"
:items="['10.00']"
></v-select>
<v-combobox
label="Amount"
value="10.00"
prefix="0x"
suffix="2x"
:items="['10.00']"
></v-combobox>
label="Amount"
value="10.00"
prefix="0x"
suffix="2x"
:items="['10.00']"
</v-row>
<v-row>
<v-text-field
dense
label="Amount"
value="10.00"
suffix="2x" …
```
> fix(VTextField): align dense mode text field prefix and content

- packages/vuetify/src/components/VBottomNavigation/__tests__/__snapshots__/VBottomNavigation.spec.ts.snap
- packages/vuetify/src/components/VBtn/VBtn.sass
- packages/vuetify/src/components/VBtn/VBtn.ts
- packages/vuetify/src/components/VBtn/__tests__/__snapshots__/VBtn.spec.ts.snap
add check to isElevated to ensure elevation prop is not null.
fixes #12845
playground
<details>
```vue
<template>
<div class="ma-12 pa-12">
<v-card>
<v-card-text>
<v-container>
<v-row
align="center"
justify="space-around"
class="my-10"
>
<v-btn disabled>Disabled</v-btn>
<v-btn color="red" :disabled="disabled"  outlined>outlined</v-btn>
<v-btn color="primary"  :disabled="disabled" icon>
<v-icon dark>
mdi-vuetify
</v-icon>
</v-btn>
<v-btn color="blue" :disabled="disabled" text>text</v-btn>
<v-btn color="green" :disabled="disabled" elevation="5">elevated</v-btn>
</v-row>
<v-row
align="center"
justify="space-around"
class="my-10"
>
<v-btn color="green"  :disabled="disabled"  plain>plain</v-btn>
<v-btn color="red" depressed :disabled="disabled">depressed</v-btn>
<v-btn color="blue" …
```
> fix(VBtn): disabled state background-color

- packages/vuetify/src/components/VCalendar/VCalendar.ts
- packages/vuetify/src/components/VCalendar/__tests__/VCalendarCategory.spec.ts
Tried to call .hasOwnProperty on an object that didn't enherit from Object prototype
Fixed a bug with VCalendar
There was an object we were calling .hasOwnProperty on which didn't have this method because it didn't inherit from 
Bug was throwing an error
Wrote new unit test to make sure
<details>
```vue
<template>
<v-container>
<v-calendar
type="category"
:categories="[{name: 'Nate', age: 20}]"
category-text="name"
category-show-all
:events="[{start: new Date(), category: 'Nate', name: 'Event'}]"
></v-calendar>
</v-container>
</template>
<script>
data: () => ({
//
}),
}
</script>
```
</details>
> fix(vcalendar): object inheritance

- packages/api-generator/src/locale/en/v-navigation-drawer.json
Added 'clipped-left' and 'clipped-right' prop reference for v-app-bar to get 'clipped' prop functionality to work as intended.
I could not figure out why the clipped prop wasn't working until I went into the api for the v-app-bar to see that an additional prop was required.
Visually
> docs(api): update v-navigation-drawer clipped description

- packages/vuetify/src/components/VGrid/VGrid.sass
fixes #12915
<details>
```vue
<template>
<v-container>
<v-row dense>
<v-col cols="8">
<v-card height="100%"></v-card>
</v-col>
<v-row dense>
<v-card>
<v-skeleton-loader type="article" />
</v-card>
</v-col>
<v-card>
<v-skeleton-loader type="article" />
</v-card>
</v-col>
</v-row>
</v-col>
</v-row>
<v-row dense>
<v-col
v-for="i in 6"
:key="i"
cols="6"
>
<v-card>
<v-skeleton-loader type="article" />
</v-card>
</v-col>
</v-row>
</v-container>
</template>
```
</details>
> fix(grid): don't halve gutters between v-rows

- packages/docs/src/layouts/default/settings/Theme.vue
Legend position was not aligned with the reverse prop that reverses the label position. So when the value of the reverse prop is true the legend should move right
fixes #10798
Done to Fix #10798
Visually via playground on Chrome, Edge, IE and Morzilla
<details>
```vue
<template>
<v-container>
<v-text-field label="Label" outlined reverse></v-text-field>
<v-text-field label="Label" outlined></v-text-field>
</v-container>
</template>
<script>
data: () => {
return {}
},
}
</script>
```
</details>
> fix(VTextField): legend position not aligned with reverse prop

- packages/vuetify/src/components/VApp/VApp.sass
- packages/vuetify/src/components/VThemeProvider/VThemeProvider.sass
- packages/vuetify/src/components/VThemeProvider/VThemeProvider.tsx
- packages/vuetify/src/composables/__tests__/__snapshots__/theme.spec.ts.snap
- packages/vuetify/src/composables/theme.ts
`.theme--x` classes should not apply background colors since they are applied on component level
manually
<details>
```vue
```
</details>
> fix(theme): do not apply background colors in theme class

- packages/docs/src/pages/en/getting-started/installation.md
- packages/vuetify/src/components/VDatePicker/VDatePicker.ts
- packages/vuetify/src/components/VDatePicker/__tests__/VDatePickerDateTable.spec.ts
- packages/vuetify/src/components/VDatePicker/__tests__/VDatePickerMonthTable.spec.ts
- packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.ts
- packages/vuetify/src/components/VDatePicker/util/__tests__/sanitizeDateString.spec.ts
- packages/vuetify/src/components/VDatePicker/util/index.ts
- packages/vuetify/src/components/VDatePicker/util/sanitizeDateString.ts
Honoring Min and Max date value for Scrolling of VDatePicker .
Added checks to check if a valid scroll is made (i.e tableDate is between min and max date both inclusive) before triggering update:table-date event
fixes #12856
Done to Fix #12856
To not perform scroll beyond min and max date
1. UTs have been added
2. Visually via Playground
<details>
```vue
<template>
<v-container>
<v-date-picker
:min="'2020-12-29T22:59:42+0000'"
:max="'2021-01-01T22:59:42+0000'"
range
scrollable
>
</v-date-picker>
<v-date-picker
type="month"
:min="'2020-12-29T22:59:42+0000'"
:max="'2020-12-31T22:59:42+0000'"
range
scrollable
>
</v-date-picker>
<v-date-picker
range
scrollable
>
</v-date-picker>
</v-container>
</template>
<script>
data: () => {
return {}
},
}
</script>
```
</details>
> fix(VDatePicker): scroll not honoring min and max tableDate

- packages/docs/src/examples/v-date-picker/misc-formatting-external-libraries.vue
…in date-fns library
See: https://github.com/date-fns/date-fns/blob/master/docs/upgradeGuide.md#string-arguments
Simple fix, this example is throwing an error on the live site. You can see (or not see, rather) the issue here:
https://vuetifyjs.com/en/components/date-pickers/#formatting-with-external-libraries
Fix documentation
visually
> docs(examples): fix v-date-picker date-fns in formatting-external-libraries 

- packages/vuetify/src/components/VData/VData.ts
Decrementing page by one assumes that the data set has shrank by less than 2x(itemsPerPage). 
My proposed change is a fix my bug report #12732
none
> fix(VDataTable): clamp current page when filtering

- packages/vuetify/src/components/VCalendar/mixins/__tests__/calendar-with-events.spec.ts
- packages/vuetify/src/components/VList/VListItem.ts
- packages/vuetify/src/components/VList/__tests__/VListItem.spec.ts
A `listitem` should not contain an `aria-selected` attribute, and a
`listbox` should only have `option`s as children.
See also:
* https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Listbox_role
* https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Listitem_role
fixes #13125
Unit tests have been run & updated as necessary.
~~As a note, some tests in `calendar-with-events.spec.ts` failed for me, so I updated them... but I'm unsure why they would've failed, as my change had nothing to do with time formatting.~~ CI failed (unsurprisingly), so I've reverted this change.
In addition, this change was manually tested using NVDA.
<details>
```vue
<template>
<v-container>
<v-list-item-group color="primary" aria-label="some label">
<v-subheader …
```
> fix(VListItem): use item role when in a group

- packages/docs/src/pages/en/features/sass-variables.md
Adding an alert to inform people that some variables that affect components can be found the the main theme variables.
Wanted to change the default `VChip` color and expected the variable in the `chip-api`.
> docs: add alert reg component variables in the global theme

- packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete.spec.ts
- packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete2.spec.ts
- packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete3.spec.ts
- packages/vuetify/src/components/VCombobox/__tests__/VCombobox.spec.ts
- packages/vuetify/src/components/VTextField/VTextField.ts
- packages/vuetify/src/components/VTextField/__tests__/VTextField.spec.ts
- packages/vuetify/src/util/__tests__/dom.spec.ts
- packages/vuetify/src/util/dom.ts
When an input element is inside a shadowDom, and is active (focused), the `document.activeElement` will not reference the input element but rather its shadowRoot. In order to properly detect what the `activeElement` is, we must use the proper root node for that element, as explained on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/activeElement).
This PR:
- Considers whether an element is attached to the DOM when computing `tryAutofocus`, and during the processing of `onFocus` event.
- Correctly detects the focused element event if the component is inside a Shadow DOM (solving part of #7622)
- Improves the quality of tests by enforcing `focus`/`activeElement` dependent tests to attach the mounted components to the DOM (read below for motivation)
- Uses a shim …
> fix(VTextField): detect activeElement from shadowRoot

- packages/api-generator/src/locale/en/applicationable.json
Added the missing 'find' inside the description for 'app'.
> docs(applicationable): fix a typo

- packages/vuetify/src/components/VGrid/VCol.ts
- packages/vuetify/src/components/VGrid/VContainer.tsx
- packages/vuetify/src/components/VGrid/VRow.ts
updates components to use the tag composable
Consistency with other components
unit | visually 
<details>
```vue
<template>
<v-app>
<v-container tag="ul">
<v-row tag="strong">
<v-col tag="li">Hello</v-col>
</v-row>
</v-container>
</v-app>
</template>
```
</details>
> refactor(grid): update components to use tag composable

- packages/vuetify/src/components/VImg/VImg.tsx
- packages/vuetify/src/components/VLayout/VLayout.tsx
- packages/vuetify/src/util/useRender.ts
`expose()` is broken: https://github.com/vuejs/vue-test-utils-next/issues/435, https://github.com/vuejs/rfcs/pull/210
`useRender` allows us to return the public state from setup and then infer types from that:
```js
<v-img ref="img">
setup () {
const img = ref<InstanceType<typeof VImg>>()
img.value.currentSrc // string
}
```
> refactor: create useRender helper instead of expose()

- packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts
- packages/vuetify/src/components/VCombobox/VCombobox.ts
fixes #12958
The issue is regression after #12415
Search should not be counted as dirty when empty string in VCombobox, but not in VAutocomplete
Visually on the markup from #12958 (https://codepen.io/djaler/pen/ZEpmazq) and from #12322 (https://codepen.io/MatthewAry/pen/BaKgBNq)
> fix(VAutocomplete): don't count search as dirty if it is empty

- packages/vuetify/src/components/VCheckbox/VCheckbox.ts
- packages/vuetify/src/components/VInput/VInput.ts
- packages/vuetify/src/components/VRadioGroup/VRadio.ts
- packages/vuetify/src/components/VSwitch/VSwitch.ts
- packages/vuetify/src/components/VTextField/VTextField.sass
- packages/vuetify/src/components/VTextField/VTextField.ts
- packages/vuetify/src/styles/components/_selection-controls.sass
Display hover effect of title attr even on label of v-text-field, which may have moved outside (above) the input when not outlined, by enabling pointer-events only when it's active (not otherwise).
Fix another v-switch bug of ripple effect's event blocking hover.
Fix displaying title at all in v-radio. (Also fixed ripple here.)
Move title attr to a parent object, making it trigger even on the threshold of input boundaries, increasing its accessibility scope to avoid blind zones. Remove the duplicate title in v-text-field, v-radio, v-switch, and v-checkbox after moving to parent element; specifically VInput, or in the v-radio's case via its own parent. Modified VInput's genInputSlot(): it's being called by components VAutocomplete, VRadioGroup, VSelect, and VTextField (maybe more).
This …
> fix(inputs): display title attribute on root element

- packages/docs/src/pages/en/features/icon-fonts.md
Adding an example of how to use SVGs with the workflow.
I struggled figuring out on how to exactly import and use an SVG-file for a custom icon.  
After several tries and asking in discord @MajesticPotatoe created this example:  
https://codesandbox.io/s/icon-example-gfelz?file=/src/main.js  
With this I finally understood it.
Maybe this should be added to https://vuetifyjs.com/en/features/icon-fonts/#component-icons instead.  
Could also explain that the SVG-files or direct imports only work with very simple path. For more complex SVGs the "Component Icon" should be used.
> docs(icons): add simple svg example import

- packages/vuetify/src/components/VRangeSlider/VRangeSlider.ts
- packages/vuetify/src/components/VSlider/VSlider.ts
fixes #13151 (regression from #12640)
`onSliderMouseDown` was being bound to two elements so the event listeners would be triggered twice
<details>
```vue
<template>
<v-app>
<v-container>
<v-slider @change="onChange"></v-slider>
<v-range-slider @change="onChange"></v-range-slider>
</v-container>
</v-app>
</template>
<script>
methods: {
onChange (e) {
console.log(e)
},
},
}
</script>
```
</details>
> fix(VSlider): only emit a single change event

- packages/vuetify/src/components/VSlideGroup/VSlideGroup.ts
fixes #13212 
fixes #13212 
visually
https://user-images.githubusercontent.com/557005/111451899-37303780-8712-11eb-9d19-1c8db9d27849.mov
https://user-images.githubusercontent.com/557005/111451928-3f887280-8712-11eb-95f4-4d94064a7c27.mov
Visit with chrome and set the Zoom to 110%, then resize the screen:
<details>
```vue
<template>
<v-container>
<v-tabs>
<v-tab>Item One</v-tab>
<v-tab>Item Two</v-tab>
<v-tab>Item Three</v-tab>
</v-tabs>
</v-container>
</template>
<script>
data: () => ({
//
}),
}
</script>
<style lang="scss">
.v-tabs {
padding-left: 14px;
.v-tabs-bar {
padding-left: 16px;
}
}
</style>
```
</details>
> fix(VSlideGroup): handle rounding issue if using browser zoom

- packages/vuetify/src/directives/click-outside/__tests__/click-outside.spec.ts
- packages/vuetify/src/directives/click-outside/index.ts
- packages/vuetify/src/globals.d.ts
- packages/vuetify/src/styles/elements/_global.sass
fixes #5886
fixes #9283
On dev in case it breaks safari again. 
<details>
```vue
<template>
<v-app>
app
temporary
>
<v-text-field
class="px-3"
value="https://google.com"
clearable
/>
<v-container>
<v-btn
icon
@click="drawer = !drawer"
>
</v-btn>
<div
id="a"
v-click-outside="onClickOutside"
></div>
<v-menu
v-model="linkMenu"
bottom
:close-on-content-click="false"
offset-y
>
<v-btn
icon
v-on="on"
>
<v-icon>mdi-link</v-icon>
</v-btn>
</template>
<v-form
class="white"
@submit.prevent="linkMenu=false"
>
<v-text-field
class="px-3"
value="https://google.com"
clearable
/>
</v-form>
</v-menu>
</v-container>
</v-app>
</template>
<script>
data: () => ({
drawer: false, …
```
> fix(click-outside): don't trigger if mousedown inside target

- packages/docs/src/pages/en/components/bottom-navigation.md
The `active` property of the `v-bottom-navigation` component and the event 'update:active' are not implemented but they are desccribed in documentation of the `2.3.*` and `2.4.*` branches.
I tried to achieve that it worked, but it seems that it does not work at all. Perhaps this piece of text from the old documentation.
And i didn't find any `active` property or the `update:active` event in API docs of 2.3.* &amp; 2.4.* versions for the `v-bottom-navigation` component.
It's the misleading text
https://codepen.io/Perlover/pen/zYoVbMM?editors=101
> docs(bottom-navigation): update usage description

- packages/vuetify/src/directives/ripple/__tests__/ripple.spec.ts
- packages/vuetify/src/directives/ripple/index.ts
fixes #13189
In this issue, active element is changed in the keydown event, so the button`s  keyup event is not triggered. As a result, ripple is not hidden.
The keyup event can only be triggered at the focused element. So we can hide ripple when target loses focus.
fixes #13189
add unit test case
<details>
```vue
<template>
<v-container>
<v-btn v-ripple>keep pressing</v-btn>
<v-dialog
width="500"
>
<v-btn
color="red lighten-2"
dark
v-bind="attrs"
v-on="on"
>
Click Me
</v-btn>
</template>
<v-card>
<v-card-title class="headline grey lighten-2">
Lorem
<v-card-text>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna …
```
> fix(VRipple): hide ripple on blur

- packages/vuetify/src/components/VBadge/_variables.scss
Variable `$badge-dot-border-radius` was missing a `!default`
Changing the border radius on badge dots was impossible without a CSS selector and `!important`
> fix(VBadge): add missing !default on border radius

- packages/vuetify/src/components/VSelect/VSelect.sass
Fix vuetifyjs/vuetify#13149
vuetifyjs/vuetify#13149
visually
```vue
<v-app>
<v-container>
<v-row>
<v-col>
<v-text-field
label="v-text-field"
filled
</v-col>  
<v-col>
<v-select
label="v-select"
filled
></v-select>
</v-col>  
<v-col>
label="v-autocomplete"
filled
</v-col>  
</v-row>
</v-container>
</v-app>
```
> fix(VSelect): make CSS order-independent

- packages/vuetify/src/components/VCombobox/VCombobox.ts
- packages/vuetify/src/components/VCombobox/__tests__/VCombobox-multiple.spec.ts
Don't add empty values in Combobox.
Fixes #13274
Unit testing and Visually
<details>
```vue
<template>
<div id="app">
<v-combobox
:items="items"
hide-selected
hint="Maximum of 5 tags"
label="Add some tags"
multiple
small-chips
>
</v-combobox>
</v-container>
</v-app>
</div>
</template>
<script>
data: () => ({
items: ['Gaming', 'Programming', 'Vue', 'Vuetify'],
model: ['Vuetify'],
search: null,
})
}
</script>
```
</details>
> fix(VCombobox): don't add empty values

- packages/vuetify/src/components/VExpansionPanel/VExpansionPanelHeader.ts
Added aria-expanded to the v-expansion-panel-header button so that it can be picked up by a screen reader.
Fixes #13354
Previously screen readers were not telling users if an expansion panel was expanded or collapsed because aria-expanded was not on the correct element.
> fix(VExpansionPanelHeader): add missing aria-expanded attribute

- packages/vuetify/src/components/VAutocomplete/VAutocomplete.ts
- packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete3.spec.ts
Fixed infinite loop with update:search-input event for VAutocomplete
FIxes #9489
Whenever the items list is updated for VAutocomplete, the setSearch() method is called. This sets the value of search and emits the  update:search-input event even if there is no change in the search value. This will cause an infinite loop with the test case mentioned in the issue. The fix is to only emit the event if the new search value is different from the previous one.
visually
<details>
```vue
<template>
<v-app>
<v-container>
<v-autocomplete 
:items="items" 
@update:search-input="search">
</v-container>
</v-app>
</template>
<script>
data() {
return {
selected: '',
items: []
}
},
methods: {
search(term) {
// Open …
```
> fix(VAutocomplete): compare current lazyValue before emiting update

- packages/api-generator/src/locale/en/v-slide-group.json
- packages/api-generator/src/maps/v-slide-group.js
https://vuetifyjs.com/en/api/v-slide-group/#events 
`click:location` only support receive two param: ‘prev' | 'next' form the source code.  
`src/components/VSlideGroup/VSlideGroup.ts`:
```
onAffixClick (location: 'prev' | 'next') {
this.$emit(`click:${location}`)
this.scrollTo(location)
},
```
The current version of the documentation does not allow the user to use it correctly.
Visual
<details>
```vue
```
</details>
> docs(v-slide-group): update the click receive params description 

- packages/vuetify/src/components/VExpansionPanel/VExpansionPanelHeader.ts
updated aria-expanded on the v-expansion-panel-header button to use isActive instead of hasMousedown since that seemed much more appropriate. 
Fixes #13354
I realized when reviewing the PR I put in yesterday that I should have used isActive instead of hasMousedown. I wanted to fix my mistake.
> fix(VExpansionPanels): change aria-expanded to use isActive

- packages/vuetify/src/components/VCombobox/VCombobox.ts
- packages/vuetify/src/components/VCombobox/__tests__/VCombobox-multiple.spec.ts
Multiple Combobox adds empty chips when double click on chip and then re-select an item. Fixes #10827 
This issue was happening because of incorrect value of editingIndex in combobox. When we double click a chip, its text is displayed as editable text in the combobox and this sets the editingIndex to the index of the chip double clicked. This is done in VCombobox.ts where dbl click event for chip is handled
```
dblclick: () => {
this.editingIndex = index
this.internalSearch = this.getText(item)
this.selectedIndex = -1
}
``` 
Currently, after clicking clear button we don't reset editingIndex. And, if we try to add any value after clear, it will cause updateEditing() function to get called instead of adding that item. updateEditing() adds the null value to the combobox.
```
selectItem …
```
> fix(VCombobox): reset editingIndex after clear

- packages/vuetify/package.json
- packages/vuetify/src/composables/__tests__/resizeObserver.spec.ts
- packages/vuetify/src/composables/resizeObserver.ts
- packages/vuetify/test/index.ts
- yarn.lock
adds ResizeObserver composable. exposes a ref that can be attached to element/component you want to observe.
usage
```ts
const { resizeRef } = useResizeObserver(entries => {
// do something with observed entries
})
..
ref={resizeRef}
```
if there is only need to get size of actual element that ref is attached to, usage can be
```ts
const { resizeRef, contentRect, contentBoxSize, borderBoxSize } = useResizeObserver()
...
ref={resizeRef}
```
playground and unit tests
<details>
```vue
<template>
<div v-if="val" ref="resizeRef">{{ width }}</div>
<v-btn @click="val = !val">toggle</v-btn>
</template>
<script>
import { useResizeObserver } from '../src/composables/resizeObserver'
setup () {
const val = ref(true)
const width = ref(0) …
```
> feat: add resize observer composable

- packages/vuetify/src/components/VSelect/VSelect.ts
- packages/vuetify/src/components/VSelect/__tests__/VSelect2.spec.ts
- packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect2.spec.ts.snap
fixes #13658
<details>
```vue
<template>
<v-container>
<v-select
:items="options"
></v-select>
</v-container>
</template>
<script>
data: () => ({
selected: { foo: null },
options: [
{ text: 'A', value: { foo: null } },
{ text: 'B', value: { foo: '' } },
],
}),
watch: {
selected (oldValue, newValue) {
console.log(newValue.foo)
console.log(oldValue.foo)
},
},
}
</script>
```
</details>
> fix(VSelect): compare object values before emitting change

- packages/vuetify/src/components/VTimePicker/VTimePickerClock.ts
In some rare cases the error `Cannot read property 'getBoundingClientRect' of undefined` is thrown, I believe it's due to the fact that the event may fire only after the element has been destroyed in some slow devices, for now it only has happened on chrome desktop
Simply gracefully exit the function without throwing in this very edge case
Some of my users (less than 0.1%) experience this issue in production
This is an edge case that happens randomly with very low incidence and probably impossible to reproduce deterministically, so it hasn't
> fix(VTimePickerClock): race condition between event and $refs

- packages/vuetify/types/lib.d.ts
fixes #13578
added missing VThemeProvider export in lib.d.ts
missing VThemeProvider export in lib.d.ts
> fix(typescript): added missing VThemeProvider export in lib.d.ts

- packages/vuetify/src/directives/intersect/__tests__/intersect.spec.ts
- packages/vuetify/src/directives/intersect/index.ts
The handler can sometimes be called even if no entries are intersecting, if the `once` modifier is used we don't want to unbind until the element is actually visible in the viewport.
> fix(intersect): don't unbind until the element is intersecting

- packages/vuetify/src/components/VApp/VApp.tsx
- packages/vuetify/src/components/VApp/__tests__/__snapshots__/VApp.spec.ts.snap
- packages/vuetify/src/components/VAppBar/VAppBar.sass
- packages/vuetify/src/components/VDialog/VDialog.sass
- packages/vuetify/src/components/VLayout/VLayout.sass
- packages/vuetify/src/components/VLayout/VLayout.tsx
- packages/vuetify/src/components/VOverlay/VOverlay.tsx
- packages/vuetify/src/composables/layout.ts
- packages/vuetify/src/styles/elements/_global.sass
<details>
```vue
<template>
<v-app>
<v-app-bar>
<template #prepend>
<v-btn icon="mdi-menu" />
</template>
<v-app-bar-title>
Title
</v-app-bar-title>
<v-btn icon="mdi-download" />
<v-btn icon="mdi-printer" />
<v-btn icon="mdi-heart" />
</template>
</v-app-bar>
<v-main>
<v-container class="pa-0 pa-md-16" style="height: 200vh">
<v-layout style="height: 600px">
<v-app-bar absolute>
<v-app-bar-title>
Title
</v-app-bar-title>
<v-btn icon="mdi-vuetify"></v-btn>
</template>
</v-app-bar>
<v-main>
<v-container style="height: 1200px">
<v-dialog>
<v-btn v-bind="props">Dialog</v-btn>
</template>
<v-sheet width="300" height="300">
Dialog
</v-sheet>
</v-dialog>
<v-dialog attach absolute>
<v-btn …
```
> fix: apply offset padding to appbars when an overlay is open

- packages/api-generator/src/locale/en/v-theme-provider.json
I specified on the documentation that the `<v-theme-provider>` slot must have only one root element to avoid confusion. Not sure the wording is perfect but at least it mentions the limitation I encountered.
I recently noted that using `<v-theme-provider>` with more than one root element in the slot doesn't work. All elements expect the first one are omitted.
This was not documented at all. And I didn't expected it to happen since Vue `<slot>` doesn't have this limitation. Only components template have it (just to mention it wasn't intuitive to discover this by myself)
> docs(VThemeProvider): slot must include one root element

- packages/vuetify/src/components/VMenu/VMenu.ts
- packages/vuetify/src/components/VTooltip/VTooltip.ts
- packages/vuetify/src/mixins/menuable/__tests__/menuable.spec.ts
- packages/vuetify/src/mixins/menuable/index.ts
Fixes #7703
Visually and unit
Jest doesn't really simulate dom positioning so the unit tests are limited and sadly there doesn't seem to be any base for e2e tests
<details>
```vue
<template>
<div class="wrapper">
<v-app style="height: 4000px; margin: 20px 40px;">
<v-app-bar
absolute
color="#6A76AB"
shrink-on-scroll
prominent
>
<v-app-bar-nav-icon></v-app-bar-nav-icon>
<v-app-bar-title>Title</v-app-bar-title>
<v-btn icon>
<v-icon>mdi-magnify</v-icon>
</v-btn>
<v-btn icon>
<v-icon>mdi-heart</v-icon>
</v-btn>
<v-btn icon>
<v-icon>mdi-dots-vertical</v-icon>
</v-btn>
<template v-slot:extension>
<v-menu attach>
<template v-slot:activator="{ on, attrs }">
<v-btn
dark
v-bind="attrs"
v-on="on"
>
Dropdown
</v-btn>
</template>
<v-list>
<v-list-item
v-for="(item, …
```
> fix(Menuable): correctly calculate position in embedded v-app

- packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.date.spec.ts
- packages/vuetify/src/components/VDatePicker/__tests__/VDatePicker.month.spec.ts
- packages/vuetify/src/components/VDatePicker/__tests__/VDatePickerDateTable.spec.ts
- packages/vuetify/src/components/VDatePicker/__tests__/VDatePickerMonthTable.spec.ts
- packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.ts
a bug
scroll using touchpad (2 fingers), it's possible to scroll beyond the max date
visually, updated unit tests
<details>
```vue
<template>
<v-container>
<v-date-picker
v-model="date"
class="mt-4"
min="2020-06-15"
max="2021-05-20"
scrollable
</v-container>
</template>
<script>
data: () => {
return {}
},
}
</script>
```
</details>
> fix(VDatePicker): prevent scroll beyond max date with touchpad

- packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.ts
- packages/vuetify/src/components/VCalendar/util/__tests__/events.spec.ts
- packages/vuetify/src/components/VCalendar/util/events.ts
fixes: #11767 & #12223
These changes allow events that end at midnight to be displayed 
As discussed in #11767 events that end in midnight are not displayed, this also affected #12223, for events that both start and end at midnight.
unit and visually
<details>
```vue
<template>
<v-container>
<v-calendar type="week" :events="events" start="2021-05-20">
</v-calendar>
</v-container>
</template>
<script>
data: () => ({
events: [
{
name: 'normal',
start: '2021-05-17 12:00',
end: '2021-05-17 13:00',
},
{
name: 'midnight end',
start: '2021-05-18 12:00',
end: '2021-05-19 00:00',
},
{
name: 'just at 00:00',
start: '2021-05-20 00:00',
end: '2021-05-20 00:00',
},
],
}),
}
</script>
```
</details>
> fix(VCalendar): display events ending at midnight

- packages/vuetify/src/components/VCalendar/VCalendar.ts
- packages/vuetify/src/components/VCalendar/VCalendarCategory.ts
- packages/vuetify/src/components/VCalendar/__tests__/VCalendarCategory.spec.ts
- packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.ts
- packages/vuetify/src/components/VCalendar/util/parser.ts
Support for array of strings for categories was removed during last release. 
This adds that functionality back in
resolves #12922
https://github.com/vuetifyjs/vuetify/issues/12922
added unit tests
<details>
```vue
<template>
<v-container>
<v-calendar
type="category"
:categories="['Nate', 'Bob', 'Jeff']"
:events="[{start: new Date(), category: 'Nate', name: 'Cool story'}]"
categoryText="name"
category-show-all
/>
</v-container>
</template>
```
</details>
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [x ] My code follows …
> fix(VCalendar): add support for string[] of categories

- packages/vuetify/types/lib.d.ts
Vuetify has separated `declare module` for `vuetify/lib/directives`. This add `vuetify/lib/components` too.
Now we can do something like `import * as VuetifyComponents from 'vuetify/lib/components';` without typescript errors.
> fix(types): add declaration for vuetify/lib/components

- packages/api-generator/src/locale/en/v-input.json
- packages/vuetify/src/components/VInput/VInput.sass
- packages/vuetify/src/components/VInput/VInput.ts
Add prop to hide spin buttons on number type input
feat #6157
Resolves #6157
Adds the `hide-spin-buttons` to `VInput`. This hides the spin buttons added by the browser to `number` type inputs.
Hiding the spin buttons for VInput is a commonly searched/requested feature. The current solution is a copy-paste css snippet (see #6157).
Visually tested on Chrome, Firefox, and Safari.
<details>
```vue
<template>
<v-container>
<v-text-field
type="number"
hide-spin-buttons
/>
</v-container>
</template>
<script>
data: () => ({
//
}),
}
</script>
```
</details>
> feat(VInput): add hide-spin-buttons prop

- packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.ts
`events` in https://github.com/vuetifyjs/vuetify/blob/d9668ce058c4cccad5456d47194b42857e50226a/packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.ts#L168 were not sorted by the position (bounding rect), so if the first event was outside of the calendar cell then `hide` was set to `true` and all next events were treated as hidden. This PR sorts event by the `bottom` position, not sure if there's a way to get events properly sorted in `getEventsMap`
fixes #13720
playground
https://gist.githubusercontent.com/jacekkarczmarczyk/cd30d957a7d2a629e2bdd738d2fc6d61/raw/eaaf8d89c770c66fc27015bbeb382a27e5ba5ef1/vuetify-13720-playground.vue
> fix(VCalendar): missing events under certain circumstances

- packages/vuetify/src/components/VCard/VCard.sass
A sass rule makes a `VAvatar` that is the first child of a `VCard` look weird :
My change makes it back to normal :
It doesn't change modifiers, like `tile` :
I tested it visually. I am not comfortable with unit testing with a Vue framework but am willing to implement unit tests if they are required here, with some direction pointing
<details>
```vue
<template>
<v-container>
<v-row>
<v-card>
<v-avatar size="40" color="primary">
<span class="white--text text-h5">A</span>
</v-avatar>
</v-card>
</v-row>
<v-row>
<v-card>
<v-avatar tile size="40" color="primary">
<span class="white--text text-h5">B</span>
</v-avatar>
</v-card>
</v-row>
<v-row>
<v-card>
<v-avatar rounded size="40" color="primary">
<span class="white--text text-h5">C</span>
</v-avatar>
</v-card>
</v-row>
</v-container> …
```
> fix(VCard): set correct radius for direct VAvatar children

- packages/docs/src/pages/en/components/data-tables.md
A small documentation addition added to tell users that a unique row item key is required for v-data-table's expandable rows feature to work. Tells the user the default of `id` and tells the user how to change it with `item-key` prop. This documentation would have prevented false bug #8807.
Added two short sentences because not knowing about the item-key prop tripped me up and I saw I wasn't the first: https://github.com/vuetifyjs/vuetify/issues/8807
- [ x My code follows the code style of this project.
> docs(VDataTable): add item-key prop info to expandable section

- packages/docs/src/pages/en/components/overflow-btns.md
- packages/docs/src/pages/en/components/text-fields.md
Remove conflicting message about v-text-field and v-overflow-btn using "filled" prop can't use append and prepend icons
fixes #13817
Visually / Docs
<details>
</details>
> docs(text-fields): remove conflict msg about cant use append/prepend icon

- package.json
- packages/vuetify/build/webpack.dev.config.js
- packages/vuetify/dev/index.js
- packages/vuetify/package.json
- packages/vuetify/src/components/VBtn/VBtn.sass
- packages/vuetify/src/components/VBtn/VBtn.tsx
- packages/vuetify/src/components/VCard/VCard.sass
- packages/vuetify/src/components/VCard/VCard.tsx
- packages/vuetify/src/components/VList/VListItem.sass
- packages/vuetify/src/components/VList/VListItem.tsx
- packages/vuetify/src/components/VOverlay/VOverlay.tsx
- packages/vuetify/src/composables/router.tsx
- packages/vuetify/src/styles/tools/_states.sass
- packages/vuetify/tsconfig.json
- yarn.lock
Resolves #1793
Depends on https://github.com/vuejs/vue-router-next/pull/1002
<details>
```vue
<template>
<v-app>
<v-container>
<v-btn to="/page1">button</v-btn>
<router-link to="/page1">Page 1</router-link>
<router-link to="/page2">Page 2</router-link>
</v-container>
</v-app>
</template>
```
</details>
Reference: https://github.com/vuejs/vue-router-next/blob/master/e2e/modal/index.ts
> feat: add router integration

- packages/vuetify/src/components/VSelect/VSelect.ts
fixes #12567
<details>
```vue
<template>
<v-app>
<v-container>
<v-combobox :items="items"></v-combobox>
<v-autocomplete :items="items"></v-autocomplete>
<v-select :items="items"></v-select>
</v-container>
</v-app>
</template>
<script>
data: () => ({
items: ['a', 'b', 'c', 'd', 'e', 'f'],
}),
}
</script>
```
</details>
> fix(VCombobox): re-compute menu items before setting index

- packages/vuetify/src/components/VAlert/VAlert.tsx
- packages/vuetify/src/components/VList/VListItem.tsx
- packages/vuetify/src/components/VList/__tests__/VListItem.spec.cy.tsx
- packages/vuetify/src/composables/variant.tsx
fixes #13893 with computed instead of reactive
keeps code base consistent, and adds test
cy test and playground
<details>
```vue
<template>
<v-app>
<v-list
lines="three"
max-width="500"
theme="dark"
>
<v-list-item
v-for="n in 3"
:key="n"
title="Three line item"
:active="n === model"
subtitle="lorem"
active-color="success"
text="text"
@click="model = n"
/>
</v-list>
</v-app>
</template>
<script>
data: () => ({
model: 1,
}),
}
</script>
```
</details>
> fix(VListItem): properly display active-color when active

- packages/docs/src/pages/en/components/text-fields.md
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
Fix a typo in [Text fields docs (v2.5.6)](https://vuetifyjs.com/en/components/text-fields/#password-input).
> docs(text-fields): fix typo

- packages/docs/src/pages/en/components/navigation-drawers.md
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
Fix a typo in [Navigation drawers docs (v2.5.6)](https://vuetifyjs.com/en/components/navigation-drawers/#right).
> docs(navigation-drawers): fix typo
