vuetifyjs/vuetify

src/components/navbar/Navbar.vue
src/components/navbar/NavbarGroup.vue
src/components/navbar/NavbarItem.vue
src/components/navbar/NavbarItems.vue
src/components/navbar/index.js
src/components/parallax/Parallax.vue
src/directives/ripple.js
src/mixins/translatable.js
src/stylus/components/_navbar.styl
src/stylus/trumps/_app.styl

https://github.com/vuetifyjs/vuetify/issues/54

Parallax bug fix for #54

---

src/components/sidebar/Sidebar.js

Added missing prop for right option.

Fix Sidebar Right option

---

src/components/toolbar/ToolbarItem.js

Fix wrong toolbar item active class name

---

src/mixins/input.js

This should enable users to write more generic rule functions which can be re-used in other parts of the app.

Pass value to rule callbacks

---

src/stylus/components/_chips.styl

Avatar needs to change size with v-chip when using small attribute.

Change size of avatar when using v-chip small

---

src/components/tables/DataTable.js
src/components/tables/mixins/body.js
src/components/tables/mixins/foot.js

fix for #328

---

src/components/snackbars/Snackbar.js
src/stylus/components/_snackbars.styl

Updated snackbar with:
- added vertical mode for mobile
- fixed transition bug when using multi-line option
- both multi-line and vertical are mobile use only
- (and converted _snackbars.styl to use spaces instead of tabs)
http://i.imgur.com/IlPgdi3.gifv
There's a PR in docs with updated snackbar page where you can try out all options

Snackbar update

---

src/components/alerts/Alert.js
src/components/buttons/ButtonToggle.vue
src/components/icons/Icon.js
src/components/pagination/Pagination.vue
src/stylus/components/_alerts.styl
src/stylus/components/_bottom-nav.styl
src/stylus/components/_buttons.styl
src/stylus/components/_chips.styl
src/stylus/components/_icons.styl
src/stylus/components/_tabs.styl
src/stylus/tools/_icons.styl
src/stylus/tools/_mixins.styl

Icons enhancement

---

src/components/sidebar/Sidebar.js
src/stylus/components/_sidebar.styl
src/stylus/generic/_grid.styl
src/stylus/settings/_variables.styl
src/stylus/trumps/_app.styl

Grid enhancement

---

src/components/app/App.js
src/stylus/components/_buttons.styl
src/stylus/components/_cards.styl
src/stylus/components/_dialogs.styl
src/stylus/components/_lists.styl
src/stylus/components/_overlay.styl
src/stylus/components/_pickers.styl
src/stylus/components/_tables.styl
src/stylus/elements/_global.styl
src/stylus/generic/_grid.styl
src/stylus/settings/_variables.styl
src/stylus/trumps/_app.styl

Enhancement themes

---

src/components/forms/TextField.js
src/mixins/input.js
src/stylus/components/_text-fields.styl

adding placeholder prop to textfield

---

src/components/pickers/DatePicker.js
src/components/pickers/mixins/date-table.js

Added allowed-dates functionality to date picker (vuetifyjs/vuetify#419). There's a PR in docs with an example

Added allowed-dates functionality

---

src/components/tables/DataTable.js
src/components/tables/mixins/body.js
src/components/tables/mixins/foot.js
src/components/tables/mixins/progress.js
src/stylus/components/_datatables.styl

Update to support server side pagination and sorting (vuetifyjs/vuetify#345)

Data table update

---

src/components/tables/DataTable.js
src/components/tables/mixins/head.js
src/stylus/components/_datatables.styl

Added default sorting to data table

---

src/components/tables/DataTable.js

#482 for dev branch
Issue #480 
My code sample:
```
<v-data-table
v-bind:headers="headers"
:search="filterKey"
v-model="data"
rows-per-page="50"
:customFilter="customFilter"
:customSort="customSort"
>
<template slot="items" scope="props">
<td class="text-xs-right" v-for="entry in headers" :key="entry.value" :class="entry.style" v-html="getValue(entry.value, props.item)"></td>
</template>
```
```
methods: 
{
customFilter(items, filterKey)
{
if (filterKey)
{
let search = new RegExp(filterKey.replace(/ [\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&"), 'i');
return items.filter(row =>
this.headers.some(column =>
{
return search.test(this.getValue(column.value, row));
})
);
}
return items;
},
customSort(items, index, desc)
{
let modifier = (desc ? 1 : -1); …
```

[dev] Allow override default search and filter functions

---

README.md

Hi,
I am new to github and pull request so I hope I am doing it right
Cheers

Fixed Broken link to gitter

---

src/components/pickers/DatePicker.js
src/components/pickers/mixins/date-table.js

Added firstDayOfWeek prop

---

src/components/progress/ProgressLinear.vue
src/stylus/components/_progress-linear.styl

Fixes progress linear performance issue with data table

Progress linear fix

---

src/components/tables/mixins/body.js
src/components/tables/mixins/head.js

Related to https://github.com/vuetifyjs/vuetify/issues/731

Datatable slots

---

src/directives/badge.js
src/stylus/components/_badges.styl

I offer the opportunity to place a badge at the bottom

---

src/components/app/App.js

Sometimes I got this error:
Cannot read property 'staticClass' of undefined
I changed the "if" statement so it cannot throw this error.

Prevent possible error

---

src/components/sliders/Slider.js
src/stylus/components/_sliders.styl
src/stylus/tools/_sliders.styl
src/util/helpers.js

Added snap prop, fixed a few bugs. Related to https://github.com/vuetifyjs/vuetify/issues/219
See examples at https://github.com/vuetifyjs/docs/pull/87

Slider enhancements

---

src/components/pickers/DatePicker.js
src/components/pickers/mixins/date-header.js
src/components/pickers/mixins/date-table.js
src/components/pickers/mixins/date-title.js

Solves https://github.com/vuetifyjs/vuetify/issues/757
See example in https://github.com/vuetifyjs/docs/pull/86

Added props to allow internationalization of datepicker

---

src/directives/badge.js

Related to https://github.com/vuetifyjs/vuetify/issues/796
Example at https://github.com/vuetifyjs/docs/pull/85

Added functionality to hide/show badges

---

src/components/tabs/Tabs.js

Now tabs works fine, in case of tab count get changed but active index doesn't

Fix tabs issue #762

---

src/components/forms/Checkbox.js
src/components/forms/Radio.js
src/components/forms/Switch.js
src/mixins/checkbox.js
src/mixins/colorable.js
src/stylus/components/_switch.styl

Added a "colorable" mixin that adds a "color" prop and method for joining color classes into the classes() object.
Modified checkbox mixin to include colorable mixin.
Modified Radio to include colorable mixin.
Modified Checkbox, Radio, and Switch to call the addColorClassChecks in the appropriate classes() method.

Remove contextualable from Checkbox, Radio, and Switch

---

src/components/tables/DataTable.js

to avoid unnecessary event emit

Stopped emitting totalItems in pagination prop sync 

---

src/components/tables/mixins/head.js

Fixed bug when explicitly setting select-all prop to true

---

BACKERS.md

Can I put a link to my website? I trying to build a small community around it for Spanish speakers providing good quality content for topics like Vue.js, good coding practices and programming in general.

Backers minor change

---

src/components/selects/Select.js

[Here](https://jsfiddle.net/fhLwq3m9/) is example how it works now (with bug)
On the picture - how it should works

Fix editable select

---

src/components/tables/DataTable.js
src/components/tables/mixins/foot.js

Fix for #986

---

src/components/steppers/Stepper.js
src/stylus/components/_steppers.styl
src/stylus/settings/_theme.styl
src/stylus/tools/_application.styl
src/stylus/tools/_steppers.styl

Added theme support to stepper

Fix for #937

---

.eslintrc.js
src/components/menus/mixins/generators.js
src/components/menus/mixins/keyable.js
src/components/menus/mixins/position.js
src/components/menus/mixins/utils.js
src/components/pickers/VTimePicker.js
src/components/pickers/mixins/date-header.js
src/components/pickers/mixins/date-table.js
src/components/pickers/mixins/date-title.js
src/components/pickers/mixins/time-body.js
src/components/selection-controls/VRadio.js
src/components/selects/VSelect.js
src/components/sliders/VSlider.js
src/components/snackbars/VSnackbar.js
src/components/tables/mixins/body.js
src/components/tables/mixins/foot.js
src/components/tables/mixins/head.js
src/components/tables/mixins/progress.js
src/components/tabs/VTabs.js
src/components/tabs/VTabsBar.js
src/components/text-fields/VTextField.js
src/mixins/overlayable.js
src/mixins/resizable.js
src/mixins/selectable.js
src/mixins/translatable.js

Fixed eslint max-len errors

---

src/components/grid/index.js

Before fixed add id attribute with value of undefined

Remove attr id when this is undefined

---

src/components/lists/VListTile.js

Fix ripple import

---

src/components/tables/VDataTable.js
src/components/tables/mixins/foot.js
src/stylus/components/_data-table.styl
src/stylus/components/_tables.styl
src/stylus/settings/_theme.styl
src/stylus/tools/_application.styl
src/stylus/tools/_data-tables.styl
src/stylus/tools/_tables.styl

Added theme support for data table

---

src/components/tables/mixins/foot.js

Fixed vuex mutation error in data table

---

src/components/text-fields/VTextField.js

Fixed autofocus typo

---

src/mixins/input.js
src/mixins/selectable.js

This allow us to customize labels by using slot:
```
<v-checkbox>
<span slot="label">this is <b>important</b> field</span>
</v-checkbox>
```

allow customize label by slot

---

src/components/snackbars/VSnackbar.spec.js

Tests for one timeout function being created and called with the correct time. It then makes sure isActive and the emitted value are false when the timeout finishes.

Added timeout test

---

src/stylus/generic/_grid.styl

I was hesitating between `<v-layout align-content-start />` and `<v-layout content-start />`, chosen the first one which is longer but more descriptive

align-content support in v-layout

---

src/stylus/components/_navigation-drawer.styl

Fix v-navigation-drawer right border

---

src/components/VTextField/VTextField.vue

Playground.vue
```
<template>
<v-text-field label="date" type="date" />
<v-text-field label="time" type="time" />
<v-text-field label="datetime-local" type="datetime-local" />
<v-text-field label="week" type="week" />
<v-text-field label="month" type="month" />
</v-app>
</template>
```

additional input types to fix #1309

---

src/components/VRadioGroup/VRadio.spec.js
src/components/VRadioGroup/VRadio.vue
src/components/VRadioGroup/index.js

Testing library isn't able to do what's needed to cleanly test this.  Once that's the case, these checks can be improved

Add semantic check for new VRadioGroup requirement

---

src/components/VTextField/VTextField.vue

Updated PR https://github.com/vuetifyjs/vuetify/pull/1260

label covers invalid value of number text field

---

src/components/VCarousel/VCarousel.spec.js
src/components/VCarousel/VCarousel.vue
src/components/VCarousel/__snapshots__/VCarousel.spec.js.snap

This PR adds model to carousel component and fixes #1358 
Playground:
```
<template>
<v-app>
<main>
<v-container>
<div class="headline">With v-model</div>
<v-carousel v-model="model" style="height: 300px">
<v-carousel-item v-for="(item,i) in items" v-bind:src="item.src" :key="i"></v-carousel-item>
</v-carousel>
<div class="headline">Without v-model</div>
<v-carousel style="height: 300px">
<v-carousel-item v-for="(item,i) in items" v-bind:src="item.src" :key="i"></v-carousel-item>
</v-carousel>
</v-container>
</main>
</v-app>
</template>
<script>
data () {
return {
model: 0,
items: [1,2,3,4].map(i => ({
src: `http://lorempixel.com/400/200/?${i}`
}))
}
},
watch: {
model () {
console.log(`Current element: ${this.model}`)
}
}
}
</script>
```

Enhancement/carousel v-model

---

src/stylus/components/_toolbar.styl

toolbar mobile portrait height

---

src/util/breakpoint.spec.js

I wrote some tests to ensure that the breakpoint mixin behaves as expected (I took it as a tiny a avoriaz exercise). Nice testsuite and dev setup (git pre-commit hooks) you have already, makes it a joy to work with :hugs:

Add scenario tests for the VApp breakpoint mixin

---

src/components/VSelect/VSelect.spec.js
src/components/VSelect/VSelect.vue
src/components/VSelect/__snapshots__/VSelect.spec.js.snap
src/components/VSelect/mixins/generators.js

Respect tabindex prop in VSelect

Fixes #1590

---

src/components/VExpansionPanel/VExpansionPanelContent.js
src/components/VExpansionPanel/VExpansionPanelContent.spec.js

Playground.vue
```vue
<template>
<v-expansion-panel>
<v-expansion-panel-content v-for="(item,i) in 5" :key="i" :lazy="i%2 === 0">
<div slot="header">Item</div>
<v-card>
<v-card-text class="grey lighten-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</v-card-text>
</v-card>
</v-expansion-panel-content>
</v-app>
</template>
<script>
}
</script>
```

Lazy prop on VExpansionPanelContent

---

src/components/VDatePicker/VDatePicker.spec.js
src/components/VDatePicker/VDatePicker.vue
src/components/VDatePicker/__snapshots__/VDatePicker.spec.js.snap
src/components/VDatePicker/mixins/date-header.js
src/components/VDatePicker/mixins/date-title.js

This fix is ready for 0.15.3, it's also integrated with month picker
```vue
<template>
<div id="app">
<v-layout row>
<v-date-picker :first-day-of-week="0" locale="fa-AF" :header-date-format="headerDateFormat" :title-date-format="titleDateFormat" v-model="picker"></v-date-picker>
<v-date-picker :first-day-of-week="0" locale="fa-IR" v-model="picker"></v-date-picker>
</v-layout>
</v-app>
</div>
</template>
<script>
data: () => ({
picker: null,
headerDateFormat: date => {
return date.toLocaleString('fa-AF', { year: 'numeric' }) + ' ' + ['حمل', 'ثور', 'جوزا', 'سرطان',' اسد', 'سنبله' ,'میزان' ,'عقرب' ,'قوس', 'جدی' ,'دلو', 'حوت'][11-date.getMonth()]
},
titleDateFormat: date => {
return ['حمل', 'ثور', 'جوزا', 'سرطان',' اسد', 'سنبله' ,'میزان' ,'عقرب' ,'قوس', …
```

Allows passing a function for datepicker title/header formatting (fixes #1651)

---

src/components/VRadioGroup/VRadio.vue

Add input-group--disabled to VRadio

---

src/components/VTextField/VTextField.vue

Was broken by 2b797b03b9c0c0bfa060f4bf5ab7932ee99d1fda
Fixes #1664

Add back readonly attribute to VTextField's internal input

---

src/stylus/components/_input-groups.styl
src/stylus/components/_select.styl

Playground.vue
```vue
<template>
<v-app id="inspire" class="pa-5">
<v-layout row>
<v-text-field :async-loading="saving" @input="save()" placeholder="Start typing..." persistent-hint hint="This is hint"></v-text-field>
<v-text-field :async-loading="true" @input="save()" disabled placeholder="Loading" persistent-hint hint="This is hint"></v-text-field>
</v-layout>
<v-layout row>
<v-select autocomplete :async-loading="saving" @update:search="save()" :items="[1,2]" placeholder="Start typing..." persistent-hint hint="This is hint"></v-select>
<v-select autocomplete  :async-loading="true" @input="save()" :items="[1,2]" disabled placeholder="Loading" persistent-hint hint="This is hint"></v-select>
</v-layout>
</v-app>
</template>
<script>
data: () => ({
saving: false,
}), …
```

layout issue with async-loading v-text-field (fixes #1672)

---

src/components/VBtn/VBtn.vue
src/components/VRadioGroup/VRadio.vue
src/components/VRadioGroup/VRadioGroup.vue

Fix several radio issues

---

src/components/VSelect/VSelect.spec.js
src/components/VSelect/VSelect.vue

test is ok, not sure about solution

fixes #1699

---

src/components/VTextField/VTextField.spec.js

Should prevent fc774a26 from happening again

Test if VTextField keeps its value on blur

---

src/components/VTabs/VTabs.spec.js
src/components/VTabs/VTabsBar.js
src/components/VTabs/VTabsItem.js

Dynamically adding v-tabs-item should now trigger overflow calculation

Fixed #1711

---

src/components/VTextField/VTextField.spec.js
src/components/VTextField/VTextField.vue

Caused by 8411ff60 and fc774a26

Fix an issue where the VTextField's change event would fire multiple times

---

src/components/VTextField/VTextField.spec.js
src/components/VTextField/VTextField.vue

If you'd just merged #1702 this wouldn't have happened
Fixes #1726

Update lazyValue even if the input is focused

---

src/stylus/components/_buttons.styl
src/stylus/components/_data-table.styl
src/stylus/components/_icons.styl
src/stylus/components/_navigation-drawer.styl

Similar to https://github.com/vuetifyjs/vuetify/pull/1747#issuecomment-329949149

moves styles that are not theme dependent outside the theme()

---

src/components/VFooter/VFooter.vue

Add themeable mixin to VFooter so dark and light props can be managed.

Add themeable mixin to VFooter

---

.eslintignore

It's super annoying to paste in somebody's codepen and have the build fail for some arbitrary reason

Dont lint /dev

---

src/components/VMenu/VMenu.js
src/components/VMenu/mixins/menu-activator.js
src/components/VMenu/mixins/menu-generators.js
src/mixins/menuable.js

why just control close delay if we can control open delay as well
`<v-menu open-delay="500" close-delay="0">`
Needs docs update if merged

fixes #1794

---

src/components/VTextField/VTextField.js
src/components/VTextField/VTextField.spec.js

`value`, `inputValue`, `lazyValue`, `initialValue`... :/

Change event was emitted when value hasn't changed

---

src/components/VSelect/VSelect2.spec.js
src/components/VSelect/__snapshots__/VSelect2.spec.js.snap
src/mixins/input.js
src/stylus/components/_input-groups.styl
src/stylus/components/_select.styl

repushed https://github.com/vuetifyjs/vuetify/pull/1747

Fixes rotated clearable icon

---

src/components/VSelect/VSelect.js

Focus v-select's internal input when focus() is called

---

src/components/VMenu/mixins/menu-activator.js

Focus menu activator when clicked

---

src/stylus/components/_lists.styl

Was added in 8f06b55d6c1fc95efe86b84d095e47064570005f
Codepen: https://codepen.io/anon/pen/QqGjbJ?editors=1000

Fix an issue with text fields inside list-tile-actions

---

src/components/VCheckbox/VCheckbox.js
src/components/VRadioGroup/VRadio.js
src/components/VSwitch/VSwitch.js
src/mixins/rippleable.js
src/util/to-have-been-warned.js

@johnleider suggested this in #1674 
Also cleaned up `to-have-been-warned` because codebeat said to

Extract ripple into a mixin for VCheckbox, VRadio, and VSwitch

---

src/stylus/generic/_reset.styl

Remove button focus border on firefox

---

src/components/VTabs/VTabsItems.js

Scrolling paginated tabs on mobile also switches between them

---

src/util/mask.js
src/util/mask.spec.js

PR for alphanumeric mask in docs included
https://github.com/vuetifyjs/docs/pull/246

alphanumeric mask

---

dist/vuetify.js
src/components/VSelect/VSelect.js

Fix autocomplete showing only filtered item if field is not dirty

---

src/components/VApp/VApp.js
src/components/Vuetify/index.js
src/util/touchSupport.js

WIP: Detect touchscreen support instead of using breakpoints

---

src/components/VSnackbar/VSnackbar.js
src/components/VSnackbar/VSnackbar.spec.js

docs https://github.com/vuetifyjs/docs/pull/259

colorable snacks

---

src/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
src/components/VList/VListTile.js
src/components/VList/VListTile.spec.js
src/components/VSelect/__snapshots__/VSelect.spec.js.snap
src/components/VSelect/__snapshots__/VSelect2.spec.js.snap

v-list-tile with click handler should be a routeLink

---

src/components/VBtn/VBtn.js

docs https://github.com/vuetifyjs/docs/pull/272/files

colorable v-btn

---

src/components/VIcon/VIcon.js

docs https://github.com/vuetifyjs/docs/pull/272/files

colorable v-icon

---

src/components/VTextField/VTextField.js
src/mixins/maskable.js

Fixed caret position on delete. The caret position stays/jumps to the correct position even if the deletion causes a dynamic switch of mask.

Fixed caret position on mask change during deletion.

---

src/components/VSlider/VSlider.js

Change slider value only when clicked on the track

---

src/stylus/components/_tooltips.styl

enables pointer-events for tooltip

---

src/components/VBadge/VBadge.js

playground
```vue
<template>
<v-app>
<main>
<v-content>
<v-checkbox v-model="badge" label="Badge on/off"></v-checkbox>
<v-badge>
<span v-if="badge" slot="badge">y</span>
<v-icon>check</v-icon>
</v-badge>
</v-container>
</v-content>
</main>
</v-app>
</template>
<script>
data: () => ({
badge: true
})
}
</script>
```

do not display empty badge if there is no badge slot

---

src/stylus/components/_buttons.styl
src/stylus/components/_icons.styl

fixes disabled button text/icon colors and disabled icon color

---

src/components/VDataTable/VEditDialog.js

use 'color' prop instead of 'primary', do not generate actions if not large

---

src/stylus/components/_app.styl
src/stylus/components/_breadcrumbs.styl
src/stylus/elements/_global.styl
src/stylus/settings/_theme.styl

fixes breadcrumbs styles for light/dark theme, adds global a:hover styles

---

src/stylus/components/_buttons.styl

Adds styles for hovered v-btn text

---

src/components/VDatePicker/VDatePicker.js

run proper wheel handler depending on active picker

---

src/components/VSelect/mixins/select-autocomplete.js

Don't try to slice item text if it isn't being searched for

---

src/components/VSelect/VSelect.js

Don't blur selects when an item is selected

---

src/components/VChip/VChip.js
src/components/VChip/VChip.spec.js

Chip colorable

---

src/components/VList/VListTile.js
src/components/VList/VListTile.spec.js

We don't like boolean props to be true by default

renames active prop to inactive to make it false by default

---

src/stylus/components/_buttons.styl

IconsInsideButtonsColor_#2108

---

.github/.git_commit_msg.txt
.gitignore
dev/prepare-commit-message.js
package.json

This will help everyone create more descriptive commit messages, and
hopefully reduce the number of unrelated changes
A modified version of this template can be used for pull requests as well

chore: Create a git commit message template and apply it to new commits

---

.gitignore
.npmignore
.travis.yml
build/release.sh
package.json

This will allow travis to build and release new versions simply by pushing a new tag to dev
@johnleider will have to add `NPM_API_KEY` and `GITHUB_API_KEY` in the travis dashboard , see https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

Automatic releases

---

src/stylus/components/_text-fields.styl

Fixes VTextField box label position if placeholder is set

---

src/stylus/components/_text-fields.styl

fix: set proper color for textarea placeholder

---

src/stylus/components/_bottom-navs.styl

fix: styles for buttons in bottom navigation

---

src/components/VTooltip/VTooltip.js

Top as default position for VTooltip

---

src/components/VDialog/VDialog.js
src/components/VDialog/__snapshots__/VDialog.spec.js.snap

See 5168d648d62e61265c133353936e4fb0695d9725

refactor: do not put inline styles if they equal to defaults

---

src/components/VSelect/VSelect.js

https://codepen.io/anon/pen/WZaPBq?editors=1010

fix: duplicated entries when using cache-items without return-object

---

src/stylus/components/_select.styl

fix: background color for segmented button

---

src/components/VDatePicker/mixins/date-years.js
src/components/VDatePicker/mixins/month-table.js

fix: don't update inputDate if new date is not allowed

---

src/stylus/components/_carousel.styl
src/stylus/elements/_code.styl

fix: Remove stylus @extend for stylus block level import (#1902)

---

src/components/transitions/row-expand-transition.js

fix: set proper expanded row height

---

src/components/VSelect/VSelect.js
src/components/VSelect/VSelect2.spec.js
src/components/VSelect/__snapshots__/VSelect2.spec.js.snap

fix: clearable icon behaviour in autocomplete

---

src/components/VSlider/VSlider.js
src/components/VSlider/__snapshots__/VSlider.spec.js.snap
src/stylus/components/_sliders.styl

fixes white space around the disabled slider indicator

---

src/components/VDataTable/mixins/body.js

feat: no-data and no-results slots for data table

---

src/components/VSelect/VSelect-autocomplete.spec.js
src/components/VSelect/VSelect-tags.spec.js
src/components/VSelect/VSelect.js
src/components/VSelect/mixins/select-autocomplete.js
src/components/VSelect/mixins/select-generators.js

fixes #2094
```vue
<template>
<main>
<v-content>
<v-container>
<v-checkbox label="Hide selected" v-model="hideSelected"></v-checkbox>
<v-select clearable :hide-selected="hideSelected" :items="items" v-model="select2" label="default select"></v-select>
<v-select clearable :hide-selected="hideSelected" :items="items" v-model="select1" multiple label="multiple"></v-select>
<v-select clearable :hide-selected="hideSelected" :items="items" v-model="select2" autocomplete label="autocomplete"></v-select>
<v-select clearable :hide-selected="hideSelected" :items="items" v-model="select1" multiple autocomplete label="multiple autocomplete"></v-select>
<v-select clearable :hide-selected="hideSelected" :items="items" combobox v-model="select2" label="combo"></v-select>
<v-select …
```

fixes TAB key in selects

---

src/components/VGrid/VContent.js
src/stylus/components/_app.styl
src/stylus/components/_content.styl
src/stylus/components/_navigation-drawer.styl
src/stylus/elements/_global.styl

New layout markup:
```html
<v-app>
<v-toolbar app>...</v-toolbar>
<v-content>
Content
</v-content>
</v-app>
```

fix: remove necessity of <main>

---

src/mixins/overlayable.js

fix: arrow up/down not working in inputs in dialog

---

src/components/VCard/VCard.js
src/components/VCard/VCard.spec.js
src/components/VCard/__snapshots__/VCard.spec.js.snap

fixes: #2346
Don't know what happened to tests, background style is rendered in browser but not in test :/

fix: adds quotes to background image

---

src/components/VDataTable/VEditDialog.js
src/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
src/components/VDialog/VDialog.js
src/components/VDialog/VDialog.spec.js
src/components/VDialog/__snapshots__/VDialog.spec.js.snap
src/components/VExpansionPanel/VExpansionPanelContent.js
src/components/VExpansionPanel/VExpansionPanelContent.spec.js
src/components/VList/VListGroup.js
src/components/VList/VListGroup.spec.js
src/components/VList/__snapshots__/VListGroup.spec.js.snap
src/components/VMenu/VMenu.spec.js
src/components/VMenu/__snapshots__/VMenu.spec.js.snap
src/components/VSelect/VSelect-autocomplete.spec.js
src/components/VSelect/VSelect-tags.spec.js
src/components/VSelect/VSelect.js
src/components/VSelect/VSelect.spec.js
src/components/VSelect/VSelect2.spec.js
src/components/VSelect/__snapshots__/VSelect.spec.js.snap
src/components/VSelect/__snapshots__/VSelect2.spec.js.snap
src/components/VSelect/mixins/select-autocomplete.js
src/components/VSelect/mixins/select-generators.js
src/mixins/bootable.js

fixes #2305
slightly improves #2080
- removes 'lazy' prop
- adds 'eager' prop

fix: do not render bootable content if not active

---

src/components/VDatePicker/VDatePicker.js
src/components/VDatePicker/VDatePicker.spec.js
src/components/VDatePicker/__snapshots__/VDatePicker.spec.js.snap
src/components/VDatePicker/mixins/date-header.js
src/components/VDatePicker/mixins/date-table.js
src/components/VDatePicker/mixins/date-title.js
src/components/VDatePicker/mixins/date-years.js
src/components/VDatePicker/mixins/month-table.js
src/stylus/components/_date-picker.styl

fix: improve date picker performance

---

src/components/VTextField/VTextField.js

fix: invalid textfield behaviour with number value

---

src/components/VPagination/VPagination.js
src/components/VPagination/VPagination.spec.js
src/components/VPagination/__snapshots__/VPagination.spec.js.snap

fix: disabled pagination next button if length=0

---

src/components/VDataTable/VDataTable.spec.js
src/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
src/components/VDataTable/mixins/foot.js

feat: do not render items-per-page select with only 1 option

---

src/components/VApp/mixins/app-theme.js
src/components/Vuetify/mixins/theme.js

Prevents everything from flashing black while the JS loads

fix(theme): generate theme stylesheet with SSR

---

.github/CONTRIBUTING.md
.travis.yml
build/parse-npm-tag.js
build/release.sh

- `dev` will be new features and breaking changes
- `master` will be the default branch, and contain the current supported release with bugfixes only
- `dev` will be merged into master before a new stable release
When releasing:
- beta versions:
- checkout latest `dev`
- run release script
- patch versions:
- checkout latest `master`
- run release script
- follow instructions to merge master into dev
- new stable versions from dev:
- checkout latest `master`
- `git merge dev`
- run release script
- follow instructions to merge master into dev

Update build script and CONTRIBUTING.md for new branch model

---

src/components/VDataTable/VDataTable.spec.js
src/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
src/components/VDataTable/mixins/body.js

display no-results-text when no item matches search string

---

src/components/VDataTable/VDataTable.js
src/components/VDataTable/VDataTable.spec.js
src/components/VDataTable/mixins/head.js

fix: display progress with headers slot

---

src/components/VApp/mixins/app-theme.js
src/stylus/components/_app.styl

resolves #2515
To force the current blue colour, use `class="blue--text text--darken-2"`

feat(anchor tags): added theme support to anchor tags

---

src/components/VNavigationDrawer/VNavigationDrawer.js
src/components/VNavigationDrawer/VNavigationDrawer.spec.js

fix(drawer): convert isMobile to a computed property

---

src/components/VGrid/VContent.js
src/stylus/components/_app.styl

This was deprecated in 0.17 and can be removed for 1.0

Remove v-content <main> warning

---

src/stylus/components/_buttons.styl

fix: accent button text color

---

src/components/VDatePicker/mixins/date-years.js

fix: don't select date when changing year and date not allowed

---

src/components/VDataIterator/VDataIterator.spec.js
src/components/VDataTable/VDataTable.spec.js
src/mixins/data-iterable.js

makes it working similar to data table (#2590)
additionally refactors the test for data table

fix: data iterator items should not be filtered with empty search

---

src/components/VBottomNav/VBottomNav.spec.js
src/components/VBtn/VBtn.js
src/components/VBtn/VBtn.spec.js
src/components/VBtnToggle/VBtnToggle.spec.js
src/components/VBtnToggle/__snapshots__/VBtnToggle.spec.js.snap
src/mixins/button-group.js
src/mixins/registrable.js

Added and fixed existing tests.
The pen shows the problem.  First toggle button is unselectable, as is first botton nav button.  Also note that when you Click to Show Extra Button, the extra buttons don't work.  That bug is fixed as well.
Copy into playground with fixes to see that the toggle buttons work, the bottom nav continues to work, and adding and removing buttons works correctly while preserving mandatory invariant.
https://codepen.io/jayblanchard/pen/ooBXKo?&editors=101

Allow buttons embedded in other components to still function within VBtnToggle and VBottomNav.

---

src/stylus/components/_dialogs.styl

fix(VDialog): prevent scrollable dialog content from being cut off in IE

---

src/components/VSelect/VSelect.js

Basic comparison, old vs new (Set) vs new (Map)
https://codepen.io/jayblanchard/pen/qVwpGz?editors=1010

perf: Rewrite filteredDuplicates to be O(n) rather than O(n*n)

---

src/directives/click-outside.js

Navigation Drawer does not react to touchable device

Fixes #2544

---

src/components/VSelect/VSelect.js
src/components/VSelect/VSelect.spec.js
src/components/VSelect/mixins/select-helpers.js
src/components/VSelect/mixins/select-props.js

It also simplifies the default comparator code
fixes #2692
alternative for https://github.com/vuetifyjs/vuetify/pull/2693

enh: **value-comparator** prop for multiple `v-select`

---

src/components/VDatePicker/VDatePicker.date.spec.js
src/components/VDatePicker/VDatePicker.js
src/components/VDatePicker/VDatePicker.month.spec.js
src/components/VDatePicker/mixins/date-header.js

fixes #2123
docs: https://github.com/vuetifyjs/vuetifyjs.com/pull/105

enh: add possibility to define previous/next date icons in pickers

---

src/components/VNavigationDrawer/VNavigationDrawer.spec.js
src/components/VToolbar/VToolbar.js
src/components/VToolbar/VToolbar.spec.js
src/util/testing.js

fix: application not updating top on screen resize

---

src/components/VApp/__snapshots__/VApp.spec.js.snap
src/components/VApp/mixins/app-theme.js
src/components/VGrid/VContent.js
src/components/VNavigationDrawer/VNavigationDrawer.js
src/components/VToolbar/VToolbar.js
src/components/VToolbar/__snapshots__/VToolbar.spec.js.snap
src/mixins/ssr-bootable.js
src/stylus/bootstrap.styl
src/stylus/components/_content.styl
src/stylus/components/_navigation-drawer.styl
src/stylus/components/_toolbar.styl
src/stylus/tools/_bootable.styl

moved all logic to mixin, apply dataset value for boot status, hide until booted to avoid entry
animation or pre-emptive popin

refactor(layout): changed how ssr bootable works

---

src/components/VTextField/VTextField.js
src/components/VTextField/VTextField.spec.js
src/components/VTextField/__snapshots__/VTextField.spec.js.snap
src/mixins/maskable.js
src/util/mask.js
src/util/mask.spec.js

test: increased test coverage for mask/maskable/VTextField

---

src/components/Vuetify/index.js

I think it is better to use Object.values() instead of Object.keys() because of fewer code

improve code in components/vuetify/index.js

---

src/stylus/components/_footer.styl

[issue #2853]Applies a dark tint to the content. get primary text color theme dark

---

src/components/VAlert/__snapshots__/VAlert.spec.js.snap
src/components/VBtnToggle/__snapshots__/VBtnToggle.spec.js.snap
src/components/VChip/__snapshots__/VChip.spec.js.snap
src/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
src/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
src/components/VDatePicker/__snapshots__/VDatePicker.date.spec.js.snap
src/components/VDatePicker/__snapshots__/VDatePicker.month.spec.js.snap
src/components/VExpansionPanel/__snapshots__/VExpansionPanel.spec.js.snap
src/components/VExpansionPanel/__snapshots__/VExpansionPanelContent.spec.js.snap
src/components/VIcon/VIcon.js
src/components/VIcon/VIcon.spec.js
src/components/VList/__snapshots__/VListGroup.spec.js.snap
src/components/VPagination/__snapshots__/VPagination.spec.js.snap
src/components/VRadioGroup/__snapshots__/VRadio.spec.js.snap
src/components/VRadioGroup/__snapshots__/VRadioGroup.spec.js.snap
src/components/VSelect/__snapshots__/VSelect.spec.js.snap
src/components/VSelect/__snapshots__/VSelect2.spec.js.snap
src/components/VToolbar/__snapshots__/VToolbarSideIcon.spec.js.snap

No style size on VIcon by default

---

src/components/VCarousel/VCarouselItem.spec.js
src/components/VDataTable/mixins/head.js
src/components/VList/VListGroup.spec.js
src/components/VRadioGroup/VRadio.spec.js
src/components/VSelect/mixins/select-generators.js
src/components/VSlider/VSlider.js
src/components/VSlider/VSlider.spec.js
src/components/VTabs/VTab.spec.js
src/components/VTabs/VTabItem.spec.js
src/index.js
src/mixins/data-iterable.js
src/mixins/detachable.js
src/mixins/registrable.js
src/util/console.js
src/util/console.spec.js

Unifies all console warns/errors
Adds warning when data-iterator item has missing the key attribute
My motivation was to unify all console warns/errors
Manually + updated unit tests

enh: unified console messages

---

src/stylus/components/_expansion-panel.styl

The panel was expanding horizontally to fit the overflowing data. 
With this change the user now needs to add `overflow-x: auto` to the element containing the overflow and it will work properly.
https://codepen.io/anon/pen/govXEG?editors=1100
Tested on the new docs with latest Firefox and Chromium on Linux.

fix(v-expansion-panel): Add max-width to resolve overflow issues

---

src/components/VDialog/VDialog.js
src/components/VMenu/mixins/menu-generators.js
src/components/VNavigationDrawer/VNavigationDrawer.js
src/components/VNavigationDrawer/VNavigationDrawer.spec.js
src/components/VSelect/VSelect.js
src/components/VSlider/VSlider.js
src/components/VSpeedDial/VSpeedDial.js
src/directives/click-outside.js
src/directives/resize.js

`v-resize` and `v-click-outside` were storing references to the vnode context that was being passed, this
was not properly being GCed. 
Wanted to clog the leak
Extensively comparing heap snapshots
```vue
<template>
<v-app>
<v-toolbar>
<v-btn to="/page1">1</v-btn>
<v-btn to="/page2">2</v-btn>
</v-toolbar>
<v-navigation-drawer stateless></v-navigation-drawer>
<v-content class="px-5">
<router-view></router-view>
<v-dialog>
<v-btn slot="activator">Click</v-btn>
<v-card>
<v-card-text>
hi
</v-card-text>
</v-card>
</v-dialog>
<v-select label="test" :items="[1,2,3,4]"></v-select>
<v-slider v-model="value"></v-slider>
<v-menu>
<v-btn slot="activator">hi</v-btn>
<v-card>
<v-card-text>Hello</v-card-text>
</v-card>
</v-menu>
<v-tabs></v-tabs>
</v-content>
</v-app>
</template>
<script>
export default …
```

fix(directives): fixed memory leak

---

src/util/mask.js

Fixes a js error ReferenceError: isMaskDelimiter is not defined.
I also moved `defaultDelimiters` export to top for better readability.
An error is thrown in es6 version on load, in es5 there error can be seen if you use char `X` for `mask` property on a `v-text-field`.
Fixes #2998
You can reproduce the bug using the following snippet:
```js
const x = {test: isMaskDelimiter};
const isMaskDelimiter = "something";
```
In "es5 version" of the bug the property will be `undefined`:
```js
var x = {test: isMaskDelimiter};
var isMaskDelimiter = "something";
console.log(x.test); // undefined
```
No test files created.
Not needed.

Bugfix - ReferenceError: isMaskDelimiter is not defined

---

src/components/VDialog/VDialog.js
src/components/VMenu/VMenu.js
src/components/VMenu/mixins/menu-generators.js
src/components/VNavigationDrawer/VNavigationDrawer.js
src/components/VSelect/VSelect.js
src/directives/click-outside.js

Adjusted evaluation process for click-outside implementing components.
Since vNode.context reference was removed due to a memory leak, added **isActive** to closeConditional checks to allow time for state to propagate before running the callback.
fixes #3021 
Needs a test
https://hastebin.com/bazezeceha.xml

fix(click-outside): adjusted logic for determining click-outside state

---

src/stylus/components/_tabs.styl

fixes #3061
PR for docs (right aligned tabs example was commented out): https://github.com/vuetifyjs/vuetifyjs.com/pull/226
manualy/visually 
see #3061 repro

fix (v-tabs): right aligned tabs were centered

---

src/stylus/components/_input-groups.styl

fixes a bug when using validation rules with persistent-hint
clicking out of the input causes a layout jump because the hint is too narrow
```html
<template>
<v-app>
<v-content>
<v-container>
<v-text-field
label="Legal last name"
hint="example of persistent helper text"
v-model="last"
:rules="[() => last.length > 0 || 'This field is required']"
required
</v-container>
</v-content>
</v-app>
</template>
<script>
data: () => ({
last: ''
})
}
</script>
```

fix: make input error full width

---

src/components/VTextField/VTextField.js

domProps are for things you would set in js, eg `document.getElementById('mySelect').value = 'Two'`
unrecognised domProps will throw an error, but attrs will just be ignored. 
fixes #3072
```html
<template>
<v-app>
<v-content>
<v-layout row>
<v-flex xs4>
<v-subheader>Suffix for time zone</v-subheader>
</v-flex>
<v-flex xs8>
<v-text-field
label="Label Text"
value="12:30:00"
type="time"
suffix="PST"
</v-flex>
</v-layout>
</v-container>
</v-content>
</v-app>
</template>
```

fix(VTextField): only use valid domProps

---

src/stylus/components/_buttons.styl
src/stylus/components/_toolbar.styl

fixed a bug where the fab styles were not proper on i11. also fixed a bug where btns would shift
when clicked in ie11
fixes #3068
visually
```vue
<template>
<v-content>
<div>
<v-btn>tset</v-btn>
<v-btn large>tset</v-btn>
<v-btn small>tset</v-btn>
</div>
<div>
<v-btn icon><v-icon>block</v-icon></v-btn>
<v-btn icon small><v-icon>block</v-icon></v-btn>
<v-btn icon small><v-icon small>block</v-icon></v-btn>
<v-btn icon large><v-icon>block</v-icon></v-btn>
<v-btn icon large><v-icon large>block</v-icon></v-btn>
</div>
<div>
<v-btn fab><v-icon>block</v-icon></v-btn>
<v-btn fab small><v-icon>block</v-icon></v-btn>
<v-btn fab small><v-icon small>block</v-icon></v-btn>
<v-btn fab large><v-icon>block</v-icon></v-btn>
<v-btn fab large><v-icon large>block</v-icon></v-btn>
</div> …
```

fix(v-btn): fixed fab styles in ie11

---

src/components/VTabs/VTab.js
src/components/VTabs/VTab.spec.js

the current logic was very hacky and caused issues when building static sites, such as with nuxt
fixes #3010
Changed how `v-tab` determines a router-link active state
Fixes #3010 
Cloning the reproduction repository and linking vuetify
```cli
$ git clone git@github.com:farrajota/vuetify-nuxt-issue-report.git
$ yarn && yarn link vuetify && yarn generate
```
See above

fix(v-tab): changed how active link is derived

---

src/mixins/bootable.js
src/mixins/bootable.spec.js

if lazy and active at boot, should show content
fixes #3084
jest
```vue
<template>
<div id="app">
<v-content>
<v-expansion-panel expand class="elevation-0">
<v-expansion-panel-content
v-model="post.open"
lazy
v-for="(post, i) in posts"
:key="i"
>
<div slot="header">{{post.open ? 'Close' : 'Open'}}</div>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veritatis repudiandae unde, placeat iste eaque omnis necessitatibus, ratione, distinctio laboriosam rem, at porro aut saepe voluptatem. Voluptas dicta alias, molestiae!</p>
</v-expansion-panel-content>
</v-content>
</v-app>
</div>
</template>
<script>
const posts = []
for (let i = 0; i < 10; i++) {
posts.push({
title: `Post #${i}`,
open: i === 2
})
}
data: () …
```

fix(bootable): added check for active status

---

src/components/VNavigationDrawer/VNavigationDrawer.spec.js
src/mixins/applicationable.js

Not setting application properties on the server meant a content jump once hydration is complete. 
fixes #3012 
before:
after: 
Tested with the vuetifyjs.com repo, and a basic CSR template too
```html
<template>
<v-app>
<v-toolbar app></v-toolbar>
<v-navigation-drawer app></v-navigation-drawer>
<v-content>
<v-container>
<h1 class="title">Title</h1>
</v-container>
</v-content>
</v-app>
</template>
```

fix(ssr): update $vuetify.application when created instead of mounted

---

src/stylus/components/_pickers.styl

Commit for master branch: https://github.com/vuetifyjs/vuetify/commit/751cd2b68bb47e66cb6300126f1575412bee4dee
Fixes problem with Chrome 64
```vue
<template>
<v-app id="app">
<v-navigation-drawer app fixed :value="true"></v-navigation-drawer>
<v-content>
<v-date-picker v-model="date"></v-date-picker>
</v-content>
</v-app>
</template>
<script>
data: () => ({
date: null
})
};
</script>
```

fix (v-picker): workaround for chrome 64 rendering issue

---

index.d.ts
src/components/Vuetify/util/goTo.js
src/components/Vuetify/util/goTo.spec.js
src/util/testing.js

and added support for passing VueComponent as target
Found problems when writing doc page for goTo
Manually in docs, and added a couple of simple tests
N/A

enh(goTo): fixed potential error when passing undefined/null

---

src/stylus/components/_tooltips.styl

Changed tooltip to inherit height
fixes #3205
visually
```vue
<template>
<div id="app">
<v-app dark>
<v-content>
<v-layout column class="mt-3 ml-3">
<v-flex xs12>
<v-toolbar
app
fixed
>
<v-tooltip
:disabled="false"
bottom
>
<v-btn
flat
slot="activator"
>
<span>with tooltip</span>
</v-btn>
<span>text</span>
</v-tooltip>
<v-btn
flat
slot="activator"
ref="activator"
>
<span>without tooltip</span>
</v-btn>
</v-toolbar>
</v-flex>
</v-layout>
</v-content>
</v-app>
</div>
</template>
```

fix(v-tooltip): fixed tooltip height

---

src/components/VTabs/VTabs.js
src/components/VTabs/mixins/tabs-watchers.js

updateTabs was not being called, also fixed initial render of slider being off by a few px
fixes #3174
visually (also docs run through)
```vue
<template>
<div id="app">
<div>
<v-tabs v-model="active" color="cyan" dark slider-color="yellow">
<v-tab href="#a">
AAA
</v-tab>
<v-tab href="#b">
BBB
</v-tab>
<v-tab href="#c">
CCC
</v-tab>
<v-tab-item id="a">
<v-card flat>
</v-card>
</v-tab-item>
<v-tab-item id="b">
<v-card flat>
</v-card>
</v-tab-item>
<v-tab-item id="c">
<v-card flat>
</v-card>
</v-tab-item>
</v-tabs>
</div>
Active: {{active}}
</v-app>
</div>
</template>
<script>
data () {
return {
active: 'c',
text: 'Lorem ipsum dolor sit amet, …
```

fix(v-tabs): updated booting process

---

src/components/VSelect/mixins/select-autocomplete.js

removed unnecessary  code
fixes #3151
visually
```vue
<template>
<div id="app">
<v-card color="grey lighten-4" flat>
<v-card-text>
<v-layout wrap>
<v-flex xs12>
<v-select
v-model="select2"
label="Select a favorite activity or create a new one"
combobox
:items="items"
></v-select>
</v-flex>
<v-flex xs12>
<v-select
label="I use chips"
chips
tags
:items="items"
></v-select>
</v-flex>
<v-flex xs12>
<v-select
label="I use a scoped slot"
chips
tags
:items="items"
>
<template slot="selection" slot-scope="data">
<v-chip
@input="data.parent.selectItem(data.item)"
class="chip--select-multi"
:selected="data.selected"
:disabled="data.disabled"
:key="JSON.stringify(data.item)"
>
<v-avatar class="accent">{{ data.item.slice(0, …
```

fix(v-select): removed useless operation

---

src/components/VApp/mixins/app-theme.js

Nuxt uses vue-meta, so the traditional `$ssrContext.head` method didn't work server-side
Fixes #3329

fix(ssr): allow theme to be applied with vue-meta

---

.babelrc
build/babel-transform-define.js
build/webpack.base.config.js
package.json
src/components/Vuetify/index.js
yarn.lock

fixes vuetifyjs/nuxt#27
fixes vuetifyjs/nuxt#28
fixes vuetifyjs/webpack#5

fix(build): use babel-transform-define instead of webpack.DefinePlugin

---

src/components/VBtnToggle/VBtnToggle.js
src/components/VBtnToggle/VBtnToggle.spec.js
src/mixins/button-group.js

This resolves #3136 and also fixes internal and external state tracking when doing things like v-if with buttons within the button group.  2 new warnings were added to assist users with invalid usage.
Fixes #3136 
New tests added, and manual testing using the following Playground
```html
<template>
<Boilerplate>
<v-layout row>
<v-btn @click="showToggle = !showToggle">{{ showToggle ? 'Hide' : 'Show' }} button toggle</v-btn>
<v-btn @click="showBtn = !showBtn">{{ showBtn ? 'Hide' : 'Show' }} buttons</v-btn>
</v-layout>
<v-layout row>
<v-btn-toggle v-if="showToggle" mandatory multiple v-model="toggle">
<v-btn v-if="showBtn" value="val1">Val 1</v-btn>
<v-btn value="val2">Val 2</v-btn>
<v-btn v-if="showBtn" value="val3">Val 3</v-btn>
<v-btn value="val4">Val 4</v-btn>
<v-btn v-if="showBtn" …
```

Fixes for button-group button state synching and tracking

---

src/stylus/components/_data-table.styl

Removed the blue outline.  To keep track of which header has the keyboard focus, the sort arrow icon is shown on focus similar to hover.  I marked this as a breaking change because some people may actually want the blue outline.
Fixes #3331
Any data table code example from docs

Remove outline on data table headers, add focus effect

---

src/components/Vuetify/mixins/application.js
src/mixins/applicationable.js

Will now store a reference to the components that bind to ensure no unbinding component can
overwrite a new bind
fixes #3347
none
See attached, requires dev setup

fix(applicationable): updated process

---

build/config.js
build/webpack.prod.config.js

fix(build): remove CSS sourcemaps from production builds

---

src/stylus/components/_toolbar.styl

Fixes probable typo in toolbar's style.

Fix toolbar style typo

---

index.d.ts
src/util/colors.d.ts

Added a .d.ts type declaration file for util/colors 
First time ever creating any sort of type declaration file for a library so please do feel free to suggest changes if needed.
Resolves complaints of Tslint (No implicit any + unknown property).
Tested locally in a simple project. No errors are shows after adding this d.ts file.
Also:
```
Test Suites: 1 skipped, 85 passed, 85 of 86 total
Tests:       8 skipped, 688 passed, 696 total
Snapshots:   258 passed, 258 total
Time:        11.337s
Ran all test suites.
```
```
// index.d.ts
import 'vuetify/src/util/colors'
```
```
// src/util/color.d.ts
declare module 'vuetify/es5/util/colors' {
interface Color {
base: string;
lighten5: string;
lighten4: string;
lighten3: string;
lighten2: string;
lighten1: string;
darken1: string;
darken2: string; …
```

Add typings for util/colors

---

src/mixins/menuable.js

Avoid invoking `window.pageYOffset` while mouting menuable component for performance reasons (avoid layout trashing).
It doesn't seems required to compute offsetY at this time in the component lifecycle. It's now called later when the menuable is about to be displayed.
fixes #3497

perf(menuable): Avoid layout trashing on menuable components mount

---

src/stylus/components/_speed-dial.styl

Adds styles similar to what's already on fixed FABs
Fixes #3414
```vue
<template>
<v-content>
<v-btn
fab
v-model="fab"
fixed
bottom
right
>
<v-icon large>
settings
</v-icon>
</v-btn>
<v-speed-dial
v-model="fab"
direction="top"
transition="scale-transition"
class="mb-5"
fixed
bottom
right
>
<v-btn
slot="activator"
fab
v-model="fab"
>
<v-icon large>
settings
</v-icon>
</v-btn>
<v-btn fab color="primary">
<v-icon large>
playlist_add
</v-icon>
</v-btn>
<v-btn fab color="green">
<v-icon large>
power_settings_new
</v-icon>
</v-btn>
<v-btn color="red" fab>
<v-icon large>
stop
</v-icon>
</v-btn>
<v-btn fab color="yellow accent-1">
<v-icon large class="red--text">
delete
</v-icon>
</v-btn> …
```

fix(speed-dial): add z-index and remove activator when fixed

---

src/mixins/data-iterable.js

When search updates, it calls the **updatePagination** method. When this method is called, search passes through the _itemsLength_ computed property. This property is already reactive to search changes. The solution was to either wait for the next tick after search was updated, or to simply watch itemsLength.
fixes #3511
none
``` vue
<template>
<div id="app">
<v-card>
<pre>{{ pagination }}</pre>
<v-card-title>
Nutrition
<v-text-field
append-icon="search"
label="Search"
single-line
hide-details
<v-data-table
:items="items"
:pagination.sync="pagination"
>
<td class="text-xs-right">{{ …
```

fix(data-iterator): watch items instead of search for pagination

---

src/components/Vuetify/util/goTo.js

It was possible to pass a negative value for the scroll position, causing it to get stuck. Also cleaned up process slightly.
fixes #3384
visually
``` vue
<template>
<div id="app">
<v-content>
<div id="element-near-top">Element Near Top</div>
<v-card height="100vh">
<v-card-text>Scroll down, click the button, Then try scrolling down again...</v-card-text>
</v-card>
<v-btn class="my-5" @click="$vuetify.goTo('#element-near-top', { offset: -100 })">Scroll To First Div</v-btn>
</v-content>
</v-app>
</div>
</template>
<style>
#element-near-top {
height: 100px;
}
</style>
```

fix($goTo): fixed negative scroll and cleaned up process

---

src/components/Vuetify/util/goTo.js

When using `goTo` the `step` function will check `progressPercentage`. If it reaches 1 it means the animation should be finished, according to the given time.
This fixes https://github.com/vuetifyjs/vuetify/issues/3608, where a different zoom setting could result in a target that will never be reached, thus locking the scroll permanently.
Visually.

fix(goTo) Always respect progressPercentage. Fixes #3608

---

src/components/VCard/VCardMedia.js
test/unit/components/VCard/VCardMedia.spec.js
test/unit/components/VCard/__snapshots__/VCardMedia.spec.js.snap

Fixes #3625
Made sure the source that gets added in `v-card-media` component is wrapped in quotes to avoid this situation
#3625 
I have added unit test and it created new snapshot in jest. I have never used it before so please let me know if I did something stupid.
```vue
<v-card-media src="file(1).jpg" height="200px">
</v-card-media>
```

fix: #3625 - image-links with parentheses aren't recognized

---

src/components/VTabs/VTabs.js
src/components/VTabs/mixins/tabs-watchers.js
test/unit/components/VTabs/VTabs.spec.js
test/unit/components/VTabs/__snapshots__/VTabs.spec.js.snap

overflow checks were not properly firing on resize
fixes #3620
could not figure out a direct way to test the logic of **callSlider**, so I did it indirectly
``` vue
<template>
<div id="app">
<v-tabs
dark
color="cyan"
show-arrows
>
<v-tabs-slider color="yellow"></v-tabs-slider>
<v-tab
v-for="i in 15"
:key="i"
:href="'#tab-' + i"
>
Item {{ i }}
</v-tab>
<v-tabs-items>
<v-tab-item
v-for="i in 15"
:key="i"
:id="'tab-' + i"
>
<v-card flat>
</v-card>
</v-tab-item>
</v-tabs>
</v-app>
</div>
</template>
<script>
data () {
return {
text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud …
```

fix(v-tabs): fixed dynamic arrows

---

src/components/VTabs/VTabs.js

fixes #3637
```vue
<template>
<v-app>
<v-navigation-drawer app v-model="drawer"/>
<v-content>
<v-tabs v-model="active" color="cyan" dark grow>
<v-tab
v-for="tab in tabs"
:key="tab"
ripple
>
Item {{ tab }}
</v-tab>
<v-tabs-slider color="yellow"></v-tabs-slider>
<v-tabs-items>
<v-tab-item
v-for="tab in tabs"
:key="tab"
>
<v-card flat>
</v-card>
</v-tab-item>
</v-tabs>
<div class="text-xs-center mt-3">
<v-btn @click="next">next tab</v-btn>
</div>
{{ typeof active }} {{ active }}
<v-btn @click="drawer = !drawer">Toggle drawer</v-btn>
</v-content>
</v-app>
</template>
<script>
data () {
return {
tabs: 18,
active: null,
text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore …
```

fix(VTabs): update slider position after resize timeout

---

src/components/VSelect/mixins/select-props.js
test/unit/components/VSelect/VSelect-autocomplete.spec.js

Change default browser-autocomplete to "off" on v-select
Fixes #3582 
Created a new unit test in `test/unit/components/VSelect/VSelect-autocomplete.spec.js` to test the default has been changed to 'off'
I only changed a word, `on` to `off` 😬

Change default browser-autocomplete to "off" on v-select

---

src/stylus/components/_snackbars.styl

The close button on the snackbar looks like it doesn't have any padding because of margin. This is fixed so it looks a bit better.
Current: https://prnt.sc/ixwfot
Proposed change: https://prnt.sc/ixwgjs
Just looks a bit better.
Chrome and Firefox (visually?)

Fix margin problem with snackbar "close" button

---

src/components/VBtn/VBtn.js
test/unit/components/VBtn/__snapshots__/VBtn.spec.js.snap

#3661 aftermath
fixes #3691
visually, updated snapshot
```vue
<template>
<v-app>
<v-content>
<v-btn color="success">Success</v-btn>
<v-btn color="error" loading>Error</v-btn>
<v-btn color="warning">Warning</v-btn>
<v-btn color="info">Info</v-btn>
</v-content>
</v-app>
</template>
```

fix (VBtn): button loader thickness and size

---

src/components/VAlert/VAlert.js
src/stylus/components/_alerts.styl
test/unit/components/VAlert/VAlert.spec.js
test/unit/components/VAlert/__snapshots__/VAlert.spec.js.snap

refactor (VAlert): Add v- prefix to alert classes

---

src/components/VBottomSheet/VBottomSheet.js
src/stylus/components/_bottom-sheets.styl

Refactor (VBottonSheet): Add v- prefix to bottom-sheet classes

---

src/components/VCard/VCard.js
src/components/VCard/VCardMedia.js
src/components/VCard/VCardTitle.js
src/stylus/components/_cards.styl
test/unit/components/VCard/VCard.spec.js
test/unit/components/VCard/__snapshots__/VCard.spec.js.snap
test/unit/components/VCard/__snapshots__/VCardMedia.spec.js.snap
test/unit/components/VCard/__snapshots__/VCardTitle.spec.js.snap
test/unit/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
test/unit/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
test/unit/components/VDatePicker/__snapshots__/VDatePicker.date.spec.js.snap
test/unit/components/VDatePicker/__snapshots__/VDatePicker.month.spec.js.snap
test/unit/components/VMenu/__snapshots__/VMenu.spec.js.snap
test/unit/components/VPicker/__snapshots__/VPicker.spec.js.snap
test/unit/components/VSelect/__snapshots__/VSelect.spec.js.snap
test/unit/components/VSelect/__snapshots__/VSelect2.spec.js.snap
test/unit/components/VTimePicker/__snapshots__/VTimePicker.spec.js.snap

Refactor (VCard): Add v- prefix to card classes

---

src/components/VChip/VChip.js
src/stylus/components/_chips.styl
test/unit/components/VChip/VChip.spec.js
test/unit/components/VChip/__snapshots__/VChip.spec.js.snap
test/unit/components/VSelect/VSelect-tags.spec.js
test/unit/components/VSelect/VSelect.spec.js

Refactor (VChip): Add v- prefix to chip classes

---

src/components/VTooltip/VTooltip.js
src/stylus/components/_toolbar.styl
src/stylus/components/_tooltips.styl
test/unit/components/VTooltip/VTooltip.spec.js
test/unit/components/VTooltip/__snapshots__/VTooltip.spec.js.snap

refactor (VTooltip): Add v- prefix to tooltip classes

---

src/components/VDataIterator/VDataIterator.js
src/mixins/data-iterable.js
src/stylus/components/_data-iterator.styl
test/unit/components/VDataIterator/VDataIterator.spec.js
test/unit/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap

Refactor (VDataIterator): Add v- prefix on data-iterator classes

---

src/components/VCard/index.js
src/components/VDataTable/VDataTable.js
src/components/VDataTable/index.js
src/components/VPicker/VPicker.js
src/util/helpers.js
test/unit/components/VDataTable/__snapshots__/VDataTable.spec.js.snap

- Add a temporary fix to createSimpleFunctional helper to allow better visually tests when adding the new prefix
- `yarn test`

refactor: Add v- prefix to card, picker and data table classes

---

src/components/VJumbotron/VJumbotron.js
src/stylus/components/_jumbotrons.styl
test/unit/components/VCarousel/__snapshots__/VCarousel.spec.js.snap
test/unit/components/VCarousel/__snapshots__/VCarouselItem.spec.js.snap

refactor (VJumbotron): Add v- prefix to jumbotron classes

---

src/components/VSubheader/VSubheader.js
src/stylus/components/_lists.styl
src/stylus/components/_navigation-drawer.styl
src/stylus/components/_subheaders.styl
test/unit/components/VSubheader/VSubheader.spec.js
test/unit/components/VSubheader/__snapshots__/VSubheader.spec.js.snap

refactor (VSubheader): Add v- prefix on subheader classes

---

src/components/VToolbar/VToolbar.js
src/components/VToolbar/VToolbarSideIcon.js
src/components/VToolbar/index.js
src/stylus/components/_toolbar.styl
test/unit/components/VToolbar/__snapshots__/VToolbar.spec.js.snap
test/unit/components/VToolbar/__snapshots__/VToolbarSideIcon.spec.js.snap

refactor (VToolbar): Add v- prefix on toolbar classes

---

src/stylus/components/_expansion-panel.styl

* Fix stylus update error
* Yarn test

Refactor (VExpansionPanel): Add v- prefix to expansion-panel classes

---

src/components/VTabs/VTab.js
src/components/VTabs/VTabItem.js
src/components/VTabs/VTabs.js
src/components/VTabs/VTabsItems.js
src/components/VTabs/VTabsSlider.js
src/components/VTabs/mixins/tabs-generators.js
src/stylus/components/_tabs.styl
src/stylus/components/_toolbar.styl
test/unit/components/VTabs/VTab.spec.js
test/unit/components/VTabs/VTabs.spec.js
test/unit/components/VTabs/__snapshots__/VTabs.spec.js.snap

refactor (VTabs): Add v- prefix to tabs classes

---

src/components/VStepper/VStepper.js
src/components/VStepper/VStepperContent.js
src/components/VStepper/VStepperStep.js
src/components/VStepper/__snapshots__/VStepperStep.spec.js.snap
src/components/VStepper/index.js
src/stylus/components/_steppers.styl
test/unit/components/VStepper/VStepperContent.spec.js

refactor (VStepper): Add v- prefix on stepper classes

---

src/components/VList/VList.js
src/components/VList/VListGroup.js
src/components/VList/VListTile.js
src/components/VList/VListTileAction.js
src/components/VList/VListTileAvatar.js
src/components/VList/index.js
src/components/VMenu/mixins/menu-keyable.js
src/stylus/components/_lists.styl
src/stylus/components/_menus.styl
src/stylus/components/_navigation-drawer.styl
src/stylus/components/_toolbar.styl
test/unit/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
test/unit/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
test/unit/components/VForm/VForm.spec.js
test/unit/components/VList/VListGroup.spec.js
test/unit/components/VList/VListTile.spec.js
test/unit/components/VList/__snapshots__/VList.spec.js.snap
test/unit/components/VList/__snapshots__/VListGroup.spec.js.snap
test/unit/components/VList/__snapshots__/VListTile.spec.js.snap
test/unit/components/VList/__snapshots__/VListTileAction.spec.js.snap
test/unit/components/VList/__snapshots__/VListTileAvatar.spec.js.snap
test/unit/components/VSelect/VSelect-autocomplete.spec.js
test/unit/components/VSelect/VSelect-combobox.spec.js
test/unit/components/VSelect/VSelect.spec.js
test/unit/components/VSelect/VSelect2.spec.js
test/unit/components/VSelect/__snapshots__/VSelect.spec.js.snap
test/unit/components/VSelect/__snapshots__/VSelect2.spec.js.snap

Refactor (VList): Add v- prefix to list classes

---

src/components/VDataTable/VDataTable.js
src/stylus/components/_tables.styl
test/unit/components/VDataTable/__snapshots__/VDataTable.spec.js.snap

refactor (VTable): Add v- prefix on table classes

---

src/components/VSpeedDial/VSpeedDial.js
src/stylus/components/_speed-dial.styl
test/unit/components/VSpeedDial/__snapshots__/VSpeedDial.spec.js.snap

refactor (VSpeedDial): Add v- prefix on speed dial classes

---

src/components/VSnackbar/VSnackbar.js
src/stylus/components/_snackbars.styl
test/unit/components/VSnackbar/VSnackbar.spec.js

refactor (VSnackbar): Add v- prefix on snackbar classes

---

src/components/VDataTable/VEditDialog.js
src/stylus/components/_small-dialog.styl

refactor (VDataTable): Add v- prefix on small dialog classes

---

src/components/VSlider/VSlider.js
src/stylus/components/_sliders.styl
test/unit/components/VSlider/__snapshots__/VSlider.spec.js.snap

refactor (VSlider): Add v- prefix on slider classes

---

src/stylus/components/_lists.styl

Add missing v- on list subheader removed on https://github.com/vuetifyjs/vuetify/pull/3776/files#diff-5a5680a23ec40dee49d87a222c29863aR153
- `yarn test`

Refactor (VSubheader): Add missing v- on list subheader

---

src/stylus/components/_small-dialog.styl

Fixes zero-width edit-dialog activator
closes #1795
Checked in markup from issue
```vue
<template>
<v-app>
<v-data-table :headers="headers"
:items="items"
:search="search">
<td class="text-xs-right">
<v-edit-dialog lazy> {{ props.item.type }}
<v-text-field slot="input"
label="Edit"
v-model="props.item.type"
single-line
counter
:rules="[max25chars]"></v-text-field>
</td>
<td class="text-xs-right">
<v-edit-dialog lazy> {{ props.item.email }}
<v-text-field slot="input"
label="Edit"
v-model="props.item.email"
single-line
counter
:rules="[max25chars]"></v-text-field>
</td>
<td class="text-xs-left">
<v-switch :label="props.item.is_default.toString()"
v-model="props.item.is_default"
></v-switch>
</td> …
```

fix: zero-width activator when edit-dialog input is empty

---

src/components/VBreadcrumbs/VBreadcrumbs.js
test/unit/components/VBreadcrumbs/VBreadcrumbs.spec.js
test/unit/components/VBreadcrumbs/__snapshots__/VBreadcrumbs.spec.js.snap

This change make sure to add divider only if next item available in breadcrumb.
This fix #3747
Tested by using code shared in codepen as well performed additional test when item with v-if available in between of other items.
```vue
<template>
<v-app>
<div>
<v-breadcrumbs>
<v-icon slot="divider">forward</v-icon>
<v-breadcrumbs-item
:key="item.text"
:disabled="item.disabled"
>
{{ item.text }}
</v-breadcrumbs-item>
<v-breadcrumbs-item> 
breadcrumb item 4 
</v-breadcrumbs-item>
<v-breadcrumbs-item v-if="false"> 
breadcrumb item 5 
</v-breadcrumbs-item>
<v-breadcrumbs-item> 
breadcrumb item 6 
</v-breadcrumbs-item>
<v-breadcrumbs-item v-if="false"> 
breadcrumb item 7 
</v-breadcrumbs-item>
</v-breadcrumbs>
</div>
</v-app>
</template>
<script>
data: () => …
```

fix(VBreadcrumbs): only create dividers for v-breadcrumbs-item

---

src/components/VAvatar/VAvatar.js
src/components/VIcon/VIcon.js
src/util/helpers.js
test/unit/components/VIcon/VIcon.spec.js

Added a ternary operation for props.size to check if it has not 'px' string. If it has not then add the string. 
Fixes #3565 
Added a new test to check that size='122' results in a correct answer and  rename the current test size='122px'

[Bug Report] V-icon size property not working with Number

---

src/directives/ripple.js
src/stylus/components/_ripples.styl

Refactor Add v- prefix on ripple class

---

src/components/VProgressLinear/VProgressLinear.js
src/stylus/components/_progress-linear.styl
test/unit/components/VProgressLinear/__snapshots__/VProgressLinear.spec.js.snap
test/unit/components/VTextField/__snapshots__/VTextField.spec.js.snap

Refactor (VProgressLinear): Add -v prefix to progress-lienar classes

---

src/components/VProgressCircular/VProgressCircular.js
src/stylus/components/_progress-circular.styl
test/unit/components/VBtn/__snapshots__/VBtn.spec.js.snap
test/unit/components/VProgressCircular/__snapshots__/VProgressCircular.spec.js.snap

Refactor (VProgressCircular): Add -v prefix to progress-circular classes

---

src/components/VParallax/VParallax.js
src/stylus/components/_parallax.styl
test/unit/components/VParallax/__snapshots__/VParallax.spec.js.snap

Refactor (VParallax): Add v- prefix to parallax classes

---

src/components/VPagination/VPagination.js
src/stylus/components/_pagination.styl
test/unit/components/VPagination/VPagination.spec.js
test/unit/components/VPagination/__snapshots__/VPagination.spec.js.snap

Refactor (VPagination): Add v- prefix to pagination classes

---

src/mixins/overlayable.js
src/stylus/components/_overlay.styl

Refactor overlay: Add v- prefix to overlay class

---

src/stylus/components/_cards.styl

Fix VChip border radius when using it inside a VCard.
I PR it to dev since the next version will be v1.1 and the changes are using the new classes names.
visually

fix(vChip): Border radius when inside a v-card

---

src/components/VTooltip/VTooltip.js
test/unit/components/VTooltip/VTooltip.spec.js
test/unit/components/VTooltip/__snapshots__/VTooltip.spec.js.snap

fix(vTooltip): missing lazy behavior

---

src/stylus/components/_bottom-navs.styl
src/stylus/components/_button-toggle.styl
src/stylus/components/_buttons.styl
src/stylus/components/_snackbars.styl
test/unit/components/VBtn/VBtn.spec.js
test/unit/components/VBtn/__snapshots__/VBtn.spec.js.snap

Moved btn padding from its content to parent, allowing it to be customized by adding `px-*` classes.
`py-*` can't be applied because btn has a fixed height.
By moving this an issue occurs with focused background, so :focus style was also moved to parent.
Allow `.px-*` on btn as a partial fix for #3936
Fix #3452
Visually tested on Chrome 66.0.3359.139 64bits.
No broken tests.
**Important**: To do an IE11 test. VBtn has some fixes for IE11 and I don't have it installed.

fix(btn): Allow VBtn custom padding and fix focus effect

---

index.d.ts
src/components/Vuetify/util/goTo.js
test/unit/components/Vuetify/util/goTo.spec.js

`$vuetify.goTo()` returns now a Promise. 
fixes #3748 
updated jest tests, added new
```vue
<template>
<v-app>
<v-content>
<v-btn @click="goto()">Scroll me</v-btn>
<div style="height: 2000px"></div>
<div id="target">Target</div>
</v-content>
</v-app>
</template>
<script>
methods: {
goto () {
this.$vuetify.goTo('#target').then(alert)
}
}
}
</script>
```

feat: goTo returns a Promise

---

src/components/VSlider/VSlider.js

Added an import to the input-groups stylus file inside the VSlider component
The VSlider needs this styling to correctly display with append-icon and prepend-icon and to remove the focus outline of the component. This is required if you just import this component (a-la-carte)
This has been visually tested by importing the required component. Without the change, the component wasn't displayed correctly. With the change, the component displayed correctly.
<details>
```vue
<template>
<v-app>
<v-container>
<v-slider v-model="value" thumb-label step="10" ticks prepend-icon="timer"></v-slider>
</v-container>
</v-app>
</template>
<script>
data: () => ({
value: 0
})
}
</script>
```
</details>

fix(v-slider): add missing input-groups import

---

src/components/VForm/VForm.js
src/components/VInput/VInput.js
src/mixins/validatable.js
src/stylus/components/_inputs.styl
src/stylus/components/_text-fields.styl
test/unit/components/VCheckbox/__snapshots__/VCheckbox.spec.js.snap
test/unit/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
test/unit/components/VDataTable/__snapshots__/VDataTable.spec.js.snap
test/unit/components/VForm/VForm.spec.js
test/unit/components/VInput/VInput.spec.js
test/unit/components/VInput/__snapshots__/VInput.spec.js.snap
test/unit/components/VOverflowBtn/__snapshots__/VOverflowBtn.spec.js.snap
test/unit/components/VRadioGroup/VRadioGroup.spec.js
test/unit/components/VRadioGroup/__snapshots__/VRadioGroup.spec.js.snap
test/unit/components/VSelect/__snapshots__/VSelect.spec.js.snap
test/unit/components/VSelect/__snapshots__/VSelect2.spec.js.snap
test/unit/components/VSlider/__snapshots__/VSlider.spec.js.snap
test/unit/components/VTextField/VTextField.spec.js
test/unit/components/VTextField/__snapshots__/VTextField.spec.js.snap

- `lazy-validation` wasn't working correctly, it would never validate as true
- setting `error-messages` on a non-dirty input wouldn't change to the error colour
- the extra transitions and colour classes on v-input caused weird effects with the bottom border, I don't think anything broke by removing them
- some tests were invalid, had been changed to make incorrect behaviour pass. these have been reverted
<details>
```vue
<template>
<v-app>
<v-container>
<v-text-field v-model="input" :error-messages="errors" label="input"/>
<v-layout align-center>
<v-flex><v-text-field v-model="error" label="Message" clearable/></v-flex>
<v-btn @click="setError" :disabled="!error">set</v-btn>
<v-btn @click="errors = []" :disabled="!errors">reset</v-btn>
</v-layout>
</v-container>
</v-app>
</template> …
```

fix(VTextField): fix error state with external validation

---

src/components/VDataIterator/index.js
src/mixins/data-iterable.js
test/unit/components/VDataTable/VDataTable.spec.js

reverts e57229d09e33a920575f0fdaa3c4b2edff513d4f to fix #3766
adds $nextTick to fix #3511
emits modified pagination object to fix #3585
closes #3766, closes #3585, closes #3511
manually
https://gist.github.com/nekosaur/4cb1d15efb3019b0ec51f87bfd913d56

fix: data-table issues

---

.travis.yml

chore(ci): run tests and build in parallel

---

src/util/colors.d.ts

Wrapping the color definition in an object.
Solves import warning when using typescript

fix(types): correct colors.d.ts exports

---

src/components/VDatePicker/VDatePickerYears.js

Centers active year in date picker
fixes #3828
<details>
```vue
<template>
<v-app>
<v-layout>
<v-flex xs4>
<v-date-picker type="month" class="mt-3" min="2000-06" max="2050-10" v-model="date"></v-date-picker>
</v-flex>
<v-flex xs4>
<v-date-picker type="month" class="mt-3" min="2017-06" max="2050-10" v-model="date"></v-date-picker>
</v-flex>
<v-flex xs4>
<v-date-picker type="month" class="mt-3" min="1950-06" max="2019-10" v-model="date"></v-date-picker>
</v-flex>
</v-layout>
</v-app>
</template>
<script>
data: () => ({
date: '2018-01',
})
}
</script>
```
</details>

fix: centers active year in date picker

---

src/components/Vuetify/util/goTo.js

fixes #4226
visually
<details>
```vue
<template>
<v-content>
<div style="height: 300px" />
<v-tabs-items v-model="tab">
<v-tab-item id="1">
<v-card style="height: 500px">
test
</v-card>
</v-tab-item>
<v-btn color="error" @click="$vuetify.goTo('.v-tabs__content')">Goto .v-tabs__content</v-btn>
<v-btn color="success" @click="$vuetify.goTo('.v-tabs__items')">Goto .v-tabs__items</v-btn>
<div style="height: 1000px" />
</v-content>
</v-app>
</template>
<script>
data: () => ({
tab: '1'
})
}
</script>
```
</details>

fix(goTo): miscalculated target offset

---

src/components/VGrid/VContent.js
src/stylus/components/_content.styl

refactor(VContent): add v- prefix to classes

---

src/mixins/selectable.js
test/unit/components/VCheckbox/VCheckbox.spec.js

see #3845
fixes #4230
<details>
```vue
<template>
<v-app>
<v-container>
<v-switch v-model="switch1" multiple label="Multiple" value="1"></v-switch>
<v-switch v-model="switch1" multiple label="Multiple" value="2"></v-switch>
<pre>{{ JSON.stringify(switch1) }}</pre>
<v-switch v-model="switch2" label="Shared model" value="1"></v-switch>
<v-switch v-model="switch2" label="Shared model" value="2"></v-switch>
<pre>{{ JSON.stringify(switch2) }}</pre>
<v-switch v-model="switch3" label="Custom true/false values" true-value="on" false-value="off"></v-switch>
<pre>{{ JSON.stringify(switch3) }}</pre>
</v-container>
</v-app>
</template>
<script>
data: () => ({
switch1: null,
switch2: null,
switch3: null
})
}
</script>
```
</details>

fix(selectable): use custom true- and false-value correctly

---

src/components/VMessages/VMessages.js
src/stylus/components/_inputs.styl
src/stylus/components/_messages.styl
src/stylus/generic/_transitions.styl
test/unit/components/VMessages/__snapshots__/VMessages.spec.js.snap

fixes #4248
visually
<details>
```vue
<template>
<v-content>
<v-container>
<v-form ref="form" v-model="valid" lazy-validation>
<v-checkbox label="RTL" v-model="rtl" />
<v-text-field
v-model="name"
label="Name"
counter="30"
hint="I am aligned to left - always"
required
<v-text-field
:rules="emailRules"
label="E-mail"
hint="I am aligned to left - always"
required
<v-select
:items="items"
:rules="[v => !!v || 'Item is required']"
label="Item"
hint="I am aligned to left - always"
required
></v-select>
<v-checkbox
v-model="checkbox"
:rules="[v => !!v || 'You must agree to continue!']"
label="Do you agree?"
required
></v-checkbox>
</v-form> …
```

fix(v-input): hint in rtl

---

src/stylus/components/_text-fields.styl

fixes #4256
visually 
<details>
```vue
<template>
<v-data-table :items="[{}]">
<td>
<v-edit-dialog :return-value.sync="props.item.name" lazy>
Frozen yogurt (normal dialog)
<v-text-field slot="input" v-model="props.item.name" label="Edit" hint="This is a hint" counter></v-text-field>
</td>
<td>
<v-edit-dialog :return-value.sync="props.item.name" lazy large>
Frozen yogurt (large dialog)
<v-text-field slot="input" v-model="props.item.name" label="Edit" counter></v-text-field>
</td>
</template>
</v-app>
</template>
```
</details>

fix(VMessage): added overflow:hidden to prevent scrollbar

---

src/stylus/components/_lists.styl

Align `v-list-tile-action` with button
Fix https://codepen.io/anon/pen/pVYQga?editors=1011
Follow specs
visually
https://codepen.io/anon/pen/pVYQga?editors=1011

fix(v-list): align list action button

---

src/components/VInput/VInput.js

fixes #4279
visually
<details>
```vue
<template>
<v-content>
<v-text-field v-model="message" append-outer-icon="send" label="Message" @click:append-outer="sendMessage" />
</v-content>
</v-app>
</template>
<script>
data: () => ({message: 'Hey!'}),
methods: {
sendMessage: () => alert('ok')
}
}
</script>
```
</details>

fix(VInput): emitting click:append-outer event

---

src/components/VInput/VInput.js
src/components/VTextField/VTextField.js
src/stylus/components/_inputs.styl
src/stylus/components/_messages.styl
src/stylus/components/_select.styl
src/stylus/components/_text-fields.styl
src/stylus/components/_textarea.styl
src/stylus/generic/_transitions.styl
test/unit/components/VSelect/VSelect3.spec.js

Improve input structure to allow for long messages. Added `prepend-inner` slot and icon
Move towards 2.0 spec
fixes #4280 
fixes #4276
fixes #4235 
<details>
```vue
<template>
<v-app>
<v-flex xs12>
<v-radio-group row v-model="selectedStyle">
<v-radio
v-for="type in inputStyles"
:value="type"
:key="type"
:label="type || 'default'"
/>
<v-switch v-model="rtl" label="RTL" />
<v-select v-model="mode" :items="['default', 'readonly', 'disabled']" label="Mode" />
{{ mode === 'readonly' }}
<v-text-field label="Hint" v-model="hint"></v-text-field>
<v-text-field label="Placeholder" v-model="placeholder"></v-text-field>
<v-text-field label="Prefix" v-model="prefix"></v-text-field>
</v-flex>
<v-flex xs12>
<v-text-field …
```

refactor(inputs): allow long messages, inner icons when enclosed

---

src/stylus/components/_tabs.styl
src/stylus/components/_toolbar.styl

Fix https://github.com/vuetifyjs/vuetify/pull/4305 requested changes
visually on Chrome 67
<details>
```vue
<template>
<v-app>
<v-content id="x">
<v-container fluid grid-list-lg class="py-3 px-0">
<v-flex xs12>
<v-toolbar color="cyan" flat>
<v-toolbar-title>Toolbar 1</v-toolbar-title>
</v-toolbar>
</v-flex>
<v-flex xs12>
<v-toolbar color="cyan" flat>
<v-toolbar-title>Toolbar 2</v-toolbar-title>
</v-toolbar>
</v-flex>
<v-flex xs12>
<v-toolbar color="cyan" flat>
<v-toolbar-title>Toolbar 3</v-toolbar-title>
<v-btn icon>
<v-icon>aspect_ratio</v-icon>
</v-btn>
<v-btn icon>
<v-icon>aspect_ratio</v-icon>
</v-btn>
</v-toolbar>
</v-flex>
<v-flex xs12>
<v-toolbar color="cyan" flat>
<v-toolbar-title>Toolbar 4</v-toolbar-title> …
```

feat(v-toolbar): fix tab align and distance between button icons

---

src/components/VCard/VCard.js
src/components/VCard/VCardMedia.js
src/components/VDialog/VDialog.js
src/components/VMenu/VMenu.js
src/components/VNavigationDrawer/VNavigationDrawer.js
src/components/VProgressLinear/VProgressLinear.js
src/components/VStepper/VStepperContent.js
src/components/VTooltip/VTooltip.js
test/unit/components/VDialog/VDialog.spec.js
test/unit/components/VDialog/__snapshots__/VDialog.spec.js.snap

uses `convertToUnit` where applicable
additionally it's possible now to provide height with unit for VProgressLinear (prior to this change only numbers were allowed)
wasn't (except running jest)

refactor: use convertToUnit helper

---

src/stylus/components/_textarea.styl

fixes #4232
visually 
<details>
```vue
<template>
<v-content>
<v-container>
<v-checkbox v-model="rtl" label="rtl" />
<v-textarea v-model="m" label="Description"></v-textarea>
<v-textarea v-model="m" label="Description" outline></v-textarea>
<v-textarea v-model="m" label="Description" box></v-textarea>
<v-textarea v-model="m" label="Description" solo></v-textarea>
<v-textarea v-model="m" label="Description" single-line></v-textarea>
</v-container>
</v-content>
</v-app>
</template>
<script>
data: () => ({m: null}),
computed: {
rtl: {
get () { return this.$vuetify.rtl },
set (rtl) { this.$vuetify.rtl = rtl }
}
}
}
</script>
```
</details>

fix(VTextarea): resize handler position

---

src/stylus/components/_text-fields.styl

fixes #4271
visually
<details>
```vue
<template>
<v-text-field hide-details prefix="Long" single-line label="Label is not aligned properly"></v-text-field>
<v-text-field hide-details prefix="Long" single-line placeholder="Label should be here"></v-text-field>
<v-text-field hide-details prefix="|" single-line label="Label is not aligned properly"></v-text-field>
<v-text-field hide-details prefix="|" single-line placeholder="Label should be here"></v-text-field>
<v-textarea hide-details prefix="|" single-line label="Label is not aligned properly"></v-textarea>
<v-textarea hide-details prefix="|" single-line placeholder="Label should be here"></v-textarea>
<v-text-field hide-details prefix="W" single-line label="Label is not aligned …
```

fix(VInput): prefix width

---

src/components/VTimePicker/VTimePickerClock.js
test/unit/components/VTimePicker/VTimePickerClock.spec.js

fixes #4196
visually, updated unit tests
<details>
```vue
<template>
<v-content>
<v-container>
<v-time-picker v-model="picker" scrollable :allowed-hours="(h) => h % 2 == 0"></v-time-picker>
</v-container>
</v-content>
</v-app>
</template>
<script>
data: () => ({picker: null})
}
</script>
```
</details>

fix(VTimePickerClock): dont switch to minutes if clicked disabled hour

---

src/components/VDialog/VDialog.js
src/components/VMenu/mixins/menu-generators.js
src/components/VTooltip/VTooltip.js
src/mixins/detachable.js
test/unit/components/VDialog/__snapshots__/VDialog.spec.js.snap

Lets you use scoped styles with detachable components
<details>
```vue
<template>
<v-app>
<v-container>
<v-menu>
<v-btn slot="activator">menu</v-btn>
<v-list>
<v-list-tile v-for="i in 5" :key="i">{{ i }}</v-list-tile>
</v-list>
</v-menu>
<v-dialog>
<v-btn slot="activator">dialog</v-btn>
<v-card>
<v-card-text>
Dialog
</v-card-text>
</v-card>
</v-dialog>
<v-tooltip>
<v-btn slot="activator">tooltip</v-btn>
<span>tooltip</span>
</v-tooltip>
</v-container>
</v-app>
</template>
<style scoped>
.v-menu__content,
.v-dialog__content,
.v-tooltip__content {
border: 1px solid red;
box-shadow: none !important;
}
</style>
```
</details>

feat(detachable): pass through scoped style attribute from parent

---

src/stylus/components/_selection-controls.styl

fixes #4314
https://codepen.io/anon/pen/jKarWM
visually
<details>
```vue
<template>
<v-app>
<v-content>
<v-container>
<v-layout>
<v-flex xs12 md6>
<v-checkbox :label="longLabel" />
<v-checkbox :label="shortLabel" />
<v-checkbox :label="longLabel" />
<v-switch :label="longLabel" />
<v-switch :label="shortLabel" />
<v-switch :label="longLabel" />
</v-flex>
<v-flex xs12 md6>
<v-radio-group v-model="radios" :label="longLabel">
<v-radio :label="longLabel" value="radio-1"></v-radio>
<v-radio :label="shortLabel" value="radio-2"></v-radio>
<v-radio-group v-model="radios" :label="longLabel">
<v-radio :label="shortLabel" value="radio-2"></v-radio>
<v-radio :label="longLabel" value="radio-1"></v-radio>
<v-radio-group v-model="radios" :label="shortLabel">
<v-radio …
```

fix(selection-controls): label height and IE11 layout issues

---

src/components/VAlert/VAlert.js
src/stylus/components/_autocompletes.styl
src/stylus/components/_menus.styl
src/stylus/components/_radio-group.styl
src/stylus/components/_range-sliders.styl
src/stylus/components/_sliders.styl
test/unit/components/VAlert/__snapshots__/VAlert.spec.js.snap

Removed unused classes and styles
Moved declarations from `theme($material)` if they don't use `$material`

chore: stylus cleanup

---

src/components/VCarousel/VCarousel.js
src/components/VCarousel/VCarouselItem.js
src/components/VDatePicker/VDatePickerHeader.js
src/components/VDatePicker/mixins/date-picker-table.js
src/components/VPagination/VPagination.js
src/mixins/data-iterable.js
src/stylus/components/_carousel.styl
src/stylus/components/_date-picker-header.styl
src/stylus/components/_date-picker-title.styl
test/unit/components/VCarousel/VCarousel.spec.js
test/unit/components/VCarousel/__snapshots__/VCarousel.spec.js.snap
test/unit/components/VDataIterator/VDataIterator.spec.js
test/unit/components/VDataIterator/__snapshots__/VDataIterator.spec.js.snap
test/unit/components/VDatePicker/VDatePickerHeader.spec.js
test/unit/components/VDatePicker/__snapshots__/VDatePickerHeader.spec.js.snap
test/unit/components/VPagination/VPagination.spec.js
test/unit/components/VPagination/__snapshots__/VPagination.spec.js.snap

fixes #4327
visually
<details>
```vue
<template>
<v-app>
<v-content>
<v-date-picker v-model="date" locale="fa-IR"></v-date-picker>
<v-pagination v-model="pagination" :length="6"></v-pagination>
<div class="elevation-8 ma-4">
<v-data-iterator :items="[1, 2, 3, 4, 5]" :rows-per-page-items="[1]" content-tag="v-layout" row wrap>
<v-flex slot="item" slot-scope="props" xs3>Item: {{ props.item }}</v-flex>
</v-data-iterator>
</div>
<v-tabs dark color="cyan" show-arrows>
<v-tab v-for="i in 30" :key="i">Item {{ i }}</v-tab>
</v-tabs>
<v-carousel color="primary" interval="1000">
<v-carousel-item v-for="carouselImage in carouselImages" :key="carouselImage" :src="carouselImage"></v-carousel-item>
</v-carousel>
</v-content>
</v-app>
</template>
<script>
data: () => ({
date: …
```

fix(RTL): next/prev icons and transitions in picker, pagination, carousel, iterable

---

src/components/VCombobox/VCombobox.js
test/unit/components/VCombobox/VCombobox.spec.js

enables `return-object` by default on v-combobox
The component's behaviour doesn't really make sense without it.
resolves #4345
<details>
```vue
<template>
<v-app>
<v-container>
<v-layout column fill-height>
<v-combobox v-model="selected" v-bind="{ items, multiple }" chips :delimiters="[',']"/>
<v-spacer/>
<pre>{{ selected }}</pre>
</v-layout>
</v-container>
</v-app>
</template>
<script>
data: () => ({
selected: ['foo', 'value2'],
items: [
{ text: 'text1', value: 'value1' },
{ text: 'text2', value: 'value2' },
{ text: 'text3', value: 'value3' },
'string1',
'string2',
'string3'
],
multiple: true
})
}
</script>
```
</details>

enh(VCombobox): enable return-object by default

---

src/components/VRadioGroup/VRadio.js
src/components/VRadioGroup/VRadioGroup.js
test/unit/components/VRadioGroup/VRadio.spec.js
test/unit/components/VRadioGroup/VRadioGroup.spec.js

Makes radios disabled/readonly when v-radio-group is disabled/readonly
see #4349
unit
<details>
```vue
<template>
<v-radio-group v-model="radios" label="Normal">
<v-radio label="Radio 1" value="radio-1"></v-radio>
<v-radio label="Radio 2" value="radio-2"></v-radio>
<v-radio-group v-model="radios" readonly label="Readonly">
<v-radio label="Radio 1" value="radio-1"></v-radio>
<v-radio label="Radio 2" value="radio-2"></v-radio>
<v-radio-group v-model="radios" disabled label="Disabled">
<v-radio label="Radio 1" value="radio-1"></v-radio>
<v-radio label="Radio 2" value="radio-2"></v-radio>
</v-container>
</v-app>
</template>
<script>
data: () => ({
radios: 'radio-1'
})
}
</script>
``` …

fix(VRadio): inject disabled/readonly from VRadioGroup

---

src/components/VTabs/VTabItem.js
src/components/VTabs/VTabsItems.js

Change how active tab is derived
`v-tabs` already determines active index
fixes #4397
none
<details>
```vue
<template>
<div id="app">
<div>
<v-tabs
color="cyan"
dark
slider-color="yellow"
>
<v-tab
v-for="n in 3"
:key="n"
ripple
>
Item {{ n }}
</v-tab>
</v-tabs>
<v-tabs-items v-model="model">
<v-tab-item
v-for="n in 3"
:key="n"
>
<v-card flat>
</v-card>
</v-tab-item>
</div>
</v-app>
</div>
</template>
<script>
data () {
return {
model: 2,
text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
}
}, …
```

fix(v-tabs): update active comparison

---

src/stylus/components/_buttons.styl

see https://github.com/vuetifyjs/vuetify/issues/3400#issuecomment-399365365
visually
<details>
```vue
<template>
<v-content>
<v-btn>btn</v-btn>
<v-btn color="success">btn</v-btn>
<v-btn depressed>btn</v-btn>
<v-btn depressed color="success">btn</v-btn>
<v-btn flat>btn</v-btn>
<v-btn flat color="success">btn</v-btn>
<v-btn fab flat>btn</v-btn>
<v-btn fab flat color="success">btn</v-btn>
</v-content>
</v-app>
</template>
```
</details>

fix: v-btn classes cleanup

---

src/components/VChip/VChip.js
src/stylus/components/_chips.styl
test/unit/components/VChip/VChip.spec.js

Prevents disabled chips to be focused, disabled "close" icon in disabled chips, fixes the text color, adds test ensuring that close icon is available in disabled chips
fixes #4442
visually 
<details>
```vue
<template>
<v-container>
<v-chip>Default</v-chip>
<v-chip disabled>Disabled</v-chip>
<v-chip close>Default, close</v-chip>
<v-chip close disabled>Disabled, close</v-chip>
<v-chip v-for="color in ['blue', 'yellow', 'red', 'green']" :key="color" :color="color" disabled>{{ color }}</v-chip>
<v-chip dark v-for="color in ['blue', 'yellow', 'red', 'green']" :key="color" :color="color" disabled>{{ color }}</v-chip>
<v-autocomplete multiple v-model="chips" :items="items" label="Chips" chips deletable-chips>
<template slot="selection" slot-scope="data">
<v-chip …
```

fix(VChip): styles for disabled chips

---

src/stylus/components/_text-fields.styl

fixes #4478
visually
<details>
```vue
<template>
<v-app>
<v-content>
<v-container>
<div><v-text-field prefix="X" suffix="append text"></v-text-field></div>
<div><v-menu><v-text-field slot="activator" prefix="X" suffix="append text"></v-text-field></v-menu></div>
<div><v-dialog><v-text-field slot="activator" prefix="X" suffix="append text"></v-text-field></v-dialog></div>
</v-container>
</v-content>
</v-app>
</template>
```
</details>

fix(VTextField): prefix/suffix cursor

---

src/components/VDialog/VDialog.js
src/mixins/overlayable.js
src/stylus/components/_overlay.styl

fixes #4466
visually
<details>
```vue
<template>
<v-app>
<v-container>
<v-btn>Click me when dialog is open</v-btn>
<v-dialog v-model="d1" persistent @keydown.esc="d1 = false">
<v-btn slot="activator">Open persistent dialog</v-btn>
<v-card><v-card-text>Close with ESC</v-card-text></v-card>
</v-dialog>
<v-dialog v-model="d2" persistent hide-overlay @keydown.esc="d2 = false">
<v-btn slot="activator">Open persistent dialog (hide-overlay)</v-btn>
<v-card><v-card-text>Close with ESC</v-card-text></v-card>
</v-dialog>
<v-dialog v-model="d3" @keydown.esc="d3 = false">
<v-btn slot="activator">Open dialog</v-btn>
<v-card><v-card-text>Close with ESC</v-card-text></v-card>
</v-dialog>
<v-dialog v-model="d4" hide-overlay @keydown.esc="d4 = false">
<v-btn slot="activator">Open dialog …
```

fix(VDialog): use overlay with persistent and hide-overlay props

---

src/stylus/components/_tabs.styl

fixes #4489
<details>
```vue
<template>
<v-app>
<v-container>
Default, no overflow <v-tabs><v-tab v-for="i in 5" :href="'#tab-' + i" :key="i">{{ i === 3 ? 'blah blah' : i }}</v-tab></v-tabs>
Centered, no overflow <v-tabs centered><v-tab v-for="i in 5" :href="'#tab-' + i" :key="i">{{ i === 3 ? 'blah blah' : i }}</v-tab></v-tabs>
Fixed, no overflow <v-tabs fixed-tabs><v-tab v-for="i in 5" :href="'#tab-' + i" :key="i">{{ i === 3 ? 'blah blah' : i }}</v-tab></v-tabs>
Grow, no overflow <v-tabs grow><v-tab v-for="i in 5" :href="'#tab-' + i" :key="i">{{ i === 3 ? 'blah blah' : i }}</v-tab></v-tabs>
Default, overflow <v-tabs><v-tab v-for="i in 100" :href="'#tab-' + i" :key="i">{{ i === 3 ? 'blah blah' : i }}</v-tab></v-tabs>
Centered, overflow <v-tabs centered><v-tab v-for="i in 100" …
```

fix(VTabs): tab width in IE11

---

src/stylus/generic/_transitions.styl

Fix double bounce that can happen on edge and firefox. I guess there some race condition between enter and enter-to transition that was causing this.
https://github.com/vuetifyjs/vuetify/issues/4154
visually 
<details>
```vue
<template>
<v-stepper v-model="e1">
<v-stepper-step :complete="e1 > 1" step="1">Name of step 1</v-stepper-step>
<v-stepper-step :complete="e1 > 2" step="2">Name of step 2</v-stepper-step>
<v-stepper-step step="3">Name of step 3</v-stepper-step>
</v-stepper-header>
<v-stepper-items>
<v-stepper-content step="1">
<v-card color="grey lighten-1" class="mb-5" height="200px"></v-card>
<v-btn color="primary" @click.native="e1 = 2">Continue</v-btn>
<v-btn flat>Cancel</v-btn> …
```

fix double bounce on stepper change step

---

src/locale/pl.js

feat(locale): polish

---

src/components/VInput/VInput.js
src/util/console.ts
test/unit/components/VInput/VInput.spec.js
test/unit/components/VSelect/VSelect2.spec.js
test/unit/components/VTextField/VTextField.spec.js

Fixes #4265 
Help with some first issues
Upgrading tests
- [ x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and breaking changes).

4265 update tests to use new icon events

---

src/stylus/components/_buttons.styl
src/stylus/components/_toolbar.styl

Fixes #3412 
It has been not tested because it's a CSS issue and I'm not sure how to do it. If you provide some instructions on how to test it I'd happily do it.

Set to v-btn shrink factor to 0 on toolbar

---

src/components/VBadge/VBadge.ts
src/components/VBtn/VBtn.ts
src/components/VBtnToggle/VBtnToggle.ts
src/mixins/bootable.ts
src/mixins/button-group.ts
src/mixins/registrable.ts
src/mixins/toggleable.ts
src/util/mixins.ts

fix(types): prevent type leak in Toggleable, add $el to VBtn

---

src/stylus/components/_lists.styl

Fixes #3669 
visually
<details>
<template>
<v-list two-line>
<v-list-tile>
<v-list-tile-title>some title here</v-list-tile-title>
<v-list-tile-sub-title> sub title here</v-list-tile-sub-title>
</v-list-tile>
<v-list-tile>
<v-list-tile-title>some title here</v-list-tile-title>
<v-list-tile-sub-title> sub title here</v-list-tile-sub-title>
</v-list-tile>
<v-list-tile to='https://vuetifyjs.com'>
<v-list-tile-title>some title here</v-list-tile-title>
<v-list-tile-sub-title> sub title here</v-list-tile-sub-title>
</v-list-tile>
<v-list-tile to='https://vuetifyjs.com' …

User-select: none only when ListTile is a link

---

src/components/VExpansionPanel/VExpansionPanelContent.ts
src/stylus/components/_expansion-panel.styl
test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanel.spec.js.snap
test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanelContent.spec.js.snap

Fixes #4629 
unit
<details>
```vue
```
</details>

Stick to naming convetions v-header__icon

---

src/stylus/components/_toolbar.styl

Fixes #3974
visually
<details>
<template>
<v-toolbar dark color="primary" extended>
<v-toolbar-side-icon></v-toolbar-side-icon>
<v-toolbar-title class="white--text" slot="extension">Title</v-toolbar-title>
<v-btn icon>
<v-icon>search</v-icon>
</v-btn>
<v-btn icon>
<v-icon>apps</v-icon>
</v-btn>
<v-btn icon>
<v-icon>refresh</v-icon>
</v-btn>
<v-btn icon>
<v-icon>more_vert</v-icon>
</v-btn>
</v-toolbar>
</v-app>
</template>
<script>
data: () => ({})
};
</script>
</details>

Add removed style to shift text on expansion toolbar

---

src/locale/fr.js

Add french locale in `src/locale/fr.js`

feat: add french locale

---

src/locale/pt.js

feat(locale): portuguese

---

src/locale/de.js

feat(locale): german

---

src/locale/gr.js

feat(locale): greek

---

src/components/VSlider/VSlider.js
test/unit/components/VSlider/VSlider.spec.js

Fixed roundValue method of VSlider component (added offset).
Fixes #4575
Unit tests + visually
<details>
```vue
<template>
<v-app>
<v-container>
<v-slider min='45' :step='step' thumb-label v-model='value'></v-slider>
{{ value }}
</v-container>
</v-app>
</template>
<script>
data: () => ({
step: 2,
value: 45
})
}
</script>
<style>
.speed-dial {
top: 0% !important;
}
</style>
```
</details>

Fixed slider value rounding. Fixes #4575

---

src/components/VApp/mixins/app-theme.js
src/components/Vuetify/mixins/options.js
src/util/colorUtils.ts
src/util/theme.ts
test/unit/components/VApp/__snapshots__/VApp.spec.js.snap
types/index.d.ts
types/test/plugin.ts

resolves #4408
<details>
```js
import colors from '../src/util/colors'
Vue.use(Vuetify, {
theme: {
primary: colors.green
}
})
```
</details>

feat(theme): accept color objects

---

BACKERS.md

<details>
```vue
```
</details>

would prefer my org name

---

src/stylus/components/_buttons.styl

fix: #4825 - the icons aren't center aligned in floating fab buttons.
for details check - https://github.com/vuetifyjs/vuetify/issues/4825#issuecomment-411965580
fix: #4825 
unit
<details>
```vue
```
</details>

fix: #4825 - icon alignment in fab broken

---

src/stylus/components/_data-table.styl

Fixes #4826 
I have also removed the hacking looking margin. Doesn't seem to disrupt the expected functionality.
Unit tested. Ran locally.
<details>
```vue
```
</details>

fix: #4826 - Data Table Progress bar overlaps table header border

---

src/locale/fr.js

Fix french misspells
Because it has to ;)   
The 3rd line is a question of taste, it really sounds better, you can keep "Objet" but at least add a "s" at the end.
Other lines are just mistakes.
- [] I have created a PR in the [documentation](https://github.com/vuetifyjs/vuetifyjs.com) with the necessary changes.

fix french misspellings

---

src/locale/nl.js

Just a language change
It adds the dutch language to vuetify
Just tested
```vue
import Vuetify from 'vuetify'
import nl from './i18n/vuetify/nl'
Vue.use(Vuetify, {
lang: {
locales: { nl },
current: 'nl'
}
})
```
</details>

Created dutch (nl) translation file

---

src/stylus/components/_data-table.styl

Fixes #4892 
visually 
<details>
```vue
```
</details>

Fix IE11 issue where select is too tall in data-table

---

src/stylus/components/_toolbar.styl

https://codepen.io/anon/pen/rrXomw?editors=1000
fixes #2557
playground
<details>
```vue
<template>
<v-toolbar fill-height align-center m-0 p-0>
<v-btn flat>Button</v-btn>
<v-btn icon><v-icon>check</v-icon></v-btn>
<v-btn fab><v-icon>check</v-icon></v-btn>
<v-menu><v-btn slot="activator" flat>Button</v-btn></v-menu>
<v-menu><v-btn slot="activator" icon><v-icon>check</v-icon></v-btn></v-menu>
<v-menu><v-btn slot="activator" fab><v-icon>check</v-icon></v-btn></v-menu>
</v-toolbar>
</v-app>
</template>
```
</details>

fix: icon button's height in toolbar items

---

src/stylus/components/_sliders.styl

You may ignore this @KaelWD if this is not the correct fix, I was just trying it myself
https://github.com/vuetifyjs/vuetify/issues/4891
visually
<details>
```vue
<v-range-slider 
v-model="slider1Val" 
label="Slider without thumb-label" 
:step="5" 
ticks
:max="80" 
hide-details
></v-range-slider>
<v-range-slider 
v-model="slider2Val" 
label="Slider with thumb-label" 
:step="5" 
ticks thumb-label 
:max="80" 
hide-details
></v-range-slider>
<v-range-slider 
v-model="slider1Val" 
label="Slider without thumb-label" 
:step="5" 
ticks
:max="80" 
hide-details
></v-range-slider>
```
</details>

Fix(V-slider): missing margin-top on input slider w/ thumb

---

src/locale/fa.ts

feat(locale): farsi

---

src/stylus/components/_select.styl
src/stylus/components/_text-fields.styl

fixes #4456
Remove height declaration in input slot to avoid flex bug
fixes #4456
visually
https://codepen.io/jameycribbs/pen/WymRNP?editors=1000

fix(v-text-field/v-select): remove explicit height

---

src/stylus/elements/_global.styl

Material design spec requires a scrollbar to be shown every time there's an overflow of items. The spec does not necessarily mention how to style the scrollbar but an example is given here - //https://material.io/design/components/menus.html#behavior
I have tweaked the colors to match vuetify's default light theme.
An example can be found here. - https://codepen.io/praveenpuglia/pen/LBqmeb
Manual, visual test on different platforms and devices.
<details>
```vue
<template>
<v-app dark id="inspire">
<v-container>
<v-data-table
:loading="true"
>
<v-progress-linear slot="progress" color="blue" indeterminate></v-progress-linear>
<td class="text-xs-right">{{ …
```

show custom scrollbars for overflowing containers

---

src/components/VRating/VRating.ts
src/stylus/components/_rating.styl

Added dense prop to v-rating
visually with markup
<details>
```vue
<template>
<boilerplate>
Regular
<v-rating v-model="rating"></v-rating>
Dense
<v-rating v-model="rating" dense color="yellow darken-1" background-color="yellow darken-1"></v-rating>
</boilerplate>
</template>
<script>
data: () => ({
rating: 0
}),
methods: {
genColor (i) {
const colors = ['green', 'purple', 'orange', 'indigo', 'red']
return colors[i]
}
}
}
</script>
```
</details>

feat: added dense prop to v-rating

---

src/stylus/generic/_transitions.styl

Fixes a typo in `_transitions.styl`.
Fixes [#4758](https://github.com/vuetifyjs/vuetify/issues/4758)

Fix #4758: Typo in _transitions.styl

---

src/locale/ca.ts

Add catalan locale file
<details>
```vue
```
</details>
- [x ] New feature (non-breaking change which adds functionality)

Add catalan locale

---

src/locale/it.ts

feat(locale): italian

---

src/components/VStepper/VStepper.js
src/components/VStepper/VStepperContent.js
test/unit/components/VStepper/VStepperContent.spec.js

Provide `isVertical` from `VStepper` to `VStepperContent` in order to correctly initialize `isVertical` state of `VStepperContent`
Fixes #3904
visually
<details>
```vue
<template>
<v-app class="ma-4">
<v-stepper v-model="step" vertical>
<template v-for="i of steps">
<v-stepper-step :complete="step > i" :step="i">
Step {{i}}
<v-stepper-content :step="i">
Some text
</v-stepper-content>
</template>
</v-stepper>
</v-app>
</template>
<script>
data () {
return {
step: 0,
steps: 2,
}
},
async mounted() {
const sleep = milliseconds => new Promise(resolve => setTimeout(resolve, milliseconds));
await sleep(100);
this.steps = 5;
}
}
</script>
```
</details>

Fix #3904: dividers are not shown in dynamic vertical stepper

---

src/components/VItemGroup/VItemGroup.ts
src/components/VTabs/VTab.js
src/components/VTabs/VTabs.js
src/components/VTabs/mixins/tabs-computed.js
src/components/VTabs/mixins/tabs-props.js
src/components/VTabs/mixins/tabs-watchers.js
src/mixins/groupable.ts
src/mixins/proxyable.ts
test/unit/components/VItemGroup/VItem.spec.js
test/unit/components/VItemGroup/VItemGroup.spec.js
test/unit/components/VTabs/VTab.spec.js
test/unit/components/VTabs/VTabs.spec.js

Convert `v-tabs` to use new `v-item-grup`
DRY up the codebase
jest
<details>
```vue
<template>
<boilerplate>
<pre>{{ tab }}</pre>
<v-btn to="/page1">To</v-btn>
<v-tabs v-model="tab">
<template v-for="val in ['foo', 'bar']">
<v-tab :href="`#${val}`" :key="`${val}-link`">{{ val }}</v-tab>
<v-tab-item :id="val" :key="`${val}-item`">{{ val }}</v-tab-item>
</template>
</v-tabs>
</boilerplate>
</template>
<script>
data: () => ({
tab: null
})
}
</script>
```
</details>

feat(v-tabs): convert to use item/group

---

src/components/VTabs/VTab.js
src/components/VTabs/VTabItem.js
src/components/VTabs/VTabs.js
src/components/VTabs/VTabsItems.js
src/components/VTabs/mixins/tabs-watchers.js
src/components/VWindow/VWindowItem.ts
src/stylus/components/_tabs.styl
test/unit/components/VTabs/VTab.spec.js
test/unit/components/VTabs/VTabItem.spec.js
test/unit/components/VTabs/VTabs.spec.js
test/unit/components/VTabs/VTabsItems.spec.js
test/unit/components/VTabs/__snapshots__/VTabs.spec.js.snap
test/unit/components/VWindow/VWindow.spec.js
test/unit/components/VWindow/VWindowItem.spec.js

Update `v-tabs` to use `v-window`. Looking for feedback on the abstraction and figuring out why the avoriaz no longer picks up the VTabsItems constructor
DRYing up the codebase
jest / visually
<details>
```vue
<template>
<v-app>
<div class="text-xs-center mt-3">
<v-btn @click="next">next tab</v-btn>
</div>
<div>
<v-tabs
v-model="active"
color="cyan"
dark
slider-color="yellow"
>
<v-tab
v-for="n in 3"
:key="n"
ripple
>
Item {{ n }}
</v-tab>
<v-tab-item
v-for="n in 3"
:key="n"
>
<v-card flat>
<v-card-text v-for="j in n" :key="`text-${j}`">{{ text }}</v-card-text>
</v-card>
</v-tab-item>
</v-tabs>
</div>
</v-app>
</template>
<script>
data () {
return {
active: 1,
text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do …
```

feat(v-tabs): update to use v-window

---

package.json

Adds new lint:fix script
Fixes 5157
Added lint errors in a .js file and noticed it get fixed automatically
No functional testing required.

Add lint:fix npm script

---

src/components/VPagination/VPagination.ts
test/unit/components/VPagination/VPagination.spec.js
test/unit/components/VPagination/__snapshots__/VPagination.spec.js.snap

Handle cases in VPagination when current selected page is the last before dots, or the first after dots.
Here is screenshot of how it looks now (see for example third line):
Fixes #4760
unit (existing snapshots were updated) and visually
<details>
```vue
<template>
<v-app>
<v-container>
<v-layout>
<v-flex xs6>
<h1 class="display-1 mb-3">totalVisible=7 (odd)</h1>
<v-pagination
v-for="i in 9"
:value="i"
:length="9"
:total-visible="7"
></v-pagination>
</v-layout>
</v-flex>
<v-flex xs6>
<h1 class="display-1 mb-3">totalVisible=8 (even)</h1>
<v-pagination
v-for="i in 9"
:value="i"
:length="9"
:total-visible="8"
></v-pagination>
</v-layout>
</v-flex>
</v-layout>
</v-container>
</v-app>
</template>
<script>
export default {}
</script>
```
</details>

Fix #4760: show next pagination page if current page is last

---

src/locale/hu.ts

hungarian language support
n/a
n/a

added hungarian language

---

src/mixins/data-iterable.js

Iterable's rows-per-page selector takes the theme from the app instead of the component (data-iterable, data-table)
https://codepen.io/anon/pen/pOBLaO
visually
<details>
```vue
<template>
<v-app :dark="dark">
<v-content>
<v-container>
<v-switch label="Dark" v-model="dark"></v-switch>
<div class="headline mt-5">No theme</div>
<v-data-table :headers="headers" :items="desserts">
<td><v-edit-dialog>Click<v-text-field slot="input"></v-text-field></v-edit-dialog></td>
<td><v-edit-dialog large>Click<v-text-field slot="input"></v-text-field></v-edit-dialog></td>
</template>
<div class="headline mt-5">Dark</div>
<v-data-table dark :headers="headers" :items="desserts"> …
```

fix(data-iterable): rows-per-page selector not inheriting theme

---

src/components/VTabs/VTab.js

Just a minor fix for the href attribute on v-tab when using hash urls. Originally it prevents default, but I believe that the intention was to only prevent default when the url is exactly '#'. In the case of using hash urls for the tab, this will not work. 
I had this issue open for a while to see why this code was here in the first place, after no feedback decided to fix it as I am going live with a feature that is using this soon.
https://github.com/vuetifyjs/vuetify/issues/4784
I have tested that it works visually in my project, not quite sure how to write a test for this one.
<details>
```vue
<template lang="pug">
.main
v-tabs.shadow(v-model="activeTab" slider-color="primary" fixed-tabs)
v-tab(v-for="tab in tabs" :key="tab.name" :href="`#${tab.name}`")
| {{ $t(tab.title) }} …
```

fix(v-tab): anchor hash routing

---

src/mixins/data-iterable.js

Localize presentation of numbers based on current locale in data-iterable mixin.
To localize numbers in v-data-table and v-data-iterator pagination. 
visually
<details>
```vue
<template>
<v-app dark>
<v-content>
<v-container fill-height>
<v-layout column
justify-space-between>
<v-data-table :headers="headers"
class="elevation-1">
<template slot="items"
slot-scope="props">
<td class="text-xs-right">{{ props.item.iron }}</td>
</template>
<v-data-iterator :items="desserts" …
```

Localize numbers in pagination

---

src/components/VDatePicker/VDatePicker.js
test/unit/components/VDatePicker/VDatePicker.date.spec.js

Allows customized formatting of weekdays
fixes #5020
visually, unit
<details>
```vue
<template>
<v-app>
<v-content>
<v-date-picker v-model="date" :weekday-format="weekdayFormat"></v-date-picker>
</v-content>
</v-app>
</template>
<script>
data() {
return {
date: null,
};
},
methods: {
weekdayFormat: dateString => new Date(`${dateString}T00:00:00+00:00`).toLocaleDateString('en' || undefined, { weekday: 'short', timeZone: 'UTC' })
}
};
</script>
```
</details>

feat(VDatePicker): add weekdayFormat prop

---

src/components/VDataTable/VDataTable.js

Fixes https://github.com/vuetifyjs/vuetify/issues/4586
I passed `customerFilter` to v-data-table
https://codepen.io/ittus/pen/PdBYyM

Fix table filter when there is dot in field name

---

packages/vuetify/src/stylus/components/_treeview.styl

fixes #5462
visually
<details>
```vue
<template>
<v-content>
<v-container>
<v-btn @click="switchDirection()" color="primary" xs12>
Switch
</v-btn>
<v-treeview :items="items" open-all></v-treeview>
</v-container>
</v-content>
</v-app>
</template>
<script>
methods: {
switchDirection() {
this.$vuetify.rtl = !this.$vuetify.rtl;
}
},
data: () => ({
items: [
{
id: 1,
name: "Applications :",
children: [
{ id: 2, name: "Calendar : app" },
{ id: 3, name: "Chrome : app" },
{ id: 4, name: "Webstorm : app" }
]
},
{
id: 5,
name: "Documents :",
children: [
{
id: 6,
name: "vuetify :",
children: [
{
id: 7,
name: "src :",
children: [
{ id: 8, name: "index : ts" },
{ id: 9, name: "bootstrap : ts" }
]
}
]
},
{
id: 10,
name: "material2 :",
children: [
{
id: 11,
name: …
```

fix(VTreeview): rtl mode

---

packages/vuetify/src/stylus/components/_lists.styl

@M6stafa (#4745)
fixes #4606
visually
<details>
```vue
<template>
<v-app>
<v-content>
<v-container>
<v-select :items="['בדיקה 1', 'בדיקה 2']" label="בדיקה"></v-select>
<v-list>
<v-list-tile>
<v-list-tile-action><v-icon>check</v-icon></v-list-tile-action>
<v-list-tile-title>Title</v-list-tile-title>
<v-list-tile-sub-title>Subtitle</v-list-tile-sub-title>
<v-list-tile-action><v-icon>block</v-icon></v-list-tile-action>
</v-list-tile>
</v-list>
</v-container>
</v-content>
</v-app>
</template>
<script>
mounted () {
}
}
</script>
```
</details>

fix(VList): rtl

---

packages/vuetifyjs.com/src/pages/getting-started/QuickStartPage.vue
packages/vuetifyjs.com/src/themes/blog-starter/index.html
packages/vuetifyjs.com/src/themes/parallax-starter/index.html

Add all font weight on themes and quick start page
Missing font weight in some places
none
<details>
```vue
```
</details>

fix: font weight on themes and quick start page

---

packages/vuetifyjs.com/src/lang/en/getting-started/QuickStart.json
packages/vuetifyjs.com/src/lang/pt-BR/getting-started/QuickStart.json
packages/vuetifyjs.com/src/pages/getting-started/QuickStartPage.vue

Add an example of how to async import fonts.
Closes https://github.com/vuetifyjs/vuetifyjs.com/issues/505
none
<details>
```vue
```
</details>

feat: add how to async load fonts

---

.github/PULL_REQUEST_TEMPLATE.md

chore: update PR template to include docs check in the checklist

---

packages/vuetify/src/stylus/components/_dialogs.styl

Set `flex-basis: 100%` on `.v-card` of a dialog when it's set to scrollable.
When a modal contains a tab component and if a tab contains a certain amount of content it may trigger a horizontal scroll bar rather than wrap in IE11. 
The issue is when dealing with nested flexbox containers in IE, text generally will not wrap using `flex-basis: auto;` More details about this issue can be found - https://github.com/philipwalton/flexbugs/issues/170
Fixes #5488 
visually 
<details>
```vue
```
</details>

Fix IE11 issue with nested flexbox on scrollable dialog

---

packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
tslint.json

```
vuetify: [tslint] C:/cygwin64/home/Jacek/vuetifyjs/vuetify/packages/vuetify/src/components/VImg/VImg.ts:154:11
vuetify: [tslint] ERROR: 154:11  no-floating-promises           Promises must be handled appropriately
vuetify: [tslint]
vuetify: [tslint] C:/cygwin64/home/Jacek/vuetifyjs/vuetify/packages/vuetify/src/components/VTreeview/VTreeview.ts:305:9
vuetify: [tslint] ERROR: 305:9   no-floating-promises           Promises must be handled appropriately
vuetify: [tslint]
vuetify: [tslint] C:/cygwin64/home/Jacek/vuetifyjs/vuetify/packages/vuetify/src/components/VTreeview/VTreeviewNode.ts:138:14
vuetify: [tslint] ERROR: 138:14  no-inferred-empty-object-type  Explicit type parameter needs to be provided to the constructor
vuetify: [tslint] ERROR: 186:13  no-floating-promises …
```

fix: typescript lint errors

---

packages/vuetify/src/stylus/components/_treeview.styl

fixes #5534
visually
<details>
```vue
<template>
<v-app>
<v-treeview :items="items"></v-treeview>
</v-app>
</template>
<script>
data: () => ({
items: [
{
id: 19,
name: 'Videos :',
children: [
{
id: 20,
name: 'Tutorials :',
children: [
{ id: 21, name: 'Basic layouts : mp4' },
{ id: 22, name: 'Advanced techniques : mp4' },
{ id: 23, name: 'All about app : dir' }
]
},
{ id: 24, name: 'Intro : mov' },
{ id: 25, name: 'Conference introduction : avi' }
]
}
]
}),
mounted () {
}
}
</script>
```
</details>

fix(VTreeview): arrow direction in rtl

---

packages/vuetifyjs.com/src/examples/data-tables/crud.vue
packages/vuetifyjs.com/src/examples/data-tables/editdialog.vue
packages/vuetifyjs.com/src/examples/data-tables/expand.vue
packages/vuetifyjs.com/src/examples/data-tables/footer.vue
packages/vuetifyjs.com/src/examples/data-tables/noData.vue
packages/vuetifyjs.com/src/examples/data-tables/paginate.vue
packages/vuetifyjs.com/src/examples/data-tables/select.vue
packages/vuetifyjs.com/src/examples/data-tables/standard.vue
packages/vuetifyjs.com/src/lang/en/components/DataTables.json

removed unnecessary things, standardized props, and stuff
make it easier for users to copy examples and use them directly
manually
<details>
```vue
```
</details>

 docs(v-data-table): simplify and standardize examples

---

packages/vuetify/src/mixins/menuable.js

Modify menuable.js to support scrollX
Fixes #5114 
Playground.vue and fixed version of Codepen from the issue
https://codepen.io/anon/pen/EOaBGe?editors=1010
<details>
```vue
<template>
<v-app>
<div class="text-xs-center">
<v-menu offset-y>
<v-btn
slot="activator"
dark
>
Dropdown
</v-btn>
<v-list>
<v-list-tile
:key="index"
@click=""
>
<v-list-tile-title>{{ item.title }}</v-list-tile-title>
</v-list-tile>
</v-list>
</v-menu>
</div>
</v-app>
</template>
<script>
data: () => ({
items: [
{ title: 'Click Me' },
{ title: 'Click Me' },
{ title: 'Click Me' },
{ title: 'Click Me 2' }
]
})
}
</script>
<style>
html {
overflow-x: auto !important;
}
body {
min-width: 1300px;
}
</style>
```
</details>
I'm new to Vue, Vuetify and also git. …

Fix: v-menu position problem with horizontal scrolling

---

packages/vuetify/src/stylus/components/_text-fields.styl

fixes #5555
visually
<details>
```vue
<template>
<v-form>
<v-container>
<div style="width: 630px">
<v-layout row>
<v-flex xs4 elevation-1 ma-2>
<v-text-field prepend-icon="check" label="lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll" />
<v-text-field prepend-icon="check" box label="lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll" />
<v-text-field prepend-icon="check" outline label="lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll" />
</v-flex>
<v-flex xs4 elevation-1 ma-2>
<v-text-field label="lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll" />
<v-text-field box label="lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll" /> …
```

fix(VTextField): use available space for active label

---

packages/vuetify/src/components/VSelect/VSelect.js

fixes #5560
visually
<details>
```vue
<template>
<v-container>
<v-btn @click="showDialog = true">Open dialog</v-btn>
</v-container>
<v-dialog v-model="showDialog" max-width="300px" persistent @keydown.esc.prevent="showDialog = false">
<v-toolbar dark class="blue-grey lighten-5 grey--text text--darken-2 elevation-0">
<v-toolbar-title class="pt-1">Dialog</v-toolbar-title>
<v-tooltip top nudge-top="6" class="ml-2">
<span slot="activator">
<v-btn icon light @click="showDialog = false">
</v-btn>
</span>
<span>Close</span>
</v-tooltip>
</v-toolbar>
<v-layout>
<v-select
:items="['one', 'two', 'three', 'four', 'five']"
label="Number"
></v-select>
</v-layout>
</v-dialog>
</v-app>
</template>
<script>
export …
```

fix(VSelect): stop keydown.esc propagation

---

packages/vuetify/src/stylus/components/_lists.styl

fixes #5553
visually
<details>
```vue
<template>
<v-content>
<v-container>
<v-list two-line style="width: 350px">
<v-list-tile>
<v-list-tile-action><v-checkbox hint="Hint" persistent-hint /></v-list-tile-action>
<v-list-tile-content><v-text-field hint="Hint" persistent-hint /></v-list-tile-content>
<v-list-tile-action><v-checkbox hint="Hint" persistent-hint /></v-list-tile-action>
</v-list-tile>
<v-list-tile>
<v-list-tile-action><v-radio hint="Hint" persistent-hint /></v-list-tile-action>
<v-list-tile-content><v-checkbox hint="Hint" persistent-hint /></v-list-tile-content>
<v-list-tile-action><v-checkbox hint="Hint" persistent-hint /></v-list-tile-action>
</v-list-tile>
</v-list>
</v-container>
</v-content>
</v-app>
</template>
```
</details>

fix(VList): hide input messages only when in .v-list__tile__action

---

packages/vuetify/src/stylus/components/_data-table.styl

this will center selection-controls correctly (checkboxes) when using it inside data-tables,
see current behaviour here: <https://codepen.io/anon/pen/jQWggG?&editors=101>
there is a small padding on top that pushes the selection-control down just a little bit
visually
<details>
```vue
<template>
<v-app>
<v-data-table
:pagination.sync="pagination"
select-all
>
<template slot="headers" slot-scope="props">
<tr>
<th>
<v-checkbox
:input-value="props.all"
:indeterminate="props.indeterminate"
primary
hide-details
@click.native="toggleAll"
></v-checkbox>
</th>
<th
v-for="header in props.headers"
:key="header.text"
:class="['column sortable', pagination.descending ? 'desc' : 'asc', header.value === …
```

fix(V-data-table): correctly center the selection-controls

---

packages/vuetifyjs.com/src/lang/ja/components/ApiExplorer.json

Added Japanese translation.
Supporting a new language
It is not tested because it is a translation file
<details>
```vue
```
</details>

docs: translate components/ApiExplorer into Japanese

---

packages/vuetifyjs.com/src/examples/cards/horizontal.vue

I came across this file and the first card wasn't really nice if you increase the max-width. Not an important change though.
<details>
```vue
```
</details>

Improve responsive behaviour

---

packages/vuetify/src/components/VCheckbox/VCheckbox.js
packages/vuetify/src/components/VRadioGroup/VRadio.js
packages/vuetify/src/components/VSwitch/VSwitch.js
packages/vuetify/test/unit/components/VCheckbox/VCheckbox.spec.js

fixes #5653
visually
<details>
```vue
<template>
<v-app>
<v-content>
<v-container>
<v-switch v-model="active" :disabled="!enable" @change="activeChanged()" />
<v-checkbox v-model="active" :disabled="!enable" @change="activeChanged()" />
</v-container>
</v-content>
</v-app>
</template>
<script>
methods: {
activeChanged() {
this.enable = false;
setTimeout(() => (this.enable = true), 500);
}
},
data: () => ({
active: true,
enable: true
})
};
</script>
```
</details>

fix(selection-controls): use ripple even when disabled

---

packages/vuetify/src/components/VBtn/VBtn.ts

A check is added to see if the `disabled` prop has a true value. If so, then the render function will not call `setBackgroundColor`.
See issue here: https://github.com/vuetifyjs/vuetify/issues/5720
None.
<details>
```vue
<template>
<v-app>
<v-content>
<v-btn icon>
<v-icon>print</v-icon>
</v-btn>
<v-btn icon color="primary">
<v-icon>print</v-icon>
</v-btn>
<v-btn icon disabled>
<v-icon>print</v-icon>
</v-btn>
<v-btn icon disabled color="primary">
<v-icon>print</v-icon>
</v-btn>
<v-btn disabled color="primary">
<v-icon>print</v-icon>
</v-btn>
<v-btn color="primary">
<v-icon>print</v-icon>
</v-btn>
</v-container>
</v-content>
</v-app>
</template>
<script>
data: () => ({
})
}
</script>
```
</details>

Fixes disabled styling for v-btn when a color prop is passed in

---

packages/vuetifyjs.com/src/public/sitemap.xml
packages/vuetifyjs.com/src/router/301.json

Added Redirects for A-la-carte and SSR. Updated a-la-carte record and removed the SSR record
Updates for 301.json Redirects and the sitemap
None
<details>
```vue
```
</details>

docs(301.json and sitemap.xml): Updated Redirects and Sitemap

---

packages/vuetify/src/components/VCarousel/VCarousel.ts
packages/vuetify/test/unit/components/VCarousel/__snapshots__/VCarousel.spec.js.snap

The carousel paging buttons do not work when the value is dynamic
unit, visually
<details>
```vue
<template>
<v-carousel v-model="carousel">
<v-carousel-item v-for="item in itens" :key="item.id" :src="item.image" :value="item.id" />
</v-carousel>
</template>
<script>
data() {
return {
carousel: 111,
itens: [
{
id: 111,
image: 'https://via.placeholder.com/111'
},
{
id: 222,
image: 'https://via.placeholder.com/222'
},
{
id: 333,
image: 'https://via.placeholder.com/333'
}
]
}
}
}
</script>
```
</details>

fix(VCarousel): pass `value` property to controls

---

packages/vuetify/package.json

Add link for [Unpkg](https://unpkg.com).
none
<details>
```vue
```
</details>

chore(package): add Unpkg link

---

packages/vuetify/src/stylus/settings/_variables.styl
packages/vuetifyjs.com/src/data/pages/layout/Display.json
packages/vuetifyjs.com/src/lang/en/layout/Display.json

Adds `hidden-screen-only` and `hidden-print-only` convenience classes to assist when building a custom component for both the screen and printer.
Re-submission of #5164
Some components require changes to the content in addition to print stylesheets. Hiding interaction elements such as buttons, replacing with contextually relevant information, etc. In these cases, rather than add a bunch of custom styles, it would be great to use the same CSS helper classes we are already accustomed to using with the various screen size breakpoints.
Visually
<details>
```vue
<template>
<v-app>
<v-btn class="hidden-print-only">
E-mail Us
</v-btn>
<p class="hidden-screen-only">
Email us <b>hello@vuetifyjs.com</b>
</p>
</v-app>
</template>
<script>
import '../src/stylus/trumps/_display.styl'
export default {} …
```

feat: add display breakpoints for printing

---

packages/vuetify/src/stylus/components/_chips.styl
packages/vuetify/src/stylus/settings/_variables.styl

fixes #5782
visually
<details>
```vue
<template>
<v-content>
<v-container>
<v-chip>normal</v-chip>
<v-chip close>closable</v-chip>
<v-chip close><v-avatar color=red>X</v-avatar>closable</v-chip>
<v-chip><v-icon>place</v-icon>icon</v-chip>
<v-chip><v-icon left>place</v-icon>icon left</v-chip>
<v-chip>icon right<v-icon right>place</v-icon></v-chip>
<v-select multiple chips :items="['foo', 'bar']" :value="['foo', 'bar']" deletable-chips />
<v-btn @click="$vuetify.rtl = !$vuetify.rtl">Switch rtl</v-btn>
</v-container>
</v-content>
</v-app>
</template>
```
</details>

fix(VChip): rtl mode

---

packages/vuetify/src/stylus/components/_badges.styl

fixes #5684
visually
<details>
```vue
<template>
<v-content>
<v-container>
<v-badge class="mx-5"><v-icon slot="badge">place</v-icon>default</v-badge>
<v-badge left class="mx-5"><v-icon slot="badge">place</v-icon>left</v-badge>
<v-badge right class="mx-5"><v-icon slot="badge">place</v-icon>right</v-badge>
<v-divider />
<v-badge overlap class="mx-5"><v-icon slot="badge">place</v-icon>default</v-badge>
<v-badge overlap left class="mx-5"><v-icon slot="badge">place</v-icon>left</v-badge>
<v-badge overlap right class="mx-5"><v-icon slot="badge">place</v-icon>right</v-badge>
<v-btn @click="$vuetify.rtl = !$vuetify.rtl">Switch rtl</v-btn>
</v-container>
</v-content>
</v-app>
</template>
```
</details>

fix(VBadge): rtl mode

---

packages/vuetify/src/stylus/components/_data-iterator.styl

Fixes #5655
visually 
<details>
```vue
```
</details>

fix(VDataIterator): select is too tall in IE11

---

packages/vuetify/src/components/VSelect/VSelect.js

V-select should close when it loses focus or user switches to another tab.
Fixes #5774
visually
<details>
```vue
// Paste your FULL Playground.vue here<template>
<v-app>
<v-card>
<v-container
fluid
grid-list-xl
>
<v-layout
align-center
wrap
>
<v-flex xs12 sm6>
<v-select
:items="items"
attach
chips
label="Chips"
multiple
></v-select>
</v-flex>
<v-flex xs12 sm6>
<v-select
:items="items"
box
chips
label="Chips"
multiple
></v-select>
</v-flex>
<v-flex xs12 sm6>
<v-select
:items="items"
chips
label="Chips"
multiple
outline
></v-select>
</v-flex>
<v-flex xs12 sm6>
<v-select
:items="items"
chips
label="Chips"
multiple
solo
></v-select>
</v-flex>
</v-layout>
</v-container>
</v-card>
</v-app>
</template>
<script> …
```

fix(VSelect): fix VSelect behavior when switching to another tab

---

packages/vuetify/src/stylus/elements/_code.styl

Change `kbd` background to `$grey.darken-2`
Fixes #5509.
visually
<details>
```vue
<template>
<v-app>
<v-container>
<v-card dark>
<v-card-text>
im some card text<br>
<kbd>im a kbd tag</kbd>
<code>im a code tag</code>
</v-card-text>
</v-card>
<v-card>
<v-card-text>
im some card text<br>
<kbd>im a kbd tag</kbd>
<code>im a code tag</code>
</v-card-text>
</v-card>
</v-container>
</v-app>
</template>
<script>
data: () => ({
})
}
</script>
```
</details>

fix(kbd): fix `kbd` background color

---

packages/vuetifyjs.com/src/data/pages/components/ExpansionPanels.json
packages/vuetifyjs.com/src/examples/expansion-panels/iconSlot.vue
packages/vuetifyjs.com/src/lang/en/components/ExpansionPanels.json

Add an example of custom icon using `actions` slot.
Fixes #5275

docs(VExpansionPanel): add docs for `actions` slot

---

packages/vuetify/src/components/VDatePicker/VDatePicker.js
packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.js
packages/vuetify/src/components/VDatePicker/VDatePickerMonthTable.js
packages/vuetify/src/components/VDatePicker/VDatePickerYears.js
packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.js
packages/vuetify/test/unit/components/VDatePicker/VDatePicker.date.spec.js
packages/vuetify/test/unit/components/VDatePicker/VDatePicker.month.spec.js

Add support for mouse events on date/month buttons and year items
fixes #3023
playground
<details>
```vue
<template>
<v-content>
<v-radio-group row v-model="state">
<v-radio label="normal" value="normal"/>
<v-radio label="readonly" value="readonly"/>
<v-radio label="disabled" value="disabled"/>
<v-radio-group row label="type" v-model="month">
<v-radio label="date" :value="false"/>
<v-radio label="month" :value="true"/>
<v-date-picker
v-model="date"
:disabled="state === 'disabled'"
:readonly="state === 'readonly'"
:type="month ? 'month' : 'date'"
@click:date="log('click', 'date', $event)"
@click:month="log('click', 'month', $event)"
@dblclick:date="log('dblclick', 'date', $event)"
@dblclick:month="log('dblclick', 'month', $event)" …
```

feat(VDatePicker): mouse events - click/dblclick

---

LICENSE.md

2019! :christmas_tree: :gift:
Update year.
> P.S. This is a copy of the #6002 for `dev` branch
Happy New Year! Merry Christmas! gift
It has been a pleasure to work with you this year. I wish you the best of holidays and a Happy New Year! :santa: :christmas_tree:

docs: Happy New Year! :gift:

---

packages/vuetify/src/components/VTreeview/VTreeviewNode.ts

moved active-class to __root element instead so that it only applies to
active nodes.
fixes #5854
manually
<details>
```vue
<template>
<v-app>
<v-treeview
v-model="tree"
:active.sync="active"
:items="items"
:open.sync="open"
activatable
active-class="primary--text"
class="grey lighten-5"
transition
>
<v-icon
slot="prepend"
slot-scope="{ item, active }"
:color="active ? 'orange' : 'red'"
>{{ accountTypeIcon(item) }}</v-icon>
</v-treeview>
<v-treeview
:items="items"
activatable
></v-treeview>
</v-app>
</template>
<script>
const findItemById = (item, id) => {
if (!item) {
return undefined
}
if (item.id && item.id === id) {
return item
}
const children = item.children
if (children && Array.isArray(children) && children.length > 0) {
for (let child of children) {
const item = …
```

fix(VTreeview): active-class applies to node and all its children

---

packages/vuetify/src/stylus/components/_snackbars.styl

Fix margin for `v-btn` of `v-snack` in rtl mode
visually
<details>
```vue
<template>
<v-app>
<v-snackbar :value="true">
Hello, I'm a snackbar
<v-btn icon>
</v-btn>
</v-snackbar>
</v-app>
</template>
<script>
data: () => ({
}),
mounted: () => {
}
}
</script>
```
</details>

add rtl to snackbars component

---

packages/vuetify/src/components/VTreeview/VTreeview.ts
packages/vuetify/test/unit/components/VTreeview/VTreeview.spec.js
packages/vuetify/test/unit/components/VTreeview/__snapshots__/VTreeview.spec.js.snap

Loading async children using a non-standard children key resulted in
error messages as tree was not recalculated when children were added
fixes #5550
manually and added unit test
<details>
```vue
<template>
<v-app>
<v-treeview
:active.sync="active"
:items="items"
:load-children="fetchUsers"
:open.sync="open"
activatable
item-children="__children"
active-class="primary--text"
class="grey lighten-5"
open-on-click
transition
>
<v-icon
v-if="!item.children"
slot="prepend"
slot-scope="{ item, active }"
:color="active ? 'primary' : ''"
>mdi-account</v-icon>
</v-treeview>
</v-app>
</template>
<script>
const pause = ms => new Promise(resolve => setTimeout(resolve, ms))
data: () => ({
active: [],
avatar: null,
open: [],
users: []
}),
computed: {
items () {
return [ …
```

fix(VTreeview): async loading using custom children key

---

packages/vuetifyjs.com/src/lang/en/components/Icons.json

Add link to SVG guide
Fixes #6033

docs(Icons): add link to SVG guide

---

jest.config.js
packages/vuetify/package.json
yarn.lock

Added @vue/test-utils package
To convert from avoriaz to vue-test-utils
Manually
-NA-

chore: add @vue/test-utils

---

packages/vuetifyjs.com/src/lang/zh-Hans/components/NavigationDrawers.json

docs(VNavigationDrawer): fix typos in Chinese

---

packages/vuetifyjs.com/src/lang/zh-Hans/components/Parallax.json

docs(VParallax): fix typos in Chinese

---

packages/vuetify/src/components/VFooter/VFooter.js
packages/vuetify/test/unit/components/VFooter/VFooter.spec.js
packages/vuetify/test/unit/components/VFooter/__snapshots__/VFooter.spec.js.snap

Center the content of the footer when a v-navigation-drawer exists on the right.
Fixes https://github.com/vuetifyjs/vuetify/issues/5908
visually
<details>
```vue
<template>
<v-app>
<v-navigation-drawer app clipped v-if="showLeftDrawer"></v-navigation-drawer>
<v-navigation-drawer app clipped right v-if="showRightDrawer"></v-navigation-drawer>
<v-footer color="green" app dark>
<v-layout justify-center>this text is not centered but shifted to the left</v-layout>
</v-footer>
</v-app>
</template>
<script>
data: () => ({
showLeftDrawer: true,
showRightDrawer: true,
})
}
</script>
```
</details>

fix(VFooter): center content when right v-navigation-drawer exists

---

packages/vuetify/src/components/VProgressLinear/VProgressLinear.ts
packages/vuetify/src/stylus/components/_progress-linear.styl
packages/vuetify/test/unit/components/VProgressLinear/VProgressLinear.spec.js
packages/vuetify/test/unit/components/VProgressLinear/__snapshots__/VProgressLinear.spec.js.snap

Added support for content inside progress bar. Using contribution from @greenya https://github.com/vuetifyjs/vuetify/issues/3768
solves #3768 
playground & unit test
<details>
```vue
<template>
<v-app>
<v-container>
<v-progress-linear value="75" height="20" color="error"></v-progress-linear>
<v-progress-linear value="75" height="20" color="error">
just text
</v-progress-linear>
<v-progress-linear value="75" height="20" color="error">
<div>a div</div>
</v-progress-linear>
<v-progress-linear value="75" height="20" color="error">
<div class="d-flex justify-space-between white--text px-2">
<span>Health</span>
<span>75 / 100</span>
</div>
</v-progress-linear>
</v-layout>
</v-container>
</v-app>
</template>
<script>
}
</script>
```
</details>

feat(VProgressLinear): support for content inside progress bar

---

packages/kitchen/src/pan/Alerts.vue

Add more examples to VAlert pan
Create kitchen sink
visually

docs(kitchen): add more examples to VAlert pan

---

packages/kitchen/src/pan/Ratings.vue

Add VRating pan.
https://github.com/vuetifyjs/vuetify/projects/19#card-16137402

docs(kitchen): add VRating pan

---

packages/kitchen/src/pan/Time pickers.vue

Add VTimePicker pan to the kitchen sink.
https://github.com/vuetifyjs/vuetify/projects/19#card-16137402

docs(kitchen): add VTimePicker pan

---

packages/vuetify/src/components/VItemGroup/VItemGroup.ts
packages/vuetify/src/components/VSelect/VSelect.js
packages/vuetify/test/unit/components/VSelect/VSelect3.spec.js

Possible implementation for quick select item in `v-select` by typing first few letters of item
Fixes #4853
visually & unit
<details>
```vue
<template>
<v-app>
<v-layout align-center justify-center>
<v-flex xs4 text-xs-center>
<v-text-field solo />
<v-select
solo
:items="items"
/>
<a href="https://codepen.io/dima74/pen/yGXabW" target="_blank">codepen with native select</a>
</v-flex>
</v-layout>
</v-app>
</template>
<script>
data: () => ({
items: ['Aaa', 'Ooo', 'Faa', 'Foo'],
}),
};
</script>
```
</details>

feat(VSelect): replicate html select hotkeys

---

packages/vuetify/src/components/VAlert/VAlert.sass
packages/vuetify/src/components/VAlert/_variables.scss
packages/vuetify/src/styles/base/_variables.scss

Fix colored border with `dense` prop
Fixes #6216.
Visually
<details>
```vue
<template>
<v-container>
<v-flex>
<h3 class="title grey--text text-xs-center mb-4 mt-5">
Dense
</h3>
<v-alert
type="success"
dense
>
This is a success alert.
</v-alert>
<v-alert
type="info"
dense
>
This is an info alert.
</v-alert>
<v-alert
type="warning"
dense
>
This is a warning alert.
</v-alert>
<v-alert
type="error"
dense
>
This is an error alert.
</v-alert>
</v-flex>
<v-flex>
<h3 class="title grey--text text-xs-center mb-4 mt-5">
Default
</h3>
<v-alert
type="success"
>
This is a success alert.
</v-alert>
<v-alert
type="info"
>
This is a info alert.
</v-alert>
<v-alert
type="warning"
>
This is a warning alert.
</v-alert>
<v-alert
type="error"
>
This is an error alert.
</v-alert>
</v-flex> …
```

fix(VAlert): fix border with dense prop

---

packages/kitchen/src/pan/Alerts.vue

Add more examples to VAlert pan in the kitchen sink.
https://github.com/vuetifyjs/vuetify/projects/19#card-16137402

docs(kitchen): add more examples for VAlert

---

packages/kitchen/src/pan/Timelines.vue

Use CoreSection and CoreTitle in Timelines pan
Fix issues I made in #6210.

docs(kitchen): use CoreSection and CoreTitle in Timelines pan

---

packages/kitchen/src/pan/Lists.vue

Add VList pan.
Add components to kitchen.

docs(kitchen): add VList pan

---

packages/kitchen/src/pan/Tabs.vue

Add VTabs pan.
Add components to the kitchen.

docs(kitchen): add VTabs pan

---

packages/kitchen/src/pan/Item Groups.vue

Add VItemGroup pan to the kitchen.
https://github.com/vuetifyjs/vuetify/projects/19#card-16137402

docs(kitchen): add VItemGroup pan

---

packages/kitchen/src/pan/Windows.vue

Add VWindow pan.
Add components to the kitchen sink.

docs(kitchen): add VWindow pan

---

packages/kitchen/src/pan/Slide groups.vue

Add Slide Groups pan.
Add components to the kitchen.

docs(kitchen): add Slide Groups pan

---

packages/vuetify/src/components/VChipGroup/__tests__/VChipGroup.spec.ts
packages/vuetify/src/components/VChipGroup/__tests__/__snapshots__/VChipGroup.spec.ts.snap

Add unit tests for VChipGroup.
@johnleider asked.
`jest`

test(VChipGroup): add tests

---

packages/kitchen/src/pan/Chip Groups.vue

Add VChipGroup pan.
New component needs a pan. :shallow_pan_of_food:

docs(kitchen): add VChipGroup pan

---

packages/vuetify/src/components/VChip/VChip.sass

Add margin after pill filter
Fixes ![](https://cdn.discordapp.com/attachments/340199191282319360/540219111997964288/unknown.png)
visually
docs example

fix(VChip): add margin after pill filter

---

packages/vuetify/src/components/VChip/__tests__/VChip.spec.ts

Add more tests for VChip.
Fix coverage.
`jest --coverage`
<details>
```vue
<none />
```
</details>

test(VChip): add more tests

---

packages/kitchen/src/App.vue
packages/kitchen/src/router.js
packages/kitchen/src/views/Theme.vue

Add theming page to kitchen.
Add custom theme check support to kitchen.

docs(kitchen): add theming page

---

packages/docs/src/lang/zh-Hans/components/Snackbars.json

Optimize Chinese translation about Snackbars.
The original translation is obscure, and has some typos.
Passed
<details>
```vue
{
"header": "Snackbars",
"headerText": "`v-snackbar`组件用于向用户显示快速消息，Snackbars 支持定位、消失延迟和回调。",
"components": ["v-snackbar"],
"examples": {
"position": {
"header": "位置",
"desc": "标准 Snackbars 有利于使用户注意到一些刚发生的活动。"
},
"contextual": {
"header": "上下文",
"desc": "您可以为 Snackbars 应用一种色彩，以更好地适应您的实现。"
}
},
"props": {
"multiLine": "使 Snackbars 的高度动态变化（移动设备）",
"timeout": "等待 Snackbars 自动隐藏的时间。使用 0 来保持永久开启。",
"vertical": "垂直折叠 Snackbars 的内容（移动设备）"
}
}
```
</details>

docs(Snackbars): optimize Chinese translation

---

packages/vuetify/src/components/VDatePicker/VDatePicker.ts
packages/vuetify/src/components/VDatePicker/VDatePickerDateTable.ts
packages/vuetify/src/components/VDatePicker/VDatePickerHeader.ts
packages/vuetify/src/components/VDatePicker/VDatePickerMonthTable.ts
packages/vuetify/src/components/VDatePicker/VDatePickerYears.ts
packages/vuetify/src/components/VDatePicker/mixins/date-picker-table.ts
packages/vuetify/src/components/VDatePicker/util/createNativeLocaleFormatter.ts
packages/vuetify/src/components/VDatePicker/util/isDateAllowed.ts
packages/vuetify/src/mixins/picker.ts

refactor(VDatePicker): convert to typescript

---

packages/vuetify/src/mixins/overlayable.js

fixes #6346
playground
<details>
```vue
<template>
<v-app>
<v-dialog v-model="dialog" scrollable max-width="300px" :fullscreen="fullscreen" :hide-overlay="hideme">
<v-btn slot="activator" color="primary" dark>Open Dialog</v-btn>
<v-card>
<v-card-text>
<v-btn color="blue darken-1" flat @click="hideme = !hideme">toggle overlay</v-btn>
<v-btn color="blue darken-1" flat @click="fullscreen = !fullscreen">toggle fullscreen</v-btn>
</v-card-text>
</v-card>
</v-dialog>
</v-app>
</template>
<script>
data: () => ({
dialog: false,
hideme: false,
fullscreen: false
})
}
</script>
```
</details>

fix(overlayable): make hide-overlay prop reactive

---

packages/docs/src/snippets/js/cache_theme.txt

Since in lru-cache version 5, we must initialize the constructor using `new` keyword. Otherwise it will rise an error like this 
```
Class constructor LRUCache cannot be invoked without 'new'
```
Re-run the project again.
<details>
```vue
```
</details>

Chore: Update LRU Cache Initialization Method

---

packages/docs/src/examples/sparklines/playground.vue

Add `gradientDirection` property to playground.
There is `gradientDirection` property so we need an example.

docs(VSparkline): add gradientDirection property to playground

---

packages/docs/src/lang/en/framework/ALaCarte.json

"whereever" -> "wherever"
<details>
```vue
```
</details>

Minor typo

---

packages/vuetify/src/styles/themes/_dark.scss
packages/vuetify/src/styles/themes/_light.scss

Use color variables in theme.
@MajesticPotatoe asked.
none
<details>
```vue
```
</details>

refactor(theme): use color variables

---

packages/vuetify/test/index.js
packages/vuetify/test/unit/components/VMenu/VMenu.spec.js

Some time ago #6330 was merged, which contains [some test](https://github.com/vuetifyjs/vuetify/blob/cbf53290d98abd9739509671a3ef06a9e8494a66/packages/vuetify/test/unit/components/VMenu/VMenu.spec.js#L459-L486). Unfortunately that test fails randomly ([example](https://travis-ci.org/vuetifyjs/vuetify/builds/490695166?utm_source=github_status&utm_medium=notification)). I am sorry for writing such a test.
I explained why it is hard to write proper test in [this comment](https://github.com/vuetifyjs/vuetify/pull/6330#issuecomment-460083547). This pr improves that test by extending `requestAnimationFrame` polyfill and removing `await sleep(50)` statements.
Fix failing test
unit

fix(VMenu): fix randomly failing test

---

packages/vuetify/src/components/VAutocomplete/VAutocomplete.js
packages/vuetify/test/unit/components/VAutocomplete/VAutocomplete.spec.js

Closes #6368
Addresses [#6368](https://github.com/vuetifyjs/vuetify/issues/6368)
visually
<details>
```vue
<template>
<boilerplate>
<v-card>
<v-card-title class="headline font-weight-regular blue-grey white--text">Profile</v-card-title>
<v-card-text>
<v-subheader v-if="model" class="pa-0">
Lang: {{ lang }},
Model: {{ model }}, <br /><br />
Items: {{ myItems }}
</v-subheader>
<v-select
:items="langs"
label="Parameter currentLang" v-model="lang"
></v-select>
:items="myItems" :item-text="displayLabel"
label="Autocomplete with translation"
persistent-hint solo return-object
prepend-icon="mdi-flag"
>
</v-card-text>
</v-card>
</boilerplate>
</template>
<script>
import Boilerplate from './Boilerplate'
export …
```

fix(VAutocomplete): Update dynamically when itemText is updated

---

packages/vuetify/src/components/VMenu/VMenu.js
packages/vuetify/src/components/VTooltip/VTooltip.js
packages/vuetify/src/mixins/menuable.js
packages/vuetify/test/unit/components/VMenu/__snapshots__/VMenu.spec.js.snap

fixes #6294
visually
<details>
```vue
<template>
<v-app>
<v-content>
<h2>#6294</h2>
<v-layout justify-end mb-5>
<v-tooltip bottom>
<v-btn slot="activator" flat>hoverme</v-btn>
Looooooooooooooooooooooooooooooooooong
</v-tooltip>
<v-tooltip bottom>
<v-btn slot="activator" flat>hoverme</v-btn>
Looooooooooooooooooooooooooooooooooong
</v-tooltip>
</v-layout>
<v-layout justify-end mb-5>
<v-tooltip bottom>
<v-btn slot="activator" flat>hoverme</v-btn>
short
</v-tooltip>
<v-tooltip bottom>
<v-btn slot="activator" flat>hoverme</v-btn>
short
</v-tooltip>
</v-layout>
<v-layout justify-end mb-5>
<v-btn @click="show2">Open menu</v-btn>
<v-btn @click="show">Open menu</v-btn>
</v-layout>
<v-menu v-model="showMenu" :position-x="x" :position-y="y" absolute offset-y>
<v-list>
<v-list-tile> …
```

fix(menuable): positioning when overflowing viewport

---

packages/docs/src/components/getting-started/Team.vue

docs(meet the team): add me to team

---

packages/docs/src/lang/en/components/Calendars.json

Update the text to be day `and week` view
<details>
```vue
```
</details>

docs(calendar) fix intervalFormat

---

packages/kitchen/src/pan/Daily Calendars.vue
packages/kitchen/src/pan/Monthly Calendars.vue
packages/kitchen/src/pan/Weekly Calendars.vue

Add `VCalendar` pans to the kitchen sink.
Add kitchen sink
kitchen
kitchen
- [c] New feature (non-breaking change which adds functionality)
- [c] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

docs(kitchen): add pans for VCalendar

---

packages/kitchen/src/components/CoreTitle.vue
packages/kitchen/src/components/SubHeader.vue
packages/kitchen/src/main.js

Add sub-header component for kitchen
Create more complex pans with sub-categories

 docs(kitchen): add sub-header component

---

packages/vuetify/src/components/VCarousel/VCarousel.ts
packages/vuetify/test/unit/components/VCarousel/VCarousel.spec.js

Fixed transition direction when clicked outside buttons of `VCarousel` that changing index.
fixes #6366
visually
<details>
```vue
<template>
<v-app>
<v-content>
<v-carousel v-model="index" :cycle="false">
v-for="(item, i) in items"
:key="i"
:src="item.src"
transition="fade"
:reverse-transition="false"
/>
</v-carousel>
<v-btn @click="clickHandle">Click</v-btn>
</v-content>
</v-app>
</template>
<style>
.fade-enter-active,
.fade-leave-active {
transition: opacity 0.5s;
}
.fade-enter,
.fade-leave-to {
opacity: 0;
}
</style>
<script>
data () {
return {
direction: 'right',
index: 0,
items: [
{
src: 'https://cdn.vuetifyjs.com/images/carousel/squirrel.jpg'
},
{
src: 'https://cdn.vuetifyjs.com/images/carousel/sky.jpg'
},
{
src: …
```

fix(VCarousel): transition direction when outside button click

---

packages/vuetify/src/stylus/components/_pagination.styl

revert: fix(VPagination): remove unnecessary outline for circle pagination buttons

---

packages/vuetify/test/unit/components/VCalendar/VCalendar.spec.js
packages/vuetify/test/unit/components/VCalendar/__snapshots__/VCalendar.spec.js.snap

Fix `VCalendar` tests
Make these tests pass
`jest`

test(VCalendar): fix tests

---

packages/docs/src/examples/grid/growShrink.vue
packages/docs/src/lang/en/framework/Grid.json
packages/vuetify/src/stylus/components/_grid.styl

Reference: PR https://github.com/vuetifyjs/vuetify/pull/6533
Resolves https://github.com/vuetifyjs/vuetify/issues/6530

feat(VGrid): support for no grow/shrink, and better documentation

---

packages/docs/src/examples/cards/usage.vue

In this example, I believe you wanted to use the `card_text` returned by `data()` function.  That is what I did.
It may be confusing for beginners (as it happened to me in the start) as to why you defined `card_text` but you used different text for the description.  If you prefer not using `card_text`, as it is the case with the present situation, then please remove totally `data()` function because it is a good practice  to code  only what we need to use.
This is what I did, and I believe it makes sens in this case:
```
<div> {{ card_text }} </div>
```
And the output looks nice.
<details>
```vue
```
</details>

docs(VCard): use text defined in data() function

---

.travis.yml

Use latest Node.js in Travis CI
New Node.js is faster, it will improve CI performance
Travis CI

ci(Travis): use latest Node.js

---

packages/docs/src/examples/dialogs/withoutActivator.vue

The description above this example says "If for some reason you are unable to use the activator slot, be sure to add the .stop modifier to the event that triggers the dialog.", but the example does not use .stop.
I *think* I did this right.
This is just a small documentation change.
I'm trying to learn Vuetify and Vue and this example seemed incomplete. Fixing this small thing hopefully is helpful.
I used this syntax myself and it works.
<details>
```vue
```
</details>

Make example consistent with documentation

---

packages/vuetify/src/components/VSheet/VSheet.ts

Made v-sheet listen for events
Fixes https://github.com/vuetifyjs/vuetify/issues/6572
v-sheet wasn't taking events
visually 
<details>
```vue
```
</details>

Fix to listen for events on v-sheet

---

packages/kitchen/src/components/CoreTitle.vue
packages/kitchen/src/plugins/vuetify.js
packages/kitchen/src/router.js

Add anchors to kitchen.
Developers will be able to share links to specific examples.

docs(kitchen): add anchors

---

packages/vuetify/src/components/VAlert/VAlert.sass
packages/vuetify/src/components/VAlert/_variables.scss

Split out more variables for `VAlert`
Better customization & material theming.
none

refactor(VAlert): split out variables

---

packages/vuetify/src/components/VDivider/VDivider.sass
packages/vuetify/src/components/VDivider/_variables.sass

Split out `VDivider` variables
Customize margin
not tested

refactor(VDivider): split out variables

---

packages/vuetify/src/styles/base/_variables.scss
packages/vuetify/src/styles/elements/_blockquote.sass
packages/vuetify/src/styles/elements/_code.sass
packages/vuetify/src/styles/helpers/_bootable.sass

Split out HTML elements' variables
Support material theming
none

refactor(elements): split out variables

---

packages/vuetify/src/components/VBtn/VBtn.sass
packages/vuetify/src/components/VBtn/_variables.scss

Split out `VBtn` variables
Material theming
It builds :)

refactor(VBtn): split out variables

---

packages/vuetify/src/components/VSlideGroup/VSlideGroup.sass
packages/vuetify/src/components/VSlideGroup/_variables.sass

Split out `VSlideGroup` variables
Easy customization of component
none (logical checked)

refactor(VSlideGroup): split out variables

---

packages/vuetify/src/components/VTooltip/VTooltip.js
packages/vuetify/test/unit/components/VTooltip/VTooltip.spec.js
packages/vuetify/test/unit/components/VTooltip/__snapshots__/VTooltip.spec.js.snap

playground, jest
<details>
```vue
<template>
<v-app>
<v-content>
<v-tooltip min-width=300 bottom>
<template v-slot:activator={on}><v-btn v-on=on>btn</v-btn></template>
Hey
</v-tooltip>
</v-content>
</v-app>
</template>
```
</details>

fix(VTooltip): min width is not applied

---

packages/vuetify/src/styles/base/_variables.scss

To match [MD2 specs](https://material.io/design/typography/the-type-system.html#type-scale)
none

feat(typography): update typography font weight to md2

---

packages/vuetify/src/services/lang/index.ts
packages/vuetify/src/services/theme/__tests__/__snapshots__/theme.spec.ts.snap
packages/vuetify/src/services/theme/__tests__/theme.spec.ts
packages/vuetify/src/services/theme/index.ts

Add some ignore comments to things we can't properly test, add some tests for some cases.
Make framework coverage higher
`jest`

test(services): improve coverage

---

packages/vuetify/src/util/__tests__/colorUtils.spec.ts
packages/vuetify/src/util/__tests__/console.spec.ts
packages/vuetify/src/util/__tests__/helpers.spec.ts
packages/vuetify/src/util/__tests__/mask.spec.ts

Convert util tests to TypeScript and move them to util folder
Refactor tests
`jest`

test(util): convert to TypeScript and move

---

packages/docs/src/lang/en/components/Banners.json
packages/vuetify/src/components/VBanner/VBanner.sass

I noticed some small flexbox bugs in IE11 regarding  `v-banner`
Decided I could try and fix them, @sh7dm PTAL
visually
<details>
```vue
<v-container>
<v-layout wrap>
<v-flex xs12>
<v-banner two-line>
<v-avatar
slot="icon"
color="deep-purple accent-4"
size="40">
<v-icon
icon="mdi-lock"
color="white">
mdi-lock
</v-icon>
</v-avatar>
Three line text string example with two actions. One to two lines is preferable. Three lines should be
considered the maximum string length on desktop in order to keep messages short and actionable.
<template v-slot:actions>
<v-btn text color="deep-purple accent-4">Action</v-btn>
<v-btn text color="deep-purple accent-4">Action</v-btn>
</template>
</v-banner>
</v-flex>
</v-layout>
</v-container>
```
</details>

fix(VBanner): flexbox related issues with IE11

---

packages/vuetify/src/directives/ripple.ts

See also: #6477
I randomly got an error `ripple.js:109 Uncaught TypeError: Cannot read property 'touched' of undefined` (the line numbers are off due to my build system, I think)
To not crash.
I don't know how to reproduce the issue. But this look like the only line in ripple.ts which assumes that `_ripple` exists before accessing its `touched`.
<details>
```vue
```
</details>

Probably fix Uncaught TypeError in ripple.ts

---

packages/docs/src/lang/en/mixins/Bootable.json
packages/vuetify/src/components/VDataTable/VEditDialog.js
packages/vuetify/src/components/VList/VListGroup.ts
packages/vuetify/src/components/VList/__tests__/VListGroup.spec.ts
packages/vuetify/src/components/VList/__tests__/__snapshots__/VListGroup.spec.ts.snap
packages/vuetify/src/components/VSelect/VSelect.js
packages/vuetify/src/components/VTooltip/__tests__/VTooltip.spec.js
packages/vuetify/src/components/VTooltip/__tests__/__snapshots__/VTooltip.spec.js.snap
packages/vuetify/src/mixins/bootable.ts
packages/vuetify/src/mixins/bootable/__tests__/bootable.spec.ts
packages/vuetify/src/mixins/bootable/index.ts
packages/vuetify/src/mixins/detachable.ts
packages/vuetify/test/unit/components/VCarousel/__snapshots__/VCarousel.spec.js.snap
packages/vuetify/test/unit/components/VCarousel/__snapshots__/VCarouselItem.spec.js.snap
packages/vuetify/test/unit/components/VDialog/VDialog.spec.js
packages/vuetify/test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanel.spec.js.snap
packages/vuetify/test/unit/components/VExpansionPanel/__snapshots__/VExpansionPanelContent.spec.js.snap
packages/vuetify/test/unit/components/VMenu/VMenu.spec.js
packages/vuetify/test/unit/mixins/detachable.spec.js

Update bootable to v2 structure, move over tests.
Make **bootable** lazy by default. Enable existing default by **eager** prop. Input components retain their eager state but can be disabled with **menu-props="{ eager: false }"**.
Improve framework performance.
jest
<details>
```vue
<template>
<div>
<v-menu>
<v-btn v-on="on">
Click
</v-btn>
</template>
<v-card>
<v-card-text>Lorem ipsum</v-card-text>
</v-card>
</v-menu>
<v-dialog>
<v-btn v-on="on">
Click
</v-btn>
</template>
<v-card>
<v-card-text>Lorem ipsum</v-card-text>
</v-card>
</v-dialog>
<v-select :items="[1,2,3,4]"></v-select>
</div>
</template>
```
</details>

feat(bootable): update for v2

---

packages/docs/src/lang/zh-CN/generic/Props.json

docs: fix typo in Chinese

---

packages/vuetify/src/components/VTextField/VTextField.js

In IE 11 input elements with placeholders triggers unnecessary
"input" events. It causes bugs when using mask property.
This commit checks if there is an actual change in input before
calling other methods implementing mask logic.
Example: See bugs #4290, #5225 
If it fixes an open issue [4290](https://github.com/vuetifyjs/vuetify/issues/4290), also is 
associated with [5225](https://github.com/vuetifyjs/vuetify/issues/5225)
manually using Internet Explorer
<details>
```vue
<template>
<v-app>
<Boilerplate>
<v-text-field
v-model="textValue"
solo
outline
flat
<v-text-field
v-model="text"
single-line
placeholder="just placeholder"
return-masked-value
outline
mask="##/##/#### ##:##"
</Boilerplate>
</v-app>
</template>
import Vue from "vue"; …
```

fix(VTextField): VTextField with placeholder and mask bug

---

packages/docs/src/lang/en/components/DataTables.json
packages/docs/src/lang/zh-CN/components/DataTables.json

Point out that users have to specify "key" manually if they try to control the entire row of
DataTable
Please refer to #6770 
Visually verified
changes are highlighted with red lines
**en:**
**zh-CN:**

docs(component): add complement to "item-key" of DataTable

---

packages/docs/src/lang/en/mixins/Validatable.json

Just fix typo in update:error event description

docs: fix typo in update:error event description

---

packages/vuetify/src/components/VBtnToggle/__tests__/VBtnToggle.spec.ts

Mocks are not needed for testing this component so they were removed.
It makes the code shorter and easier to maintain.
unit

refactor(VBtnToggle): remove reference to mocks

---

packages/docs/src/lang/en/components/NavigationDrawers.json
packages/docs/src/lang/en/mixins/Validatable.json
packages/docs/src/lang/ko-KR/mixins/Filterable.json
packages/docs/src/lang/ru-RU/mixins/Input.json

Just fix wrong descriptions for update events

docs: fix wrong descriptions for events

---

packages/vuetify/src/components/VIcon/VIcon.ts
packages/vuetify/src/services/icons/presets/index.ts
packages/vuetify/src/util/helpers.ts
packages/vuetify/types/index.d.ts
packages/vuetify/types/presets/index.d.ts
packages/vuetify/types/services/icons.d.ts
packages/vuetify/types/test/plugin.ts

Improve icon service types
Fix our types

refactor(icons-service): improve typings

---

packages/vuetify/build/babel-transform-stylus-paths.js

refactor: delete unused variables

---

packages/vuetify/src/components/VCheckbox/VCheckbox.ts
packages/vuetify/src/components/VRadioGroup/VRadioGroup.js
packages/vuetify/src/components/VSwitch/VSwitch.js
packages/vuetify/src/styles/components/_index.sass
packages/vuetify/src/styles/components/_mixins.sass
packages/vuetify/src/styles/components/_selection-controls.sass
packages/vuetify/src/styles/settings/_variables.scss

Convert `selection-controls` to SASS
Convert framework to SASS
none

refactor(selection-controls): convert to SASS

---

packages/vuetify/src/components/VSelect/VSelect.js

Bug was only present in Box, Solo, Outline versions of V-Select.
fix #6844
<details>
```vue
```
</details>

fix(VSelect.js): Menu would open when removing a selected chip item.

---

packages/vuetify/types/index.d.ts

Add missing VuetifyGoToOptions properties to the types definition file
When using TypeScript, the $vuetify.goTo function is missing some of its possible properties.
By compiling the typescript types project and by running the linter. Also trying to consume the goto function, making sure the properties are recognised by TypeScript's compiler and its VSCode integration.
<details>
```vue
this.$vuetify.goTo(this.scrollPosition, {
container: this.$refs.dialog,
duration: 300,
offset: 0,
easing: "easeInOutCubic"
});
```
</details>

fix(VuetifyGoToOptions): add missing properties to types

---

packages/vuetify/src/components/VPicker/VPicker.sass
packages/vuetify/src/components/VPicker/VPicker.styl
packages/vuetify/src/components/VPicker/VPicker.ts
packages/vuetify/src/components/VPicker/_mixins.sass
packages/vuetify/src/components/VPicker/_variables.scss

Convert VPicker styles to SASS
Convert all framework styles to SASS
visually
Kitchen -> Date/Time pickers

refactor(VPicker): convert to SASS

---

packages/docs/src/lang/en/components/DataTables.json

hide-headers and hide-actions were still present in one example description. Also fixed another typo.
<details>
```vue
```
</details>

docs(fix-data-table)

---

packages/vuetify/src/services/theme/__tests__/theme.spec.ts
packages/vuetify/src/services/theme/index.ts
packages/vuetify/test/unit/components/VRadioGroup/__snapshots__/VRadioGroup.spec.js.snap

Use a vue instance to provide reactivity for applying theme changes.
Better user experience
jest
- [x My code follows the code style of this project.

feat(theme): add reactivity

---

packages/vuetify/src/components/VDataTable/VEditDialog.ts

Convert VEditDialog to TS
Convert framework to TS
none + IntelliSense
none

refactor(VEditDialog): convert to TS

---

packages/vuetify/src/stylus/components/_text-fields.styl

margin-top: 22px wasn't provided if there wasn't a placeholder provided.
fixes #6942
in codepen.
<details>
```vue
```
</details>
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] The PR title is no longer than 64 characters.
- [ x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).

fix(prefix position) provide margin-top

---

packages/vuetify/src/stylus/elements/_typography.styl
packages/vuetify/src/stylus/settings/_variables.styl

Remove the `v-btn` styling from `_typography.styl`.
Remove `$headings.button` from `_variables.styl`.
Fixes issue #6974 .
none
<details>
**Template**
```
<v-btn large>Button</v-btn>
```
_typography.styl
```
.v-btn
font-size: $headings.button.size
font-weight: $headings.button.weight
```
vuetify.css
```
.caption {
font-size: 12px !important;
font-weight: 400;
}
.v-btn {
font-size: 14px;
font-weight: 500;
}
```
vuetify.min.css
```
.caption{font-weight:400}.caption{font-size:12px!important} // There's no v-btn
```
</details>

Resolves #6974 v-btn font-size overwrite by typography css

---

packages/vuetify/src/stylus/components/_overflow-buttons.styl

Added Stylus rule for removing v-text-field top border in the v-overflow-bnt; noticeable with outline and prepend-icon props
fixes #6960 
playground.vue (only local/not included)
<details>
```vue
<v-overflow-btn outline prepend-icon="close"></v-overflow-btn>
```
</details>
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [ x] My code follows the code style of this project.

fix(overflow-btn top border)

---

packages/docs/src/examples/data-tables/search.vue

no-results, need to be placed on a template component in order to work.
<details>
```vue
```
</details>

Added missing template component to example

---

packages/vuetify/src/components/VBtn/VBtn.ts

This PR removes an unnecessary if statement on VBtn.ts file render function.
unit and e2e
<details>
```vue
```
</details>

refactor(VBtn): remove redundant if on component render function

---

packages/docs/src/lang/ja-JP/framework/Grid.json

Add Japanese translation for framework/Grid page.
Translate docs to Japanese.
none
<details>
```vue
```
</details>

docs: translate framework/Grid page to Japanese

---

packages/docs/src/lang/en/framework/Scroll.json

I added 'container' in the scroll documentation page to the list of options in the usage section.
This change fixes #7103

Fix #7103 in Scoll.json

---

packages/vuetify/src/components/VTextField/VTextField.ts

Reverts vuetifyjs/vuetify#7175

revert: fix(VTextField): clearable should respect readonly=true

---

packages/vuetify/src/components/VTextField/VTextField.sass

Fixes #5481 and #5634, both of which were previously fixed and closed but this regressed. It's regressed in both 1.5.14 and the alpha.
<details>
```vue
```
</details>

fix(VTextField): fix color of prefix/suffix when disabled

---

packages/vuetify/types/lib.d.ts

fixes #7267
We need somehow automate the test for lib.d.ts
wasn't

fix(typescript): missing components in lib.d.ts

---

packages/docs/src/examples/dividers/simple/verticalInset.vue

Fix VDivider example.
Fix inconsistent theme for vertical inset example.
Visually
<details>
```vue
```
</details>

docs(VDivider): Fix inset example theme.

---

package.json
packages/docs/package.json
packages/kitchen/package.json
packages/vuetify/package.json

add `lint:fix` script for all packages, fixes the tslint config path

chore: global lint:fix script

---

packages/vuetify/src/locale/ru.ts

Updated new RU localization messages for v.2.0
Requested at Discord: volunteers
Requested only to edit the file on Github 
NA
<details>
</details>

Update ru.ts for v.2.0

---

packages/vuetify/src/locale/fa.ts

Update new FA localization messages for version 2.0 and some improvements.
Requested at Discord: volunteers
none

fix(locale): update fa locale

---

README.md

The current link is for the documentation of the module, previous package links are for the
repositories, changed the link so it's the module repository as well. The module's README.md already
links to it's docs.
<details>
```vue
```
</details>

refactor(README.md): Replaced the docs link for the repo link.

---

packages/docs/src/data/i18n/languages.json

Add Vietnamese language to translate menu.

Add Vietnamese

---

packages/vuetify/src/locale/pt.ts

Add new v2.0 messages and update others.
i18n
none
<details>
```vue
```
</details>

chore(i18n): update pt translation

---

packages/docs/src/data/pages/components/OverflowBtns.json
packages/docs/src/examples/overflow-btns/playground.vue
packages/docs/src/examples/overflow-btns/simple/box.vue
packages/docs/src/examples/overflow-btns/simple/counter.vue
packages/docs/src/examples/overflow-btns/simple/disabled.vue
packages/docs/src/examples/overflow-btns/simple/editable.vue
packages/docs/src/examples/overflow-btns/simple/filled.vue
packages/docs/src/examples/overflow-btns/simple/hint.vue
packages/docs/src/examples/overflow-btns/simple/loading.vue
packages/docs/src/examples/overflow-btns/simple/menuProps.vue
packages/docs/src/examples/overflow-btns/simple/readonly.vue
packages/docs/src/examples/overflow-btns/simple/segmented.vue
packages/docs/src/examples/overflow-btns/usage.vue
packages/docs/src/lang/en/components/OverflowBtns.json
packages/docs/src/lang/en/meta.json

Update examples in prep for Vuetify 2.0
Co-authored-by: Elijah Kotyluk <elijah@elijahkotyluk.com>
More detail and clarity for use of component.

docs(VOverFlowBtn): update examples

---

packages/vuetify/src/globals.d.ts
packages/vuetify/src/install.ts

Workaround for memory leak caused by infinite global mixins being declared when in dev mode using HMR
Fix memory leak
Making changes in dev mode, triggering HMR for the documentation

fix(install): add property to Vue object to avoid memory leak

---

packages/docs/src/examples/hover/usage.vue

Change slot-scope to Vue 2.6 slot syntax.
<details>
```vue
```
</details>

(docs:fix) Update Hover Slot Syntax

---

packages/docs/src/examples/hover/usage.vue

Reverts vuetifyjs/vuetify#7512

docs(VHover) revert update slot syntax"

---

packages/vuetify/src/components/VChip/VChip.ts

Remove check for click:close listener in VChip.hasClose method.
Presence of close button shouldn't depend on presence of the listener. If I want to dynamically change visibility of a close button on v-chip I have to manually add / remove listeners. Also it isn't mentioned anywhere in the docs that just having click:close listener attached will make close button appear.
Manually.
1. Close button on VChip is visible when close property is set to true.
2. Close button on VChip is **invisible** when close property is set to false and listener is attached (through `click:close="close"`).

Remove check for click:close listener in VChip.hasClose

---

packages/vuetify/src/components/VBtnToggle/VBtnToggle.sass
packages/vuetify/src/components/VBtnToggle/VBtnToggle.ts
packages/vuetify/src/components/VBtnToggle/_variables.sass

Allow manual override of btn color/size, improve state visual clarity. Slightly deters from spec in that the non-active buttons have a lower opacity, but greatly improves visual clarity when using anything other than the default styles.
fixes #7420
visual
<details>
```vue
<template>
<div class="ma-5 pa-5">
<v-card
flat
class="py-5"
>
<v-card-text>
<v-layout
column
align-center
>
<v-btn-toggle
v-model="toggle_exclusive"
rounded
multiple
dark
>
<v-btn
value="a"
>
Option A
</v-btn>
<v-btn
value="b"
>
Option B
</v-btn>
<v-btn
value="c"
>
Option C
</v-btn>
<v-btn
value="d"
>
Option D
</v-btn>
<div class="my-5"></div>
<v-btn-toggle
v-model="toggle_exclusive"
rounded
multiple …
```

fix(VBtnToggle): restructure styles

---

packages/docs/src/data/pages/framework/Theme.json
packages/docs/src/lang/en/framework/Theme.json
packages/docs/src/snippets/js/vuetify_anchor_color.txt
packages/vuetify/src/services/theme/__tests__/__snapshots__/theme-utils.spec.ts.snap
packages/vuetify/src/services/theme/__tests__/__snapshots__/theme.spec.ts.snap
packages/vuetify/src/services/theme/__tests__/theme-utils.spec.ts
packages/vuetify/src/services/theme/utils.ts
packages/vuetify/types/services/theme.d.ts

resolves #6360
Added the ability to define an application's anchor color
Currently, the anchor color is defined as the application's primary color which may not always be desired
jest
<details>
```vue
// dev/index.js
const vuetify = new Vuetify({
theme: {
themes: {
options: {
// customProperties: true,
},
light: {
anchor: '#000'
}
}
},
lang: {
locales,
},
})
```
</details>

feat(theme): add anchor color support

---

packages/vuetify/src/util/console.ts
packages/vuetify/src/util/helpers.ts

Fix types of some places where empty arrays with implicit type would resolve to `never[]` type instead of `any[]` and cause TypeScript errors.
Running a simple TypeScript project with Vuetify was displaying 5 errors regarding Vuetify types, see below the screenshots.
<details>
<summary>Screenshots of errors</summary>
</details>
Weirdly, in editor, we can't see these errors in Vuetify source code but only inside a TS project using Vuetify under `node_modules/vuetify/src/util/{file}.ts` (it's probably due to some `tsconfig.json` options).
In TypeScript, empty arrays that have no explicit types are resolving to the type `never[]`, so pushing anything (even of `any` type) in to this array leads to a type error `"Argument of type 'any' is not assignable to parameter of type 'never'."`
It can …

fix(types): give explicit type to empty arrays

---

packages/vuetify/src/components/VDataIterator/VDataFooter.ts

fix(VDataFooter): Add missing translation

---

packages/docs/src/lang/ja-JP/components/DataTables.json

Reverts vuetifyjs/vuetify#7596

Revert "Fix japanese translation of DataTable"

---

packages/vuetify/src/components/VSparkline/VSparkline.ts
packages/vuetify/src/components/VSparkline/__tests__/__snapshots__/VSparkline.spec.ts.snap

sparkline was not rendering custom labels (scoped slot, labels prop) when using type bar
closes #7584
playground, unit tests
<details>
```vue
<template>
<v-card
class="mx-auto text-xs-center"
color="blue"
dark
>
<v-card-text>
<v-sheet color="rgba(0, 0, 0, .12)">
<v-sparkline
:value="value"
color="rgba(255, 255, 255, .7)"
height="100"
padding="24"
stroke-linecap="round"
label-size="12"
type="bar"
smooth
>
<template v-slot:label="item">
${{ item.value }}
</template>
</v-sparkline>
</v-sheet>
</v-card-text>
</v-card>
</template>
<script>
data: () => ({
value: [
423,
446,
675,
510,
590,
610,
760
],
labels: [
'a',
'b',
'c',
'd',
'e',
'f',
'g'
],
})
}
</script>
```
</details>

fix(VSparkline): show custom labels when using bars

---

packages/api-generator/src/variables.js
packages/vuetify/src/components/VList/VList.ts
packages/vuetify/src/components/VList/VListGroup.sass
packages/vuetify/src/components/VList/VListGroup.ts
packages/vuetify/src/components/VList/VListItem.ts
packages/vuetify/src/components/VList/VListItemGroup.ts
packages/vuetify/src/components/VList/__tests__/VList.spec.ts
packages/vuetify/src/components/VList/__tests__/VListGroup.spec.ts
packages/vuetify/src/components/VList/__tests__/VListItem.spec.ts
packages/vuetify/src/components/VList/__tests__/VListItemGroup.spec.ts
packages/vuetify/src/components/VList/__tests__/__snapshots__/VListGroup.spec.ts.snap
packages/vuetify/src/components/VList/__tests__/__snapshots__/VListItem.spec.ts.snap
packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts
packages/vuetify/src/components/VNavigationDrawer/__tests__/VNavigationDrawer.spec.ts
packages/vuetify/src/components/VSelect/VSelectList.ts
packages/vuetify/src/components/VSelect/__tests__/VSelect.spec.ts
packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelectList.spec.ts.snap

Created additional injected props to infer proper a11y for `v-list-item`. Added `v-navigation-drawer` interactions when used as an **app** element. Added correct a11y attributes for `v-list-group`.
**TODO:**
fix keyboard controls for list-groups, improved a11y for other possible interactions
<details>
```vue
<template>
<div>
<v-navigation-drawer app>
<h2>Nav list group</h2>
<v-list>
<v-list-group>
<template v-slot:activator>
<v-list-item-title>I'm a group</v-list-item-title>
</template>
<v-list-item to="/page1">
<v-list-item-title>Hello I'm a title</v-list-item-title>
</v-list-item>
<v-list-item
to="/page3"
disabled
>
<v-list-item-title>Hello I'm a title 2</v-list-item-title>
</v-list-item>
<v-list-item
v-for="i in 5"
:key="i"
@click="() => {}"
>
<v-list-item-title>Hello I'm a …
```

feat(VList/Item/Group): improve a11y

---

packages/api-generator/src/maps/v-banner.js
packages/docs/src/lang/en/components/Banners.json

docs(VBanner): api update for 2.0

---

packages/docs/src/lang/en/components/Avatars.json

docs(VAvatar): api update for 2.0

---

packages/api-generator/src/maps/v-breadcrumbs.js
packages/docs/src/lang/en/components/Breadcrumbs.json

docs(VBreadcrumbs): api update for 2.0

---

packages/api-generator/src/maps/v-dialog.js
packages/docs/src/lang/en/components/Dialogs.json
packages/docs/src/lang/en/generic/ScopedSlots.json
packages/docs/src/lang/en/generic/Slots.json
packages/vuetify/src/components/VDialog/VDialog.ts

docs(VDialog): update api for 2.0

---

packages/api-generator/src/maps/v-bottom-sheet.js
packages/docs/src/lang/en/components/BottomSheets.json

docs(VBottomSheet): api update for 2.0

---

packages/api-generator/src/maps/v-btn.js
packages/docs/src/lang/en/components/Buttons.json

docs(VBtn): api update for 2.0

---

packages/docs/src/lang/en/components/ButtonGroups.json

docs(VBtnToggle): api update for 2.0

---

packages/api-generator/src/maps/v-tooltip.js
packages/docs/src/lang/en/components/Tooltips.json

Updated props/slots/events/functions for `VTooltip` for v2.0
re #7694 
Visually.

Docs(VTooltip)--update api docs

---

.eslintrc.js
packages/docs/src/examples/app-bars/playground.vue
packages/docs/src/examples/avatars/playground.vue
packages/docs/src/examples/badges/playground.vue
packages/docs/src/examples/banners/playground.vue
packages/docs/src/examples/breadcrumbs/playground.vue
packages/docs/src/examples/inputs/playground.vue
packages/docs/src/examples/selects/playground.vue
packages/kitchen/src/pan/Sheets.vue
packages/vuetify/src/components/VAutocomplete/__tests__/VAutocomplete2.spec.ts
packages/vuetify/src/components/VBanner/VBanner.ts
packages/vuetify/src/components/VCalendar/util/__tests__/timestamp.spec.ts
packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts
packages/vuetify/src/components/VDataTable/__tests__/VDataTableHeader.spec.ts
packages/vuetify/src/components/VDataTable/__tests__/VMobileRow.spec.ts
packages/vuetify/src/components/VDataTable/__tests__/VRow.spec.ts
packages/vuetify/src/components/VDataTable/__tests__/VVirtualTable.spec.ts
packages/vuetify/src/components/VDataTable/mixins/__tests__/header.spec.ts
packages/vuetify/src/components/VItemGroup/__tests__/VItemGroup.spec.ts
packages/vuetify/src/components/VTimePicker/VTimePicker.ts
packages/vuetify/src/components/VTimePicker/__tests__/VTimePicker.spec.ts
packages/vuetify/src/mixins/activatable/__tests__/activatable.spec.ts
packages/vuetify/src/mixins/applicationable/__tests__/applicationable.spec.ts
packages/vuetify/src/mixins/elevatable/__tests__/elevatable.spec.ts
packages/vuetify/src/mixins/routable/__tests__/routable.spec.ts

Setup `array-bracket-spacing` rule in eslint config
see in discord
none

chore(ESLint): setup array-bracket-spacing

---

packages/docs/src/snippets/js/use_vuetify_alacarte.txt
packages/vuetify/src/directives/click-outside/index.ts
packages/vuetify/src/directives/index.ts
packages/vuetify/src/directives/resize/index.ts
packages/vuetify/src/directives/ripple/index.ts
packages/vuetify/src/directives/scroll/index.ts
packages/vuetify/src/directives/touch/index.ts
packages/vuetify/src/mixins/scrollable/index.ts

fixes #7684
<details>
```vue
```
</details>

fix(typescript): export directives in PascalCase

---

packages/docs/src/lang/en/components/Autocompletes.json
packages/docs/src/lang/en/components/Combobox.json
packages/docs/src/lang/en/components/Inputs.json
packages/docs/src/lang/en/components/OverflowBtns.json
packages/docs/src/lang/en/components/SelectionControls.json
packages/docs/src/lang/en/components/Selects.json
packages/docs/src/lang/en/components/Sliders.json
packages/docs/src/lang/en/components/TextFields.json
packages/docs/src/lang/en/components/Textarea.json
packages/vuetify/src/components/VCheckbox/VCheckbox.ts
packages/vuetify/src/components/VCheckbox/__tests__/__snapshots__/VCheckbox.spec.ts.snap
packages/vuetify/src/components/VInput/VInput.ts
packages/vuetify/src/components/VRadioGroup/VRadio.ts
packages/vuetify/src/components/VRangeSlider/__tests__/__snapshots__/VRangeSlider.spec.ts.snap
packages/vuetify/src/components/VSelect/VSelect.ts
packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect3.spec.ts.snap
packages/vuetify/src/components/VSlider/VSlider.ts
packages/vuetify/src/components/VSlider/__tests__/__snapshots__/VSlider.spec.ts.snap
packages/vuetify/src/components/VSwitch/VSwitch.ts
packages/vuetify/src/components/VSwitch/__tests__/__snapshots__/VSwitch.spec.ts.snap
packages/vuetify/src/components/VTextField/VTextField.ts
packages/vuetify/src/mixins/selectable/index.ts
packages/vuetify/src/mixins/validatable/__tests__/validatable.spec.ts
packages/vuetify/src/mixins/validatable/index.ts

**TODO:**
Properly setup validation states for input controls. Moved themeable to validatable to normalize color states.
- add new prop to `v-slider`, **track-fill-color**, change the fill color of the track
- add new prop to `v-select`, **item-color**, change the color of the selected items in the `v-select-list`
Infer white color on dark background (similar to tabs) but still allow override. Can now have different colored selects without affecting selected item colors.
Some bugs fixed along the way:
- `v-switch` didn't have the correct validation colors when in an error/success state
jest
<details>
```vue
<template>
<div class="ma-5 pa-5">
<v-card class="pa-5">
<v-text-field label="Field"></v-text-field>
<v-text-field
label="Field"
disabled
error
<v-textarea …
```

fix(validatable): setup proper validation state coloring on all inputs

---

.github/PULL_REQUEST_TEMPLATE.md

none
<details>
```vue
```
</details>

github: pull request template: fix grammar

---

packages/docs/src/lang/en/mixins/Validatable.json

none
<details>
```vue
```
</details>

docs(Validatable): fix a typo

---

packages/api-generator/src/maps/v-item-groups.js
packages/docs/src/lang/en/components/ItemGroups.json

docs(VItemGroup): API updates for 2.0

---

packages/api-generator/src/maps/v-rating.js
packages/docs/src/lang/en/components/Ratings.json
packages/vuetify/src/components/VRating/VRating.ts

docs(VRating): Update API for 2.0

---

packages/api-generator/src/helpers/default-slots.js

docs(VProgressLinear): Update API for 2.0

---

packages/vuetify/src/components/VOverlay/VOverlay.ts

docs(VOverlay): Update API for 2.0

---

packages/docs/src/lang/en/components/Paginations.json
packages/vuetify/src/components/VPagination/VPagination.ts

docs(VPagination): Update API for 2.0

---

packages/api-generator/src/helpers/default-slots.js
packages/vuetify/src/components/VProgressCircular/VProgressCircular.ts

docs(VProgressCircular): Update API for 2.0

---

packages/api-generator/src/maps/v-timeline-item.js
packages/docs/src/lang/en/components/Timelines.json

Cleans and updates component API for Vuetify 2.0

 docs(VTimeline): API update for 2.0

---

packages/vuetify/src/styles/elements/_global.sass
packages/vuetify/src/styles/tools/_utilities.sass
packages/vuetify/src/styles/utilities/_transition.sass

regressed in beta.9
build and look at vuetify.css and then look again

fix(style); bring back .v-application scope to utility classes

---

packages/docs/src/examples/item-groups/playground.vue
packages/docs/src/examples/item-groups/simple/active-class.vue
packages/docs/src/examples/item-groups/simple/mandatory.vue
packages/docs/src/examples/item-groups/simple/multiple.vue
packages/docs/src/examples/item-groups/usage.vue

text is not centered
https://next.vuetifyjs.com/en/components/item-groups
vs
https://vuetifyjscom-satsnizamc.now.sh/en/components/item-groups

docs: fixed item group examples

---

packages/api-generator/src/maps/v-date-picker.js
packages/docs/src/lang/en/components/DatePickers.json
packages/docs/src/lang/en/components/TimePickers.json

docs: missing time/date picker props and events

---

packages/api-generator/src/maps/v-sparkline.js
packages/docs/src/lang/en/components/Sparklines.json
packages/vuetify/src/components/VSparkline/VSparkline.ts

docs(VSparkline): Update API for 2.0

---

packages/api-generator/src/helpers/default-slots.js
packages/api-generator/src/maps/v-stepper.js
packages/docs/src/lang/en/components/Steppers.json
packages/vuetify/src/components/VStepper/VStepper.ts
packages/vuetify/src/components/VStepper/VStepperStep.ts

docs(VSteppers): Update API for 2.0

---

packages/docs/src/lang/en/components/Subheaders.json

docs(VSubheader): Update API for 2.0

---

packages/docs/src/lang/en/components/SystemBars.json

docs(VSystemBar): Update API for 2.0

---

packages/docs/src/components/core/OpenCollectiveBtn.vue

I made two minor spelling corrections.
Spelling errors found and fixed.
```vue
```
</details>

docs(OpenCollectiveBtn): fix spelling errors

---

packages/docs/src/components/doc/Heading.vue
packages/docs/src/components/getting-started/Lts.vue

Corrected the spelling of this property.
I corrected the spelling of the `inheritAttrs` property used with `export default {}` in a couple of files.
It will cause the corrected code portion to function.
I am unable to test this, but I trust it will work as intended.
```vue
```
</details>

fix: spelling of inheritAttrs

---

packages/api-generator/src/maps/v-tab.js
packages/api-generator/src/maps/v-tabs.js
packages/docs/src/lang/en/components/Tabs.json
packages/vuetify/src/components/VTabs/VTabs.ts

docs(VTabs): Update API for 2.0

---

packages/docs/src/lang/en/components/DataTables.json

Extraneous `.column.` is included in several slot names in the English text.
<details>
```vue
```
</details>

docs(vdatatable): fix slot names

---

packages/docs/src/lang/en/components/SimpleTables.json
packages/vuetify/src/components/VDataTable/VSimpleTable.ts

docs(VSimpleTable): Update API for 2.0

---

packages/docs/src/examples/alignment/example.vue
packages/vuetify/src/styles/settings/_utilities.scss

`text-start` and `text-end` classes don't exist in v2.0.0, this adds them in
These classes are documented as existing, and needed for the `start` and `end` alignment in `VDataTable`.
In browser.
<details>
```vue
```
</details>

fix(styles): add missing text-start and text-end classes

---

packages/vuetify/types/lib.d.ts

VToolbarSideIcon was removed in v2.0.0 but it looks like the reference in `types/lib.d.ts` was missed.
None.
<details>
```vue
```
</details>

fix(types): remove VToolbarSideIcon

---

packages/vuetify/src/components/VBottomNavigation/VBottomNavigation.sass

fix(VBottomNavigation): increase specificity of **v-bottom-navigation** styles

---

packages/vuetify/src/locale/cs.ts
packages/vuetify/src/locale/index.ts

I've added Czech localization
It makes it easier for Czech coders to develop web apps with correct localization
none

Added Czech translation

---

packages/vuetify/src/locale/he.ts

Add missing translation for hebrew locale
Current translation is missing some words.
visually

fix(locale): complete hebrew translation

---

packages/vuetify/src/mixins/dependent/index.ts

dependent mixin was typing this.overlay as an HTMLElement when it was
in fact a VOverlay instance.
closes #8240
<details>
```vue
<template>
<div>
absolute
temporary
>
<v-dialog
persistent
width="500"
>
<v-btn
color="red lighten-2"
dark
v-on="on"
>
Click Me
</v-btn>
</template>
<v-card>
<v-card-title
class="headline grey lighten-2"
primary-title
>
Privacy Policy
<v-card-text>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu …
```

[Bug] fix(VDialog): fix dialog error when clicking on overlay

---

packages/vuetify/src/components/VDataIterator/VDataFooter.sass
packages/vuetify/src/components/VDataTable/VDataTable.sass
packages/vuetify/src/components/VDataTable/VSimpleTable.sass

- `.v-data-table__empty-wrapper` has hover effect again, regressed in 13816f144f9fe493df0dbfd3258d4258e91bb105
- added `pointer-events: none` to `.v-data-table__empty-wrapper`
- added missing rtl styles
- moved styles not related to theming outside of `theme()`
visually
<details>
```vue
<template>
<v-btn block @click="$vuetify.rtl = !$vuetify.rtl" class="mb-12">toggle rtl: {{ $vuetify.rtl }}</v-btn>
<v-data-table item-key="name" class="elevation-1 mb-12" loading loading-text="Loading... Please wait"></v-data-table>
<v-data-table
height="300"
fixed-header
class="elevation-1 mb-12"
/>
<v-simple-table>
<thead><tr><th>Foo</th><th>Bar</th></tr></thead>
</v-simple-table>
</v-container>
</template>
<script>
data: () …
```

fix(VDataTable, VSimpleTable): missing rtl styles, other minor tweaks

---

packages/vuetify/src/components/VCalendar/VCalendarWeekly.ts
packages/vuetify/src/components/VCalendar/__tests__/__snapshots__/VCalendar.spec.ts.snap
packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.ts
packages/vuetify/src/components/VCalendar/util/props.ts

fixes #8096 and #8175
- The default for the end prop was interfering with the coalescing logic.
- The ripple directive was missing from the calendar-with-events mixin.
- #8096 
- #8175
- visually
<details>
```vue
<template>
<v-sheet class="v-fullscreen" color="grey lighten-1">
<v-toolbar fixed flat app color="white">
<v-btn outlined @click="setToday" class="mr-3">
Today
</v-btn>
<v-btn fab text small @click="prev">
<v-icon small>arrow_back_ios</v-icon>
</v-btn>
<v-btn fab text small @click="next">
<v-icon small>arrow_forward_ios</v-icon>
</v-btn>
<v-toolbar-title>{{ title }}</v-toolbar-title>
<v-menu bottom right>
<v-btn outlined v-on="on">
<span>{{ typeToLabel[type] }}</span>
<v-icon right>arrow_drop_down</v-icon>
</v-btn> …
```

fix(VCalendar): end date and ripple errors

---

packages/vuetify/src/components/VBtnToggle/VBtnToggle.sass

Fix VButtonsGroup borders between buttons (from two pixel wide to one pixel wide)
None
Before
After

fix(VBtnToggle ): fix borders between buttons

---

packages/docs/src/lang/en/styles/Spacing.json

Current Documentation describes 5 levels of spacing where the playground and code shows 12, updating documentation accordingly
Fixes misleading documentation, making the framework more accessible.
</details>

Updated spacing docs to reflect 12 spacing levels

---

packages/vuetify/src/locale/zh-Hant.ts

Update translation of zh-Hant
Improve existing add new translations.
none

Update translation of zh-Hant

---

packages/docs/src/lang/en/components/Application.json

spelling error
<details>
```vue
```
</details>

docs(application): fix typo

---

packages/docs/src/examples/expansion-panels/complex/advanced.vue

Currently the example changes the date regardless of whether OK or CANCEL is clicked. This fixes it so that it only updates when OK is clicked, as that seems to have been the intention of the example. At the least, cancel still selecting the date is wrong behavior.
<details>
```vue
```
</details>

docs(VExpansionPanel): fix advanced example

---

packages/vuetify/src/components/VDataTable/VSimpleTable.sass

chore(VDataTable): remove unused styles

---

packages/docs/src/data/pages/customization/SassVariables.json
packages/docs/src/lang/en/customization/SassVariables.json

Updated SassVariables.json doc file replacing info alert
"SCSS is used for variable files to support maps using indented syntax."
with warning alert about A-la-carte installation
Addresses #8366

docs: Update Sass Variables docs to include a-la-carte req

---

packages/vuetify/src/components/VMenu/VMenu.ts
packages/vuetify/src/mixins/activatable/__tests__/activatable.spec.ts
packages/vuetify/src/mixins/activatable/index.ts
packages/vuetify/src/mixins/menuable/index.ts

Add listeners to custom activators
fixes #7944
fixes #5890 
fixes #5860
Custom activators were not working at all
jest
<details>
```vue
<template>
<div class="ma-5 pa-5">
<v-container>
<v-btn
id="activator-click"
ref="act"
color="success"
>
click
</v-btn>
<v-menu
:activator="activator"
>
<v-card>
<v-card-text>
</v-card-text>
</v-card>
</v-menu>
<div class="ma-5"></div>
<v-btn
id="activator-hover"
color="error"
>
hover
</v-btn>
<v-menu
activator="#activator-hover"
open-on-hover
>
<v-card>
<v-card-text>
</v-card-text>
</v-card>
</v-menu>
</v-container>
</div>
</template>
<script>
data: () => ({
activator: null,
}),
mounted () {
this.activator = this.$refs.act
},
}
</script>
```
</details>

fix(activatable): add listeners for custom activators

---

packages/vuetify/types/lib.d.ts

I found that the VFileInput type was not in the lib.d.ts file so I added it.

Fix missing VFileInput type in types/lib.d.ts

---

packages/vuetify/src/components/VBadge/VBadge.sass
packages/vuetify/src/components/VBadge/_variables.scss

Enable unused sass variables.
I want to use the following sass variables.
```
$badge-top
$badge-right
```
visually
<details>
```vue
<template>
<v-container>
<v-badge>
<template v-slot:badge>0</template>
<v-icon>mail</v-icon>
</v-badge>
</v-container>
</template>
```
</details>

fix(VBadge): enable unused variable (-top, -right)

---

packages/vuetify/src/components/VRangeSlider/VRangeSlider.ts
packages/vuetify/src/components/VSlider/VSlider.ts

v-range-slider was not emitting focus/blur events
closes #8290
playground
<details>
```vue
<template>
<v-range-slider v-model="sliderData" height="10" :min="0" :max="100" :step="1" @focus="onfocus()" @blur="onblur()" ref="range"></v-range-slider>
<v-text-field></v-text-field>
<v-slider v-model="sliderData2" height="10" :min="0" :max="100" :step="1" @focus="onfocus()" @blur="onblur()"></v-slider>
{{ sliderData }} <br/>
{{ sliderData2 }} <br/>
isfocus: {{ isFocused }}
</v-container>
</template>
<script>
data: () => ({
sliderData: [10,30],
sliderData2: 30,
isFocused: false,
}),
methods:{
onfocus(){
this.isFocused = true;
},
onblur(){
this.isFocused = false;
}
}
}
</script>
```
</details>

[Bug] fix(VRangeSlider): fix focus/blur events not emitting

---

packages/vuetify/src/components/VTextField/VTextField.ts

fixes #8393
visually
<details>
```vue
<template>
<v-container>
Type something
<v-text-field v-model="label" :label="label" outlined/>
</v-container>
</template>
<script>
data: () => ({
label: "Label"
}),
}
</script>
```
</details>

fix(VTextField): update label width on label change

---

packages/vuetify/src/services/theme/__tests__/__snapshots__/theme.spec.ts.snap
packages/vuetify/src/services/theme/__tests__/theme.spec.ts
packages/vuetify/src/services/theme/index.ts

- Prevent double stylesheet when vueMeta is used
- Fix theme issues when using vueMeta in SPA's (i.e. Nuxt `spa` mode)
Fixes https://github.com/nuxt-community/vuetify-module/issues/69
Fixes https://github.com/nuxt-community/vuetify-module/issues/103
jest - updated vue-meta unit test

fix(Theme): fix issues for spa with vue-meta

---

packages/vuetify/src/components/VAvatar/VAvatar.sass

Right v-avatar only really works properly with img elements. There are cases where svg is preferred such as identicon graphics generated client-side. This change makes svg work as expected.
Fixes #8367 
Functional support for SVG generated client-side
I did functional test on my own project using Vuetify by implementing this CSS change on my own project. I did not run comprehensive testing such as unit testing.
Use VAvatar with svg instead of img
<details>
```vue
<v-avatar>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="isolation:isolate" viewBox="0 0 20 20" version="1.1" shape-rendering="crispEdges"><path d="M8 15v1H4v1H3v3h14v-3h-1v-1h-4v-1h3v-1h1v-1h1v-3h1V7h-1V4h-1V3h-1V2H5v1H4v1H3v3H2v3h1v3h1v1h1v1h3z" fill="#F5CFA0"/><path d="M5 …
```

[Bug Report] Extend v-avatar functionality to work with SVG

---

packages/vuetify/src/components/VWindow/VWindow.sass

fixes #8457 
<details>
```vue
<template>
<v-container>
<v-card width="600" class="mx-auto my-4 pa-4 text-center">
<v-carousel continuous height="300" show-arrows-on-hover>
<v-carousel-item v-for="(img,j) in imgs" :key="j" :src="img.src"></v-carousel-item>
</v-carousel>
<v-btn class="primary mt-5" @click="$vuetify.rtl = ! $vuetify.rtl"> Toggle RTL </v-btn>
</v-card>
</v-container>
</template>
<script>
data () {
return {
imgs: [
{ src: 'https://picsum.photos/600/400?random=1' },
{ src: 'https://picsum.photos/600/400?random=2' },
{ src: 'https://picsum.photos/600/400?random=3' },
],
}
},
}
</script>
```
</details>

fix(VWindow): wrong position of arrows on hover in rtl mode

---

packages/docs/src/lang/en/components/Grids.json

<details>
```vue
```
</details>

[Docs] Typo in Grids

---

packages/docs/src/examples/calendars/complex/events.vue
packages/docs/src/examples/calendars/playground.vue
packages/docs/src/examples/calendars/usage.vue
packages/docs/src/lang/en/components/Calendars.json

docs(VCalendar): switch usage and events examples, change icons to mdi

---

README.md

chore(README.md): update licence badge url

---

packages/vuetify/src/components/VBtn/VBtn.sass
packages/vuetify/src/components/VBtn/_variables.scss

fix #8358
Playground
<details>
```vue
<template>
<v-container>
<v-btn x-small>X-SMALL</v-btn>
<v-btn small>SMALL</v-btn>
<v-btn>DEFAULT</v-btn>
<v-btn large>LARGE</v-btn>
<v-btn x-large>X-LARGE</v-btn>
</v-container>
</template>
```
</details>

fix(VBtn): correct font-size for different VBtn sizes

---

packages/vuetify/src/components/VOverlay/VOverlay.sass

fix #2984
visually
<details>
```vue
<template>
<div>
<v-btn color="primary" dark @click.stop="dialog = true">Open Dialog 1</v-btn>
<v-btn color="primary" dark @click.stop="dialog2 = true">Open Dialog 2</v-btn>
<v-btn color="primary" dark @click.stop="dialog3 = true">Open Dialog 3</v-btn>
<v-menu bottom offset-y>
<v-btn slot="activator">A Menu</v-btn>
<v-list>
<v-list-tile v-for="(item, i) in items" :key="i" @click="">
<v-list-tile-title>{{ item.title }}</v-list-tile-title>
</v-list-tile>
</v-list>
</v-menu>
<v-dialog
fullscreen
transition="dialog-bottom-transition"
:overlay=false
scrollable
>
<v-card>
<v-toolbar style="flex: 0 0 auto;" dark class="primary">
<v-btn icon @click.native="dialog = false" dark>
</v-btn> …
```

fix(VOverlay): fix second dialog overlay animation problems

---

packages/vuetify/src/locale/de.ts

Missing translations for the de-locale were added
Complete existing translation
N/A

refactor(de.ts): update translation of de-locale

---

packages/api-generator/src/maps/v-data-table.js

incorrect props
closes #8044
<details>
```vue
```
</details>

docs(VDataTable): fixed incorrect props for body slots

---

packages/vuetify/src/locale/nl.ts

I've updated the locale keys in `nl.ts`
Some keys for 2.0 features were not yet translated
N/A

refactor(nl.ts): update translations in nl-locale

---

packages/vuetify/src/components/VTextField/VTextField.sass

Bug fix: enable the 'background-color' attribute when the 'outlined' attribute is specified.
Cannot change the color of v-text-field's background when the 'outlined' attribute is specified.
visually
<details>
```vue
<template>
<v-text-field outlined>
<v-text-field outlined background-color="blue">
</template>
```
</details>

fix(VTextField): remove !important flag

---

packages/vuetify/src/components/VCarousel/VCarousel.ts
packages/vuetify/src/components/VWindow/VWindow.sass

Fix #8273
visually
<details>
```vue
<template>
<v-container>
<v-flex xs6 class="pa-2">
<h3>Mandatory: true</h3>
<v-carousel>
v-for="(color, i) in colors"
:key="color"
>
<v-sheet
:color="color"
height="100%"
tile
>
<v-row
class="fill-height"
align="center"
justify="center"
>
<div class="display-3">Slide {{ i + 1 }}</div>
</v-row>
</v-sheet>
</v-carousel>
</v-flex>
<v-flex xs6 class="pa-2">
<h3>Mandatory: false</h3>
<v-carousel :mandatory="false">
v-for="(color, i) in colors"
:key="color"
>
<v-sheet
:color="color"
height="100%"
tile
>
<v-row
class="fill-height"
align="center"
justify="center"
>
<div class="display-3">Slide {{ i + 1 }}</div>
</v-row>
</v-sheet>
</v-carousel> …
```

fix(VCarousel): pass mandatory prop to the delimiters

---

packages/vuetify/src/components/VTabs/VTabs.sass

fixes #8596
visually
<details>
```vue
<template>
<v-container>
<v-tabs background-color="indigo" dark>
<v-tab class='green'>Option</v-tab>
<v-tab>Another Selection</v-tab>
<v-tab class='orange'>Items</v-tab>
<v-tab>Another Screen</v-tab>
</v-tabs>
<v-tabs background-color="indigo" dark>
<v-tabs-slider color="white" />
<v-tab class='green'>Option</v-tab>
<v-tab>Another Selection</v-tab>
<v-tab class='orange'>Items</v-tab>
<v-tab>Another Screen</v-tab>
</v-tabs>
</v-container>
</template>
```
</details>

fix(VTabs): slider hides behind the colored tab

---

packages/docs/src/data/pages/getting-started/UnitTesting.json
packages/docs/src/lang/en/getting-started/UnitTesting.json
packages/docs/src/snippets/html/testing_e2e_data_attributes.txt
packages/docs/src/snippets/js/testing_e2e_data_attributes.txt

Add E2E test guideline.
Simple usage of data-* for element pickup after unit test section.
<details>
```vue
```
</details>

docs(e2e testing): add E2E test

---

packages/docs/src/examples/expansion-panels/complex/advanced.vue

Fixed advanced.vue

---

packages/docs/src/data/pages/styles/Spacing.json
packages/docs/src/examples/spacing/simple/breakpoint-md.vue
packages/docs/src/lang/en/styles/Spacing.json

Add description about breakpoints in spacing utilities guide (#8545)

---

packages/vuetify/src/locale/fr.ts

Update french (fr) translation
Fix the wrong/missing translations.
None

Update french translation

---

packages/vuetify/src/locale/no.ts

Updateted missing translation of the word "Sort by"
<details>
```vue
```
</details>

feat(i18n): translate Sort by to Norwegian

---

packages/vuetify/src/components/VSwitch/_variables.sass

Allow to override SASS variables for VSwitch component. The change is basically based on similar concept from other components, using `!default` qualifier 
https://vuetifyjs.com/en/customization/sass-variables#sass-variables
Tested on a local project with custom SASS/SCSS variables configuration.
<details>
```vue
```
</details>

fix(VSwitch): allow override vars definition

---

packages/vuetify/src/components/VList/VListItem.sass

Fix #8327 
visually
<details>
```vue
<template>
<v-card
:dark="dark"
>
<v-card-title>Default color</v-card-title>
<v-list>
<v-list-item
@click="currItem = i"
v-for="(item, i) in items"
:key="i"
:href="item.href"
:input-value="i === currItem"
:disabled="item.disabled"
>
<v-list-item-title v-text="item.text" />
</v-list-item>
</v-list>
</v-card>
<v-card
:dark="dark"
>
<v-card-title>Transparent VList</v-card-title>
<v-list color="transparent">
<v-list-item
@click="currItem = i"
v-for="(item, i) in items"
:key="i"
:href="item.href"
:input-value="i === currItem"
:disabled="item.disabled"
>
<v-list-item-title v-text="item.text" />
</v-list-item>
</v-list>
</v-card>
<v-card
:dark="dark" …
```

fix(VListItem): add default active color (#8327)

---

packages/vuetify/src/components/VData/VData.ts

added proxy computed object for options prop to get around vue
limitation of new/old value being the same for watched objects
fixes #8707
playground
<details>
```vue
<template>
<div>
<v-container>
<v-data-table
:items="items"
:options.sync="paginationOptions"
:footer-props="{
itemsPerPageOptions: paginationOptions.itemsRange,
showCurrentPage: true,
showFirstLastPage: true,
}"
@update:options="updated"
/>
<v-btn @click="updatePage">Set page to 1</v-btn>
</v-container>
</div>
</template>
<script>
data: () => ({
paginationOptions: {
sortBy: ["h1"],
sortDesc: [true],
page: 1,
itemsPerPage: 2,
itemsRange: [1, 2]
},
headers: [
{ text: "h1", value: "itemData1" },
{ text: "h2", value: "itemData2" },
{ text: "h3", value: "itemData3" }
],
items: [
{ itemData1: 1, …
```

fix(VDataTable): detect changes in options prop

---

packages/docs/src/examples/grids/usage.vue

Resolves #8649
<details>
```vue
```
</details>

docs(grids): make usage example responsive

---

packages/docs/src/data/pages/components/ExpansionPanels.json

Update link to the source code for expansion panels.
Resolves #8747
* Link is currently https://github.com/vuetifyjs/vuetify/tree/master/packages/vuetify/src/components/VExpansionPanels (broken)
* Should be https://github.com/vuetifyjs/vuetify/tree/master/packages/vuetify/src/components/VExpansionPanel

Fix broken source link in expansion panels docs

---

packages/vuetify/src/components/VTooltip/VTooltip.sass

--fixed somehow got lost, bringing it back
See [VTooltip.ts#L189](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/components/VTooltip/VTooltip.ts#L189)
Related #6460
fixes #8894
<details>
```vue
```
</details>

fix(VTooltip): bring back --fixed in VTooltip.sass

---

packages/vuetify/src/locale/he.ts

"Sort by" is translated to Hebrew

fix: update hebrew translation

---

packages/vuetify/src/locale/id.ts

<details>
```vue
```
</details>

refactor(locale): update id translation

---

packages/vuetify/src/locale/ar.ts

Currecting arabic translation
visually

fix arabic translation.

---

packages/vuetify/src/locale/it.ts

updates it.ts translation of sortBy per discord user request
language is important

fix(locale) update it.ts sortBy

---

packages/vuetify/src/locale/it.ts

Correct some translation for italian
language is important
<details>
```vue
```
</details>
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] The PR title is no longer than 64 characters.
- [x ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).

fix(locale): add missing Italian translations

---

packages/vuetify/src/components/VStepper/VStepperContent.ts
packages/vuetify/src/components/VStepper/__tests__/VStepperContent.spec.ts

Reverse `isReverse` on rtl
#8978 
visually

fix(VStepper): fix transition in RTL

---

packages/docs/src/data/pages/components/Autocompletes.json
packages/docs/src/data/pages/components/Combobox.json
packages/docs/src/data/pages/components/FileInputs.json
packages/docs/src/data/pages/components/OverflowBtns.json
packages/docs/src/data/pages/components/Selects.json
packages/docs/src/data/pages/components/TextFields.json
packages/docs/src/examples/autocompletes/simple/dense.vue
packages/docs/src/examples/combobox/simple/dense.vue
packages/docs/src/examples/file-inputs/simple/dense.vue
packages/docs/src/examples/overflow-btns/simple/dense.vue
packages/docs/src/examples/selects/simple/dense.vue
packages/docs/src/examples/text-fields/playground.vue
packages/docs/src/examples/text-fields/simple/dense.vue
packages/docs/src/lang/en/components/Autocompletes.json
packages/docs/src/lang/en/components/Combobox.json
packages/docs/src/lang/en/components/FileInputs.json
packages/docs/src/lang/en/components/Inputs.json
packages/docs/src/lang/en/components/OverflowBtns.json
packages/docs/src/lang/en/components/Selects.json
packages/docs/src/lang/en/components/TextFields.json
packages/vuetify/src/components/VFileInput/VFileInput.sass
packages/vuetify/src/components/VInput/VInput.sass
packages/vuetify/src/components/VInput/VInput.ts
packages/vuetify/src/components/VOverflowBtn/VOverflowBtn.sass
packages/vuetify/src/components/VSelect/VSelect.sass
packages/vuetify/src/components/VSelect/VSelect.ts
packages/vuetify/src/components/VTextField/VTextField.sass
packages/vuetify/src/components/VTextField/VTextField.ts
packages/vuetify/src/components/VTextField/_mixins.sass

Hi,
as @MajesticPotatoe suggested in the previous PR #8755 
This PR will add a dense prop to this VInput components:
- VTextField
- VAutocomplete
- VOverflowBtn
- VSelect
- VCombobox
- VFileInput
VTextField is not sizeable and field height in some cases is too large.
for example densed app-bar.
#1846
visually
<details>
Icon font md
```vue
<template>
<div class="pa-6">
<v-btn @click="isDense = !isDense">
Toggle dense
</v-btn>
<br>
<br>
<v-form>
<v-container>
<v-row>
<v-col cols="12" sm="6" md="3">
<v-text-field
:dense="isDense"
hint="this is a hint"
label="Regular"
</v-col>
<v-col cols="12" sm="6" md="3">
<v-text-field
:dense="isDense"
hint="this is a hint"
label="Regular"
</v-col>
<v-col cols="12" sm="6" md="3">
<v-text-field …
```

feat(VInput): add dense

---

packages/docs/src/lang/en/components/ChipGroups.json

Fix minor typo in VChipGroup docs

---

packages/api-generator/src/index.js
packages/api-generator/src/maps/v-intersect.js
packages/docs/src/components/doc/ApiItem.vue
packages/docs/src/data/drawerItems.json
packages/docs/src/data/pages/directives/Intersect.json
packages/docs/src/examples/intersect/usage.vue
packages/docs/src/lang/en/directives/Intersect.json
packages/docs/src/lang/en/meta.json
packages/docs/src/lang/en/vuetify/AppDrawer.json
packages/docs/src/snippets/html/directive_intersect.txt
packages/docs/src/snippets/html/directive_intersect_once.txt
packages/docs/src/snippets/html/directive_intersect_quiet.txt
packages/vuetify/src/directives/index.ts
packages/vuetify/src/directives/intersect/__tests__/intersect.spec.ts
packages/vuetify/src/directives/intersect/index.ts
packages/vuetify/src/globals.d.ts

Created new directive that utilizes the [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) api.
Provide a directive that allows invoking methods when elements are intersected by the user's scroll
jest
<details>
```vue
```
</details>

feat(VIntersect): add new directive

---

packages/vuetify/src/components/VDataTable/VDataTable.sass
packages/vuetify/src/components/VDataTable/VDataTable.ts
packages/vuetify/src/components/VDataTable/VSimpleTable.sass
packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap

expanded row no longer has hover effect. table tr now has selected
class when selected and another background color as in 1.5
closes #8368
playground
<details>
```vue
<template>
<div>
<v-data-table
show-select
show-expand
>
<template v-slot:expanded-item>
<td colspan="8">
Hello
</td>
</template>
</div>
</template>
<script>
data () {
return {
search: null,
headers: [
{
align: 'left',
value: 'name',
},
],
desserts: [
{ …
```

fix(VDataTable): fixed table row classes

---

packages/api-generator/src/maps/v-data-table.js
packages/docs/src/data/pages/components/DataTables.json
packages/docs/src/examples/data-tables/simple/filterable-columns.vue
packages/docs/src/lang/en/components/DataTables.json
packages/vuetify/src/components/VDataTable/VDataTable.ts
packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts
packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap
packages/vuetify/src/components/VDataTable/mixins/header.ts

if filterable is set to false on header item, it is no longer searchable
closes #8242
playground and unit tests
<details>
```vue
<template>
<div>
<v-text-field label="search" v-model="search"></v-text-field>
<v-data-table
</div>
</template>
<script>
data () {
return {
search: null,
headers: [
{
align: 'left',
value: 'name',
filterable: false
},
{ text: 'Calories', value: 'calories', filter: v => v > 400, filterable: false },
],
desserts: [
{
calories: 159,
fat: …
```

feat(VDataTable): added filterable property to header items

---

packages/vuetify/src/components/VList/VListItem.ts
packages/vuetify/src/components/VList/__tests__/VListItem.spec.ts

Issue https://github.com/vuetifyjs/vuetify/issues/9060

Elements with [role] that require specific children [role]s, are missing.

---

packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.ts

Check if multi-day event part is hidden for every day. If it is, count it as hidden for that day and add event-more label.
The `updateEventVisibility` method checks if the event does fit into day view. If it doesn't, it hides it for that day and all the other days that it is in.
The problem is that it didn't check for already hidden events, didn't count them and didn't show "event-more" label.
Fixes #8263
Visually
<details>
```vue
<template>
<v-sheet height="400">
<v-calendar
ref="calendar"
v-model="focus"
:event-color="getEventColor"
:event-margin-bottom="3"
:now="today"
:type="type"
></v-calendar>
</v-sheet>
</template>
<script>
data: () => ({
today: "2019-01-08",
focus: "2019-01-08",
type: "month",
events: [
{
name: "Event1",
start: …
```

fix(VCalendar): fix event-more labels in month view

---

packages/vuetify/src/components/VNavigationDrawer/VNavigationDrawer.ts
packages/vuetify/src/components/VNavigationDrawer/__tests__/VNavigationDrawer.spec.ts

Fixes #8133
unit, visually
<details>
```vue
<template>
:mini-variant.sync="mini"
:expand-on-hover="expandOnHover"
app
>
<v-list-item-group dense v-model="current">
<template v-for="item in items">
<v-row
v-if="item.heading"
:key="item.heading"
align="center"
>
<v-col cols="6">
<v-subheader v-if="item.heading">
{{ item.heading }}
</v-subheader>
</v-col>
<v-col
cols="6"
class="text-center"
>
<a
href="#!"
class="body-2 black--text"
>EDIT</a>
</v-col>
</v-row>
<v-list-group
v-else-if="item.children"
:key="item.text"
v-model="item.model"
:prepend-icon="item.model ? item.icon : item['icon-alt']"
append-icon=""
>
<template v-slot:activator>
<v-list-item>
{{ item.text }} …
```

fix(VNavigationDrawer): should emit update:mini-variant

---

packages/vuetify/src/services/goto/index.ts

When using $vuetify.goTo with a target element and container should scroll element to container top, not page top
fixes #8662 and could be used to fix #6933 by specifying the container
Playground.vue
<details>
```vue
<template>
<v-container>
<v-row>
<v-col>
<h3>Page scroll</h3>
<v-btn @click="scroll('first')">
Scroll to "#First"
</v-btn>
<v-btn @click="scroll('second')">
Scroll to "#Second"
</v-btn>
<v-btn @click="scroll(300)">
Scroll to 300
</v-btn>
</v-col>
<v-col>
<h3>Div scroll</h3>
<v-btn @click="divScroll('divFirst')">
Scroll to "#First"
</v-btn>
<v-btn @click="divScroll('divSecond')">
Scroll to "#Second"
</v-btn>
<v-btn @click="divScroll(100)">
Scroll to 100
</v-btn>
</v-col>
</v-row>
<v-row>
<v-col>
<v-card id="container" class="mb-4" style="height: 300px; overflow-y: scroll;"> …
```

fix(goTo): goTo scrolls to container top

---

packages/vuetify/src/components/VTextField/VTextField.ts
packages/vuetify/src/components/VTextField/__tests__/VTextField.spec.ts

Fixes #7916
unit, visually
<details>
```vue
<template>
<v-container>
<v-card class="card">
<v-card-title>VTextField</v-card-title>
<v-card-text>
<v-text-field
@focus="focus('VTextField')"
@input="input('VTextField')"
@change="change('VTextField')"
@blur="blur('VTextField')"
clearable
/>
</v-card-text>
</v-card>
<v-card class="card">
<v-card-title>VTextarea</v-card-title>
<v-card-text>
<v-textarea
@focus="focus('VTextarea')"
@input="input('VTextarea')"
@change="change('VTextarea')"
@blur="blur('VTextarea')"
clearable
/>
</v-card-text>
</v-card>
</v-container>
</template>
<script>
methods: {
focus: component => console.log('focus', component),
input: component => console.log('input', component),
change: component => console.log('change', component),
blur: component => …
```

fix(VTextField): should respect events in correct order (#7916)

---

packages/docs/src/examples/button-groups/intermediate/app-bar.vue
packages/docs/src/examples/button-groups/intermediate/qwerty.vue
packages/docs/src/examples/button-groups/usage.vue
packages/docs/src/lang/en/components/ButtonGroups.json
packages/vuetify/src/components/VBtnToggle/VBtnToggle.sass
packages/vuetify/src/components/VBtnToggle/VBtnToggle.ts
packages/vuetify/src/components/VBtnToggle/__tests__/VBtnToggle.spec.ts
packages/vuetify/src/components/VBtnToggle/_variables.sass
packages/vuetify/src/components/VBtnToggle/_variables.scss

resolves #4325
<details>
```vue
```
</details>

feat(VBtnToggle): add group prop

---

packages/vuetify/src/locale/sl.ts

Added missing items and changed some for consistent word usage.
<details>
```vue
```
</details>

Update sl locale.

---

packages/vuetify/src/locale/et.ts

Improved Estonian translations

Improved Estonian translations

---

packages/vuetify/src/locale/hr.ts

This is https://github.com/vuetifyjs/vuetify/pull/9124#issuecomment-536022931, with the correct branch.

Grammar fixes, improvements (Croatian locale)

---

packages/docs/src/examples/data-tables/intermediate/server.vue

The old code doesn't works on v2.0.19

Fixing server.vue

---

packages/docs/src/examples/autocompletes/intermediate/slots.vue

Little change to an autocomplete example. Name and Title centered within the image.
Design change to center text because it was align weirdly to the right.
Visually (with codepen) https://codepen.io/vrufine/pen/qBWGmLX

Center text for autocomplete example

---

packages/api-generator/src/index.js
packages/api-generator/src/maps/v-mutate.js
packages/docs/src/data/drawerItems.json
packages/docs/src/data/pages/directives/Mutate.json
packages/docs/src/examples/mutate/simple/once.vue
packages/docs/src/examples/mutate/usage.vue
packages/docs/src/lang/en/directives/Mutate.json
packages/docs/src/lang/en/meta.json
packages/docs/src/lang/en/vuetify/AppDrawer.json
packages/docs/src/public/sitemap.xml
packages/vuetify/src/directives/index.ts
packages/vuetify/src/directives/mutate/__tests__/mutate.spec.ts
packages/vuetify/src/directives/mutate/index.ts
packages/vuetify/src/globals.d.ts

Add a new `mutate` directive.
Required in #9140 
`jest` + markup
<details>
```vue
<template>
<div v-mutate="cb">
{{ content }}
</div>
<v-btn @click="content = 1">1</v-btn>
<v-btn @click="content = 2">2</v-btn>
</v-container>
</template>
<script>
data: () => ({
content: 0,
}),
methods: {
cb (mutations) {
console.log(mutations)
}
},
}
</script>
```
</details>

feat(mutate): add a new directive

---

packages/vuetify/src/components/VInput/VInput.sass
packages/vuetify/src/components/VTextField/VTextField.sass
packages/vuetify/src/components/VTextField/VTextField.ts

Following #8810 PR
I was wrong about label on dense, thanks to @cafedo, @MajesticPotatoe and @DRoet for the correction
fix #9105 
visually

fix(VTextField): show label on dense

---

packages/docs/src/examples/footer/intermediate/teal-footer.vue

The use of `VCardAction` appears to mess with the hyphen spacing. pr #7901 was submitted to address
the issue, but failed travis tests. This pr is my suggested alternative fix, which more closely
follows the indigo-footer example syntax.
Minor fix of hyphen spacing.
Visually.
<details>
```vue
```
</details>

fix(teal-footer): fix hyphen spacing in footer text

---

packages/vuetify/src/components/VPicker/VPicker.sass

Reset picker body margin on full-width
fixes #9119 
fixes #9141 
visually
https://codepen.io/dev0x0/pen/BaBeLxd

fix(VTimePicker): reset margin on full width

---

packages/docs/src/examples/text-fields/simple/dense.vue

docs(VTextField): fix dense filled example

---

MIGRATION.md

The existing link https://github.com/orgs/vuetifyjs/people/KaelWD leads to a 404 (at least for me as a non-community member); changed it to the user page https://github.com/KaelWD
fixes broken link

Fix KaelWD github link in migration docs

---

packages/vuetify/src/components/VBtnToggle/VBtnToggle.sass

Removed `background-color: transparent !important` as it should be delegated to the button's `text` prop. This also causes v-button-toggle with `group` prop to not have a transparent background, which it should have according to [the docs](https://vuetifyjs.com/en/components/button-groups#api). `.v-btn-toggle--group > .v-btn.v-btn:not(.v-btn--active` was also removed as it affects the text color in dark theme.
The button `color` nested in v-button-group can't be changed since v2.1.1 as it's being overridden by `background-color: transparent !important`. This fix would revert the issue.
It also fixes the `group` prop's styles.
Fixes #9226.
The changes are tested in [codepen](https://codepen.io/bjornlu/pen/JjjjpPB), manually editing the css in dev tools.
<details>
```vue
// Paste your FULL …
```

fix(VButtonToggle): fix color theming

---

packages/vuetify/types/presets/index.d.ts

fix(types): fix lang option name in preset

---

packages/vuetify/src/components/VTextarea/VTextarea.sass

When VTextArea with solo, fix clear icon overlapped by the scrollbar.
#8910 
visually
<details>
```vue
<template>
<v-app>
<v-flex xs2>
<v-textarea
clearable
solo
label="Text"
value="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
rows="1"
></v-textarea>
</v-flex>
<v-flex xs2>
<v-textarea
clearable
label="Text"
value="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
rows="1"
></v-textarea>
</v-flex>
</v-container>
</v-app>
</template>
```
</details>

fix(VTextArea): fix clear icon overlapped by the scrollbar

---

packages/docs/src/examples/grids/simple/spacer.vue

Updated the old v-spacer syntax of `<div class="flex-grow-1"></div>` to the new syntax `<v-spacer></v-spacer>` for the example code in the v-spacer section of the grid system documentation.
The example for the v-spacer section of the grid system documentation shows spacers but does not use the actual v-spacer component it is describing.

docs(spacer): updated old v-spacer syntax with new syntax for grid doc

---

packages/vuetify/src/mixins/activatable/__tests__/activatable.spec.ts
packages/vuetify/src/mixins/activatable/index.ts

`getActivator` was previously using the click event's `currentTarget` when the activator slot was used, but #8121 broke this by calling the method on mount and caching the slot root element. This would cause the menu to be offset as it would use the inner component's empty wrapper element instead of the actual activator.
#9163 broke this even further by hiding this element, resulting in its position being 0,0
We now use the event target again when possible as it is most likely to be the intended element being explicitly bound by the user. If this is not possible then the activator is retrieved from the inner component instead. 
fixes #8846
<details>
```vue
<template>
<v-container>
<v-menu v-model="menu">
<template v-slot:activator="{ on: menu }">
<v-tooltip …
```

fix(activatable): get activator element from event or nested component

---

packages/vuetify/src/components/VSparkline/VSparkline.sass
packages/vuetify/src/components/VSparkline/VSparkline.ts
packages/vuetify/src/components/VSparkline/__tests__/__snapshots__/VSparkline.spec.ts.snap

Fix #8557
visually
<details>
```vue
<template>
<v-sparkline
:value="value"
:gradient="gradient"
:smooth="radius || false"
:padding="padding"
:line-width="lineWidth"
:stroke-linecap="lineCap"
:gradient-direction="gradientDirection"
:fill="fill"
:type="type"
:auto-line-width="autoLineWidth"
auto-draw
:show-labels="showLabels"
:label-size="labelSize"
></v-sparkline>
<v-row>
<v-row class="fill-height" align="center">
<v-subheader class="pl-0">Type</v-subheader>
<v-btn-toggle v-model="type" mandatory>
<v-btn small text value="bar">bar</v-btn>
<v-btn small text value="trend">trend</v-btn>
</v-row>
</v-col>
<v-col cols="12" md="6">
<v-row class="fill-height" align="center">
<v-subheader …
```

fix(VSparkline): add label color for light/dark theme (fix #8557)

---

packages/vuetify/src/components/VGrid/_grid.sass

fix #8608 
Adds `flex-wrap: wrap` to `.container.fill-height` and adds `flex: 1 1 100%` to `.container.fill-height > .row`
Fixes #8608

fix(container): adjust container fill-height

---

packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.sass

Nested expansion-panels get active class of parent since it's within an active panel
fix #8677
<details>
```vue
```
</details>

fix(vexpansionpanel): nested expansion-panels get active class of parent

---

packages/vuetify/src/components/VAlert/VAlert.ts

fixes #9386
Typo
visually
<details>
```vue
```
</details>

fix(VAlert): typo in computedIcon

---

packages/docs/src/examples/chips/playground.vue

Fixed a bug in the Chip component documentation where the "Avatar: none" radio button in the playground example adds an avatar and does not clear it.
The radio button should clear the avatar on the chip as it's supposed to. Users will know the correct syntax for removing an avatar from a chip.

docs(chips): Playground "Avatar: none" Bug Fix

---

packages/docs/src/snippets/js/import_fa_svg.txt

Fix typo in docs: customizations/icons/fa_svg

---

packages/docs/src/examples/parallax/simple/content.vue

Proper grid row>col
Create a v-col to contain the h1 and h4 elements
Proper demonstrationof how to use the new grid
Visually on codepen
https://codepen.io/vrufine/pen/JjjRzqM?editors=1000
<details>
```vue
<div id="app">
<v-parallax
dark
src="https://cdn.vuetifyjs.com/images/backgrounds/vbanner.jpg"
>
<v-row
align="center"
justify="center"
>
<v-col class="text-center" xs="12">
<h1 class="display-1 font-weight-thin mb-4">Vuetify.js</h1>
<h4 class="subheading">Build your application today!</h4>
</v-col>
</v-row>
</v-parallax>
</v-app>
</div>
```
</details>

Update parallax simple example with proper grid use

---

packages/vuetify/src/components/VList/VListItem.sass

Small icon is centered just like when it is not dense
#9331 
visually
<details>
```vue
<template>
<v-app>
<v-content>
<v-container>
<v-card>
<v-card-title>List Icon Test</v-card-title>
<v-list dense>
<v-list-item @click.stop>
<v-icon small>mdi-plus</v-icon>
Add an item
</v-list-item>
</v-list>
</v-card>
</v-container>
</v-content>
</v-app>
</template>
```
</details>

fix(vlistitem): fix to misplaced small icon in dense list

---

packages/docs/src/components/getting-started/Team.vue

Updates the Meet the Team page to include myself as a new Vuetify team member
Updates array of members in `Team.vue`
Happy to join the team :)
none
<details>
```vue
```
</details>

Add Sean to meet the team page

---

packages/vuetify/src/locale/no.ts

Improved some of the translations to Norwegian
The Norwegian translation for VCarusell wasn't translated properly, and moreEvents could use better language.
</details>

fix(locale): update Norwegian translation

---

packages/docs/src/examples/layouts/centered.vue

Data is being removed because it's not used anywhere

Remove data attribute

---

packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbs.ts
packages/vuetify/src/components/VBreadcrumbs/VBreadcrumbsDivider.ts
packages/vuetify/src/components/VBreadcrumbs/index.ts
packages/vuetify/src/components/VTimePicker/SelectingTimes.ts
packages/vuetify/src/components/VTimePicker/VTimePicker.ts
packages/vuetify/src/components/VTimePicker/VTimePickerTitle.ts
packages/vuetify/src/components/VTreeview/VTreeviewNode.ts

Removes circular dependencies in VBreadcrumbs, VTimePicker and VTreeview by either moving the critical dependency out of the circle (VBreadcrumbs and VTimePicker), or minimising its scope in case of a self-reference (VTreeview).
Improves the code quality by resolving circular dependencies. Having these could create nasty bugs in the future. It also resolves warnings/errors from build tools and linters.
Closes #9337 and #7033.
Checking (by using Rollup) that all to be fixed circles where found before, but none after applying the changes.

chore: Removes circular dependencies

---

packages/docs/src/data/pages/components/SystemBars.json

Fix typo.The previous path to tabs page was not found (404). I just add "s" to tab.
<details>
```vue
```
</details>

chore(SystemBars): fix navigation

---

packages/docs/src/lang/en/components/SkeletonLoaders.json

I may be wrong but this is what some quick code skimming led me to believe.  
Feel free to enhance.

docs(VSkeleton): add description for loading prop

---

packages/vuetify/src/components/VSheet/_variables.scss

Set the default sheet border radius like the card default border radius.
I tryed to apply "tile" prop to sheet and nothing changed, then checked the variables.scss and confirmed that the sheet default border radius is 0 and when tile prop is applied, it re-apply the border radius 0 property.
None. Just checked how card border radius was set and copied to sheet's variables.
<details>
```scss
$sheet-border-radius: $border-radius-root !default;
```
</details>

Update sheet variables to default border radius

---

packages/vuetify/src/components/VDataTable/VDataTableHeaderMobile.ts

Hides the select element on mobile when there are no sortable headers
fixes #9209
visually
https://jsfiddle.net/1s0xua3f/

feature(datatable): hide sort by select on mobile if not needed

---

packages/vuetify/src/components/VCheckbox/VCheckbox.ts
packages/vuetify/src/components/VRadioGroup/VRadio.ts
packages/vuetify/src/components/VRadioGroup/__tests__/VRadioGroup.spec.ts
packages/vuetify/src/components/VRadioGroup/__tests__/__snapshots__/VRadioGroup.spec.ts.snap
packages/vuetify/src/components/VSwitch/VSwitch.sass
packages/vuetify/src/components/VSwitch/_variables.sass
packages/vuetify/src/styles/components/_selection-controls.sass

This PR require #9494 to work as expected
Works on:
- VSwitch
- VCheckbox
- VRadioGroup
Fixes #9381 
visually | unit
```vue
<v-switch
dense
label="Dense"
></v-switch>
<v-switch
dense
inset
label="Dense"
></v-switch>
<v-checkbox
dense
label="Dense"
></v-checkbox>
<v-radio-group dense>
<v-radio label="Radio 1" value="radio-1"></v-radio>
<v-radio label="Radio 2" value="radio-2"></v-radio>
```

fix(Selection Controls): Dense Prop 

---

packages/vuetify/src/locale/uk.ts

Add missed translations and fix some existen strings

fix: Ukrainian translation

---

packages/docs/src/examples/selection-controls/playground.vue

Changes:
- Renamed 3 headers bad-positionated, so they now match the right section. 
- Added a radios group example on the radios section.
All the changes refer to: https://vuetifyjs.com/es-MX/components/selection-controls#playground
By changing the above explained, it's easier to understand what the code does.
I have made the testing on the CodePen provided by the example itself and then adapted on the source.
<details>
```vue
<template>
<div>
<v-checkbox v-model="disabled" class="mx-2" label="Disabled"></v-checkbox>
<v-checkbox v-model="readonly" class="mx-2" label="Read-only"></v-checkbox>
<v-checkbox v-model="error" class="mx-2" label="Error"></v-checkbox>
<v-checkbox v-model="success" class="mx-2" label="Success"></v-checkbox> …
```

docs: update selection-controls playground

---

packages/vuetify/types/lib.d.ts

fix(typescript): missing VLazy/VSkeletonLoader declaration

---

packages/vuetify/src/locale/pt.ts

<details>
```vue
```
</details>

fix(locale): update Portuguese translation

---

MIGRATION.md

remove unnecessary dot in the bullet points
<details>
```vue
```
</details>

docs: remove unnecessary dot in the bullet points

---

packages/vuetify/src/components/VTreeview/VTreeview.sass

fixes #9475
playground
<details>
```vue
<template>
<v-container>
<div class="v-icon v-treeview-node__toggle mdi mdi-cached v-treeview-node__toggle--loading" />
<div class="v-icon mdi mdi-cached v-treeview-node__toggle--loading" />
<v-divider />
<v-treeview :load-children="fetch" :items="items" open-on-click selectable />
</v-container>
</template>
<script>
data: () => ({
items: [{ id: 1, name: 'All Breweries', children: [] }],
}),
methods: {
async fetch () {
await new Promise((resolve) => { setTimeout(() => resolve(), 5000) })
this.items[0].children = [{ id: 2, name: 'Some Brewery', children: [] }]
},
},
}
</script>
```
</details>

fix(VTreeview): stuttering animation of toggle icon when loading

---

packages/vuetify/src/styles/settings/_light.scss

By provided links in the description for the issue, understood the problem and found places where set text color and opacity (changed from `0.54` to `0.6` ) .
Fixes opened issue #9366 
Now sure how to test , that's why the only draft PR so need help with testing this.

fix:fix opacity for secondary text folloing by md2

---

packages/vuetify/src/components/VData/VData.ts
packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts
packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap

removes `immediate: true` from items-per-page watcher. It seems like the only reason I added it in the first place was to be able to check the value in a toHaveBeenCalled in test. Using snapshots instead.
closes #9599
manually, test
<details>
```vue
<template>
<v-container>
<v-data-table
:options="options"
:server-items-length="totalDesserts"
@update:items-per-page="test"
</v-container>
</template>
<script>
data () {
return {
desserts: [],
loading: true,
options: {
page: 1,
itemsPerPage: 15
},
headers: [
{
align: 'left',
value: 'name',
},
{ …
```

fix(VDataTable): items-per-page event should not emit immediately

---

packages/vuetify/src/components/VSkeletonLoader/VSkeletonLoader.sass

fixes #9447
playground
<details>
```vue
<template>
<v-container>
<v-skeleton-loader :loading="true" type="chip,list-item-avatar-two-line@8" />
</v-container>
</template>
```
</details>

fix(VSkeletonLoader): avatar is not rounded

---

packages/vuetify/src/components/VDataTable/Row.ts
packages/vuetify/src/components/VDataTable/VDataTableHeaderDesktop.ts
packages/vuetify/src/components/VDataTable/VSimpleTable.sass

after https://github.com/vuetifyjs/vuetify/pull/8297 old divider method of adding class to colspan was no longer working.
closes #8514, closes #7411
playground
<details>
```vue
<template>
<div>
<v-data-table
group-by="category"
show-group-by
fixed-header
height="400px"
<v-switch v-model="$vuetify.theme.dark" label="dark"></v-switch>
</div>
</template>
<script>
data () {
return {
headers: [
{ text: 'Id', value: 'id', divider: true },
{
align: 'left',
value: 'name',
},
{ text: 'Category', value: 'category' },
],
desserts: [
{
id: 0,
category: 'Ice cream',
},
{
id: 1,
category: 'Ice cream',
},
{
id: 2, …
```

fix(VDataTable): divider was not showing up

---

packages/vuetify/src/components/VDataTable/MobileRow.ts
packages/vuetify/src/components/VDataTable/VDataTable.sass
packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/MobileRow.spec.ts.snap

mobile rows had fixed height of 48px which made long texts overlap.
closes #8761
playground
<details>
```vue
<template>
<div>
<v-data-table
:items="items"
</div>
</template>
<script>
data () {
return {
headers: [
{
align: 'left',
value: 'name',
},
{ text: 'Iron (%)', value: 'iron' }
],
items: [
{
calories: 'Long string description Long string description Long string description Long string description Long string description ',
fat: 'Long string description Long string description Long string description Long string description Long string description …
```

fix(VDataTable): overlapping text in mobile rows

---

packages/vuetify/src/components/VExpansionPanel/VExpansionPanel.sass

fixes #9692
visually
<details>
```vue
<template>
<v-container>
<v-select label="Style" :items="['default', 'popout', 'inset']" v-model="style" />
<v-checkbox v-model="accordion" label="accordion" />
<v-expansion-panels
:popout="style === 'popout'"
:inset="style === 'inset'"
:accordion="accordion"
>
<v-expansion-panel v-for="i in 3" :key="`outer-${i}`">
<v-expansion-panel-header>Outer {{ i }}</v-expansion-panel-header>
<v-expansion-panel-content>
<v-expansion-panels>
<v-expansion-panel v-for="j in 3" :key="`inner-${j}`">
<v-expansion-panel-header>Inner {{ i }} / {{ j }}</v-expansion-panel-header>
<v-expansion-panel-content>Inner {{ i }} / {{ j }} content</v-expansion-panel-content>
</v-expansion-panel-content> …
```

fix(VExpansionPanels): outer panels styles cascade to inner panels

---

packages/vuetify/src/components/VGrid/_grid.sass

Similar to #8352 an image which have a larger width than the container itself breaks the design if the container uses the property `fill-height`.
The change solves design breaks. Maybe it solves related issues and can be seen as an enhancement for #9189.
visually
I've created a pen which demonstrates the issue and the solution: https://codepen.io/rwam/pen/LYYqjjJ
Short example which leads to the design break:
```html
<div id="app">
<v-app>
<v-content>
<v-container fill-height>
<v-img :src="'http://placehold.it/2800x170'" height="100px"></v-img>
</v-col>
</v-row>
</v-container>
</v-content>
</v-app>
</div>
```

fix(VGrid): add max-width for row in container and fill-height

---

packages/docs/src/snippets/js/testing_mock_vuetify_services.txt

Changed:
`import Breakpoint from 'vuetify/lib/services'` to `import { Breakpoint } from 'vuetify/lib/services'`
Currently if you follow the current doc it results in a `TypeError: _services.default is not a constructor` This is largely to due with the way that the service is exported without a default before the class.
I've tested this in local large projects of my team and also new simple instances of the vue/vuetify projects.
N/A

Docs - Unit Testing Breakpoint Import Fix

---

README.md

Broken link describing how to polyfill ie11, needs to be updated to the new browser support page
Broken link in docs for ie11 support
none
Support for IE11 / Safari 9 with [polyfill](https://vuetifyjs.com/getting-started/browser-support)

docs: fix broken ie11 polyfill link

---

packages/vuetify/src/components/VCalendar/VCalendar.ts
packages/vuetify/src/components/VCalendar/VCalendarDaily.sass
packages/vuetify/src/components/VCalendar/VCalendarDaily.ts
packages/vuetify/src/components/VCalendar/VCalendarWeekly.sass
packages/vuetify/src/components/VCalendar/VCalendarWeekly.ts
packages/vuetify/src/components/VCalendar/__tests__/__snapshots__/VCalendar.spec.ts.snap
packages/vuetify/src/components/VCalendar/__tests__/__snapshots__/VCalendarDaily.spec.ts.snap
packages/vuetify/src/components/VCalendar/_variables.scss
packages/vuetify/src/components/VCalendar/mixins/__tests__/calendar-with-events.spec.ts
packages/vuetify/src/components/VCalendar/mixins/__tests__/calendar-with-intervals.spec.ts
packages/vuetify/src/components/VCalendar/mixins/calendar-base.ts
packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.sass
packages/vuetify/src/components/VCalendar/mixins/calendar-with-events.ts
packages/vuetify/src/components/VCalendar/mixins/calendar-with-intervals.ts
packages/vuetify/src/components/VCalendar/util/props.ts

- Resolves #8429
- Resolves #7992
- Resolves #8870
- Resolves #9208
- Resolves #9154
- Resolves #8971
- Resolves #8525
- Resolves #8849
- Resolves #8342
- Resolves #8668
- Resolves #9114
<details>
```vue
<template>
<v-sheet class="v-fullscreen">
<v-toolbar fixed flat app color="white">
<v-btn outlined @click="setToday" class="mr-3">
Today
</v-btn>
<v-btn fab text small @click="prev">
<v-icon small>arrow_back_ios</v-icon>
</v-btn>
<v-btn fab text small @click="next">
<v-icon small>arrow_forward_ios</v-icon>
</v-btn>
<v-toolbar-title>{{ title }}</v-toolbar-title>
<v-menu bottom right>
<v-btn outlined v-on="on">
<span>{{ typeToLabel[type] }}</span>
<v-icon right>arrow_drop_down</v-icon>
</v-btn>
</template>
<v-list> …
```

fix(VCalendar): validation, style, slot, event, and format fixes

---

packages/vuetify/src/components/VWindow/VWindow.ts

Reverse internalReverse on RTL mode when it's horizontally
Similar to #8978 
visually | unit
https://codepen.io/dev0x0/pen/GRRLMVq

fix(VWindow): Fix Transition in RTL Mode

---

packages/api-generator/src/maps/v-data-table.js
packages/vuetify/src/components/VDataTable/VDataTable.ts

added to body slot props
added to click:row event
closes #8008
<details>
```vue
<template>
<v-data-table
:single-select="singleSelect"
show-select
@click:row="hello"
>
</template>
<script>
data () {
return {
singleSelect: false,
selected: [],
headers: [
{
align: 'left',
value: 'name',
},
],
desserts: [
{
calories: 159,
fat: 6.0,
carbs: 24,
protein: 4.0,
iron: '1%',
},
{ …
```

feat(VDataTable): expose expand/select functionality

---

packages/vuetify/src/components/VTreeview/VTreeview.sass
packages/vuetify/src/components/VTreeview/VTreeview.ts
packages/vuetify/src/components/VTreeview/VTreeviewNode.ts
packages/vuetify/src/components/VTreeview/__tests__/__snapshots__/VTreeview.spec.ts.snap
packages/vuetify/src/components/VTreeview/__tests__/__snapshots__/VTreeviewNode.spec.ts.snap
packages/vuetify/src/components/VTreeview/_variables.scss

this fix resulted in a slight internal refactor of the treeview node markup and sass, which is why it's targeted at dev instead of master.
closes #8212
playground
<details>
```vue
<template>
<div>
<v-switch v-model="dense" label="Dense"></v-switch>
<v-switch v-model="selectable" label="Selectable"></v-switch>
<v-switch v-model="activatable" label="Activatable"></v-switch>
<v-switch v-model="hoverable" label="Hoverable"></v-switch>
<v-switch v-model="shaped" label="Shaped"></v-switch>
<v-switch v-model="rounded" label="Rounded"></v-switch>
<v-switch v-model="openOnClick" label="Open on any item click"></v-switch>
<v-switch v-model="$vuetify.rtl" label="RTL"></v-switch>
<v-switch v-model="$vuetify.theme.dark" label="Dark"></v-switch> …
```

fix(VTreeview): incorrect alignment of nodes

---

packages/docs/src/lang/en/components/DataIterators.json
packages/vuetify/src/components/VDataIterator/VDataIterator.ts
packages/vuetify/src/components/VDataTable/VDataTable.ts
packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts
packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap

added new prop selectable-key to check if an item is selectable or not
if item has property with the name of the value of the selectable-key
prop and it is false, then item is not selectable.
selectable-key default value is "isSelectable"
rows that are not selectable have the checkbox disabled.
closes #8915
<details>
```vue
<template>
<v-data-table
:single-select="singleSelect"
show-select
</template>
<script>
data () {
return {
singleSelect: false,
selected: [],
headers: [
{
align: 'left',
value: 'name',
},
{ text: 'Carbs (g)', value: …
```

feat(VDataIterator): items can now be made unselectable

---

packages/vuetify/src/components/VCard/VCard.ts
packages/vuetify/src/components/VCard/__tests__/__snapshots__/VCard.spec.ts.snap

fixes #9889
<details>
```vue
<template>
<v-container>
<v-card loading>
<v-card-text>
<v-btn>Foo</v-btn>
</v-card-text>
</v-card>
</v-container>
</template>
```
</details>

fix(VCard): loading shouldn't disable the card

---

packages/vuetify/src/locale/tr.ts

Turkish translation update for Carousel
<details>
```vue
```
</details>
- [] I've added new examples to the kitchen (applies to new features and breaking changes in core library)

Updated Turkish translation for Carousel

---

packages/vuetify/types/services/icons.d.ts

add missing faSvg type to Iconfont
resolves #9995 
none

fix(icons): add missing faSvg type to Iconfont

---

packages/docs/src/examples/calendars/simple/weekly.vue

Renamed variable in weekly.vue
Misnamed variable in the script section causes the weekly component to crash
#9877 
Tested in codepen

Fixed crashing weekly.vue #9877

---

packages/vuetify/src/components/VAppBar/__tests__/__snapshots__/VAppBar.spec.ts.snap
packages/vuetify/src/components/VImg/VImg.ts
packages/vuetify/src/components/VImg/__tests__/__snapshots__/VImg.spec.ts.snap
packages/vuetify/src/components/VResponsive/VResponsive.sass
packages/vuetify/src/components/VResponsive/VResponsive.ts
packages/vuetify/src/components/VResponsive/__tests__/__snapshots__/VResponsive.spec.ts.snap

Alternate method of enforcing aspect ratio which works around buggy behavior in Firefox.
fixes #9659. @KaelWD 
Visually tested in Chrome, Firefox, and Safari. Has not been tested in IE11 or Edge.
<details>
```vue
<template>
<div id="app">
<div>
<v-text-field v-model="aspectRatio"></v-text-field>
<v-card>
<v-responsive :aspect-ratio="aspectRatio">
<v-card-text>
This card has the above aspect ratio
</v-card-text>
</v-responsive>
</v-card>
</div>
</v-app>
</div>
</template>
<script>
new Vue({
el: '#app',
vuetify: new Vuetify(),
data () { 
return {
aspectRatio: 16/9
}
}
})
</script>
```
</details>

fix(VResponsive): refactor VResponsive to work with Firefox

---

packages/docs/src/components/doc/ApiItem.vue

fix #10040
Change text color for Dark mode
visually
<details>
```vue
```
</details>

docs(apiitem.vue): set text text--secondary

---

packages/vuetify/src/components/VSelect/VSelectList.ts
packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect.spec.ts.snap
packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelect2.spec.ts.snap
packages/vuetify/src/components/VSelect/__tests__/__snapshots__/VSelectList.spec.ts.snap

Added an Index based ID avoiding duplication
fix #9819
Select options were being generated with duplicated id. It was fixed appending to the old ID already generated an Index.
Duplicated IDs aren't allowed in HTML. This PR fix #9819 
This was tested in the playground with developer tools.
<details>
```vue
<template>
<div id="app">
<v-row align="center">
<v-col class="d-flex" cols="12" sm="6">
<v-select
:items="items"
></v-select>
</v-col>
<v-col class="d-flex" cols="12" sm="6">
<v-select
:items="items"
filled
label="Filled style"
></v-select>
</v-col>
</v-row>
</v-container>
</v-app>
</div>
</template>
<script>
data: () => ({
items: ['Foo', 'Bar', 'Fizz', 'Buzz'],
}),
}
</script>
```
</details>

fix(VSelect): fix duplicated ID

---

LICENSE.md

Update license year.
Happy new year! :gift:

docs(LICENSE): update year

---

packages/api-generator/src/maps/v-data.js
packages/docs/src/lang/en/components/Data.json

add missing options prop example
closes #9048
manually
<details>
```vue
```
</details>

docs(VDataTable): add options prop example

---

packages/docs/src/examples/breadcrumbs/intermediate/item-slot.vue

Update v-breadcrumbs-item to use disabled prop instead of custom css styling.
#10073
visually
<details>
```vue
```
</details>

docs(vbreadcrumbs): update item slot example

---

packages/vuetify/src/components/VTextField/VTextField.ts

Limit the width of the label to the width of the field itself
Fixes #10030 
visually (using this template https://codepen.io/maylow/pen/GRgmJYv)

fix(VTextField): calculate label width depending on the textfield width

---

packages/vuetify/types/services/icons.d.ts

Due to Vuetify 2.2 new feature of using font awesome svg icons the `icons.d.ts` didn't get a proper update. This change just updates the typings for proper usage in TypeScript files.
none

fix(icons.d.ts): adapt icons.d.ts for proper faSvg usage in ts files

---

packages/vuetify/src/directives/ripple/index.ts

The wrong handler was being removed in removeListeners()
Improve performance with proper gc
Not tested

fix(v-ripple): remove the correct event listener

---

packages/vuetify/src/components/VList/VListGroup.sass

fix #10008
Add extra styles to VListGroup to prevent content overflow
#10008
Playground (using code from bug report codepen) | Visually
<details>
```vue
<template>
<v-container>
<v-card
width="300"
>
<v-list>
<v-list-item>
<v-icon>mdi-home</v-icon>
<v-list-item-title>Home with a really quite lengthy titie</v-list-item-title>
</v-list-item>
<v-list-group
prepend-icon="account_circle"
value="true"
>
<template v-slot:activator>
<v-list-item-title>Users</v-list-item-title>
</template>
<v-list-group
no-action
sub-group
value="true"
>
<template v-slot:activator>
<v-list-item-title>Admin, also with a long title that should be ellided</v-list-item-title>
</template>
<v-list-item
v-for="(admin, i) …
```

fix(VListGroup): added styles to prevent content overflow

---

packages/vuetify/src/components/VAvatar/VAvatar.sass

added a `overflow:hidden` to VAvatar fixes #10000
see issue #10000 
Tested the change in my project
<details>
https://codepen.io/ricardovanlaarhoven/pen/NWPdpgg
</details>

fix(VAvatar): add overflow:hidden

---

packages/docs/src/examples/time-pickers/simple/width.vue

This PR fixes the "Setting picker width" [example](https://vuetifyjs.com/en/components/time-pickers#setting-picker-width), which does not display correctly.
Before fix:
After fix:
The example is not displayed correctly.
visually
<details>
```vue
```
</details>

docs(VTimePicker): fix example layout

---

packages/vuetify/types/index.d.ts

Configuration options should export.
visually (Intelli Sense working)
```ts
import Vue from 'vue';
import Vuetify from 'vuetify/lib';
import { UserVuetifyPreset } from 'vuetify';
Vue.use(Vuetify);
const opts: Partial<UserVuetifyPreset> = {
theme: {
dark: false,
},
};
export default new Vuetify(opts);
```
</details>

fix(presets): export interfaces

---

packages/docs/src/examples/calendars/simple/weekly.vue

Renamed eventsMap to events in data object
Documentation example wasn't working.
</details>
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)
- [ x ] The PR title is no longer than 64 characters.
- [ x ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and breaking changes).
- [ x ] My code follows the code style of this project.

Fix simple/weekly v-calendar example not showing events

---

packages/docs/src/layouts/layouts/demos/google-contacts.vue

This was a very simple change.  I noticed the icons didn't display properly so I made the appropriate changes and chose two icons for the ones that I couldn't find at all.
It looks nicer and you don't get strange text when you load the contact form.
<details>
```vue
```
</details>
- [x ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

docs: update icons on google-contacts layout

---

packages/vuetify/src/components/VResponsive/VResponsive.sass

it's affected on the image component
fixes #10268
<details>
```vue
```
</details>

Fix responsive bug in RTL

---

packages/vuetify/src/components/VSnackbar/VSnackbar.sass
packages/vuetify/src/components/VSnackbar/VSnackbar.ts

This merge request improves the appearance of the Snackbar action button and makes the whole snackbar be properly announced by screen readers.
Focus states are obligatory for accessibility and the current action button does not have a focus state.
Also the screen reader should immediately announce a snackbar message when it shows up.
fixes #10047 
I have tested using NVDA and visually too.
<details>
```vue
<template>
<v-container>
<v-btn
dark
@click="snackbar = true"
>
Open Snackbar
</v-btn>
<v-snackbar
v-model="snackbar"
>
{{ text }}
<v-btn
text
@click="snackbar = false"
>
Hello
</v-btn>
</v-snackbar>
</v-container>
</template>
<script>
data: () => ({
snackbar: false,
text: 'Hello, I am a snackbar',
}),
}
</script>
```
</details>

fix(VSnackbar): a11y and appearance improvements

---

packages/docs/src/examples/sliders/simple/min-max.vue

resolves #10034
<details>
```vue
```
</details>

docs(VSlider): fix min-max example

---

packages/docs/src/snippets/js/webpack_sass_variables.txt

This has only document change.
```js
// webpack.config.js
module.exports = {
rules: [
...
]
}
```
```js
// webpack.config.js
module.exports = {
module: {
rules: [
...
]
},
}
```
<https://github.com/webpack-contrib/sass-loader/tree/03773152760434a2dd845008c504a09c0eb3fd91#getting-started>
<details>
```vue
```
</details>

docs(SASSVariables): fix .rules to module.rules

---

packages/vuetify/src/components/VDataTable/mixins/body.js
packages/vuetify/src/stylus/components/_data-table.styl
packages/vuetify/src/stylus/components/_tables.styl
packages/vuetify/src/stylus/settings/_theme.styl

Remove the extra border added to data tables with expanded rows enabled
fixed #6429 
Fixes an existing issue
https://github.com/vuetifyjs/vuetify/issues/6429
visually
<details>
```vue
<template>
<div id="app">
<v-container>
<v-data-table
:headers-length="6"
hide-headers
hide-actions
expand
>
<template v-slot:items="props">
<tr @click="props.expanded = !props.expanded">
<td class="text-xs-right">{{ props.item.iron }}</td>
</tr>
</template>
<template v-slot:expand> …
```

fix(VDatatable): remove extra border from expanded functionality

---

packages/vuetify/src/components/VTimePicker/VTimePickerClock.sass
packages/vuetify/src/components/VTimePicker/_variables.scss

playground
<details>
```vue
<template>
<v-time-picker
ref="p"
value="1:07"
/>
</template>
<script>
mounted () {
this.$refs.p.selecting = 2
}
}
</script>
```
</details>

fix(VTimePicker): missing end circle in clock hand

---

packages/docs/src/data/pages/getting-started/QuickStart.json

Fix the duplicate section of text in Font Installation that doesn't really make sense to be there.
I noticed that the Vuetify Quick Start documentation mentions changing stuff in main entry point under Font Installation.
I think this is a duplicate of a paragraph from the above section. Here is a screenshot showing the problem:
I think it should actually refer to the `index.html` section below (as changing the main.js for fonts doesn't make sense to me), so I got rid of the duplicate key and replaced it with the section that references `index.html`.

Remove duplicate section from Font Installation

---

packages/vuetify/src/components/VTimePicker/VTimePickerClock.ts
packages/vuetify/src/components/VTimePicker/__tests__/VTimePickerClock.spec.ts

fixes #7299
unit, playground
<details>
```vue
<template>
<v-container>
<v-time-picker
:allowed-minutes="v => v % 30 === 0"
:allowed-hours="v => v % 3 === 0"
/>
<v-time-picker />
</v-container>
</template>
```
</details>

fix(VTimePicker): increase clock click accuracy

---

packages/docs/src/lang/en/customization/Presets.json

https://dev.vuetifyjs.com > https://vuetifyjs.com
Resolves #10486 
<details>
```vue
```
</details>

docs(SASS) fix sass variables hyperlink

---

packages/vuetify/src/components/VDataTable/VDataTable.ts
packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts
packages/vuetify/src/components/VDataTable/__tests__/__snapshots__/VDataTable.spec.ts.snap

search should use raw headers instead of computed which have filtered out group-by column
closes #10392
<details>
```vue
<template>
<v-row>
<v-text-field v-model="searchForm" label="search"></v-text-field>
</v-row>
<v-data-table
:items="forms"
item-key="version_id"
:search="searchForm"
group-by="name"
show-select
</v-row>
</v-container>
</template>
<script>
data: () => ({
forms: [
{
name: 'Assistance',
form_id: 1,
version_id: 1,
version_number: 1,
},
{
name: 'Candidat',
form_id: 2,
version_id: 15,
version_number: 1,
},
{
name: 'Assistance',
form_id: 1,
version_id: 3,
version_number: 2,
},
{
name: 'Assistance',
form_id: 1,
version_id: 4,
version_number: 3,
},
{
name: …
```

fix(VDataTable): group-by column should be included in search

---

packages/docs/src/examples/steppers/usage.vue

fix #10614
resolves #10614 
https://github.com/vuetifyjs/vuetify/issues/10614
none
<details>
```vue
```
</details>

docs(stepper): fixed the usage example code

---

packages/vuetify/src/components/VData/VData.ts
packages/vuetify/src/components/VDataTable/__tests__/VDataTable.spec.ts

we didn't emit pagination when it was recalculated
closes #10212
<details>
```vue
<template>
<v-container>
<v-text-field
placeholder="Search"
hide-details
solo
<v-data-table
:page.sync="page"
:items-per-page="itemsPerPage"
@pagination="pagination = $event"
@page-count="pageCount = $event"
<v-pagination v-model="page" :length="pageCount" total-visible="7"></v-pagination>
<div>Items: {{ desserts.length }}</div>
<div>Pagination: {{ pagination }}</div>
<div>PageCount: {{ pageCount }}</div>
</v-container>
</template>
<script>
data: () => ({
search: '',
itemsPerPage: 5,
page: 1,
pageCount: 0,
pagination: {},
headers: [
{
text: …
```

fix(VDataTable): emit pagination event when filtering

---

packages/vuetify/src/components/VColorPicker/VColorPicker.ts
packages/vuetify/src/components/VColorPicker/__tests__/VColorPicker.spec.ts
packages/vuetify/src/components/VColorPicker/__tests__/__snapshots__/VColorPicker.spec.ts.snap
packages/vuetify/src/components/VColorPicker/util/index.ts

alpha input should be hidden if value prop does not include alpha information.
an exception is made for null/undefined value
closes #10402
<details>
```vue
<template>
<div>
<v-color-picker mode="rgba" v-model="color1"/>
<v-color-picker mode="rgba" v-model="color2"/>
<v-color-picker mode="rgba" v-model="color3"/>
<v-color-picker mode="rgba" v-model="color4"/>
<v-color-picker mode="rgba" v-model="color5"/>
</div>
</template>
<script>
data: () => ({
color1: null,
color2: '#FF00FF',
color3: '#FF00FFAA',
color4: { r: 10, g: 20, b: 30 },
color5: { r: 10, g: 20, b: 30, a: 1 },
}),
}
</script>
```
</details>

fix(VColorPicker): hide alpha input correctly

---

packages/api-generator/src/maps/v-simple-checkbox.js

The v-simple-checkbox currently emits an input event but the docs
currently state that it emits a click event
✅ Closes: #10681
Currently the docs state that the `v-simple-checkbox` component emits a `click` event when it actually emits an `input` event. Resolves #10681 
Resolves #10681 
<details>
```vue
```
</details>

docs(VSimpleCheckbox): Change click event input

---

packages/vuetify/src/components/VColorPicker/VColorPickerSwatches.sass

Swatch grid is off center. This is obvious when the swatch is small enough that it does not have a scrollbar. See swatch in current documentation
discovered while browsing lib
<details>
```vue
<template>
<v-container>
<v-row>
<v-col>
<v-color-picker class="ma-2" show-swatches></v-color-picker>
</v-col>
<v-col>
<v-color-picker class="ma-2" :swatches="swatches" show-swatches></v-color-picker>
</v-col>
<v-col>
<v-color-picker class="ma-2" show-swatches swatches-max-height="300px"></v-color-picker>
</v-col>
</v-row>
</v-container>
</template>
<script>
data: () => ({
swatches: [
['#FF0000', '#AA0000', '#550000'],
['#FFFF00', '#AAAA00', '#555500'],
['#00FF00', '#00AA00', '#005500'],
['#00FFFF', '#00AAAA', '#005555'],
['#0000FF', '#0000AA', '#000055'],
],
}),
}
</script>
``` …

fix(VColorPicker): center swatch grid

---

packages/vuetify/src/components/VColorPicker/VColorPickerEdit.sass
packages/vuetify/src/components/VColorPicker/VColorPickerPreview.sass
packages/vuetify/src/components/VColorPicker/VColorPickerPreview.ts
packages/vuetify/src/components/VColorPicker/_variables.scss

fixes #10655
playground
<details>
```vue
<template>
<v-container>
<v-btn
block
@click="$vuetify.rtl = !$vuetify.rtl"
>RTL {{ $vuetify.rtl }}</v-btn>
<v-color-picker />
</v-container>
</template>
<script>
created () {
},
}
</script>
```
</details>

fix(VColorPicker): incorrect layout in RTL mode

---

packages/docs/src/components/base/EnterpriseLink.vue
packages/docs/src/components/base/Item.vue
packages/docs/src/components/base/Markdown.vue
packages/docs/src/components/getting-started/WhyVuetify.vue
packages/docs/src/components/supporters/SponsorBtn.vue
packages/docs/src/layouts/frontend/AppBar.vue
packages/docs/src/mixins/meta.js
packages/docs/src/router/util.js
packages/docs/src/util/helpers.js
packages/docs/src/views/home/components/Feature.vue
packages/docs/src/views/home/components/Hero.vue
packages/docs/src/views/home/components/PremiumThemes.vue
packages/docs/src/views/home/components/Sponsors.vue

Ensured that all generated links contain language, leading and trailing slashes.
Links were not working properly with the new router:
* `en/namespace/page` Would concat onto route
* `/namespace/page` would cause a redirect to `/en/...`
* `/namespace/page#hash` would cause a redirect and lose the hash
* it's possible this one could be resolved within our router logic
Normalized parseLink generation since we have access to localStorage for the user.
visual

docs: fix language redirect

---

packages/docs/src/lang/en/framework/Icons.json

fix #10615
Documentation was pointing to the wrong branch (dev)
resolves #10615 
Seems like the issue was caused by a simple oversight during some refactoring process.
resolves #10615
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] The PR title is no longer than 64 characters.
- [ x ] The PR is submitted to the correct branch (`master` for bug fixes and documentation updates, `dev` for new features and backwards compatible changes and `next` for non-backwards compatible changes).
- [ x ] My code follows the code style of this project.

docs(icons): fix broken link
